--------------------------------------------------------
--  DDL for Procedure AP_PRODUCT_SETUP_ADP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "APPS"."AP_PRODUCT_SETUP_ADP" (A0 IN NUMBER,JB IN VARCHAR2,JC IN VARCHAR2,JD IN VARCHAR2,JF IN NUMBER,JG IN DATE,
JH IN VARCHAR2,JJ IN VARCHAR2,JK IN NUMBER,JL IN DATE,JM IN NUMBER,
JN IN VARCHAR2,JP IN NUMBER,JQ IN VARCHAR2,JR IN VARCHAR2,JS IN VARCHAR2,
JT IN VARCHAR2,JV IN VARCHAR2,JW IN VARCHAR2,JX IN NUMBER,JZ IN VARCHAR2,E0 IN NUMBER,RB IN VARCHAR2,RC IN VARCHAR2,RD IN VARCHAR2,RF IN NUMBER,RG IN DATE,
RH IN VARCHAR2,RJ IN VARCHAR2,RK IN NUMBER,RL IN DATE,RM IN NUMBER,
RN IN VARCHAR2,RP IN NUMBER,RQ IN VARCHAR2,RR IN VARCHAR2,RS IN VARCHAR2,
RT IN VARCHAR2,RV IN VARCHAR2,RW IN VARCHAR2,RX IN NUMBER,RZ IN VARCHAR2)
AS
NXT NUMBER;
CMT NUMBER;
NUSER varchar2(100);
newTRUE_NULLS VARCHAR2(250);
nls_date_fmt VARCHAR2(40);
BEGIN
select value into nls_date_fmt from v$NLS_PARAMETERS where parameter='NLS_DATE_FORMAT';
execute IMMEDIATE 'alter session set nls_date_format="MM/DD/YYYY HH24:MI:SS"';
NXT:=FND_AUDIT_SEQ_PKG.NXT;
CMT:=FND_AUDIT_SEQ_PKG.CMT;
NUSER:=FND_AUDIT_SEQ_PKG.USER_NAME;
SELECT decode(A0,NULL,'Y','N')
||decode(JB,NULL,'Y','N')
||decode(JC,NULL,'Y','N')
||decode(JD,NULL,'Y','N')
||decode(JF,NULL,'Y','N')
||decode(JG,NULL,'Y','N')
||decode(JH,NULL,'Y','N')
||decode(JJ,NULL,'Y','N')
||decode(JK,NULL,'Y','N')
||decode(JL,NULL,'Y','N')
||decode(JM,NULL,'Y','N')
||decode(JN,NULL,'Y','N')
||decode(JP,NULL,'Y','N')
||decode(JQ,NULL,'Y','N')
||decode(JR,NULL,'Y','N')
||decode(JS,NULL,'Y','N')
||decode(JT,NULL,'Y','N')
||decode(JV,NULL,'Y','N')
||decode(JW,NULL,'Y','N')
||decode(JX,NULL,'Y','N')
||decode(JZ,NULL,'Y','N') INTO newTRUE_NULLS FROM SYS.DUAL;
IF(newTRUE_NULLS='NNNNNNNNNNNNNNNNNNNNN') THEN 
newTRUE_NULLS:= NULL;
END IF;
INSERT INTO AP_PRODUCT_SETUP_A
VALUES(SYSDATE,'D',NUSER,newTRUE_NULLS,
USERENV('SESSIONID'),NXT,CMT,(TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'))*100000+MOD(NXT,100000)) * 100000 + USERENV('SESSIONID'),
A0,JB,JC,JD,JF,JG,
JH,JJ,JK,JL,JM,
JN,JP,JQ,JR,JS,
JT,JV,JW,JX,JZ);
execute IMMEDIATE 'alter session set nls_date_format="'||nls_date_fmt||'"';
END AP_PRODUCT_SETUP_ADP;

/
