--------------------------------------------------------
--  DDL for Package Body AME_ACL_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."AME_ACL_RKI" as
/* $Header: amaclrhi.pkb 120.1 2006/01/03 02:35 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:30:29 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_ACTION_ID in NUMBER
,P_LANGUAGE in VARCHAR2
,P_SOURCE_LANG in VARCHAR2
,P_DESCRIPTION in VARCHAR2
)is
begin
hr_utility.set_location('Entering: ame_acl_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: ame_acl_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end ame_acl_RKI;

/
