--------------------------------------------------------
--  DDL for Package Body AME_ITU_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."AME_ITU_RKI" as
/* $Header: amiturhi.pkb 120.6 2006/10/05 16:11:40 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:30:38 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EFFECTIVE_DATE in DATE
,P_VALIDATION_START_DATE in DATE
,P_VALIDATION_END_DATE in DATE
,P_APPLICATION_ID in NUMBER
,P_ITEM_CLASS_ID in NUMBER
,P_ITEM_ID_QUERY in VARCHAR2
,P_ITEM_CLASS_ORDER_NUMBER in NUMBER
,P_ITEM_CLASS_PAR_MODE in VARCHAR2
,P_ITEM_CLASS_SUBLIST_MODE in VARCHAR2
,P_START_DATE in DATE
,P_END_DATE in DATE
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: AME_ITU_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: AME_ITU_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end AME_ITU_RKI;

/
