--------------------------------------------------------
--  DDL for Package Body AME_RTL_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."AME_RTL_RKI" as
/* $Header: amrtlrhi.pkb 120.0 2005/09/02 04:02 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:30:39 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_RULE_ID in NUMBER
,P_LANGUAGE in VARCHAR2
,P_SOURCE_LANG in VARCHAR2
,P_DESCRIPTION in VARCHAR2
)is
begin
hr_utility.set_location('Entering: AME_RTL_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: AME_RTL_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end AME_RTL_RKI;

/
