--------------------------------------------------------
--  DDL for Package Body AME_CAL_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."AME_CAL_RKI" as
/* $Header: amcalrhi.pkb 120.2 2006/01/03 22:52 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:30:34 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_APPLICATION_ID in NUMBER
,P_LANGUAGE in VARCHAR2
,P_SOURCE_LANG in VARCHAR2
,P_APPLICATION_NAME in VARCHAR2
)is
begin
hr_utility.set_location('Entering: AME_CAL_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: AME_CAL_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end AME_CAL_RKI;

/
