--------------------------------------------------------
--  DDL for Package Body AME_CNU_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."AME_CNU_RKI" as
/* $Header: amcnurhi.pkb 120.4 2005/11/22 03:15 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:30:35 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EFFECTIVE_DATE in DATE
,P_VALIDATION_START_DATE in DATE
,P_VALIDATION_END_DATE in DATE
,P_RULE_ID in NUMBER
,P_CONDITION_ID in NUMBER
,P_START_DATE in DATE
,P_END_DATE in DATE
,P_SECURITY_GROUP_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: ame_cnu_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: ame_cnu_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end ame_cnu_RKI;

/
