--------------------------------------------------------
--  DDL for Package Body AME_CNU_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."AME_CNU_RKU" as
/* $Header: amcnurhi.pkb 120.4 2005/11/22 03:15 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:30:35 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
,P_VALIDATION_START_DATE in DATE
,P_VALIDATION_END_DATE in DATE
,P_RULE_ID in NUMBER
,P_CONDITION_ID in NUMBER
,P_START_DATE in DATE
,P_END_DATE in DATE
,P_SECURITY_GROUP_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_START_DATE_O in DATE
,P_END_DATE_O in DATE
,P_SECURITY_GROUP_ID_O in NUMBER
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: ame_cnu_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: ame_cnu_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end ame_cnu_RKU;

/
