--------------------------------------------------------
--  DDL for Package Body AMW_ASSESSMENTS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."AMW_ASSESSMENTS_PKG" as
/* $Header: amwvassb.pls 120.0 2005/05/31 18:39:29 appldev noship $ */
procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_ASSESSMENT_ID in NUMBER,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_SECURITY_GROUP_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_EFFECTIVE_COMPLETION_DATE in DATE,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ASSESSMENT_TYPE_CODE in VARCHAR2,
  X_ASSESSMENT_OWNER_ID in NUMBER,
  X_IES_SURVEY_ID in NUMBER,
  X_IES_CYCLE_ID in NUMBER,
  X_IES_DEPLOYMENT_ID in NUMBER,
  X_ASSESSMENT_STATUS_CODE in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_START_DATE in DATE,
  X_PERIOD_NAME in VARCHAR2
) is
  cursor C is select ROWID from AMW_ASSESSMENTS_B
    where ASSESSMENT_ID = X_ASSESSMENT_ID;

  l_start_date  DATE;
begin
  -- 12.16.2003 tsho: update start_date if status_code becomes 'P' (In Progress)
  if (X_START_DATE is null AND X_ASSESSMENT_STATUS_CODE='P') then
    l_start_date := SYSDATE;
  else
    l_start_date := X_START_DATE;
  end if;

  insert into AMW_ASSESSMENTS_B (
    ATTRIBUTE15,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    SECURITY_GROUP_ID,
    OBJECT_VERSION_NUMBER,
    EFFECTIVE_COMPLETION_DATE,
    ATTRIBUTE7,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ASSESSMENT_ID,
    ASSESSMENT_TYPE_CODE,
    ASSESSMENT_OWNER_ID,
    IES_SURVEY_ID,
    IES_CYCLE_ID,
    IES_DEPLOYMENT_ID,
    ASSESSMENT_STATUS_CODE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    START_DATE,
    PERIOD_NAME
  ) values (
    X_ATTRIBUTE15,
    X_ATTRIBUTE8,
    X_ATTRIBUTE9,
    X_ATTRIBUTE10,
    X_ATTRIBUTE11,
    X_ATTRIBUTE12,
    X_ATTRIBUTE13,
    X_ATTRIBUTE14,
    X_SECURITY_GROUP_ID,
    X_OBJECT_VERSION_NUMBER,
    X_EFFECTIVE_COMPLETION_DATE,
    X_ATTRIBUTE7,
    X_ATTRIBUTE3,
    X_ATTRIBUTE4,
    X_ATTRIBUTE5,
    X_ATTRIBUTE6,
    X_ASSESSMENT_ID,
    X_ASSESSMENT_TYPE_CODE,
    X_ASSESSMENT_OWNER_ID,
    X_IES_SURVEY_ID,
    X_IES_CYCLE_ID,
    X_IES_DEPLOYMENT_ID,
    X_ASSESSMENT_STATUS_CODE,
    X_ATTRIBUTE_CATEGORY,
    X_ATTRIBUTE1,
    X_ATTRIBUTE2,
    X_CREATION_DATE,
    X_CREATED_BY,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN,
    l_start_date, -- 12.16.2003 tsho: use l_start_date instead of X_START_DATE
    X_PERIOD_NAME
  );

  insert into AMW_ASSESSMENTS_TL (
    LAST_UPDATE_LOGIN,
    ASSESSMENT_ID,
    NAME,
    DESCRIPTION,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    SECURITY_GROUP_ID,
    LANGUAGE,
    SOURCE_LANG
  ) select
    X_LAST_UPDATE_LOGIN,
    X_ASSESSMENT_ID,
    X_NAME,
    X_DESCRIPTION,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY,
    X_CREATION_DATE,
    X_CREATED_BY,
    X_SECURITY_GROUP_ID,
    L.LANGUAGE_CODE,
    userenv('LANG')
  from FND_LANGUAGES L
  where L.INSTALLED_FLAG in ('I', 'B')
  and not exists
    (select NULL
    from AMW_ASSESSMENTS_TL T
    where T.ASSESSMENT_ID = X_ASSESSMENT_ID
    and T.LANGUAGE = L.LANGUAGE_CODE);

  open c;
  fetch c into X_ROWID;
  if (c%notfound) then
    close c;
    raise no_data_found;
  end if;
  close c;

end INSERT_ROW;

procedure LOCK_ROW (
  X_ASSESSMENT_ID in NUMBER,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_SECURITY_GROUP_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_EFFECTIVE_COMPLETION_DATE in DATE,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ASSESSMENT_TYPE_CODE in VARCHAR2,
  X_ASSESSMENT_OWNER_ID in NUMBER,
  X_IES_SURVEY_ID in NUMBER,
  X_IES_CYCLE_ID in NUMBER,
  X_IES_DEPLOYMENT_ID in NUMBER,
  X_ASSESSMENT_STATUS_CODE in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_START_DATE in DATE,
  X_PERIOD_NAME in VARCHAR2
) is
  cursor c is select
      ATTRIBUTE15,
      ATTRIBUTE8,
      ATTRIBUTE9,
      ATTRIBUTE10,
      ATTRIBUTE11,
      ATTRIBUTE12,
      ATTRIBUTE13,
      ATTRIBUTE14,
      SECURITY_GROUP_ID,
      OBJECT_VERSION_NUMBER,
      EFFECTIVE_COMPLETION_DATE,
      ATTRIBUTE7,
      ATTRIBUTE3,
      ATTRIBUTE4,
      ATTRIBUTE5,
      ATTRIBUTE6,
      ASSESSMENT_TYPE_CODE,
      ASSESSMENT_OWNER_ID,
      IES_SURVEY_ID,
      IES_CYCLE_ID,
      IES_DEPLOYMENT_ID,
      ASSESSMENT_STATUS_CODE,
      ATTRIBUTE_CATEGORY,
      ATTRIBUTE1,
      ATTRIBUTE2,
      START_DATE,
      PERIOD_NAME
    from AMW_ASSESSMENTS_B
    where ASSESSMENT_ID = X_ASSESSMENT_ID
    for update of ASSESSMENT_ID nowait;
  recinfo c%rowtype;

  cursor c1 is select
      NAME,
      DESCRIPTION,
      decode(LANGUAGE, userenv('LANG'), 'Y', 'N') BASELANG
    from AMW_ASSESSMENTS_TL
    where ASSESSMENT_ID = X_ASSESSMENT_ID
    and userenv('LANG') in (LANGUAGE, SOURCE_LANG)
    for update of ASSESSMENT_ID nowait;
begin
  open c;
  fetch c into recinfo;
  if (c%notfound) then
    close c;
    fnd_message.set_name('FND', 'FORM_RECORD_DELETED');
    app_exception.raise_exception;
  end if;
  close c;
  if (    ((recinfo.ATTRIBUTE15 = X_ATTRIBUTE15)
           OR ((recinfo.ATTRIBUTE15 is null) AND (X_ATTRIBUTE15 is null)))
      AND ((recinfo.ATTRIBUTE8 = X_ATTRIBUTE8)
           OR ((recinfo.ATTRIBUTE8 is null) AND (X_ATTRIBUTE8 is null)))
      AND ((recinfo.ATTRIBUTE9 = X_ATTRIBUTE9)
           OR ((recinfo.ATTRIBUTE9 is null) AND (X_ATTRIBUTE9 is null)))
      AND ((recinfo.ATTRIBUTE10 = X_ATTRIBUTE10)
           OR ((recinfo.ATTRIBUTE10 is null) AND (X_ATTRIBUTE10 is null)))
      AND ((recinfo.ATTRIBUTE11 = X_ATTRIBUTE11)
           OR ((recinfo.ATTRIBUTE11 is null) AND (X_ATTRIBUTE11 is null)))
      AND ((recinfo.ATTRIBUTE12 = X_ATTRIBUTE12)
           OR ((recinfo.ATTRIBUTE12 is null) AND (X_ATTRIBUTE12 is null)))
      AND ((recinfo.ATTRIBUTE13 = X_ATTRIBUTE13)
           OR ((recinfo.ATTRIBUTE13 is null) AND (X_ATTRIBUTE13 is null)))
      AND ((recinfo.ATTRIBUTE14 = X_ATTRIBUTE14)
           OR ((recinfo.ATTRIBUTE14 is null) AND (X_ATTRIBUTE14 is null)))
      AND ((recinfo.SECURITY_GROUP_ID = X_SECURITY_GROUP_ID)
           OR ((recinfo.SECURITY_GROUP_ID is null) AND (X_SECURITY_GROUP_ID is null)))
      AND ((recinfo.OBJECT_VERSION_NUMBER = X_OBJECT_VERSION_NUMBER)
           OR ((recinfo.OBJECT_VERSION_NUMBER is null) AND (X_OBJECT_VERSION_NUMBER is null)))
      AND ((recinfo.EFFECTIVE_COMPLETION_DATE = X_EFFECTIVE_COMPLETION_DATE)
           OR ((recinfo.EFFECTIVE_COMPLETION_DATE is null) AND (X_EFFECTIVE_COMPLETION_DATE is null)))
      AND ((recinfo.ATTRIBUTE7 = X_ATTRIBUTE7)
           OR ((recinfo.ATTRIBUTE7 is null) AND (X_ATTRIBUTE7 is null)))
      AND ((recinfo.ATTRIBUTE3 = X_ATTRIBUTE3)
           OR ((recinfo.ATTRIBUTE3 is null) AND (X_ATTRIBUTE3 is null)))
      AND ((recinfo.ATTRIBUTE4 = X_ATTRIBUTE4)
           OR ((recinfo.ATTRIBUTE4 is null) AND (X_ATTRIBUTE4 is null)))
      AND ((recinfo.ATTRIBUTE5 = X_ATTRIBUTE5)
           OR ((recinfo.ATTRIBUTE5 is null) AND (X_ATTRIBUTE5 is null)))
      AND ((recinfo.ATTRIBUTE6 = X_ATTRIBUTE6)
           OR ((recinfo.ATTRIBUTE6 is null) AND (X_ATTRIBUTE6 is null)))
      AND (recinfo.ASSESSMENT_TYPE_CODE = X_ASSESSMENT_TYPE_CODE)
      AND ((recinfo.ASSESSMENT_OWNER_ID = X_ASSESSMENT_OWNER_ID)
           OR ((recinfo.ASSESSMENT_OWNER_ID is null) AND (X_ASSESSMENT_OWNER_ID is null)))
      AND ((recinfo.IES_SURVEY_ID = X_IES_SURVEY_ID)
           OR ((recinfo.IES_SURVEY_ID is null) AND (X_IES_SURVEY_ID is null)))
      AND ((recinfo.IES_CYCLE_ID = X_IES_CYCLE_ID)
           OR ((recinfo.IES_CYCLE_ID is null) AND (X_IES_CYCLE_ID is null)))
      AND ((recinfo.IES_DEPLOYMENT_ID = X_IES_DEPLOYMENT_ID)
           OR ((recinfo.IES_DEPLOYMENT_ID is null) AND (X_IES_DEPLOYMENT_ID is null)))
      AND (recinfo.ASSESSMENT_STATUS_CODE = X_ASSESSMENT_STATUS_CODE)
      AND ((recinfo.ATTRIBUTE_CATEGORY = X_ATTRIBUTE_CATEGORY)
           OR ((recinfo.ATTRIBUTE_CATEGORY is null) AND (X_ATTRIBUTE_CATEGORY is null)))
      AND ((recinfo.ATTRIBUTE1 = X_ATTRIBUTE1)
           OR ((recinfo.ATTRIBUTE1 is null) AND (X_ATTRIBUTE1 is null)))
      AND ((recinfo.ATTRIBUTE2 = X_ATTRIBUTE2)
           OR ((recinfo.ATTRIBUTE2 is null) AND (X_ATTRIBUTE2 is null)))
      AND ((recinfo.PERIOD_NAME = X_PERIOD_NAME)
           OR ((recinfo.PERIOD_NAME is null) AND (X_PERIOD_NAME is null)))
  ) then
    null;
  else
    fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
    app_exception.raise_exception;
  end if;

  for tlinfo in c1 loop
    if (tlinfo.BASELANG = 'Y') then
      if (    (tlinfo.NAME = X_NAME)
          AND ((tlinfo.DESCRIPTION = X_DESCRIPTION)
               OR ((tlinfo.DESCRIPTION is null) AND (X_DESCRIPTION is null)))
      ) then
        null;
      else
        fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
        app_exception.raise_exception;
      end if;
    end if;
  end loop;
  return;
end LOCK_ROW;

procedure UPDATE_ROW (
  X_ASSESSMENT_ID in NUMBER,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_SECURITY_GROUP_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_EFFECTIVE_COMPLETION_DATE in DATE,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ASSESSMENT_TYPE_CODE in VARCHAR2,
  X_ASSESSMENT_OWNER_ID in NUMBER,
  X_IES_SURVEY_ID in NUMBER,
  X_IES_CYCLE_ID in NUMBER,
  X_IES_DEPLOYMENT_ID in NUMBER,
  X_ASSESSMENT_STATUS_CODE in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_START_DATE in DATE,
  X_PERIOD_NAME in VARCHAR2
) is
  l_start_date  DATE;

begin
  -- 12.16.2003 tsho: update start_date if status_code becomes 'P' (In Progress)
  if (X_START_DATE is null AND X_ASSESSMENT_STATUS_CODE='P') then
    l_start_date := SYSDATE;
  else
    l_start_date := X_START_DATE;
  end if;

  update AMW_ASSESSMENTS_B set
    ATTRIBUTE15 = X_ATTRIBUTE15,
    ATTRIBUTE8 = X_ATTRIBUTE8,
    ATTRIBUTE9 = X_ATTRIBUTE9,
    ATTRIBUTE10 = X_ATTRIBUTE10,
    ATTRIBUTE11 = X_ATTRIBUTE11,
    ATTRIBUTE12 = X_ATTRIBUTE12,
    ATTRIBUTE13 = X_ATTRIBUTE13,
    ATTRIBUTE14 = X_ATTRIBUTE14,
    SECURITY_GROUP_ID = X_SECURITY_GROUP_ID,
    OBJECT_VERSION_NUMBER = X_OBJECT_VERSION_NUMBER,
    EFFECTIVE_COMPLETION_DATE = X_EFFECTIVE_COMPLETION_DATE,
    ATTRIBUTE7 = X_ATTRIBUTE7,
    ATTRIBUTE3 = X_ATTRIBUTE3,
    ATTRIBUTE4 = X_ATTRIBUTE4,
    ATTRIBUTE5 = X_ATTRIBUTE5,
    ATTRIBUTE6 = X_ATTRIBUTE6,
    ASSESSMENT_TYPE_CODE = X_ASSESSMENT_TYPE_CODE,
    ASSESSMENT_OWNER_ID = X_ASSESSMENT_OWNER_ID,
    IES_SURVEY_ID = X_IES_SURVEY_ID,
    IES_CYCLE_ID = X_IES_CYCLE_ID,
    IES_DEPLOYMENT_ID = X_IES_DEPLOYMENT_ID,
    ASSESSMENT_STATUS_CODE = X_ASSESSMENT_STATUS_CODE,
    ATTRIBUTE_CATEGORY = X_ATTRIBUTE_CATEGORY,
    ATTRIBUTE1 = X_ATTRIBUTE1,
    ATTRIBUTE2 = X_ATTRIBUTE2,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN,
    START_DATE = l_start_date, -- 12.16.2003 tsho: use l_start_date instead of X_START_DATE
    PERIOD_NAME = X_PERIOD_NAME
  where ASSESSMENT_ID = X_ASSESSMENT_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;

  update AMW_ASSESSMENTS_TL set
    NAME = X_NAME,
    DESCRIPTION = X_DESCRIPTION,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN,
    SOURCE_LANG = userenv('LANG')
  where ASSESSMENT_ID = X_ASSESSMENT_ID
  and userenv('LANG') in (LANGUAGE, SOURCE_LANG);

  if (sql%notfound) then
    raise no_data_found;
  end if;
end UPDATE_ROW;

procedure DELETE_ROW (
  X_ASSESSMENT_ID in NUMBER
) is
begin
  delete from AMW_ASSESSMENTS_TL
  where ASSESSMENT_ID = X_ASSESSMENT_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;

  delete from AMW_ASSESSMENTS_B
  where ASSESSMENT_ID = X_ASSESSMENT_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;
end DELETE_ROW;

procedure ADD_LANGUAGE
is
begin
  delete from AMW_ASSESSMENTS_TL T
  where not exists
    (select NULL
    from AMW_ASSESSMENTS_B B
    where B.ASSESSMENT_ID = T.ASSESSMENT_ID
    );

  update AMW_ASSESSMENTS_TL T set (
      NAME,
      DESCRIPTION
    ) = (select
      B.NAME,
      B.DESCRIPTION
    from AMW_ASSESSMENTS_TL B
    where B.ASSESSMENT_ID = T.ASSESSMENT_ID
    and B.LANGUAGE = T.SOURCE_LANG)
  where (
      T.ASSESSMENT_ID,
      T.LANGUAGE
  ) in (select
      SUBT.ASSESSMENT_ID,
      SUBT.LANGUAGE
    from AMW_ASSESSMENTS_TL SUBB, AMW_ASSESSMENTS_TL SUBT
    where SUBB.ASSESSMENT_ID = SUBT.ASSESSMENT_ID
    and SUBB.LANGUAGE = SUBT.SOURCE_LANG
    and (SUBB.NAME <> SUBT.NAME
      or SUBB.DESCRIPTION <> SUBT.DESCRIPTION
      or (SUBB.DESCRIPTION is null and SUBT.DESCRIPTION is not null)
      or (SUBB.DESCRIPTION is not null and SUBT.DESCRIPTION is null)
  ));

  insert into AMW_ASSESSMENTS_TL (
    LAST_UPDATE_LOGIN,
    ASSESSMENT_ID,
    NAME,
    DESCRIPTION,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    SECURITY_GROUP_ID,
    LANGUAGE,
    SOURCE_LANG
  ) select
    B.LAST_UPDATE_LOGIN,
    B.ASSESSMENT_ID,
    B.NAME,
    B.DESCRIPTION,
    B.LAST_UPDATE_DATE,
    B.LAST_UPDATED_BY,
    B.CREATION_DATE,
    B.CREATED_BY,
    B.SECURITY_GROUP_ID,
    L.LANGUAGE_CODE,
    B.SOURCE_LANG
  from AMW_ASSESSMENTS_TL B, FND_LANGUAGES L
  where L.INSTALLED_FLAG in ('I', 'B')
  and B.LANGUAGE = userenv('LANG')
  and not exists
    (select NULL
    from AMW_ASSESSMENTS_TL T
    where T.ASSESSMENT_ID = B.ASSESSMENT_ID
    and T.LANGUAGE = L.LANGUAGE_CODE);
end ADD_LANGUAGE;

end AMW_ASSESSMENTS_PKG;


/
