--------------------------------------------------------
--  DDL for Package Body BEN_POPL_YR_PERD_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_POPL_YR_PERD_BK3" as
/* $Header: becpyapi.pkb 115.3 2002/12/13 06:52:18 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:38:19 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_POPL_YR_PERD_A
(P_POPL_YR_PERD_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: BEN_POPL_YR_PERD_BK3.DELETE_POPL_YR_PERD_A', 10);
hr_utility.set_location(' Leaving: BEN_POPL_YR_PERD_BK3.DELETE_POPL_YR_PERD_A', 20);
end DELETE_POPL_YR_PERD_A;
procedure DELETE_POPL_YR_PERD_B
(P_POPL_YR_PERD_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: BEN_POPL_YR_PERD_BK3.DELETE_POPL_YR_PERD_B', 10);
hr_utility.set_location(' Leaving: BEN_POPL_YR_PERD_BK3.DELETE_POPL_YR_PERD_B', 20);
end DELETE_POPL_YR_PERD_B;
end BEN_POPL_YR_PERD_BK3;

/
