--------------------------------------------------------
--  DDL for Package Body BEN_PIL_ASSIGNMENT_BK2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_PIL_ASSIGNMENT_BK2" as
/*  $Header: bepsgapi.pkb 120.0 2005/09/29 06:20:39 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:40:41 (YYYY/MM/DD HH24:MI:SS)
procedure UPDATE_PIL_ASSIGNMENT_A
(P_PIL_ASSIGNMENT_ID in NUMBER
,P_PER_IN_LER_ID in NUMBER
,P_APPLICANT_ASSIGNMENT_ID in NUMBER
,P_OFFER_ASSIGNMENT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: BEN_PIL_ASSIGNMENT_BK2.UPDATE_PIL_ASSIGNMENT_A', 10);
hr_utility.set_location(' Leaving: BEN_PIL_ASSIGNMENT_BK2.UPDATE_PIL_ASSIGNMENT_A', 20);
end UPDATE_PIL_ASSIGNMENT_A;
procedure UPDATE_PIL_ASSIGNMENT_B
(P_PIL_ASSIGNMENT_ID in NUMBER
,P_PER_IN_LER_ID in NUMBER
,P_APPLICANT_ASSIGNMENT_ID in NUMBER
,P_OFFER_ASSIGNMENT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: BEN_PIL_ASSIGNMENT_BK2.UPDATE_PIL_ASSIGNMENT_B', 10);
hr_utility.set_location(' Leaving: BEN_PIL_ASSIGNMENT_BK2.UPDATE_PIL_ASSIGNMENT_B', 20);
end UPDATE_PIL_ASSIGNMENT_B;
end BEN_PIL_ASSIGNMENT_BK2;

/
