--------------------------------------------------------
--  DDL for Package Body BEN_ELIG_OBJ_BK2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_ELIG_OBJ_BK2" as
/* $Header: bebeoapi.pkb 120.0 2005/05/28 00:38:26 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:37:39 (YYYY/MM/DD HH24:MI:SS)
procedure UPDATE_ELIG_OBJ_A
(P_ELIG_OBJ_ID in NUMBER
,P_EFFECTIVE_START_DATE in DATE
,P_EFFECTIVE_END_DATE in DATE
,P_BUSINESS_GROUP_ID in NUMBER
,P_TABLE_NAME in VARCHAR2
,P_COLUMN_NAME in VARCHAR2
,P_COLUMN_VALUE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_ELIG_OBJ_BK2.UPDATE_ELIG_OBJ_A', 10);
hr_utility.set_location(' Leaving: BEN_ELIG_OBJ_BK2.UPDATE_ELIG_OBJ_A', 20);
end UPDATE_ELIG_OBJ_A;
procedure UPDATE_ELIG_OBJ_B
(P_ELIG_OBJ_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_TABLE_NAME in VARCHAR2
,P_COLUMN_NAME in VARCHAR2
,P_COLUMN_VALUE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_ELIG_OBJ_BK2.UPDATE_ELIG_OBJ_B', 10);
hr_utility.set_location(' Leaving: BEN_ELIG_OBJ_BK2.UPDATE_ELIG_OBJ_B', 20);
end UPDATE_ELIG_OBJ_B;
end BEN_ELIG_OBJ_BK2;

/
