--------------------------------------------------------
--  DDL for Package Body BEN_BPI_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_BPI_RKI" as
/* $Header: bebpirhi.pkb 115.5 2002/12/16 11:53:30 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:37:47 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_BATCH_PROC_ID in NUMBER
,P_BENEFIT_ACTION_ID in NUMBER
,P_STRT_DT in DATE
,P_END_DT in DATE
,P_STRT_TM in VARCHAR2
,P_END_TM in VARCHAR2
,P_ELPSD_TM in VARCHAR2
,P_PER_SLCTD in NUMBER
,P_PER_PROC in NUMBER
,P_PER_UNPROC in NUMBER
,P_PER_PROC_SUCC in NUMBER
,P_PER_ERR in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: ben_bpi_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: ben_bpi_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end ben_bpi_RKI;

/
