--------------------------------------------------------
--  DDL for Package Body BEN_XCC_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_XCC_RKU" as
/* $Header: bexccrhi.pkb 120.1 2005/10/31 11:39:19 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:41:06 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_EXT_CRIT_CMBN_ID in NUMBER
,P_CRIT_TYP_CD in VARCHAR2
,P_OPER_CD in VARCHAR2
,P_VAL_1 in VARCHAR2
,P_VAL_2 in VARCHAR2
,P_EXT_CRIT_VAL_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_CRIT_TYP_CD_O in VARCHAR2
,P_OPER_CD_O in VARCHAR2
,P_VAL_1_O in VARCHAR2
,P_VAL_2_O in VARCHAR2
,P_EXT_CRIT_VAL_ID_O in NUMBER
,P_BUSINESS_GROUP_ID_O in NUMBER
,P_LEGISLATION_CODE_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: ben_xcc_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: ben_xcc_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end ben_xcc_RKU;

/
