--------------------------------------------------------
--  DDL for Package Body BEN_PRMRY_CARE_PRVDR_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_PRMRY_CARE_PRVDR_BK3" as
/* $Header: bepprapi.pkb 120.2.12000000.1 2007/01/19 21:49:49 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/10/10 13:32:32 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_PRMRY_CARE_PRVDR_A
(P_PRMRY_CARE_PRVDR_ID in NUMBER
,P_EFFECTIVE_START_DATE in DATE
,P_EFFECTIVE_END_DATE in DATE
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_PRMRY_CARE_PRVDR_BK3.DELETE_PRMRY_CARE_PRVDR_A', 10);
hr_utility.set_location(' Leaving: BEN_PRMRY_CARE_PRVDR_BK3.DELETE_PRMRY_CARE_PRVDR_A', 20);
end DELETE_PRMRY_CARE_PRVDR_A;
procedure DELETE_PRMRY_CARE_PRVDR_B
(P_PRMRY_CARE_PRVDR_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_PRMRY_CARE_PRVDR_BK3.DELETE_PRMRY_CARE_PRVDR_B', 10);
hr_utility.set_location(' Leaving: BEN_PRMRY_CARE_PRVDR_BK3.DELETE_PRMRY_CARE_PRVDR_B', 20);
end DELETE_PRMRY_CARE_PRVDR_B;
end BEN_PRMRY_CARE_PRVDR_BK3;

/
