--------------------------------------------------------
--  DDL for Package Body BEN_PL_BNF_CTFN_PRVDD_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_PL_BNF_CTFN_PRVDD_BK3" as
/* $Header: bepbcapi.pkb 120.1 2006/05/03 01:19:31 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:40:05 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_PL_BNF_CTFN_PRVDD_A
(P_PL_BNF_CTFN_PRVDD_ID in NUMBER
,P_EFFECTIVE_START_DATE in DATE
,P_EFFECTIVE_END_DATE in DATE
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_PL_BNF_CTFN_PRVDD_BK3.DELETE_PL_BNF_CTFN_PRVDD_A', 10);
hr_utility.set_location(' Leaving: BEN_PL_BNF_CTFN_PRVDD_BK3.DELETE_PL_BNF_CTFN_PRVDD_A', 20);
end DELETE_PL_BNF_CTFN_PRVDD_A;
procedure DELETE_PL_BNF_CTFN_PRVDD_B
(P_PL_BNF_CTFN_PRVDD_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_PL_BNF_CTFN_PRVDD_BK3.DELETE_PL_BNF_CTFN_PRVDD_B', 10);
hr_utility.set_location(' Leaving: BEN_PL_BNF_CTFN_PRVDD_BK3.DELETE_PL_BNF_CTFN_PRVDD_B', 20);
end DELETE_PL_BNF_CTFN_PRVDD_B;
end BEN_PL_BNF_CTFN_PRVDD_BK3;

/
