--------------------------------------------------------
--  DDL for Package Body BEN_XID_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_XID_RKU" as
/* $Header: bexidrhi.pkb 115.7 2002/12/16 07:24:29 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:41:12 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_EXT_INCL_DATA_ELMT_ID in NUMBER
,P_EXT_RCD_IN_FILE_ID in NUMBER
,P_EXT_DATA_ELMT_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EXT_DATA_ELMT_IN_RCD_ID in NUMBER
,P_EXT_RCD_IN_FILE_ID_O in NUMBER
,P_EXT_DATA_ELMT_ID_O in NUMBER
,P_BUSINESS_GROUP_ID_O in NUMBER
,P_LEGISLATION_CODE_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
,P_EXT_DATA_ELMT_IN_RCD_ID_O in NUMBER
)is
begin
hr_utility.set_location('Entering: ben_xid_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: ben_xid_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end ben_xid_RKU;

/
