--------------------------------------------------------
--  DDL for Package Body BEN_XIC_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_XIC_RKD" as
/* $Header: bexicrhi.pkb 120.2 2006/03/20 13:02:22 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:41:12 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_EXT_INCL_CHG_ID in NUMBER
,P_CHG_EVT_CD_O in VARCHAR2
,P_CHG_EVT_SOURCE_O in VARCHAR2
,P_EXT_RCD_IN_FILE_ID_O in NUMBER
,P_EXT_DATA_ELMT_IN_RCD_ID_O in NUMBER
,P_BUSINESS_GROUP_ID_O in NUMBER
,P_LEGISLATION_CODE_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: ben_xic_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: ben_xic_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end ben_xic_RKD;

/
