--------------------------------------------------------
--  DDL for Package Body BEN_EXT_ELMT_DECD_BK1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_EXT_ELMT_DECD_BK1" as
/* $Header: bexddapi.pkb 120.1 2005/06/08 13:08:59 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:41:09 (YYYY/MM/DD HH24:MI:SS)
procedure CREATE_EXT_ELMT_DECD_A
(P_EXT_DATA_ELMT_DECD_ID in NUMBER
,P_VAL in VARCHAR2
,P_DCD_VAL in VARCHAR2
,P_CHG_EVT_SOURCE in VARCHAR2
,P_EXT_DATA_ELMT_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: BEN_EXT_ELMT_DECD_BK1.CREATE_EXT_ELMT_DECD_A', 10);
hr_utility.set_location(' Leaving: BEN_EXT_ELMT_DECD_BK1.CREATE_EXT_ELMT_DECD_A', 20);
end CREATE_EXT_ELMT_DECD_A;
procedure CREATE_EXT_ELMT_DECD_B
(P_VAL in VARCHAR2
,P_DCD_VAL in VARCHAR2
,P_CHG_EVT_SOURCE in VARCHAR2
,P_EXT_DATA_ELMT_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_EXT_ELMT_DECD_BK1.CREATE_EXT_ELMT_DECD_B', 10);
hr_utility.set_location(' Leaving: BEN_EXT_ELMT_DECD_BK1.CREATE_EXT_ELMT_DECD_B', 20);
end CREATE_EXT_ELMT_DECD_B;
end BEN_EXT_ELMT_DECD_BK1;

/
