--------------------------------------------------------
--  DDL for Package Body BEN_EXT_CRIT_TYP_BK2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_EXT_CRIT_TYP_BK2" as
/* $Header: bexctapi.pkb 115.4 2002/12/24 22:24:42 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:41:08 (YYYY/MM/DD HH24:MI:SS)
procedure UPDATE_EXT_CRIT_TYP_A
(P_EXT_CRIT_TYP_ID in NUMBER
,P_CRIT_TYP_CD in VARCHAR2
,P_EXT_CRIT_PRFL_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_EXCLD_FLAG in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_EXT_CRIT_TYP_BK2.UPDATE_EXT_CRIT_TYP_A', 10);
hr_utility.set_location(' Leaving: BEN_EXT_CRIT_TYP_BK2.UPDATE_EXT_CRIT_TYP_A', 20);
end UPDATE_EXT_CRIT_TYP_A;
procedure UPDATE_EXT_CRIT_TYP_B
(P_EXT_CRIT_TYP_ID in NUMBER
,P_CRIT_TYP_CD in VARCHAR2
,P_EXT_CRIT_PRFL_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_EXCLD_FLAG in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_EXT_CRIT_TYP_BK2.UPDATE_EXT_CRIT_TYP_B', 10);
hr_utility.set_location(' Leaving: BEN_EXT_CRIT_TYP_BK2.UPDATE_EXT_CRIT_TYP_B', 20);
end UPDATE_EXT_CRIT_TYP_B;
end BEN_EXT_CRIT_TYP_BK2;

/
