--------------------------------------------------------
--  DDL for Package Body BEN_ENROLLMENT_RATE_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_ENROLLMENT_RATE_BK3" as
/* $Header: beecrapi.pkb 115.22 2004/03/23 12:43:03 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:38:43 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_ENROLLMENT_RATE_A
(P_ENRT_RT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: BEN_ENROLLMENT_RATE_BK3.DELETE_ENROLLMENT_RATE_A', 10);
hr_utility.set_location(' Leaving: BEN_ENROLLMENT_RATE_BK3.DELETE_ENROLLMENT_RATE_A', 20);
end DELETE_ENROLLMENT_RATE_A;
procedure DELETE_ENROLLMENT_RATE_B
(P_ENRT_RT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: BEN_ENROLLMENT_RATE_BK3.DELETE_ENROLLMENT_RATE_B', 10);
hr_utility.set_location(' Leaving: BEN_ENROLLMENT_RATE_BK3.DELETE_ENROLLMENT_RATE_B', 20);
end DELETE_ENROLLMENT_RATE_B;
end BEN_ENROLLMENT_RATE_BK3;

/
