--------------------------------------------------------
--  DDL for Package Body BEN_PSG_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_PSG_RKI" as
/*  $Header: bepsgrhi.pkb 120.0 2005/09/29 06:19:33 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:40:41 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_PIL_ASSIGNMENT_ID in NUMBER
,P_PER_IN_LER_ID in NUMBER
,P_APPLICANT_ASSIGNMENT_ID in NUMBER
,P_OFFER_ASSIGNMENT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: BEN_PSG_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: BEN_PSG_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end BEN_PSG_RKI;

/
