--------------------------------------------------------
--  DDL for Package Body BEN_BATCH_ELCTBL_CHC_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_BATCH_ELCTBL_CHC_BK3" as
/* $Header: bebecapi.pkb 115.3 2002/12/16 17:34:23 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:37:37 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_BATCH_ELCTBL_CHC_A
(P_BATCH_ELCTBL_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: BEN_BATCH_ELCTBL_CHC_BK3.DELETE_BATCH_ELCTBL_CHC_A', 10);
hr_utility.set_location(' Leaving: BEN_BATCH_ELCTBL_CHC_BK3.DELETE_BATCH_ELCTBL_CHC_A', 20);
end DELETE_BATCH_ELCTBL_CHC_A;
procedure DELETE_BATCH_ELCTBL_CHC_B
(P_BATCH_ELCTBL_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: BEN_BATCH_ELCTBL_CHC_BK3.DELETE_BATCH_ELCTBL_CHC_B', 10);
hr_utility.set_location(' Leaving: BEN_BATCH_ELCTBL_CHC_BK3.DELETE_BATCH_ELCTBL_CHC_B', 20);
end DELETE_BATCH_ELCTBL_CHC_B;
end BEN_BATCH_ELCTBL_CHC_BK3;

/
