--------------------------------------------------------
--  DDL for Package Body BEN_ELIG_PER_ELC_CHC_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_ELIG_PER_ELC_CHC_BK3" as
/* $Header: beepeapi.pkb 120.0 2005/05/28 02:36:32 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:39:15 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_ELIG_PER_ELC_CHC_A
(P_ELIG_PER_ELCTBL_CHC_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: BEN_ELIG_PER_ELC_CHC_BK3.DELETE_ELIG_PER_ELC_CHC_A', 10);
hr_utility.set_location(' Leaving: BEN_ELIG_PER_ELC_CHC_BK3.DELETE_ELIG_PER_ELC_CHC_A', 20);
end DELETE_ELIG_PER_ELC_CHC_A;
procedure DELETE_ELIG_PER_ELC_CHC_B
(P_ELIG_PER_ELCTBL_CHC_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: BEN_ELIG_PER_ELC_CHC_BK3.DELETE_ELIG_PER_ELC_CHC_B', 10);
hr_utility.set_location(' Leaving: BEN_ELIG_PER_ELC_CHC_BK3.DELETE_ELIG_PER_ELC_CHC_B', 20);
end DELETE_ELIG_PER_ELC_CHC_B;
end BEN_ELIG_PER_ELC_CHC_BK3;

/
