--------------------------------------------------------
--  DDL for Package Body BEN_XRF_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_XRF_RKI" as
/* $Header: bexrfrhi.pkb 120.3 2006/04/06 17:46:56 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:41:14 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EXT_RCD_IN_FILE_ID in NUMBER
,P_SEQ_NUM in NUMBER
,P_SPRS_CD in VARCHAR2
,P_SORT1_DATA_ELMT_IN_RCD_ID in NUMBER
,P_SORT2_DATA_ELMT_IN_RCD_ID in NUMBER
,P_SORT3_DATA_ELMT_IN_RCD_ID in NUMBER
,P_SORT4_DATA_ELMT_IN_RCD_ID in NUMBER
,P_EXT_RCD_ID in NUMBER
,P_EXT_FILE_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_ANY_OR_ALL_CD in VARCHAR2
,P_HIDE_FLAG in VARCHAR2
,P_RQD_FLAG in VARCHAR2
,P_CHG_RCD_UPD_FLAG in VARCHAR2
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: ben_xrf_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: ben_xrf_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end ben_xrf_RKI;

/
