--------------------------------------------------------
--  DDL for Package Body BEN_CMBN_PLIP_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BEN_CMBN_PLIP_BK3" as
/* $Header: becplapi.pkb 120.0 2005/05/28 01:14:12 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:38:14 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_CMBN_PLIP_A
(P_CMBN_PLIP_ID in NUMBER
,P_EFFECTIVE_START_DATE in DATE
,P_EFFECTIVE_END_DATE in DATE
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_CMBN_PLIP_BK3.DELETE_CMBN_PLIP_A', 10);
hr_utility.set_location(' Leaving: BEN_CMBN_PLIP_BK3.DELETE_CMBN_PLIP_A', 20);
end DELETE_CMBN_PLIP_A;
procedure DELETE_CMBN_PLIP_B
(P_CMBN_PLIP_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: BEN_CMBN_PLIP_BK3.DELETE_CMBN_PLIP_B', 10);
hr_utility.set_location(' Leaving: BEN_CMBN_PLIP_BK3.DELETE_CMBN_PLIP_B', 20);
end DELETE_CMBN_PLIP_B;
end BEN_CMBN_PLIP_BK3;

/
