--------------------------------------------------------
--  DDL for Package Body BOM_CSTRIVTI_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."BOM_CSTRIVTI_XMLP_PKG" AS
/* $Header: CSTRIVTIB.pls 120.0 2007/12/24 10:03:54 dwkrishn noship $ */
  FUNCTION BEFOREREPORT RETURN BOOLEAN IS
  BEGIN
    DECLARE
      L_FCN_CURRENCY VARCHAR2(15);
    BEGIN
      SELECT
        SOB.CURRENCY_CODE
      INTO L_FCN_CURRENCY
      FROM
        GL_SETS_OF_BOOKS SOB,
        ORG_ORGANIZATION_DEFINITIONS OOD
      WHERE OOD.ORGANIZATION_ID = P_ORG_ID
        AND SOB.SET_OF_BOOKS_ID = OOD.SET_OF_BOOKS_ID;
      P_CURRENCY_CODE := L_FCN_CURRENCY;
      SELECT
        O.ORGANIZATION_NAME,
        NVL(MINIMUM_ACCOUNTABLE_UNIT
           ,POWER(10
                ,NVL(-PRECISION
                   ,0)))
      INTO CP_ORG_NAME,ROUND_UNIT
      FROM
        ORG_ORGANIZATION_DEFINITIONS O,
        FND_CURRENCIES FC
      WHERE FC.CURRENCY_CODE = P_CURRENCY_CODE
        AND O.ORGANIZATION_ID = P_ORG_ID;
    END;
    BEGIN
      IF P_VIEW_COST <> 1 THEN
        FND_MESSAGE.SET_NAME('null'
                            ,'null');
        /*SRW.USER_EXIT('FND MESSAGE_DISPLAY')*/NULL;
        /*RAISE SRW.PROGRAM_ABORT*/RAISE_APPLICATION_ERROR(-20101,null);
      END IF;
    END;
    BEGIN
      P_CONC_REQUEST_ID := FND_GLOBAL.CONC_REQUEST_ID;
      /*SRW.USER_EXIT('FND SRWINIT')*/NULL;
    EXCEPTION
      WHEN /*SRW.USER_EXIT_FAILURE*/OTHERS THEN
        /*SRW.MESSAGE(1
                   ,'Failed in SRWINIT')*/NULL;
        RAISE;
    END;
    BEGIN
      NULL;
    EXCEPTION
      WHEN OTHERS THEN
        /*SRW.MESSAGE(999
                   ,'FND FLEXSQL(GL#) >X')*/NULL;
        RAISE;
    END;
    BEGIN
      NULL;
    EXCEPTION
      WHEN OTHERS THEN
        /*SRW.MESSAGE(999
                   ,'FND FLEXSQL(MSTK) >X')*/NULL;
        RAISE;
    END;
    RETURN (TRUE);
  END BEFOREREPORT;

  FUNCTION AFTERREPORT RETURN BOOLEAN IS
  BEGIN
    /*SRW.USER_EXIT('FND SRWEXIT')*/NULL;
    RETURN (TRUE);
  END AFTERREPORT;

  FUNCTION ITEM_PSEGFORMULA(ITEM_SEGMENT IN VARCHAR2
                           ,ITEM_NAME IN VARCHAR2
                           ,ITEM_PSEG IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    /*SRW.REFERENCE(ITEM_SEGMENT)*/NULL;
    /*SRW.REFERENCE(ITEM_NAME)*/NULL;
    RETURN (ITEM_PSEG);
  END ITEM_PSEGFORMULA;

  FUNCTION CP_ORG_NAME_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_ORG_NAME;
  END CP_ORG_NAME_P;

END BOM_CSTRIVTI_XMLP_PKG;


/
