--------------------------------------------------------
--  DDL for Package Body CSI_I_PARTIES_H_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."CSI_I_PARTIES_H_PKG" as
/* $Header: csitpthb.pls 115.13 2003/09/04 00:22:16 sguthiva ship $ */

G_PKG_NAME CONSTANT VARCHAR2(30):= 'CSI_I_PARTIES_H_PKG';
G_FILE_NAME CONSTANT VARCHAR2(12) := 'csitpthb.pls';

PROCEDURE Insert_Row(
          px_INSTANCE_PARTY_HISTORY_ID   IN OUT NOCOPY NUMBER,
          p_INSTANCE_PARTY_ID    NUMBER,
          p_TRANSACTION_ID    NUMBER,
          p_OLD_PARTY_SOURCE_TABLE    VARCHAR2,
          p_NEW_PARTY_SOURCE_TABLE    VARCHAR2,
          p_OLD_PARTY_ID    NUMBER,
          p_NEW_PARTY_ID    NUMBER,
          p_OLD_RELATIONSHIP_TYPE_CODE    VARCHAR2,
          p_NEW_RELATIONSHIP_TYPE_CODE    VARCHAR2,
          p_OLD_CONTACT_FLAG    VARCHAR2,
          p_NEW_CONTACT_FLAG    VARCHAR2,
          p_OLD_CONTACT_IP_ID    NUMBER,
          p_NEW_CONTACT_IP_ID    NUMBER,
          p_OLD_ACTIVE_START_DATE    DATE,
          p_NEW_ACTIVE_START_DATE    DATE,
          p_OLD_ACTIVE_END_DATE    DATE,
          p_NEW_ACTIVE_END_DATE    DATE,
          p_OLD_CONTEXT    VARCHAR2,
          p_NEW_CONTEXT    VARCHAR2,
          p_OLD_ATTRIBUTE1    VARCHAR2,
          p_NEW_ATTRIBUTE1    VARCHAR2,
          p_OLD_ATTRIBUTE2    VARCHAR2,
          p_NEW_ATTRIBUTE2    VARCHAR2,
          p_OLD_ATTRIBUTE3    VARCHAR2,
          p_NEW_ATTRIBUTE3    VARCHAR2,
          p_OLD_ATTRIBUTE4    VARCHAR2,
          p_NEW_ATTRIBUTE4    VARCHAR2,
          p_OLD_ATTRIBUTE5    VARCHAR2,
          p_NEW_ATTRIBUTE5    VARCHAR2,
          p_OLD_ATTRIBUTE6    VARCHAR2,
          p_NEW_ATTRIBUTE6    VARCHAR2,
          p_OLD_ATTRIBUTE7    VARCHAR2,
          p_NEW_ATTRIBUTE7    VARCHAR2,
          p_OLD_ATTRIBUTE8    VARCHAR2,
          p_NEW_ATTRIBUTE8    VARCHAR2,
          p_OLD_ATTRIBUTE9    VARCHAR2,
          p_NEW_ATTRIBUTE9    VARCHAR2,
          p_OLD_ATTRIBUTE10    VARCHAR2,
          p_NEW_ATTRIBUTE10    VARCHAR2,
          p_OLD_ATTRIBUTE11    VARCHAR2,
          p_NEW_ATTRIBUTE11    VARCHAR2,
          p_OLD_ATTRIBUTE12    VARCHAR2,
          p_NEW_ATTRIBUTE12    VARCHAR2,
          p_OLD_ATTRIBUTE13    VARCHAR2,
          p_NEW_ATTRIBUTE13    VARCHAR2,
          p_OLD_ATTRIBUTE14    VARCHAR2,
          p_NEW_ATTRIBUTE14    VARCHAR2,
          p_OLD_ATTRIBUTE15    VARCHAR2,
          p_NEW_ATTRIBUTE15    VARCHAR2,
          p_FULL_DUMP_FLAG    VARCHAR2,
          p_CREATED_BY    NUMBER,
          p_CREATION_DATE    DATE,
          p_LAST_UPDATED_BY    NUMBER,
          p_LAST_UPDATE_DATE    DATE,
          p_LAST_UPDATE_LOGIN    NUMBER,
          p_OBJECT_VERSION_NUMBER    NUMBER,
          p_OLD_PRIMARY_FLAG    VARCHAR2,
          p_NEW_PRIMARY_FLAG    VARCHAR2,
          p_OLD_PREFERRED_FLAG    VARCHAR2,
          p_NEW_PREFERRED_FLAG    VARCHAR2)
 IS
   CURSOR C2 IS SELECT CSI_I_PARTIES_H_S.nextval FROM sys.dual;
BEGIN
   If (px_INSTANCE_PARTY_HISTORY_ID IS NULL) OR (px_INSTANCE_PARTY_HISTORY_ID = FND_API.G_MISS_NUM) then
       OPEN C2;
       FETCH C2 INTO px_INSTANCE_PARTY_HISTORY_ID;
       CLOSE C2;
   End If;
   INSERT INTO CSI_I_PARTIES_H(
           INSTANCE_PARTY_HISTORY_ID,
           INSTANCE_PARTY_ID,
           TRANSACTION_ID,
           OLD_PARTY_SOURCE_TABLE,
           NEW_PARTY_SOURCE_TABLE,
           OLD_PARTY_ID,
           NEW_PARTY_ID,
           OLD_RELATIONSHIP_TYPE_CODE,
           NEW_RELATIONSHIP_TYPE_CODE,
           OLD_CONTACT_FLAG,
           NEW_CONTACT_FLAG,
           OLD_CONTACT_IP_ID,
           NEW_CONTACT_IP_ID,
           OLD_ACTIVE_START_DATE,
           NEW_ACTIVE_START_DATE,
           OLD_ACTIVE_END_DATE,
           NEW_ACTIVE_END_DATE,
           OLD_CONTEXT,
           NEW_CONTEXT,
           OLD_ATTRIBUTE1,
           NEW_ATTRIBUTE1,
           OLD_ATTRIBUTE2,
           NEW_ATTRIBUTE2,
           OLD_ATTRIBUTE3,
           NEW_ATTRIBUTE3,
           OLD_ATTRIBUTE4,
           NEW_ATTRIBUTE4,
           OLD_ATTRIBUTE5,
           NEW_ATTRIBUTE5,
           OLD_ATTRIBUTE6,
           NEW_ATTRIBUTE6,
           OLD_ATTRIBUTE7,
           NEW_ATTRIBUTE7,
           OLD_ATTRIBUTE8,
           NEW_ATTRIBUTE8,
           OLD_ATTRIBUTE9,
           NEW_ATTRIBUTE9,
           OLD_ATTRIBUTE10,
           NEW_ATTRIBUTE10,
           OLD_ATTRIBUTE11,
           NEW_ATTRIBUTE11,
           OLD_ATTRIBUTE12,
           NEW_ATTRIBUTE12,
           OLD_ATTRIBUTE13,
           NEW_ATTRIBUTE13,
           OLD_ATTRIBUTE14,
           NEW_ATTRIBUTE14,
           OLD_ATTRIBUTE15,
           NEW_ATTRIBUTE15,
           FULL_DUMP_FLAG,
           CREATED_BY,
           CREATION_DATE,
           LAST_UPDATED_BY,
           LAST_UPDATE_DATE,
           LAST_UPDATE_LOGIN,
           OBJECT_VERSION_NUMBER,
           OLD_PRIMARY_FLAG,
           NEW_PRIMARY_FLAG,
           OLD_PREFERRED_FLAG,
           NEW_PREFERRED_FLAG
          ) VALUES (
           px_INSTANCE_PARTY_HISTORY_ID,
           decode( p_INSTANCE_PARTY_ID, FND_API.G_MISS_NUM, NULL, p_INSTANCE_PARTY_ID),
           decode( p_TRANSACTION_ID, FND_API.G_MISS_NUM, NULL, p_TRANSACTION_ID),
           decode( p_OLD_PARTY_SOURCE_TABLE, FND_API.G_MISS_CHAR, NULL, p_OLD_PARTY_SOURCE_TABLE),
           decode( p_NEW_PARTY_SOURCE_TABLE, FND_API.G_MISS_CHAR, NULL, p_NEW_PARTY_SOURCE_TABLE),
           decode( p_OLD_PARTY_ID, FND_API.G_MISS_NUM, NULL, p_OLD_PARTY_ID),
           decode( p_NEW_PARTY_ID, FND_API.G_MISS_NUM, NULL, p_NEW_PARTY_ID),
           decode( p_OLD_RELATIONSHIP_TYPE_CODE, FND_API.G_MISS_CHAR, NULL, p_OLD_RELATIONSHIP_TYPE_CODE),
           decode( p_NEW_RELATIONSHIP_TYPE_CODE, FND_API.G_MISS_CHAR, NULL, p_NEW_RELATIONSHIP_TYPE_CODE),
           decode( p_OLD_CONTACT_FLAG, FND_API.G_MISS_CHAR, NULL, p_OLD_CONTACT_FLAG),
           decode( p_NEW_CONTACT_FLAG, FND_API.G_MISS_CHAR, NULL, p_NEW_CONTACT_FLAG),
           decode( p_OLD_CONTACT_IP_ID, FND_API.G_MISS_NUM, NULL, p_OLD_CONTACT_IP_ID),
           decode( p_NEW_CONTACT_IP_ID, FND_API.G_MISS_NUM, NULL, p_NEW_CONTACT_IP_ID),
           decode( p_OLD_ACTIVE_START_DATE, FND_API.G_MISS_DATE, TO_DATE(NULL), p_OLD_ACTIVE_START_DATE),
           decode( p_NEW_ACTIVE_START_DATE, FND_API.G_MISS_DATE, TO_DATE(NULL), p_NEW_ACTIVE_START_DATE),
           decode( p_OLD_ACTIVE_END_DATE, FND_API.G_MISS_DATE, TO_DATE(NULL), p_OLD_ACTIVE_END_DATE),
           decode( p_NEW_ACTIVE_END_DATE, FND_API.G_MISS_DATE, TO_DATE(NULL), p_NEW_ACTIVE_END_DATE),
           decode( p_OLD_CONTEXT, FND_API.G_MISS_CHAR, NULL, p_OLD_CONTEXT),
           decode( p_NEW_CONTEXT, FND_API.G_MISS_CHAR, NULL, p_NEW_CONTEXT),
           decode( p_OLD_ATTRIBUTE1, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE1),
           decode( p_NEW_ATTRIBUTE1, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE1),
           decode( p_OLD_ATTRIBUTE2, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE2),
           decode( p_NEW_ATTRIBUTE2, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE2),
           decode( p_OLD_ATTRIBUTE3, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE3),
           decode( p_NEW_ATTRIBUTE3, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE3),
           decode( p_OLD_ATTRIBUTE4, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE4),
           decode( p_NEW_ATTRIBUTE4, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE4),
           decode( p_OLD_ATTRIBUTE5, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE5),
           decode( p_NEW_ATTRIBUTE5, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE5),
           decode( p_OLD_ATTRIBUTE6, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE6),
           decode( p_NEW_ATTRIBUTE6, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE6),
           decode( p_OLD_ATTRIBUTE7, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE7),
           decode( p_NEW_ATTRIBUTE7, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE7),
           decode( p_OLD_ATTRIBUTE8, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE8),
           decode( p_NEW_ATTRIBUTE8, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE8),
           decode( p_OLD_ATTRIBUTE9, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE9),
           decode( p_NEW_ATTRIBUTE9, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE9),
           decode( p_OLD_ATTRIBUTE10, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE10),
           decode( p_NEW_ATTRIBUTE10, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE10),
           decode( p_OLD_ATTRIBUTE11, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE11),
           decode( p_NEW_ATTRIBUTE11, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE11),
           decode( p_OLD_ATTRIBUTE12, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE12),
           decode( p_NEW_ATTRIBUTE12, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE12),
           decode( p_OLD_ATTRIBUTE13, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE13),
           decode( p_NEW_ATTRIBUTE13, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE13),
           decode( p_OLD_ATTRIBUTE14, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE14),
           decode( p_NEW_ATTRIBUTE14, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE14),
           decode( p_OLD_ATTRIBUTE15, FND_API.G_MISS_CHAR, NULL, p_OLD_ATTRIBUTE15),
           decode( p_NEW_ATTRIBUTE15, FND_API.G_MISS_CHAR, NULL, p_NEW_ATTRIBUTE15),
           decode( p_FULL_DUMP_FLAG, FND_API.G_MISS_CHAR, NULL, p_FULL_DUMP_FLAG),
           decode( p_CREATED_BY, FND_API.G_MISS_NUM, NULL, p_CREATED_BY),
           decode( p_CREATION_DATE, FND_API.G_MISS_DATE, TO_DATE(NULL), p_CREATION_DATE),
           decode( p_LAST_UPDATED_BY, FND_API.G_MISS_NUM, NULL, p_LAST_UPDATED_BY),
           decode( p_LAST_UPDATE_DATE, FND_API.G_MISS_DATE, TO_DATE(NULL), p_LAST_UPDATE_DATE),
           decode( p_LAST_UPDATE_LOGIN, FND_API.G_MISS_NUM, NULL, p_LAST_UPDATE_LOGIN),
           decode( p_OBJECT_VERSION_NUMBER, FND_API.G_MISS_NUM, NULL, p_OBJECT_VERSION_NUMBER),
           decode( p_OLD_PRIMARY_FLAG, FND_API.G_MISS_CHAR, NULL, p_OLD_PRIMARY_FLAG),
           decode( p_NEW_PRIMARY_FLAG, FND_API.G_MISS_CHAR, NULL, p_NEW_PRIMARY_FLAG),
           decode( p_OLD_PREFERRED_FLAG, FND_API.G_MISS_CHAR, NULL, p_OLD_PREFERRED_FLAG),
           decode( p_NEW_PREFERRED_FLAG, FND_API.G_MISS_CHAR, NULL, p_NEW_PREFERRED_FLAG));
End Insert_Row;

PROCEDURE Update_Row(
          p_INSTANCE_PARTY_HISTORY_ID    NUMBER,
          p_INSTANCE_PARTY_ID    NUMBER,
          p_TRANSACTION_ID    NUMBER,
          p_OLD_PARTY_SOURCE_TABLE    VARCHAR2,
          p_NEW_PARTY_SOURCE_TABLE    VARCHAR2,
          p_OLD_PARTY_ID    NUMBER,
          p_NEW_PARTY_ID    NUMBER,
          p_OLD_RELATIONSHIP_TYPE_CODE    VARCHAR2,
          p_NEW_RELATIONSHIP_TYPE_CODE    VARCHAR2,
          p_OLD_CONTACT_FLAG    VARCHAR2,
          p_NEW_CONTACT_FLAG    VARCHAR2,
          p_OLD_CONTACT_IP_ID    NUMBER,
          p_NEW_CONTACT_IP_ID    NUMBER,
          p_OLD_ACTIVE_START_DATE    DATE,
          p_NEW_ACTIVE_START_DATE    DATE,
          p_OLD_ACTIVE_END_DATE    DATE,
          p_NEW_ACTIVE_END_DATE    DATE,
          p_OLD_CONTEXT    VARCHAR2,
          p_NEW_CONTEXT    VARCHAR2,
          p_OLD_ATTRIBUTE1    VARCHAR2,
          p_NEW_ATTRIBUTE1    VARCHAR2,
          p_OLD_ATTRIBUTE2    VARCHAR2,
          p_NEW_ATTRIBUTE2    VARCHAR2,
          p_OLD_ATTRIBUTE3    VARCHAR2,
          p_NEW_ATTRIBUTE3    VARCHAR2,
          p_OLD_ATTRIBUTE4    VARCHAR2,
          p_NEW_ATTRIBUTE4    VARCHAR2,
          p_OLD_ATTRIBUTE5    VARCHAR2,
          p_NEW_ATTRIBUTE5    VARCHAR2,
          p_OLD_ATTRIBUTE6    VARCHAR2,
          p_NEW_ATTRIBUTE6    VARCHAR2,
          p_OLD_ATTRIBUTE7    VARCHAR2,
          p_NEW_ATTRIBUTE7    VARCHAR2,
          p_OLD_ATTRIBUTE8    VARCHAR2,
          p_NEW_ATTRIBUTE8    VARCHAR2,
          p_OLD_ATTRIBUTE9    VARCHAR2,
          p_NEW_ATTRIBUTE9    VARCHAR2,
          p_OLD_ATTRIBUTE10    VARCHAR2,
          p_NEW_ATTRIBUTE10    VARCHAR2,
          p_OLD_ATTRIBUTE11    VARCHAR2,
          p_NEW_ATTRIBUTE11    VARCHAR2,
          p_OLD_ATTRIBUTE12    VARCHAR2,
          p_NEW_ATTRIBUTE12    VARCHAR2,
          p_OLD_ATTRIBUTE13    VARCHAR2,
          p_NEW_ATTRIBUTE13    VARCHAR2,
          p_OLD_ATTRIBUTE14    VARCHAR2,
          p_NEW_ATTRIBUTE14    VARCHAR2,
          p_OLD_ATTRIBUTE15    VARCHAR2,
          p_NEW_ATTRIBUTE15    VARCHAR2,
          p_FULL_DUMP_FLAG    VARCHAR2,
          p_CREATED_BY    NUMBER,
          p_CREATION_DATE    DATE,
          p_LAST_UPDATED_BY    NUMBER,
          p_LAST_UPDATE_DATE    DATE,
          p_LAST_UPDATE_LOGIN    NUMBER,
          p_OBJECT_VERSION_NUMBER    NUMBER,
          p_OLD_PRIMARY_FLAG    VARCHAR2,
          p_NEW_PRIMARY_FLAG    VARCHAR2,
          p_OLD_PREFERRED_FLAG    VARCHAR2,
          p_NEW_PREFERRED_FLAG    VARCHAR2)

 IS
 BEGIN
    Update CSI_I_PARTIES_H
    SET
              INSTANCE_PARTY_ID = decode( p_INSTANCE_PARTY_ID, FND_API.G_MISS_NUM, INSTANCE_PARTY_ID, p_INSTANCE_PARTY_ID),
              TRANSACTION_ID = decode( p_TRANSACTION_ID, FND_API.G_MISS_NUM, TRANSACTION_ID, p_TRANSACTION_ID),
              OLD_PARTY_SOURCE_TABLE = decode( p_OLD_PARTY_SOURCE_TABLE, FND_API.G_MISS_CHAR, OLD_PARTY_SOURCE_TABLE, p_OLD_PARTY_SOURCE_TABLE),
              NEW_PARTY_SOURCE_TABLE = decode( p_NEW_PARTY_SOURCE_TABLE, FND_API.G_MISS_CHAR, NEW_PARTY_SOURCE_TABLE, p_NEW_PARTY_SOURCE_TABLE),
              OLD_PARTY_ID = decode( p_OLD_PARTY_ID, FND_API.G_MISS_NUM, OLD_PARTY_ID, p_OLD_PARTY_ID),
              NEW_PARTY_ID = decode( p_NEW_PARTY_ID, FND_API.G_MISS_NUM, NEW_PARTY_ID, p_NEW_PARTY_ID),
              OLD_RELATIONSHIP_TYPE_CODE = decode( p_OLD_RELATIONSHIP_TYPE_CODE, FND_API.G_MISS_CHAR, OLD_RELATIONSHIP_TYPE_CODE, p_OLD_RELATIONSHIP_TYPE_CODE),
              NEW_RELATIONSHIP_TYPE_CODE = decode( p_NEW_RELATIONSHIP_TYPE_CODE, FND_API.G_MISS_CHAR, NEW_RELATIONSHIP_TYPE_CODE, p_NEW_RELATIONSHIP_TYPE_CODE),
              OLD_CONTACT_FLAG = decode( p_OLD_CONTACT_FLAG, FND_API.G_MISS_CHAR, OLD_CONTACT_FLAG, p_OLD_CONTACT_FLAG),
              NEW_CONTACT_FLAG = decode( p_NEW_CONTACT_FLAG, FND_API.G_MISS_CHAR, NEW_CONTACT_FLAG, p_NEW_CONTACT_FLAG),
              OLD_CONTACT_IP_ID = decode( p_OLD_CONTACT_IP_ID, FND_API.G_MISS_NUM, OLD_CONTACT_IP_ID, p_OLD_CONTACT_IP_ID),
              NEW_CONTACT_IP_ID = decode( p_NEW_CONTACT_IP_ID, FND_API.G_MISS_NUM, NEW_CONTACT_IP_ID, p_NEW_CONTACT_IP_ID),
              OLD_ACTIVE_START_DATE = decode( p_OLD_ACTIVE_START_DATE, FND_API.G_MISS_DATE, OLD_ACTIVE_START_DATE, p_OLD_ACTIVE_START_DATE),
              NEW_ACTIVE_START_DATE = decode( p_NEW_ACTIVE_START_DATE, FND_API.G_MISS_DATE, NEW_ACTIVE_START_DATE, p_NEW_ACTIVE_START_DATE),
              OLD_ACTIVE_END_DATE = decode( p_OLD_ACTIVE_END_DATE, FND_API.G_MISS_DATE, OLD_ACTIVE_END_DATE, p_OLD_ACTIVE_END_DATE),
              NEW_ACTIVE_END_DATE = decode( p_NEW_ACTIVE_END_DATE, FND_API.G_MISS_DATE, NEW_ACTIVE_END_DATE, p_NEW_ACTIVE_END_DATE),
              OLD_CONTEXT = decode( p_OLD_CONTEXT, FND_API.G_MISS_CHAR, OLD_CONTEXT, p_OLD_CONTEXT),
              NEW_CONTEXT = decode( p_NEW_CONTEXT, FND_API.G_MISS_CHAR, NEW_CONTEXT, p_NEW_CONTEXT),
              OLD_ATTRIBUTE1 = decode( p_OLD_ATTRIBUTE1, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE1, p_OLD_ATTRIBUTE1),
              NEW_ATTRIBUTE1 = decode( p_NEW_ATTRIBUTE1, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE1, p_NEW_ATTRIBUTE1),
              OLD_ATTRIBUTE2 = decode( p_OLD_ATTRIBUTE2, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE2, p_OLD_ATTRIBUTE2),
              NEW_ATTRIBUTE2 = decode( p_NEW_ATTRIBUTE2, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE2, p_NEW_ATTRIBUTE2),
              OLD_ATTRIBUTE3 = decode( p_OLD_ATTRIBUTE3, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE3, p_OLD_ATTRIBUTE3),
              NEW_ATTRIBUTE3 = decode( p_NEW_ATTRIBUTE3, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE3, p_NEW_ATTRIBUTE3),
              OLD_ATTRIBUTE4 = decode( p_OLD_ATTRIBUTE4, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE4, p_OLD_ATTRIBUTE4),
              NEW_ATTRIBUTE4 = decode( p_NEW_ATTRIBUTE4, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE4, p_NEW_ATTRIBUTE4),
              OLD_ATTRIBUTE5 = decode( p_OLD_ATTRIBUTE5, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE5, p_OLD_ATTRIBUTE5),
              NEW_ATTRIBUTE5 = decode( p_NEW_ATTRIBUTE5, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE5, p_NEW_ATTRIBUTE5),
              OLD_ATTRIBUTE6 = decode( p_OLD_ATTRIBUTE6, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE6, p_OLD_ATTRIBUTE6),
              NEW_ATTRIBUTE6 = decode( p_NEW_ATTRIBUTE6, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE6, p_NEW_ATTRIBUTE6),
              OLD_ATTRIBUTE7 = decode( p_OLD_ATTRIBUTE7, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE7, p_OLD_ATTRIBUTE7),
              NEW_ATTRIBUTE7 = decode( p_NEW_ATTRIBUTE7, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE7, p_NEW_ATTRIBUTE7),
              OLD_ATTRIBUTE8 = decode( p_OLD_ATTRIBUTE8, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE8, p_OLD_ATTRIBUTE8),
              NEW_ATTRIBUTE8 = decode( p_NEW_ATTRIBUTE8, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE8, p_NEW_ATTRIBUTE8),
              OLD_ATTRIBUTE9 = decode( p_OLD_ATTRIBUTE9, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE9, p_OLD_ATTRIBUTE9),
              NEW_ATTRIBUTE9 = decode( p_NEW_ATTRIBUTE9, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE9, p_NEW_ATTRIBUTE9),
              OLD_ATTRIBUTE10 = decode( p_OLD_ATTRIBUTE10, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE10, p_OLD_ATTRIBUTE10),
              NEW_ATTRIBUTE10 = decode( p_NEW_ATTRIBUTE10, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE10, p_NEW_ATTRIBUTE10),
              OLD_ATTRIBUTE11 = decode( p_OLD_ATTRIBUTE11, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE11, p_OLD_ATTRIBUTE11),
              NEW_ATTRIBUTE11 = decode( p_NEW_ATTRIBUTE11, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE11, p_NEW_ATTRIBUTE11),
              OLD_ATTRIBUTE12 = decode( p_OLD_ATTRIBUTE12, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE12, p_OLD_ATTRIBUTE12),
              NEW_ATTRIBUTE12 = decode( p_NEW_ATTRIBUTE12, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE12, p_NEW_ATTRIBUTE12),
              OLD_ATTRIBUTE13 = decode( p_OLD_ATTRIBUTE13, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE13, p_OLD_ATTRIBUTE13),
              NEW_ATTRIBUTE13 = decode( p_NEW_ATTRIBUTE13, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE13, p_NEW_ATTRIBUTE13),
              OLD_ATTRIBUTE14 = decode( p_OLD_ATTRIBUTE14, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE14, p_OLD_ATTRIBUTE14),
              NEW_ATTRIBUTE14 = decode( p_NEW_ATTRIBUTE14, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE14, p_NEW_ATTRIBUTE14),
              OLD_ATTRIBUTE15 = decode( p_OLD_ATTRIBUTE15, FND_API.G_MISS_CHAR, OLD_ATTRIBUTE15, p_OLD_ATTRIBUTE15),
              NEW_ATTRIBUTE15 = decode( p_NEW_ATTRIBUTE15, FND_API.G_MISS_CHAR, NEW_ATTRIBUTE15, p_NEW_ATTRIBUTE15),
              FULL_DUMP_FLAG = decode( p_FULL_DUMP_FLAG, FND_API.G_MISS_CHAR, FULL_DUMP_FLAG, p_FULL_DUMP_FLAG),
              CREATED_BY = decode( p_CREATED_BY, FND_API.G_MISS_NUM, CREATED_BY, p_CREATED_BY),
              CREATION_DATE = decode( p_CREATION_DATE, FND_API.G_MISS_DATE, CREATION_DATE, p_CREATION_DATE),
              LAST_UPDATED_BY = decode( p_LAST_UPDATED_BY, FND_API.G_MISS_NUM, LAST_UPDATED_BY, p_LAST_UPDATED_BY),
              LAST_UPDATE_DATE = decode( p_LAST_UPDATE_DATE, FND_API.G_MISS_DATE, LAST_UPDATE_DATE, p_LAST_UPDATE_DATE),
              LAST_UPDATE_LOGIN = decode( p_LAST_UPDATE_LOGIN, FND_API.G_MISS_NUM, LAST_UPDATE_LOGIN, p_LAST_UPDATE_LOGIN),
              OBJECT_VERSION_NUMBER = decode( p_OBJECT_VERSION_NUMBER, FND_API.G_MISS_NUM, OBJECT_VERSION_NUMBER, p_OBJECT_VERSION_NUMBER),
              OLD_PRIMARY_FLAG = decode( p_OLD_PRIMARY_FLAG, FND_API.G_MISS_CHAR, OLD_PRIMARY_FLAG, p_OLD_PRIMARY_FLAG),
              NEW_PRIMARY_FLAG = decode( p_NEW_PRIMARY_FLAG, FND_API.G_MISS_CHAR, NEW_PRIMARY_FLAG, p_NEW_PRIMARY_FLAG),
              OLD_PREFERRED_FLAG = decode( p_OLD_PREFERRED_FLAG, FND_API.G_MISS_CHAR, OLD_PREFERRED_FLAG, p_OLD_PREFERRED_FLAG),
              NEW_PREFERRED_FLAG = decode( p_NEW_PREFERRED_FLAG, FND_API.G_MISS_CHAR, NEW_PREFERRED_FLAG, p_NEW_PREFERRED_FLAG)
    where INSTANCE_PARTY_HISTORY_ID = p_INSTANCE_PARTY_HISTORY_ID;

    If (SQL%NOTFOUND) then
        RAISE NO_DATA_FOUND;
    End If;
END Update_Row;

PROCEDURE Delete_Row(
    p_INSTANCE_PARTY_HISTORY_ID  NUMBER)
 IS
 BEGIN
   DELETE FROM CSI_I_PARTIES_H
    WHERE INSTANCE_PARTY_HISTORY_ID = p_INSTANCE_PARTY_HISTORY_ID;
   If (SQL%NOTFOUND) then
       RAISE NO_DATA_FOUND;
   End If;
 END Delete_Row;

PROCEDURE Lock_Row(
          p_INSTANCE_PARTY_HISTORY_ID    NUMBER,
          p_INSTANCE_PARTY_ID    NUMBER,
          p_TRANSACTION_ID    NUMBER,
          p_OLD_PARTY_SOURCE_TABLE    VARCHAR2,
          p_NEW_PARTY_SOURCE_TABLE    VARCHAR2,
          p_OLD_PARTY_ID    NUMBER,
          p_NEW_PARTY_ID    NUMBER,
          p_OLD_RELATIONSHIP_TYPE_CODE    VARCHAR2,
          p_NEW_RELATIONSHIP_TYPE_CODE    VARCHAR2,
          p_OLD_CONTACT_FLAG    VARCHAR2,
          p_NEW_CONTACT_FLAG    VARCHAR2,
          p_OLD_CONTACT_IP_ID    NUMBER,
          p_NEW_CONTACT_IP_ID    NUMBER,
          p_OLD_ACTIVE_START_DATE    DATE,
          p_NEW_ACTIVE_START_DATE    DATE,
          p_OLD_ACTIVE_END_DATE    DATE,
          p_NEW_ACTIVE_END_DATE    DATE,
          p_OLD_CONTEXT    VARCHAR2,
          p_NEW_CONTEXT    VARCHAR2,
          p_OLD_ATTRIBUTE1    VARCHAR2,
          p_NEW_ATTRIBUTE1    VARCHAR2,
          p_OLD_ATTRIBUTE2    VARCHAR2,
          p_NEW_ATTRIBUTE2    VARCHAR2,
          p_OLD_ATTRIBUTE3    VARCHAR2,
          p_NEW_ATTRIBUTE3    VARCHAR2,
          p_OLD_ATTRIBUTE4    VARCHAR2,
          p_NEW_ATTRIBUTE4    VARCHAR2,
          p_OLD_ATTRIBUTE5    VARCHAR2,
          p_NEW_ATTRIBUTE5    VARCHAR2,
          p_OLD_ATTRIBUTE6    VARCHAR2,
          p_NEW_ATTRIBUTE6    VARCHAR2,
          p_OLD_ATTRIBUTE7    VARCHAR2,
          p_NEW_ATTRIBUTE7    VARCHAR2,
          p_OLD_ATTRIBUTE8    VARCHAR2,
          p_NEW_ATTRIBUTE8    VARCHAR2,
          p_OLD_ATTRIBUTE9    VARCHAR2,
          p_NEW_ATTRIBUTE9    VARCHAR2,
          p_OLD_ATTRIBUTE10    VARCHAR2,
          p_NEW_ATTRIBUTE10    VARCHAR2,
          p_OLD_ATTRIBUTE11    VARCHAR2,
          p_NEW_ATTRIBUTE11    VARCHAR2,
          p_OLD_ATTRIBUTE12    VARCHAR2,
          p_NEW_ATTRIBUTE12    VARCHAR2,
          p_OLD_ATTRIBUTE13    VARCHAR2,
          p_NEW_ATTRIBUTE13    VARCHAR2,
          p_OLD_ATTRIBUTE14    VARCHAR2,
          p_NEW_ATTRIBUTE14    VARCHAR2,
          p_OLD_ATTRIBUTE15    VARCHAR2,
          p_NEW_ATTRIBUTE15    VARCHAR2,
          p_FULL_DUMP_FLAG    VARCHAR2,
          p_CREATED_BY    NUMBER,
          p_CREATION_DATE    DATE,
          p_LAST_UPDATED_BY    NUMBER,
          p_LAST_UPDATE_DATE    DATE,
          p_LAST_UPDATE_LOGIN    NUMBER,
          p_OBJECT_VERSION_NUMBER    NUMBER,
          p_OLD_PRIMARY_FLAG    VARCHAR2,
          p_NEW_PRIMARY_FLAG    VARCHAR2,
          p_OLD_PREFERRED_FLAG    VARCHAR2,
          p_NEW_PREFERRED_FLAG    VARCHAR2)

 IS
   CURSOR C IS
        SELECT *
         FROM CSI_I_PARTIES_H
        WHERE INSTANCE_PARTY_HISTORY_ID =  p_INSTANCE_PARTY_HISTORY_ID
        FOR UPDATE of INSTANCE_PARTY_HISTORY_ID NOWAIT;
   Recinfo C%ROWTYPE;
 BEGIN
    OPEN C;
    FETCH C INTO Recinfo;
    If (C%NOTFOUND) then
        CLOSE C;
        FND_MESSAGE.SET_NAME('FND', 'FORM_RECORD_DELETED');
        APP_EXCEPTION.RAISE_EXCEPTION;
    End If;
    CLOSE C;
    if (
           (      Recinfo.INSTANCE_PARTY_HISTORY_ID = p_INSTANCE_PARTY_HISTORY_ID)
       AND (    ( Recinfo.INSTANCE_PARTY_ID = p_INSTANCE_PARTY_ID)
            OR (    ( Recinfo.INSTANCE_PARTY_ID IS NULL )
                AND (  p_INSTANCE_PARTY_ID IS NULL )))
       AND (    ( Recinfo.TRANSACTION_ID = p_TRANSACTION_ID)
            OR (    ( Recinfo.TRANSACTION_ID IS NULL )
                AND (  p_TRANSACTION_ID IS NULL )))
       AND (    ( Recinfo.OLD_PARTY_SOURCE_TABLE = p_OLD_PARTY_SOURCE_TABLE)
            OR (    ( Recinfo.OLD_PARTY_SOURCE_TABLE IS NULL )
                AND (  p_OLD_PARTY_SOURCE_TABLE IS NULL )))
       AND (    ( Recinfo.NEW_PARTY_SOURCE_TABLE = p_NEW_PARTY_SOURCE_TABLE)
            OR (    ( Recinfo.NEW_PARTY_SOURCE_TABLE IS NULL )
                AND (  p_NEW_PARTY_SOURCE_TABLE IS NULL )))
       AND (    ( Recinfo.OLD_PARTY_ID = p_OLD_PARTY_ID)
            OR (    ( Recinfo.OLD_PARTY_ID IS NULL )
                AND (  p_OLD_PARTY_ID IS NULL )))
       AND (    ( Recinfo.NEW_PARTY_ID = p_NEW_PARTY_ID)
            OR (    ( Recinfo.NEW_PARTY_ID IS NULL )
                AND (  p_NEW_PARTY_ID IS NULL )))
       AND (    ( Recinfo.OLD_RELATIONSHIP_TYPE_CODE = p_OLD_RELATIONSHIP_TYPE_CODE)
            OR (    ( Recinfo.OLD_RELATIONSHIP_TYPE_CODE IS NULL )
                AND (  p_OLD_RELATIONSHIP_TYPE_CODE IS NULL )))
       AND (    ( Recinfo.NEW_RELATIONSHIP_TYPE_CODE = p_NEW_RELATIONSHIP_TYPE_CODE)
            OR (    ( Recinfo.NEW_RELATIONSHIP_TYPE_CODE IS NULL )
                AND (  p_NEW_RELATIONSHIP_TYPE_CODE IS NULL )))
       AND (    ( Recinfo.OLD_CONTACT_FLAG = p_OLD_CONTACT_FLAG)
            OR (    ( Recinfo.OLD_CONTACT_FLAG IS NULL )
                AND (  p_OLD_CONTACT_FLAG IS NULL )))
       AND (    ( Recinfo.NEW_CONTACT_FLAG = p_NEW_CONTACT_FLAG)
            OR (    ( Recinfo.NEW_CONTACT_FLAG IS NULL )
                AND (  p_NEW_CONTACT_FLAG IS NULL )))
       AND (    ( Recinfo.OLD_CONTACT_IP_ID = p_OLD_CONTACT_IP_ID)
            OR (    ( Recinfo.OLD_CONTACT_IP_ID IS NULL )
                AND (  p_OLD_CONTACT_IP_ID IS NULL )))
       AND (    ( Recinfo.NEW_CONTACT_IP_ID = p_NEW_CONTACT_IP_ID)
            OR (    ( Recinfo.NEW_CONTACT_IP_ID IS NULL )
                AND (  p_NEW_CONTACT_IP_ID IS NULL )))
       AND (    ( Recinfo.OLD_ACTIVE_START_DATE = p_OLD_ACTIVE_START_DATE)
            OR (    ( Recinfo.OLD_ACTIVE_START_DATE IS NULL )
                AND (  p_OLD_ACTIVE_START_DATE IS NULL )))
       AND (    ( Recinfo.NEW_ACTIVE_START_DATE = p_NEW_ACTIVE_START_DATE)
            OR (    ( Recinfo.NEW_ACTIVE_START_DATE IS NULL )
                AND (  p_NEW_ACTIVE_START_DATE IS NULL )))
       AND (    ( Recinfo.OLD_ACTIVE_END_DATE = p_OLD_ACTIVE_END_DATE)
            OR (    ( Recinfo.OLD_ACTIVE_END_DATE IS NULL )
                AND (  p_OLD_ACTIVE_END_DATE IS NULL )))
       AND (    ( Recinfo.NEW_ACTIVE_END_DATE = p_NEW_ACTIVE_END_DATE)
            OR (    ( Recinfo.NEW_ACTIVE_END_DATE IS NULL )
                AND (  p_NEW_ACTIVE_END_DATE IS NULL )))
       AND (    ( Recinfo.OLD_CONTEXT = p_OLD_CONTEXT)
            OR (    ( Recinfo.OLD_CONTEXT IS NULL )
                AND (  p_OLD_CONTEXT IS NULL )))
       AND (    ( Recinfo.NEW_CONTEXT = p_NEW_CONTEXT)
            OR (    ( Recinfo.NEW_CONTEXT IS NULL )
                AND (  p_NEW_CONTEXT IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE1 = p_OLD_ATTRIBUTE1)
            OR (    ( Recinfo.OLD_ATTRIBUTE1 IS NULL )
                AND (  p_OLD_ATTRIBUTE1 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE1 = p_NEW_ATTRIBUTE1)
            OR (    ( Recinfo.NEW_ATTRIBUTE1 IS NULL )
                AND (  p_NEW_ATTRIBUTE1 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE2 = p_OLD_ATTRIBUTE2)
            OR (    ( Recinfo.OLD_ATTRIBUTE2 IS NULL )
                AND (  p_OLD_ATTRIBUTE2 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE2 = p_NEW_ATTRIBUTE2)
            OR (    ( Recinfo.NEW_ATTRIBUTE2 IS NULL )
                AND (  p_NEW_ATTRIBUTE2 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE3 = p_OLD_ATTRIBUTE3)
            OR (    ( Recinfo.OLD_ATTRIBUTE3 IS NULL )
                AND (  p_OLD_ATTRIBUTE3 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE3 = p_NEW_ATTRIBUTE3)
            OR (    ( Recinfo.NEW_ATTRIBUTE3 IS NULL )
                AND (  p_NEW_ATTRIBUTE3 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE4 = p_OLD_ATTRIBUTE4)
            OR (    ( Recinfo.OLD_ATTRIBUTE4 IS NULL )
                AND (  p_OLD_ATTRIBUTE4 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE4 = p_NEW_ATTRIBUTE4)
            OR (    ( Recinfo.NEW_ATTRIBUTE4 IS NULL )
                AND (  p_NEW_ATTRIBUTE4 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE5 = p_OLD_ATTRIBUTE5)
            OR (    ( Recinfo.OLD_ATTRIBUTE5 IS NULL )
                AND (  p_OLD_ATTRIBUTE5 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE5 = p_NEW_ATTRIBUTE5)
            OR (    ( Recinfo.NEW_ATTRIBUTE5 IS NULL )
                AND (  p_NEW_ATTRIBUTE5 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE6 = p_OLD_ATTRIBUTE6)
            OR (    ( Recinfo.OLD_ATTRIBUTE6 IS NULL )
                AND (  p_OLD_ATTRIBUTE6 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE6 = p_NEW_ATTRIBUTE6)
            OR (    ( Recinfo.NEW_ATTRIBUTE6 IS NULL )
                AND (  p_NEW_ATTRIBUTE6 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE7 = p_OLD_ATTRIBUTE7)
            OR (    ( Recinfo.OLD_ATTRIBUTE7 IS NULL )
                AND (  p_OLD_ATTRIBUTE7 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE7 = p_NEW_ATTRIBUTE7)
            OR (    ( Recinfo.NEW_ATTRIBUTE7 IS NULL )
                AND (  p_NEW_ATTRIBUTE7 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE8 = p_OLD_ATTRIBUTE8)
            OR (    ( Recinfo.OLD_ATTRIBUTE8 IS NULL )
                AND (  p_OLD_ATTRIBUTE8 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE8 = p_NEW_ATTRIBUTE8)
            OR (    ( Recinfo.NEW_ATTRIBUTE8 IS NULL )
                AND (  p_NEW_ATTRIBUTE8 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE9 = p_OLD_ATTRIBUTE9)
            OR (    ( Recinfo.OLD_ATTRIBUTE9 IS NULL )
                AND (  p_OLD_ATTRIBUTE9 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE9 = p_NEW_ATTRIBUTE9)
            OR (    ( Recinfo.NEW_ATTRIBUTE9 IS NULL )
                AND (  p_NEW_ATTRIBUTE9 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE10 = p_OLD_ATTRIBUTE10)
            OR (    ( Recinfo.OLD_ATTRIBUTE10 IS NULL )
                AND (  p_OLD_ATTRIBUTE10 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE10 = p_NEW_ATTRIBUTE10)
            OR (    ( Recinfo.NEW_ATTRIBUTE10 IS NULL )
                AND (  p_NEW_ATTRIBUTE10 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE11 = p_OLD_ATTRIBUTE11)
            OR (    ( Recinfo.OLD_ATTRIBUTE11 IS NULL )
                AND (  p_OLD_ATTRIBUTE11 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE11 = p_NEW_ATTRIBUTE11)
            OR (    ( Recinfo.NEW_ATTRIBUTE11 IS NULL )
                AND (  p_NEW_ATTRIBUTE11 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE12 = p_OLD_ATTRIBUTE12)
            OR (    ( Recinfo.OLD_ATTRIBUTE12 IS NULL )
                AND (  p_OLD_ATTRIBUTE12 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE12 = p_NEW_ATTRIBUTE12)
            OR (    ( Recinfo.NEW_ATTRIBUTE12 IS NULL )
                AND (  p_NEW_ATTRIBUTE12 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE13 = p_OLD_ATTRIBUTE13)
            OR (    ( Recinfo.OLD_ATTRIBUTE13 IS NULL )
                AND (  p_OLD_ATTRIBUTE13 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE13 = p_NEW_ATTRIBUTE13)
            OR (    ( Recinfo.NEW_ATTRIBUTE13 IS NULL )
                AND (  p_NEW_ATTRIBUTE13 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE14 = p_OLD_ATTRIBUTE14)
            OR (    ( Recinfo.OLD_ATTRIBUTE14 IS NULL )
                AND (  p_OLD_ATTRIBUTE14 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE14 = p_NEW_ATTRIBUTE14)
            OR (    ( Recinfo.NEW_ATTRIBUTE14 IS NULL )
                AND (  p_NEW_ATTRIBUTE14 IS NULL )))
       AND (    ( Recinfo.OLD_ATTRIBUTE15 = p_OLD_ATTRIBUTE15)
            OR (    ( Recinfo.OLD_ATTRIBUTE15 IS NULL )
                AND (  p_OLD_ATTRIBUTE15 IS NULL )))
       AND (    ( Recinfo.NEW_ATTRIBUTE15 = p_NEW_ATTRIBUTE15)
            OR (    ( Recinfo.NEW_ATTRIBUTE15 IS NULL )
                AND (  p_NEW_ATTRIBUTE15 IS NULL )))
       AND (    ( Recinfo.FULL_DUMP_FLAG = p_FULL_DUMP_FLAG)
            OR (    ( Recinfo.FULL_DUMP_FLAG IS NULL )
                AND (  p_FULL_DUMP_FLAG IS NULL )))
       AND (    ( Recinfo.CREATED_BY = p_CREATED_BY)
            OR (    ( Recinfo.CREATED_BY IS NULL )
                AND (  p_CREATED_BY IS NULL )))
       AND (    ( Recinfo.CREATION_DATE = p_CREATION_DATE)
            OR (    ( Recinfo.CREATION_DATE IS NULL )
                AND (  p_CREATION_DATE IS NULL )))
       AND (    ( Recinfo.LAST_UPDATED_BY = p_LAST_UPDATED_BY)
            OR (    ( Recinfo.LAST_UPDATED_BY IS NULL )
                AND (  p_LAST_UPDATED_BY IS NULL )))
       AND (    ( Recinfo.LAST_UPDATE_DATE = p_LAST_UPDATE_DATE)
            OR (    ( Recinfo.LAST_UPDATE_DATE IS NULL )
                AND (  p_LAST_UPDATE_DATE IS NULL )))
       AND (    ( Recinfo.LAST_UPDATE_LOGIN = p_LAST_UPDATE_LOGIN)
            OR (    ( Recinfo.LAST_UPDATE_LOGIN IS NULL )
                AND (  p_LAST_UPDATE_LOGIN IS NULL )))
       AND (    ( Recinfo.OBJECT_VERSION_NUMBER = p_OBJECT_VERSION_NUMBER)
            OR (    ( Recinfo.OBJECT_VERSION_NUMBER IS NULL )
                AND (  p_OBJECT_VERSION_NUMBER IS NULL )))
       AND (    ( Recinfo.OLD_PRIMARY_FLAG = p_OLD_PRIMARY_FLAG)
            OR (    ( Recinfo.OLD_PRIMARY_FLAG IS NULL )
                AND (  p_OLD_PRIMARY_FLAG IS NULL )))
       AND (    ( Recinfo.NEW_PRIMARY_FLAG = p_NEW_PRIMARY_FLAG)
            OR (    ( Recinfo.NEW_PRIMARY_FLAG IS NULL )
                AND (  p_NEW_PRIMARY_FLAG IS NULL )))
       AND (    ( Recinfo.OLD_PREFERRED_FLAG = p_OLD_PREFERRED_FLAG)
            OR (    ( Recinfo.OLD_PREFERRED_FLAG IS NULL )
                AND (  p_OLD_PREFERRED_FLAG IS NULL )))
       AND (    ( Recinfo.NEW_PREFERRED_FLAG = p_NEW_PREFERRED_FLAG)
            OR (    ( Recinfo.NEW_PREFERRED_FLAG IS NULL )
                AND (  p_NEW_PREFERRED_FLAG IS NULL )))
       ) then
       return;
   else
       FND_MESSAGE.SET_NAME('FND', 'FORM_RECORD_CHANGED');
       APP_EXCEPTION.RAISE_EXCEPTION;
   End If;
END Lock_Row;

End CSI_I_PARTIES_H_PKG;

/
