--------------------------------------------------------
--  DDL for Package Body HR_AVM_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_AVM_RKI" as
/* $Header: hravmrhi.pkb 115.1 2002/12/02 15:47:59 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:30:51 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_ATH_VARIABLEMAP_ID in NUMBER
,P_ATH_DSN in VARCHAR2
,P_ATH_TABLENAME in VARCHAR2
,P_ATH_COLUMNNAME in VARCHAR2
,P_ATH_VARNAME in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_AVM_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: HR_AVM_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end HR_AVM_RKI;

/
