--------------------------------------------------------
--  DDL for Package Body HR_FDG_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_FDG_RKI" as
/* $Header: hrfdgrhi.pkb 115.4 2002/12/03 10:53:27 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:30:56 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_FORM_DATA_GROUP_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_APPLICATION_ID in NUMBER
,P_FORM_ID in NUMBER
,P_DATA_GROUP_NAME in VARCHAR2
)is
begin
hr_utility.set_location('Entering: hr_fdg_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: hr_fdg_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end hr_fdg_RKI;

/
