--------------------------------------------------------
--  DDL for Package Body HR_FWN_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_FWN_RKD" as
/* $Header: hrfwnrhi.pkb 115.4 2002/12/03 13:32:42 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:02 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_FORM_WINDOW_ID in NUMBER
,P_OBJECT_VERSION_NUMBER_O in NUMBER
,P_APPLICATION_ID_O in NUMBER
,P_FORM_ID_O in NUMBER
,P_WINDOW_NAME_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: hr_fwn_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: hr_fwn_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end hr_fwn_RKD;

/
