--------------------------------------------------------
--  DDL for Package Body HR_FTP_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_FTP_RKU" as
/* $Header: hrftprhi.pkb 115.3 2002/12/03 13:05:33 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:02 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_EFFECTIVE_DATE in DATE
,P_FORM_TAB_PAGE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_FORM_CANVAS_ID in NUMBER
,P_TAB_PAGE_NAME in VARCHAR2
,P_DISPLAY_ORDER in NUMBER
,P_VISIBLE_OVERRIDE in NUMBER
,P_OBJECT_VERSION_NUMBER_O in NUMBER
,P_FORM_CANVAS_ID_O in NUMBER
,P_TAB_PAGE_NAME_O in VARCHAR2
,P_DISPLAY_ORDER_O in NUMBER
,P_VISIBLE_OVERRIDE_O in NUMBER
)is
begin
hr_utility.set_location('Entering: hr_ftp_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: hr_ftp_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end hr_ftp_RKU;

/
