--------------------------------------------------------
--  DDL for Package Body HR_FORM_DATA_GROUP_ITEMS_BK2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_FORM_DATA_GROUP_ITEMS_BK2" as
/* $Header: hrfgiapi.pkb 115.2 2002/12/08 05:12:25 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:30:57 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_FORM_DATA_GROUP_ITEM_A
(P_FORM_DATA_GROUP_ITEM_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_FORM_DATA_GROUP_ITEMS_BK2.DELETE_FORM_DATA_GROUP_ITEM_A', 10);
hr_utility.set_location(' Leaving: HR_FORM_DATA_GROUP_ITEMS_BK2.DELETE_FORM_DATA_GROUP_ITEM_A', 20);
end DELETE_FORM_DATA_GROUP_ITEM_A;
procedure DELETE_FORM_DATA_GROUP_ITEM_B
(P_FORM_DATA_GROUP_ITEM_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_FORM_DATA_GROUP_ITEMS_BK2.DELETE_FORM_DATA_GROUP_ITEM_B', 10);
hr_utility.set_location(' Leaving: HR_FORM_DATA_GROUP_ITEMS_BK2.DELETE_FORM_DATA_GROUP_ITEM_B', 20);
end DELETE_FORM_DATA_GROUP_ITEM_B;
end HR_FORM_DATA_GROUP_ITEMS_BK2;

/
