--------------------------------------------------------
--  DDL for Package Body HR_HRC_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_HRC_RKI" as
/* $Header: hrhrcrhi.pkb 115.0 2004/01/09 01:12:58 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:04 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_HIERARCHY_ID in NUMBER
,P_HIERARCHY_KEY in VARCHAR2
,P_PARENT_HIERARCHY_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_HRC_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: HR_HRC_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end HR_HRC_RKI;

/
