--------------------------------------------------------
--  DDL for Package Body HR_ITL_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_ITL_RKD" as
/* $Header: hritlrhi.pkb 115.1 2004/04/05 07:21:00 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:05 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_INTEGRATION_ID in NUMBER
,P_LANGUAGE in VARCHAR2
,P_PARTNER_NAME_O in VARCHAR2
,P_SERVICE_NAME_O in VARCHAR2
,P_SOURCE_LANG_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: HR_ITL_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: HR_ITL_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end HR_ITL_RKD;

/
