--------------------------------------------------------
--  DDL for Package Body HR_KI_OPTIONS_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_KI_OPTIONS_BK3" as
/* $Header: hroptapi.pkb 115.0 2004/01/09 02:36:29 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:12 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_OPTION_A
(P_OPTION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_KI_OPTIONS_BK3.DELETE_OPTION_A', 10);
hr_utility.set_location(' Leaving: HR_KI_OPTIONS_BK3.DELETE_OPTION_A', 20);
end DELETE_OPTION_A;
procedure DELETE_OPTION_B
(P_OPTION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_KI_OPTIONS_BK3.DELETE_OPTION_B', 10);
hr_utility.set_location(' Leaving: HR_KI_OPTIONS_BK3.DELETE_OPTION_B', 20);
end DELETE_OPTION_B;
end HR_KI_OPTIONS_BK3;

/
