--------------------------------------------------------
--  DDL for Package Body HR_KI_INTEGRATIONS_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_KI_INTEGRATIONS_BK3" as
/* $Header: hrintapi.pkb 115.1 2004/01/28 23:31:04 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:04 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_INTEGRATION_A
(P_SSO_ENABLED in BOOLEAN
,P_INTEGRATION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_KI_INTEGRATIONS_BK3.DELETE_INTEGRATION_A', 10);
hr_utility.set_location(' Leaving: HR_KI_INTEGRATIONS_BK3.DELETE_INTEGRATION_A', 20);
end DELETE_INTEGRATION_A;
procedure DELETE_INTEGRATION_B
(P_SSO_ENABLED in BOOLEAN
,P_INTEGRATION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_KI_INTEGRATIONS_BK3.DELETE_INTEGRATION_B', 10);
hr_utility.set_location(' Leaving: HR_KI_INTEGRATIONS_BK3.DELETE_INTEGRATION_B', 20);
end DELETE_INTEGRATION_B;
end HR_KI_INTEGRATIONS_BK3;

/
