--------------------------------------------------------
--  DDL for Package Body HR_LOT_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_LOT_RKI" as
/* $Header: hrlotrhi.pkb 115.10 2002/12/04 05:45:04 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:10 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_LOCATION_ID in NUMBER
,P_LANGUAGE in VARCHAR2
,P_SOURCE_LANG in VARCHAR2
,P_LOCATION_CODE in VARCHAR2
,P_DESCRIPTION in VARCHAR2
)is
begin
hr_utility.set_location('Entering: HR_LOT_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: HR_LOT_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end HR_LOT_RKI;

/
