--------------------------------------------------------
--  DDL for Package Body HR_OBJECTIVES_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_OBJECTIVES_BK3" as
/* $Header: peobjapi.pkb 120.4 2006/03/20 14:07:58 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:32:29 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_OBJECTIVE_A
(P_OBJECTIVE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_OBJECTIVES_BK3.DELETE_OBJECTIVE_A', 10);
hr_utility.set_location(' Leaving: HR_OBJECTIVES_BK3.DELETE_OBJECTIVE_A', 20);
end DELETE_OBJECTIVE_A;
procedure DELETE_OBJECTIVE_B
(P_OBJECTIVE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_OBJECTIVES_BK3.DELETE_OBJECTIVE_B', 10);
hr_utility.set_location(' Leaving: HR_OBJECTIVES_BK3.DELETE_OBJECTIVE_B', 20);
end DELETE_OBJECTIVE_B;
end HR_OBJECTIVES_BK3;

/
