--------------------------------------------------------
--  DDL for Package Body HR_PDE_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_PDE_RKU" as
/* $Header: hrpderhi.pkb 120.0 2005/09/23 06:44 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:16 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_PERSON_DEPLYMT_EIT_ID in NUMBER
,P_PERSON_DEPLOYMENT_ID in NUMBER
,P_PERSON_EXTRA_INFO_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_PERSON_DEPLOYMENT_ID_O in NUMBER
,P_PERSON_EXTRA_INFO_ID_O in NUMBER
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_PDE_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: HR_PDE_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end HR_PDE_RKU;

/
