--------------------------------------------------------
--  DDL for Package Body HR_PER_DEPLYMT_EIT_BK2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_PER_DEPLYMT_EIT_BK2" as
/* $Header: hrpdeapi.pkb 120.0 2005/09/23 06:44:39 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:16 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_PER_DEPLYMT_EIT_A
(P_PER_DEPLYMT_EIT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_PER_DEPLYMT_EIT_BK2.DELETE_PER_DEPLYMT_EIT_A', 10);
hr_utility.set_location(' Leaving: HR_PER_DEPLYMT_EIT_BK2.DELETE_PER_DEPLYMT_EIT_A', 20);
end DELETE_PER_DEPLYMT_EIT_A;
procedure DELETE_PER_DEPLYMT_EIT_B
(P_PER_DEPLYMT_EIT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_PER_DEPLYMT_EIT_BK2.DELETE_PER_DEPLYMT_EIT_B', 10);
hr_utility.set_location(' Leaving: HR_PER_DEPLYMT_EIT_BK2.DELETE_PER_DEPLYMT_EIT_B', 20);
end DELETE_PER_DEPLYMT_EIT_B;
end HR_PER_DEPLYMT_EIT_BK2;

/
