--------------------------------------------------------
--  DDL for Package Body HR_PERSON_ABSENCE_CASE_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_PERSON_ABSENCE_CASE_BK3" as
/* $Header: peabcapi.pkb 120.1 2006/01/27 12:46:38 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 22:00:53 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_PERSON_ABSENCE_CASE_A
(P_ABSENCE_CASE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_PERSON_ABSENCE_CASE_BK3.DELETE_PERSON_ABSENCE_CASE_A', 10);
hr_utility.set_location(' Leaving: HR_PERSON_ABSENCE_CASE_BK3.DELETE_PERSON_ABSENCE_CASE_A', 20);
end DELETE_PERSON_ABSENCE_CASE_A;
procedure DELETE_PERSON_ABSENCE_CASE_B
(P_ABSENCE_CASE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_PERSON_ABSENCE_CASE_BK3.DELETE_PERSON_ABSENCE_CASE_B', 10);
hr_utility.set_location(' Leaving: HR_PERSON_ABSENCE_CASE_BK3.DELETE_PERSON_ABSENCE_CASE_B', 20);
end DELETE_PERSON_ABSENCE_CASE_B;
end HR_PERSON_ABSENCE_CASE_BK3;

/
