--------------------------------------------------------
--  DDL for Package Body HR_RATING_LEVELS_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_RATING_LEVELS_BK3" as
/* $Header: pertlapi.pkb 120.0 2005/05/31 19:55:21 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:33:12 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_RATING_LEVEL_A
(P_RATING_LEVEL_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_RATING_LEVELS_BK3.DELETE_RATING_LEVEL_A', 10);
hr_utility.set_location(' Leaving: HR_RATING_LEVELS_BK3.DELETE_RATING_LEVEL_A', 20);
end DELETE_RATING_LEVEL_A;
procedure DELETE_RATING_LEVEL_B
(P_RATING_LEVEL_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_RATING_LEVELS_BK3.DELETE_RATING_LEVEL_B', 10);
hr_utility.set_location(' Leaving: HR_RATING_LEVELS_BK3.DELETE_RATING_LEVEL_B', 20);
end DELETE_RATING_LEVEL_B;
end HR_RATING_LEVELS_BK3;

/
