--------------------------------------------------------
--  DDL for Package Body HR_TEMPLATE_ITEMS_API_BK1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HR_TEMPLATE_ITEMS_API_BK1" as
/* $Header: hrtimapi.pkb 120.0 2005/05/31 03:12:42 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:21 (YYYY/MM/DD HH24:MI:SS)
procedure COPY_TEMPLATE_ITEM_A
(P_EFFECTIVE_DATE in DATE
,P_LANGUAGE_CODE in VARCHAR2
,P_TEMPLATE_ITEM_ID_FROM in NUMBER
,P_FORM_TEMPLATE_ID in NUMBER
,P_TEMPLATE_ITEM_ID_TO in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_TEMPLATE_ITEMS_API_BK1.COPY_TEMPLATE_ITEM_A', 10);
hr_utility.set_location(' Leaving: HR_TEMPLATE_ITEMS_API_BK1.COPY_TEMPLATE_ITEM_A', 20);
end COPY_TEMPLATE_ITEM_A;
procedure COPY_TEMPLATE_ITEM_B
(P_EFFECTIVE_DATE in DATE
,P_LANGUAGE_CODE in VARCHAR2
,P_TEMPLATE_ITEM_ID_FROM in NUMBER
,P_FORM_TEMPLATE_ID in NUMBER
)is
begin
hr_utility.set_location('Entering: HR_TEMPLATE_ITEMS_API_BK1.COPY_TEMPLATE_ITEM_B', 10);
hr_utility.set_location(' Leaving: HR_TEMPLATE_ITEMS_API_BK1.COPY_TEMPLATE_ITEM_B', 20);
end COPY_TEMPLATE_ITEM_B;
end HR_TEMPLATE_ITEMS_API_BK1;

/
