--------------------------------------------------------
--  DDL for Package Body HRDPP_CREATE_IN_PERSON_ADDRESS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HRDPP_CREATE_IN_PERSON_ADDRESS" as
/*
 * Generated by hr_pump_meta_mapper at: 2007/01/04 09:01:54
 * Generated for API: hr_in_person_address_api.create_in_person_address
 */
--
dh constant date := hr_api.g_date;
nh constant number := hr_api.g_number;
vh constant varchar2(64) := hr_api.g_varchar2;
c_sot constant date := to_date('01010001','DDMMYYYY');
cn constant varchar2(32) := '<NULL>';
dn constant date := null;
nn constant number := null;
vn constant varchar2(1) := null;
--
function dc(p in date) return varchar2 is
begin
if p<c_sot then
 if p<>trunc(p) then
  return to_char(p,'SYYYY/MM/DD HH24:MI:SS');
 end if;
 return to_char(p,'SYYYY/MM/DD');
elsif p<>trunc(p) then
 return to_char(p,'YYYY/MM/DD HH24:MI:SS');
end if;
return to_char(p,'YYYY/MM/DD');
end dc;
function d(p in varchar2) return date is
begin
if length(p)=10 then
return to_date(p,'YYYY/MM/DD');
elsif length(p)=19 then
return to_date(p,'YYYY/MM/DD HH24:MI:SS');
elsif length(p)=11 then
return to_date(p,'SYYYY/MM/DD');
elsif length(p)=20 then
return to_date(p,'SYYYY/MM/DD HH24:MI:SS');
end if;
-- Try default format as last resort.
return to_date(p,'YYYY/MM/DD');
end d;
function n(p in varchar2) return number is
begin
return to_number(p);
end n;
function dd(p in date,i in varchar2)
return varchar2 is
begin
if upper(i) = 'N' then return dc(p);
else return cn; end if;
end dd;
function nd(p in number,i in varchar2)
return varchar2 is
begin
if upper(i) = 'N' then return to_char(p);
else return cn; end if;
end nd;
--
procedure iuk
(p_batch_line_id  in number,
p_user_key_value in varchar2,
p_unique_key_id  in number)
is
begin
hr_data_pump.entry('ins_user_key');
insert into hr_pump_batch_line_user_keys
(user_key_id, batch_line_id,user_key_value,unique_key_id)
values
(hr_pump_batch_line_user_keys_s.nextval,
p_batch_line_id,
p_user_key_value,
p_unique_key_id);
hr_data_pump.exit('ins_user_key');
end iuk;
--
procedure insert_batch_lines
(p_batch_id      in number
,p_data_pump_batch_line_id in number default null
,p_data_pump_business_grp_name in varchar2 default null
,p_user_sequence in number default null
,p_link_value    in number default null
,P_EFFECTIVE_DATE in date
,P_PRADD_OVLAPVAL_OVERRIDE in boolean default null
,P_PRIMARY_FLAG in varchar2
,P_DATE_FROM in date
,P_DATE_TO in date default null
,P_ADDRESS_TYPE in varchar2 default null
,P_COMMENTS in long default null
,P_FLAT_DOOR_BLOCK in varchar2
,P_BUILDING_VILLAGE in varchar2 default null
,P_ROAD_STREET in varchar2 default null
,P_AREA_LOCALITY in varchar2 default null
,P_TOWN_OR_CITY in varchar2
,P_STATE_UT in varchar2 default null
,P_PIN_CODE in varchar2 default null
,P_ADDR_ATTRIBUTE_CATEGORY in varchar2 default null
,P_ADDR_ATTRIBUTE1 in varchar2 default null
,P_ADDR_ATTRIBUTE2 in varchar2 default null
,P_ADDR_ATTRIBUTE3 in varchar2 default null
,P_ADDR_ATTRIBUTE4 in varchar2 default null
,P_ADDR_ATTRIBUTE5 in varchar2 default null
,P_ADDR_ATTRIBUTE6 in varchar2 default null
,P_ADDR_ATTRIBUTE7 in varchar2 default null
,P_ADDR_ATTRIBUTE8 in varchar2 default null
,P_ADDR_ATTRIBUTE9 in varchar2 default null
,P_ADDR_ATTRIBUTE10 in varchar2 default null
,P_ADDR_ATTRIBUTE11 in varchar2 default null
,P_ADDR_ATTRIBUTE12 in varchar2 default null
,P_ADDR_ATTRIBUTE13 in varchar2 default null
,P_ADDR_ATTRIBUTE14 in varchar2 default null
,P_ADDR_ATTRIBUTE15 in varchar2 default null
,P_ADDR_ATTRIBUTE16 in varchar2 default null
,P_ADDR_ATTRIBUTE17 in varchar2 default null
,P_ADDR_ATTRIBUTE18 in varchar2 default null
,P_ADDR_ATTRIBUTE19 in varchar2 default null
,P_ADDR_ATTRIBUTE20 in varchar2 default null
,P_ADDRESS_USER_KEY in varchar2
,P_PERSON_USER_KEY in varchar2 default null
,P_COUNTRY in varchar2 default null) is
blid number := p_data_pump_batch_line_id;
 L_PRADD_OVLAPVAL_OVERRIDE varchar2(5);
begin
if P_PRADD_OVLAPVAL_OVERRIDE is null then
 L_PRADD_OVLAPVAL_OVERRIDE := null;
elsif P_PRADD_OVLAPVAL_OVERRIDE then
 L_PRADD_OVLAPVAL_OVERRIDE := 'TRUE';
else 
 L_PRADD_OVLAPVAL_OVERRIDE := 'FALSE';
end if;
if blid is not null then
delete from hr_pump_batch_lines where batch_line_id = blid;
delete from hr_pump_batch_exceptions
where source_type = 'BATCH_LINE' and source_id = blid;
end if;
insert into hr_pump_batch_lines
(batch_id
,batch_line_id
,business_group_name
,api_module_id
,line_status
,user_sequence
,link_value
,pval001
,pval002
,pval003
,pval004
,pval005
,pval006
,plongval
,pval008
,pval009
,pval010
,pval011
,pval012
,pval013
,pval014
,pval015
,pval016
,pval017
,pval018
,pval019
,pval020
,pval021
,pval022
,pval023
,pval024
,pval025
,pval026
,pval027
,pval028
,pval029
,pval030
,pval031
,pval032
,pval033
,pval034
,pval035
,pval036
,pval038
,pval039)
values
(p_batch_id
,nvl(blid,hr_pump_batch_lines_s.nextval)
,p_data_pump_business_grp_name
,3217
,'U'
,p_user_sequence
,p_link_value
,dc(P_EFFECTIVE_DATE)
,L_PRADD_OVLAPVAL_OVERRIDE
,P_PRIMARY_FLAG
,dc(P_DATE_FROM)
,dc(P_DATE_TO)
,P_ADDRESS_TYPE
,P_COMMENTS
,P_FLAT_DOOR_BLOCK
,P_BUILDING_VILLAGE
,P_ROAD_STREET
,P_AREA_LOCALITY
,P_TOWN_OR_CITY
,P_STATE_UT
,P_PIN_CODE
,P_ADDR_ATTRIBUTE_CATEGORY
,P_ADDR_ATTRIBUTE1
,P_ADDR_ATTRIBUTE2
,P_ADDR_ATTRIBUTE3
,P_ADDR_ATTRIBUTE4
,P_ADDR_ATTRIBUTE5
,P_ADDR_ATTRIBUTE6
,P_ADDR_ATTRIBUTE7
,P_ADDR_ATTRIBUTE8
,P_ADDR_ATTRIBUTE9
,P_ADDR_ATTRIBUTE10
,P_ADDR_ATTRIBUTE11
,P_ADDR_ATTRIBUTE12
,P_ADDR_ATTRIBUTE13
,P_ADDR_ATTRIBUTE14
,P_ADDR_ATTRIBUTE15
,P_ADDR_ATTRIBUTE16
,P_ADDR_ATTRIBUTE17
,P_ADDR_ATTRIBUTE18
,P_ADDR_ATTRIBUTE19
,P_ADDR_ATTRIBUTE20
,P_ADDRESS_USER_KEY
,P_PERSON_USER_KEY
,P_COUNTRY);
end insert_batch_lines;
--
procedure call
(p_business_group_id in number,
p_batch_line_id     in number) is
cursor cr is
select l.rowid myrowid,
decode(l.pval001,cn,dn,d(l.pval001)) p1,
decode(l.pval002,cn,vn,vn,null,l.pval002) p2,
l.pval002 d2,
decode(l.pval003,cn,vn,
 hr_pump_get.gl(l.pval003,'YES_NO',d(l.pval001),vn)) p3,
decode(l.pval004,cn,dn,d(l.pval004)) p4,
decode(l.pval005,cn,dn,vn,dn,d(l.pval005)) p5,
l.pval005 d5,
decode(l.pval006,cn,vn,vn,vn,
 hr_pump_get.gl(l.pval006,'ADDRESS_TYPE',d(l.pval001),vn)) p6,
l.pval006 d6,
l.plongval plongval,
decode(l.pval008,cn,vn,l.pval008) p8,
decode(l.pval009,cn,vn,vn,vn,l.pval009) p9,
l.pval009 d9,
decode(l.pval010,cn,vn,vn,vn,l.pval010) p10,
l.pval010 d10,
decode(l.pval011,cn,vn,vn,vn,l.pval011) p11,
l.pval011 d11,
decode(l.pval012,cn,vn,l.pval012) p12,
decode(l.pval013,cn,vn,vn,vn,
 hr_pump_get.gl(l.pval013,'IN_STATES',d(l.pval001),vn)) p13,
l.pval013 d13,
decode(l.pval014,cn,vn,vn,vn,l.pval014) p14,
l.pval014 d14,
decode(l.pval015,cn,vn,vn,vn,l.pval015) p15,
l.pval015 d15,
decode(l.pval016,cn,vn,vn,vn,l.pval016) p16,
l.pval016 d16,
decode(l.pval017,cn,vn,vn,vn,l.pval017) p17,
l.pval017 d17,
decode(l.pval018,cn,vn,vn,vn,l.pval018) p18,
l.pval018 d18,
decode(l.pval019,cn,vn,vn,vn,l.pval019) p19,
l.pval019 d19,
decode(l.pval020,cn,vn,vn,vn,l.pval020) p20,
l.pval020 d20,
decode(l.pval021,cn,vn,vn,vn,l.pval021) p21,
l.pval021 d21,
decode(l.pval022,cn,vn,vn,vn,l.pval022) p22,
l.pval022 d22,
decode(l.pval023,cn,vn,vn,vn,l.pval023) p23,
l.pval023 d23,
decode(l.pval024,cn,vn,vn,vn,l.pval024) p24,
l.pval024 d24,
decode(l.pval025,cn,vn,vn,vn,l.pval025) p25,
l.pval025 d25,
decode(l.pval026,cn,vn,vn,vn,l.pval026) p26,
l.pval026 d26,
decode(l.pval027,cn,vn,vn,vn,l.pval027) p27,
l.pval027 d27,
decode(l.pval028,cn,vn,vn,vn,l.pval028) p28,
l.pval028 d28,
decode(l.pval029,cn,vn,vn,vn,l.pval029) p29,
l.pval029 d29,
decode(l.pval030,cn,vn,vn,vn,l.pval030) p30,
l.pval030 d30,
decode(l.pval031,cn,vn,vn,vn,l.pval031) p31,
l.pval031 d31,
decode(l.pval032,cn,vn,vn,vn,l.pval032) p32,
l.pval032 d32,
decode(l.pval033,cn,vn,vn,vn,l.pval033) p33,
l.pval033 d33,
decode(l.pval034,cn,vn,vn,vn,l.pval034) p34,
l.pval034 d34,
decode(l.pval035,cn,vn,vn,vn,l.pval035) p35,
l.pval035 d35,
l.pval036 p36,
l.pval037 p37,
decode(l.pval038,cn,vn,vn,vn,l.pval038) p38,
l.pval038 d38,
decode(l.pval039,cn,vn,vn,vn,l.pval039) p39,
l.pval039 d39
from hr_pump_batch_lines l
where l.batch_line_id = p_batch_line_id;
--
c cr%rowtype;
l_validate boolean := false;
L_PRADD_OVLAPVAL_OVERRIDE boolean;
L_COMMENTS varchar2(32767);
L_ADDRESS_ID number;
L_PERSON_ID number;
L_COUNTRY varchar2(2000);
--
begin
hr_data_pump.entry('call');
open cr;
fetch cr into c;
if cr%notfound then
hr_utility.set_message(800,'HR_50326_DP_NO_ROW');
hr_utility.set_message_token('TABLE','HR_PUMP_BATCH_LINES');
hr_utility.set_message_token('COLUMN','P_BATCH_LINE_ID');
hr_utility.set_message_token('VALUE',p_batch_line_id);
hr_utility.raise_error;
end if;
--
if upper(c.p2) = 'TRUE' then
L_PRADD_OVLAPVAL_OVERRIDE := true;
elsif upper(c.p2) = 'FALSE' then
L_PRADD_OVLAPVAL_OVERRIDE := false;
elsif c.p2 is not null then
hr_utility.set_message(800,'HR_50327_DP_TYPE_ERR');
hr_utility.set_message_token('TYPE','BOOLEAN');
hr_utility.set_message_token('PARAMETER','P_PRADD_OVLAPVAL_OVERRIDE');
hr_utility.set_message_token('VALUE',c.p2);
hr_utility.set_message_token('TABLE','HR_PUMP_BATCH_LINES');
hr_utility.raise_error;
end if;
--
L_COMMENTS := c.plongval;
if L_COMMENTS = cn then
L_COMMENTS := null;
end if;
--
if c.p38 is null then
L_PERSON_ID:=nn;
else
L_PERSON_ID := 
hr_pump_get.get_person_id
(P_PERSON_USER_KEY => c.p38);
end if;
--
if c.p39 is null then
L_COUNTRY:=vn;
else
L_COUNTRY := 
hr_pump_get.GET_COUNTRY
(P_COUNTRY => c.p39);
end if;
--
hr_data_pump.api_trc_on;
hr_in_person_address_api.create_in_person_address
(p_validate => l_validate
,P_EFFECTIVE_DATE => c.p1
,P_PRADD_OVLAPVAL_OVERRIDE => L_PRADD_OVLAPVAL_OVERRIDE
,P_PERSON_ID => L_PERSON_ID
,P_PRIMARY_FLAG => c.p3
,P_DATE_FROM => c.p4
,P_DATE_TO => c.p5
,P_ADDRESS_TYPE => c.p6
,P_COUNTRY => L_COUNTRY
,P_COMMENTS => L_COMMENTS
,P_FLAT_DOOR_BLOCK => c.p8
,P_BUILDING_VILLAGE => c.p9
,P_ROAD_STREET => c.p10
,P_AREA_LOCALITY => c.p11
,P_TOWN_OR_CITY => c.p12
,P_STATE_UT => c.p13
,P_PIN_CODE => c.p14
,P_ADDR_ATTRIBUTE_CATEGORY => c.p15
,P_ADDR_ATTRIBUTE1 => c.p16
,P_ADDR_ATTRIBUTE2 => c.p17
,P_ADDR_ATTRIBUTE3 => c.p18
,P_ADDR_ATTRIBUTE4 => c.p19
,P_ADDR_ATTRIBUTE5 => c.p20
,P_ADDR_ATTRIBUTE6 => c.p21
,P_ADDR_ATTRIBUTE7 => c.p22
,P_ADDR_ATTRIBUTE8 => c.p23
,P_ADDR_ATTRIBUTE9 => c.p24
,P_ADDR_ATTRIBUTE10 => c.p25
,P_ADDR_ATTRIBUTE11 => c.p26
,P_ADDR_ATTRIBUTE12 => c.p27
,P_ADDR_ATTRIBUTE13 => c.p28
,P_ADDR_ATTRIBUTE14 => c.p29
,P_ADDR_ATTRIBUTE15 => c.p30
,P_ADDR_ATTRIBUTE16 => c.p31
,P_ADDR_ATTRIBUTE17 => c.p32
,P_ADDR_ATTRIBUTE18 => c.p33
,P_ADDR_ATTRIBUTE19 => c.p34
,P_ADDR_ATTRIBUTE20 => c.p35
,P_ADDRESS_ID => L_ADDRESS_ID
,P_OBJECT_VERSION_NUMBER => c.p37);
hr_data_pump.api_trc_off;
--
iuk(p_batch_line_id,c.p36,L_ADDRESS_ID);
--
update hr_pump_batch_lines l set
l.pval036 = decode(c.p36,null,cn,c.p36),
l.pval037 = decode(c.p37,null,cn,c.p37)
where l.rowid = c.myrowid;
--
close cr;
--
hr_data_pump.exit('call');
exception
 when hr_multi_message.error_message_exist then
   if cr%isopen then
    close cr;
   end if;
   hr_pump_utils.set_multi_msg_error_flag(true);
 when others then
 if cr%isopen then
  close cr;
 end if;
 raise;
end call;
end hrdpp_create_in_person_address;

/
