--------------------------------------------------------
--  DDL for Package Body HXC_DATA_APP_RULE_USAGES_BK_3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HXC_DATA_APP_RULE_USAGES_BK_3" as
/* $Header: hxcdruapi.pkb 120.0 2005/05/29 05:29:17 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:57:53 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_DATA_APP_RULE_USAGES_A
(P_DATA_APP_RULE_USAGE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HXC_DATA_APP_RULE_USAGES_BK_3.DELETE_DATA_APP_RULE_USAGES_A', 10);
hr_utility.set_location(' Leaving: HXC_DATA_APP_RULE_USAGES_BK_3.DELETE_DATA_APP_RULE_USAGES_A', 20);
end DELETE_DATA_APP_RULE_USAGES_A;
procedure DELETE_DATA_APP_RULE_USAGES_B
(P_DATA_APP_RULE_USAGE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: HXC_DATA_APP_RULE_USAGES_BK_3.DELETE_DATA_APP_RULE_USAGES_B', 10);
hr_utility.set_location(' Leaving: HXC_DATA_APP_RULE_USAGES_BK_3.DELETE_DATA_APP_RULE_USAGES_B', 20);
end DELETE_DATA_APP_RULE_USAGES_B;
end HXC_DATA_APP_RULE_USAGES_BK_3;

/
