--------------------------------------------------------
--  DDL for Package Body HXC_HAN_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HXC_HAN_RKD" as
/* $Header: hxchanrhi.pkb 120.2 2006/07/10 10:09:56 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:57:54 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_COMP_NOTIFICATION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_NOTIFICATION_NUM_RETRIES_O in NUMBER
,P_NOTIFICATION_TIMEOUT_VALUE_O in NUMBER
,P_NOTIFICATION_ACTION_CODE_O in VARCHAR2
,P_NOTIFICATION_RECIP_CODE_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: HXC_HAN_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: HXC_HAN_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end HXC_HAN_RKD;

/
