--------------------------------------------------------
--  DDL for Package Body HXC_TIME_CATEGORY_BK_2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HXC_TIME_CATEGORY_BK_2" as
/* $Header: hxchtcapi.pkb 120.0 2005/05/29 05:41:32 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:58:00 (YYYY/MM/DD HH24:MI:SS)
procedure UPDATE_TIME_CATEGORY_A
(P_TIME_CATEGORY_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_TIME_CATEGORY_NAME in VARCHAR2
,P_OPERATOR in VARCHAR2
,P_DESCRIPTION in VARCHAR2
,P_DISPLAY in VARCHAR2
)is
begin
hr_utility.set_location('Entering: HXC_TIME_CATEGORY_BK_2.UPDATE_TIME_CATEGORY_A', 10);
hr_utility.set_location(' Leaving: HXC_TIME_CATEGORY_BK_2.UPDATE_TIME_CATEGORY_A', 20);
end UPDATE_TIME_CATEGORY_A;
procedure UPDATE_TIME_CATEGORY_B
(P_TIME_CATEGORY_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_TIME_CATEGORY_NAME in VARCHAR2
,P_OPERATOR in VARCHAR2
,P_DESCRIPTION in VARCHAR2
,P_DISPLAY in VARCHAR2
)is
begin
hr_utility.set_location('Entering: HXC_TIME_CATEGORY_BK_2.UPDATE_TIME_CATEGORY_B', 10);
hr_utility.set_location(' Leaving: HXC_TIME_CATEGORY_BK_2.UPDATE_TIME_CATEGORY_B', 20);
end UPDATE_TIME_CATEGORY_B;
end HXC_TIME_CATEGORY_BK_2;

/
