--------------------------------------------------------
--  DDL for Package Body HXC_MAP_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HXC_MAP_RKU" as
/* $Header: hxcmaprhi.pkb 120.2 2005/09/23 08:17:59 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 21:57:40 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_MAPPING_ID in NUMBER
,P_NAME in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_NAME_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: HXC_MAP_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: HXC_MAP_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end HXC_MAP_RKU;

/
