--------------------------------------------------------
--  DDL for Package Body HXC_MPC_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HXC_MPC_RKU" as
/* $Header: hxcmpcrhi.pkb 120.2 2005/09/23 08:47:45 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 08:58:02 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_MAPPING_COMPONENT_ID in NUMBER
,P_FIELD_NAME in VARCHAR2
,P_NAME in VARCHAR2
,P_BLD_BLK_INFO_TYPE_ID in NUMBER
,P_SEGMENT in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_FIELD_NAME_O in VARCHAR2
,P_NAME_O in VARCHAR2
,P_BLD_BLK_INFO_TYPE_ID_O in NUMBER
,P_SEGMENT_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: HXC_MPC_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: HXC_MPC_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end HXC_MPC_RKU;

/
