--------------------------------------------------------
--  DDL for Package Body HZ_PER_PROFILES_EXT_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HZ_PER_PROFILES_EXT_PKG" as
/* $Header: ARHEXPPB.pls 120.1 2006/02/09 10:16:18 jhuang noship $ */

procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_EXTENSION_ID IN NUMBER,
  X_PERSON_PROFILE_ID IN NUMBER,
  X_OLD_EXTENSION_ID IN NUMBER,
  X_ATTR_GROUP_ID IN NUMBER,
  X_C_EXT_ATTR1 IN VARCHAR2,
  X_C_EXT_ATTR2 IN VARCHAR2,
  X_C_EXT_ATTR3 IN VARCHAR2,
  X_C_EXT_ATTR4 IN VARCHAR2,
  X_C_EXT_ATTR5 IN VARCHAR2,
  X_C_EXT_ATTR6 IN VARCHAR2,
  X_C_EXT_ATTR7 IN VARCHAR2,
  X_C_EXT_ATTR8 IN VARCHAR2,
  X_C_EXT_ATTR9 IN VARCHAR2,
  X_C_EXT_ATTR10 IN VARCHAR2,
  X_C_EXT_ATTR11 IN VARCHAR2,
  X_C_EXT_ATTR12 IN VARCHAR2,
  X_C_EXT_ATTR13 IN VARCHAR2,
  X_C_EXT_ATTR14 IN VARCHAR2,
  X_C_EXT_ATTR15 IN VARCHAR2,
  X_C_EXT_ATTR16 IN VARCHAR2,
  X_C_EXT_ATTR17 IN VARCHAR2,
  X_C_EXT_ATTR18 IN VARCHAR2,
  X_C_EXT_ATTR19 IN VARCHAR2,
  X_C_EXT_ATTR20 IN VARCHAR2,
  X_N_EXT_ATTR1 IN NUMBER,
  X_N_EXT_ATTR2 IN NUMBER,
  X_N_EXT_ATTR3 IN NUMBER,
  X_N_EXT_ATTR4 IN NUMBER,
  X_N_EXT_ATTR5 IN NUMBER,
  X_N_EXT_ATTR6 IN NUMBER,
  X_N_EXT_ATTR7 IN NUMBER,
  X_N_EXT_ATTR8 IN NUMBER,
  X_N_EXT_ATTR9 IN NUMBER,
  X_N_EXT_ATTR10 IN NUMBER,
  X_N_EXT_ATTR11 IN NUMBER,
  X_N_EXT_ATTR12 IN NUMBER,
  X_N_EXT_ATTR13 IN NUMBER,
  X_N_EXT_ATTR14 IN NUMBER,
  X_N_EXT_ATTR15 IN NUMBER,
  X_N_EXT_ATTR16 IN NUMBER,
  X_N_EXT_ATTR17 IN NUMBER,
  X_N_EXT_ATTR18 IN NUMBER,
  X_N_EXT_ATTR19 IN NUMBER,
  X_N_EXT_ATTR20 IN NUMBER,
  X_D_EXT_ATTR1 IN DATE,
  X_D_EXT_ATTR2 IN DATE,
  X_D_EXT_ATTR3 IN DATE,
  X_D_EXT_ATTR4 IN DATE,
  X_D_EXT_ATTR5 IN DATE,
  X_D_EXT_ATTR6 IN DATE,
  X_D_EXT_ATTR7 IN DATE,
  X_D_EXT_ATTR8 IN DATE,
  X_D_EXT_ATTR9 IN DATE,
  X_D_EXT_ATTR10 IN DATE,
  X_TL_EXT_ATTR1 IN VARCHAR2,
  X_TL_EXT_ATTR2 IN VARCHAR2,
  X_TL_EXT_ATTR3 IN VARCHAR2,
  X_TL_EXT_ATTR4 IN VARCHAR2,
  X_TL_EXT_ATTR5 IN VARCHAR2,
  X_TL_EXT_ATTR6 IN VARCHAR2,
  X_TL_EXT_ATTR7 IN VARCHAR2,
  X_TL_EXT_ATTR8 IN VARCHAR2,
  X_TL_EXT_ATTR9 IN VARCHAR2,
  X_TL_EXT_ATTR10 IN VARCHAR2,
  X_TL_EXT_ATTR11 IN VARCHAR2,
  X_TL_EXT_ATTR12 IN VARCHAR2,
  X_TL_EXT_ATTR13 IN VARCHAR2,
  X_TL_EXT_ATTR14 IN VARCHAR2,
  X_TL_EXT_ATTR15 IN VARCHAR2,
  X_TL_EXT_ATTR16 IN VARCHAR2,
  X_TL_EXT_ATTR17 IN VARCHAR2,
  X_TL_EXT_ATTR18 IN VARCHAR2,
  X_TL_EXT_ATTR19 IN VARCHAR2,
  X_TL_EXT_ATTR20 IN VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
) is
  cursor C is select ROWID from HZ_PER_PROFILES_EXT_B
    where EXTENSION_ID = X_EXTENSION_ID
    ;
begin
  insert into HZ_PER_PROFILES_EXT_B (
    EXTENSION_ID,
    PERSON_PROFILE_ID,
    ATTR_GROUP_ID,
    C_EXT_ATTR1,
    C_EXT_ATTR2,
    C_EXT_ATTR3,
    C_EXT_ATTR4,
    C_EXT_ATTR5,
    C_EXT_ATTR6,
    C_EXT_ATTR7,
    C_EXT_ATTR8,
    C_EXT_ATTR9,
    C_EXT_ATTR10,
    C_EXT_ATTR11,
    C_EXT_ATTR12,
    C_EXT_ATTR13,
    C_EXT_ATTR14,
    C_EXT_ATTR15,
    C_EXT_ATTR16,
    C_EXT_ATTR17,
    C_EXT_ATTR18,
    C_EXT_ATTR19,
    C_EXT_ATTR20,
    N_EXT_ATTR1,
    N_EXT_ATTR2,
    N_EXT_ATTR3,
    N_EXT_ATTR4,
    N_EXT_ATTR5,
    N_EXT_ATTR6,
    N_EXT_ATTR7,
    N_EXT_ATTR8,
    N_EXT_ATTR9,
    N_EXT_ATTR10,
    N_EXT_ATTR11,
    N_EXT_ATTR12,
    N_EXT_ATTR13,
    N_EXT_ATTR14,
    N_EXT_ATTR15,
    N_EXT_ATTR16,
    N_EXT_ATTR17,
    N_EXT_ATTR18,
    N_EXT_ATTR19,
    N_EXT_ATTR20,
    D_EXT_ATTR1,
    D_EXT_ATTR2,
    D_EXT_ATTR3,
    D_EXT_ATTR4,
    D_EXT_ATTR5,
    D_EXT_ATTR6,
    D_EXT_ATTR7,
    D_EXT_ATTR8,
    D_EXT_ATTR9,
    D_EXT_ATTR10,
    OLD_EXTENSION_ID,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN
  ) values (
    X_EXTENSION_ID,
    X_PERSON_PROFILE_ID,
    X_ATTR_GROUP_ID,
    X_C_EXT_ATTR1,
    X_C_EXT_ATTR2,
    X_C_EXT_ATTR3,
    X_C_EXT_ATTR4,
    X_C_EXT_ATTR5,
    X_C_EXT_ATTR6,
    X_C_EXT_ATTR7,
    X_C_EXT_ATTR8,
    X_C_EXT_ATTR9,
    X_C_EXT_ATTR10,
    X_C_EXT_ATTR11,
    X_C_EXT_ATTR12,
    X_C_EXT_ATTR13,
    X_C_EXT_ATTR14,
    X_C_EXT_ATTR15,
    X_C_EXT_ATTR16,
    X_C_EXT_ATTR17,
    X_C_EXT_ATTR18,
    X_C_EXT_ATTR19,
    X_C_EXT_ATTR20,
    X_N_EXT_ATTR1,
    X_N_EXT_ATTR2,
    X_N_EXT_ATTR3,
    X_N_EXT_ATTR4,
    X_N_EXT_ATTR5,
    X_N_EXT_ATTR6,
    X_N_EXT_ATTR7,
    X_N_EXT_ATTR8,
    X_N_EXT_ATTR9,
    X_N_EXT_ATTR10,
    X_N_EXT_ATTR11,
    X_N_EXT_ATTR12,
    X_N_EXT_ATTR13,
    X_N_EXT_ATTR14,
    X_N_EXT_ATTR15,
    X_N_EXT_ATTR16,
    X_N_EXT_ATTR17,
    X_N_EXT_ATTR18,
    X_N_EXT_ATTR19,
    X_N_EXT_ATTR20,
    X_D_EXT_ATTR1,
    X_D_EXT_ATTR2,
    X_D_EXT_ATTR3,
    X_D_EXT_ATTR4,
    X_D_EXT_ATTR5,
    X_D_EXT_ATTR6,
    X_D_EXT_ATTR7,
    X_D_EXT_ATTR8,
    X_D_EXT_ATTR9,
    X_D_EXT_ATTR10,
    X_OLD_EXTENSION_ID,
    X_CREATION_DATE,
    X_CREATED_BY,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN
  );

  insert into HZ_PER_PROFILES_EXT_TL (
    EXTENSION_ID,
    PERSON_PROFILE_ID,
    ATTR_GROUP_ID,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TL_EXT_ATTR1,
    TL_EXT_ATTR2,
    TL_EXT_ATTR3,
    TL_EXT_ATTR4,
    TL_EXT_ATTR5,
    TL_EXT_ATTR6,
    TL_EXT_ATTR7,
    TL_EXT_ATTR8,
    TL_EXT_ATTR9,
    TL_EXT_ATTR10,
    TL_EXT_ATTR11,
    TL_EXT_ATTR12,
    TL_EXT_ATTR13,
    TL_EXT_ATTR14,
    TL_EXT_ATTR15,
    TL_EXT_ATTR16,
    TL_EXT_ATTR17,
    TL_EXT_ATTR18,
    TL_EXT_ATTR19,
    TL_EXT_ATTR20,
    LANGUAGE,
    SOURCE_LANG
  ) select
    X_EXTENSION_ID,
    X_PERSON_PROFILE_ID,
    X_ATTR_GROUP_ID,
    X_CREATED_BY,
    X_CREATION_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATE_LOGIN,
    X_TL_EXT_ATTR1,
    X_TL_EXT_ATTR2,
    X_TL_EXT_ATTR3,
    X_TL_EXT_ATTR4,
    X_TL_EXT_ATTR5,
    X_TL_EXT_ATTR6,
    X_TL_EXT_ATTR7,
    X_TL_EXT_ATTR8,
    X_TL_EXT_ATTR9,
    X_TL_EXT_ATTR10,
    X_TL_EXT_ATTR11,
    X_TL_EXT_ATTR12,
    X_TL_EXT_ATTR13,
    X_TL_EXT_ATTR14,
    X_TL_EXT_ATTR15,
    X_TL_EXT_ATTR16,
    X_TL_EXT_ATTR17,
    X_TL_EXT_ATTR18,
    X_TL_EXT_ATTR19,
    X_TL_EXT_ATTR20,
    L.LANGUAGE_CODE,
    userenv('LANG')
  from FND_LANGUAGES L
  where L.INSTALLED_FLAG in ('I', 'B')
  and not exists
    (select NULL
    from HZ_PER_PROFILES_EXT_TL T
    where T.EXTENSION_ID = X_EXTENSION_ID
    and T.LANGUAGE = L.LANGUAGE_CODE);

  open c;
  fetch c into X_ROWID;
  if (c%notfound) then
    close c;
    raise no_data_found;
  end if;
  close c;

end INSERT_ROW;

procedure LOCK_ROW (
  X_EXTENSION_ID IN NUMBER,
  X_PERSON_PROFILE_ID IN NUMBER,
  X_OLD_EXTENSION_ID IN NUMBER,
  X_ATTR_GROUP_ID IN NUMBER,
  X_C_EXT_ATTR1 IN VARCHAR2,
  X_C_EXT_ATTR2 IN VARCHAR2,
  X_C_EXT_ATTR3 IN VARCHAR2,
  X_C_EXT_ATTR4 IN VARCHAR2,
  X_C_EXT_ATTR5 IN VARCHAR2,
  X_C_EXT_ATTR6 IN VARCHAR2,
  X_C_EXT_ATTR7 IN VARCHAR2,
  X_C_EXT_ATTR8 IN VARCHAR2,
  X_C_EXT_ATTR9 IN VARCHAR2,
  X_C_EXT_ATTR10 IN VARCHAR2,
  X_C_EXT_ATTR11 IN VARCHAR2,
  X_C_EXT_ATTR12 IN VARCHAR2,
  X_C_EXT_ATTR13 IN VARCHAR2,
  X_C_EXT_ATTR14 IN VARCHAR2,
  X_C_EXT_ATTR15 IN VARCHAR2,
  X_C_EXT_ATTR16 IN VARCHAR2,
  X_C_EXT_ATTR17 IN VARCHAR2,
  X_C_EXT_ATTR18 IN VARCHAR2,
  X_C_EXT_ATTR19 IN VARCHAR2,
  X_C_EXT_ATTR20 IN VARCHAR2,
  X_N_EXT_ATTR1 IN NUMBER,
  X_N_EXT_ATTR2 IN NUMBER,
  X_N_EXT_ATTR3 IN NUMBER,
  X_N_EXT_ATTR4 IN NUMBER,
  X_N_EXT_ATTR5 IN NUMBER,
  X_N_EXT_ATTR6 IN NUMBER,
  X_N_EXT_ATTR7 IN NUMBER,
  X_N_EXT_ATTR8 IN NUMBER,
  X_N_EXT_ATTR9 IN NUMBER,
  X_N_EXT_ATTR10 IN NUMBER,
  X_N_EXT_ATTR11 IN NUMBER,
  X_N_EXT_ATTR12 IN NUMBER,
  X_N_EXT_ATTR13 IN NUMBER,
  X_N_EXT_ATTR14 IN NUMBER,
  X_N_EXT_ATTR15 IN NUMBER,
  X_N_EXT_ATTR16 IN NUMBER,
  X_N_EXT_ATTR17 IN NUMBER,
  X_N_EXT_ATTR18 IN NUMBER,
  X_N_EXT_ATTR19 IN NUMBER,
  X_N_EXT_ATTR20 IN NUMBER,
  X_D_EXT_ATTR1 IN DATE,
  X_D_EXT_ATTR2 IN DATE,
  X_D_EXT_ATTR3 IN DATE,
  X_D_EXT_ATTR4 IN DATE,
  X_D_EXT_ATTR5 IN DATE,
  X_D_EXT_ATTR6 IN DATE,
  X_D_EXT_ATTR7 IN DATE,
  X_D_EXT_ATTR8 IN DATE,
  X_D_EXT_ATTR9 IN DATE,
  X_D_EXT_ATTR10 IN DATE,
  X_TL_EXT_ATTR1 IN VARCHAR2,
  X_TL_EXT_ATTR2 IN VARCHAR2,
  X_TL_EXT_ATTR3 IN VARCHAR2,
  X_TL_EXT_ATTR4 IN VARCHAR2,
  X_TL_EXT_ATTR5 IN VARCHAR2,
  X_TL_EXT_ATTR6 IN VARCHAR2,
  X_TL_EXT_ATTR7 IN VARCHAR2,
  X_TL_EXT_ATTR8 IN VARCHAR2,
  X_TL_EXT_ATTR9 IN VARCHAR2,
  X_TL_EXT_ATTR10 IN VARCHAR2,
  X_TL_EXT_ATTR11 IN VARCHAR2,
  X_TL_EXT_ATTR12 IN VARCHAR2,
  X_TL_EXT_ATTR13 IN VARCHAR2,
  X_TL_EXT_ATTR14 IN VARCHAR2,
  X_TL_EXT_ATTR15 IN VARCHAR2,
  X_TL_EXT_ATTR16 IN VARCHAR2,
  X_TL_EXT_ATTR17 IN VARCHAR2,
  X_TL_EXT_ATTR18 IN VARCHAR2,
  X_TL_EXT_ATTR19 IN VARCHAR2,
  X_TL_EXT_ATTR20 IN VARCHAR2
) is
  cursor c is select
      PERSON_PROFILE_ID,
      ATTR_GROUP_ID,
      C_EXT_ATTR1,
      C_EXT_ATTR2,
      C_EXT_ATTR3,
      C_EXT_ATTR4,
      C_EXT_ATTR5,
      C_EXT_ATTR6,
      C_EXT_ATTR7,
      C_EXT_ATTR8,
      C_EXT_ATTR9,
      C_EXT_ATTR10,
      C_EXT_ATTR11,
      C_EXT_ATTR12,
      C_EXT_ATTR13,
      C_EXT_ATTR14,
      C_EXT_ATTR15,
      C_EXT_ATTR16,
      C_EXT_ATTR17,
      C_EXT_ATTR18,
      C_EXT_ATTR19,
      C_EXT_ATTR20,
      N_EXT_ATTR1,
      N_EXT_ATTR2,
      N_EXT_ATTR3,
      N_EXT_ATTR4,
      N_EXT_ATTR5,
      N_EXT_ATTR6,
      N_EXT_ATTR7,
      N_EXT_ATTR8,
      N_EXT_ATTR9,
      N_EXT_ATTR10,
      N_EXT_ATTR11,
      N_EXT_ATTR12,
      N_EXT_ATTR13,
      N_EXT_ATTR14,
      N_EXT_ATTR15,
      N_EXT_ATTR16,
      N_EXT_ATTR17,
      N_EXT_ATTR18,
      N_EXT_ATTR19,
      N_EXT_ATTR20,
      D_EXT_ATTR1,
      D_EXT_ATTR2,
      D_EXT_ATTR3,
      D_EXT_ATTR4,
      D_EXT_ATTR5,
      D_EXT_ATTR6,
      D_EXT_ATTR7,
      D_EXT_ATTR8,
      D_EXT_ATTR9,
      D_EXT_ATTR10,
      OLD_EXTENSION_ID
    from HZ_PER_PROFILES_EXT_B
    where EXTENSION_ID = X_EXTENSION_ID
    for update of EXTENSION_ID nowait;
  recinfo c%rowtype;

  cursor c1 is select
      TL_EXT_ATTR1,
      TL_EXT_ATTR2,
      TL_EXT_ATTR3,
      TL_EXT_ATTR4,
      TL_EXT_ATTR5,
      TL_EXT_ATTR6,
      TL_EXT_ATTR7,
      TL_EXT_ATTR8,
      TL_EXT_ATTR9,
      TL_EXT_ATTR10,
      TL_EXT_ATTR11,
      TL_EXT_ATTR12,
      TL_EXT_ATTR13,
      TL_EXT_ATTR14,
      TL_EXT_ATTR15,
      TL_EXT_ATTR16,
      TL_EXT_ATTR17,
      TL_EXT_ATTR18,
      TL_EXT_ATTR19,
      TL_EXT_ATTR20,
      decode(LANGUAGE, userenv('LANG'), 'Y', 'N') BASELANG
    from HZ_PER_PROFILES_EXT_TL
    where EXTENSION_ID = X_EXTENSION_ID
    and userenv('LANG') in (LANGUAGE, SOURCE_LANG)
    for update of EXTENSION_ID nowait;
begin
  open c;
  fetch c into recinfo;
  if (c%notfound) then
    close c;
    fnd_message.set_name('FND', 'FORM_RECORD_DELETED');
    app_exception.raise_exception;
  end if;
  close c;
  if (    (recinfo.PERSON_PROFILE_ID = X_PERSON_PROFILE_ID)
      AND (recinfo.ATTR_GROUP_ID = X_ATTR_GROUP_ID)
      AND ((recinfo.C_EXT_ATTR1 = X_C_EXT_ATTR1)
           OR ((recinfo.C_EXT_ATTR1 is null) AND (X_C_EXT_ATTR1 is null)))
      AND ((recinfo.C_EXT_ATTR2 = X_C_EXT_ATTR2)
           OR ((recinfo.C_EXT_ATTR2 is null) AND (X_C_EXT_ATTR2 is null)))
      AND ((recinfo.C_EXT_ATTR3 = X_C_EXT_ATTR3)
           OR ((recinfo.C_EXT_ATTR3 is null) AND (X_C_EXT_ATTR3 is null)))
      AND ((recinfo.C_EXT_ATTR4 = X_C_EXT_ATTR4)
           OR ((recinfo.C_EXT_ATTR4 is null) AND (X_C_EXT_ATTR4 is null)))
      AND ((recinfo.C_EXT_ATTR5 = X_C_EXT_ATTR5)
           OR ((recinfo.C_EXT_ATTR5 is null) AND (X_C_EXT_ATTR5 is null)))
      AND ((recinfo.C_EXT_ATTR6 = X_C_EXT_ATTR6)
           OR ((recinfo.C_EXT_ATTR6 is null) AND (X_C_EXT_ATTR6 is null)))
      AND ((recinfo.C_EXT_ATTR7 = X_C_EXT_ATTR7)
           OR ((recinfo.C_EXT_ATTR7 is null) AND (X_C_EXT_ATTR7 is null)))
      AND ((recinfo.C_EXT_ATTR8 = X_C_EXT_ATTR8)
           OR ((recinfo.C_EXT_ATTR8 is null) AND (X_C_EXT_ATTR8 is null)))
      AND ((recinfo.C_EXT_ATTR9 = X_C_EXT_ATTR9)
           OR ((recinfo.C_EXT_ATTR9 is null) AND (X_C_EXT_ATTR9 is null)))
      AND ((recinfo.C_EXT_ATTR10 = X_C_EXT_ATTR10)
           OR ((recinfo.C_EXT_ATTR10 is null) AND (X_C_EXT_ATTR10 is null)))
      AND ((recinfo.C_EXT_ATTR11 = X_C_EXT_ATTR11)
           OR ((recinfo.C_EXT_ATTR11 is null) AND (X_C_EXT_ATTR11 is null)))
      AND ((recinfo.C_EXT_ATTR12 = X_C_EXT_ATTR12)
           OR ((recinfo.C_EXT_ATTR12 is null) AND (X_C_EXT_ATTR12 is null)))
      AND ((recinfo.C_EXT_ATTR13 = X_C_EXT_ATTR13)
           OR ((recinfo.C_EXT_ATTR13 is null) AND (X_C_EXT_ATTR13 is null)))
      AND ((recinfo.C_EXT_ATTR14 = X_C_EXT_ATTR14)
           OR ((recinfo.C_EXT_ATTR14 is null) AND (X_C_EXT_ATTR14 is null)))
      AND ((recinfo.C_EXT_ATTR15 = X_C_EXT_ATTR15)
           OR ((recinfo.C_EXT_ATTR15 is null) AND (X_C_EXT_ATTR15 is null)))
      AND ((recinfo.C_EXT_ATTR16 = X_C_EXT_ATTR16)
           OR ((recinfo.C_EXT_ATTR16 is null) AND (X_C_EXT_ATTR16 is null)))
      AND ((recinfo.C_EXT_ATTR17 = X_C_EXT_ATTR17)
           OR ((recinfo.C_EXT_ATTR17 is null) AND (X_C_EXT_ATTR17 is null)))
      AND ((recinfo.C_EXT_ATTR18 = X_C_EXT_ATTR18)
           OR ((recinfo.C_EXT_ATTR18 is null) AND (X_C_EXT_ATTR18 is null)))
      AND ((recinfo.C_EXT_ATTR19 = X_C_EXT_ATTR19)
           OR ((recinfo.C_EXT_ATTR19 is null) AND (X_C_EXT_ATTR19 is null)))
      AND ((recinfo.C_EXT_ATTR20 = X_C_EXT_ATTR20)
           OR ((recinfo.C_EXT_ATTR20 is null) AND (X_C_EXT_ATTR20 is null)))
      AND ((recinfo.N_EXT_ATTR1 = X_N_EXT_ATTR1)
           OR ((recinfo.N_EXT_ATTR1 is null) AND (X_N_EXT_ATTR1 is null)))
      AND ((recinfo.N_EXT_ATTR2 = X_N_EXT_ATTR2)
           OR ((recinfo.N_EXT_ATTR2 is null) AND (X_N_EXT_ATTR2 is null)))
      AND ((recinfo.N_EXT_ATTR3 = X_N_EXT_ATTR3)
           OR ((recinfo.N_EXT_ATTR3 is null) AND (X_N_EXT_ATTR3 is null)))
      AND ((recinfo.N_EXT_ATTR4 = X_N_EXT_ATTR4)
           OR ((recinfo.N_EXT_ATTR4 is null) AND (X_N_EXT_ATTR4 is null)))
      AND ((recinfo.N_EXT_ATTR5 = X_N_EXT_ATTR5)
           OR ((recinfo.N_EXT_ATTR5 is null) AND (X_N_EXT_ATTR5 is null)))
      AND ((recinfo.N_EXT_ATTR6 = X_N_EXT_ATTR6)
           OR ((recinfo.N_EXT_ATTR6 is null) AND (X_N_EXT_ATTR6 is null)))
      AND ((recinfo.N_EXT_ATTR7 = X_N_EXT_ATTR7)
           OR ((recinfo.N_EXT_ATTR7 is null) AND (X_N_EXT_ATTR7 is null)))
      AND ((recinfo.N_EXT_ATTR8 = X_N_EXT_ATTR8)
           OR ((recinfo.N_EXT_ATTR8 is null) AND (X_N_EXT_ATTR8 is null)))
      AND ((recinfo.N_EXT_ATTR9 = X_N_EXT_ATTR9)
           OR ((recinfo.N_EXT_ATTR9 is null) AND (X_N_EXT_ATTR9 is null)))
      AND ((recinfo.N_EXT_ATTR10 = X_N_EXT_ATTR10)
           OR ((recinfo.N_EXT_ATTR10 is null) AND (X_N_EXT_ATTR10 is null)))
      AND ((recinfo.N_EXT_ATTR11 = X_N_EXT_ATTR11)
           OR ((recinfo.N_EXT_ATTR11 is null) AND (X_N_EXT_ATTR11 is null)))
      AND ((recinfo.N_EXT_ATTR12 = X_N_EXT_ATTR12)
           OR ((recinfo.N_EXT_ATTR12 is null) AND (X_N_EXT_ATTR12 is null)))
      AND ((recinfo.N_EXT_ATTR13 = X_N_EXT_ATTR13)
           OR ((recinfo.N_EXT_ATTR13 is null) AND (X_N_EXT_ATTR13 is null)))
      AND ((recinfo.N_EXT_ATTR14 = X_N_EXT_ATTR14)
           OR ((recinfo.N_EXT_ATTR14 is null) AND (X_N_EXT_ATTR14 is null)))
      AND ((recinfo.N_EXT_ATTR15 = X_N_EXT_ATTR15)
           OR ((recinfo.N_EXT_ATTR15 is null) AND (X_N_EXT_ATTR15 is null)))
      AND ((recinfo.N_EXT_ATTR16 = X_N_EXT_ATTR16)
           OR ((recinfo.N_EXT_ATTR16 is null) AND (X_N_EXT_ATTR16 is null)))
      AND ((recinfo.N_EXT_ATTR17 = X_N_EXT_ATTR17)
           OR ((recinfo.N_EXT_ATTR17 is null) AND (X_N_EXT_ATTR17 is null)))
      AND ((recinfo.N_EXT_ATTR18 = X_N_EXT_ATTR18)
           OR ((recinfo.N_EXT_ATTR18 is null) AND (X_N_EXT_ATTR18 is null)))
      AND ((recinfo.N_EXT_ATTR19 = X_N_EXT_ATTR19)
           OR ((recinfo.N_EXT_ATTR19 is null) AND (X_N_EXT_ATTR19 is null)))
      AND ((recinfo.N_EXT_ATTR20 = X_N_EXT_ATTR20)
           OR ((recinfo.N_EXT_ATTR20 is null) AND (X_N_EXT_ATTR20 is null)))
      AND ((recinfo.D_EXT_ATTR1 = X_D_EXT_ATTR1)
           OR ((recinfo.D_EXT_ATTR1 is null) AND (X_D_EXT_ATTR1 is null)))
      AND ((recinfo.D_EXT_ATTR2 = X_D_EXT_ATTR2)
           OR ((recinfo.D_EXT_ATTR2 is null) AND (X_D_EXT_ATTR2 is null)))
      AND ((recinfo.D_EXT_ATTR3 = X_D_EXT_ATTR3)
           OR ((recinfo.D_EXT_ATTR3 is null) AND (X_D_EXT_ATTR3 is null)))
      AND ((recinfo.D_EXT_ATTR4 = X_D_EXT_ATTR4)
           OR ((recinfo.D_EXT_ATTR4 is null) AND (X_D_EXT_ATTR4 is null)))
      AND ((recinfo.D_EXT_ATTR5 = X_D_EXT_ATTR5)
           OR ((recinfo.D_EXT_ATTR5 is null) AND (X_D_EXT_ATTR5 is null)))
      AND ((recinfo.D_EXT_ATTR6 = X_D_EXT_ATTR6)
           OR ((recinfo.D_EXT_ATTR6 is null) AND (X_D_EXT_ATTR6 is null)))
      AND ((recinfo.D_EXT_ATTR7 = X_D_EXT_ATTR7)
           OR ((recinfo.D_EXT_ATTR7 is null) AND (X_D_EXT_ATTR7 is null)))
      AND ((recinfo.D_EXT_ATTR8 = X_D_EXT_ATTR8)
           OR ((recinfo.D_EXT_ATTR8 is null) AND (X_D_EXT_ATTR8 is null)))
      AND ((recinfo.D_EXT_ATTR9 = X_D_EXT_ATTR9)
           OR ((recinfo.D_EXT_ATTR9 is null) AND (X_D_EXT_ATTR9 is null)))
      AND ((recinfo.D_EXT_ATTR10 = X_D_EXT_ATTR10)
           OR ((recinfo.D_EXT_ATTR10 is null) AND (X_D_EXT_ATTR10 is null)))
      AND ((recinfo.OLD_EXTENSION_ID = X_OLD_EXTENSION_ID)
           OR ((recinfo.OLD_EXTENSION_ID is null) AND (X_OLD_EXTENSION_ID is null)))
  ) then
    null;
  else
    fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
    app_exception.raise_exception;
  end if;

  for tlinfo in c1 loop
    if (tlinfo.BASELANG = 'Y') then
      if (    ((tlinfo.TL_EXT_ATTR1 = X_TL_EXT_ATTR1)
               OR ((tlinfo.TL_EXT_ATTR1 is null) AND (X_TL_EXT_ATTR1 is null)))
          AND ((tlinfo.TL_EXT_ATTR2 = X_TL_EXT_ATTR2)
               OR ((tlinfo.TL_EXT_ATTR2 is null) AND (X_TL_EXT_ATTR2 is null)))
          AND ((tlinfo.TL_EXT_ATTR3 = X_TL_EXT_ATTR3)
               OR ((tlinfo.TL_EXT_ATTR3 is null) AND (X_TL_EXT_ATTR3 is null)))
          AND ((tlinfo.TL_EXT_ATTR4 = X_TL_EXT_ATTR4)
               OR ((tlinfo.TL_EXT_ATTR4 is null) AND (X_TL_EXT_ATTR4 is null)))
          AND ((tlinfo.TL_EXT_ATTR5 = X_TL_EXT_ATTR5)
               OR ((tlinfo.TL_EXT_ATTR5 is null) AND (X_TL_EXT_ATTR5 is null)))
          AND ((tlinfo.TL_EXT_ATTR6 = X_TL_EXT_ATTR6)
               OR ((tlinfo.TL_EXT_ATTR6 is null) AND (X_TL_EXT_ATTR6 is null)))
          AND ((tlinfo.TL_EXT_ATTR7 = X_TL_EXT_ATTR7)
               OR ((tlinfo.TL_EXT_ATTR7 is null) AND (X_TL_EXT_ATTR7 is null)))
          AND ((tlinfo.TL_EXT_ATTR8 = X_TL_EXT_ATTR8)
               OR ((tlinfo.TL_EXT_ATTR8 is null) AND (X_TL_EXT_ATTR8 is null)))
          AND ((tlinfo.TL_EXT_ATTR9 = X_TL_EXT_ATTR9)
               OR ((tlinfo.TL_EXT_ATTR9 is null) AND (X_TL_EXT_ATTR9 is null)))
          AND ((tlinfo.TL_EXT_ATTR10 = X_TL_EXT_ATTR10)
               OR ((tlinfo.TL_EXT_ATTR10 is null) AND (X_TL_EXT_ATTR10 is null)))
          AND ((tlinfo.TL_EXT_ATTR11 = X_TL_EXT_ATTR11)
               OR ((tlinfo.TL_EXT_ATTR11 is null) AND (X_TL_EXT_ATTR11 is null)))
          AND ((tlinfo.TL_EXT_ATTR12 = X_TL_EXT_ATTR12)
               OR ((tlinfo.TL_EXT_ATTR12 is null) AND (X_TL_EXT_ATTR12 is null)))
          AND ((tlinfo.TL_EXT_ATTR13 = X_TL_EXT_ATTR13)
               OR ((tlinfo.TL_EXT_ATTR13 is null) AND (X_TL_EXT_ATTR13 is null)))
          AND ((tlinfo.TL_EXT_ATTR14 = X_TL_EXT_ATTR14)
               OR ((tlinfo.TL_EXT_ATTR14 is null) AND (X_TL_EXT_ATTR14 is null)))
          AND ((tlinfo.TL_EXT_ATTR15 = X_TL_EXT_ATTR15)
               OR ((tlinfo.TL_EXT_ATTR15 is null) AND (X_TL_EXT_ATTR15 is null)))
          AND ((tlinfo.TL_EXT_ATTR16 = X_TL_EXT_ATTR16)
               OR ((tlinfo.TL_EXT_ATTR16 is null) AND (X_TL_EXT_ATTR16 is null)))
          AND ((tlinfo.TL_EXT_ATTR17 = X_TL_EXT_ATTR17)
               OR ((tlinfo.TL_EXT_ATTR17 is null) AND (X_TL_EXT_ATTR17 is null)))
          AND ((tlinfo.TL_EXT_ATTR18 = X_TL_EXT_ATTR18)
               OR ((tlinfo.TL_EXT_ATTR18 is null) AND (X_TL_EXT_ATTR18 is null)))
          AND ((tlinfo.TL_EXT_ATTR19 = X_TL_EXT_ATTR19)
               OR ((tlinfo.TL_EXT_ATTR19 is null) AND (X_TL_EXT_ATTR19 is null)))
          AND ((tlinfo.TL_EXT_ATTR20 = X_TL_EXT_ATTR20)
               OR ((tlinfo.TL_EXT_ATTR20 is null) AND (X_TL_EXT_ATTR20 is null)))
      ) then
        null;
      else
        fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
        app_exception.raise_exception;
      end if;
    end if;
  end loop;
  return;
end LOCK_ROW;

procedure UPDATE_ROW (
  X_EXTENSION_ID IN NUMBER,
  X_PERSON_PROFILE_ID IN NUMBER,
  X_OLD_EXTENSION_ID IN NUMBER,
  X_ATTR_GROUP_ID IN NUMBER,
  X_C_EXT_ATTR1 IN VARCHAR2,
  X_C_EXT_ATTR2 IN VARCHAR2,
  X_C_EXT_ATTR3 IN VARCHAR2,
  X_C_EXT_ATTR4 IN VARCHAR2,
  X_C_EXT_ATTR5 IN VARCHAR2,
  X_C_EXT_ATTR6 IN VARCHAR2,
  X_C_EXT_ATTR7 IN VARCHAR2,
  X_C_EXT_ATTR8 IN VARCHAR2,
  X_C_EXT_ATTR9 IN VARCHAR2,
  X_C_EXT_ATTR10 IN VARCHAR2,
  X_C_EXT_ATTR11 IN VARCHAR2,
  X_C_EXT_ATTR12 IN VARCHAR2,
  X_C_EXT_ATTR13 IN VARCHAR2,
  X_C_EXT_ATTR14 IN VARCHAR2,
  X_C_EXT_ATTR15 IN VARCHAR2,
  X_C_EXT_ATTR16 IN VARCHAR2,
  X_C_EXT_ATTR17 IN VARCHAR2,
  X_C_EXT_ATTR18 IN VARCHAR2,
  X_C_EXT_ATTR19 IN VARCHAR2,
  X_C_EXT_ATTR20 IN VARCHAR2,
  X_N_EXT_ATTR1 IN NUMBER,
  X_N_EXT_ATTR2 IN NUMBER,
  X_N_EXT_ATTR3 IN NUMBER,
  X_N_EXT_ATTR4 IN NUMBER,
  X_N_EXT_ATTR5 IN NUMBER,
  X_N_EXT_ATTR6 IN NUMBER,
  X_N_EXT_ATTR7 IN NUMBER,
  X_N_EXT_ATTR8 IN NUMBER,
  X_N_EXT_ATTR9 IN NUMBER,
  X_N_EXT_ATTR10 IN NUMBER,
  X_N_EXT_ATTR11 IN NUMBER,
  X_N_EXT_ATTR12 IN NUMBER,
  X_N_EXT_ATTR13 IN NUMBER,
  X_N_EXT_ATTR14 IN NUMBER,
  X_N_EXT_ATTR15 IN NUMBER,
  X_N_EXT_ATTR16 IN NUMBER,
  X_N_EXT_ATTR17 IN NUMBER,
  X_N_EXT_ATTR18 IN NUMBER,
  X_N_EXT_ATTR19 IN NUMBER,
  X_N_EXT_ATTR20 IN NUMBER,
  X_D_EXT_ATTR1 IN DATE,
  X_D_EXT_ATTR2 IN DATE,
  X_D_EXT_ATTR3 IN DATE,
  X_D_EXT_ATTR4 IN DATE,
  X_D_EXT_ATTR5 IN DATE,
  X_D_EXT_ATTR6 IN DATE,
  X_D_EXT_ATTR7 IN DATE,
  X_D_EXT_ATTR8 IN DATE,
  X_D_EXT_ATTR9 IN DATE,
  X_D_EXT_ATTR10 IN DATE,
  X_TL_EXT_ATTR1 IN VARCHAR2,
  X_TL_EXT_ATTR2 IN VARCHAR2,
  X_TL_EXT_ATTR3 IN VARCHAR2,
  X_TL_EXT_ATTR4 IN VARCHAR2,
  X_TL_EXT_ATTR5 IN VARCHAR2,
  X_TL_EXT_ATTR6 IN VARCHAR2,
  X_TL_EXT_ATTR7 IN VARCHAR2,
  X_TL_EXT_ATTR8 IN VARCHAR2,
  X_TL_EXT_ATTR9 IN VARCHAR2,
  X_TL_EXT_ATTR10 IN VARCHAR2,
  X_TL_EXT_ATTR11 IN VARCHAR2,
  X_TL_EXT_ATTR12 IN VARCHAR2,
  X_TL_EXT_ATTR13 IN VARCHAR2,
  X_TL_EXT_ATTR14 IN VARCHAR2,
  X_TL_EXT_ATTR15 IN VARCHAR2,
  X_TL_EXT_ATTR16 IN VARCHAR2,
  X_TL_EXT_ATTR17 IN VARCHAR2,
  X_TL_EXT_ATTR18 IN VARCHAR2,
  X_TL_EXT_ATTR19 IN VARCHAR2,
  X_TL_EXT_ATTR20 IN VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
) is
begin
  update HZ_PER_PROFILES_EXT_B set
    PERSON_PROFILE_ID = X_PERSON_PROFILE_ID,
    ATTR_GROUP_ID = X_ATTR_GROUP_ID,
    C_EXT_ATTR1 = X_C_EXT_ATTR1,
    C_EXT_ATTR2 = X_C_EXT_ATTR2,
    C_EXT_ATTR3 = X_C_EXT_ATTR3,
    C_EXT_ATTR4 = X_C_EXT_ATTR4,
    C_EXT_ATTR5 = X_C_EXT_ATTR5,
    C_EXT_ATTR6 = X_C_EXT_ATTR6,
    C_EXT_ATTR7 = X_C_EXT_ATTR7,
    C_EXT_ATTR8 = X_C_EXT_ATTR8,
    C_EXT_ATTR9 = X_C_EXT_ATTR9,
    C_EXT_ATTR10 = X_C_EXT_ATTR10,
    C_EXT_ATTR11 = X_C_EXT_ATTR11,
    C_EXT_ATTR12 = X_C_EXT_ATTR12,
    C_EXT_ATTR13 = X_C_EXT_ATTR13,
    C_EXT_ATTR14 = X_C_EXT_ATTR14,
    C_EXT_ATTR15 = X_C_EXT_ATTR15,
    C_EXT_ATTR16 = X_C_EXT_ATTR16,
    C_EXT_ATTR17 = X_C_EXT_ATTR17,
    C_EXT_ATTR18 = X_C_EXT_ATTR18,
    C_EXT_ATTR19 = X_C_EXT_ATTR19,
    C_EXT_ATTR20 = X_C_EXT_ATTR20,
    N_EXT_ATTR1 = X_N_EXT_ATTR1,
    N_EXT_ATTR2 = X_N_EXT_ATTR2,
    N_EXT_ATTR3 = X_N_EXT_ATTR3,
    N_EXT_ATTR4 = X_N_EXT_ATTR4,
    N_EXT_ATTR5 = X_N_EXT_ATTR5,
    N_EXT_ATTR6 = X_N_EXT_ATTR6,
    N_EXT_ATTR7 = X_N_EXT_ATTR7,
    N_EXT_ATTR8 = X_N_EXT_ATTR8,
    N_EXT_ATTR9 = X_N_EXT_ATTR9,
    N_EXT_ATTR10 = X_N_EXT_ATTR10,
    N_EXT_ATTR11 = X_N_EXT_ATTR11,
    N_EXT_ATTR12 = X_N_EXT_ATTR12,
    N_EXT_ATTR13 = X_N_EXT_ATTR13,
    N_EXT_ATTR14 = X_N_EXT_ATTR14,
    N_EXT_ATTR15 = X_N_EXT_ATTR15,
    N_EXT_ATTR16 = X_N_EXT_ATTR16,
    N_EXT_ATTR17 = X_N_EXT_ATTR17,
    N_EXT_ATTR18 = X_N_EXT_ATTR18,
    N_EXT_ATTR19 = X_N_EXT_ATTR19,
    N_EXT_ATTR20 = X_N_EXT_ATTR20,
    D_EXT_ATTR1 = X_D_EXT_ATTR1,
    D_EXT_ATTR2 = X_D_EXT_ATTR2,
    D_EXT_ATTR3 = X_D_EXT_ATTR3,
    D_EXT_ATTR4 = X_D_EXT_ATTR4,
    D_EXT_ATTR5 = X_D_EXT_ATTR5,
    D_EXT_ATTR6 = X_D_EXT_ATTR6,
    D_EXT_ATTR7 = X_D_EXT_ATTR7,
    D_EXT_ATTR8 = X_D_EXT_ATTR8,
    D_EXT_ATTR9 = X_D_EXT_ATTR9,
    D_EXT_ATTR10 = X_D_EXT_ATTR10,
    OLD_EXTENSION_ID = X_OLD_EXTENSION_ID,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN
  where EXTENSION_ID = X_EXTENSION_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;

  update HZ_PER_PROFILES_EXT_TL set
    TL_EXT_ATTR1 = X_TL_EXT_ATTR1,
    TL_EXT_ATTR2 = X_TL_EXT_ATTR2,
    TL_EXT_ATTR3 = X_TL_EXT_ATTR3,
    TL_EXT_ATTR4 = X_TL_EXT_ATTR4,
    TL_EXT_ATTR5 = X_TL_EXT_ATTR5,
    TL_EXT_ATTR6 = X_TL_EXT_ATTR6,
    TL_EXT_ATTR7 = X_TL_EXT_ATTR7,
    TL_EXT_ATTR8 = X_TL_EXT_ATTR8,
    TL_EXT_ATTR9 = X_TL_EXT_ATTR9,
    TL_EXT_ATTR10 = X_TL_EXT_ATTR10,
    TL_EXT_ATTR11 = X_TL_EXT_ATTR11,
    TL_EXT_ATTR12 = X_TL_EXT_ATTR12,
    TL_EXT_ATTR13 = X_TL_EXT_ATTR13,
    TL_EXT_ATTR14 = X_TL_EXT_ATTR14,
    TL_EXT_ATTR15 = X_TL_EXT_ATTR15,
    TL_EXT_ATTR16 = X_TL_EXT_ATTR16,
    TL_EXT_ATTR17 = X_TL_EXT_ATTR17,
    TL_EXT_ATTR18 = X_TL_EXT_ATTR18,
    TL_EXT_ATTR19 = X_TL_EXT_ATTR19,
    TL_EXT_ATTR20 = X_TL_EXT_ATTR20,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN,
    SOURCE_LANG = userenv('LANG')
  where EXTENSION_ID = X_EXTENSION_ID
  and userenv('LANG') in (LANGUAGE, SOURCE_LANG);

  if (sql%notfound) then
    raise no_data_found;
  end if;
end UPDATE_ROW;

procedure DELETE_ROW (
  X_EXTENSION_ID IN NUMBER) is
begin
  delete from HZ_PER_PROFILES_EXT_TL
  where EXTENSION_ID = X_EXTENSION_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;

  delete from HZ_PER_PROFILES_EXT_B
  where EXTENSION_ID = X_EXTENSION_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;
end DELETE_ROW;

procedure ADD_LANGUAGE
is
begin
  insert into /*+ append parallel(tt) */ HZ_PER_PROFILES_EXT_TL tt (
    EXTENSION_ID,
    PERSON_PROFILE_ID,
    ATTR_GROUP_ID,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TL_EXT_ATTR1,
    TL_EXT_ATTR2,
    TL_EXT_ATTR3,
    TL_EXT_ATTR4,
    TL_EXT_ATTR5,
    TL_EXT_ATTR6,
    TL_EXT_ATTR7,
    TL_EXT_ATTR8,
    TL_EXT_ATTR9,
    TL_EXT_ATTR10,
    TL_EXT_ATTR11,
    TL_EXT_ATTR12,
    TL_EXT_ATTR13,
    TL_EXT_ATTR14,
    TL_EXT_ATTR15,
    TL_EXT_ATTR16,
    TL_EXT_ATTR17,
    TL_EXT_ATTR18,
    TL_EXT_ATTR19,
    TL_EXT_ATTR20,
    LANGUAGE,
    SOURCE_LANG
  )
  select /*+ parallel(v) parallel(t) use_nl(t) */
    v.EXTENSION_ID,
    v.PERSON_PROFILE_ID,
    v.ATTR_GROUP_ID,
    v.CREATED_BY,
    v.CREATION_DATE,
    v.LAST_UPDATED_BY,
    v.LAST_UPDATE_DATE,
    v.LAST_UPDATE_LOGIN,
    v.TL_EXT_ATTR1,
    v.TL_EXT_ATTR2,
    v.TL_EXT_ATTR3,
    v.TL_EXT_ATTR4,
    v.TL_EXT_ATTR5,
    v.TL_EXT_ATTR6,
    v.TL_EXT_ATTR7,
    v.TL_EXT_ATTR8,
    v.TL_EXT_ATTR9,
    v.TL_EXT_ATTR10,
    v.TL_EXT_ATTR11,
    v.TL_EXT_ATTR12,
    v.TL_EXT_ATTR13,
    v.TL_EXT_ATTR14,
    v.TL_EXT_ATTR15,
    v.TL_EXT_ATTR16,
    v.TL_EXT_ATTR17,
    v.TL_EXT_ATTR18,
    v.TL_EXT_ATTR19,
    v.TL_EXT_ATTR20,
    v.LANGUAGE_CODE,
    v.SOURCE_LANG
  from
  (SELECT /*+ no_merge ordered parallel(b) */
    B.EXTENSION_ID,
    B.PERSON_PROFILE_ID,
    B.ATTR_GROUP_ID,
    B.CREATED_BY,
    B.CREATION_DATE,
    B.LAST_UPDATED_BY,
    B.LAST_UPDATE_DATE,
    B.LAST_UPDATE_LOGIN,
    B.TL_EXT_ATTR1,
    B.TL_EXT_ATTR2,
    B.TL_EXT_ATTR3,
    B.TL_EXT_ATTR4,
    B.TL_EXT_ATTR5,
    B.TL_EXT_ATTR6,
    B.TL_EXT_ATTR7,
    B.TL_EXT_ATTR8,
    B.TL_EXT_ATTR9,
    B.TL_EXT_ATTR10,
    B.TL_EXT_ATTR11,
    B.TL_EXT_ATTR12,
    B.TL_EXT_ATTR13,
    B.TL_EXT_ATTR14,
    B.TL_EXT_ATTR15,
    B.TL_EXT_ATTR16,
    B.TL_EXT_ATTR17,
    B.TL_EXT_ATTR18,
    B.TL_EXT_ATTR19,
    B.TL_EXT_ATTR20,
    L.LANGUAGE_CODE,
    B.SOURCE_LANG
   FROM HZ_PER_PROFILES_EXT_TL B ,
        FND_LANGUAGES L
   WHERE L.INSTALLED_FLAG IN ( 'I','B' )
   AND B.LANGUAGE = USERENV ( 'LANG' )
  ) v, HZ_PER_PROFILES_EXT_TL t
  WHERE t.EXTENSION_ID(+) = v.EXTENSION_ID
  AND t.language(+) = v.language_code
  AND t.EXTENSION_ID IS NULL;
end ADD_LANGUAGE;

procedure LOAD_ROW(
  X_EXTENSION_ID IN NUMBER,
  X_PERSON_PROFILE_ID IN NUMBER,
  X_OLD_EXTENSION_ID IN NUMBER,
  X_ATTR_GROUP_ID IN NUMBER,
  X_C_EXT_ATTR1 IN VARCHAR2,
  X_C_EXT_ATTR2 IN VARCHAR2,
  X_C_EXT_ATTR3 IN VARCHAR2,
  X_C_EXT_ATTR4 IN VARCHAR2,
  X_C_EXT_ATTR5 IN VARCHAR2,
  X_C_EXT_ATTR6 IN VARCHAR2,
  X_C_EXT_ATTR7 IN VARCHAR2,
  X_C_EXT_ATTR8 IN VARCHAR2,
  X_C_EXT_ATTR9 IN VARCHAR2,
  X_C_EXT_ATTR10 IN VARCHAR2,
  X_C_EXT_ATTR11 IN VARCHAR2,
  X_C_EXT_ATTR12 IN VARCHAR2,
  X_C_EXT_ATTR13 IN VARCHAR2,
  X_C_EXT_ATTR14 IN VARCHAR2,
  X_C_EXT_ATTR15 IN VARCHAR2,
  X_C_EXT_ATTR16 IN VARCHAR2,
  X_C_EXT_ATTR17 IN VARCHAR2,
  X_C_EXT_ATTR18 IN VARCHAR2,
  X_C_EXT_ATTR19 IN VARCHAR2,
  X_C_EXT_ATTR20 IN VARCHAR2,
  X_N_EXT_ATTR1 IN NUMBER,
  X_N_EXT_ATTR2 IN NUMBER,
  X_N_EXT_ATTR3 IN NUMBER,
  X_N_EXT_ATTR4 IN NUMBER,
  X_N_EXT_ATTR5 IN NUMBER,
  X_N_EXT_ATTR6 IN NUMBER,
  X_N_EXT_ATTR7 IN NUMBER,
  X_N_EXT_ATTR8 IN NUMBER,
  X_N_EXT_ATTR9 IN NUMBER,
  X_N_EXT_ATTR10 IN NUMBER,
  X_N_EXT_ATTR11 IN NUMBER,
  X_N_EXT_ATTR12 IN NUMBER,
  X_N_EXT_ATTR13 IN NUMBER,
  X_N_EXT_ATTR14 IN NUMBER,
  X_N_EXT_ATTR15 IN NUMBER,
  X_N_EXT_ATTR16 IN NUMBER,
  X_N_EXT_ATTR17 IN NUMBER,
  X_N_EXT_ATTR18 IN NUMBER,
  X_N_EXT_ATTR19 IN NUMBER,
  X_N_EXT_ATTR20 IN NUMBER,
  X_D_EXT_ATTR1 IN DATE,
  X_D_EXT_ATTR2 IN DATE,
  X_D_EXT_ATTR3 IN DATE,
  X_D_EXT_ATTR4 IN DATE,
  X_D_EXT_ATTR5 IN DATE,
  X_D_EXT_ATTR6 IN DATE,
  X_D_EXT_ATTR7 IN DATE,
  X_D_EXT_ATTR8 IN DATE,
  X_D_EXT_ATTR9 IN DATE,
  X_D_EXT_ATTR10 IN DATE,
  X_TL_EXT_ATTR1 IN VARCHAR2,
  X_TL_EXT_ATTR2 IN VARCHAR2,
  X_TL_EXT_ATTR3 IN VARCHAR2,
  X_TL_EXT_ATTR4 IN VARCHAR2,
  X_TL_EXT_ATTR5 IN VARCHAR2,
  X_TL_EXT_ATTR6 IN VARCHAR2,
  X_TL_EXT_ATTR7 IN VARCHAR2,
  X_TL_EXT_ATTR8 IN VARCHAR2,
  X_TL_EXT_ATTR9 IN VARCHAR2,
  X_TL_EXT_ATTR10 IN VARCHAR2,
  X_TL_EXT_ATTR11 IN VARCHAR2,
  X_TL_EXT_ATTR12 IN VARCHAR2,
  X_TL_EXT_ATTR13 IN VARCHAR2,
  X_TL_EXT_ATTR14 IN VARCHAR2,
  X_TL_EXT_ATTR15 IN VARCHAR2,
  X_TL_EXT_ATTR16 IN VARCHAR2,
  X_TL_EXT_ATTR17 IN VARCHAR2,
  X_TL_EXT_ATTR18 IN VARCHAR2,
  X_TL_EXT_ATTR19 IN VARCHAR2,
  X_TL_EXT_ATTR20 IN VARCHAR2,
  X_OWNER in VARCHAR2)
IS
BEGIN
  null;
end LOAD_ROW;


procedure TRANSLATE_ROW (
  X_EXTENSION_ID IN NUMBER,
  X_PERSON_PROFILE_ID IN NUMBER,
  X_OLD_EXTENSION_ID IN NUMBER,
  X_ATTR_GROUP_ID IN NUMBER,
  X_TL_EXT_ATTR1 IN VARCHAR2,
  X_TL_EXT_ATTR2 IN VARCHAR2,
  X_TL_EXT_ATTR3 IN VARCHAR2,
  X_TL_EXT_ATTR4 IN VARCHAR2,
  X_TL_EXT_ATTR5 IN VARCHAR2,
  X_TL_EXT_ATTR6 IN VARCHAR2,
  X_TL_EXT_ATTR7 IN VARCHAR2,
  X_TL_EXT_ATTR8 IN VARCHAR2,
  X_TL_EXT_ATTR9 IN VARCHAR2,
  X_TL_EXT_ATTR10 IN VARCHAR2,
  X_TL_EXT_ATTR11 IN VARCHAR2,
  X_TL_EXT_ATTR12 IN VARCHAR2,
  X_TL_EXT_ATTR13 IN VARCHAR2,
  X_TL_EXT_ATTR14 IN VARCHAR2,
  X_TL_EXT_ATTR15 IN VARCHAR2,
  X_TL_EXT_ATTR16 IN VARCHAR2,
  X_TL_EXT_ATTR17 IN VARCHAR2,
  X_TL_EXT_ATTR18 IN VARCHAR2,
  X_TL_EXT_ATTR19 IN VARCHAR2,
  X_TL_EXT_ATTR20 IN VARCHAR2,
  X_OWNER in VARCHAR2)
IS
BEGIN
  null;
end TRANSLATE_ROW;


end HZ_PER_PROFILES_EXT_PKG;

/
