--------------------------------------------------------
--  DDL for Package Body HZ_PERSON_PROFILES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."HZ_PERSON_PROFILES_PKG" AS
/*$Header: ARHPERTB.pls 115.20 2003/09/03 20:55:33 kttang ship $ */

g_miss_content_source_type                  CONSTANT VARCHAR2(30) := 'USER_ENTERED';
g_sst_source_type                           CONSTANT VARCHAR2(30) := 'SST';

PROCEDURE Insert_Row (
    X_ROWID                                 OUT NOCOPY    ROWID,
    X_PERSON_PROFILE_ID                     IN OUT NOCOPY NUMBER,
    X_PARTY_ID                              IN     NUMBER,
    X_PERSON_NAME                           IN     VARCHAR2,
    X_ATTRIBUTE_CATEGORY                    IN     VARCHAR2,
    X_ATTRIBUTE1                            IN     VARCHAR2,
    X_ATTRIBUTE2                            IN     VARCHAR2,
    X_ATTRIBUTE3                            IN     VARCHAR2,
    X_ATTRIBUTE4                            IN     VARCHAR2,
    X_ATTRIBUTE5                            IN     VARCHAR2,
    X_ATTRIBUTE6                            IN     VARCHAR2,
    X_ATTRIBUTE7                            IN     VARCHAR2,
    X_ATTRIBUTE8                            IN     VARCHAR2,
    X_ATTRIBUTE9                            IN     VARCHAR2,
    X_ATTRIBUTE10                           IN     VARCHAR2,
    X_ATTRIBUTE11                           IN     VARCHAR2,
    X_ATTRIBUTE12                           IN     VARCHAR2,
    X_ATTRIBUTE13                           IN     VARCHAR2,
    X_ATTRIBUTE14                           IN     VARCHAR2,
    X_ATTRIBUTE15                           IN     VARCHAR2,
    X_ATTRIBUTE16                           IN     VARCHAR2,
    X_ATTRIBUTE17                           IN     VARCHAR2,
    X_ATTRIBUTE18                           IN     VARCHAR2,
    X_ATTRIBUTE19                           IN     VARCHAR2,
    X_ATTRIBUTE20                           IN     VARCHAR2,
    X_INTERNAL_FLAG                         IN     VARCHAR2,
    X_PERSON_PRE_NAME_ADJUNCT               IN     VARCHAR2,
    X_PERSON_FIRST_NAME                     IN     VARCHAR2,
    X_PERSON_MIDDLE_NAME                    IN     VARCHAR2,
    X_PERSON_LAST_NAME                      IN     VARCHAR2,
    X_PERSON_NAME_SUFFIX                    IN     VARCHAR2,
    X_PERSON_TITLE                          IN     VARCHAR2,
    X_PERSON_ACADEMIC_TITLE                 IN     VARCHAR2,
    X_PERSON_PREVIOUS_LAST_NAME             IN     VARCHAR2,
    X_PERSON_INITIALS                       IN     VARCHAR2,
    X_KNOWN_AS                              IN     VARCHAR2,
    X_PERSON_NAME_PHONETIC                  IN     VARCHAR2,
    X_PERSON_FIRST_NAME_PHONETIC            IN     VARCHAR2,
    X_PERSON_LAST_NAME_PHONETIC             IN     VARCHAR2,
    X_TAX_REFERENCE                         IN     VARCHAR2,
    X_JGZZ_FISCAL_CODE                      IN     VARCHAR2,
    X_PERSON_IDEN_TYPE                      IN     VARCHAR2,
    X_PERSON_IDENTIFIER                     IN     VARCHAR2,
    X_DATE_OF_BIRTH                         IN     DATE,
    X_PLACE_OF_BIRTH                        IN     VARCHAR2,
    X_DATE_OF_DEATH                         IN     DATE,
    X_DECEASED_FLAG                         IN     VARCHAR2,
    X_GENDER                                IN     VARCHAR2,
    X_DECLARED_ETHNICITY                    IN     VARCHAR2,
    X_MARITAL_STATUS                        IN     VARCHAR2,
    X_MARITAL_STATUS_EFF_DATE               IN     DATE,
    X_PERSONAL_INCOME                       IN     NUMBER,
    X_HEAD_OF_HOUSEHOLD_FLAG                IN     VARCHAR2,
    X_HOUSEHOLD_INCOME                      IN     NUMBER,
    X_HOUSEHOLD_SIZE                        IN     NUMBER,
    X_RENT_OWN_IND                          IN     VARCHAR2,
    X_LAST_KNOWN_GPS                        IN     VARCHAR2,
    X_EFFECTIVE_START_DATE                  IN     DATE,
    X_EFFECTIVE_END_DATE                    IN     DATE,
    X_CONTENT_SOURCE_TYPE                   IN     VARCHAR2,
    X_KNOWN_AS2                             IN     VARCHAR2,
    X_KNOWN_AS3                             IN     VARCHAR2,
    X_KNOWN_AS4                             IN     VARCHAR2,
    X_KNOWN_AS5                             IN     VARCHAR2,
    X_MIDDLE_NAME_PHONETIC                  IN     VARCHAR2,
    X_OBJECT_VERSION_NUMBER                 IN     NUMBER,
    X_CREATED_BY_MODULE                     IN     VARCHAR2,
    X_APPLICATION_ID                        IN     NUMBER,
    X_ACTUAL_CONTENT_SOURCE                 IN     VARCHAR2,
    X_VERSION_NUMBER                 	    IN     NUMBER default 1
  ) IS

    l_success                               VARCHAR2(1) := 'N';

BEGIN

    WHILE l_success = 'N' LOOP
    BEGIN
        INSERT INTO HZ_PERSON_PROFILES (
            PERSON_PROFILE_ID,
            PARTY_ID,
            PERSON_NAME,
            LAST_UPDATE_DATE,
            LAST_UPDATED_BY,
            CREATION_DATE,
            CREATED_BY,
            LAST_UPDATE_LOGIN,
            REQUEST_ID,
            PROGRAM_APPLICATION_ID,
            PROGRAM_ID,
            PROGRAM_UPDATE_DATE,
            ATTRIBUTE_CATEGORY,
            ATTRIBUTE1,
            ATTRIBUTE2,
            ATTRIBUTE3,
            ATTRIBUTE4,
            ATTRIBUTE5,
            ATTRIBUTE6,
            ATTRIBUTE7,
            ATTRIBUTE8,
            ATTRIBUTE9,
            ATTRIBUTE10,
            ATTRIBUTE11,
            ATTRIBUTE12,
            ATTRIBUTE13,
            ATTRIBUTE14,
            ATTRIBUTE15,
            ATTRIBUTE16,
            ATTRIBUTE17,
            ATTRIBUTE18,
            ATTRIBUTE19,
            ATTRIBUTE20,
            INTERNAL_FLAG,
            PERSON_PRE_NAME_ADJUNCT,
            PERSON_FIRST_NAME,
            PERSON_MIDDLE_NAME,
            PERSON_LAST_NAME,
            PERSON_NAME_SUFFIX,
            PERSON_TITLE,
            PERSON_ACADEMIC_TITLE,
            PERSON_PREVIOUS_LAST_NAME,
            PERSON_INITIALS,
            KNOWN_AS,
            PERSON_NAME_PHONETIC,
            PERSON_FIRST_NAME_PHONETIC,
            PERSON_LAST_NAME_PHONETIC,
            TAX_REFERENCE,
            JGZZ_FISCAL_CODE,
            PERSON_IDEN_TYPE,
            PERSON_IDENTIFIER,
            DATE_OF_BIRTH,
            PLACE_OF_BIRTH,
            DATE_OF_DEATH,
            DECEASED_FLAG,
            GENDER,
            DECLARED_ETHNICITY,
            MARITAL_STATUS,
            MARITAL_STATUS_EFFECTIVE_DATE,
            PERSONAL_INCOME,
            HEAD_OF_HOUSEHOLD_FLAG,
            HOUSEHOLD_INCOME,
            HOUSEHOLD_SIZE,
            RENT_OWN_IND,
            LAST_KNOWN_GPS,
            EFFECTIVE_START_DATE,
            EFFECTIVE_END_DATE,
            CONTENT_SOURCE_TYPE,
            KNOWN_AS2,
            KNOWN_AS3,
            KNOWN_AS4,
            KNOWN_AS5,
            MIDDLE_NAME_PHONETIC,
            OBJECT_VERSION_NUMBER,
            CREATED_BY_MODULE,
            APPLICATION_ID,
            ACTUAL_CONTENT_SOURCE,
	    VERSION_NUMBER
        )
        VALUES (
            DECODE( X_PERSON_PROFILE_ID, FND_API.G_MISS_NUM, HZ_PERSON_PROFILES_S.NEXTVAL, NULL, HZ_PERSON_PROFILES_S.NEXTVAL, X_PERSON_PROFILE_ID ),
            DECODE( X_PARTY_ID, FND_API.G_MISS_NUM, NULL, X_PARTY_ID ),
            DECODE( X_PERSON_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_NAME ),
            HZ_UTILITY_V2PUB.LAST_UPDATE_DATE,
            HZ_UTILITY_V2PUB.LAST_UPDATED_BY,
            HZ_UTILITY_V2PUB.CREATION_DATE,
            HZ_UTILITY_V2PUB.CREATED_BY,
            HZ_UTILITY_V2PUB.LAST_UPDATE_LOGIN,
            HZ_UTILITY_V2PUB.REQUEST_ID,
            HZ_UTILITY_V2PUB.PROGRAM_APPLICATION_ID,
            HZ_UTILITY_V2PUB.PROGRAM_ID,
            HZ_UTILITY_V2PUB.PROGRAM_UPDATE_DATE,
            DECODE( X_ATTRIBUTE_CATEGORY, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE_CATEGORY ),
            DECODE( X_ATTRIBUTE1, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE1 ),
            DECODE( X_ATTRIBUTE2, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE2 ),
            DECODE( X_ATTRIBUTE3, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE3 ),
            DECODE( X_ATTRIBUTE4, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE4 ),
            DECODE( X_ATTRIBUTE5, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE5 ),
            DECODE( X_ATTRIBUTE6, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE6 ),
            DECODE( X_ATTRIBUTE7, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE7 ),
            DECODE( X_ATTRIBUTE8, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE8 ),
            DECODE( X_ATTRIBUTE9, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE9 ),
            DECODE( X_ATTRIBUTE10, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE10 ),
            DECODE( X_ATTRIBUTE11, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE11 ),
            DECODE( X_ATTRIBUTE12, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE12 ),
            DECODE( X_ATTRIBUTE13, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE13 ),
            DECODE( X_ATTRIBUTE14, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE14 ),
            DECODE( X_ATTRIBUTE15, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE15 ),
            DECODE( X_ATTRIBUTE16, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE16 ),
            DECODE( X_ATTRIBUTE17, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE17 ),
            DECODE( X_ATTRIBUTE18, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE18 ),
            DECODE( X_ATTRIBUTE19, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE19 ),
            DECODE( X_ATTRIBUTE20, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE20 ),
            DECODE( X_INTERNAL_FLAG, FND_API.G_MISS_CHAR, NULL, X_INTERNAL_FLAG ),
            DECODE( X_PERSON_PRE_NAME_ADJUNCT, FND_API.G_MISS_CHAR, NULL, X_PERSON_PRE_NAME_ADJUNCT ),
            DECODE( X_PERSON_FIRST_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_FIRST_NAME ),
            DECODE( X_PERSON_MIDDLE_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_MIDDLE_NAME ),
            DECODE( X_PERSON_LAST_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_LAST_NAME ),
            DECODE( X_PERSON_NAME_SUFFIX, FND_API.G_MISS_CHAR, NULL, X_PERSON_NAME_SUFFIX ),
            DECODE( X_PERSON_TITLE, FND_API.G_MISS_CHAR, NULL, X_PERSON_TITLE ),
            DECODE( X_PERSON_ACADEMIC_TITLE, FND_API.G_MISS_CHAR, NULL, X_PERSON_ACADEMIC_TITLE ),
            DECODE( X_PERSON_PREVIOUS_LAST_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_PREVIOUS_LAST_NAME ),
            DECODE( X_PERSON_INITIALS, FND_API.G_MISS_CHAR, NULL, X_PERSON_INITIALS ),
            DECODE( X_KNOWN_AS, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS ),
            DECODE( X_PERSON_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_PERSON_NAME_PHONETIC ),
            DECODE( X_PERSON_FIRST_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_PERSON_FIRST_NAME_PHONETIC ),
            DECODE( X_PERSON_LAST_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_PERSON_LAST_NAME_PHONETIC ),
            DECODE( X_TAX_REFERENCE, FND_API.G_MISS_CHAR, NULL, X_TAX_REFERENCE ),
            DECODE( X_JGZZ_FISCAL_CODE, FND_API.G_MISS_CHAR, NULL, X_JGZZ_FISCAL_CODE ),
            DECODE( X_PERSON_IDEN_TYPE, FND_API.G_MISS_CHAR, NULL, X_PERSON_IDEN_TYPE ),
            DECODE( X_PERSON_IDENTIFIER, FND_API.G_MISS_CHAR, NULL, X_PERSON_IDENTIFIER ),
            DECODE( X_DATE_OF_BIRTH, FND_API.G_MISS_DATE, TO_DATE( NULL ), X_DATE_OF_BIRTH ),
            DECODE( X_PLACE_OF_BIRTH, FND_API.G_MISS_CHAR, NULL, X_PLACE_OF_BIRTH ),
            DECODE( X_DATE_OF_DEATH, FND_API.G_MISS_DATE, TO_DATE( NULL ), X_DATE_OF_DEATH ),
            DECODE( X_DECEASED_FLAG, FND_API.G_MISS_CHAR, NULL, X_DECEASED_FLAG ),
            DECODE( X_GENDER, FND_API.G_MISS_CHAR, NULL, X_GENDER ),
            DECODE( X_DECLARED_ETHNICITY, FND_API.G_MISS_CHAR, NULL, X_DECLARED_ETHNICITY ),
            DECODE( X_MARITAL_STATUS, FND_API.G_MISS_CHAR, NULL, X_MARITAL_STATUS ),
            DECODE( X_MARITAL_STATUS_EFF_DATE, FND_API.G_MISS_DATE, TO_DATE( NULL ), X_MARITAL_STATUS_EFF_DATE ),
            DECODE( X_PERSONAL_INCOME, FND_API.G_MISS_NUM, NULL, X_PERSONAL_INCOME ),
            DECODE( X_HEAD_OF_HOUSEHOLD_FLAG, FND_API.G_MISS_CHAR, 'N', NULL, 'N', X_HEAD_OF_HOUSEHOLD_FLAG ),
            DECODE( X_HOUSEHOLD_INCOME, FND_API.G_MISS_NUM, NULL, X_HOUSEHOLD_INCOME ),
            DECODE( X_HOUSEHOLD_SIZE, FND_API.G_MISS_NUM, NULL, X_HOUSEHOLD_SIZE ),
            DECODE( X_RENT_OWN_IND, FND_API.G_MISS_CHAR, NULL, X_RENT_OWN_IND ),
            DECODE( X_LAST_KNOWN_GPS, FND_API.G_MISS_CHAR, NULL, X_LAST_KNOWN_GPS ),
            DECODE( X_EFFECTIVE_START_DATE, FND_API.G_MISS_DATE, trunc(hz_utility_v2pub.CREATION_DATE), NULL, trunc(hz_utility_v2pub.CREATION_DATE), X_EFFECTIVE_START_DATE ),
            DECODE( X_EFFECTIVE_END_DATE, FND_API.G_MISS_DATE, TO_DATE( NULL ), X_EFFECTIVE_END_DATE ),
            DECODE( X_CONTENT_SOURCE_TYPE, FND_API.G_MISS_CHAR, G_MISS_CONTENT_SOURCE_TYPE, NULL, G_MISS_CONTENT_SOURCE_TYPE, X_CONTENT_SOURCE_TYPE ),
            DECODE( X_KNOWN_AS2, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS2 ),
            DECODE( X_KNOWN_AS3, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS3 ),
            DECODE( X_KNOWN_AS4, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS4 ),
            DECODE( X_KNOWN_AS5, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS5 ),
            DECODE( X_MIDDLE_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_MIDDLE_NAME_PHONETIC ),
            DECODE( X_OBJECT_VERSION_NUMBER, FND_API.G_MISS_NUM, NULL, X_OBJECT_VERSION_NUMBER ),
            DECODE( X_CREATED_BY_MODULE, FND_API.G_MISS_CHAR, NULL, X_CREATED_BY_MODULE ),
            DECODE( X_APPLICATION_ID, FND_API.G_MISS_NUM, NULL, X_APPLICATION_ID ),
            DECODE( X_ACTUAL_CONTENT_SOURCE, FND_API.G_MISS_CHAR, G_SST_SOURCE_TYPE, NULL, G_SST_SOURCE_TYPE, X_ACTUAL_CONTENT_SOURCE ),
    	    DECODE( X_VERSION_NUMBER, FND_API.G_MISS_NUM, NULL, X_VERSION_NUMBER )

        ) RETURNING
            ROWID, PERSON_PROFILE_ID
        INTO
            X_ROWID, X_PERSON_PROFILE_ID;

        l_success := 'Y';

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            IF INSTRB( SQLERRM, 'HZ_PERSON_PROFILES_U1' ) <> 0 OR
               INSTRB( SQLERRM, 'HZ_PERSON_PROFILES_PK' ) <> 0
            THEN
            DECLARE
                l_count             NUMBER;
                l_dummy             VARCHAR2(1);
            BEGIN
                l_count := 1;
                WHILE l_count > 0 LOOP
                    SELECT HZ_PERSON_PROFILES_S.NEXTVAL
                    INTO X_PERSON_PROFILE_ID FROM dual;
                    BEGIN
                        SELECT 'Y' INTO l_dummy
                        FROM HZ_PERSON_PROFILES
                        WHERE PERSON_PROFILE_ID = X_PERSON_PROFILE_ID;
                        l_count := 1;
                    EXCEPTION
                        WHEN NO_DATA_FOUND THEN
                            l_count := 0;
                    END;
                END LOOP;
            END;
            ELSE
                RAISE;
            END IF;

    END;
    END LOOP;

END Insert_Row;

PROCEDURE Update_Row (
    X_Rowid                                 IN OUT NOCOPY VARCHAR2,
    X_PERSON_PROFILE_ID                     IN     NUMBER,
    X_PARTY_ID                              IN     NUMBER,
    x_PERSON_NAME                           IN     VARCHAR2,
    X_ATTRIBUTE_CATEGORY                    IN     VARCHAR2,
    X_ATTRIBUTE1                            IN     VARCHAR2,
    X_ATTRIBUTE2                            IN     VARCHAR2,
    X_ATTRIBUTE3                            IN     VARCHAR2,
    X_ATTRIBUTE4                            IN     VARCHAR2,
    X_ATTRIBUTE5                            IN     VARCHAR2,
    X_ATTRIBUTE6                            IN     VARCHAR2,
    X_ATTRIBUTE7                            IN     VARCHAR2,
    X_ATTRIBUTE8                            IN     VARCHAR2,
    X_ATTRIBUTE9                            IN     VARCHAR2,
    X_ATTRIBUTE10                           IN     VARCHAR2,
    X_ATTRIBUTE11                           IN     VARCHAR2,
    X_ATTRIBUTE12                           IN     VARCHAR2,
    X_ATTRIBUTE13                           IN     VARCHAR2,
    X_ATTRIBUTE14                           IN     VARCHAR2,
    X_ATTRIBUTE15                           IN     VARCHAR2,
    X_ATTRIBUTE16                           IN     VARCHAR2,
    X_ATTRIBUTE17                           IN     VARCHAR2,
    X_ATTRIBUTE18                           IN     VARCHAR2,
    X_ATTRIBUTE19                           IN     VARCHAR2,
    X_ATTRIBUTE20                           IN     VARCHAR2,
    X_INTERNAL_FLAG                         IN     VARCHAR2,
    X_PERSON_PRE_NAME_ADJUNCT               IN     VARCHAR2,
    X_PERSON_FIRST_NAME                     IN     VARCHAR2,
    X_PERSON_MIDDLE_NAME                    IN     VARCHAR2,
    X_PERSON_LAST_NAME                      IN     VARCHAR2,
    X_PERSON_NAME_SUFFIX                    IN     VARCHAR2,
    X_PERSON_TITLE                          IN     VARCHAR2,
    X_PERSON_ACADEMIC_TITLE                 IN     VARCHAR2,
    X_PERSON_PREVIOUS_LAST_NAME             IN     VARCHAR2,
    X_PERSON_INITIALS                       IN     VARCHAR2,
    X_KNOWN_AS                              IN     VARCHAR2,
    X_PERSON_NAME_PHONETIC                  IN     VARCHAR2,
    X_PERSON_FIRST_NAME_PHONETIC            IN     VARCHAR2,
    X_PERSON_LAST_NAME_PHONETIC             IN     VARCHAR2,
    X_TAX_REFERENCE                         IN     VARCHAR2,
    X_JGZZ_FISCAL_CODE                      IN     VARCHAR2,
    X_PERSON_IDEN_TYPE                      IN     VARCHAR2,
    X_PERSON_IDENTIFIER                     IN     VARCHAR2,
    X_DATE_OF_BIRTH                         IN     DATE,
    X_PLACE_OF_BIRTH                        IN     VARCHAR2,
    X_DATE_OF_DEATH                         IN     DATE,
    X_DECEASED_FLAG                         IN     VARCHAR2 DEFAULT NULL,
    X_GENDER                                IN     VARCHAR2,
    X_DECLARED_ETHNICITY                    IN     VARCHAR2,
    X_MARITAL_STATUS                        IN     VARCHAR2,
    X_MARITAL_STATUS_EFF_DATE               IN     DATE,
    X_PERSONAL_INCOME                       IN     NUMBER,
    X_HEAD_OF_HOUSEHOLD_FLAG                IN     VARCHAR2,
    X_HOUSEHOLD_INCOME                      IN     NUMBER,
    X_HOUSEHOLD_SIZE                        IN     NUMBER,
    X_RENT_OWN_IND                          IN     VARCHAR2,
    X_LAST_KNOWN_GPS                        IN     VARCHAR2,
    X_EFFECTIVE_START_DATE                  IN     DATE,
    X_EFFECTIVE_END_DATE                    IN     DATE,
    X_CONTENT_SOURCE_TYPE                   IN     VARCHAR2,
    X_KNOWN_AS2                             IN     VARCHAR2,
    X_KNOWN_AS3                             IN     VARCHAR2,
    X_KNOWN_AS4                             IN     VARCHAR2,
    X_KNOWN_AS5                             IN     VARCHAR2,
    X_MIDDLE_NAME_PHONETIC                  IN     VARCHAR2,
    X_OBJECT_VERSION_NUMBER                 IN     NUMBER,
    X_CREATED_BY_MODULE                     IN     VARCHAR2,
    X_APPLICATION_ID                        IN     NUMBER,
    X_ACTUAL_CONTENT_SOURCE                 IN     VARCHAR2 DEFAULT NULL,
    X_VERSION_NUMBER                        IN     NUMBER DEFAULT NULL
) IS

BEGIN

    UPDATE HZ_PERSON_PROFILES SET
        PERSON_PROFILE_ID = DECODE( X_PERSON_PROFILE_ID, NULL, PERSON_PROFILE_ID, FND_API.G_MISS_NUM, NULL, X_PERSON_PROFILE_ID ),
        PARTY_ID = DECODE( X_PARTY_ID, NULL, PARTY_ID, FND_API.G_MISS_NUM, NULL, X_PARTY_ID ),
        PERSON_NAME = DECODE( X_PERSON_NAME, NULL, PERSON_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_NAME),
        LAST_UPDATE_DATE = HZ_UTILITY_V2PUB.LAST_UPDATE_DATE,
        LAST_UPDATED_BY = HZ_UTILITY_V2PUB.LAST_UPDATED_BY,
        CREATION_DATE = CREATION_DATE,
        CREATED_BY = CREATED_BY,
        LAST_UPDATE_LOGIN = HZ_UTILITY_V2PUB.LAST_UPDATE_LOGIN,
        REQUEST_ID = HZ_UTILITY_V2PUB.REQUEST_ID,
        PROGRAM_APPLICATION_ID = HZ_UTILITY_V2PUB.PROGRAM_APPLICATION_ID,
        PROGRAM_ID = HZ_UTILITY_V2PUB.PROGRAM_ID,
        PROGRAM_UPDATE_DATE = HZ_UTILITY_V2PUB.PROGRAM_UPDATE_DATE,
        ATTRIBUTE_CATEGORY = DECODE( X_ATTRIBUTE_CATEGORY, NULL, ATTRIBUTE_CATEGORY, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE_CATEGORY ),
        ATTRIBUTE1 = DECODE( X_ATTRIBUTE1, NULL, ATTRIBUTE1, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE1 ),
        ATTRIBUTE2 = DECODE( X_ATTRIBUTE2, NULL, ATTRIBUTE2, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE2 ),
        ATTRIBUTE3 = DECODE( X_ATTRIBUTE3, NULL, ATTRIBUTE3, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE3 ),
        ATTRIBUTE4 = DECODE( X_ATTRIBUTE4, NULL, ATTRIBUTE4, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE4 ),
        ATTRIBUTE5 = DECODE( X_ATTRIBUTE5, NULL, ATTRIBUTE5, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE5 ),
        ATTRIBUTE6 = DECODE( X_ATTRIBUTE6, NULL, ATTRIBUTE6, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE6 ),
        ATTRIBUTE7 = DECODE( X_ATTRIBUTE7, NULL, ATTRIBUTE7, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE7 ),
        ATTRIBUTE8 = DECODE( X_ATTRIBUTE8, NULL, ATTRIBUTE8, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE8 ),
        ATTRIBUTE9 = DECODE( X_ATTRIBUTE9, NULL, ATTRIBUTE9, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE9 ),
        ATTRIBUTE10 = DECODE( X_ATTRIBUTE10, NULL, ATTRIBUTE10, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE10 ),
        ATTRIBUTE11 = DECODE( X_ATTRIBUTE11, NULL, ATTRIBUTE11, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE11 ),
        ATTRIBUTE12 = DECODE( X_ATTRIBUTE12, NULL, ATTRIBUTE12, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE12 ),
        ATTRIBUTE13 = DECODE( X_ATTRIBUTE13, NULL, ATTRIBUTE13, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE13 ),
        ATTRIBUTE14 = DECODE( X_ATTRIBUTE14, NULL, ATTRIBUTE14, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE14 ),
        ATTRIBUTE15 = DECODE( X_ATTRIBUTE15, NULL, ATTRIBUTE15, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE15 ),
        ATTRIBUTE16 = DECODE( X_ATTRIBUTE16, NULL, ATTRIBUTE16, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE16 ),
        ATTRIBUTE17 = DECODE( X_ATTRIBUTE17, NULL, ATTRIBUTE17, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE17 ),
        ATTRIBUTE18 = DECODE( X_ATTRIBUTE18, NULL, ATTRIBUTE18, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE18 ),
        ATTRIBUTE19 = DECODE( X_ATTRIBUTE19, NULL, ATTRIBUTE19, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE19 ),
        ATTRIBUTE20 = DECODE( X_ATTRIBUTE20, NULL, ATTRIBUTE20, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE20 ),
        INTERNAL_FLAG = DECODE( X_INTERNAL_FLAG, NULL, INTERNAL_FLAG, FND_API.G_MISS_CHAR, NULL, X_INTERNAL_FLAG ),
        PERSON_PRE_NAME_ADJUNCT = DECODE( X_PERSON_PRE_NAME_ADJUNCT, NULL, PERSON_PRE_NAME_ADJUNCT, FND_API.G_MISS_CHAR, NULL, X_PERSON_PRE_NAME_ADJUNCT ),
        PERSON_FIRST_NAME = DECODE( X_PERSON_FIRST_NAME, NULL, PERSON_FIRST_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_FIRST_NAME ),
        PERSON_MIDDLE_NAME = DECODE( X_PERSON_MIDDLE_NAME, NULL, PERSON_MIDDLE_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_MIDDLE_NAME ),
        PERSON_LAST_NAME = DECODE( X_PERSON_LAST_NAME, NULL, PERSON_LAST_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_LAST_NAME ),
        PERSON_NAME_SUFFIX = DECODE( X_PERSON_NAME_SUFFIX, NULL, PERSON_NAME_SUFFIX, FND_API.G_MISS_CHAR, NULL, X_PERSON_NAME_SUFFIX ),
        PERSON_TITLE = DECODE( X_PERSON_TITLE, NULL, PERSON_TITLE, FND_API.G_MISS_CHAR, NULL, X_PERSON_TITLE ),
        PERSON_ACADEMIC_TITLE = DECODE( X_PERSON_ACADEMIC_TITLE, NULL, PERSON_ACADEMIC_TITLE, FND_API.G_MISS_CHAR, NULL, X_PERSON_ACADEMIC_TITLE ),
        PERSON_PREVIOUS_LAST_NAME = DECODE( X_PERSON_PREVIOUS_LAST_NAME, NULL, PERSON_PREVIOUS_LAST_NAME, FND_API.G_MISS_CHAR, NULL, X_PERSON_PREVIOUS_LAST_NAME ),
        PERSON_INITIALS = DECODE( X_PERSON_INITIALS, NULL, PERSON_INITIALS, FND_API.G_MISS_CHAR, NULL, X_PERSON_INITIALS ),
        KNOWN_AS = DECODE( X_KNOWN_AS, NULL, KNOWN_AS, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS ),
        PERSON_NAME_PHONETIC = DECODE( X_PERSON_NAME_PHONETIC, NULL, PERSON_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_PERSON_NAME_PHONETIC ),
        PERSON_FIRST_NAME_PHONETIC = DECODE( X_PERSON_FIRST_NAME_PHONETIC, NULL, PERSON_FIRST_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_PERSON_FIRST_NAME_PHONETIC ),
        PERSON_LAST_NAME_PHONETIC = DECODE( X_PERSON_LAST_NAME_PHONETIC, NULL, PERSON_LAST_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_PERSON_LAST_NAME_PHONETIC ),
        TAX_REFERENCE = DECODE( X_TAX_REFERENCE, NULL, TAX_REFERENCE, FND_API.G_MISS_CHAR, NULL, X_TAX_REFERENCE ),
        JGZZ_FISCAL_CODE = DECODE( X_JGZZ_FISCAL_CODE, NULL, JGZZ_FISCAL_CODE, FND_API.G_MISS_CHAR, NULL, X_JGZZ_FISCAL_CODE ),
        PERSON_IDEN_TYPE = DECODE( X_PERSON_IDEN_TYPE, NULL, PERSON_IDEN_TYPE, FND_API.G_MISS_CHAR, NULL, X_PERSON_IDEN_TYPE ),
        PERSON_IDENTIFIER = DECODE( X_PERSON_IDENTIFIER, NULL, PERSON_IDENTIFIER, FND_API.G_MISS_CHAR, NULL, X_PERSON_IDENTIFIER ),
        DATE_OF_BIRTH = DECODE( X_DATE_OF_BIRTH, NULL, DATE_OF_BIRTH, FND_API.G_MISS_DATE, NULL, X_DATE_OF_BIRTH ),
        PLACE_OF_BIRTH = DECODE( X_PLACE_OF_BIRTH, NULL, PLACE_OF_BIRTH, FND_API.G_MISS_CHAR, NULL, X_PLACE_OF_BIRTH ),
        DATE_OF_DEATH = DECODE( X_DATE_OF_DEATH, NULL, DATE_OF_DEATH, FND_API.G_MISS_DATE, NULL, X_DATE_OF_DEATH ),
        DECEASED_FLAG = DECODE( X_DECEASED_FLAG, NULL, DECEASED_FLAG, FND_API.G_MISS_CHAR, NULL, X_DECEASED_FLAG ),
        GENDER = DECODE( X_GENDER, NULL, GENDER, FND_API.G_MISS_CHAR, NULL, X_GENDER ),
        DECLARED_ETHNICITY = DECODE( X_DECLARED_ETHNICITY, NULL, DECLARED_ETHNICITY, FND_API.G_MISS_CHAR, NULL, X_DECLARED_ETHNICITY ),
        MARITAL_STATUS = DECODE( X_MARITAL_STATUS, NULL, MARITAL_STATUS, FND_API.G_MISS_CHAR, NULL, X_MARITAL_STATUS ),
        MARITAL_STATUS_EFFECTIVE_DATE = DECODE( X_MARITAL_STATUS_EFF_DATE, NULL, MARITAL_STATUS_EFFECTIVE_DATE, FND_API.G_MISS_DATE, NULL, X_MARITAL_STATUS_EFF_DATE ),
        PERSONAL_INCOME = DECODE( X_PERSONAL_INCOME, NULL, PERSONAL_INCOME, FND_API.G_MISS_NUM, NULL, X_PERSONAL_INCOME ),
        HEAD_OF_HOUSEHOLD_FLAG = DECODE( X_HEAD_OF_HOUSEHOLD_FLAG, NULL, HEAD_OF_HOUSEHOLD_FLAG, FND_API.G_MISS_CHAR, 'N', X_HEAD_OF_HOUSEHOLD_FLAG ),
        HOUSEHOLD_INCOME = DECODE( X_HOUSEHOLD_INCOME, NULL, HOUSEHOLD_INCOME, FND_API.G_MISS_NUM, NULL, X_HOUSEHOLD_INCOME ),
        HOUSEHOLD_SIZE = DECODE( X_HOUSEHOLD_SIZE, NULL, HOUSEHOLD_SIZE, FND_API.G_MISS_NUM, NULL, X_HOUSEHOLD_SIZE ),
        RENT_OWN_IND = DECODE( X_RENT_OWN_IND, NULL, RENT_OWN_IND, FND_API.G_MISS_CHAR, NULL, X_RENT_OWN_IND ),
        LAST_KNOWN_GPS = DECODE( X_LAST_KNOWN_GPS, NULL, LAST_KNOWN_GPS, FND_API.G_MISS_CHAR, NULL, X_LAST_KNOWN_GPS ),
        EFFECTIVE_START_DATE = DECODE( X_EFFECTIVE_START_DATE, NULL, EFFECTIVE_START_DATE, FND_API.G_MISS_DATE, NULL, X_EFFECTIVE_START_DATE ),
        EFFECTIVE_END_DATE = DECODE( X_EFFECTIVE_END_DATE, NULL, EFFECTIVE_END_DATE, FND_API.G_MISS_DATE, NULL, X_EFFECTIVE_END_DATE ),
        CONTENT_SOURCE_TYPE = DECODE( X_CONTENT_SOURCE_TYPE, NULL, CONTENT_SOURCE_TYPE, FND_API.G_MISS_CHAR, NULL, X_CONTENT_SOURCE_TYPE ),
        KNOWN_AS2 = DECODE( X_KNOWN_AS2, NULL, KNOWN_AS2, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS2 ),
        KNOWN_AS3 = DECODE( X_KNOWN_AS3, NULL, KNOWN_AS3, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS3 ),
        KNOWN_AS4 = DECODE( X_KNOWN_AS4, NULL, KNOWN_AS4, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS4 ),
        KNOWN_AS5 = DECODE( X_KNOWN_AS5, NULL, KNOWN_AS5, FND_API.G_MISS_CHAR, NULL, X_KNOWN_AS5 ),
        MIDDLE_NAME_PHONETIC = DECODE( X_MIDDLE_NAME_PHONETIC, NULL, MIDDLE_NAME_PHONETIC, FND_API.G_MISS_CHAR, NULL, X_MIDDLE_NAME_PHONETIC ),
        OBJECT_VERSION_NUMBER = DECODE( X_OBJECT_VERSION_NUMBER, NULL, OBJECT_VERSION_NUMBER, FND_API.G_MISS_NUM, NULL, X_OBJECT_VERSION_NUMBER ),
        CREATED_BY_MODULE = DECODE( X_CREATED_BY_MODULE, NULL, CREATED_BY_MODULE, FND_API.G_MISS_CHAR, NULL, X_CREATED_BY_MODULE ),
        APPLICATION_ID = DECODE( X_APPLICATION_ID, NULL, APPLICATION_ID, FND_API.G_MISS_NUM, NULL, X_APPLICATION_ID ),
        ACTUAL_CONTENT_SOURCE = DECODE( X_ACTUAL_CONTENT_SOURCE, NULL, ACTUAL_CONTENT_SOURCE, FND_API.G_MISS_CHAR, NULL, X_ACTUAL_CONTENT_SOURCE ),
	VERSION_NUMBER = DECODE( X_VERSION_NUMBER, NULL, VERSION_NUMBER, FND_API.G_MISS_NUM, NULL, X_VERSION_NUMBER )
    WHERE ROWID = X_RowId;

    IF ( SQL%NOTFOUND ) THEN
        RAISE NO_DATA_FOUND;
    END IF;

END Update_Row;

PROCEDURE Lock_Row (
    X_Rowid                                 IN OUT NOCOPY VARCHAR2,
    X_PERSON_PROFILE_ID                     IN     NUMBER,
    X_PARTY_ID                              IN     NUMBER,
    X_LAST_UPDATE_DATE                      IN     DATE,
    X_LAST_UPDATED_BY                       IN     NUMBER,
    X_CREATION_DATE                         IN     DATE,
    X_CREATED_BY                            IN     NUMBER,
    X_LAST_UPDATE_LOGIN                     IN     NUMBER,
    X_REQUEST_ID                            IN     NUMBER,
    X_PROGRAM_APPLICATION_ID                IN     NUMBER,
    X_PROGRAM_ID                            IN     NUMBER,
    X_PROGRAM_UPDATE_DATE                   IN     DATE,
    X_ATTRIBUTE_CATEGORY                    IN     VARCHAR2,
    X_ATTRIBUTE1                            IN     VARCHAR2,
    X_ATTRIBUTE2                            IN     VARCHAR2,
    X_ATTRIBUTE3                            IN     VARCHAR2,
    X_ATTRIBUTE4                            IN     VARCHAR2,
    X_ATTRIBUTE5                            IN     VARCHAR2,
    X_ATTRIBUTE6                            IN     VARCHAR2,
    X_ATTRIBUTE7                            IN     VARCHAR2,
    X_ATTRIBUTE8                            IN     VARCHAR2,
    X_ATTRIBUTE9                            IN     VARCHAR2,
    X_ATTRIBUTE10                           IN     VARCHAR2,
    X_ATTRIBUTE11                           IN     VARCHAR2,
    X_ATTRIBUTE12                           IN     VARCHAR2,
    X_ATTRIBUTE13                           IN     VARCHAR2,
    X_ATTRIBUTE14                           IN     VARCHAR2,
    X_ATTRIBUTE15                           IN     VARCHAR2,
    X_ATTRIBUTE16                           IN     VARCHAR2,
    X_ATTRIBUTE17                           IN     VARCHAR2,
    X_ATTRIBUTE18                           IN     VARCHAR2,
    X_ATTRIBUTE19                           IN     VARCHAR2,
    X_ATTRIBUTE20                           IN     VARCHAR2,
    X_INTERNAL_FLAG                         IN     VARCHAR2,
    X_PERSON_PRE_NAME_ADJUNCT               IN     VARCHAR2,
    X_PERSON_FIRST_NAME                     IN     VARCHAR2,
    X_PERSON_MIDDLE_NAME                    IN     VARCHAR2,
    X_PERSON_LAST_NAME                      IN     VARCHAR2,
    X_PERSON_NAME_SUFFIX                    IN     VARCHAR2,
    X_PERSON_TITLE                          IN     VARCHAR2,
    X_PERSON_ACADEMIC_TITLE                 IN     VARCHAR2,
    X_PERSON_PREVIOUS_LAST_NAME             IN     VARCHAR2,
    X_PERSON_INITIALS                       IN     VARCHAR2,
    X_KNOWN_AS                              IN     VARCHAR2,
    X_PERSON_NAME_PHONETIC                  IN     VARCHAR2,
    X_PERSON_FIRST_NAME_PHONETIC            IN     VARCHAR2,
    X_PERSON_LAST_NAME_PHONETIC             IN     VARCHAR2,
    X_TAX_REFERENCE                         IN     VARCHAR2,
    X_JGZZ_FISCAL_CODE                      IN     VARCHAR2,
    X_PERSON_IDEN_TYPE                      IN     VARCHAR2,
    X_PERSON_IDENTIFIER                     IN     VARCHAR2,
    X_DATE_OF_BIRTH                         IN     DATE,
    X_PLACE_OF_BIRTH                        IN     VARCHAR2,
    X_DATE_OF_DEATH                         IN     DATE,
    X_DECEASED_FLAG                         IN     VARCHAR2,
    X_GENDER                                IN     VARCHAR2,
    X_DECLARED_ETHNICITY                    IN     VARCHAR2,
    X_MARITAL_STATUS                        IN     VARCHAR2,
    X_MARITAL_STATUS_EFF_DATE               IN     DATE,
    X_PERSONAL_INCOME                       IN     NUMBER,
    X_HEAD_OF_HOUSEHOLD_FLAG                IN     VARCHAR2,
    X_HOUSEHOLD_INCOME                      IN     NUMBER,
    X_HOUSEHOLD_SIZE                        IN     NUMBER,
    X_RENT_OWN_IND                          IN     VARCHAR2,
    X_LAST_KNOWN_GPS                        IN     VARCHAR2,
    X_EFFECTIVE_START_DATE                  IN     DATE,
    X_EFFECTIVE_END_DATE                    IN     DATE,
    X_CONTENT_SOURCE_TYPE                   IN     VARCHAR2,
    X_KNOWN_AS2                             IN     VARCHAR2,
    X_KNOWN_AS3                             IN     VARCHAR2,
    X_KNOWN_AS4                             IN     VARCHAR2,
    X_KNOWN_AS5                             IN     VARCHAR2,
    X_MIDDLE_NAME_PHONETIC                  IN     VARCHAR2,
    X_OBJECT_VERSION_NUMBER                 IN     NUMBER,
    X_CREATED_BY_MODULE                     IN     VARCHAR2,
    X_APPLICATION_ID                        IN     NUMBER,
    X_ACTUAL_CONTENT_SOURCE                 IN     VARCHAR2 DEFAULT NULL
) IS

    CURSOR C IS
        SELECT * FROM HZ_PERSON_PROFILES
        WHERE  ROWID = x_Rowid
        FOR UPDATE NOWAIT;
    Recinfo C%ROWTYPE;

BEGIN

    OPEN C;
    FETCH C INTO Recinfo;
    IF ( C%NOTFOUND ) THEN
        CLOSE C;
        FND_MESSAGE.SET_NAME('FND', 'FORM_RECORD_DELETED');
        APP_EXCEPTION.RAISE_EXCEPTION;
    END IF;
    CLOSE C;

    IF (
        ( ( Recinfo.PERSON_PROFILE_ID = X_PERSON_PROFILE_ID )
        OR ( ( Recinfo.PERSON_PROFILE_ID IS NULL )
            AND (  X_PERSON_PROFILE_ID IS NULL ) ) )
    AND ( ( Recinfo.PARTY_ID = X_PARTY_ID )
        OR ( ( Recinfo.PARTY_ID IS NULL )
            AND (  X_PARTY_ID IS NULL ) ) )
    AND ( ( Recinfo.LAST_UPDATE_DATE = X_LAST_UPDATE_DATE )
        OR ( ( Recinfo.LAST_UPDATE_DATE IS NULL )
            AND (  X_LAST_UPDATE_DATE IS NULL ) ) )
    AND ( ( Recinfo.LAST_UPDATED_BY = X_LAST_UPDATED_BY )
        OR ( ( Recinfo.LAST_UPDATED_BY IS NULL )
            AND (  X_LAST_UPDATED_BY IS NULL ) ) )
    AND ( ( Recinfo.CREATION_DATE = X_CREATION_DATE )
        OR ( ( Recinfo.CREATION_DATE IS NULL )
            AND (  X_CREATION_DATE IS NULL ) ) )
    AND ( ( Recinfo.CREATED_BY = X_CREATED_BY )
        OR ( ( Recinfo.CREATED_BY IS NULL )
            AND (  X_CREATED_BY IS NULL ) ) )
    AND ( ( Recinfo.LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN )
        OR ( ( Recinfo.LAST_UPDATE_LOGIN IS NULL )
            AND (  X_LAST_UPDATE_LOGIN IS NULL ) ) )
    AND ( ( Recinfo.REQUEST_ID = X_REQUEST_ID )
        OR ( ( Recinfo.REQUEST_ID IS NULL )
            AND (  X_REQUEST_ID IS NULL ) ) )
    AND ( ( Recinfo.PROGRAM_APPLICATION_ID = X_PROGRAM_APPLICATION_ID )
        OR ( ( Recinfo.PROGRAM_APPLICATION_ID IS NULL )
            AND (  X_PROGRAM_APPLICATION_ID IS NULL ) ) )
    AND ( ( Recinfo.PROGRAM_ID = X_PROGRAM_ID )
        OR ( ( Recinfo.PROGRAM_ID IS NULL )
            AND (  X_PROGRAM_ID IS NULL ) ) )
    AND ( ( Recinfo.PROGRAM_UPDATE_DATE = X_PROGRAM_UPDATE_DATE )
        OR ( ( Recinfo.PROGRAM_UPDATE_DATE IS NULL )
            AND (  X_PROGRAM_UPDATE_DATE IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE_CATEGORY = X_ATTRIBUTE_CATEGORY )
        OR ( ( Recinfo.ATTRIBUTE_CATEGORY IS NULL )
            AND (  X_ATTRIBUTE_CATEGORY IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE1 = X_ATTRIBUTE1 )
        OR ( ( Recinfo.ATTRIBUTE1 IS NULL )
            AND (  X_ATTRIBUTE1 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE2 = X_ATTRIBUTE2 )
        OR ( ( Recinfo.ATTRIBUTE2 IS NULL )
            AND (  X_ATTRIBUTE2 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE3 = X_ATTRIBUTE3 )
        OR ( ( Recinfo.ATTRIBUTE3 IS NULL )
            AND (  X_ATTRIBUTE3 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE4 = X_ATTRIBUTE4 )
        OR ( ( Recinfo.ATTRIBUTE4 IS NULL )
            AND (  X_ATTRIBUTE4 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE5 = X_ATTRIBUTE5 )
        OR ( ( Recinfo.ATTRIBUTE5 IS NULL )
            AND (  X_ATTRIBUTE5 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE6 = X_ATTRIBUTE6 )
        OR ( ( Recinfo.ATTRIBUTE6 IS NULL )
            AND (  X_ATTRIBUTE6 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE7 = X_ATTRIBUTE7 )
        OR ( ( Recinfo.ATTRIBUTE7 IS NULL )
            AND (  X_ATTRIBUTE7 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE8 = X_ATTRIBUTE8 )
        OR ( ( Recinfo.ATTRIBUTE8 IS NULL )
            AND (  X_ATTRIBUTE8 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE9 = X_ATTRIBUTE9 )
        OR ( ( Recinfo.ATTRIBUTE9 IS NULL )
            AND (  X_ATTRIBUTE9 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE10 = X_ATTRIBUTE10 )
        OR ( ( Recinfo.ATTRIBUTE10 IS NULL )
            AND (  X_ATTRIBUTE10 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE11 = X_ATTRIBUTE11 )
        OR ( ( Recinfo.ATTRIBUTE11 IS NULL )
            AND (  X_ATTRIBUTE11 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE12 = X_ATTRIBUTE12 )
        OR ( ( Recinfo.ATTRIBUTE12 IS NULL )
            AND (  X_ATTRIBUTE12 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE13 = X_ATTRIBUTE13 )
        OR ( ( Recinfo.ATTRIBUTE13 IS NULL )
            AND (  X_ATTRIBUTE13 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE14 = X_ATTRIBUTE14 )
        OR ( ( Recinfo.ATTRIBUTE14 IS NULL )
            AND (  X_ATTRIBUTE14 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE15 = X_ATTRIBUTE15 )
        OR ( ( Recinfo.ATTRIBUTE15 IS NULL )
            AND (  X_ATTRIBUTE15 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE16 = X_ATTRIBUTE16 )
        OR ( ( Recinfo.ATTRIBUTE16 IS NULL )
            AND (  X_ATTRIBUTE16 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE17 = X_ATTRIBUTE17 )
        OR ( ( Recinfo.ATTRIBUTE17 IS NULL )
            AND (  X_ATTRIBUTE17 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE18 = X_ATTRIBUTE18 )
        OR ( ( Recinfo.ATTRIBUTE18 IS NULL )
            AND (  X_ATTRIBUTE18 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE19 = X_ATTRIBUTE19 )
        OR ( ( Recinfo.ATTRIBUTE19 IS NULL )
            AND (  X_ATTRIBUTE19 IS NULL ) ) )
    AND ( ( Recinfo.ATTRIBUTE20 = X_ATTRIBUTE20 )
        OR ( ( Recinfo.ATTRIBUTE20 IS NULL )
            AND (  X_ATTRIBUTE20 IS NULL ) ) )
    AND ( ( Recinfo.INTERNAL_FLAG = X_INTERNAL_FLAG )
        OR ( ( Recinfo.INTERNAL_FLAG IS NULL )
            AND (  X_INTERNAL_FLAG IS NULL ) ) )
    AND ( ( Recinfo.PERSON_PRE_NAME_ADJUNCT = X_PERSON_PRE_NAME_ADJUNCT )
        OR ( ( Recinfo.PERSON_PRE_NAME_ADJUNCT IS NULL )
            AND (  X_PERSON_PRE_NAME_ADJUNCT IS NULL ) ) )
    AND ( ( Recinfo.PERSON_FIRST_NAME = X_PERSON_FIRST_NAME )
        OR ( ( Recinfo.PERSON_FIRST_NAME IS NULL )
            AND (  X_PERSON_FIRST_NAME IS NULL ) ) )
    AND ( ( Recinfo.PERSON_MIDDLE_NAME = X_PERSON_MIDDLE_NAME )
        OR ( ( Recinfo.PERSON_MIDDLE_NAME IS NULL )
            AND (  X_PERSON_MIDDLE_NAME IS NULL ) ) )
    AND ( ( Recinfo.PERSON_LAST_NAME = X_PERSON_LAST_NAME )
        OR ( ( Recinfo.PERSON_LAST_NAME IS NULL )
            AND (  X_PERSON_LAST_NAME IS NULL ) ) )
    AND ( ( Recinfo.PERSON_NAME_SUFFIX = X_PERSON_NAME_SUFFIX )
        OR ( ( Recinfo.PERSON_NAME_SUFFIX IS NULL )
            AND (  X_PERSON_NAME_SUFFIX IS NULL ) ) )
    AND ( ( Recinfo.PERSON_TITLE = X_PERSON_TITLE )
        OR ( ( Recinfo.PERSON_TITLE IS NULL )
            AND (  X_PERSON_TITLE IS NULL ) ) )
    AND ( ( Recinfo.PERSON_ACADEMIC_TITLE = X_PERSON_ACADEMIC_TITLE )
        OR ( ( Recinfo.PERSON_ACADEMIC_TITLE IS NULL )
            AND (  X_PERSON_ACADEMIC_TITLE IS NULL ) ) )
    AND ( ( Recinfo.PERSON_PREVIOUS_LAST_NAME = X_PERSON_PREVIOUS_LAST_NAME )
        OR ( ( Recinfo.PERSON_PREVIOUS_LAST_NAME IS NULL )
            AND (  X_PERSON_PREVIOUS_LAST_NAME IS NULL ) ) )
    AND ( ( Recinfo.PERSON_INITIALS = X_PERSON_INITIALS )
        OR ( ( Recinfo.PERSON_INITIALS IS NULL )
            AND (  X_PERSON_INITIALS IS NULL ) ) )
    AND ( ( Recinfo.KNOWN_AS = X_KNOWN_AS )
        OR ( ( Recinfo.KNOWN_AS IS NULL )
            AND (  X_KNOWN_AS IS NULL ) ) )
    AND ( ( Recinfo.PERSON_NAME_PHONETIC = X_PERSON_NAME_PHONETIC )
        OR ( ( Recinfo.PERSON_NAME_PHONETIC IS NULL )
            AND (  X_PERSON_NAME_PHONETIC IS NULL ) ) )
    AND ( ( Recinfo.PERSON_FIRST_NAME_PHONETIC = X_PERSON_FIRST_NAME_PHONETIC )
        OR ( ( Recinfo.PERSON_FIRST_NAME_PHONETIC IS NULL )
            AND (  X_PERSON_FIRST_NAME_PHONETIC IS NULL ) ) )
    AND ( ( Recinfo.PERSON_LAST_NAME_PHONETIC = X_PERSON_LAST_NAME_PHONETIC )
        OR ( ( Recinfo.PERSON_LAST_NAME_PHONETIC IS NULL )
            AND (  X_PERSON_LAST_NAME_PHONETIC IS NULL ) ) )
    AND ( ( Recinfo.TAX_REFERENCE = X_TAX_REFERENCE )
        OR ( ( Recinfo.TAX_REFERENCE IS NULL )
            AND (  X_TAX_REFERENCE IS NULL ) ) )
    AND ( ( Recinfo.JGZZ_FISCAL_CODE = X_JGZZ_FISCAL_CODE )
        OR ( ( Recinfo.JGZZ_FISCAL_CODE IS NULL )
            AND (  X_JGZZ_FISCAL_CODE IS NULL ) ) )
    AND ( ( Recinfo.PERSON_IDEN_TYPE = X_PERSON_IDEN_TYPE )
        OR ( ( Recinfo.PERSON_IDEN_TYPE IS NULL )
            AND (  X_PERSON_IDEN_TYPE IS NULL ) ) )
    AND ( ( Recinfo.PERSON_IDENTIFIER = X_PERSON_IDENTIFIER )
        OR ( ( Recinfo.PERSON_IDENTIFIER IS NULL )
            AND (  X_PERSON_IDENTIFIER IS NULL ) ) )
    AND ( ( Recinfo.DATE_OF_BIRTH = X_DATE_OF_BIRTH )
        OR ( ( Recinfo.DATE_OF_BIRTH IS NULL )
            AND (  X_DATE_OF_BIRTH IS NULL ) ) )
    AND ( ( Recinfo.PLACE_OF_BIRTH = X_PLACE_OF_BIRTH )
        OR ( ( Recinfo.PLACE_OF_BIRTH IS NULL )
            AND (  X_PLACE_OF_BIRTH IS NULL ) ) )
    AND ( ( Recinfo.DATE_OF_DEATH = X_DATE_OF_DEATH )
        OR ( ( Recinfo.DATE_OF_DEATH IS NULL )
            AND (  X_DATE_OF_DEATH IS NULL ) ) )
    AND ( ( Recinfo.DECEASED_FLAG = X_DECEASED_FLAG )
        OR ( ( Recinfo.DECEASED_FLAG IS NULL )
            AND (  X_DECEASED_FLAG IS NULL ) ) )
    AND ( ( Recinfo.GENDER = X_GENDER )
        OR ( ( Recinfo.GENDER IS NULL )
            AND (  X_GENDER IS NULL ) ) )
    AND ( ( Recinfo.DECLARED_ETHNICITY = X_DECLARED_ETHNICITY )
        OR ( ( Recinfo.DECLARED_ETHNICITY IS NULL )
            AND (  X_DECLARED_ETHNICITY IS NULL ) ) )
    AND ( ( Recinfo.MARITAL_STATUS = X_MARITAL_STATUS )
        OR ( ( Recinfo.MARITAL_STATUS IS NULL )
            AND (  X_MARITAL_STATUS IS NULL ) ) )
    AND ( ( Recinfo.MARITAL_STATUS_EFFECTIVE_DATE = X_MARITAL_STATUS_EFF_DATE )
        OR ( ( Recinfo.MARITAL_STATUS_EFFECTIVE_DATE IS NULL )
            AND (  X_MARITAL_STATUS_EFF_DATE IS NULL ) ) )
    AND ( ( Recinfo.PERSONAL_INCOME = X_PERSONAL_INCOME )
        OR ( ( Recinfo.PERSONAL_INCOME IS NULL )
            AND (  X_PERSONAL_INCOME IS NULL ) ) )
    AND ( ( Recinfo.HEAD_OF_HOUSEHOLD_FLAG = X_HEAD_OF_HOUSEHOLD_FLAG )
        OR ( ( Recinfo.HEAD_OF_HOUSEHOLD_FLAG IS NULL )
            AND (  X_HEAD_OF_HOUSEHOLD_FLAG IS NULL ) ) )
    AND ( ( Recinfo.HOUSEHOLD_INCOME = X_HOUSEHOLD_INCOME )
        OR ( ( Recinfo.HOUSEHOLD_INCOME IS NULL )
            AND (  X_HOUSEHOLD_INCOME IS NULL ) ) )
    AND ( ( Recinfo.HOUSEHOLD_SIZE = X_HOUSEHOLD_SIZE )
        OR ( ( Recinfo.HOUSEHOLD_SIZE IS NULL )
            AND (  X_HOUSEHOLD_SIZE IS NULL ) ) )
    AND ( ( Recinfo.RENT_OWN_IND = X_RENT_OWN_IND )
        OR ( ( Recinfo.RENT_OWN_IND IS NULL )
            AND (  X_RENT_OWN_IND IS NULL ) ) )
    AND ( ( Recinfo.LAST_KNOWN_GPS = X_LAST_KNOWN_GPS )
        OR ( ( Recinfo.LAST_KNOWN_GPS IS NULL )
            AND (  X_LAST_KNOWN_GPS IS NULL ) ) )
    AND ( ( Recinfo.EFFECTIVE_START_DATE = X_EFFECTIVE_START_DATE )
        OR ( ( Recinfo.EFFECTIVE_START_DATE IS NULL )
            AND (  X_EFFECTIVE_START_DATE IS NULL ) ) )
    AND ( ( Recinfo.EFFECTIVE_END_DATE = X_EFFECTIVE_END_DATE )
        OR ( ( Recinfo.EFFECTIVE_END_DATE IS NULL )
            AND (  X_EFFECTIVE_END_DATE IS NULL ) ) )
    AND ( ( Recinfo.CONTENT_SOURCE_TYPE = X_CONTENT_SOURCE_TYPE )
        OR ( ( Recinfo.CONTENT_SOURCE_TYPE IS NULL )
            AND (  X_CONTENT_SOURCE_TYPE IS NULL ) ) )
    AND ( ( Recinfo.KNOWN_AS2 = X_KNOWN_AS2 )
        OR ( ( Recinfo.KNOWN_AS2 IS NULL )
            AND (  X_KNOWN_AS2 IS NULL ) ) )
    AND ( ( Recinfo.KNOWN_AS3 = X_KNOWN_AS3 )
        OR ( ( Recinfo.KNOWN_AS3 IS NULL )
            AND (  X_KNOWN_AS3 IS NULL ) ) )
    AND ( ( Recinfo.KNOWN_AS4 = X_KNOWN_AS4 )
        OR ( ( Recinfo.KNOWN_AS4 IS NULL )
            AND (  X_KNOWN_AS4 IS NULL ) ) )
    AND ( ( Recinfo.KNOWN_AS5 = X_KNOWN_AS5 )
        OR ( ( Recinfo.KNOWN_AS5 IS NULL )
            AND (  X_KNOWN_AS5 IS NULL ) ) )
    AND ( ( Recinfo.MIDDLE_NAME_PHONETIC = X_MIDDLE_NAME_PHONETIC )
        OR ( ( Recinfo.MIDDLE_NAME_PHONETIC IS NULL )
            AND (  X_MIDDLE_NAME_PHONETIC IS NULL ) ) )
    AND ( ( Recinfo.OBJECT_VERSION_NUMBER = X_OBJECT_VERSION_NUMBER )
        OR ( ( Recinfo.OBJECT_VERSION_NUMBER IS NULL )
            AND (  X_OBJECT_VERSION_NUMBER IS NULL ) ) )
    AND ( ( Recinfo.CREATED_BY_MODULE = X_CREATED_BY_MODULE )
        OR ( ( Recinfo.CREATED_BY_MODULE IS NULL )
            AND (  X_CREATED_BY_MODULE IS NULL ) ) )
    AND ( ( Recinfo.APPLICATION_ID = X_APPLICATION_ID )
        OR ( ( Recinfo.APPLICATION_ID IS NULL )
            AND (  X_APPLICATION_ID IS NULL ) ) )
    AND ( ( Recinfo.ACTUAL_CONTENT_SOURCE = X_ACTUAL_CONTENT_SOURCE )
        OR ( ( Recinfo.ACTUAL_CONTENT_SOURCE IS NULL )
            AND (  X_ACTUAL_CONTENT_SOURCE IS NULL ) ) )
    ) THEN
        RETURN;
    ELSE
        FND_MESSAGE.SET_NAME('FND', 'FORM_RECORD_DELETED');
        APP_EXCEPTION.RAISE_EXCEPTION;
    END IF;

END Lock_Row;

PROCEDURE Select_Row (
    X_PERSON_PROFILE_ID                     IN OUT NOCOPY NUMBER,
    X_PARTY_ID                              OUT NOCOPY    NUMBER,
    X_ATTRIBUTE_CATEGORY                    OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE1                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE2                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE3                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE4                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE5                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE6                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE7                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE8                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE9                            OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE10                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE11                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE12                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE13                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE14                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE15                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE16                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE17                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE18                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE19                           OUT NOCOPY    VARCHAR2,
    X_ATTRIBUTE20                           OUT NOCOPY    VARCHAR2,
    X_INTERNAL_FLAG                         OUT NOCOPY     VARCHAR2,
    X_PERSON_PRE_NAME_ADJUNCT               OUT NOCOPY    VARCHAR2,
    X_PERSON_FIRST_NAME                     OUT NOCOPY    VARCHAR2,
    X_PERSON_MIDDLE_NAME                    OUT NOCOPY    VARCHAR2,
    X_PERSON_LAST_NAME                      OUT NOCOPY    VARCHAR2,
    X_PERSON_NAME_SUFFIX                    OUT NOCOPY    VARCHAR2,
    X_PERSON_TITLE                          OUT NOCOPY    VARCHAR2,
    X_PERSON_ACADEMIC_TITLE                 OUT NOCOPY    VARCHAR2,
    X_PERSON_PREVIOUS_LAST_NAME             OUT NOCOPY    VARCHAR2,
    X_PERSON_INITIALS                       OUT NOCOPY    VARCHAR2,
    X_KNOWN_AS                              OUT NOCOPY    VARCHAR2,
    X_PERSON_NAME_PHONETIC                  OUT NOCOPY    VARCHAR2,
    X_PERSON_FIRST_NAME_PHONETIC            OUT NOCOPY    VARCHAR2,
    X_PERSON_LAST_NAME_PHONETIC             OUT NOCOPY    VARCHAR2,
    X_TAX_REFERENCE                         OUT NOCOPY    VARCHAR2,
    X_JGZZ_FISCAL_CODE                      OUT NOCOPY    VARCHAR2,
    X_PERSON_IDEN_TYPE                      OUT NOCOPY    VARCHAR2,
    X_PERSON_IDENTIFIER                     OUT NOCOPY    VARCHAR2,
    X_DATE_OF_BIRTH                         OUT NOCOPY    DATE,
    X_PLACE_OF_BIRTH                        OUT NOCOPY    VARCHAR2,
    X_DATE_OF_DEATH                         OUT NOCOPY    DATE,
    X_DECEASED_FLAG                         OUT NOCOPY    VARCHAR2,
    X_GENDER                                OUT NOCOPY    VARCHAR2,
    X_DECLARED_ETHNICITY                    OUT NOCOPY    VARCHAR2,
    X_MARITAL_STATUS                        OUT NOCOPY    VARCHAR2,
    X_MARITAL_STATUS_EFF_DATE               OUT NOCOPY    DATE,
    X_PERSONAL_INCOME                       OUT NOCOPY    NUMBER,
    X_HEAD_OF_HOUSEHOLD_FLAG                OUT NOCOPY    VARCHAR2,
    X_HOUSEHOLD_INCOME                      OUT NOCOPY    NUMBER,
    X_HOUSEHOLD_SIZE                        OUT NOCOPY    NUMBER,
    X_RENT_OWN_IND                          OUT NOCOPY    VARCHAR2,
    X_LAST_KNOWN_GPS                        OUT NOCOPY    VARCHAR2,
    X_EFFECTIVE_START_DATE                  OUT NOCOPY    DATE,
    X_EFFECTIVE_END_DATE                    OUT NOCOPY    DATE,
    X_CONTENT_SOURCE_TYPE                   OUT NOCOPY    VARCHAR2,
    X_KNOWN_AS2                             OUT NOCOPY    VARCHAR2,
    X_KNOWN_AS3                             OUT NOCOPY    VARCHAR2,
    X_KNOWN_AS4                             OUT NOCOPY    VARCHAR2,
    X_KNOWN_AS5                             OUT NOCOPY    VARCHAR2,
    X_MIDDLE_NAME_PHONETIC                  OUT NOCOPY    VARCHAR2,
    X_CREATED_BY_MODULE                     OUT NOCOPY    VARCHAR2,
    X_APPLICATION_ID                        OUT NOCOPY    NUMBER,
    X_ACTUAL_CONTENT_SOURCE                 OUT NOCOPY    VARCHAR2
) IS

BEGIN

    SELECT
        NVL( PERSON_PROFILE_ID, FND_API.G_MISS_NUM ),
        NVL( PARTY_ID, FND_API.G_MISS_NUM ),
        NVL( ATTRIBUTE_CATEGORY, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE1, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE2, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE3, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE4, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE5, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE6, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE7, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE8, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE9, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE10, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE11, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE12, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE13, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE14, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE15, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE16, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE17, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE18, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE19, FND_API.G_MISS_CHAR ),
        NVL( ATTRIBUTE20, FND_API.G_MISS_CHAR ),
        NVL( INTERNAL_FLAG, FND_API.G_MISS_CHAR ),
        NVL( PERSON_PRE_NAME_ADJUNCT, FND_API.G_MISS_CHAR ),
        NVL( PERSON_FIRST_NAME, FND_API.G_MISS_CHAR ),
        NVL( PERSON_MIDDLE_NAME, FND_API.G_MISS_CHAR ),
        NVL( PERSON_LAST_NAME, FND_API.G_MISS_CHAR ),
        NVL( PERSON_NAME_SUFFIX, FND_API.G_MISS_CHAR ),
        NVL( PERSON_TITLE, FND_API.G_MISS_CHAR ),
        NVL( PERSON_ACADEMIC_TITLE, FND_API.G_MISS_CHAR ),
        NVL( PERSON_PREVIOUS_LAST_NAME, FND_API.G_MISS_CHAR ),
        NVL( PERSON_INITIALS, FND_API.G_MISS_CHAR ),
        NVL( KNOWN_AS, FND_API.G_MISS_CHAR ),
        NVL( PERSON_NAME_PHONETIC, FND_API.G_MISS_CHAR ),
        NVL( PERSON_FIRST_NAME_PHONETIC, FND_API.G_MISS_CHAR ),
        NVL( PERSON_LAST_NAME_PHONETIC, FND_API.G_MISS_CHAR ),
        NVL( TAX_REFERENCE, FND_API.G_MISS_CHAR ),
        NVL( JGZZ_FISCAL_CODE, FND_API.G_MISS_CHAR ),
        NVL( PERSON_IDEN_TYPE, FND_API.G_MISS_CHAR ),
        NVL( PERSON_IDENTIFIER, FND_API.G_MISS_CHAR ),
        NVL( DATE_OF_BIRTH, FND_API.G_MISS_DATE ),
        NVL( PLACE_OF_BIRTH, FND_API.G_MISS_CHAR ),
        NVL( DATE_OF_DEATH, FND_API.G_MISS_DATE ),
        NVL( DECEASED_FLAG, FND_API.G_MISS_CHAR ),
        NVL( GENDER, FND_API.G_MISS_CHAR ),
        NVL( DECLARED_ETHNICITY, FND_API.G_MISS_CHAR ),
        NVL( MARITAL_STATUS, FND_API.G_MISS_CHAR ),
        NVL( MARITAL_STATUS_EFFECTIVE_DATE, FND_API.G_MISS_DATE ),
        NVL( PERSONAL_INCOME, FND_API.G_MISS_NUM ),
        NVL( HEAD_OF_HOUSEHOLD_FLAG, FND_API.G_MISS_CHAR ),
        NVL( HOUSEHOLD_INCOME, FND_API.G_MISS_NUM ),
        NVL( HOUSEHOLD_SIZE, FND_API.G_MISS_NUM ),
        NVL( RENT_OWN_IND, FND_API.G_MISS_CHAR ),
        NVL( LAST_KNOWN_GPS, FND_API.G_MISS_CHAR ),
        NVL( EFFECTIVE_START_DATE, FND_API.G_MISS_DATE ),
        NVL( EFFECTIVE_END_DATE, FND_API.G_MISS_DATE ),
        NVL( CONTENT_SOURCE_TYPE, FND_API.G_MISS_CHAR ),
        NVL( KNOWN_AS2, FND_API.G_MISS_CHAR ),
        NVL( KNOWN_AS3, FND_API.G_MISS_CHAR ),
        NVL( KNOWN_AS4, FND_API.G_MISS_CHAR ),
        NVL( KNOWN_AS5, FND_API.G_MISS_CHAR ),
        NVL( MIDDLE_NAME_PHONETIC, FND_API.G_MISS_CHAR ),
        NVL( CREATED_BY_MODULE, FND_API.G_MISS_CHAR ),
        NVL( APPLICATION_ID, FND_API.G_MISS_NUM ),
        NVL( ACTUAL_CONTENT_SOURCE, FND_API.G_MISS_CHAR )
    INTO
        X_PERSON_PROFILE_ID,
        X_PARTY_ID,
        X_ATTRIBUTE_CATEGORY,
        X_ATTRIBUTE1,
        X_ATTRIBUTE2,
        X_ATTRIBUTE3,
        X_ATTRIBUTE4,
        X_ATTRIBUTE5,
        X_ATTRIBUTE6,
        X_ATTRIBUTE7,
        X_ATTRIBUTE8,
        X_ATTRIBUTE9,
        X_ATTRIBUTE10,
        X_ATTRIBUTE11,
        X_ATTRIBUTE12,
        X_ATTRIBUTE13,
        X_ATTRIBUTE14,
        X_ATTRIBUTE15,
        X_ATTRIBUTE16,
        X_ATTRIBUTE17,
        X_ATTRIBUTE18,
        X_ATTRIBUTE19,
        X_ATTRIBUTE20,
        X_INTERNAL_FLAG,
        X_PERSON_PRE_NAME_ADJUNCT,
        X_PERSON_FIRST_NAME,
        X_PERSON_MIDDLE_NAME,
        X_PERSON_LAST_NAME,
        X_PERSON_NAME_SUFFIX,
        X_PERSON_TITLE,
        X_PERSON_ACADEMIC_TITLE,
        X_PERSON_PREVIOUS_LAST_NAME,
        X_PERSON_INITIALS,
        X_KNOWN_AS,
        X_PERSON_NAME_PHONETIC,
        X_PERSON_FIRST_NAME_PHONETIC,
        X_PERSON_LAST_NAME_PHONETIC,
        X_TAX_REFERENCE,
        X_JGZZ_FISCAL_CODE,
        X_PERSON_IDEN_TYPE,
        X_PERSON_IDENTIFIER,
        X_DATE_OF_BIRTH,
        X_PLACE_OF_BIRTH,
        X_DATE_OF_DEATH,
        X_DECEASED_FLAG,
        X_GENDER,
        X_DECLARED_ETHNICITY,
        X_MARITAL_STATUS,
        X_MARITAL_STATUS_EFF_DATE,
        X_PERSONAL_INCOME,
        X_HEAD_OF_HOUSEHOLD_FLAG,
        X_HOUSEHOLD_INCOME,
        X_HOUSEHOLD_SIZE,
        X_RENT_OWN_IND,
        X_LAST_KNOWN_GPS,
        X_EFFECTIVE_START_DATE,
        X_EFFECTIVE_END_DATE,
        X_CONTENT_SOURCE_TYPE,
        X_KNOWN_AS2,
        X_KNOWN_AS3,
        X_KNOWN_AS4,
        X_KNOWN_AS5,
        X_MIDDLE_NAME_PHONETIC,
        X_CREATED_BY_MODULE,
        X_APPLICATION_ID,
        X_ACTUAL_CONTENT_SOURCE
    FROM HZ_PERSON_PROFILES
    WHERE PERSON_PROFILE_ID = X_PERSON_PROFILE_ID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        FND_MESSAGE.SET_NAME( 'AR', 'HZ_API_NO_RECORD' );
        FND_MESSAGE.SET_TOKEN( 'RECORD', 'person_profile_rec');
        FND_MESSAGE.SET_TOKEN( 'VALUE', TO_CHAR( X_PERSON_PROFILE_ID ) );
        FND_MSG_PUB.ADD;
        RAISE FND_API.G_EXC_ERROR;

END Select_Row;

PROCEDURE Delete_Row (
    X_PERSON_PROFILE_ID                     IN     NUMBER
) IS

BEGIN

    DELETE FROM HZ_PERSON_PROFILES
    WHERE PERSON_PROFILE_ID = X_PERSON_PROFILE_ID;

    IF ( SQL%NOTFOUND ) THEN
        RAISE NO_DATA_FOUND;
    END IF;

END Delete_Row;

END HZ_PERSON_PROFILES_PKG;

/
