--------------------------------------------------------
--  DDL for Package Body IEX_SCORE_COMP_TYPES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IEX_SCORE_COMP_TYPES_PKG" AS
/* $Header: iextsctb.pls 120.3 2004/11/05 21:35:06 jypark ship $ */
PG_DEBUG NUMBER(2) ;

PROCEDURE INSERT_ROW (
  X_ROWID                   IN OUT NOCOPY VARCHAR2,
  P_SCORE_COMP_TYPE_ID      IN NUMBER,
  P_OBJECT_VERSION_NUMBER   IN NUMBER,
  P_SCORE_COMP_VALUE        IN VARCHAR2,
  P_ACTIVE_FLAG             IN VARCHAR2,
  P_SCORE_COMP_NAME         IN VARCHAR2,
  P_DESCRIPTION             IN VARCHAR2,
  P_CREATION_DATE           IN DATE,
  P_CREATED_BY              IN NUMBER,
  P_LAST_UPDATE_DATE        IN DATE,
  P_LAST_UPDATED_BY         IN NUMBER,
  P_LAST_UPDATE_LOGIN       IN NUMBER,
  P_JTF_OBJECT_CODE         IN VARCHAR2,
  P_FUNCTION_FLAG           IN VARCHAR2,
  P_METRIC_FLAG             IN VARCHAR2,
  P_DISPLAY_ORDER           IN NUMBER)
IS
  CURSOR C IS
    SELECT ROWID
    FROM IEX_SCORE_COMP_TYPES_B
    WHERE SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID;
    l_function_flag VARCHAR2(1);
BEGIN

if p_function_Flag is null then
    l_function_flag := 'N';
else
    l_function_flag := p_function_flag;
end if;


  INSERT INTO IEX_SCORE_COMP_TYPES_B (
    SCORE_COMP_TYPE_ID,
    OBJECT_VERSION_NUMBER,
    SCORE_COMP_VALUE,
    ACTIVE_FLAG,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    JTF_OBJECT_CODE,
    FUNCTION_FLAG,
    METRIC_FLAG,
    DISPLAY_ORDER)
  VALUES (
    P_SCORE_COMP_TYPE_ID,
    P_OBJECT_VERSION_NUMBER,
    P_SCORE_COMP_VALUE,
    P_ACTIVE_FLAG,
    P_CREATION_DATE,
    P_CREATED_BY,
    P_LAST_UPDATE_DATE,
    P_LAST_UPDATED_BY,
    P_LAST_UPDATE_LOGIN,
    P_JTF_OBJECT_CODE,
    l_function_flag,
    p_metric_flag,
    p_display_order);

  INSERT INTO IEX_SCORE_COMP_TYPES_TL (
    SCORE_COMP_TYPE_ID,
    OBJECT_VERSION_NUMBER,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATION_DATE,
    CREATED_BY,
    SCORE_COMP_NAME,
    DESCRIPTION,
    LANGUAGE,
    SOURCE_LANG)
  SELECT
    P_SCORE_COMP_TYPE_ID,
    P_OBJECT_VERSION_NUMBER,
    P_LAST_UPDATE_DATE,
    P_LAST_UPDATED_BY,
    P_LAST_UPDATE_LOGIN,
    P_CREATION_DATE,
    P_CREATED_BY,
    P_SCORE_COMP_NAME,
    P_DESCRIPTION,
    L.LANGUAGE_CODE,
    userenv('LANG')
  FROM FND_LANGUAGES L
  WHERE L.INSTALLED_FLAG IN ('I', 'B')
  AND NOT EXISTS
    (SELECT NULL
    FROM IEX_SCORE_COMP_TYPES_TL T
    WHERE T.SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID
    AND T.LANGUAGE = L.LANGUAGE_CODE);

  OPEN c;
  FETCH c INTO X_ROWID;
  IF (c%NOTFOUND) THEN
    CLOSE c;
    RAISE NO_DATA_FOUND;
  END IF;
  CLOSE c;

END INSERT_ROW;

PROCEDURE LOCK_ROW (
  P_SCORE_COMP_TYPE_ID      IN NUMBER,
  P_OBJECT_VERSION_NUMBER   IN NUMBER,
  P_SCORE_COMP_VALUE        IN VARCHAR2,
  P_ACTIVE_FLAG             IN VARCHAR2,
  P_SCORE_COMP_NAME         IN VARCHAR2) IS

  CURSOR c IS SELECT
      OBJECT_VERSION_NUMBER,
      SCORE_COMP_VALUE,
      ACTIVE_FLAG
    FROM IEX_SCORE_COMP_TYPES_B
    WHERE SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID
    FOR UPDATE of SCORE_COMP_TYPE_ID NOWAIT;
  recinfo c%rowtype;

  CURSOR c1 IS SELECT
      SCORE_COMP_NAME,
      decode(LANGUAGE, userenv('LANG'), 'Y', 'N') BASELANG
    FROM IEX_SCORE_COMP_TYPES_TL
    WHERE SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID
    AND userenv('LANG') IN (LANGUAGE, SOURCE_LANG)
    FOR UPDATE of SCORE_COMP_TYPE_ID nowait;

BEGIN
  OPEN c;
  FETCH c INTO recinfo;
  IF (c%notfound) THEN
    CLOSE c;
    fnd_message.set_name('FND', 'FORM_RECORD_DELETED');
    app_exception.raise_exception;
  END IF;
  CLOSE c;
  IF (    (recinfo.OBJECT_VERSION_NUMBER = P_OBJECT_VERSION_NUMBER)
      AND ((recinfo.SCORE_COMP_VALUE = P_SCORE_COMP_VALUE)
           OR ((recinfo.SCORE_COMP_VALUE IS NULL) AND (P_SCORE_COMP_VALUE IS NULL)))
      AND ((recinfo.ACTIVE_FLAG = P_ACTIVE_FLAG)
           OR ((recinfo.ACTIVE_FLAG IS NULL) AND (P_ACTIVE_FLAG IS NULL)))
  ) THEN
    NULL;
  ELSE
    fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
    app_exception.raise_exception;
  END IF;

  FOR tlinfo IN c1 LOOP
    IF (tlinfo.BASELANG = 'Y') THEN
      IF (    ((tlinfo.SCORE_COMP_NAME = P_SCORE_COMP_NAME)
               OR ((tlinfo.SCORE_COMP_NAME IS NULL) AND (P_SCORE_COMP_NAME IS NULL)))
      ) THEN
        NULL;
      ELSE
        fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
        app_exception.raise_exception;
      END IF;
    END IF;
  END LOOP;
  RETURN;
END LOCK_ROW;

PROCEDURE UPDATE_ROW (
  P_SCORE_COMP_TYPE_ID      IN NUMBER,
  P_OBJECT_VERSION_NUMBER   IN NUMBER,
  P_SCORE_COMP_VALUE        IN VARCHAR2,
  P_ACTIVE_FLAG             IN VARCHAR2,
  P_SCORE_COMP_NAME         IN VARCHAR2,
  P_LAST_UPDATE_DATE        IN DATE,
  P_LAST_UPDATED_BY         IN NUMBER,
  P_LAST_UPDATE_LOGIN       IN NUMBER,
  P_DESCRIPTION             IN VARCHAR2,
  P_JTF_OBJECT_CODE         IN VARCHAR2,
  P_FUNCTION_FLAG           IN VARCHAR2,
  P_METRIC_FLAG             IN VARCHAR2,
  P_DISPLAY_ORDER           IN NUMBER) IS
  l_function_flag VARCHAR2(1);
BEGIN

if p_function_Flag is null then
    l_function_flag := 'N';
else
    l_function_flag := p_function_flag;
end if;

  UPDATE IEX_SCORE_COMP_TYPES_B SET
    OBJECT_VERSION_NUMBER = P_OBJECT_VERSION_NUMBER,
    SCORE_COMP_VALUE      = P_SCORE_COMP_VALUE,
    ACTIVE_FLAG           = P_ACTIVE_FLAG,
    LAST_UPDATE_DATE      = P_LAST_UPDATE_DATE,
    LAST_UPDATED_BY       = P_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN     = P_LAST_UPDATE_LOGIN,
    JTF_OBJECT_CODE       = P_JTF_OBJECT_CODE,
    FUNCTION_FLAG         = l_FUNCTION_FLAG,
    METRIC_FLAG           = P_METRIC_FLAG,
    DISPLAY_ORDER         = P_DISPLAY_ORDER
  WHERE SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID;

  IF (sql%notfound) THEN
    RAISE no_data_found;
  END IF;

  UPDATE IEX_SCORE_COMP_TYPES_TL SET
    SCORE_COMP_NAME = P_SCORE_COMP_NAME,
    DESCRIPTION = P_DESCRIPTION,
    LAST_UPDATE_DATE = P_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = P_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = P_LAST_UPDATE_LOGIN,
    SOURCE_LANG = userenv('LANG')
  WHERE SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID
  AND userenv('LANG') IN (LANGUAGE, SOURCE_LANG);

  IF (sql%notfound) THEN
    RAISE no_data_found;
  END IF;
END UPDATE_ROW;

PROCEDURE DELETE_ROW (
  P_SCORE_COMP_TYPE_ID IN NUMBER
) IS
BEGIN
  DELETE FROM IEX_SCORE_COMP_TYPES_TL
  WHERE SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID;

  IF (sql%notfound) THEN
    RAISE no_data_found;
  END IF;

  DELETE FROM IEX_SCORE_COMP_TYPES_B
  WHERE SCORE_COMP_TYPE_ID = P_SCORE_COMP_TYPE_ID;

  IF (sql%notfound) THEN
    RAISE no_data_found;
  END IF;
END DELETE_ROW;

PROCEDURE ADD_LANGUAGE
IS
BEGIN
  DELETE FROM IEX_SCORE_COMP_TYPES_TL T
  WHERE NOT EXISTS
    (SELECT NULL
    FROM IEX_SCORE_COMP_TYPES_B B
    WHERE B.SCORE_COMP_TYPE_ID = T.SCORE_COMP_TYPE_ID
    );

  UPDATE IEX_SCORE_COMP_TYPES_TL T SET
    (SCORE_COMP_NAME ) =
       (SELECT
        B.SCORE_COMP_NAME
        FROM IEX_SCORE_COMP_TYPES_TL B
        WHERE B.SCORE_COMP_TYPE_ID = T.SCORE_COMP_TYPE_ID
        AND B.LANGUAGE = T.SOURCE_LANG)
    WHERE (T.SCORE_COMP_TYPE_ID,
         T.LANGUAGE) IN
    (SELECT
      SUBT.SCORE_COMP_TYPE_ID,
      SUBT.LANGUAGE
    FROM IEX_SCORE_COMP_TYPES_TL SUBB, IEX_SCORE_COMP_TYPES_TL SUBT
    WHERE SUBB.SCORE_COMP_TYPE_ID = SUBT.SCORE_COMP_TYPE_ID
    AND SUBB.LANGUAGE = SUBT.SOURCE_LANG
    AND (SUBB.SCORE_COMP_NAME <> SUBT.SCORE_COMP_NAME)
      OR (SUBB.SCORE_COMP_NAME IS NULL AND SUBT.SCORE_COMP_NAME IS NOT NULL)
      OR (SUBB.SCORE_COMP_NAME IS NOT NULL AND SUBT.SCORE_COMP_NAME IS NULL)
  );

  INSERT INTO IEX_SCORE_COMP_TYPES_TL (
    SCORE_COMP_TYPE_ID,
    OBJECT_VERSION_NUMBER,
    PROGRAM_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATION_DATE,
    CREATED_BY,
    SCORE_COMP_NAME,
    DESCRIPTION,
    LANGUAGE,
    SOURCE_LANG
  ) SELECT
    B.SCORE_COMP_TYPE_ID,
    B.OBJECT_VERSION_NUMBER,
    B.PROGRAM_ID,
    B.LAST_UPDATE_DATE,
    B.LAST_UPDATED_BY,
    B.LAST_UPDATE_LOGIN,
    B.CREATION_DATE,
    B.CREATED_BY,
    B.SCORE_COMP_NAME,
    B.DESCRIPTION,
    L.LANGUAGE_CODE,
    B.SOURCE_LANG
  FROM IEX_SCORE_COMP_TYPES_TL B, FND_LANGUAGES L
  WHERE L.INSTALLED_FLAG IN ('I', 'B')
  AND B.LANGUAGE = userenv('LANG')
  AND NOT EXISTS
    (SELECT NULL
    FROM IEX_SCORE_COMP_TYPES_TL T
    WHERE T.SCORE_COMP_TYPE_ID = B.SCORE_COMP_TYPE_ID
    AND T.LANGUAGE = L.LANGUAGE_CODE);
END ADD_LANGUAGE;

BEGIN
  PG_DEBUG := TO_NUMBER(NVL(FND_PROFILE.value('IEX_DEBUG_LEVEL'), '20'));

END IEX_SCORE_COMP_TYPES_PKG;

/
