--------------------------------------------------------
--  DDL for Package Body IGI_IGIGBUCC_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IGI_IGIGBUCC_XMLP_PKG" AS
/* $Header: IGIGBUCCB.pls 120.0.12010000.1 2008/07/29 08:58:10 appldev ship $ */
  FUNCTION BEFOREREPORT RETURN BOOLEAN IS
  BEGIN
    IF P_RUN_AOL = 'Y' THEN
      P_CONC_REQUEST_ID := FND_GLOBAL.CONC_REQUEST_ID;
      /*SRW.USER_EXIT('FND SRWINIT')*/NULL;
      IF (P_DEBUG_SWITCH = 'Y') THEN
        /*SRW.MESSAGE('1'
                   ,'After SRWINIT')*/NULL;
      END IF;
      /*SRW.REFERENCE(P_COA_ID)*/NULL;
      IF (P_DEBUG_SWITCH = 'Y') THEN
        /*SRW.MESSAGE('2'
                   ,'After USER_EXIT FND FLEXSQL ALL')*/NULL;
      END IF;
      IF (P_DEBUG_SWITCH = 'Y') THEN
        /*SRW.MESSAGE('3'
                   ,'After USER_EXIT FND FLEXSQL MIN_MAX_FLEX')*/NULL;
      END IF;
    END IF;
    RETURN (TRUE);
  EXCEPTION
    WHEN OTHERS THEN
      /*RAISE SRW.PROGRAM_ABORT*/RAISE_APPLICATION_ERROR(-20101,null);
      RETURN (FALSE);
  END BEFOREREPORT;

  FUNCTION AFTERREPORT RETURN BOOLEAN IS
  BEGIN
    IF (P_RUN_AOL = 'Y') THEN
      /*SRW.USER_EXIT('FND SRWEXIT')*/NULL;
      IF (P_DEBUG_SWITCH = 'Y') THEN
        /*SRW.MESSAGE('4'
                   ,'After SRWEXIT')*/NULL;
      END IF;
    END IF;
    RETURN (TRUE);
  END AFTERREPORT;

  FUNCTION CF_UPDATEFORMULA(CCID IN NUMBER) RETURN NUMBER IS
PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    UPDATE
      GL_CODE_COMBINATIONS gcc
    SET
      IGI_BALANCED_BUDGET_FLAG = 'Y'
    WHERE GCC.CODE_COMBINATION_ID = CCID;
COMMIT;
    RETURN 0;
  END CF_UPDATEFORMULA;

  FUNCTION CF_NO_DATA_FOUNDFORMULA(NO_DATA IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    CP_NO_DATA_FOUND := NO_DATA;
    RETURN 0;
  END CF_NO_DATA_FOUNDFORMULA;

  FUNCTION CP_SELECT_ALL_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_SELECT_ALL;
  END CP_SELECT_ALL_P;

  FUNCTION CP_WHERE_FLEX_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_WHERE_FLEX;
  END CP_WHERE_FLEX_P;

  FUNCTION CP_NO_DATA_FOUND_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_NO_DATA_FOUND;
  END CP_NO_DATA_FOUND_P;

END IGI_IGIGBUCC_XMLP_PKG;


/
