--------------------------------------------------------
--  DDL for Package Body IGI_IGIRTAUD_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IGI_IGIRTAUD_XMLP_PKG" AS
/* $Header: IGIRTAUDB.pls 120.0.12010000.1 2008/07/29 08:59:31 appldev ship $ */
  FUNCTION BEFOREREPORT RETURN BOOLEAN IS
    LV_MESSAGE VARCHAR2(200) := NULL;
    C_DATE_FORMAT varchar2(25);
  BEGIN
    P_CONC_REQUEST_ID := FND_GLOBAL.CONC_REQUEST_ID;
    C_DATE_FORMAT := 'DD-MON-YYYY';
    CP_DATE_LOW := to_date(P_DATE_LOW,C_DATE_FORMAT);
    CP_DATE_HIGH := to_date(P_DATE_HIGH,C_DATE_FORMAT);
    /*SRW.USER_EXIT('FND SRWINIT')*/NULL;
    IF IGI_GEN.IS_REQ_INSTALLED('INS') THEN
      RETURN (TRUE);
    ELSE
      FND_MESSAGE.SET_NAME('IGI'
                          ,'IGI_INS_IS_DISABLED');
      LV_MESSAGE := FND_MESSAGE.GET;
      /*SRW.MESSAGE(20000
                 ,LV_MESSAGE)*/NULL;
      RETURN (FALSE);
    END IF;
    RETURN (TRUE);
  EXCEPTION
    WHEN OTHERS THEN
      /*SRW.MESSAGE(100
                 ,SQLERRM)*/NULL;
      RETURN (FALSE);
  END BEFOREREPORT;

  FUNCTION AFTERREPORT RETURN BOOLEAN IS
  BEGIN
    /*SRW.USER_EXIT('FND SRWEXIT')*/NULL;
    RETURN (TRUE);
  EXCEPTION
    WHEN OTHERS THEN
      /*SRW.MESSAGE(100
                 ,SQLERRM)*/NULL;
      RETURN (FALSE);
  END AFTERREPORT;

END IGI_IGIRTAUD_XMLP_PKG;

/
