--------------------------------------------------------
--  DDL for Package Body IGI_IGISLSSA_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IGI_IGISLSSA_XMLP_PKG" AS
/* $Header: IGISLSSAB.pls 120.0.12010000.1 2008/07/29 08:59:40 appldev ship $ */
  FUNCTION AFTERREPORT RETURN BOOLEAN IS
  BEGIN
    RETURN (TRUE);
  END AFTERREPORT;

  FUNCTION CF_1FORMULA(GRP_FOR_TAB_NAME IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    CP_GRP_NAME := GRP_FOR_TAB_NAME;
    RETURN (1);
  END CF_1FORMULA;

  FUNCTION CF_2FORMULA(GRP_FOR_PRC_NAME IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    CP_PRC_NAME := GRP_FOR_PRC_NAME;
    RETURN (1);
  END CF_2FORMULA;

  FUNCTION CF_3FORMULA(PRC_FOR_TAB_NAME IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    CP_TAB_NAME := PRC_FOR_TAB_NAME;
    RETURN (1);
  END CF_3FORMULA;

  FUNCTION BEFOREREPORT RETURN BOOLEAN IS
  BEGIN
    P_CONC_REQUEST_ID := FND_GLOBAL.CONC_REQUEST_ID;

      P_PROCESS_NAME_T := nvl(P_PROCESS_NAME,'%');
      P_GROUP_NAME_T := nvl(P_GROUP_NAME,'%');
      P_TABLE_NAME_T := nvl(P_TABLE_NAME,'%');



    RETURN (TRUE);
  END BEFOREREPORT;

  FUNCTION CP_GRP_NAME_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_GRP_NAME;
  END CP_GRP_NAME_P;

  FUNCTION CP_PRC_NAME_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_PRC_NAME;
  END CP_PRC_NAME_P;

  FUNCTION CP_TAB_NAME_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_TAB_NAME;
  END CP_TAB_NAME_P;

FUNCTION F_GTAB_DT_ENABLED_AU1FORMATTRI(GRP_TABLE_ENABLED IN DATE,GRP_TABLE_DISABLED IN DATE,GRP_TABLE_REMOVED IN DATE
,GTAB_DT_ENABLED_AU IN DATE,GTAB_DT_DISABLED_AU IN DATE,GTAB_DT_REMOVED_AU IN DATE) RETURN VARCHAR IS
P_DATE 		DATE := SYSDATE;
BEGIN
  IF  NVL(GRP_TABLE_ENABLED,P_DATE)  = NVL(GTAB_DT_ENABLED_AU, P_DATE)
  AND NVL(GRP_TABLE_DISABLED,P_DATE) = NVL(GTAB_DT_DISABLED_AU, P_DATE)
  AND NVL(GRP_TABLE_REMOVED,P_DATE)  = NVL(GTAB_DT_REMOVED_AU,P_DATE)
  THEN
      RETURN ('N');
  ELSE
      RETURN ('Y');
  END IF;
END;

FUNCTION F_GPRC_DT_ENABLED_AU1FORMATTRI(GRP_PRC_ENABLED IN DATE,GRP_PRC_DISABLED IN DATE,GRP_PRC_REMOVED IN DATE,GPRC_DT_ENABLED_AU IN DATE,GPRC_DT_DISABLED_AU IN DATE,GPRC_DT_REMOVED_AU IN DATE) RETURN VARCHAR IS
P_DATE  DATE := SYSDATE;
BEGIN
  IF  NVL(GRP_PRC_ENABLED,P_DATE)  = NVL(GPRC_DT_ENABLED_AU,P_DATE)
  AND NVL(GRP_PRC_DISABLED,P_DATE) = NVL(GPRC_DT_DISABLED_AU,P_DATE)
  AND NVL(GRP_PRC_REMOVED,P_DATE) =  NVL(GPRC_DT_REMOVED_AU,P_DATE)
  THEN
      RETURN ('N');
  ELSE
      RETURN ('Y');
  END IF;
END;

FUNCTION F_PTAB_DT_ENABLED_AU1FORMATTRI(PRC_TABLE_ENABLED IN DATE,PRC_TABLE_DISABLED IN DATE,PRC_TABLE_REMOVED IN DATE,PTAB_DT_ENABLED_AU IN DATE,PTAB_DT_DISABLED_AU IN DATE,PTAB_DT_REMOVED_AU IN DATE) RETURN VARCHAR IS
P_DATE DATE := SYSDATE;
BEGIN
  IF  NVL(PRC_TABLE_ENABLED,P_DATE) = NVL(PTAB_DT_ENABLED_AU,P_DATE)
  AND NVL(PRC_TABLE_DISABLED,P_DATE)= NVL(PTAB_DT_DISABLED_AU,P_DATE)
  AND NVL(PRC_TABLE_REMOVED,P_DATE) = NVL(PTAB_DT_REMOVED_AU,P_DATE)
  THEN
      RETURN ('N');
  ELSE
      RETURN ('Y');
  END IF;
END;


END IGI_IGISLSSA_XMLP_PKG;

/
