--------------------------------------------------------
--  DDL for Package Body IGI_IGIPSAPR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IGI_IGIPSAPR_XMLP_PKG" AS
/* $Header: IGIPSAPRB.pls 120.0.12010000.1 2008/11/20 13:57:39 sasukuma noship $ */
  FUNCTION AFTERREPORT RETURN BOOLEAN IS
  BEGIN
    /*SRW.USER_EXIT('FND SRWEXIT')*/NULL;
    RETURN (TRUE);
  END AFTERREPORT;

  FUNCTION BEFOREREPORT RETURN BOOLEAN IS
    LV_MESSAGE VARCHAR2(4000) := NULL;
    CURSOR CUR_GET_DESCRIPTION IS
      SELECT
        DESCRIPTION
      FROM
        IGI_LOOKUPS
      WHERE UPPER(LOOKUP_CODE) = 'SIA'
        AND LOOKUP_TYPE = 'GCC_DESCRIPTION';
    L_DESCRIPTION IGI_LOOKUPS.DESCRIPTION%TYPE;
  BEGIN
    P_CONC_REQUEST_ID := FND_GLOBAL.CONC_REQUEST_ID;
    /*SRW.USER_EXIT('FND SRWINIT')*/NULL;
    OPEN CUR_GET_DESCRIPTION;
    FETCH CUR_GET_DESCRIPTION
     INTO L_DESCRIPTION;
    CLOSE CUR_GET_DESCRIPTION;
    IF IGI_GEN.IS_REQ_INSTALLED('SIA') THEN
      RETURN (TRUE);
    ELSE
      FND_MESSAGE.SET_NAME('IGI'
                          ,'IGI_GEN_PROD_NOT_INSTALLED');
      FND_MESSAGE.SET_TOKEN('OPTION_NAME'
                           ,L_DESCRIPTION);
      LV_MESSAGE := FND_MESSAGE.GET;
      /*SRW.MESSAGE(20000
                 ,LV_MESSAGE)*/NULL;
      RETURN (FALSE);
    END IF;
    RETURN (TRUE);
  EXCEPTION
    WHEN OTHERS THEN
      /*SRW.MESSAGE(100
                 ,SQLERRM)*/NULL;
      RETURN (FALSE);
  END BEFOREREPORT;

  FUNCTION AFTERPFORM RETURN BOOLEAN IS
  BEGIN
    IF P_RELEASE_LOOKUP_CODE IS NOT NULL THEN
      SELECT
        LOOKUP_CODE
      INTO P_RELEASE_LOOKUP_CODE_1
      FROM
        IGI_LOOKUPS
      WHERE LOOKUP_TYPE = 'REPORTS'
        AND MEANING = P_RELEASE_LOOKUP_CODE;
    END IF;
    RETURN (TRUE);
  END AFTERPFORM;

END IGI_IGIPSAPR_XMLP_PKG;


/
