--------------------------------------------------------
--  DDL for Package Body IRC_JOB_BASKET_ITEMS_BK1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IRC_JOB_BASKET_ITEMS_BK1" as
/* $Header: irjbiapi.pkb 120.0 2005/07/26 15:12:54 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 21:58:20 (YYYY/MM/DD HH24:MI:SS)
procedure CREATE_JOB_BASKET_ITEM_A
(P_EFFECTIVE_DATE in DATE
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_JOB_BASKET_ITEM_ID in NUMBER
,P_RECRUITMENT_ACTIVITY_ID in NUMBER
,P_PERSON_ID in NUMBER
)is
l_commit_unit_number number;
l_legislation_code   varchar2(30);
begin
hr_utility.set_location('Entering: IRC_JOB_BASKET_ITEMS_BK1.CREATE_JOB_BASKET_ITEM_A', 10);
l_commit_unit_number := hr_api.return_commit_unit;
if hr_api.call_app_hooks then
irc_job_basket_items_be1.CREATE_JOB_BASKET_ITEM_A
(P_EFFECTIVE_DATE => P_EFFECTIVE_DATE
,P_OBJECT_VERSION_NUMBER => P_OBJECT_VERSION_NUMBER
,P_JOB_BASKET_ITEM_ID => P_JOB_BASKET_ITEM_ID
,P_RECRUITMENT_ACTIVITY_ID => P_RECRUITMENT_ACTIVITY_ID
,P_PERSON_ID => P_PERSON_ID
);
end if;
hr_multi_message.end_validation_set;
hr_api.validate_commit_unit(l_commit_unit_number, 'CREATE_JOB_BASKET_ITEM', 'AP');
hr_utility.set_location(' Leaving: IRC_JOB_BASKET_ITEMS_BK1.CREATE_JOB_BASKET_ITEM_A', 20);
end CREATE_JOB_BASKET_ITEM_A;
procedure CREATE_JOB_BASKET_ITEM_B
(P_EFFECTIVE_DATE in DATE
,P_RECRUITMENT_ACTIVITY_ID in NUMBER
,P_PERSON_ID in NUMBER
)is
begin
hr_utility.set_location('Entering: IRC_JOB_BASKET_ITEMS_BK1.CREATE_JOB_BASKET_ITEM_B', 10);
hr_utility.set_location(' Leaving: IRC_JOB_BASKET_ITEMS_BK1.CREATE_JOB_BASKET_ITEM_B', 20);
end CREATE_JOB_BASKET_ITEM_B;
end IRC_JOB_BASKET_ITEMS_BK1;

/
