--------------------------------------------------------
--  DDL for Package Body IRC_LOCATION_CRITERIA_VAL_BK1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IRC_LOCATION_CRITERIA_VAL_BK1" as
/* $Header: irlcvapi.pkb 120.0 2005/10/03 14:58:42 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 21:58:20 (YYYY/MM/DD HH24:MI:SS)
procedure CREATE_LOCATION_CRITERIA_A
(P_LOCATION_CRITERIA_VALUE_ID in NUMBER
,P_SEARCH_CRITERIA_ID in NUMBER
,P_DERIVED_LOCALE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
l_commit_unit_number number;
l_legislation_code   varchar2(30);
begin
hr_utility.set_location('Entering: IRC_LOCATION_CRITERIA_VAL_BK1.CREATE_LOCATION_CRITERIA_A', 10);
l_commit_unit_number := hr_api.return_commit_unit;
if hr_api.call_app_hooks then
irc_location_criteria_val_be1.CREATE_LOCATION_CRITERIA_A
(P_LOCATION_CRITERIA_VALUE_ID => P_LOCATION_CRITERIA_VALUE_ID
,P_SEARCH_CRITERIA_ID => P_SEARCH_CRITERIA_ID
,P_DERIVED_LOCALE => P_DERIVED_LOCALE
,P_OBJECT_VERSION_NUMBER => P_OBJECT_VERSION_NUMBER
);
end if;
hr_multi_message.end_validation_set;
hr_api.validate_commit_unit(l_commit_unit_number, 'CREATE_LOCATION_CRITERIA', 'AP');
hr_utility.set_location(' Leaving: IRC_LOCATION_CRITERIA_VAL_BK1.CREATE_LOCATION_CRITERIA_A', 20);
end CREATE_LOCATION_CRITERIA_A;
procedure CREATE_LOCATION_CRITERIA_B
(P_SEARCH_CRITERIA_ID in NUMBER
,P_DERIVED_LOCALE in VARCHAR2
)is
begin
hr_utility.set_location('Entering: IRC_LOCATION_CRITERIA_VAL_BK1.CREATE_LOCATION_CRITERIA_B', 10);
hr_utility.set_location(' Leaving: IRC_LOCATION_CRITERIA_VAL_BK1.CREATE_LOCATION_CRITERIA_B', 20);
end CREATE_LOCATION_CRITERIA_B;
end IRC_LOCATION_CRITERIA_VAL_BK1;

/
