--------------------------------------------------------
--  DDL for Package Body IRC_APL_PROFILE_ACCESS_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IRC_APL_PROFILE_ACCESS_BK3" as
/* $Header: irapaapi.pkb 120.0.12000000.1 2007/03/23 12:08:48 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 21:58:18 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_APL_PROFILE_ACCESS_A
(P_PERSON_ID in NUMBER
,P_APL_PROFILE_ACCESS_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
l_commit_unit_number number;
l_legislation_code   varchar2(30);
begin
hr_utility.set_location('Entering: IRC_APL_PROFILE_ACCESS_BK3.DELETE_APL_PROFILE_ACCESS_A', 10);
l_commit_unit_number := hr_api.return_commit_unit;
if hr_api.call_app_hooks then
irc_apl_profile_access_be3.DELETE_APL_PROFILE_ACCESS_A
(P_PERSON_ID => P_PERSON_ID
,P_APL_PROFILE_ACCESS_ID => P_APL_PROFILE_ACCESS_ID
,P_OBJECT_VERSION_NUMBER => P_OBJECT_VERSION_NUMBER
);
end if;
hr_multi_message.end_validation_set;
hr_api.validate_commit_unit(l_commit_unit_number, 'DELETE_APL_PROFILE_ACCESS', 'AP');
hr_utility.set_location(' Leaving: IRC_APL_PROFILE_ACCESS_BK3.DELETE_APL_PROFILE_ACCESS_A', 20);
end DELETE_APL_PROFILE_ACCESS_A;
procedure DELETE_APL_PROFILE_ACCESS_B
(P_PERSON_ID in NUMBER
,P_APL_PROFILE_ACCESS_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: IRC_APL_PROFILE_ACCESS_BK3.DELETE_APL_PROFILE_ACCESS_B', 10);
hr_utility.set_location(' Leaving: IRC_APL_PROFILE_ACCESS_BK3.DELETE_APL_PROFILE_ACCESS_B', 20);
end DELETE_APL_PROFILE_ACCESS_B;
end IRC_APL_PROFILE_ACCESS_BK3;

/
