--------------------------------------------------------
--  DDL for Package Body IRC_IDO_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."IRC_IDO_RKI" as
/* $Header: iridorhi.pkb 120.5.12010000.2 2008/09/26 13:55:20 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 21:58:18 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EFFECTIVE_DATE in DATE
,P_DOCUMENT_ID in NUMBER
,P_PARTY_ID in NUMBER
,P_PERSON_ID in NUMBER
,P_ASSIGNMENT_ID in NUMBER
,P_FILE_NAME in VARCHAR2
,P_FILE_FORMAT in VARCHAR2
,P_MIME_TYPE in VARCHAR2
,P_DESCRIPTION in VARCHAR2
,P_TYPE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_END_DATE in DATE
)is
begin
hr_utility.set_location('Entering: IRC_IDO_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: IRC_IDO_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end IRC_IDO_RKI;

/
