--------------------------------------------------------
--  DDL for Package Body JL_JLCOGLNM_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."JL_JLCOGLNM_XMLP_PKG" AS
/* $Header: JLCOGLNMB.pls 120.1 2007/12/25 16:50:19 dwkrishn noship $ */
  FUNCTION BEFOREREPORT RETURN BOOLEAN IS
  BEGIN
    P_CONC_REQUEST_ID := FND_GLOBAL.CONC_REQUEST_ID;
    /*SRW.USER_EXIT('FND SRWINIT')*/NULL;
    IF P_REPORTED_YEAR IS NULL THEN
      /*RAISE SRW.PROGRAM_ABORT*/RAISE_APPLICATION_ERROR(-20101,null);
    END IF;
    P_LITERAL_START1 :=P_LITERAL_START;
    P_LITERAL_END1 :=P_LITERAL_END;
    IF P_LITERAL_START1 IS NULL THEN
      BEGIN
        SELECT
          NVL(MIN(LITERAL_CODE)
             ,0)
        INTO CP_LITERAL_START
        FROM
          JL_CO_GL_MG_LITERALS
        WHERE REPORTED_YEAR = P_REPORTED_YEAR
          AND SET_OF_BOOKS_ID = P_SOB_ID;
        P_LITERAL_START1 := CP_LITERAL_START;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          CP_LITERAL_START := 0;
        WHEN OTHERS THEN
          NULL;
      END;
    END IF;
    IF P_LITERAL_END1 IS NULL THEN
      BEGIN
        SELECT
          NVL(MAX(LITERAL_CODE)
             ,9999)
        INTO CP_LITERAL_END
        FROM
          JL_CO_GL_MG_LITERALS
        WHERE REPORTED_YEAR = P_REPORTED_YEAR
          AND SET_OF_BOOKS_ID = P_SOB_ID;
        P_LITERAL_END1 := CP_LITERAL_END;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          CP_LITERAL_END := 9999;
        WHEN OTHERS THEN
          NULL;
      END;
    END IF;
    BEGIN
      SELECT
        CURRENCY_CODE
      INTO P_CURRENCY_CODE
      FROM
        GL_SETS_OF_BOOKS
      WHERE SET_OF_BOOKS_ID = P_SOB_ID;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        NULL;
      WHEN OTHERS THEN
        NULL;
    END;
    BEGIN
      SELECT
        NAME COMP_NAME,
        REGISTRATION_NUMBER COMP_ID
      INTO P_REPORT_SUB_TITLE,CP_COMP_NIT
      FROM
        XLE_FIRSTPARTY_INFORMATION_V
      WHERE LEGAL_ENTITY_ID = P_LEGAL_ENTITY_ID;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        SELECT
          NAME
        INTO P_REPORT_SUB_TITLE
        FROM
          GL_SETS_OF_BOOKS
        WHERE SET_OF_BOOKS_ID = P_SOB_ID
          AND ROWNUM < 2;
    END;
    RETURN (TRUE);
  END BEFOREREPORT;

  FUNCTION AFTERREPORT RETURN BOOLEAN IS
  BEGIN
    /*SRW.USER_EXIT('FND SRWEXIT')*/NULL;
    RETURN (TRUE);
  END AFTERREPORT;

  FUNCTION CF_TOTALFORMULA(CS_REP_FIRSTVAL IN NUMBER
                          ,CS_REP_SECONDVAL IN NUMBER) RETURN NUMBER IS
  BEGIN
    CP_TOTAL := CS_REP_FIRSTVAL + CS_REP_SECONDVAL;
    RETURN (1);
  END CF_TOTALFORMULA;

  FUNCTION CP_COMP_NIT_P RETURN VARCHAR2 IS
  BEGIN
    RETURN CP_COMP_NIT;
  END CP_COMP_NIT_P;

  FUNCTION CP_COMP_NIT_VERF_DIG_P RETURN NUMBER IS
  BEGIN
    RETURN CP_COMP_NIT_VERF_DIG;
  END CP_COMP_NIT_VERF_DIG_P;

  FUNCTION CP_LITERAL_START_P RETURN NUMBER IS
  BEGIN
    RETURN CP_LITERAL_START;
  END CP_LITERAL_START_P;

  FUNCTION CP_LITERAL_END_P RETURN NUMBER IS
  BEGIN
    RETURN CP_LITERAL_END;
  END CP_LITERAL_END_P;

  FUNCTION CP_TOTAL_P RETURN NUMBER IS
  BEGIN
    RETURN CP_TOTAL;
  END CP_TOTAL_P;

END JL_JLCOGLNM_XMLP_PKG;



/
