--------------------------------------------------------
--  DDL for Package Body JTF_TASK_CONTACTS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."JTF_TASK_CONTACTS_PKG" as
/* $Header: jtftkcob.pls 115.17 2002/12/06 02:02:20 sachoudh ship $ */
procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_TASK_CONTACT_ID in NUMBER,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_CONTACT_ID in NUMBER,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_CONTACT_TYPE_CODE in VARCHAR2,
  X_ESCALATION_NOTIFY_FLAG in VARCHAR2,
  X_ESCALATION_REQUESTER_FLAG in VARCHAR2,
  X_PRIMARY_FLAG in VARCHAR2 default null
) is
  cursor C is select ROWID from JTF_TASK_CONTACTS
    where TASK_CONTACT_ID = X_TASK_CONTACT_ID
    ;
begin
  insert into JTF_TASK_CONTACTS (
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE_CATEGORY,
    TASK_CONTACT_ID,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TASK_ID,
    CONTACT_ID,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    OBJECT_VERSION_NUMBER,
    CONTACT_TYPE_CODE,
    ESCALATION_NOTIFY_FLAG,
    ESCALATION_REQUESTER_FLAG,
    PRIMARY_FLAG
  ) values (
    X_ATTRIBUTE4,
    X_ATTRIBUTE5,
    X_ATTRIBUTE6,
    X_ATTRIBUTE7,
    X_ATTRIBUTE8,
    X_ATTRIBUTE9,
    X_ATTRIBUTE10,
    X_ATTRIBUTE11,
    X_ATTRIBUTE12,
    X_ATTRIBUTE13,
    X_ATTRIBUTE14,
    X_ATTRIBUTE15,
    X_ATTRIBUTE_CATEGORY,
    X_TASK_CONTACT_ID,
    X_CREATED_BY,
    X_CREATION_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATE_LOGIN,
    X_TASK_ID,
    X_CONTACT_ID,
    X_ATTRIBUTE1,
    X_ATTRIBUTE2,
    X_ATTRIBUTE3,
    1,
    X_CONTACT_TYPE_CODE,
    X_ESCALATION_NOTIFY_FLAG,
    X_ESCALATION_REQUESTER_FLAG,
    X_PRIMARY_FLAG
    ) ;

  open c;
  fetch c into X_ROWID;
  if (c%notfound) then
    close c;
    raise no_data_found;
  end if;
  close c;

end INSERT_ROW;

procedure LOCK_ROW (
  X_TASK_CONTACT_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER
  ) is
  cursor c1 is select
        OBJECT_VERSION_NUMBER
    from JTF_TASK_CONTACTS
    where TASK_CONTACT_ID = X_TASK_CONTACT_ID
    for update of TASK_CONTACT_ID nowait;

    tlinfo c1%rowtype ;
begin
	open c1;
	fetch c1 into tlinfo;
	if (c1%notfound) then
		close c1;
		fnd_message.set_name('FND', 'FORM_RECORD_DELETED');
	    app_exception.raise_exception;
	 end if;
	 close c1;

  if  (tlinfo.OBJECT_VERSION_NUMBER = X_OBJECT_VERSION_NUMBER)
  then
    null;
  else
    fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
    app_exception.raise_exception;
  end if;

end LOCK_ROW;

procedure UPDATE_ROW (
  X_TASK_CONTACT_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_CONTACT_ID in NUMBER,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_CONTACT_TYPE_CODE in VARCHAR2,
  X_ESCALATION_NOTIFY_FLAG in VARCHAR2,
  X_ESCALATION_REQUESTER_FLAG in VARCHAR2,
  X_PRIMARY_FLAG in VARCHAR2 default null
) is
begin
  update JTF_TASK_CONTACTS set
    ATTRIBUTE4 = X_ATTRIBUTE4,
    OBJECT_VERSION_NUMBER = X_OBJECT_VERSION_NUMBER,
    ATTRIBUTE5 = X_ATTRIBUTE5,
    ATTRIBUTE6 = X_ATTRIBUTE6,
    ATTRIBUTE7 = X_ATTRIBUTE7,
    ATTRIBUTE8 = X_ATTRIBUTE8,
    ATTRIBUTE9 = X_ATTRIBUTE9,
    ATTRIBUTE10 = X_ATTRIBUTE10,
    ATTRIBUTE11 = X_ATTRIBUTE11,
    ATTRIBUTE12 = X_ATTRIBUTE12,
    ATTRIBUTE13 = X_ATTRIBUTE13,
    ATTRIBUTE14 = X_ATTRIBUTE14,
    ATTRIBUTE15 = X_ATTRIBUTE15,
    ATTRIBUTE_CATEGORY = X_ATTRIBUTE_CATEGORY,
    CONTACT_ID = X_CONTACT_ID,
    ATTRIBUTE1 = X_ATTRIBUTE1,
    ATTRIBUTE2 = X_ATTRIBUTE2,
    ATTRIBUTE3 = X_ATTRIBUTE3,
    TASK_ID = X_TASK_ID,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN,
    CONTACT_TYPE_CODE = X_CONTACT_TYPE_CODE,
    ESCALATION_NOTIFY_FLAG = X_ESCALATION_NOTIFY_FLAG,
    ESCALATION_REQUESTER_FLAG = X_ESCALATION_REQUESTER_FLAG,
    PRIMARY_FLAG = X_PRIMARY_FLAG
  where TASK_CONTACT_ID = X_TASK_CONTACT_ID ;

  if (sql%notfound) then
    raise no_data_found;
  end if;
end UPDATE_ROW;

procedure DELETE_ROW (
  X_TASK_CONTACT_ID in NUMBER
) is
begin
  delete from JTF_TASK_CONTACTS
  where TASK_CONTACT_ID = X_TASK_CONTACT_ID ;

  if (sql%notfound) then
    raise no_data_found;
  end if;

end DELETE_ROW;


end JTF_TASK_CONTACTS_PKG;

/
