--------------------------------------------------------
--  DDL for Package Body LNS_LOAN_HEADER_ALL_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."LNS_LOAN_HEADER_ALL_PKG" AS
/*$Header: LNS_LNHDR_TBLH_B.pls 120.7.12010000.7 2010/03/19 08:42:05 gparuchu ship $ */

PROCEDURE Insert_Row (
	X_LOAN_ID                         IN OUT NOCOPY NUMBER,
	X_ORG_ID                          IN     NUMBER,
	X_LOAN_NUMBER             	  IN OUT NOCOPY VARCHAR2,
	X_LOAN_DESCRIPTION		  IN 	 VARCHAR2,
	X_OBJECT_VERSION_NUMBER           IN     NUMBER,
	X_LOAN_APPLICATION_DATE           IN     DATE,
	X_END_DATE                        IN     DATE,
	X_INITIAL_LOAN_BALANCE            IN     NUMBER,
	X_LAST_PAYMENT_DATE               IN     DATE,
	X_LAST_PAYMENT_AMOUNT             IN     NUMBER,
	X_LOAN_TERM                       IN     NUMBER,
	X_LOAN_TERM_PERIOD                IN     VARCHAR2,
	X_AMORTIZED_TERM                  IN     NUMBER,
	X_AMORTIZED_TERM_PERIOD           IN     VARCHAR2,
	X_LOAN_STATUS			  IN     VARCHAR2,
	X_LOAN_ASSIGNED_TO                IN     NUMBER,
	X_LOAN_CURRENCY                   IN     VARCHAR2,
	X_LOAN_CLASS_CODE                 IN     VARCHAR2,
	X_LOAN_TYPE                       IN     VARCHAR2,
	X_LOAN_SUBTYPE                    IN     VARCHAR2,
	X_LOAN_PURPOSE_CODE               IN     VARCHAR2,
	X_CUST_ACCOUNT_ID                 IN     NUMBER,
	X_BILL_TO_ACCT_SITE_ID		  IN     NUMBER,
	X_LOAN_MATURITY_DATE              IN     DATE,
	X_LOAN_START_DATE                 IN     DATE,
	X_LOAN_CLOSING_DATE               IN     DATE,
	X_REFERENCE_ID                    IN     NUMBER,
	X_REFERENCE_NUMBER                IN     VARCHAR2,
	X_REFERENCE_DESCRIPTION           IN     VARCHAR2,
	X_REFERENCE_AMOUNT                IN     NUMBER,
	X_PRODUCT_FLAG                    IN     VARCHAR2,
	X_PRIMARY_BORROWER_ID             IN     NUMBER,
	X_PRODUCT_ID                      IN     NUMBER,
	X_REQUESTED_AMOUNT                IN     NUMBER,
	X_FUNDED_AMOUNT                   IN     NUMBER,
	X_LOAN_APPROVAL_DATE              IN     DATE,
	X_LOAN_APPROVED_BY                IN     NUMBER,
	X_ATTRIBUTE_CATEGORY              IN     VARCHAR2,
	X_ATTRIBUTE1                      IN     VARCHAR2,
	X_ATTRIBUTE2                      IN     VARCHAR2,
	X_ATTRIBUTE3                      IN     VARCHAR2,
	X_ATTRIBUTE4                      IN     VARCHAR2,
	X_ATTRIBUTE5                      IN     VARCHAR2,
	X_ATTRIBUTE6                      IN     VARCHAR2,
	X_ATTRIBUTE7                      IN     VARCHAR2,
	X_ATTRIBUTE8                      IN     VARCHAR2,
	X_ATTRIBUTE9                      IN     VARCHAR2,
	X_ATTRIBUTE10                     IN     VARCHAR2,
	X_ATTRIBUTE11                     IN     VARCHAR2,
	X_ATTRIBUTE12                     IN     VARCHAR2,
	X_ATTRIBUTE13                     IN     VARCHAR2,
	X_ATTRIBUTE14                     IN     VARCHAR2,
	X_ATTRIBUTE15                     IN     VARCHAR2,
	X_ATTRIBUTE16                     IN     VARCHAR2,
	X_ATTRIBUTE17                     IN     VARCHAR2,
	X_ATTRIBUTE18                     IN     VARCHAR2,
	X_ATTRIBUTE19                     IN     VARCHAR2,
	X_ATTRIBUTE20                     IN     VARCHAR2,
	X_LAST_BILLED_DATE                IN     DATE,
	X_CUSTOM_PAYMENTS_FLAG            IN     VARCHAR2,
	X_BILLED_FLAG                     IN     VARCHAR2,
	X_REFERENCE_NAME		  IN     VARCHAR2,
	X_REFERENCE_TYPE		  IN     VARCHAR2,
	X_REFERENCE_TYPE_ID		  IN     NUMBER,
	X_USSGL_TRANSACTION_CODE	  IN     VARCHAR2,
	X_GL_DATE			  IN     DATE,
	X_REC_ADJUSTMENT_NUMBER	  	  IN     VARCHAR2,
	X_CONTACT_REL_PARTY_ID            IN     NUMBER,
	X_CONTACT_PERS_PARTY_ID           IN     NUMBER,
	X_CREDIT_REVIEW_FLAG	          IN     VARCHAR2,
	X_EXCHANGE_RATE_TYPE		  IN     VARCHAR2,
	X_EXCHANGE_DATE			  IN     DATE,
	X_EXCHANGE_RATE			  IN     NUMBER,
	X_COLLATERAL_PERCENT		  IN     NUMBER,
	X_LAST_PAYMENT_NUMBER		  IN 	 NUMBER,
	X_LAST_AMORTIZATION_ID		  IN 	 NUMBER,
	X_LEGAL_ENTITY_ID     		  IN 	 NUMBER,
	X_OPEN_TO_TERM_FLAG               IN   VARCHAR2,
	X_MULTIPLE_FUNDING_FLAG           IN   VARCHAR2,
	X_LOAN_TYPE_ID                    IN   NUMBER,
	X_SECONDARY_STATUS                IN   VARCHAR2,
	X_OPEN_TO_TERM_EVENT              IN   VARCHAR2,
	X_BALLOON_PAYMENT_TYPE            IN   VARCHAR2,
	X_BALLOON_PAYMENT_AMOUNT          IN   NUMBER,
	X_CURRENT_PHASE                   IN   VARCHAR2,
	X_OPEN_LOAN_START_DATE            IN 		DATE,
	X_OPEN_LOAN_TERM                  IN 		NUMBER,
	X_OPEN_LOAN_TERM_PERIOD           IN 		VARCHAR2,
	X_OPEN_MATURITY_DATE			  IN 		DATE,
	X_FUNDS_RESERVED_FLAG             IN  	VARCHAR2,
	X_FUNDS_CHECK_DATE                IN  	DATE,
	X_SUBSIDY_RATE	                  IN  	NUMBER,
	X_APPLICATION_ID                  IN NUMBER,
	X_CREATED_BY_MODULE               IN VARCHAR2,
	X_PARTY_TYPE                      IN VARCHAR2,
	X_FORGIVENESS_FLAG		  IN     VARCHAR2,
	X_FORGIVENESS_PERCENT		  IN 	 NUMBER,
	X_DISABLE_BILLING_FLAG		IN VARCHAR2,
	X_ADD_REQUESTED_AMOUNT		  IN 	 NUMBER
) IS

  CURSOR l_insert is
    SELECT ROWID FROM LNS_LOAN_HEADERS_ALL
    WHERE LOAN_ID = X_LOAN_ID ;

  l_rowid varchar2(2000);

--To handle the reset of data due to change in loan currency in the UI
L_RESET_EXCHANGE_DATA VARCHAR2(1);
BEGIN

	--To handle the reset of data due to change in loan currency in the UI
	IF (X_EXCHANGE_RATE_TYPE = FND_API.G_MISS_CHAR) THEN
		L_RESET_EXCHANGE_DATA := 'Y';
	ELSE
		L_RESET_EXCHANGE_DATA := 'N';
	END IF;

	INSERT INTO LNS_LOAN_HEADERS_ALL
	(
		LOAN_ID
		,LAST_UPDATE_DATE
		,LAST_UPDATED_BY
		,LAST_UPDATE_LOGIN
		,CREATION_DATE
		,CREATED_BY
		,PROGRAM_ID
		,OBJECT_VERSION_NUMBER
		,REQUEST_ID
		,ORG_ID
		,LOAN_NUMBER
		,LOAN_APPLICATION_DATE
		,END_DATE
		,INITIAL_LOAN_BALANCE
		,LAST_PAYMENT_DATE
		,LAST_PAYMENT_AMOUNT
		,LOAN_TERM
		,LOAN_TERM_PERIOD
		,AMORTIZED_TERM
		,AMORTIZED_TERM_PERIOD
		,LOAN_STATUS
		,LOAN_ASSIGNED_TO
		,LOAN_CURRENCY
		,LOAN_CLASS_CODE
		,LOAN_TYPE
		,LOAN_SUBTYPE
		,LOAN_PURPOSE_CODE
		,CUST_ACCOUNT_ID
		,BILL_TO_ACCT_SITE_ID
		,LOAN_MATURITY_DATE
		,LOAN_START_DATE
		,LOAN_CLOSING_DATE
		,REFERENCE_ID
		,REFERENCE_NUMBER
		,REFERENCE_AMOUNT
		,PRODUCT_FLAG
		,PRIMARY_BORROWER_ID
		,PRODUCT_ID
		,REQUESTED_AMOUNT
		,FUNDED_AMOUNT
		,LOAN_APPROVAL_DATE
		,LOAN_APPROVED_BY
		,ATTRIBUTE_CATEGORY
		,ATTRIBUTE1
		,ATTRIBUTE2
		,ATTRIBUTE3
		,ATTRIBUTE4
		,ATTRIBUTE5
		,ATTRIBUTE6
		,ATTRIBUTE7
		,ATTRIBUTE8
		,ATTRIBUTE9
		,ATTRIBUTE10
		,ATTRIBUTE11
		,ATTRIBUTE12
		,ATTRIBUTE13
		,ATTRIBUTE14
		,ATTRIBUTE15
		,ATTRIBUTE16
		,ATTRIBUTE17
		,ATTRIBUTE18
		,ATTRIBUTE19
		,ATTRIBUTE20
		,LAST_BILLED_DATE
		,CUSTOM_PAYMENTS_FLAG
		,BILLED_FLAG
		,REFERENCE_NAME
		,REFERENCE_TYPE
		,REFERENCE_TYPE_ID
		,USSGL_TRANSACTION_CODE
		,GL_DATE
                ,REC_ADJUSTMENT_NUMBER
		,CONTACT_REL_PARTY_ID
		,CONTACT_PERS_PARTY_ID
		,CREDIT_REVIEW_FLAG
		,EXCHANGE_RATE_TYPE
		,EXCHANGE_DATE
		,EXCHANGE_RATE
		,COLLATERAL_PERCENT
		,LAST_PAYMENT_NUMBER
		,LAST_AMORTIZATION_ID
		,LEGAL_ENTITY_ID
		,OPEN_TO_TERM_FLAG
		,MULTIPLE_FUNDING_FLAG
		,LOAN_TYPE_ID
		,SECONDARY_STATUS
		,OPEN_TO_TERM_EVENT
		,BALLOON_PAYMENT_TYPE
		,BALLOON_PAYMENT_AMOUNT
		,CURRENT_PHASE
		,OPEN_LOAN_START_DATE
		,OPEN_LOAN_TERM
		,OPEN_LOAN_TERM_PERIOD
		,OPEN_MATURITY_DATE
		,FUNDS_RESERVED_FLAG
		,FUNDS_CHECK_DATE
		,SUBSIDY_RATE
		,APPLICATION_ID
		,CREATED_BY_MODULE
		,PARTY_TYPE
		,FORGIVENESS_FLAG
		,FORGIVENESS_PERCENT
		,DISABLE_BILLING_FLAG
		,ADD_REQUESTED_AMOUNT
	) VALUES (
		DECODE( X_LOAN_ID, FND_API.G_MISS_NUM, LNS_LOAN_HEADERS_S.NEXTVAL, NULL, LNS_LOAN_HEADERS_S.NEXTVAL, X_LOAN_ID )
		,LNS_UTILITY_PUB.LAST_UPDATE_DATE
		,LNS_UTILITY_PUB.LAST_UPDATED_BY
		,LNS_UTILITY_PUB.LAST_UPDATE_LOGIN
		,LNS_UTILITY_PUB.CREATION_DATE
		,LNS_UTILITY_PUB.CREATED_BY
		,LNS_UTILITY_PUB.PROGRAM_ID
		,DECODE( X_OBJECT_VERSION_NUMBER, FND_API.G_MISS_NUM, NULL, X_OBJECT_VERSION_NUMBER )
		,LNS_UTILITY_PUB.REQUEST_ID
		,DECODE( X_ORG_ID, FND_API.G_MISS_NUM, NULL, X_ORG_ID )
		,DECODE( X_LOAN_NUMBER, FND_API.G_MISS_CHAR, 'L'||TO_CHAR(LNS_LOAN_NUMBER_S.NEXTVAL), NULL, 'L'||TO_CHAR(LNS_LOAN_NUMBER_S.NEXTVAL), X_LOAN_NUMBER )
		,DECODE( X_LOAN_APPLICATION_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_APPLICATION_DATE )
		,DECODE( X_END_DATE, FND_API.G_MISS_DATE, NULL, X_END_DATE )
		,DECODE( X_INITIAL_LOAN_BALANCE, FND_API.G_MISS_NUM, NULL, X_INITIAL_LOAN_BALANCE )
		,DECODE( X_LAST_PAYMENT_DATE, FND_API.G_MISS_DATE, NULL, X_LAST_PAYMENT_DATE )
		,DECODE( X_LAST_PAYMENT_AMOUNT, FND_API.G_MISS_NUM, NULL, X_LAST_PAYMENT_AMOUNT )
		,DECODE( X_LOAN_TERM, FND_API.G_MISS_NUM, NULL, X_LOAN_TERM )
		,DECODE( X_LOAN_TERM_PERIOD, FND_API.G_MISS_CHAR, NULL, X_LOAN_TERM_PERIOD )
		,DECODE( X_AMORTIZED_TERM, FND_API.G_MISS_NUM, NULL, X_AMORTIZED_TERM )
		,DECODE( X_AMORTIZED_TERM_PERIOD, FND_API.G_MISS_CHAR, NULL, X_AMORTIZED_TERM_PERIOD )
		,DECODE( X_LOAN_STATUS, FND_API.G_MISS_CHAR, NULL, X_LOAN_STATUS )
		,DECODE( X_LOAN_ASSIGNED_TO, FND_API.G_MISS_NUM, NULL, X_LOAN_ASSIGNED_TO )
		,DECODE( X_LOAN_CURRENCY, FND_API.G_MISS_CHAR, NULL, X_LOAN_CURRENCY )
		,DECODE( X_LOAN_CLASS_CODE, FND_API.G_MISS_CHAR, NULL, X_LOAN_CLASS_CODE )
		,DECODE( X_LOAN_TYPE, FND_API.G_MISS_CHAR, NULL, X_LOAN_TYPE )
		,DECODE( X_LOAN_SUBTYPE, FND_API.G_MISS_CHAR, NULL, X_LOAN_SUBTYPE )
		,DECODE( X_LOAN_PURPOSE_CODE, FND_API.G_MISS_CHAR, NULL, X_LOAN_PURPOSE_CODE )
		,DECODE( X_CUST_ACCOUNT_ID, FND_API.G_MISS_NUM, NULL, X_CUST_ACCOUNT_ID )
		,DECODE( X_BILL_TO_ACCT_SITE_ID, FND_API.G_MISS_NUM, NULL, X_BILL_TO_ACCT_SITE_ID )
		,DECODE( X_LOAN_MATURITY_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_MATURITY_DATE )
		,DECODE( X_LOAN_START_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_START_DATE )
		,DECODE( X_LOAN_CLOSING_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_CLOSING_DATE )
		,DECODE( X_REFERENCE_ID, FND_API.G_MISS_NUM, NULL, X_REFERENCE_ID )
		,DECODE( X_REFERENCE_NUMBER, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_NUMBER )
		,DECODE( X_REFERENCE_AMOUNT, FND_API.G_MISS_NUM, NULL, X_REFERENCE_AMOUNT )
		,DECODE( X_PRODUCT_FLAG, FND_API.G_MISS_CHAR, NULL, X_PRODUCT_FLAG )
		,DECODE( X_PRIMARY_BORROWER_ID, FND_API.G_MISS_NUM, NULL, X_PRIMARY_BORROWER_ID )
		,DECODE( X_PRODUCT_ID, FND_API.G_MISS_NUM, NULL, X_PRODUCT_ID )
		,DECODE( X_REQUESTED_AMOUNT, FND_API.G_MISS_NUM, NULL, X_REQUESTED_AMOUNT )
		,DECODE( X_FUNDED_AMOUNT, FND_API.G_MISS_NUM, NULL, X_FUNDED_AMOUNT )
		,DECODE( X_LOAN_APPROVAL_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_APPROVAL_DATE )
		,DECODE( X_LOAN_APPROVED_BY, FND_API.G_MISS_NUM, NULL, X_LOAN_APPROVED_BY )
		,DECODE( X_ATTRIBUTE_CATEGORY, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE_CATEGORY )
		,DECODE( X_ATTRIBUTE1, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE1 )
		,DECODE( X_ATTRIBUTE2, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE2 )
		,DECODE( X_ATTRIBUTE3, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE3 )
		,DECODE( X_ATTRIBUTE4, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE4 )
		,DECODE( X_ATTRIBUTE5, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE5 )
		,DECODE( X_ATTRIBUTE6, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE6 )
		,DECODE( X_ATTRIBUTE7, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE7 )
		,DECODE( X_ATTRIBUTE8, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE8 )
		,DECODE( X_ATTRIBUTE9, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE9 )
		,DECODE( X_ATTRIBUTE10, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE10 )
		,DECODE( X_ATTRIBUTE11, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE11 )
		,DECODE( X_ATTRIBUTE12, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE12 )
		,DECODE( X_ATTRIBUTE13, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE13 )
		,DECODE( X_ATTRIBUTE14, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE14 )
		,DECODE( X_ATTRIBUTE15, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE15 )
		,DECODE( X_ATTRIBUTE16, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE16 )
		,DECODE( X_ATTRIBUTE17, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE17 )
		,DECODE( X_ATTRIBUTE18, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE18 )
		,DECODE( X_ATTRIBUTE19, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE19 )
		,DECODE( X_ATTRIBUTE20, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE20 )
		,DECODE( X_LAST_BILLED_DATE, FND_API.G_MISS_CHAR, NULL, X_LAST_BILLED_DATE )
		,DECODE( X_CUSTOM_PAYMENTS_FLAG, FND_API.G_MISS_CHAR, NULL, X_CUSTOM_PAYMENTS_FLAG )
		,DECODE( X_BILLED_FLAG, FND_API.G_MISS_CHAR, NULL, X_BILLED_FLAG )
		,DECODE( X_REFERENCE_NAME, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_NAME )
		,DECODE( X_REFERENCE_TYPE, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_TYPE )
		,DECODE( X_REFERENCE_TYPE_ID, FND_API.G_MISS_NUM, NULL, X_REFERENCE_TYPE_ID )
		,DECODE( X_USSGL_TRANSACTION_CODE, FND_API.G_MISS_CHAR, NULL, X_USSGL_TRANSACTION_CODE )
		,DECODE( X_GL_DATE, FND_API.G_MISS_DATE, NULL, X_GL_DATE )
		,DECODE( X_REC_ADJUSTMENT_NUMBER, FND_API.G_MISS_CHAR, NULL, X_REC_ADJUSTMENT_NUMBER )
		,DECODE( X_CONTACT_REL_PARTY_ID, FND_API.G_MISS_NUM, NULL, X_CONTACT_REL_PARTY_ID )
		,DECODE( X_CONTACT_PERS_PARTY_ID, FND_API.G_MISS_NUM, NULL, X_CONTACT_PERS_PARTY_ID )
		,DECODE( X_CREDIT_REVIEW_FLAG, FND_API.G_MISS_CHAR, NULL, X_CREDIT_REVIEW_FLAG )
		,DECODE( X_EXCHANGE_RATE_TYPE, FND_API.G_MISS_CHAR, NULL, X_EXCHANGE_RATE_TYPE )
		,DECODE( L_RESET_EXCHANGE_DATA, 'Y', NULL, ( DECODE( X_EXCHANGE_DATE, FND_API.G_MISS_DATE, NULL, X_EXCHANGE_DATE ) ) )
		,DECODE( L_RESET_EXCHANGE_DATA, 'Y', NULL, ( DECODE( X_EXCHANGE_RATE, FND_API.G_MISS_NUM, NULL, X_EXCHANGE_RATE ) ) )
		,DECODE( X_COLLATERAL_PERCENT, FND_API.G_MISS_NUM, NULL, 0, NULL, X_COLLATERAL_PERCENT )
		,DECODE( X_LAST_PAYMENT_NUMBER, FND_API.G_MISS_NUM, NULL, 0, NULL, X_LAST_PAYMENT_NUMBER )
		,DECODE( X_LAST_AMORTIZATION_ID, FND_API.G_MISS_NUM, NULL, 0, NULL, X_LAST_AMORTIZATION_ID )
		,DECODE( X_LEGAL_ENTITY_ID, FND_API.G_MISS_NUM, NULL, 0, NULL, X_LEGAL_ENTITY_ID )
		,DECODE( X_OPEN_TO_TERM_FLAG, FND_API.G_MISS_CHAR, NULL, X_OPEN_TO_TERM_FLAG )
		,DECODE( X_MULTIPLE_FUNDING_FLAG, FND_API.G_MISS_CHAR, NULL, X_MULTIPLE_FUNDING_FLAG )
		,DECODE( X_LOAN_TYPE_ID, FND_API.G_MISS_NUM, NULL, 0, NULL, X_LOAN_TYPE_ID )
		,DECODE( X_SECONDARY_STATUS, FND_API.G_MISS_CHAR, NULL, X_SECONDARY_STATUS )
		,DECODE( X_OPEN_TO_TERM_EVENT, FND_API.G_MISS_CHAR, NULL, X_OPEN_TO_TERM_EVENT )
		,DECODE( X_BALLOON_PAYMENT_TYPE, FND_API.G_MISS_CHAR, NULL, X_BALLOON_PAYMENT_TYPE )
		,DECODE( X_BALLOON_PAYMENT_AMOUNT, FND_API.G_MISS_NUM, NULL, X_BALLOON_PAYMENT_AMOUNT )
		,DECODE( X_CURRENT_PHASE, FND_API.G_MISS_CHAR, NULL, X_CURRENT_PHASE )
		,DECODE( X_OPEN_LOAN_START_DATE, FND_API.G_MISS_DATE, NULL, X_OPEN_LOAN_START_DATE )
		,DECODE( X_OPEN_LOAN_TERM, FND_API.G_MISS_NUM, NULL, X_OPEN_LOAN_TERM )
		,DECODE( X_OPEN_LOAN_TERM_PERIOD, FND_API.G_MISS_CHAR, NULL, X_OPEN_LOAN_TERM_PERIOD )
		,DECODE( X_OPEN_MATURITY_DATE, FND_API.G_MISS_DATE, NULL, X_OPEN_MATURITY_DATE )
		,DECODE( X_FUNDS_RESERVED_FLAG, FND_API.G_MISS_CHAR, NULL, X_FUNDS_RESERVED_FLAG )
		,DECODE( X_FUNDS_CHECK_DATE, FND_API.G_MISS_DATE, NULL, X_FUNDS_CHECK_DATE )
		,DECODE( X_SUBSIDY_RATE, FND_API.G_MISS_NUM, NULL, X_SUBSIDY_RATE )
		,DECODE( X_APPLICATION_ID, FND_API.G_MISS_NUM, NULL, X_APPLICATION_ID )
		,DECODE( X_CREATED_BY_MODULE, FND_API.G_MISS_CHAR, NULL, X_CREATED_BY_MODULE )
		,DECODE( X_PARTY_TYPE, FND_API.G_MISS_CHAR, NULL, X_PARTY_TYPE )
		,DECODE( X_FORGIVENESS_FLAG, FND_API.G_MISS_CHAR, NULL, X_FORGIVENESS_FLAG )
		,DECODE( X_FORGIVENESS_PERCENT, FND_API.G_MISS_NUM, NULL, 0, NULL, X_FORGIVENESS_PERCENT )
		,DECODE( X_DISABLE_BILLING_FLAG, FND_API.G_MISS_CHAR, NULL, X_DISABLE_BILLING_FLAG )
		,DECODE( X_ADD_REQUESTED_AMOUNT, FND_API.G_MISS_NUM, NULL, 0, NULL, X_ADD_REQUESTED_AMOUNT )
        ) RETURNING
            LOAN_ID,
            LOAN_NUMBER
        INTO
            X_LOAN_ID,
            X_LOAN_NUMBER;


	INSERT INTO LNS_LOAN_HEADERS_ALL_TL (
              LOAN_ID
             ,LOAN_DESCRIPTION
             ,REFERENCE_DESCRIPTION
             ,LANGUAGE
             ,SOURCE_LANG
             ,CREATED_BY
             ,CREATION_DATE
             ,LAST_UPDATE_DATE
             ,LAST_UPDATED_BY
             ,LAST_UPDATE_LOGIN
          ) SELECT
              X_LOAN_ID
	     ,DECODE( X_LOAN_DESCRIPTION, FND_API.G_MISS_CHAR, NULL, X_LOAN_DESCRIPTION )
             ,DECODE( X_REFERENCE_DESCRIPTION, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_DESCRIPTION )
             ,L.LANGUAGE_CODE
             ,userenv('LANG')
             ,fnd_global.user_id
             ,sysdate
             ,sysdate
             ,fnd_global.user_id
             ,fnd_global.user_id
          FROM FND_LANGUAGES L
          where L.INSTALLED_FLAG in ('I', 'B')
          AND not exists
            (select NULL
            from LNS_LOAN_HEADERS_ALL_TL T
            where T.LOAN_ID = X_LOAN_ID
            and T.LANGUAGE = L.LANGUAGE_CODE);

          OPEN l_insert;
          FETCH l_insert INTO l_rowid;
          IF (l_insert%notfound) THEN
            CLOSE l_insert;
            RAISE no_data_found;
          END IF;
          CLOSE l_insert;

END Insert_Row;

PROCEDURE Update_Row(
	X_Rowid				  IN OUT NOCOPY VARCHAR2,
	X_LOAN_ID                         IN     NUMBER,
	X_ORG_ID                          IN     NUMBER,
	X_LOAN_NUMBER             	  IN     VARCHAR2,
	X_LOAN_DESCRIPTION		  IN 	 VARCHAR2,
	X_OBJECT_VERSION_NUMBER           IN     NUMBER,
	X_LOAN_APPLICATION_DATE           IN     DATE,
	X_END_DATE                        IN     DATE,
	X_INITIAL_LOAN_BALANCE            IN     NUMBER,
	X_LAST_PAYMENT_DATE               IN     DATE,
	X_LAST_PAYMENT_AMOUNT             IN     NUMBER,
	X_LOAN_TERM                       IN     NUMBER,
	X_LOAN_TERM_PERIOD                IN     VARCHAR2,
	X_AMORTIZED_TERM                  IN     NUMBER,
	X_AMORTIZED_TERM_PERIOD           IN     VARCHAR2,
	X_LOAN_STATUS			  IN     VARCHAR2,
	X_LOAN_ASSIGNED_TO                IN     NUMBER,
	X_LOAN_CURRENCY                   IN     VARCHAR2,
	X_LOAN_CLASS_CODE                 IN     VARCHAR2,
	X_LOAN_TYPE                       IN     VARCHAR2,
	X_LOAN_SUBTYPE                    IN     VARCHAR2,
	X_LOAN_PURPOSE_CODE               IN     VARCHAR2,
	X_CUST_ACCOUNT_ID                 IN     NUMBER,
	X_BILL_TO_ACCT_SITE_ID		  IN     NUMBER,
	X_LOAN_MATURITY_DATE              IN     DATE,
	X_LOAN_START_DATE                 IN     DATE,
	X_LOAN_CLOSING_DATE               IN     DATE,
	X_REFERENCE_ID                    IN     NUMBER,
	X_REFERENCE_NUMBER                IN     VARCHAR2,
	X_REFERENCE_DESCRIPTION           IN     VARCHAR2,
	X_REFERENCE_AMOUNT                IN     NUMBER,
	X_PRODUCT_FLAG                    IN     VARCHAR2,
	X_PRIMARY_BORROWER_ID             IN     NUMBER,
	X_PRODUCT_ID                      IN     NUMBER,
	X_REQUESTED_AMOUNT                IN     NUMBER,
	X_FUNDED_AMOUNT                   IN     NUMBER,
	X_LOAN_APPROVAL_DATE              IN     DATE,
	X_LOAN_APPROVED_BY                IN     NUMBER,
	X_ATTRIBUTE_CATEGORY              IN     VARCHAR2,
	X_ATTRIBUTE1                      IN     VARCHAR2,
	X_ATTRIBUTE2                      IN     VARCHAR2,
	X_ATTRIBUTE3                      IN     VARCHAR2,
	X_ATTRIBUTE4                      IN     VARCHAR2,
	X_ATTRIBUTE5                      IN     VARCHAR2,
	X_ATTRIBUTE6                      IN     VARCHAR2,
	X_ATTRIBUTE7                      IN     VARCHAR2,
	X_ATTRIBUTE8                      IN     VARCHAR2,
	X_ATTRIBUTE9                      IN     VARCHAR2,
	X_ATTRIBUTE10                     IN     VARCHAR2,
	X_ATTRIBUTE11                     IN     VARCHAR2,
	X_ATTRIBUTE12                     IN     VARCHAR2,
	X_ATTRIBUTE13                     IN     VARCHAR2,
	X_ATTRIBUTE14                     IN     VARCHAR2,
	X_ATTRIBUTE15                     IN     VARCHAR2,
	X_ATTRIBUTE16                     IN     VARCHAR2,
	X_ATTRIBUTE17                     IN     VARCHAR2,
	X_ATTRIBUTE18                     IN     VARCHAR2,
	X_ATTRIBUTE19                     IN     VARCHAR2,
	X_ATTRIBUTE20                     IN     VARCHAR2,
	X_LAST_BILLED_DATE                IN     DATE,
	X_CUSTOM_PAYMENTS_FLAG            IN     VARCHAR2,
	X_BILLED_FLAG                     IN     VARCHAR2,
	X_REFERENCE_NAME		  IN     VARCHAR2,
	X_REFERENCE_TYPE		  IN     VARCHAR2,
	X_REFERENCE_TYPE_ID		  IN     NUMBER,
	X_USSGL_TRANSACTION_CODE	  IN     VARCHAR2,
	X_GL_DATE			  IN     DATE,
	X_REC_ADJUSTMENT_NUMBER	  IN     VARCHAR2,
	X_CONTACT_REL_PARTY_ID            IN     NUMBER,
	X_CONTACT_PERS_PARTY_ID           IN     NUMBER,
	X_CREDIT_REVIEW_FLAG	          IN     VARCHAR2,
	X_EXCHANGE_RATE_TYPE		  IN     VARCHAR2,
	X_EXCHANGE_DATE			  IN     DATE,
	X_EXCHANGE_RATE			  IN     NUMBER,
	X_COLLATERAL_PERCENT		  IN     NUMBER,
	X_LAST_PAYMENT_NUMBER		  IN 	 NUMBER,
	X_LAST_AMORTIZATION_ID		  IN 	 NUMBER,
	X_LEGAL_ENTITY_ID     		  IN 	 NUMBER,
	X_OPEN_TO_TERM_FLAG               IN   VARCHAR2,
	X_MULTIPLE_FUNDING_FLAG           IN   VARCHAR2,
	X_LOAN_TYPE_ID                    IN   NUMBER,
	X_SECONDARY_STATUS                IN   VARCHAR2,
	X_OPEN_TO_TERM_EVENT              IN   VARCHAR2,
	X_BALLOON_PAYMENT_TYPE            IN   VARCHAR2,
	X_BALLOON_PAYMENT_AMOUNT          IN   NUMBER,
	X_CURRENT_PHASE                   IN   VARCHAR2,
	X_OPEN_LOAN_START_DATE            IN 		DATE,
	X_OPEN_LOAN_TERM                  IN 		NUMBER,
	X_OPEN_LOAN_TERM_PERIOD           IN 		VARCHAR2,
	X_OPEN_MATURITY_DATE              IN 		DATE,
	X_FUNDS_RESERVED_FLAG             IN  	VARCHAR2,
	X_FUNDS_CHECK_DATE                IN  	DATE,
	X_SUBSIDY_RATE	                   IN  	NUMBER,
	X_APPLICATION_ID                  IN NUMBER,
	X_CREATED_BY_MODULE               IN VARCHAR2,
	X_PARTY_TYPE                      IN VARCHAR2,
	X_FORGIVENESS_FLAG		  IN     VARCHAR2,
	X_FORGIVENESS_PERCENT		  IN 	 NUMBER,
	X_DISABLE_BILLING_FLAG		IN VARCHAR2,
	X_ADD_REQUESTED_AMOUNT		  IN 	 NUMBER
) IS

--To handle the reset of data due to change in loan currency in the UI
L_RESET_EXCHANGE_DATA VARCHAR2(1);
BEGIN

	--To handle the reset of data due to change in loan currency in the UI
	IF (X_EXCHANGE_RATE_TYPE = FND_API.G_MISS_CHAR) THEN
		L_RESET_EXCHANGE_DATA := 'Y';
	ELSE
		L_RESET_EXCHANGE_DATA := 'N';
	END IF;

	--Call to record history
	LNS_LOAN_HISTORY_PUB.log_record_pre(
		p_id => X_LOAN_ID,
		p_primary_key_name => 'LOAN_ID',
		p_table_name => 'LNS_LOAN_HEADERS_ALL'
	);

	UPDATE LNS_LOAN_HEADERS_ALL SET
		LOAN_ID = DECODE( X_LOAN_ID, NULL, LOAN_ID, FND_API.G_MISS_NUM, NULL, X_LOAN_ID )
		,LAST_UPDATE_DATE = LNS_UTILITY_PUB.LAST_UPDATE_DATE
		,LAST_UPDATED_BY = LNS_UTILITY_PUB.LAST_UPDATED_BY
		,LAST_UPDATE_LOGIN = LNS_UTILITY_PUB.LAST_UPDATE_LOGIN
		,PROGRAM_ID = LNS_UTILITY_PUB.PROGRAM_ID
		,OBJECT_VERSION_NUMBER = DECODE( X_OBJECT_VERSION_NUMBER, NULL, OBJECT_VERSION_NUMBER, FND_API.G_MISS_NUM, NULL, X_OBJECT_VERSION_NUMBER )
		,REQUEST_ID = LNS_UTILITY_PUB.REQUEST_ID
		,ORG_ID = DECODE( X_ORG_ID, NULL, ORG_ID, FND_API.G_MISS_NUM, NULL, X_ORG_ID )
		,LOAN_NUMBER = DECODE( X_LOAN_NUMBER, NULL, LOAN_NUMBER, FND_API.G_MISS_CHAR, NULL, X_LOAN_NUMBER )
		,LOAN_APPLICATION_DATE = DECODE( X_LOAN_APPLICATION_DATE, NULL, LOAN_APPLICATION_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_APPLICATION_DATE )
		,END_DATE = DECODE( X_END_DATE, NULL, END_DATE, FND_API.G_MISS_DATE, NULL, X_END_DATE )
		,INITIAL_LOAN_BALANCE = DECODE( X_INITIAL_LOAN_BALANCE, NULL, INITIAL_LOAN_BALANCE, FND_API.G_MISS_NUM, NULL, X_INITIAL_LOAN_BALANCE )
		,LAST_PAYMENT_DATE = DECODE( X_LAST_PAYMENT_DATE, NULL, LAST_PAYMENT_DATE, FND_API.G_MISS_DATE, NULL, X_LAST_PAYMENT_DATE )
		,LAST_PAYMENT_AMOUNT = DECODE( X_LAST_PAYMENT_AMOUNT, NULL, LAST_PAYMENT_AMOUNT, FND_API.G_MISS_NUM, NULL, X_LAST_PAYMENT_AMOUNT )
		,LOAN_TERM = DECODE( X_LOAN_TERM, NULL, LOAN_TERM, FND_API.G_MISS_NUM, NULL, X_LOAN_TERM )
		,LOAN_TERM_PERIOD = DECODE( X_LOAN_TERM_PERIOD, NULL, LOAN_TERM_PERIOD, FND_API.G_MISS_CHAR, NULL, X_LOAN_TERM_PERIOD )
		,AMORTIZED_TERM = DECODE( X_AMORTIZED_TERM, NULL, AMORTIZED_TERM, FND_API.G_MISS_NUM, NULL, X_AMORTIZED_TERM )
		,AMORTIZED_TERM_PERIOD = DECODE( X_AMORTIZED_TERM_PERIOD, NULL, AMORTIZED_TERM_PERIOD, FND_API.G_MISS_CHAR, NULL, X_AMORTIZED_TERM_PERIOD )
		,LOAN_STATUS = DECODE( X_LOAN_STATUS, NULL, LOAN_STATUS, FND_API.G_MISS_CHAR, NULL, X_LOAN_STATUS )
		,LOAN_ASSIGNED_TO = DECODE( X_LOAN_ASSIGNED_TO, NULL, LOAN_ASSIGNED_TO, FND_API.G_MISS_NUM, NULL, X_LOAN_ASSIGNED_TO )
		,LOAN_CURRENCY = DECODE( X_LOAN_CURRENCY, NULL, LOAN_CURRENCY, FND_API.G_MISS_CHAR, NULL, X_LOAN_CURRENCY )
		,LOAN_CLASS_CODE = DECODE( X_LOAN_CLASS_CODE, NULL, LOAN_CLASS_CODE, FND_API.G_MISS_CHAR, NULL, X_LOAN_CLASS_CODE )
		,LOAN_TYPE = DECODE( X_LOAN_TYPE, NULL, LOAN_TYPE, FND_API.G_MISS_CHAR, NULL, X_LOAN_TYPE )
		,LOAN_SUBTYPE = DECODE( X_LOAN_SUBTYPE, NULL, LOAN_SUBTYPE, FND_API.G_MISS_CHAR, NULL, X_LOAN_SUBTYPE )
		,LOAN_PURPOSE_CODE = DECODE( X_LOAN_PURPOSE_CODE, NULL, LOAN_PURPOSE_CODE, FND_API.G_MISS_CHAR, NULL, X_LOAN_PURPOSE_CODE )
		,CUST_ACCOUNT_ID = DECODE( X_CUST_ACCOUNT_ID, NULL, CUST_ACCOUNT_ID, FND_API.G_MISS_NUM, NULL, X_CUST_ACCOUNT_ID )
		,BILL_TO_ACCT_SITE_ID = DECODE( X_BILL_TO_ACCT_SITE_ID, NULL, BILL_TO_ACCT_SITE_ID, FND_API.G_MISS_NUM, NULL, X_BILL_TO_ACCT_SITE_ID )
		,LOAN_MATURITY_DATE = DECODE( X_LOAN_MATURITY_DATE, NULL, LOAN_MATURITY_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_MATURITY_DATE )
		,LOAN_START_DATE = DECODE( X_LOAN_START_DATE, NULL, LOAN_START_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_START_DATE )
		,LOAN_CLOSING_DATE = DECODE( X_LOAN_CLOSING_DATE, NULL, LOAN_CLOSING_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_CLOSING_DATE )
		,REFERENCE_ID = DECODE( X_REFERENCE_ID, NULL, REFERENCE_ID, FND_API.G_MISS_NUM, NULL, X_REFERENCE_ID )
		,REFERENCE_NUMBER = DECODE( X_REFERENCE_NUMBER, NULL, REFERENCE_NUMBER, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_NUMBER )
		,REFERENCE_AMOUNT = DECODE( X_REFERENCE_AMOUNT, NULL, REFERENCE_AMOUNT, FND_API.G_MISS_NUM, NULL, X_REFERENCE_AMOUNT )
		,PRODUCT_FLAG = DECODE( X_PRODUCT_FLAG, NULL, PRODUCT_FLAG, FND_API.G_MISS_CHAR, NULL, X_PRODUCT_FLAG )
		,PRIMARY_BORROWER_ID = DECODE( X_PRIMARY_BORROWER_ID, NULL, PRIMARY_BORROWER_ID, FND_API.G_MISS_NUM, NULL, X_PRIMARY_BORROWER_ID )
		,PRODUCT_ID = DECODE( X_PRODUCT_ID, NULL, PRODUCT_ID, FND_API.G_MISS_NUM, NULL, X_PRODUCT_ID )
		,REQUESTED_AMOUNT = DECODE( X_REQUESTED_AMOUNT, NULL, REQUESTED_AMOUNT, FND_API.G_MISS_NUM, NULL, X_REQUESTED_AMOUNT )
		,FUNDED_AMOUNT = DECODE( X_FUNDED_AMOUNT, NULL, FUNDED_AMOUNT, FND_API.G_MISS_NUM, NULL, X_FUNDED_AMOUNT )
		,LOAN_APPROVAL_DATE = DECODE( X_LOAN_APPROVAL_DATE, NULL, LOAN_APPROVAL_DATE, FND_API.G_MISS_DATE, NULL, X_LOAN_APPROVAL_DATE )
		,LOAN_APPROVED_BY = DECODE( X_LOAN_APPROVED_BY, NULL, LOAN_APPROVED_BY, FND_API.G_MISS_NUM, NULL, X_LOAN_APPROVED_BY )
		,ATTRIBUTE_CATEGORY = DECODE( X_ATTRIBUTE_CATEGORY, NULL, ATTRIBUTE_CATEGORY, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE_CATEGORY )
		,ATTRIBUTE1 = DECODE( X_ATTRIBUTE1, NULL, ATTRIBUTE1, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE1 )
		,ATTRIBUTE2 = DECODE( X_ATTRIBUTE2, NULL, ATTRIBUTE2, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE2 )
		,ATTRIBUTE3 = DECODE( X_ATTRIBUTE3, NULL, ATTRIBUTE3, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE3 )
		,ATTRIBUTE4 = DECODE( X_ATTRIBUTE4, NULL, ATTRIBUTE4, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE4 )
		,ATTRIBUTE5 = DECODE( X_ATTRIBUTE5, NULL, ATTRIBUTE5, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE5 )
		,ATTRIBUTE6 = DECODE( X_ATTRIBUTE6, NULL, ATTRIBUTE6, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE6 )
		,ATTRIBUTE7 = DECODE( X_ATTRIBUTE7, NULL, ATTRIBUTE7, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE7 )
		,ATTRIBUTE8 = DECODE( X_ATTRIBUTE8, NULL, ATTRIBUTE8, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE8 )
		,ATTRIBUTE9 = DECODE( X_ATTRIBUTE9, NULL, ATTRIBUTE9, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE9 )
		,ATTRIBUTE10 = DECODE( X_ATTRIBUTE10, NULL, ATTRIBUTE10, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE10 )
		,ATTRIBUTE11 = DECODE( X_ATTRIBUTE11, NULL, ATTRIBUTE11, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE11 )
		,ATTRIBUTE12 = DECODE( X_ATTRIBUTE12, NULL, ATTRIBUTE12, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE12 )
		,ATTRIBUTE13 = DECODE( X_ATTRIBUTE13, NULL, ATTRIBUTE13, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE13 )
		,ATTRIBUTE14 = DECODE( X_ATTRIBUTE14, NULL, ATTRIBUTE14, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE14 )
		,ATTRIBUTE15 = DECODE( X_ATTRIBUTE15, NULL, ATTRIBUTE15, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE15 )
		,ATTRIBUTE16 = DECODE( X_ATTRIBUTE16, NULL, ATTRIBUTE16, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE16 )
		,ATTRIBUTE17 = DECODE( X_ATTRIBUTE17, NULL, ATTRIBUTE17, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE17 )
		,ATTRIBUTE18 = DECODE( X_ATTRIBUTE18, NULL, ATTRIBUTE18, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE18 )
		,ATTRIBUTE19 = DECODE( X_ATTRIBUTE19, NULL, ATTRIBUTE19, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE19 )
		,ATTRIBUTE20 = DECODE( X_ATTRIBUTE20, NULL, ATTRIBUTE20, FND_API.G_MISS_CHAR, NULL, X_ATTRIBUTE20 )
		,LAST_BILLED_DATE = DECODE( X_LAST_BILLED_DATE, NULL, LAST_BILLED_DATE, FND_API.G_MISS_DATE, NULL, X_LAST_BILLED_DATE )
		,CUSTOM_PAYMENTS_FLAG = DECODE( X_CUSTOM_PAYMENTS_FLAG, NULL, CUSTOM_PAYMENTS_FLAG, FND_API.G_MISS_CHAR, NULL, X_CUSTOM_PAYMENTS_FLAG )
		,BILLED_FLAG = DECODE( X_BILLED_FLAG, NULL, BILLED_FLAG, FND_API.G_MISS_CHAR, NULL, X_BILLED_FLAG )
		,REFERENCE_NAME = DECODE( X_REFERENCE_NAME, NULL, REFERENCE_NAME, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_NAME )
		,REFERENCE_TYPE = DECODE( X_REFERENCE_TYPE, NULL, REFERENCE_TYPE, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_TYPE )
		,REFERENCE_TYPE_ID = DECODE( X_REFERENCE_TYPE_ID, NULL, REFERENCE_TYPE_ID, FND_API.G_MISS_NUM, NULL, X_REFERENCE_TYPE_ID )
		,USSGL_TRANSACTION_CODE = DECODE( X_USSGL_TRANSACTION_CODE, NULL, USSGL_TRANSACTION_CODE, FND_API.G_MISS_CHAR, NULL, X_USSGL_TRANSACTION_CODE )
		,GL_DATE = DECODE( X_GL_DATE, NULL, GL_DATE, FND_API.G_MISS_DATE, NULL, X_GL_DATE )
		,REC_ADJUSTMENT_NUMBER = DECODE( X_REC_ADJUSTMENT_NUMBER, NULL, REC_ADJUSTMENT_NUMBER, FND_API.G_MISS_CHAR, NULL, X_REC_ADJUSTMENT_NUMBER )
		,CONTACT_REL_PARTY_ID = DECODE( X_CONTACT_REL_PARTY_ID, NULL, CONTACT_REL_PARTY_ID, FND_API.G_MISS_NUM, NULL, X_CONTACT_REL_PARTY_ID )
		,CONTACT_PERS_PARTY_ID = DECODE( X_CONTACT_PERS_PARTY_ID, NULL, CONTACT_PERS_PARTY_ID, FND_API.G_MISS_NUM, NULL, X_CONTACT_PERS_PARTY_ID )
		,CREDIT_REVIEW_FLAG = DECODE( X_CREDIT_REVIEW_FLAG, NULL, CREDIT_REVIEW_FLAG, FND_API.G_MISS_CHAR, NULL, X_CREDIT_REVIEW_FLAG )
		,EXCHANGE_RATE_TYPE = DECODE( X_EXCHANGE_RATE_TYPE, NULL, EXCHANGE_RATE_TYPE, FND_API.G_MISS_CHAR, NULL, X_EXCHANGE_RATE_TYPE )
		,EXCHANGE_DATE = DECODE( L_RESET_EXCHANGE_DATA, 'Y', NULL, ( DECODE( X_EXCHANGE_DATE, NULL, EXCHANGE_DATE, FND_API.G_MISS_DATE, NULL, X_EXCHANGE_DATE ) ) )
		,EXCHANGE_RATE = DECODE( L_RESET_EXCHANGE_DATA, 'Y', NULL, ( DECODE( X_EXCHANGE_RATE, NULL, EXCHANGE_RATE, FND_API.G_MISS_NUM, NULL, X_EXCHANGE_RATE ) ) )
		,COLLATERAL_PERCENT = DECODE( X_COLLATERAL_PERCENT, NULL, COLLATERAL_PERCENT, FND_API.G_MISS_NUM, NULL, 0, NULL, X_COLLATERAL_PERCENT )
		,LAST_PAYMENT_NUMBER = DECODE( X_LAST_PAYMENT_NUMBER, NULL, LAST_PAYMENT_NUMBER, FND_API.G_MISS_NUM, NULL, X_LAST_PAYMENT_NUMBER )
		,LAST_AMORTIZATION_ID = DECODE( X_LAST_AMORTIZATION_ID, NULL, LAST_AMORTIZATION_ID, FND_API.G_MISS_NUM, NULL, X_LAST_AMORTIZATION_ID )
		,LEGAL_ENTITY_ID = DECODE( X_LEGAL_ENTITY_ID, NULL, LEGAL_ENTITY_ID, FND_API.G_MISS_NUM, NULL, X_LEGAL_ENTITY_ID )
		,OPEN_TO_TERM_FLAG = DECODE( X_OPEN_TO_TERM_FLAG, NULL, OPEN_TO_TERM_FLAG, FND_API.G_MISS_CHAR, NULL, X_OPEN_TO_TERM_FLAG )
		,MULTIPLE_FUNDING_FLAG = DECODE( X_MULTIPLE_FUNDING_FLAG, NULL, MULTIPLE_FUNDING_FLAG, FND_API.G_MISS_CHAR, NULL, X_MULTIPLE_FUNDING_FLAG )
		,LOAN_TYPE_ID = DECODE( X_LOAN_TYPE_ID, NULL, LOAN_TYPE_ID, FND_API.G_MISS_NUM, NULL, X_LOAN_TYPE_ID )
		,SECONDARY_STATUS = DECODE( X_SECONDARY_STATUS, NULL, SECONDARY_STATUS, FND_API.G_MISS_CHAR, NULL, X_SECONDARY_STATUS )
		,OPEN_TO_TERM_EVENT = DECODE( X_OPEN_TO_TERM_EVENT, NULL, OPEN_TO_TERM_EVENT, FND_API.G_MISS_CHAR, NULL, X_OPEN_TO_TERM_EVENT )
		,BALLOON_PAYMENT_TYPE = DECODE( X_BALLOON_PAYMENT_TYPE, NULL, BALLOON_PAYMENT_TYPE, FND_API.G_MISS_CHAR, NULL, X_BALLOON_PAYMENT_TYPE )
		,BALLOON_PAYMENT_AMOUNT = DECODE( X_BALLOON_PAYMENT_AMOUNT, NULL, BALLOON_PAYMENT_AMOUNT, FND_API.G_MISS_NUM, NULL, X_BALLOON_PAYMENT_AMOUNT )
		,CURRENT_PHASE = DECODE( X_CURRENT_PHASE, NULL, CURRENT_PHASE, FND_API.G_MISS_CHAR, NULL, X_CURRENT_PHASE )
		,OPEN_LOAN_START_DATE = DECODE( X_OPEN_LOAN_START_DATE, NULL, OPEN_LOAN_START_DATE, FND_API.G_MISS_DATE, NULL, X_OPEN_LOAN_START_DATE )
		,OPEN_LOAN_TERM = DECODE( X_OPEN_LOAN_TERM, NULL, OPEN_LOAN_TERM, FND_API.G_MISS_NUM, NULL, X_OPEN_LOAN_TERM )
		,OPEN_LOAN_TERM_PERIOD = DECODE( X_OPEN_LOAN_TERM_PERIOD, NULL, OPEN_LOAN_TERM_PERIOD, FND_API.G_MISS_CHAR, NULL, X_OPEN_LOAN_TERM_PERIOD )
		,OPEN_MATURITY_DATE = DECODE( X_OPEN_MATURITY_DATE, NULL, OPEN_MATURITY_DATE, FND_API.G_MISS_DATE, NULL, X_OPEN_MATURITY_DATE )
		,FUNDS_RESERVED_FLAG = DECODE( X_FUNDS_RESERVED_FLAG, NULL, FUNDS_RESERVED_FLAG, FND_API.G_MISS_CHAR, NULL, X_FUNDS_RESERVED_FLAG )
		,FUNDS_CHECK_DATE = DECODE( X_FUNDS_CHECK_DATE, NULL, FUNDS_CHECK_DATE, FND_API.G_MISS_DATE, NULL, X_FUNDS_CHECK_DATE )
		,SUBSIDY_RATE = DECODE( X_SUBSIDY_RATE, NULL, SUBSIDY_RATE, FND_API.G_MISS_NUM, NULL, X_SUBSIDY_RATE )
		,APPLICATION_ID = DECODE( X_APPLICATION_ID, NULL, APPLICATION_ID, FND_API.G_MISS_NUM, NULL, X_APPLICATION_ID )
		,CREATED_BY_MODULE = DECODE( X_CREATED_BY_MODULE, NULL, CREATED_BY_MODULE, FND_API.G_MISS_CHAR, NULL, X_CREATED_BY_MODULE )
		,PARTY_TYPE = DECODE( X_PARTY_TYPE, NULL, PARTY_TYPE, FND_API.G_MISS_CHAR, NULL, X_PARTY_TYPE )
		,FORGIVENESS_FLAG = DECODE( X_FORGIVENESS_FLAG, NULL, FORGIVENESS_FLAG, FND_API.G_MISS_CHAR, NULL, X_FORGIVENESS_FLAG )
		,FORGIVENESS_PERCENT = DECODE( X_FORGIVENESS_PERCENT, NULL, FORGIVENESS_PERCENT, FND_API.G_MISS_NUM, NULL, 0, NULL, X_FORGIVENESS_PERCENT )
		,DISABLE_BILLING_FLAG = DECODE( X_DISABLE_BILLING_FLAG, NULL, DISABLE_BILLING_FLAG, FND_API.G_MISS_CHAR, NULL, X_DISABLE_BILLING_FLAG )
		,ADD_REQUESTED_AMOUNT = DECODE( X_ADD_REQUESTED_AMOUNT, NULL, ADD_REQUESTED_AMOUNT, FND_API.G_MISS_NUM, NULL, 0, NULL, X_ADD_REQUESTED_AMOUNT )

	 WHERE ROWID = X_Rowid;

	IF (SQL%NOTFOUND) THEN
		RAISE NO_DATA_FOUND;
	END IF;

	UPDATE LNS_LOAN_HEADERS_ALL_TL SET
		 LOAN_DESCRIPTION = DECODE( X_LOAN_DESCRIPTION, NULL, LOAN_DESCRIPTION, FND_API.G_MISS_CHAR, NULL, X_LOAN_DESCRIPTION )
 		,REFERENCE_DESCRIPTION = DECODE( X_REFERENCE_DESCRIPTION, NULL, REFERENCE_DESCRIPTION, FND_API.G_MISS_CHAR, NULL, X_REFERENCE_DESCRIPTION )
                ,LAST_UPDATE_DATE = sysdate
                ,LAST_UPDATED_BY = fnd_global.user_id
                ,LAST_UPDATE_LOGIN = fnd_global.user_id
                ,SOURCE_LANG = userenv('LANG')
              WHERE LOAN_ID = X_LOAN_ID
              AND userenv('LANG') in (LANGUAGE, SOURCE_LANG);

 	if (sql%notfound) then
		raise no_data_found;
	end if;


	--Call to record history
	LNS_LOAN_HISTORY_PUB.log_record_post(
		p_id => X_LOAN_ID,
		p_primary_key_name => 'LOAN_ID',
		p_table_name => 'LNS_LOAN_HEADERS_ALL',
		p_loan_id => X_LOAN_ID
	);
END Update_Row;

PROCEDURE Lock_Row(
	 x_rowid	VARCHAR2
	,p_LOAN_ID		NUMBER
	,p_LAST_UPDATE_DATE		DATE
	,p_LAST_UPDATED_BY		NUMBER
	,p_LAST_UPDATE_LOGIN		NUMBER
	,p_CREATION_DATE		DATE
	,p_CREATED_BY		NUMBER
	,p_PROGRAM_ID		NUMBER
	,p_OBJECT_VERSION_NUMBER		NUMBER
	,p_REQUEST_ID		NUMBER
	,p_ORG_ID		NUMBER
	,p_LOAN_NUMBER		VARCHAR2
	,p_LOAN_DESCRIPTION	VARCHAR2
	,p_LOAN_APPLICATION_DATE		DATE
	,p_END_DATE		DATE
	,p_INITIAL_LOAN_BALANCE		NUMBER
	,p_LAST_PAYMENT_DATE		DATE
	,p_LAST_PAYMENT_AMOUNT		NUMBER
	,p_LOAN_TERM		NUMBER
	,p_LOAN_TERM_PERIOD		VARCHAR2
	,p_AMORTIZED_TERM               NUMBER
	,p_AMORTIZED_TERM_PERIOD        VARCHAR2
	,p_LOAN_STATUS			VARCHAR2
	,p_LOAN_ASSIGNED_TO             NUMBER
	,p_LOAN_CURRENCY		VARCHAR2
	,p_LOAN_CLASS_CODE		VARCHAR2
	,p_LOAN_TYPE		VARCHAR2
	,p_LOAN_SUBTYPE		VARCHAR2
	,p_LOAN_PURPOSE_CODE		VARCHAR2
	,p_CUST_ACCOUNT_ID		NUMBER
	,p_BILL_TO_ACCT_SITE_ID		NUMBER
	,p_LOAN_MATURITY_DATE		DATE
	,p_LOAN_START_DATE		DATE
	,p_LOAN_CLOSING_DATE		DATE
	,p_REFERENCE_ID                 NUMBER
	,p_REFERENCE_NUMBER		VARCHAR2
	,p_REFERENCE_DESCRIPTION		VARCHAR2
	,p_REFERENCE_AMOUNT                 NUMBER
	,p_PRODUCT_FLAG		VARCHAR2
	,p_PRIMARY_BORROWER_ID		NUMBER
	,p_PRODUCT_ID		NUMBER
	,p_REQUESTED_AMOUNT		NUMBER
	,p_FUNDED_AMOUNT		NUMBER
	,p_LOAN_APPROVAL_DATE		DATE
	,p_LOAN_APPROVED_BY		NUMBER
	,p_ATTRIBUTE_CATEGORY		VARCHAR2
	,p_ATTRIBUTE1		VARCHAR2
	,p_ATTRIBUTE2		VARCHAR2
	,p_ATTRIBUTE3		VARCHAR2
	,p_ATTRIBUTE4		VARCHAR2
	,p_ATTRIBUTE5		VARCHAR2
	,p_ATTRIBUTE6		VARCHAR2
	,p_ATTRIBUTE7		VARCHAR2
	,p_ATTRIBUTE8		VARCHAR2
	,p_ATTRIBUTE9		VARCHAR2
	,p_ATTRIBUTE10		VARCHAR2
	,p_ATTRIBUTE11		VARCHAR2
	,p_ATTRIBUTE12		VARCHAR2
	,p_ATTRIBUTE13		VARCHAR2
	,p_ATTRIBUTE14		VARCHAR2
	,p_ATTRIBUTE15		VARCHAR2
	,p_ATTRIBUTE16		VARCHAR2
	,p_ATTRIBUTE17		VARCHAR2
	,p_ATTRIBUTE18		VARCHAR2
	,p_ATTRIBUTE19		VARCHAR2
	,p_ATTRIBUTE20		VARCHAR2
	,p_LAST_BILLED_DATE      DATE
	,p_CUSTOM_PAYMENTS_FLAG  VARCHAR2
	,p_BILLED_FLAG           VARCHAR2
	,p_REFERENCE_NAME	 VARCHAR2
	,p_REFERENCE_TYPE	 VARCHAR2
	,p_REFERENCE_TYPE_ID	 NUMBER
	,p_USSGL_TRANSACTION_CODE	VARCHAR2
	,p_GL_DATE			DATE
	,p_REC_ADJUSTMENT_NUMBER	  VARCHAR2
	,p_CONTACT_REL_PARTY_ID            NUMBER
	,p_CONTACT_PERS_PARTY_ID           NUMBER
	,p_CREDIT_REVIEW_FLAG	  VARCHAR2
	,p_EXCHANGE_RATE_TYPE	VARCHAR2
	,p_EXCHANGE_DATE	DATE
	,p_EXCHANGE_RATE	NUMBER
	,p_COLLATERAL_PERCENT   NUMBER
	,p_LAST_PAYMENT_NUMBER	NUMBER
	,p_LAST_AMORTIZATION_ID	NUMBER
	,p_LEGAL_ENTITY_ID     	NUMBER
	,p_OPEN_TO_TERM_FLAG            VARCHAR2
	,p_MULTIPLE_FUNDING_FLAG        VARCHAR2
	,p_LOAN_TYPE_ID                 NUMBER
	,p_SECONDARY_STATUS             VARCHAR2
	,p_OPEN_TO_TERM_EVENT           VARCHAR2
	,p_BALLOON_PAYMENT_TYPE         VARCHAR2
	,p_BALLOON_PAYMENT_AMOUNT       NUMBER
	,p_CURRENT_PHASE                VARCHAR2
	,p_OPEN_LOAN_START_DATE         DATE
	,p_OPEN_LOAN_TERM               NUMBER
	,p_OPEN_LOAN_TERM_PERIOD        VARCHAR2
	,p_OPEN_MATURITY_DATE           DATE
	,p_FUNDS_RESERVED_FLAG          VARCHAR2
	,p_FUNDS_CHECK_DATE             DATE
	,p_SUBSIDY_RATE	                NUMBER
	,p_APPLICATION_ID                      NUMBER
	,p_CREATED_BY_MODULE                   VARCHAR2
	,p_PARTY_TYPE                          VARCHAR2
	,p_FORGIVENESS_FLAG		VARCHAR2
	,p_FORGIVENESS_PERCENT		NUMBER
	,p_DISABLE_BILLING_FLAG		VARCHAR2
	,p_ADD_REQUESTED_AMOUNT		NUMBER
) IS
	CURSOR C IS SELECT * FROM LNS_LOAN_HEADERS_ALL
		WHERE rowid = x_rowid
		FOR UPDATE of LOAN_ID NOWAIT;
	Recinfo C%ROWTYPE;

	CURSOR C_TL IS SELECT
			  LOAN_DESCRIPTION
			  ,REFERENCE_DESCRIPTION
			  ,decode(LANGUAGE, userenv('LANG'), 'Y', 'N') BASELANG
		    FROM LNS_LOAN_HEADERS_ALL_TL
		    WHERE rowid = x_rowid
		    FOR UPDATE of LOAN_ID NOWAIT;

BEGIN
	OPEN C;
	FETCH C INTO Recinfo;
	IF (C%NOTFOUND) THEN
		CLOSE C;
		FND_MESSAGE.Set_Name('FND', 'FORM_RECORD_DELETED');
		APP_EXCEPTION.Raise_Exception;
	END IF;
	CLOSE C;

	IF (
		(Recinfo.LOAN_ID = p_LOAN_ID)
		AND ( (Recinfo.OBJECT_VERSION_NUMBER = p_OBJECT_VERSION_NUMBER)
			OR ( (Recinfo.OBJECT_VERSION_NUMBER IS NULL)
				AND (p_OBJECT_VERSION_NUMBER IS NULL)))
	   ) THEN
		return;
	ELSE
		FND_MESSAGE.Set_Name('FND', 'FORM_RECORD_CHANGED');
		APP_EXCEPTION.Raise_Exception;
	END IF;

	FOR tlinfo in C_TL LOOP
          IF (tlinfo.BASELANG = 'Y') THEN
            if (
	        ((tlinfo.LOAN_DESCRIPTION = P_LOAN_DESCRIPTION)
                     OR ((tlinfo.LOAN_DESCRIPTION is null) AND (P_LOAN_DESCRIPTION is null)))
                AND ( (tlinfo.REFERENCE_DESCRIPTION = P_REFERENCE_DESCRIPTION)
                          OR ( (tlinfo.REFERENCE_DESCRIPTION IS NULL)
                                  AND (P_REFERENCE_DESCRIPTION IS NULL)))

             ) THEN
              null;
            ELSE
		FND_MESSAGE.Set_Name('FND', 'FORM_RECORD_CHANGED');
		APP_EXCEPTION.Raise_Exception;
            END IF;
          END IF;
        END LOOP;


END Lock_Row;

procedure ADD_LANGUAGE
is
begin
  delete from LNS_LOAN_HEADERS_ALL_TL T
  where not exists
    (select NULL
    from LNS_LOAN_HEADERS_ALL B
    where B.LOAN_ID = T.LOAN_ID
    );

  update LNS_LOAN_HEADERS_ALL_TL T set (
      LOAN_DESCRIPTION,
      REFERENCE_DESCRIPTION
    ) = (select
      B.LOAN_DESCRIPTION,
      B.REFERENCE_DESCRIPTION
    from LNS_LOAN_HEADERS_ALL_TL B
    where B.LOAN_ID = T.LOAN_ID
    and B.LANGUAGE = T.SOURCE_LANG)
  where (
      T.LOAN_ID,
      T.LANGUAGE
  ) in (select
      SUBT.LOAN_ID,
      SUBT.LANGUAGE
    from LNS_LOAN_HEADERS_ALL_TL SUBB, LNS_LOAN_HEADERS_ALL_TL SUBT
    where SUBB.LOAN_ID = SUBT.LOAN_ID
    and SUBB.LANGUAGE = SUBT.SOURCE_LANG
    and (SUBB.LOAN_DESCRIPTION <> SUBT.LOAN_DESCRIPTION
      or (SUBB.LOAN_DESCRIPTION is null and SUBT.LOAN_DESCRIPTION is not null)
      or (SUBB.LOAN_DESCRIPTION is not null and SUBT.LOAN_DESCRIPTION is null)
      or SUBB.REFERENCE_DESCRIPTION <> SUBT.REFERENCE_DESCRIPTION
      or (SUBB.REFERENCE_DESCRIPTION is null and SUBT.REFERENCE_DESCRIPTION is not null)
      or (SUBB.REFERENCE_DESCRIPTION is not null and SUBT.REFERENCE_DESCRIPTION is null)
  ));

  insert into LNS_LOAN_HEADERS_ALL_TL (
    LOAN_ID,
    LOAN_DESCRIPTION,
    REFERENCE_DESCRIPTION,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    LANGUAGE,
    SOURCE_LANG
  ) select
    B.LOAN_ID,
    B.LOAN_DESCRIPTION,
    B.REFERENCE_DESCRIPTION,
    B.LAST_UPDATE_DATE,
    B.LAST_UPDATED_BY,
    B.CREATION_DATE,
    B.CREATED_BY,
    B.LAST_UPDATE_LOGIN,
    L.LANGUAGE_CODE,
    B.SOURCE_LANG
  from LNS_LOAN_HEADERS_ALL_TL B, FND_LANGUAGES L
  where L.INSTALLED_FLAG in ('I', 'B')
  and B.LANGUAGE = userenv('LANG')
  and not exists
    (select NULL
    from LNS_LOAN_HEADERS_ALL_TL T
    where T.LOAN_ID = B.LOAN_ID
    and T.LANGUAGE = L.LANGUAGE_CODE);
end ADD_LANGUAGE;

PROCEDURE Select_Row (
	X_LOAN_ID                         IN OUT NOCOPY NUMBER,
	X_ORG_ID                          OUT NOCOPY    NUMBER,
	X_LOAN_NUMBER             	   OUT NOCOPY    VARCHAR2,
	X_LOAN_DESCRIPTION		   OUT NOCOPY	 VARCHAR2,
	X_LOAN_APPLICATION_DATE           OUT NOCOPY    DATE,
	X_END_DATE                        OUT NOCOPY    DATE,
	X_INITIAL_LOAN_BALANCE            OUT NOCOPY    NUMBER,
	X_LAST_PAYMENT_DATE               OUT NOCOPY    DATE,
	X_LAST_PAYMENT_AMOUNT             OUT NOCOPY    NUMBER,
	X_LOAN_TERM                       OUT NOCOPY    NUMBER,
	X_LOAN_TERM_PERIOD                OUT NOCOPY    VARCHAR2,
	X_AMORTIZED_TERM                  OUT NOCOPY    NUMBER,
	X_AMORTIZED_TERM_PERIOD           OUT NOCOPY    VARCHAR2,
	X_LOAN_STATUS			   OUT NOCOPY    VARCHAR2,
	X_LOAN_ASSIGNED_TO                OUT NOCOPY    NUMBER,
	X_LOAN_CURRENCY                   OUT NOCOPY    VARCHAR2,
	X_LOAN_CLASS_CODE                 OUT NOCOPY    VARCHAR2,
	X_LOAN_TYPE                       OUT NOCOPY    VARCHAR2,
	X_LOAN_SUBTYPE                    OUT NOCOPY    VARCHAR2,
	X_LOAN_PURPOSE_CODE               OUT NOCOPY    VARCHAR2,
	X_CUST_ACCOUNT_ID                 OUT NOCOPY    NUMBER,
	X_BILL_TO_ACCT_SITE_ID		  OUT NOCOPY     NUMBER,
	X_LOAN_MATURITY_DATE              OUT NOCOPY    DATE,
	X_LOAN_START_DATE               OUT NOCOPY    DATE,
	X_LOAN_CLOSING_DATE               OUT NOCOPY    DATE,
	X_REFERENCE_ID                    OUT NOCOPY    NUMBER,
	X_REFERENCE_NUMBER                OUT NOCOPY    VARCHAR2,
	X_REFERENCE_DESCRIPTION           OUT NOCOPY    VARCHAR2,
	X_REFERENCE_AMOUNT                OUT NOCOPY    NUMBER,
	X_PRODUCT_FLAG                    OUT NOCOPY    VARCHAR2,
	X_PRIMARY_BORROWER_ID             OUT NOCOPY    NUMBER,
	X_PRODUCT_ID                      OUT NOCOPY    NUMBER,
	X_REQUESTED_AMOUNT                OUT NOCOPY    NUMBER,
	X_FUNDED_AMOUNT                   OUT NOCOPY    NUMBER,
	X_LOAN_APPROVAL_DATE              OUT NOCOPY    DATE,
	X_LOAN_APPROVED_BY                OUT NOCOPY    NUMBER,
	X_ATTRIBUTE_CATEGORY              OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE1                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE2                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE3                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE4                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE5                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE6                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE7                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE8                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE9                      OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE10                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE11                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE12                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE13                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE14                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE15                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE16                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE17                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE18                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE19                     OUT NOCOPY    VARCHAR2,
	X_ATTRIBUTE20                     OUT NOCOPY    VARCHAR2,
	X_LAST_BILLED_DATE                OUT NOCOPY    DATE,
	X_CUSTOM_PAYMENTS_FLAG            OUT NOCOPY    VARCHAR2,
	X_BILLED_FLAG                     OUT NOCOPY    VARCHAR2,
	X_REFERENCE_NAME		   OUT NOCOPY    VARCHAR2,
	X_REFERENCE_TYPE		   OUT NOCOPY    VARCHAR2,
	X_REFERENCE_TYPE_ID		   OUT NOCOPY    NUMBER,
	X_USSGL_TRANSACTION_CODE	   OUT NOCOPY    VARCHAR2,
	X_GL_DATE			   OUT NOCOPY    DATE,
	X_REC_ADJUSTMENT_NUMBER	  OUT NOCOPY     VARCHAR2,
	X_CONTACT_REL_PARTY_ID            OUT NOCOPY     NUMBER,
	X_CONTACT_PERS_PARTY_ID           OUT NOCOPY     NUMBER,
	X_CREDIT_REVIEW_FLAG	           OUT NOCOPY     VARCHAR2,
	X_EXCHANGE_RATE_TYPE		   OUT NOCOPY     VARCHAR2,
	X_EXCHANGE_DATE	           OUT NOCOPY     DATE,
	X_EXCHANGE_RATE	           OUT NOCOPY     NUMBER,
	X_COLLATERAL_PERCENT		   OUT NOCOPY	  NUMBER,
	X_LAST_PAYMENT_NUMBER											  OUT NOCOPY 	  NUMBER,
	X_LAST_AMORTIZATION_ID											 OUT NOCOPY 	  NUMBER,
	X_LEGAL_ENTITY_ID     											 OUT NOCOPY 	  NUMBER,
	X_OPEN_TO_TERM_FLAG               OUT NOCOPY    VARCHAR2,
	X_MULTIPLE_FUNDING_FLAG           OUT NOCOPY    VARCHAR2,
	X_LOAN_TYPE_ID                    OUT NOCOPY    NUMBER,
	X_SECONDARY_STATUS                OUT NOCOPY    VARCHAR2,
	X_OPEN_TO_TERM_EVENT              OUT NOCOPY    VARCHAR2,
	X_BALLOON_PAYMENT_TYPE            OUT NOCOPY    VARCHAR2,
	X_BALLOON_PAYMENT_AMOUNT          OUT NOCOPY    NUMBER,
	X_CURRENT_PHASE                   OUT NOCOPY    VARCHAR2,
	X_OPEN_LOAN_START_DATE            OUT NOCOPY 			DATE,
	X_OPEN_LOAN_TERM                  OUT NOCOPY 			NUMBER,
	X_OPEN_LOAN_TERM_PERIOD           OUT NOCOPY 			VARCHAR2,
	X_OPEN_MATURITY_DATE														OUT NOCOPY  		DATE,
	X_FUNDS_RESERVED_FLAG             OUT NOCOPY  		VARCHAR2,
	X_FUNDS_CHECK_DATE                OUT NOCOPY  		DATE,
	X_SUBSIDY_RATE	                   OUT NOCOPY  		NUMBER,
	X_APPLICATION_ID                          OUT NOCOPY   NUMBER,
	X_CREATED_BY_MODULE               OUT NOCOPY   VARCHAR2,
	X_PARTY_TYPE                               OUT NOCOPY    VARCHAR2,
	X_FORGIVENESS_FLAG		        OUT NOCOPY    VARCHAR2,
	X_FORGIVENESS_PERCENT		OUT NOCOPY 	   NUMBER,
	X_DISABLE_BILLING_FLAG		OUT NOCOPY    VARCHAR2,
	X_ADD_REQUESTED_AMOUNT		OUT NOCOPY 	   NUMBER
) IS

BEGIN

    SELECT
	NVL( LOAN_ID, FND_API.G_MISS_NUM ),
	NVL( ORG_ID , FND_API.G_MISS_NUM ),
	NVL( LOAN_NUMBER, FND_API.G_MISS_CHAR ),
	NVL( LOAN_DESCRIPTION, FND_API.G_MISS_CHAR ),
	NVL( LOAN_APPLICATION_DATE , FND_API.G_MISS_DATE ),
	NVL( END_DATE , FND_API.G_MISS_DATE ),
	NVL( INITIAL_LOAN_BALANCE  , FND_API.G_MISS_NUM ),
	NVL( LAST_PAYMENT_DATE  , FND_API.G_MISS_DATE ),
	NVL( LAST_PAYMENT_AMOUNT, FND_API.G_MISS_NUM ),
	NVL( LOAN_TERM, FND_API.G_MISS_NUM ),
	NVL( LOAN_TERM_PERIOD, FND_API.G_MISS_CHAR ),
	NVL( AMORTIZED_TERM, FND_API.G_MISS_NUM ),
	NVL( AMORTIZED_TERM_PERIOD, FND_API.G_MISS_CHAR ),
	NVL( LOAN_STATUS, FND_API.G_MISS_CHAR ),
	NVL( LOAN_ASSIGNED_TO, FND_API.G_MISS_NUM ),
	NVL( LOAN_CURRENCY, FND_API.G_MISS_CHAR ),
	NVL( LOAN_CLASS_CODE , FND_API.G_MISS_CHAR ),
	NVL( LOAN_TYPE, FND_API.G_MISS_CHAR ),
	NVL( LOAN_SUBTYPE, FND_API.G_MISS_CHAR ),
	NVL( LOAN_PURPOSE_CODE  , FND_API.G_MISS_CHAR ),
	NVL( CUST_ACCOUNT_ID , FND_API.G_MISS_NUM ),
	NVL( BILL_TO_ACCT_SITE_ID , FND_API.G_MISS_NUM ),
	NVL( LOAN_MATURITY_DATE , FND_API.G_MISS_DATE ),
	NVL( LOAN_START_DATE  , FND_API.G_MISS_DATE ),
	NVL( LOAN_CLOSING_DATE  , FND_API.G_MISS_DATE ),
	NVL( REFERENCE_ID, FND_API.G_MISS_NUM ),
	NVL( REFERENCE_NUMBER, FND_API.G_MISS_CHAR ),
	NVL( REFERENCE_DESCRIPTION , FND_API.G_MISS_CHAR ),
	NVL( REFERENCE_AMOUNT, FND_API.G_MISS_NUM ),
	NVL( PRODUCT_FLAG, FND_API.G_MISS_CHAR ),
	NVL( PRIMARY_BORROWER_ID, FND_API.G_MISS_NUM ),
	NVL( PRODUCT_ID  , FND_API.G_MISS_NUM ),
	NVL( REQUESTED_AMOUNT, FND_API.G_MISS_NUM ),
	NVL( FUNDED_AMOUNT, FND_API.G_MISS_NUM ),
	NVL( LOAN_APPROVAL_DATE , FND_API.G_MISS_DATE ),
	NVL( LOAN_APPROVED_BY, FND_API.G_MISS_NUM ),
	NVL( ATTRIBUTE_CATEGORY , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE1  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE2  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE3  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE4  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE5  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE6  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE7  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE8  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE9  , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE10 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE11 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE12 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE13 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE14 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE15 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE16 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE17 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE18 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE19 , FND_API.G_MISS_CHAR ),
	NVL( ATTRIBUTE20 , FND_API.G_MISS_CHAR ),
	NVL( LAST_BILLED_DATE , FND_API.G_MISS_DATE ),
	NVL( CUSTOM_PAYMENTS_FLAG , FND_API.G_MISS_CHAR ),
	NVL( BILLED_FLAG , FND_API.G_MISS_CHAR ),
	NVL( REFERENCE_NAME , FND_API.G_MISS_CHAR ),
	NVL( REFERENCE_TYPE , FND_API.G_MISS_CHAR ),
	NVL( REFERENCE_TYPE_ID , FND_API.G_MISS_NUM ),
	NVL( USSGL_TRANSACTION_CODE , FND_API.G_MISS_CHAR ),
	NVL( GL_DATE , FND_API.G_MISS_DATE ),
	NVL( REC_ADJUSTMENT_NUMBER , FND_API.G_MISS_CHAR ),
	NVL( CONTACT_REL_PARTY_ID , FND_API.G_MISS_NUM ),
	NVL( CONTACT_PERS_PARTY_ID , FND_API.G_MISS_NUM ),
	NVL( CREDIT_REVIEW_FLAG , FND_API.G_MISS_CHAR ),
	NVL( EXCHANGE_RATE_TYPE , FND_API.G_MISS_CHAR ),
	NVL( EXCHANGE_DATE , FND_API.G_MISS_DATE ),
	NVL( EXCHANGE_RATE , FND_API.G_MISS_NUM ),
	NVL( COLLATERAL_PERCENT , FND_API.G_MISS_NUM ),
	NVL( LAST_PAYMENT_NUMBER , FND_API.G_MISS_NUM ),
	NVL( LAST_AMORTIZATION_ID , FND_API.G_MISS_NUM ),
	NVL( LEGAL_ENTITY_ID , FND_API.G_MISS_NUM ),
	NVL( OPEN_TO_TERM_FLAG  , FND_API.G_MISS_CHAR ),
	NVL( MULTIPLE_FUNDING_FLAG , FND_API.G_MISS_CHAR ),
	NVL( LOAN_TYPE_ID , FND_API.G_MISS_NUM ),
	NVL( SECONDARY_STATUS , FND_API.G_MISS_CHAR ),
	NVL( OPEN_TO_TERM_EVENT, FND_API.G_MISS_CHAR ),
	NVL( BALLOON_PAYMENT_TYPE, FND_API.G_MISS_CHAR ),
	NVL( BALLOON_PAYMENT_AMOUNT, FND_API.G_MISS_NUM ),
	NVL( CURRENT_PHASE, FND_API.G_MISS_CHAR ),
	NVL( OPEN_LOAN_START_DATE, FND_API.G_MISS_DATE ),
	NVL( OPEN_LOAN_TERM, FND_API.G_MISS_NUM ),
	NVL( OPEN_LOAN_TERM_PERIOD, FND_API.G_MISS_CHAR ),
	NVL( OPEN_MATURITY_DATE, FND_API.G_MISS_DATE ),
	NVL( FUNDS_RESERVED_FLAG, FND_API.G_MISS_CHAR ),
	NVL( FUNDS_CHECK_DATE, FND_API.G_MISS_DATE ),
	NVL( SUBSIDY_RATE, FND_API.G_MISS_NUM ),
	NVL( APPLICATION_ID, FND_API.G_MISS_NUM ),
	NVL( CREATED_BY_MODULE, FND_API.G_MISS_CHAR ),
	NVL( PARTY_TYPE, FND_API.G_MISS_CHAR ),
	NVL( FORGIVENESS_FLAG , FND_API.G_MISS_CHAR ),
	NVL( FORGIVENESS_PERCENT , FND_API.G_MISS_NUM ),
	NVL( DISABLE_BILLING_FLAG , FND_API.G_MISS_CHAR ),
	NVL( ADD_REQUESTED_AMOUNT , FND_API.G_MISS_NUM )
    INTO
	X_LOAN_ID,
	X_ORG_ID,
	X_LOAN_NUMBER,
	X_LOAN_DESCRIPTION,
	X_LOAN_APPLICATION_DATE,
	X_END_DATE,
	X_INITIAL_LOAN_BALANCE,
	X_LAST_PAYMENT_DATE,
	X_LAST_PAYMENT_AMOUNT,
	X_LOAN_TERM,
	X_LOAN_TERM_PERIOD,
	X_AMORTIZED_TERM,
	X_AMORTIZED_TERM_PERIOD,
	X_LOAN_STATUS,
	X_LOAN_ASSIGNED_TO,
	X_LOAN_CURRENCY,
	X_LOAN_CLASS_CODE,
	X_LOAN_TYPE,
	X_LOAN_SUBTYPE,
	X_LOAN_PURPOSE_CODE,
	X_CUST_ACCOUNT_ID,
	X_BILL_TO_ACCT_SITE_ID,
	X_LOAN_MATURITY_DATE,
	X_LOAN_START_DATE,
	X_LOAN_CLOSING_DATE,
	X_REFERENCE_ID,
	X_REFERENCE_NUMBER,
	X_REFERENCE_DESCRIPTION,
	X_REFERENCE_AMOUNT,
	X_PRODUCT_FLAG,
	X_PRIMARY_BORROWER_ID,
	X_PRODUCT_ID,
	X_REQUESTED_AMOUNT,
	X_FUNDED_AMOUNT,
	X_LOAN_APPROVAL_DATE,
	X_LOAN_APPROVED_BY,
	X_ATTRIBUTE_CATEGORY,
	X_ATTRIBUTE1,
	X_ATTRIBUTE2,
	X_ATTRIBUTE3,
	X_ATTRIBUTE4,
	X_ATTRIBUTE5,
	X_ATTRIBUTE6,
	X_ATTRIBUTE7,
	X_ATTRIBUTE8,
	X_ATTRIBUTE9,
	X_ATTRIBUTE10,
	X_ATTRIBUTE11,
	X_ATTRIBUTE12,
	X_ATTRIBUTE13,
	X_ATTRIBUTE14,
	X_ATTRIBUTE15,
	X_ATTRIBUTE16,
	X_ATTRIBUTE17,
	X_ATTRIBUTE18,
	X_ATTRIBUTE19,
	X_ATTRIBUTE20,
	X_LAST_BILLED_DATE,
	X_CUSTOM_PAYMENTS_FLAG,
	X_BILLED_FLAG,
	X_REFERENCE_NAME,
	X_REFERENCE_TYPE,
	X_REFERENCE_TYPE_ID,
	X_USSGL_TRANSACTION_CODE,
	X_GL_DATE,
    	X_REC_ADJUSTMENT_NUMBER,
        X_CONTACT_REL_PARTY_ID,
	X_CONTACT_PERS_PARTY_ID,
	X_CREDIT_REVIEW_FLAG,
	X_EXCHANGE_RATE_TYPE,
	X_EXCHANGE_DATE,
	X_EXCHANGE_RATE,
	X_COLLATERAL_PERCENT,
	X_LAST_PAYMENT_NUMBER,
	X_LAST_AMORTIZATION_ID,
	X_LEGAL_ENTITY_ID,
	X_OPEN_TO_TERM_FLAG,
	X_MULTIPLE_FUNDING_FLAG,
	X_LOAN_TYPE_ID,
	X_SECONDARY_STATUS,
	X_OPEN_TO_TERM_EVENT,
	X_BALLOON_PAYMENT_TYPE,
	X_BALLOON_PAYMENT_AMOUNT,
	X_CURRENT_PHASE,
	X_OPEN_LOAN_START_DATE,
	X_OPEN_LOAN_TERM,
	X_OPEN_LOAN_TERM_PERIOD,
	X_OPEN_MATURITY_DATE,
	X_FUNDS_RESERVED_FLAG,
	X_FUNDS_CHECK_DATE,
	X_SUBSIDY_RATE,
	X_APPLICATION_ID,
	X_CREATED_BY_MODULE,
	X_PARTY_TYPE,
	X_FORGIVENESS_FLAG,
	X_FORGIVENESS_PERCENT,
	X_DISABLE_BILLING_FLAG,
	X_ADD_REQUESTED_AMOUNT
    FROM LNS_LOAN_HEADERS_ALL_VL
    WHERE LOAN_ID = X_LOAN_ID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        FND_MESSAGE.SET_NAME( 'LNS', 'LNS_API_NO_RECORD' );
        FND_MESSAGE.SET_TOKEN( 'RECORD', 'loan_header_rec');
        FND_MESSAGE.SET_TOKEN( 'VALUE', TO_CHAR( X_LOAN_ID ) );
        FND_MSG_PUB.ADD;
        RAISE FND_API.G_EXC_ERROR;

END Select_Row;

PROCEDURE Delete_Row (
    X_LOAN_ID                         IN     NUMBER
) IS

BEGIN

    DELETE FROM LNS_LOAN_HEADERS_ALL_TL
    WHERE LOAN_ID = X_LOAN_ID;

    IF ( SQL%NOTFOUND ) THEN
        RAISE NO_DATA_FOUND;
    END IF;


    DELETE FROM LNS_LOAN_HEADERS_ALL
    WHERE LOAN_ID = X_LOAN_ID;

    IF ( SQL%NOTFOUND ) THEN
        RAISE NO_DATA_FOUND;
    END IF;


END Delete_Row;



END LNS_LOAN_HEADER_ALL_PKG;

/
