--------------------------------------------------------
--  DDL for Package Body OTA_TCC_BK1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."OTA_TCC_BK1" as
/* $Header: ottccapi.pkb 115.2 2002/11/29 13:15:39 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:19:24 (YYYY/MM/DD HH24:MI:SS)
procedure CREATE_CROSS_CHARGE_A
(P_EFFECTIVE_DATE in DATE
,P_CROSS_CHARGE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_GL_SET_OF_BOOKS_ID in NUMBER
,P_TYPE in VARCHAR2
,P_FROM_TO in VARCHAR2
,P_START_DATE_ACTIVE in DATE
,P_END_DATE_ACTIVE in DATE
)is
begin
hr_utility.set_location('Entering: OTA_TCC_BK1.CREATE_CROSS_CHARGE_A', 10);
hr_utility.set_location(' Leaving: OTA_TCC_BK1.CREATE_CROSS_CHARGE_A', 20);
end CREATE_CROSS_CHARGE_A;
procedure CREATE_CROSS_CHARGE_B
(P_EFFECTIVE_DATE in DATE
,P_CROSS_CHARGE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_GL_SET_OF_BOOKS_ID in NUMBER
,P_TYPE in VARCHAR2
,P_FROM_TO in VARCHAR2
,P_START_DATE_ACTIVE in DATE
,P_END_DATE_ACTIVE in DATE
)is
begin
hr_utility.set_location('Entering: OTA_TCC_BK1.CREATE_CROSS_CHARGE_B', 10);
hr_utility.set_location(' Leaving: OTA_TCC_BK1.CREATE_CROSS_CHARGE_B', 20);
end CREATE_CROSS_CHARGE_B;
end OTA_TCC_BK1;

/
