--------------------------------------------------------
--  DDL for Package Body OTA_TPS_API_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."OTA_TPS_API_BK3" as
/* $Header: ottpsapi.pkb 120.0 2005/10/02 02:08:40 generated $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:19:28 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_TRAINING_PLAN_A
(P_TRAINING_PLAN_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_TPS_API_BK3.DELETE_TRAINING_PLAN_A', 10);
hr_utility.set_location(' Leaving: OTA_TPS_API_BK3.DELETE_TRAINING_PLAN_A', 20);
end DELETE_TRAINING_PLAN_A;
procedure DELETE_TRAINING_PLAN_B
(P_TRAINING_PLAN_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_TPS_API_BK3.DELETE_TRAINING_PLAN_B', 10);
hr_utility.set_location(' Leaving: OTA_TPS_API_BK3.DELETE_TRAINING_PLAN_B', 20);
end DELETE_TRAINING_PLAN_B;
end OTA_TPS_API_BK3;

/
