--------------------------------------------------------
--  DDL for Package Body OTA_CHAT_MESSAGE_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."OTA_CHAT_MESSAGE_BK3" as
/*$Header: otcmsapi.pkb 120.2 2005/08/05 14:19 generated noship $*/
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:19:07 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_CHAT_MESSAGE_A
(P_CHAT_MESSAGE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_CHAT_MESSAGE_BK3.DELETE_CHAT_MESSAGE_A', 10);
hr_utility.set_location(' Leaving: OTA_CHAT_MESSAGE_BK3.DELETE_CHAT_MESSAGE_A', 20);
end DELETE_CHAT_MESSAGE_A;
procedure DELETE_CHAT_MESSAGE_B
(P_CHAT_MESSAGE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_CHAT_MESSAGE_BK3.DELETE_CHAT_MESSAGE_B', 10);
hr_utility.set_location(' Leaving: OTA_CHAT_MESSAGE_BK3.DELETE_CHAT_MESSAGE_B', 20);
end DELETE_CHAT_MESSAGE_B;
end OTA_CHAT_MESSAGE_BK3;

/
