--------------------------------------------------------
--  DDL for Package Body OTA_FINANCE_HEADER_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."OTA_FINANCE_HEADER_BK3" as
    /* $Header: ottfhapi.pkb 120.0 2005/05/29 07:40:55 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:19:26 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_FINANCE_HEADER_A
(P_FINANCE_HEADER_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_FINANCE_HEADER_BK3.DELETE_FINANCE_HEADER_A', 10);
hr_utility.set_location(' Leaving: OTA_FINANCE_HEADER_BK3.DELETE_FINANCE_HEADER_A', 20);
end DELETE_FINANCE_HEADER_A;
procedure DELETE_FINANCE_HEADER_B
(P_FINANCE_HEADER_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_FINANCE_HEADER_BK3.DELETE_FINANCE_HEADER_B', 10);
hr_utility.set_location(' Leaving: OTA_FINANCE_HEADER_BK3.DELETE_FINANCE_HEADER_B', 20);
end DELETE_FINANCE_HEADER_B;
end OTA_FINANCE_HEADER_BK3;

/
