--------------------------------------------------------
--  DDL for Package Body OTA_CERT_PRD_ENROLLMENT_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."OTA_CERT_PRD_ENROLLMENT_BK3" as
/* $Header: otcpeapi.pkb 120.13.12010000.3 2008/09/22 10:52:35 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 21:59:26 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_CERT_PRD_ENROLLMENT_A
(P_CERT_PRD_ENROLLMENT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_CERT_PRD_ENROLLMENT_BK3.DELETE_CERT_PRD_ENROLLMENT_A', 10);
hr_utility.set_location(' Leaving: OTA_CERT_PRD_ENROLLMENT_BK3.DELETE_CERT_PRD_ENROLLMENT_A', 20);
end DELETE_CERT_PRD_ENROLLMENT_A;
procedure DELETE_CERT_PRD_ENROLLMENT_B
(P_CERT_PRD_ENROLLMENT_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: OTA_CERT_PRD_ENROLLMENT_BK3.DELETE_CERT_PRD_ENROLLMENT_B', 10);
hr_utility.set_location(' Leaving: OTA_CERT_PRD_ENROLLMENT_BK3.DELETE_CERT_PRD_ENROLLMENT_B', 20);
end DELETE_CERT_PRD_ENROLLMENT_B;
end OTA_CERT_PRD_ENROLLMENT_BK3;

/
