--------------------------------------------------------
--  DDL for Package Body OTA_LPT_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."OTA_LPT_RKI" as
/* $Header: otlptrhi.pkb 120.0 2005/05/29 07:24:49 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:19:20 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EFFECTIVE_DATE in DATE
,P_LEARNING_PATH_ID in NUMBER
,P_LANGUAGE in VARCHAR2
,P_NAME in VARCHAR2
,P_DESCRIPTION in VARCHAR2
,P_OBJECTIVES in VARCHAR2
,P_PURPOSE in VARCHAR2
,P_KEYWORDS in VARCHAR2
,P_SOURCE_LANG in VARCHAR2
)is
begin
hr_utility.set_location('Entering: OTA_LPT_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: OTA_LPT_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end OTA_LPT_RKI;

/
