--------------------------------------------------------
--  DDL for Package Body PA_PERF_KPA_SUMMARY_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PA_PERF_KPA_SUMMARY_PKG" as
/* $Header: PAPEESTB.pls 120.1 2005/08/19 16:38:39 mwasowic noship $ */

procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2, --File.Sql.39 bug 4440895
  X_KPA_SUMMARY_ID in NUMBER,
  X_OBJECT_TYPE in VARCHAR2,
  X_OBJECT_ID in NUMBER,
  X_DATE_CHECKED in DATE,
  X_CURRENT_FLAG in VARCHAR2,
  X_PERF_STATUS_CODE in VARCHAR2,
  X_KPA1_CODE in VARCHAR2,
  X_KPA1_INDICATOR in VARCHAR2,
  X_KPA1_SCORE in NUMBER,
  X_KPA1_THRES_FROM in VARCHAR2,
  X_KPA1_THRES_TO in VARCHAR2,
  X_KPA2_CODE in VARCHAR2,
  X_KPA2_INDICATOR in VARCHAR2,
  X_KPA2_SCORE in NUMBER,
  X_KPA2_THRES_FROM in VARCHAR2,
  X_KPA2_THRES_TO in VARCHAR2,
  X_KPA3_CODE in VARCHAR2,
  X_KPA3_INDICATOR in VARCHAR2,
  X_KPA3_SCORE in NUMBER,
  X_KPA3_THRES_FROM in VARCHAR2,
  X_KPA3_THRES_TO in VARCHAR2,
  X_KPA4_CODE in VARCHAR2,
  X_KPA4_INDICATOR in VARCHAR2,
  X_KPA4_SCORE in NUMBER,
  X_KPA4_THRES_FROM in VARCHAR2,
  X_KPA4_THRES_TO in VARCHAR2,
  X_KPA5_CODE in VARCHAR2,
  X_KPA5_INDICATOR in VARCHAR2,
  X_KPA5_SCORE in NUMBER,
  X_KPA5_THRES_FROM in VARCHAR2,
  X_KPA5_THRES_TO in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
) is
  cursor C is select ROWID from PA_PERF_KPA_SUMMARY
    where KPA_SUMMARY_ID = X_KPA_SUMMARY_ID
    ;
begin
  insert into PA_PERF_KPA_SUMMARY (
    KPA_SUMMARY_ID,
    OBJECT_TYPE,
    OBJECT_ID,
    DATE_CHECKED,
    CURRENT_FLAG,
    PERF_STATUS_CODE,
    KPA1_CODE,
    KPA1_INDICATOR,
    KPA1_SCORE,
    KPA1_THRES_FROM,
    KPA1_THRES_TO,
    KPA2_CODE,
    KPA2_INDICATOR,
    KPA2_SCORE,
    KPA2_THRES_FROM,
    KPA2_THRES_TO,
    KPA3_CODE,
    KPA3_INDICATOR,
    KPA3_SCORE,
    KPA3_THRES_FROM,
    KPA3_THRES_TO,
    KPA4_CODE,
    KPA4_INDICATOR,
    KPA4_SCORE,
    KPA4_THRES_FROM,
    KPA4_THRES_TO,
    KPA5_CODE,
    KPA5_INDICATOR,
    KPA5_SCORE,
    KPA5_THRES_FROM,
    KPA5_THRES_TO,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN )
  values (
    X_KPA_SUMMARY_ID,
    X_OBJECT_TYPE,
    X_OBJECT_ID,
    X_DATE_CHECKED,
    X_CURRENT_FLAG,
    X_PERF_STATUS_CODE,
    X_KPA1_CODE,
    X_KPA1_INDICATOR,
    X_KPA1_SCORE,
    X_KPA1_THRES_FROM,
    X_KPA1_THRES_TO,
    X_KPA2_CODE,
    X_KPA2_INDICATOR,
    X_KPA2_SCORE,
    X_KPA2_THRES_FROM,
    X_KPA2_THRES_TO,
    X_KPA3_CODE,
    X_KPA3_INDICATOR,
    X_KPA3_SCORE,
    X_KPA3_THRES_FROM,
    X_KPA3_THRES_TO,
    X_KPA4_CODE,
    X_KPA4_INDICATOR,
    X_KPA4_SCORE,
    X_KPA4_THRES_FROM,
    X_KPA4_THRES_TO,
    X_KPA5_CODE,
    X_KPA5_INDICATOR,
    X_KPA5_SCORE,
    X_KPA5_THRES_FROM,
    X_KPA5_THRES_TO,
    NVL(X_CREATION_DATE,sysdate),
    NVL(X_CREATED_BY,fnd_global.user_id),
    NVL(X_LAST_UPDATE_DATE,sysdate),
    NVL(X_LAST_UPDATED_BY,fnd_global.user_id),
    NVL(X_LAST_UPDATE_LOGIN,fnd_global.login_id));

  open c;
  fetch c into X_ROWID;
  if (c%notfound) then
    close c;
    raise no_data_found;
  end if;
  close c;

end INSERT_ROW;



procedure UPDATE_ROW (
  X_KPA_SUMMARY_ID in NUMBER,
  X_OBJECT_TYPE in VARCHAR2,
  X_OBJECT_ID in NUMBER,
  X_DATE_CHECKED in DATE,
  X_CURRENT_FLAG in VARCHAR2,
  X_PERF_STATUS_CODE in VARCHAR2,
  X_KPA1_CODE in VARCHAR2,
  X_KPA1_INDICATOR in VARCHAR2,
  X_KPA1_SCORE in NUMBER,
  X_KPA1_THRES_FROM in VARCHAR2,
  X_KPA1_THRES_TO in VARCHAR2,
  X_KPA2_CODE in VARCHAR2,
  X_KPA2_INDICATOR in VARCHAR2,
  X_KPA2_SCORE in NUMBER,
  X_KPA2_THRES_FROM in VARCHAR2,
  X_KPA2_THRES_TO in VARCHAR2,
  X_KPA3_CODE in VARCHAR2,
  X_KPA3_INDICATOR in VARCHAR2,
  X_KPA3_SCORE in NUMBER,
  X_KPA3_THRES_FROM in VARCHAR2,
  X_KPA3_THRES_TO in VARCHAR2,
  X_KPA4_CODE in VARCHAR2,
  X_KPA4_INDICATOR in VARCHAR2,
  X_KPA4_SCORE in NUMBER,
  X_KPA4_THRES_FROM in VARCHAR2,
  X_KPA4_THRES_TO in VARCHAR2,
  X_KPA5_CODE in VARCHAR2,
  X_KPA5_INDICATOR in VARCHAR2,
  X_KPA5_SCORE in NUMBER,
  X_KPA5_THRES_FROM in VARCHAR2,
  X_KPA5_THRES_TO in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE ,
  X_LAST_UPDATED_BY in NUMBER ,
  X_LAST_UPDATE_LOGIN in NUMBER
) is
begin
  update PA_PERF_KPA_SUMMARY set
    OBJECT_TYPE = X_OBJECT_TYPE,
    OBJECT_ID = X_OBJECT_ID,
    DATE_CHECKED = X_DATE_CHECKED,
    CURRENT_FLAG = X_CURRENT_FLAG,
    PERF_STATUS_CODE = X_PERF_STATUS_CODE,
    KPA1_CODE = X_KPA1_CODE,
    KPA1_INDICATOR = X_KPA1_INDICATOR,
    KPA1_SCORE = X_KPA1_SCORE,
    KPA1_THRES_FROM = X_KPA1_THRES_FROM,
    KPA1_THRES_TO = X_KPA1_THRES_FROM,
    KPA2_CODE = X_KPA2_CODE,
    KPA2_INDICATOR = X_KPA2_INDICATOR,
    KPA2_SCORE = X_KPA2_SCORE,
    KPA2_THRES_FROM = X_KPA2_THRES_FROM,
    KPA2_THRES_TO = X_KPA2_THRES_FROM,
    KPA3_CODE = X_KPA3_CODE,
    KPA3_INDICATOR = X_KPA3_INDICATOR,
    KPA3_SCORE = X_KPA3_SCORE,
    KPA3_THRES_FROM = X_KPA3_THRES_FROM,
    KPA3_THRES_TO = X_KPA3_THRES_FROM,
    KPA4_CODE = X_KPA4_CODE,
    KPA4_INDICATOR = X_KPA4_INDICATOR,
    KPA4_SCORE = X_KPA4_SCORE,
    KPA4_THRES_FROM = X_KPA4_THRES_FROM,
    KPA4_THRES_TO = X_KPA4_THRES_FROM,
    KPA5_CODE = X_KPA5_CODE,
    KPA5_INDICATOR = X_KPA5_INDICATOR,
    KPA5_SCORE = X_KPA5_SCORE,
    KPA5_THRES_FROM = X_KPA5_THRES_FROM,
    KPA5_THRES_TO = X_KPA5_THRES_FROM,
    KPA_SUMMARY_ID = X_KPA_SUMMARY_ID,
    LAST_UPDATE_DATE = NVL(X_LAST_UPDATE_DATE,sysdate),
    LAST_UPDATED_BY = NVL(X_LAST_UPDATED_BY,fnd_global.user_id),
    LAST_UPDATE_LOGIN = NVL(X_LAST_UPDATE_LOGIN,fnd_global.login_id)
  where KPA_SUMMARY_ID = X_KPA_SUMMARY_ID
  ;

  if (sql%notfound) then
    raise no_data_found;
  end if;
end UPDATE_ROW;

procedure DELETE_ROW (
  X_KPA_SUMMARY_ID in NUMBER
) is
begin
  delete from PA_PERF_KPA_SUMMARY
  where KPA_SUMMARY_ID = X_KPA_SUMMARY_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;

end DELETE_ROW;


end PA_PERF_KPA_SUMMARY_PKG;

/
