--------------------------------------------------------
--  DDL for Package Body PAY_INPUT_VALUE_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PAY_INPUT_VALUE_BK3" as
/* $Header: pyivlapi.pkb 115.3 2003/10/08 05:30:08 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:28:01 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_INPUT_VALUE_A
(P_VALIDATE in BOOLEAN
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_DELETE_MODE in VARCHAR2
,P_INPUT_VALUE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_START_DATE in DATE
,P_EFFECTIVE_END_DATE in DATE
,P_BALANCE_FEEDS_WARNING in BOOLEAN
)is
begin
hr_utility.set_location('Entering: PAY_INPUT_VALUE_BK3.DELETE_INPUT_VALUE_A', 10);
hr_utility.set_location(' Leaving: PAY_INPUT_VALUE_BK3.DELETE_INPUT_VALUE_A', 20);
end DELETE_INPUT_VALUE_A;
procedure DELETE_INPUT_VALUE_B
(P_VALIDATE in BOOLEAN
,P_EFFECTIVE_DATE in DATE
,P_DATETRACK_DELETE_MODE in VARCHAR2
,P_INPUT_VALUE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PAY_INPUT_VALUE_BK3.DELETE_INPUT_VALUE_B', 10);
hr_utility.set_location(' Leaving: PAY_INPUT_VALUE_BK3.DELETE_INPUT_VALUE_B', 20);
end DELETE_INPUT_VALUE_B;
end PAY_INPUT_VALUE_BK3;

/
