--------------------------------------------------------
--  DDL for Package Body PAY_EVG_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PAY_EVG_RKI" as
/* $Header: pyevgrhi.pkb 120.4 2005/11/07 09:03:07 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:27:56 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EFFECTIVE_DATE in DATE
,P_EVENT_GROUP_ID in NUMBER
,P_EVENT_GROUP_NAME in VARCHAR2
,P_EVENT_GROUP_TYPE in VARCHAR2
,P_PRORATION_TYPE in VARCHAR2
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_TIME_DEFINITION_ID in NUMBER
)is
begin
hr_utility.set_location('Entering: PAY_EVG_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: PAY_EVG_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end PAY_EVG_RKI;

/
