--------------------------------------------------------
--  DDL for Package Body PAY_OPT_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PAY_OPT_RKU" as
/* $Header: pyoptrhi.pkb 115.3 2002/12/05 17:29:47 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:28:03 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_ORG_PAYMENT_METHOD_ID in NUMBER
,P_ORG_PAYMENT_METHOD_NAME in VARCHAR2
,P_LANGUAGE in VARCHAR2
,P_SOURCE_LANG in VARCHAR2
,P_ORG_PAYMENT_METHOD_NAME_O in VARCHAR2
,P_SOURCE_LANG_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PAY_OPT_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: PAY_OPT_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end PAY_OPT_RKU;

/
