--------------------------------------------------------
--  DDL for Package Body PAY_USER_TABLE_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PAY_USER_TABLE_BK3" as
/* $Header: pyputapi.pkb 120.0 2005/05/29 08:02:50 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:28:20 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_USER_TABLE_A
(P_USER_TABLE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PAY_USER_TABLE_BK3.DELETE_USER_TABLE_A', 10);
hr_utility.set_location(' Leaving: PAY_USER_TABLE_BK3.DELETE_USER_TABLE_A', 20);
end DELETE_USER_TABLE_A;
procedure DELETE_USER_TABLE_B
(P_USER_TABLE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PAY_USER_TABLE_BK3.DELETE_USER_TABLE_B', 10);
hr_utility.set_location(' Leaving: PAY_USER_TABLE_BK3.DELETE_USER_TABLE_B', 20);
end DELETE_USER_TABLE_B;
end PAY_USER_TABLE_BK3;

/
