--------------------------------------------------------
--  DDL for Package Body PAY_BTT_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PAY_BTT_RKD" as
/* $Header: pybttrhi.pkb 120.0 2005/05/29 03:24 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:27:46 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_BALANCE_TYPE_ID in NUMBER
,P_LANGUAGE in VARCHAR2
,P_BALANCE_NAME_O in VARCHAR2
,P_REPORTING_NAME_O in VARCHAR2
,P_SOURCE_LANG_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PAY_BTT_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: PAY_BTT_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end PAY_BTT_RKD;

/
