--------------------------------------------------------
--  DDL for Package Body PAY_ACTION_INFORMATION_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PAY_ACTION_INFORMATION_BK3" as
/* $Header: pyaifapi.pkb 115.8 2003/01/14 17:25:25 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:27:45 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_ACTION_INFORMATION_A
(P_ACTION_INFORMATION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PAY_ACTION_INFORMATION_BK3.DELETE_ACTION_INFORMATION_A', 10);
hr_utility.set_location(' Leaving: PAY_ACTION_INFORMATION_BK3.DELETE_ACTION_INFORMATION_A', 20);
end DELETE_ACTION_INFORMATION_A;
procedure DELETE_ACTION_INFORMATION_B
(P_ACTION_INFORMATION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PAY_ACTION_INFORMATION_BK3.DELETE_ACTION_INFORMATION_B', 10);
hr_utility.set_location(' Leaving: PAY_ACTION_INFORMATION_BK3.DELETE_ACTION_INFORMATION_B', 20);
end DELETE_ACTION_INFORMATION_B;
end PAY_ACTION_INFORMATION_BK3;

/
