--------------------------------------------------------
--  DDL for Package Body PER_JGR_RKU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_JGR_RKU" as
/* $Header: pejgrrhi.pkb 115.9 2004/09/09 08:11:45 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:32:20 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_UPDATE
(P_EFFECTIVE_DATE in DATE
,P_JOB_GROUP_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_INTERNAL_NAME in VARCHAR2
,P_DISPLAYED_NAME in VARCHAR2
,P_ID_FLEX_NUM in NUMBER
,P_MASTER_FLAG in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_BUSINESS_GROUP_ID_O in NUMBER
,P_LEGISLATION_CODE_O in VARCHAR2
,P_INTERNAL_NAME_O in VARCHAR2
,P_DISPLAYED_NAME_O in VARCHAR2
,P_ID_FLEX_NUM_O in NUMBER
,P_MASTER_FLAG_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_JGR_RKU.AFTER_UPDATE', 10);
hr_utility.set_location(' Leaving: PER_JGR_RKU.AFTER_UPDATE', 20);
end AFTER_UPDATE;
end PER_JGR_RKU;

/
