--------------------------------------------------------
--  DDL for Package Body PER_JOB_GROUP_BK2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_JOB_GROUP_BK2" as
/* $Header: pejgrapi.pkb 115.3 2002/12/11 11:30:28 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:32:19 (YYYY/MM/DD HH24:MI:SS)
procedure UPDATE_JOB_GROUP_A
(P_EFFECTIVE_DATE in DATE
,P_JOB_GROUP_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_INTERNAL_NAME in VARCHAR2
,P_DISPLAYED_NAME in VARCHAR2
,P_ID_FLEX_NUM in NUMBER
,P_MASTER_FLAG in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PER_JOB_GROUP_BK2.UPDATE_JOB_GROUP_A', 10);
hr_utility.set_location(' Leaving: PER_JOB_GROUP_BK2.UPDATE_JOB_GROUP_A', 20);
end UPDATE_JOB_GROUP_A;
procedure UPDATE_JOB_GROUP_B
(P_EFFECTIVE_DATE in DATE
,P_JOB_GROUP_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_LEGISLATION_CODE in VARCHAR2
,P_INTERNAL_NAME in VARCHAR2
,P_DISPLAYED_NAME in VARCHAR2
,P_ID_FLEX_NUM in NUMBER
,P_MASTER_FLAG in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PER_JOB_GROUP_BK2.UPDATE_JOB_GROUP_B', 10);
hr_utility.set_location(' Leaving: PER_JOB_GROUP_BK2.UPDATE_JOB_GROUP_B', 20);
end UPDATE_JOB_GROUP_B;
end PER_JOB_GROUP_BK2;

/
