--------------------------------------------------------
--  DDL for Package Body PER_CHECKLISTS_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_CHECKLISTS_BK3" as
/* $Header: pecklapi.pkb 120.0 2005/09/28 20:56:00 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:48 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_CHECKLIST_A
(P_CHECKLIST_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_CHECKLISTS_BK3.DELETE_CHECKLIST_A', 10);
hr_utility.set_location(' Leaving: PER_CHECKLISTS_BK3.DELETE_CHECKLIST_A', 20);
end DELETE_CHECKLIST_A;
procedure DELETE_CHECKLIST_B
(P_CHECKLIST_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_CHECKLISTS_BK3.DELETE_CHECKLIST_B', 10);
hr_utility.set_location(' Leaving: PER_CHECKLISTS_BK3.DELETE_CHECKLIST_B', 20);
end DELETE_CHECKLIST_B;
end PER_CHECKLISTS_BK3;

/
