--------------------------------------------------------
--  DDL for Package Body PER_BF_BALANCE_TYPES_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_BF_BALANCE_TYPES_BK3" as
/* $Header: pebbtapi.pkb 115.6 2002/11/29 15:28:12 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:41 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_BALANCE_TYPE_A
(P_BALANCE_TYPE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_BF_BALANCE_TYPES_BK3.DELETE_BALANCE_TYPE_A', 10);
hr_utility.set_location(' Leaving: PER_BF_BALANCE_TYPES_BK3.DELETE_BALANCE_TYPE_A', 20);
end DELETE_BALANCE_TYPE_A;
procedure DELETE_BALANCE_TYPE_B
(P_BALANCE_TYPE_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_BF_BALANCE_TYPES_BK3.DELETE_BALANCE_TYPE_B', 10);
hr_utility.set_location(' Leaving: PER_BF_BALANCE_TYPES_BK3.DELETE_BALANCE_TYPE_B', 20);
end DELETE_BALANCE_TYPE_B;
end PER_BF_BALANCE_TYPES_BK3;

/
