--------------------------------------------------------
--  DDL for Package Body PER_GRA_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_GRA_RKI" as
/* $Header: pegrarhi.pkb 115.4 2003/08/31 00:48:34 generated ship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:32:13 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_CAGR_GRADE_ID in NUMBER
,P_CAGR_GRADE_STRUCTURE_ID in NUMBER
,P_CAGR_GRADE_DEF_ID in NUMBER
,P_SEQUENCE in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: PER_GRA_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: PER_GRA_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end PER_GRA_RKI;

/
