--------------------------------------------------------
--  DDL for Package Body PER_DISABILITY_API_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_DISABILITY_API_BK3" as
/* $Header: pedisapi.pkb 120.0 2005/10/02 02:14:49 generated $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:32:02 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_DISABILITY_A
(P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
,P_DISABILITY_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_START_DATE in DATE
,P_EFFECTIVE_END_DATE in DATE
)is
begin
hr_utility.set_location('Entering: PER_DISABILITY_API_BK3.DELETE_DISABILITY_A', 10);
hr_utility.set_location(' Leaving: PER_DISABILITY_API_BK3.DELETE_DISABILITY_A', 20);
end DELETE_DISABILITY_A;
procedure DELETE_DISABILITY_B
(P_EFFECTIVE_DATE in DATE
,P_DATETRACK_MODE in VARCHAR2
,P_DISABILITY_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_DISABILITY_API_BK3.DELETE_DISABILITY_B', 10);
hr_utility.set_location(' Leaving: PER_DISABILITY_API_BK3.DELETE_DISABILITY_B', 20);
end DELETE_DISABILITY_B;
end PER_DISABILITY_API_BK3;

/
