--------------------------------------------------------
--  DDL for Package Body PER_SOLUTION_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_SOLUTION_BK3" as
/* $Header: pesolapi.pkb 115.2 2003/01/04 00:38:04 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:33:19 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_SOLUTION_A
(P_SOLUTION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_SOLUTION_BK3.DELETE_SOLUTION_A', 10);
hr_utility.set_location(' Leaving: PER_SOLUTION_BK3.DELETE_SOLUTION_A', 20);
end DELETE_SOLUTION_A;
procedure DELETE_SOLUTION_B
(P_SOLUTION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_SOLUTION_BK3.DELETE_SOLUTION_B', 10);
hr_utility.set_location(' Leaving: PER_SOLUTION_BK3.DELETE_SOLUTION_B', 20);
end DELETE_SOLUTION_B;
end PER_SOLUTION_BK3;

/
