--------------------------------------------------------
--  DDL for Package Body PER_SEU_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_SEU_RKI" as
/* $Header: peseurhi.pkb 120.4 2005/11/09 13:59:48 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:33:14 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EFFECTIVE_DATE in DATE
,P_SECURITY_USER_ID in NUMBER
,P_USER_ID in NUMBER
,P_SECURITY_PROFILE_ID in NUMBER
,P_PROCESS_IN_NEXT_RUN_FLAG in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_SEU_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: PER_SEU_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end PER_SEU_RKI;

/
