--------------------------------------------------------
--  DDL for Package Body PER_ABV_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PER_ABV_RKI" as
/* $Header: peabvrhi.pkb 115.9 2002/12/03 14:36:09 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:31:32 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_EFFECTIVE_DATE in DATE
,P_VALIDATION_START_DATE in DATE
,P_VALIDATION_END_DATE in DATE
,P_ASSIGNMENT_BUDGET_VALUE_ID in NUMBER
,P_BUSINESS_GROUP_ID in NUMBER
,P_ASSIGNMENT_ID in NUMBER
,P_UNIT in VARCHAR2
,P_VALUE in NUMBER
,P_REQUEST_ID in NUMBER
,P_PROGRAM_APPLICATION_ID in NUMBER
,P_PROGRAM_ID in NUMBER
,P_PROGRAM_UPDATE_DATE in DATE
,P_EFFECTIVE_START_DATE in DATE
,P_EFFECTIVE_END_DATE in DATE
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PER_ABV_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: PER_ABV_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end PER_ABV_RKI;

/
