--------------------------------------------------------
--  DDL for Package Body PQH_TTL_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_TTL_RKD" as
/* $Header: pqttlrhi.pkb 120.1 2005/08/06 13:18:05 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:35:47 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_TEMPLATE_ID in NUMBER
,P_TEMPLATE_NAME_O in VARCHAR2
,P_LANGUAGE_O in VARCHAR2
,P_SOURCE_LANG_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PQH_TTL_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: PQH_TTL_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end PQH_TTL_RKD;

/
