--------------------------------------------------------
--  DDL for Package Body PQH_DE_ENT_MINUTES_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_DE_ENT_MINUTES_BK3" as
/* $Header: pqetmapi.pkb 115.1 2002/11/27 23:43:16 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:35:21 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_ENT_MINUTES_A
(P_ENT_MINUTES_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PQH_DE_ENT_MINUTES_BK3.DELETE_ENT_MINUTES_A', 10);
hr_utility.set_location(' Leaving: PQH_DE_ENT_MINUTES_BK3.DELETE_ENT_MINUTES_A', 20);
end DELETE_ENT_MINUTES_A;
procedure DELETE_ENT_MINUTES_B
(P_ENT_MINUTES_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PQH_DE_ENT_MINUTES_BK3.DELETE_ENT_MINUTES_B', 10);
hr_utility.set_location(' Leaving: PQH_DE_ENT_MINUTES_BK3.DELETE_ENT_MINUTES_B', 20);
end DELETE_ENT_MINUTES_B;
end PQH_DE_ENT_MINUTES_BK3;

/
