--------------------------------------------------------
--  DDL for Package Body PQH_FR_VALIDATIONS_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_FR_VALIDATIONS_BK3" as
/* $Header: pqvldapi.pkb 115.3 2002/12/05 00:30:53 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:35:49 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_VALIDATION_A
(P_VALIDATION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PQH_FR_VALIDATIONS_BK3.DELETE_VALIDATION_A', 10);
hr_utility.set_location(' Leaving: PQH_FR_VALIDATIONS_BK3.DELETE_VALIDATION_A', 20);
end DELETE_VALIDATION_A;
procedure DELETE_VALIDATION_B
(P_VALIDATION_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PQH_FR_VALIDATIONS_BK3.DELETE_VALIDATION_B', 10);
hr_utility.set_location(' Leaving: PQH_FR_VALIDATIONS_BK3.DELETE_VALIDATION_B', 20);
end DELETE_VALIDATION_B;
end PQH_FR_VALIDATIONS_BK3;

/
