--------------------------------------------------------
--  DDL for Package Body PQH_WORKSHEET_FUND_SRCS_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_WORKSHEET_FUND_SRCS_BK3" as
/* $Header: pqwfsapi.pkb 115.5 2002/12/12 23:55:35 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:35:51 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_WORKSHEET_FUND_SRC_A
(P_WORKSHEET_FUND_SRC_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PQH_WORKSHEET_FUND_SRCS_BK3.DELETE_WORKSHEET_FUND_SRC_A', 10);
hr_utility.set_location(' Leaving: PQH_WORKSHEET_FUND_SRCS_BK3.DELETE_WORKSHEET_FUND_SRC_A', 20);
end DELETE_WORKSHEET_FUND_SRC_A;
procedure DELETE_WORKSHEET_FUND_SRC_B
(P_WORKSHEET_FUND_SRC_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PQH_WORKSHEET_FUND_SRCS_BK3.DELETE_WORKSHEET_FUND_SRC_B', 10);
hr_utility.set_location(' Leaving: PQH_WORKSHEET_FUND_SRCS_BK3.DELETE_WORKSHEET_FUND_SRC_B', 20);
end DELETE_WORKSHEET_FUND_SRC_B;
end PQH_WORKSHEET_FUND_SRCS_BK3;

/
