--------------------------------------------------------
--  DDL for Package Body PQH_ATT_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_ATT_RKD" as
/* $Header: pqattrhi.pkb 120.3.12000000.2 2007/04/19 12:37:00 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2013/08/29 22:01:17 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_ATTRIBUTE_ID in NUMBER
,P_ATTRIBUTE_NAME_O in VARCHAR2
,P_MASTER_ATTRIBUTE_ID_O in NUMBER
,P_MASTER_TABLE_ROUTE_ID_O in NUMBER
,P_COLUMN_NAME_O in VARCHAR2
,P_COLUMN_TYPE_O in VARCHAR2
,P_ENABLE_FLAG_O in VARCHAR2
,P_WIDTH_O in NUMBER
,P_OBJECT_VERSION_NUMBER_O in NUMBER
,P_REGION_ITEMNAME_O in VARCHAR2
,P_ATTRIBUTE_ITEMNAME_O in VARCHAR2
,P_DECODE_FUNCTION_NAME_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PQH_ATT_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: PQH_ATT_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end PQH_ATT_RKD;

/
