--------------------------------------------------------
--  DDL for Package Body PQH_CTL_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_CTL_RKD" as
/* $Header: pqctlrhi.pkb 120.1 2005/08/06 13:16:22 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:35:18 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_TRANSACTION_CATEGORY_ID in NUMBER
,P_NAME_O in VARCHAR2
,P_LANGUAGE_O in VARCHAR2
,P_SOURCE_LANG_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PQH_CTL_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: PQH_CTL_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end PQH_CTL_RKD;

/
