--------------------------------------------------------
--  DDL for Package Body PQH_RMN_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_RMN_RKD" as
/* $Header: pqrmnrhi.pkb 120.0 2005/05/29 02:33 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:35:37 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_RATE_MATRIX_NODE_ID in NUMBER
,P_SHORT_CODE_O in VARCHAR2
,P_PL_ID_O in NUMBER
,P_LEVEL_NUMBER_O in NUMBER
,P_CRITERIA_SHORT_CODE_O in VARCHAR2
,P_NODE_NAME_O in VARCHAR2
,P_PARENT_NODE_ID_O in NUMBER
,P_ELIGY_PRFL_ID_O in NUMBER
,P_BUSINESS_GROUP_ID_O in NUMBER
,P_LEGISLATION_CODE_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
)is
begin
hr_utility.set_location('Entering: PQH_RMN_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: PQH_RMN_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end PQH_RMN_RKD;

/
