--------------------------------------------------------
--  DDL for Package Body PQH_SAT_RKD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQH_SAT_RKD" as
/* $Header: pqsatrhi.pkb 120.2 2005/10/12 20:19:29 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:35:42 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_DELETE
(P_SPECIAL_ATTRIBUTE_ID in NUMBER
,P_TXN_CATEGORY_ATTRIBUTE_ID_O in NUMBER
,P_ATTRIBUTE_TYPE_CD_O in VARCHAR2
,P_KEY_ATTRIBUTE_TYPE_O in VARCHAR2
,P_ENABLE_FLAG_O in VARCHAR2
,P_FLEX_CODE_O in VARCHAR2
,P_OBJECT_VERSION_NUMBER_O in NUMBER
,P_DDF_COLUMN_NAME_O in VARCHAR2
,P_DDF_VALUE_COLUMN_NAME_O in VARCHAR2
,P_CONTEXT_O in VARCHAR2
)is
begin
hr_utility.set_location('Entering: PQH_SAT_RKD.AFTER_DELETE', 10);
hr_utility.set_location(' Leaving: PQH_SAT_RKD.AFTER_DELETE', 20);
end AFTER_DELETE;
end PQH_SAT_RKD;

/
