--------------------------------------------------------
--  DDL for Package Body PQP_ANALYZED_ALIEN_DATA_BK3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQP_ANALYZED_ALIEN_DATA_BK3" as
/* $Header: pqaadapi.pkb 115.4 2003/01/22 00:53:34 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:36:12 (YYYY/MM/DD HH24:MI:SS)
procedure DELETE_ANALYZED_ALIEN_DATA_A
(P_ANALYZED_DATA_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: PQP_ANALYZED_ALIEN_DATA_BK3.DELETE_ANALYZED_ALIEN_DATA_A', 10);
hr_utility.set_location(' Leaving: PQP_ANALYZED_ALIEN_DATA_BK3.DELETE_ANALYZED_ALIEN_DATA_A', 20);
end DELETE_ANALYZED_ALIEN_DATA_A;
procedure DELETE_ANALYZED_ALIEN_DATA_B
(P_ANALYZED_DATA_ID in NUMBER
,P_OBJECT_VERSION_NUMBER in NUMBER
,P_EFFECTIVE_DATE in DATE
)is
begin
hr_utility.set_location('Entering: PQP_ANALYZED_ALIEN_DATA_BK3.DELETE_ANALYZED_ALIEN_DATA_B', 10);
hr_utility.set_location(' Leaving: PQP_ANALYZED_ALIEN_DATA_BK3.DELETE_ANALYZED_ALIEN_DATA_B', 20);
end DELETE_ANALYZED_ALIEN_DATA_B;
end PQP_ANALYZED_ALIEN_DATA_BK3;

/
