--------------------------------------------------------
--  DDL for Package Body PQP_FFA_RKI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PQP_FFA_RKI" as
/* $Header: pqffarhi.pkb 120.0 2006/04/26 23:47 generated noship $ */
-- Code generated by the Oracle HRMS API Hook Pre-processor
-- Created on 2007/01/04 09:36:16 (YYYY/MM/DD HH24:MI:SS)
procedure AFTER_INSERT
(P_FLXDU_FUNC_ATTRIBUTE_ID in NUMBER
,P_FLXDU_FUNC_NAME in VARCHAR2
,P_FLXDU_FUNC_SOURCE_TYPE in VARCHAR2
,P_FLXDU_FUNC_INTEGRATOR_CODE in VARCHAR2
,P_FLXDU_FUNC_XML_DATA in VARCHAR2
,P_LEGISLATION_CODE in VARCHAR2
,P_DESCRIPTION in VARCHAR2
,P_OBJECT_VERSION_NUMBER in NUMBER
)is
begin
hr_utility.set_location('Entering: PQP_FFA_RKI.AFTER_INSERT', 10);
hr_utility.set_location(' Leaving: PQP_FFA_RKI.AFTER_INSERT', 20);
end AFTER_INSERT;
end PQP_FFA_RKI;

/
