--------------------------------------------------------
--  DDL for Package Body PSP_SCHEDULE_LINES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."PSP_SCHEDULE_LINES_PKG" as
--$Header: PSPLSLIB.pls 115.8 2002/11/18 12:14:58 lveerubh ship $
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_SCHEDULE_LINE_ID in NUMBER,
  X_SCHEDULE_HIERARCHY_ID in NUMBER,
  X_GL_CODE_COMBINATION_ID in NUMBER,
  X_PROJECT_ID in NUMBER,
  X_EXPENDITURE_ORGANIZATION_ID in NUMBER,
  X_EXPENDITURE_TYPE in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_AWARD_ID in NUMBER,
  X_SCHEDULE_BEGIN_DATE in DATE,
  X_SCHEDULE_END_DATE in DATE,
  X_SCHEDULE_PERCENT in NUMBER,
  X_ENCUMBER_STATUS_CODE in VARCHAR2,
  X_DEFAULT_FLAG in VARCHAR2,
  X_WARNING_CODE in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_BUSINESS_GROUP_ID in NUMBER,
  X_SET_OF_BOOKS_ID in NUMBER
  ) is
    cursor C is select ROWID from PSP_SCHEDULE_LINES
      where SCHEDULE_LINE_ID = X_SCHEDULE_LINE_ID
      and business_group_id = X_BUSINESS_GROUP_ID
      and set_of_books_id = X_SET_OF_BOOKS_ID;
    X_LAST_UPDATE_DATE DATE;
    X_LAST_UPDATED_BY NUMBER;
    X_LAST_UPDATE_LOGIN NUMBER;
begin
  X_LAST_UPDATE_DATE := SYSDATE;
  if(X_MODE = 'I') then
    X_LAST_UPDATED_BY := 1;
    X_LAST_UPDATE_LOGIN := 0;
  elsif (X_MODE = 'R') then
    X_LAST_UPDATED_BY := FND_GLOBAL.USER_ID;
    if X_LAST_UPDATED_BY is NULL then
      X_LAST_UPDATED_BY := -1;
    end if;
    X_LAST_UPDATE_LOGIN :=FND_GLOBAL.LOGIN_ID;
    if X_LAST_UPDATE_LOGIN is NULL then
      X_LAST_UPDATE_LOGIN := -1;
    end if;
  else
    FND_MESSAGE.SET_NAME( 'FND', 'SYSTEM-INVALID ARGS');
    app_exception.raise_exception;
  end if;
  insert into PSP_SCHEDULE_LINES (
    SCHEDULE_LINE_ID,
    SCHEDULE_HIERARCHY_ID,
    GL_CODE_COMBINATION_ID,
    PROJECT_ID,
    EXPENDITURE_ORGANIZATION_ID,
    EXPENDITURE_TYPE,
    TASK_ID,
    AWARD_ID,
    SCHEDULE_BEGIN_DATE,
    SCHEDULE_END_DATE,
    SCHEDULE_PERCENT,
    ENCUMBER_STATUS_CODE,
    DEFAULT_FLAG,
    WARNING_CODE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    BUSINESS_GROUP_ID,
    SET_OF_BOOKS_ID
  ) values (
    X_SCHEDULE_LINE_ID,
    X_SCHEDULE_HIERARCHY_ID,
    X_GL_CODE_COMBINATION_ID,
    X_PROJECT_ID,
    X_EXPENDITURE_ORGANIZATION_ID,
    X_EXPENDITURE_TYPE,
    X_TASK_ID,
    X_AWARD_ID,
    X_SCHEDULE_BEGIN_DATE,
    X_SCHEDULE_END_DATE,
    X_SCHEDULE_PERCENT,
    X_ENCUMBER_STATUS_CODE,
    X_DEFAULT_FLAG,
    X_WARNING_CODE,
    X_ATTRIBUTE_CATEGORY,
    X_ATTRIBUTE1,
    X_ATTRIBUTE2,
    X_ATTRIBUTE3,
    X_ATTRIBUTE4,
    X_ATTRIBUTE5,
    X_ATTRIBUTE6,
    X_ATTRIBUTE7,
    X_ATTRIBUTE8,
    X_ATTRIBUTE9,
    X_ATTRIBUTE10,
    X_ATTRIBUTE11,
    X_ATTRIBUTE12,
    X_ATTRIBUTE13,
    X_ATTRIBUTE14,
    X_ATTRIBUTE15,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN,
    X_BUSINESS_GROUP_ID,
    X_SET_OF_BOOKS_ID
  );

  open c;
  fetch c into X_ROWID;
  if (c%notfound) then
    close c;
    raise no_data_found;
  end if;
  close c;

end INSERT_ROW;

procedure LOCK_ROW (
  X_SCHEDULE_LINE_ID in NUMBER,
  X_SCHEDULE_HIERARCHY_ID in NUMBER,
  X_GL_CODE_COMBINATION_ID in NUMBER,
  X_PROJECT_ID in NUMBER,
  X_EXPENDITURE_ORGANIZATION_ID in NUMBER,
  X_EXPENDITURE_TYPE in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_AWARD_ID in NUMBER,
  X_SCHEDULE_BEGIN_DATE in DATE,
  X_SCHEDULE_END_DATE in DATE,
  X_SCHEDULE_PERCENT in NUMBER,
  X_ENCUMBER_STATUS_CODE in VARCHAR2,
  X_DEFAULT_FLAG in VARCHAR2,
  X_WARNING_CODE in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_BUSINESS_GROUP_ID in NUMBER,
  X_SET_OF_BOOKS_ID in NUMBER
) is
  cursor c1 is select
      SCHEDULE_HIERARCHY_ID,
      GL_CODE_COMBINATION_ID,
      PROJECT_ID,
      EXPENDITURE_ORGANIZATION_ID,
      EXPENDITURE_TYPE,
      TASK_ID,
      AWARD_ID,
      SCHEDULE_BEGIN_DATE,
      SCHEDULE_END_DATE,
      SCHEDULE_PERCENT,
      ENCUMBER_STATUS_CODE,
      DEFAULT_FLAG,
      WARNING_CODE,
      ATTRIBUTE_CATEGORY,
      ATTRIBUTE1,
      ATTRIBUTE2,
      ATTRIBUTE3,
      ATTRIBUTE4,
      ATTRIBUTE5,
      ATTRIBUTE6,
      ATTRIBUTE7,
      ATTRIBUTE8,
      ATTRIBUTE9,
      ATTRIBUTE10,
      ATTRIBUTE11,
      ATTRIBUTE12,
      ATTRIBUTE13,
      ATTRIBUTE14,
      ATTRIBUTE15,
      BUSINESS_GROUP_ID,
      SET_OF_BOOKS_ID
    from PSP_SCHEDULE_LINES
    where SCHEDULE_LINE_ID = X_SCHEDULE_LINE_ID
    and business_group_id = X_BUSINESS_GROUP_ID
    and set_of_books_id = X_SET_OF_BOOKS_ID
    for update of SCHEDULE_LINE_ID nowait;
  tlinfo c1%rowtype;

begin
  open c1;
  fetch c1 into tlinfo;
  if (c1%notfound) then
    fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
    app_exception.raise_exception;
    close c1;
    return;
  end if;
  close c1;

  if ( (tlinfo.SCHEDULE_HIERARCHY_ID = X_SCHEDULE_HIERARCHY_ID)
      AND ((tlinfo.GL_CODE_COMBINATION_ID = X_GL_CODE_COMBINATION_ID)
           OR ((tlinfo.GL_CODE_COMBINATION_ID is null)
               AND (X_GL_CODE_COMBINATION_ID is null)))
      AND ((tlinfo.SCHEDULE_BEGIN_DATE = X_SCHEDULE_BEGIN_DATE)
           OR ((tlinfo.SCHEDULE_BEGIN_DATE is null)
               AND (X_SCHEDULE_BEGIN_DATE is null)))
      AND ((tlinfo.SCHEDULE_END_DATE = X_SCHEDULE_END_DATE)
           OR ((tlinfo.SCHEDULE_END_DATE is null)
               AND (X_SCHEDULE_END_DATE is null)))
      AND ((tlinfo.SCHEDULE_PERCENT = X_SCHEDULE_PERCENT)
           OR ((tlinfo.SCHEDULE_PERCENT is null)
               AND (X_SCHEDULE_PERCENT is null)))
      AND ((tlinfo.ENCUMBER_STATUS_CODE = X_ENCUMBER_STATUS_CODE)
           OR ((tlinfo.ENCUMBER_STATUS_CODE is null)
               AND (X_ENCUMBER_STATUS_CODE is null)))
      AND ((tlinfo.DEFAULT_FLAG = X_DEFAULT_FLAG)
           OR ((tlinfo.DEFAULT_FLAG is null)
               AND (X_DEFAULT_FLAG is null)))
      AND ((tlinfo.WARNING_CODE = X_WARNING_CODE)
           OR ((tlinfo.WARNING_CODE is null)
               AND (X_WARNING_CODE is null)))
      AND ((tlinfo.ATTRIBUTE_CATEGORY = X_ATTRIBUTE_CATEGORY)
           OR ((tlinfo.ATTRIBUTE_CATEGORY is null)
               AND (X_ATTRIBUTE_CATEGORY is null)))
      AND ((tlinfo.ATTRIBUTE1 = X_ATTRIBUTE1)
           OR ((tlinfo.ATTRIBUTE1 is null)
               AND (X_ATTRIBUTE1 is null)))
      AND ((tlinfo.ATTRIBUTE2 = X_ATTRIBUTE2)
           OR ((tlinfo.ATTRIBUTE2 is null)
               AND (X_ATTRIBUTE2 is null)))
      AND ((tlinfo.ATTRIBUTE3 = X_ATTRIBUTE3)
           OR ((tlinfo.ATTRIBUTE3 is null)
               AND (X_ATTRIBUTE3 is null)))
      AND ((tlinfo.ATTRIBUTE4 = X_ATTRIBUTE4)
           OR ((tlinfo.ATTRIBUTE4 is null)
               AND (X_ATTRIBUTE4 is null)))
      AND ((tlinfo.ATTRIBUTE5 = X_ATTRIBUTE5)
           OR ((tlinfo.ATTRIBUTE5 is null)
               AND (X_ATTRIBUTE5 is null)))
      AND ((tlinfo.ATTRIBUTE6 = X_ATTRIBUTE6)
           OR ((tlinfo.ATTRIBUTE6 is null)
               AND (X_ATTRIBUTE6 is null)))
      AND ((tlinfo.ATTRIBUTE7 = X_ATTRIBUTE7)
           OR ((tlinfo.ATTRIBUTE7 is null)
               AND (X_ATTRIBUTE7 is null)))
      AND ((tlinfo.ATTRIBUTE8 = X_ATTRIBUTE8)
           OR ((tlinfo.ATTRIBUTE8 is null)
               AND (X_ATTRIBUTE8 is null)))
      AND ((tlinfo.ATTRIBUTE9 = X_ATTRIBUTE9)
           OR ((tlinfo.ATTRIBUTE9 is null)
               AND (X_ATTRIBUTE9 is null)))
      AND ((tlinfo.ATTRIBUTE10 = X_ATTRIBUTE10)
           OR ((tlinfo.ATTRIBUTE10 is null)
               AND (X_ATTRIBUTE10 is null)))
      AND ((tlinfo.ATTRIBUTE11 = X_ATTRIBUTE11)
           OR ((tlinfo.ATTRIBUTE11 is null)
               AND (X_ATTRIBUTE11 is null)))
      AND ((tlinfo.ATTRIBUTE12 = X_ATTRIBUTE12)
           OR ((tlinfo.ATTRIBUTE12 is null)
               AND (X_ATTRIBUTE12 is null)))
      AND ((tlinfo.ATTRIBUTE13 = X_ATTRIBUTE13)
           OR ((tlinfo.ATTRIBUTE13 is null)
               AND (X_ATTRIBUTE13 is null)))
      AND ((tlinfo.ATTRIBUTE14 = X_ATTRIBUTE14)
           OR ((tlinfo.ATTRIBUTE14 is null)
               AND (X_ATTRIBUTE14 is null)))
      AND ((tlinfo.ATTRIBUTE15 = X_ATTRIBUTE15)
           OR ((tlinfo.ATTRIBUTE15 is null)
               AND (X_ATTRIBUTE15 is null)))
  ) then
    null;
  else
    fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
    app_exception.raise_exception;
  end if;
  return;
end LOCK_ROW;

procedure UPDATE_ROW (
  X_SCHEDULE_LINE_ID in NUMBER,
  X_SCHEDULE_HIERARCHY_ID in NUMBER,
  X_GL_CODE_COMBINATION_ID in NUMBER,
  X_PROJECT_ID in NUMBER,
  X_EXPENDITURE_ORGANIZATION_ID in NUMBER,
  X_EXPENDITURE_TYPE in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_AWARD_ID in NUMBER,
  X_SCHEDULE_BEGIN_DATE in DATE,
  X_SCHEDULE_END_DATE in DATE,
  X_SCHEDULE_PERCENT in NUMBER,
  X_ENCUMBER_STATUS_CODE in VARCHAR2,
  X_DEFAULT_FLAG in VARCHAR2,
  X_WARNING_CODE in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_BUSINESS_GROUP_ID in NUMBER,
  X_SET_OF_BOOKS_ID in NUMBER
  ) is
    X_LAST_UPDATE_DATE DATE;
    X_LAST_UPDATED_BY NUMBER;
    X_LAST_UPDATE_LOGIN NUMBER;
begin
  X_LAST_UPDATE_DATE := SYSDATE;
  if(X_MODE = 'I') then
    X_LAST_UPDATED_BY := 1;
    X_LAST_UPDATE_LOGIN := 0;
  elsif (X_MODE = 'R') then
    X_LAST_UPDATED_BY := FND_GLOBAL.USER_ID;
    if X_LAST_UPDATED_BY is NULL then
      X_LAST_UPDATED_BY := -1;
    end if;
    X_LAST_UPDATE_LOGIN :=FND_GLOBAL.LOGIN_ID;
    if X_LAST_UPDATE_LOGIN is NULL then
      X_LAST_UPDATE_LOGIN := -1;
    end if;
  else
    FND_MESSAGE.SET_NAME('FND', 'SYSTEM-INVALID ARGS');
    app_exception.raise_exception;
  end if;
  update PSP_SCHEDULE_LINES set
    SCHEDULE_HIERARCHY_ID = X_SCHEDULE_HIERARCHY_ID,
    GL_CODE_COMBINATION_ID = X_GL_CODE_COMBINATION_ID,
    PROJECT_ID = X_PROJECT_ID,
    EXPENDITURE_ORGANIZATION_ID = X_EXPENDITURE_ORGANIZATION_ID,
    EXPENDITURE_TYPE = X_EXPENDITURE_TYPE,
    TASK_ID = X_TASK_ID,
    AWARD_ID = X_AWARD_ID,
    SCHEDULE_BEGIN_DATE = X_SCHEDULE_BEGIN_DATE,
    SCHEDULE_END_DATE = X_SCHEDULE_END_DATE,
    SCHEDULE_PERCENT = X_SCHEDULE_PERCENT,
    ENCUMBER_STATUS_CODE = X_ENCUMBER_STATUS_CODE,
    DEFAULT_FLAG = X_DEFAULT_FLAG,
    WARNING_CODE = X_WARNING_CODE,
    ATTRIBUTE_CATEGORY = X_ATTRIBUTE_CATEGORY,
    ATTRIBUTE1 = X_ATTRIBUTE1,
    ATTRIBUTE2 = X_ATTRIBUTE2,
    ATTRIBUTE3 = X_ATTRIBUTE3,
    ATTRIBUTE4 = X_ATTRIBUTE4,
    ATTRIBUTE5 = X_ATTRIBUTE5,
    ATTRIBUTE6 = X_ATTRIBUTE6,
    ATTRIBUTE7 = X_ATTRIBUTE7,
    ATTRIBUTE8 = X_ATTRIBUTE8,
    ATTRIBUTE9 = X_ATTRIBUTE9,
    ATTRIBUTE10 = X_ATTRIBUTE10,
    ATTRIBUTE11 = X_ATTRIBUTE11,
    ATTRIBUTE12 = X_ATTRIBUTE12,
    ATTRIBUTE13 = X_ATTRIBUTE13,
    ATTRIBUTE14 = X_ATTRIBUTE14,
    ATTRIBUTE15 = X_ATTRIBUTE15,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN
  where SCHEDULE_LINE_ID = X_SCHEDULE_LINE_ID
  and business_group_id = X_BUSINESS_GROUP_ID
  and set_of_books_id = X_SET_OF_BOOKS_ID
  ;
  if (sql%notfound) then
    raise no_data_found;
  end if;
end UPDATE_ROW;

procedure ADD_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_SCHEDULE_LINE_ID in NUMBER,
  X_SCHEDULE_HIERARCHY_ID in NUMBER,
  X_GL_CODE_COMBINATION_ID in NUMBER,
  X_PROJECT_ID in NUMBER,
  X_EXPENDITURE_ORGANIZATION_ID in NUMBER,
  X_EXPENDITURE_TYPE in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_AWARD_ID in NUMBER,
  X_SCHEDULE_BEGIN_DATE in DATE,
  X_SCHEDULE_END_DATE in DATE,
  X_SCHEDULE_PERCENT in NUMBER,
  X_ENCUMBER_STATUS_CODE in VARCHAR2,
  X_DEFAULT_FLAG in VARCHAR2,
  X_WARNING_CODE in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_BUSINESS_GROUP_ID in NUMBER,
  X_SET_OF_BOOKS_ID in NUMBER
  ) is
  cursor c1 is select rowid from PSP_SCHEDULE_LINES
     where SCHEDULE_LINE_ID = X_SCHEDULE_LINE_ID
     and business_group_id = X_BUSINESS_GROUP_ID
     and set_of_books_id = X_SET_OF_BOOKS_ID
  ;
  dummy c1%rowtype;
begin
  open c1;
  fetch c1 into dummy;
  if (c1%notfound) then
    close c1;
    INSERT_ROW (
     X_ROWID,
     X_SCHEDULE_LINE_ID,
     X_SCHEDULE_HIERARCHY_ID,
     X_GL_CODE_COMBINATION_ID,
     X_PROJECT_ID,
     X_EXPENDITURE_ORGANIZATION_ID,
     X_EXPENDITURE_TYPE,
     X_TASK_ID,
     X_AWARD_ID,
     X_SCHEDULE_BEGIN_DATE,
     X_SCHEDULE_END_DATE,
     X_SCHEDULE_PERCENT,
     X_ENCUMBER_STATUS_CODE,
     X_DEFAULT_FLAG,
     X_WARNING_CODE,
     X_ATTRIBUTE_CATEGORY,
     X_ATTRIBUTE1,
     X_ATTRIBUTE2,
     X_ATTRIBUTE3,
     X_ATTRIBUTE4,
     X_ATTRIBUTE5,
     X_ATTRIBUTE6,
     X_ATTRIBUTE7,
     X_ATTRIBUTE8,
     X_ATTRIBUTE9,
     X_ATTRIBUTE10,
     X_ATTRIBUTE11,
     X_ATTRIBUTE12,
     X_ATTRIBUTE13,
     X_ATTRIBUTE14,
     X_ATTRIBUTE15,
     X_MODE,
     X_BUSINESS_GROUP_ID,
     X_SET_OF_BOOKS_ID
     );
    return;
  end if;
  close c1;
  UPDATE_ROW (
   X_SCHEDULE_LINE_ID,
   X_SCHEDULE_HIERARCHY_ID,
   X_GL_CODE_COMBINATION_ID,
   X_PROJECT_ID,
   X_EXPENDITURE_ORGANIZATION_ID,
   X_EXPENDITURE_TYPE,
   X_TASK_ID,
   X_AWARD_ID,
   X_SCHEDULE_BEGIN_DATE,
   X_SCHEDULE_END_DATE,
   X_SCHEDULE_PERCENT,
   X_ENCUMBER_STATUS_CODE,
   X_DEFAULT_FLAG,
   X_WARNING_CODE,
   X_ATTRIBUTE_CATEGORY,
   X_ATTRIBUTE1,
   X_ATTRIBUTE2,
   X_ATTRIBUTE3,
   X_ATTRIBUTE4,
   X_ATTRIBUTE5,
   X_ATTRIBUTE6,
   X_ATTRIBUTE7,
   X_ATTRIBUTE8,
   X_ATTRIBUTE9,
   X_ATTRIBUTE10,
   X_ATTRIBUTE11,
   X_ATTRIBUTE12,
   X_ATTRIBUTE13,
   X_ATTRIBUTE14,
   X_ATTRIBUTE15,
   X_MODE,
   X_BUSINESS_GROUP_ID,
   X_SET_OF_BOOKS_ID
);
end ADD_ROW;

procedure DELETE_ROW (
  X_SCHEDULE_LINE_ID in NUMBER,
  X_BUSINESS_GROUP_ID in NUMBER,
  X_SET_OF_BOOKS_ID in NUMBER
) is
begin
  delete from PSP_SCHEDULE_LINES
  where SCHEDULE_LINE_ID = X_SCHEDULE_LINE_ID
  and business_group_id = X_BUSINESS_GROUP_ID
  and set_of_books_id = X_SET_OF_BOOKS_ID
;
  if (sql%notfound) then
    raise no_data_found;
  end if;
end DELETE_ROW;

end PSP_SCHEDULE_LINES_PKG;

/
