--------------------------------------------------------
--  DDL for Package Body QA_QLTPLTXR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."QA_QLTPLTXR_XMLP_PKG" AS
/* $Header: QLTPLTXRB.pls 120.0 2007/12/24 10:37:40 krreddy noship $ */
  FUNCTION AFTERPFORM RETURN BOOLEAN IS
  BEGIN
  PLAN_NAME_1:=PLAN_NAME;
    IF LENGTH(PLAN_NAME_1) < 30 THEN
      PLAN_NAME_1 := PLAN_NAME_1 || '%';
    END IF;
    RETURN (TRUE);
  END AFTERPFORM;

  FUNCTION BEFOREREPORT RETURN BOOLEAN IS
  BEGIN
    P_CONC_REQUEST_ID := FND_GLOBAL.CONC_REQUEST_ID;
    /*SRW.USER_EXIT('FND SRWINIT')*/NULL;
    RETURN (TRUE);
  END BEFOREREPORT;

  FUNCTION AFTERREPORT RETURN BOOLEAN IS
  BEGIN
    /*SRW.USER_EXIT('FND SRWEXIT')*/NULL;
    RETURN (TRUE);
  END AFTERREPORT;

END QA_QLTPLTXR_XMLP_PKG;


/
