--------------------------------------------------------
--  DDL for Package Body QP_SEGMENTS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS"."QP_SEGMENTS_PKG" as
/* $Header: QPXSEGMB.pls 120.1 2005/06/09 03:04:44 appldev  $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY /* file.sql.39 change */ VARCHAR2,
  X_SEGMENT_ID in NUMBER,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_SEGMENT_CODE in VARCHAR2,
  X_PRC_CONTEXT_ID in NUMBER,
  X_AVAILABILITY_IN_BASIC in VARCHAR2,
  X_SEGMENT_MAPPING_COLUMN in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_SEEDED_PRECEDENCE in NUMBER,
  X_USER_PRECEDENCE in NUMBER,
  X_SEEDED_VALUESET_ID in NUMBER,
  X_USER_VALUESET_ID in NUMBER,
  X_SEEDED_FORMAT_TYPE in VARCHAR2,
  X_USER_FORMAT_TYPE in VARCHAR2,
  X_CONTEXT in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_SEEDED_SEGMENT_NAME in VARCHAR2,
  X_USER_SEGMENT_NAME in VARCHAR2,
  X_SEEDED_DESCRIPTION in VARCHAR2,
  X_USER_DESCRIPTION in VARCHAR2,
  X_REQUIRED_FLAG in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
) is
  cursor C is select ROWID from QP_SEGMENTS_B
    where SEGMENT_ID = X_SEGMENT_ID
    ;
begin
  insert into QP_SEGMENTS_B (
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    SEGMENT_ID,
    SEGMENT_CODE,
    PRC_CONTEXT_ID,
    AVAILABILITY_IN_BASIC,
    SEGMENT_MAPPING_COLUMN,
    SEEDED_FLAG,
    APPLICATION_ID,
    SEEDED_PRECEDENCE,
    USER_PRECEDENCE,
    SEEDED_VALUESET_ID,
    USER_VALUESET_ID,
    SEEDED_FORMAT_TYPE,
    USER_FORMAT_TYPE,
    REQUIRED_FLAG,
    CONTEXT,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE15,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN
  ) values (
    X_ATTRIBUTE12,
    X_ATTRIBUTE13,
    X_ATTRIBUTE14,
    X_ATTRIBUTE8,
    X_ATTRIBUTE9,
    X_ATTRIBUTE10,
    X_ATTRIBUTE11,
    X_SEGMENT_ID,
    X_SEGMENT_CODE,
    X_PRC_CONTEXT_ID,
    X_AVAILABILITY_IN_BASIC,
    X_SEGMENT_MAPPING_COLUMN,
    X_SEEDED_FLAG,
    X_APPLICATION_ID,
    X_SEEDED_PRECEDENCE,
    X_USER_PRECEDENCE,
    X_SEEDED_VALUESET_ID,
    X_USER_VALUESET_ID,
    X_SEEDED_FORMAT_TYPE,
    X_USER_FORMAT_TYPE,
    X_REQUIRED_FLAG,
    X_CONTEXT,
    X_ATTRIBUTE1,
    X_ATTRIBUTE2,
    X_ATTRIBUTE3,
    X_ATTRIBUTE4,
    X_ATTRIBUTE5,
    X_ATTRIBUTE6,
    X_ATTRIBUTE7,
    X_ATTRIBUTE15,
    X_CREATION_DATE,
    X_CREATED_BY,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN
  );

  insert into QP_SEGMENTS_TL (
    SEGMENT_ID,
    SEEDED_SEGMENT_NAME,
    USER_SEGMENT_NAME,
    SEEDED_DESCRIPTION,
    USER_DESCRIPTION,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    LANGUAGE,
    SOURCE_LANG
  ) select
    X_SEGMENT_ID,
    X_SEEDED_SEGMENT_NAME,
    X_USER_SEGMENT_NAME,
    X_SEEDED_DESCRIPTION,
    X_USER_DESCRIPTION,
    X_CREATED_BY,
    X_CREATION_DATE,
    X_LAST_UPDATED_BY,
    X_LAST_UPDATE_DATE,
    X_LAST_UPDATE_LOGIN,
    L.LANGUAGE_CODE,
    userenv('LANG')
  from FND_LANGUAGES L
  where L.INSTALLED_FLAG in ('I', 'B')
  and not exists
    (select NULL
    from QP_SEGMENTS_TL T
    where T.SEGMENT_ID = X_SEGMENT_ID
    and T.LANGUAGE = L.LANGUAGE_CODE);

  open c;
  fetch c into X_ROWID;
  if (c%notfound) then
    close c;
    raise no_data_found;
  end if;
  close c;

end INSERT_ROW;

procedure LOCK_ROW (
  X_SEGMENT_ID in NUMBER,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_SEGMENT_CODE in VARCHAR2,
  X_PRC_CONTEXT_ID in NUMBER,
  X_AVAILABILITY_IN_BASIC in VARCHAR2,
  X_SEGMENT_MAPPING_COLUMN in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_SEEDED_PRECEDENCE in NUMBER,
  X_USER_PRECEDENCE in NUMBER,
  X_SEEDED_VALUESET_ID in NUMBER,
  X_USER_VALUESET_ID in NUMBER,
  X_SEEDED_FORMAT_TYPE in VARCHAR2,
  X_USER_FORMAT_TYPE in VARCHAR2,
  X_CONTEXT in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_SEEDED_SEGMENT_NAME in VARCHAR2,
  X_USER_SEGMENT_NAME in VARCHAR2,
  X_SEEDED_DESCRIPTION in VARCHAR2,
  X_USER_DESCRIPTION in VARCHAR2,
  X_REQUIRED_FLAG in VARCHAR2
) is
  cursor c is select
      ATTRIBUTE12,
      ATTRIBUTE13,
      ATTRIBUTE14,
      ATTRIBUTE8,
      ATTRIBUTE9,
      ATTRIBUTE10,
      ATTRIBUTE11,
      SEGMENT_CODE,
      PRC_CONTEXT_ID,
      AVAILABILITY_IN_BASIC,
      SEGMENT_MAPPING_COLUMN,
      SEEDED_FLAG,
      APPLICATION_ID,
      SEEDED_PRECEDENCE,
      USER_PRECEDENCE,
      SEEDED_VALUESET_ID,
      USER_VALUESET_ID,
      SEEDED_FORMAT_TYPE,
      USER_FORMAT_TYPE,
      REQUIRED_FLAG,
      CONTEXT,
      ATTRIBUTE1,
      ATTRIBUTE2,
      ATTRIBUTE3,
      ATTRIBUTE4,
      ATTRIBUTE5,
      ATTRIBUTE6,
      ATTRIBUTE7,
      ATTRIBUTE15
    from QP_SEGMENTS_B
    where SEGMENT_ID = X_SEGMENT_ID
    for update of SEGMENT_ID nowait;
  recinfo c%rowtype;

  cursor c1 is select
      SEEDED_SEGMENT_NAME,
      USER_SEGMENT_NAME,
      SEEDED_DESCRIPTION,
      USER_DESCRIPTION,
      decode(LANGUAGE, userenv('LANG'), 'Y', 'N') BASELANG
    from QP_SEGMENTS_TL
    where SEGMENT_ID = X_SEGMENT_ID
    and userenv('LANG') in (LANGUAGE, SOURCE_LANG)
    for update of SEGMENT_ID nowait;
begin
  open c;
  fetch c into recinfo;
  if (c%notfound) then
    close c;
    fnd_message.set_name('FND', 'FORM_RECORD_DELETED');
    app_exception.raise_exception;
  end if;
  close c;
  if (    ((recinfo.ATTRIBUTE12 = X_ATTRIBUTE12)
           OR ((recinfo.ATTRIBUTE12 is null) AND (X_ATTRIBUTE12 is null)))
      AND ((recinfo.ATTRIBUTE13 = X_ATTRIBUTE13)
           OR ((recinfo.ATTRIBUTE13 is null) AND (X_ATTRIBUTE13 is null)))
      AND ((recinfo.ATTRIBUTE14 = X_ATTRIBUTE14)
           OR ((recinfo.ATTRIBUTE14 is null) AND (X_ATTRIBUTE14 is null)))
      AND ((recinfo.ATTRIBUTE8 = X_ATTRIBUTE8)
           OR ((recinfo.ATTRIBUTE8 is null) AND (X_ATTRIBUTE8 is null)))
      AND ((recinfo.ATTRIBUTE9 = X_ATTRIBUTE9)
           OR ((recinfo.ATTRIBUTE9 is null) AND (X_ATTRIBUTE9 is null)))
      AND ((recinfo.ATTRIBUTE10 = X_ATTRIBUTE10)
           OR ((recinfo.ATTRIBUTE10 is null) AND (X_ATTRIBUTE10 is null)))
      AND ((recinfo.ATTRIBUTE11 = X_ATTRIBUTE11)
           OR ((recinfo.ATTRIBUTE11 is null) AND (X_ATTRIBUTE11 is null)))
      AND (recinfo.SEGMENT_CODE = X_SEGMENT_CODE)
      AND (recinfo.PRC_CONTEXT_ID = X_PRC_CONTEXT_ID)
      AND (recinfo.AVAILABILITY_IN_BASIC = X_AVAILABILITY_IN_BASIC)
      AND (recinfo.SEGMENT_MAPPING_COLUMN = X_SEGMENT_MAPPING_COLUMN)
      AND (recinfo.SEEDED_FLAG = X_SEEDED_FLAG)
      AND (recinfo.APPLICATION_ID = X_APPLICATION_ID)
      AND ((recinfo.SEEDED_PRECEDENCE = X_SEEDED_PRECEDENCE)
           OR ((recinfo.SEEDED_PRECEDENCE is null) AND (X_SEEDED_PRECEDENCE is null)))
      AND (recinfo.USER_PRECEDENCE = X_USER_PRECEDENCE)
      AND ((recinfo.SEEDED_VALUESET_ID = X_SEEDED_VALUESET_ID)
           OR ((recinfo.SEEDED_VALUESET_ID is null) AND (X_SEEDED_VALUESET_ID is null)))
      AND ((recinfo.USER_VALUESET_ID = X_USER_VALUESET_ID)
           OR ((recinfo.USER_VALUESET_ID is null) AND (X_USER_VALUESET_ID is null)))
      AND ((recinfo.SEEDED_FORMAT_TYPE = X_SEEDED_FORMAT_TYPE)
           OR ((recinfo.SEEDED_FORMAT_TYPE is null) AND (X_SEEDED_FORMAT_TYPE is null)))
      AND ((recinfo.USER_FORMAT_TYPE = X_USER_FORMAT_TYPE)
           OR ((recinfo.USER_FORMAT_TYPE is null) AND (X_USER_FORMAT_TYPE is null)))
      AND ((recinfo.REQUIRED_FLAG = X_REQUIRED_FLAG)
           OR ((recinfo.REQUIRED_FLAG is null) AND (X_REQUIRED_FLAG is null)))
      AND ((recinfo.CONTEXT = X_CONTEXT)
           OR ((recinfo.CONTEXT is null) AND (X_CONTEXT is null)))
      AND ((recinfo.ATTRIBUTE1 = X_ATTRIBUTE1)
           OR ((recinfo.ATTRIBUTE1 is null) AND (X_ATTRIBUTE1 is null)))
      AND ((recinfo.ATTRIBUTE2 = X_ATTRIBUTE2)
           OR ((recinfo.ATTRIBUTE2 is null) AND (X_ATTRIBUTE2 is null)))
      AND ((recinfo.ATTRIBUTE3 = X_ATTRIBUTE3)
           OR ((recinfo.ATTRIBUTE3 is null) AND (X_ATTRIBUTE3 is null)))
      AND ((recinfo.ATTRIBUTE4 = X_ATTRIBUTE4)
           OR ((recinfo.ATTRIBUTE4 is null) AND (X_ATTRIBUTE4 is null)))
      AND ((recinfo.ATTRIBUTE5 = X_ATTRIBUTE5)
           OR ((recinfo.ATTRIBUTE5 is null) AND (X_ATTRIBUTE5 is null)))
      AND ((recinfo.ATTRIBUTE6 = X_ATTRIBUTE6)
           OR ((recinfo.ATTRIBUTE6 is null) AND (X_ATTRIBUTE6 is null)))
      AND ((recinfo.ATTRIBUTE7 = X_ATTRIBUTE7)
           OR ((recinfo.ATTRIBUTE7 is null) AND (X_ATTRIBUTE7 is null)))
      AND ((recinfo.ATTRIBUTE15 = X_ATTRIBUTE15)
           OR ((recinfo.ATTRIBUTE15 is null) AND (X_ATTRIBUTE15 is null)))
  ) then
    null;
  else
    fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
    app_exception.raise_exception;
  end if;

  for tlinfo in c1 loop
    if (tlinfo.BASELANG = 'Y') then
      if ((    ((tlinfo.SEEDED_SEGMENT_NAME = X_SEEDED_SEGMENT_NAME)
               OR ((tlinfo.SEEDED_SEGMENT_NAME is null) AND (X_SEEDED_SEGMENT_NAME is null)))
          AND (tlinfo.USER_SEGMENT_NAME = X_USER_SEGMENT_NAME)
      )  AND
       (    ((tlinfo.SEEDED_DESCRIPTION = X_SEEDED_DESCRIPTION)
               OR ((tlinfo.SEEDED_DESCRIPTION is null) AND (X_SEEDED_DESCRIPTION is null)))
          AND (tlinfo.USER_DESCRIPTION = X_USER_DESCRIPTION))) then
        null;
      else
        fnd_message.set_name('FND', 'FORM_RECORD_CHANGED');
        app_exception.raise_exception;
      end if;
    end if;
  end loop;
  return;
end LOCK_ROW;

procedure UPDATE_ROW (
  X_SEGMENT_ID in NUMBER,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_SEGMENT_CODE in VARCHAR2,
  X_PRC_CONTEXT_ID in NUMBER,
  X_AVAILABILITY_IN_BASIC in VARCHAR2,
  X_SEGMENT_MAPPING_COLUMN in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_SEEDED_PRECEDENCE in NUMBER,
  X_USER_PRECEDENCE in NUMBER,
  X_SEEDED_VALUESET_ID in NUMBER,
  X_USER_VALUESET_ID in NUMBER,
  X_SEEDED_FORMAT_TYPE in VARCHAR2,
  X_USER_FORMAT_TYPE in VARCHAR2,
  X_CONTEXT in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_SEEDED_SEGMENT_NAME in VARCHAR2,
  X_USER_SEGMENT_NAME in VARCHAR2,
  X_SEEDED_DESCRIPTION in VARCHAR2,
  X_USER_DESCRIPTION in VARCHAR2,
  X_REQUIRED_FLAG in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
) is
begin
  update QP_SEGMENTS_B set
    ATTRIBUTE12 = X_ATTRIBUTE12,
    ATTRIBUTE13 = X_ATTRIBUTE13,
    ATTRIBUTE14 = X_ATTRIBUTE14,
    ATTRIBUTE8 = X_ATTRIBUTE8,
    ATTRIBUTE9 = X_ATTRIBUTE9,
    ATTRIBUTE10 = X_ATTRIBUTE10,
    ATTRIBUTE11 = X_ATTRIBUTE11,
    SEGMENT_CODE = X_SEGMENT_CODE,
    PRC_CONTEXT_ID = X_PRC_CONTEXT_ID,
    AVAILABILITY_IN_BASIC = X_AVAILABILITY_IN_BASIC,
    SEGMENT_MAPPING_COLUMN = X_SEGMENT_MAPPING_COLUMN,
    SEEDED_FLAG = X_SEEDED_FLAG,
    APPLICATION_ID = X_APPLICATION_ID,
    SEEDED_PRECEDENCE = X_SEEDED_PRECEDENCE,
    USER_PRECEDENCE = X_USER_PRECEDENCE,
    SEEDED_VALUESET_ID = X_SEEDED_VALUESET_ID,
    USER_VALUESET_ID = X_USER_VALUESET_ID,
    SEEDED_FORMAT_TYPE = X_SEEDED_FORMAT_TYPE,
    USER_FORMAT_TYPE = X_USER_FORMAT_TYPE,
    REQUIRED_FLAG = X_REQUIRED_FLAG,
    CONTEXT = X_CONTEXT,
    ATTRIBUTE1 = X_ATTRIBUTE1,
    ATTRIBUTE2 = X_ATTRIBUTE2,
    ATTRIBUTE3 = X_ATTRIBUTE3,
    ATTRIBUTE4 = X_ATTRIBUTE4,
    ATTRIBUTE5 = X_ATTRIBUTE5,
    ATTRIBUTE6 = X_ATTRIBUTE6,
    ATTRIBUTE7 = X_ATTRIBUTE7,
    ATTRIBUTE15 = X_ATTRIBUTE15,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN
  where SEGMENT_ID = X_SEGMENT_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;

  update QP_SEGMENTS_TL set
    SEEDED_SEGMENT_NAME = X_SEEDED_SEGMENT_NAME,
    USER_SEGMENT_NAME = X_USER_SEGMENT_NAME,
    SEEDED_DESCRIPTION = X_SEEDED_DESCRIPTION,
    USER_DESCRIPTION = X_USER_DESCRIPTION,
    LAST_UPDATE_DATE = X_LAST_UPDATE_DATE,
    LAST_UPDATED_BY = X_LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN = X_LAST_UPDATE_LOGIN,
    SOURCE_LANG = userenv('LANG')
  where SEGMENT_ID = X_SEGMENT_ID
  and userenv('LANG') in (LANGUAGE, SOURCE_LANG);

  if (sql%notfound) then
    raise no_data_found;
  end if;
end UPDATE_ROW;

procedure DELETE_ROW (
  X_SEGMENT_ID in NUMBER
) is
begin
  delete from QP_SEGMENTS_TL
  where SEGMENT_ID = X_SEGMENT_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;

  delete from QP_SEGMENTS_B
  where SEGMENT_ID = X_SEGMENT_ID;

  if (sql%notfound) then
    raise no_data_found;
  end if;
end DELETE_ROW;

procedure ADD_LANGUAGE
is
begin
  delete from QP_SEGMENTS_TL T
  where not exists
    (select NULL
    from QP_SEGMENTS_B B
    where B.SEGMENT_ID = T.SEGMENT_ID
    );

  update QP_SEGMENTS_TL T set (
      SEEDED_SEGMENT_NAME,
      USER_SEGMENT_NAME,
      SEEDED_DESCRIPTION,
      USER_DESCRIPTION
    ) = (select
      B.SEEDED_SEGMENT_NAME,
      B.USER_SEGMENT_NAME,
      B.SEEDED_DESCRIPTION,
      B.USER_DESCRIPTION
    from QP_SEGMENTS_TL B
    where B.SEGMENT_ID = T.SEGMENT_ID
    and B.LANGUAGE = T.SOURCE_LANG)
  where (
      T.SEGMENT_ID,
      T.LANGUAGE
  ) in (select
      SUBT.SEGMENT_ID,
      SUBT.LANGUAGE
    from QP_SEGMENTS_TL SUBB, QP_SEGMENTS_TL SUBT
    where SUBB.SEGMENT_ID = SUBT.SEGMENT_ID
    and SUBB.LANGUAGE = SUBT.SOURCE_LANG
    and (SUBB.SEEDED_SEGMENT_NAME <> SUBT.SEEDED_SEGMENT_NAME
      or (SUBB.SEEDED_SEGMENT_NAME is null and SUBT.SEEDED_SEGMENT_NAME is not null)
      or (SUBB.SEEDED_SEGMENT_NAME is not null and SUBT.SEEDED_SEGMENT_NAME is null)
      or SUBB.USER_SEGMENT_NAME <> SUBT.USER_SEGMENT_NAME
  ));

  insert into QP_SEGMENTS_TL (
    SEGMENT_ID,
    SEEDED_SEGMENT_NAME,
    USER_SEGMENT_NAME,
    SEEDED_DESCRIPTION,
    USER_DESCRIPTION,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    LANGUAGE,
    SOURCE_LANG
  ) select
    B.SEGMENT_ID,
    B.SEEDED_SEGMENT_NAME,
    B.USER_SEGMENT_NAME,
    B.SEEDED_DESCRIPTION,
    B.USER_DESCRIPTION,
    B.CREATED_BY,
    B.CREATION_DATE,
    B.LAST_UPDATED_BY,
    B.LAST_UPDATE_DATE,
    B.LAST_UPDATE_LOGIN,
    L.LANGUAGE_CODE,
    B.SOURCE_LANG
  from QP_SEGMENTS_TL B, FND_LANGUAGES L
  where L.INSTALLED_FLAG in ('I', 'B')
  and B.LANGUAGE = userenv('LANG')
  and not exists
    (select NULL
    from QP_SEGMENTS_TL T
    where T.SEGMENT_ID = B.SEGMENT_ID
    and T.LANGUAGE = L.LANGUAGE_CODE);
end ADD_LANGUAGE;

end QP_SEGMENTS_PKG;

/
