--------------------------------------------------------
--  DDL for Package AK_FLOW_REGION_RELATIONS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AK_FLOW_REGION_RELATIONS_PKG" AUTHID CURRENT_USER as
/* $Header: AKDFRGRS.pls 120.2 2005/09/29 13:59:48 tshort ship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_FROM_REGION_APPL_ID in NUMBER,
  X_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_TO_REGION_APPL_ID in NUMBER,
  X_TO_REGION_CODE in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2
);
procedure LOCK_ROW (
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_FROM_REGION_APPL_ID in NUMBER,
  X_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_TO_REGION_APPL_ID in NUMBER,
  X_TO_REGION_CODE in VARCHAR2,
  X_APPLICATION_ID in NUMBER
);
procedure UPDATE_ROW (
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_FROM_REGION_APPL_ID in NUMBER,
  X_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_TO_REGION_APPL_ID in NUMBER,
  X_TO_REGION_CODE in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2
);
procedure DELETE_ROW (
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_FROM_REGION_APPL_ID in NUMBER,
  X_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_TO_REGION_APPL_ID in NUMBER,
  X_TO_REGION_CODE in VARCHAR2
);
end AK_FLOW_REGION_RELATIONS_PKG;

 

/
