--------------------------------------------------------
--  DDL for Package AK_PAGE_REGION_RELATIONS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AK_PAGE_REGION_RELATIONS_PKG" AUTHID CURRENT_USER as
/* $Header: AKDPRGRS.pls 115.4 2002/01/18 11:35:38 pkm ship      $ */
procedure INSERT_ROW (
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_FROM_REGION_APPL_ID in NUMBER,
  X_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_TO_REGION_APPL_ID in NUMBER,
  X_TO_REGION_CODE in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure LOCK_ROW (
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_OLD_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_OLD_FROM_REGION_APPL_ID in NUMBER,
  X_OLD_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_OLD_TO_REGION_APPL_ID in NUMBER,
  X_OLD_TO_REGION_CODE in VARCHAR2
);
procedure UPDATE_ROW (
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_FOREIGN_KEY_NAME in VARCHAR2,
  X_OLD_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_FROM_REGION_APPL_ID in NUMBER,
  X_FROM_REGION_CODE in VARCHAR2,
  X_OLD_FROM_REGION_APPL_ID in NUMBER,
  X_OLD_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_TO_REGION_APPL_ID in NUMBER,
  X_TO_REGION_CODE in VARCHAR2,
  X_OLD_TO_REGION_APPL_ID in NUMBER,
  X_OLD_TO_REGION_CODE in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_FLOW_APPLICATION_ID in NUMBER,
  X_FLOW_CODE in VARCHAR2,
  X_FOREIGN_KEY_NAME in VARCHAR2,
  X_FROM_PAGE_APPL_ID in NUMBER,
  X_FROM_PAGE_CODE in VARCHAR2,
  X_FROM_REGION_APPL_ID in NUMBER,
  X_FROM_REGION_CODE in VARCHAR2,
  X_TO_PAGE_APPL_ID in NUMBER,
  X_TO_PAGE_CODE in VARCHAR2,
  X_TO_REGION_APPL_ID in NUMBER,
  X_TO_REGION_CODE in VARCHAR2
);
end AK_PAGE_REGION_RELATIONS_PKG;

 

/
