--------------------------------------------------------
--  DDL for Package AMS_STATUS_ORDER_RULES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AMS_STATUS_ORDER_RULES_PKG" AUTHID CURRENT_USER as
/* $Header: amslstss.pls 115.5 2002/11/16 01:44:39 dbiswas ship $ */
procedure INSERT_ROW (
  X_ROWID in OUT NOCOPY VARCHAR2,
  X_STATUS_ORDER_RULE_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SYSTEM_STATUS_TYPE in VARCHAR2,
  X_CURRENT_STATUS_CODE in VARCHAR2,
  X_NEXT_STATUS_CODE in VARCHAR2,
  X_SHOW_IN_LOV_FLAG in VARCHAR2,
  X_THEME_APPROVAL_FLAG in VARCHAR2,
  X_BUDGET_APPROVAL_FLAG in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_APPLICATION_ID in NUMBER DEFAULT '530');
procedure UPDATE_ROW (
  X_STATUS_ORDER_RULE_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SYSTEM_STATUS_TYPE in VARCHAR2,
  X_CURRENT_STATUS_CODE in VARCHAR2,
  X_NEXT_STATUS_CODE in VARCHAR2,
  X_SHOW_IN_LOV_FLAG in VARCHAR2,
  X_THEME_APPROVAL_FLAG in VARCHAR2,
  X_BUDGET_APPROVAL_FLAG in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_APPLICATION_ID in NUMBER DEFAULT '530'
);
procedure DELETE_ROW (
  X_STATUS_ORDER_RULE_ID in NUMBER
);

procedure  LOAD_ROW(
  X_STATUS_ORDER_RULE_ID in NUMBER,
  X_SYSTEM_STATUS_TYPE in VARCHAR2,
  X_CURRENT_STATUS_CODE in VARCHAR2,
  X_NEXT_STATUS_CODE in VARCHAR2,
  X_SHOW_IN_LOV_FLAG in VARCHAR2,
  X_THEME_APPROVAL_FLAG in VARCHAR2,
  X_BUDGET_APPROVAL_FLAG in VARCHAR2,
  X_Owner              VARCHAR2,
  X_APPLICATION_ID in NUMBER DEFAULT '530'
  ) ;


end AMS_STATUS_ORDER_RULES_PKG;

 

/
