--------------------------------------------------------
--  DDL for Package AMS_QUERY_TMP_ASSOC_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AMS_QUERY_TMP_ASSOC_PKG" AUTHID CURRENT_USER as
/* $Header: amstqcas.pls 120.0 2005/06/01 00:32:08 appldev noship $ */
procedure INSERT_ROW (
  X_ASSOC_ID in NUMBER,
  X_TEMPLATE_INSTANCE_ID in NUMBER,
  X_QUERY_CONDITION_ID in NUMBER,
  X_CONDITION_SEQUENCE in NUMBER,
  X_RUNNING_TOTAL in NUMBER,
  X_DELTA in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_REQUEST_ID in NUMBER,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_ASSOC_ID in NUMBER,
  X_TEMPLATE_INSTANCE_ID in NUMBER,
  X_QUERY_CONDITION_ID in NUMBER,
  X_CONDITION_SEQUENCE in NUMBER,
  X_RUNNING_TOTAL in NUMBER,
  X_DELTA in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_REQUEST_ID in NUMBER
);
procedure UPDATE_ROW (
  X_ASSOC_ID in NUMBER,
  X_TEMPLATE_INSTANCE_ID in NUMBER,
  X_QUERY_CONDITION_ID in NUMBER,
  X_CONDITION_SEQUENCE in NUMBER,
  X_RUNNING_TOTAL in NUMBER,
  X_DELTA in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_REQUEST_ID in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_ASSOC_ID in NUMBER
);

PROCEDURE load_row (
  X_ASSOC_ID in NUMBER,
  X_TEMPLATE_INSTANCE_ID in NUMBER,
  X_QUERY_CONDITION_ID in NUMBER,
  X_CONDITION_SEQUENCE in NUMBER,
  X_RUNNING_TOTAL in NUMBER,
  X_DELTA in NUMBER,
  X_REQUEST_ID in NUMBER,
  x_owner IN VARCHAR2,
  x_custom_mode IN VARCHAR2

);

end AMS_QUERY_TMP_ASSOC_PKG;

 

/
