--------------------------------------------------------
--  DDL for Package AMS_CELLS_ALL_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AMS_CELLS_ALL_PKG" AUTHID CURRENT_USER AS
/* $Header: amslcels.pls 115.2 2000/01/09 17:36:45 pkm ship    $ */
procedure INSERT_ROW (
  X_ROWID in out VARCHAR2,
  X_CELL_ID in NUMBER,
  X_OWNER_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_CELL_CODE in VARCHAR2,
  X_MARKET_SEGMENT_FLAG in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_ORIGINAL_SIZE in NUMBER,
  X_PARENT_CELL_ID in NUMBER,
  X_CELL_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_CELL_ID in NUMBER,
  X_OWNER_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_CELL_CODE in VARCHAR2,
  X_MARKET_SEGMENT_FLAG in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_ORIGINAL_SIZE in NUMBER,
  X_PARENT_CELL_ID in NUMBER,
  X_CELL_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2
);
procedure UPDATE_ROW (
  X_CELL_ID in NUMBER,
  X_OWNER_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_CELL_CODE in VARCHAR2,
  X_MARKET_SEGMENT_FLAG in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_ORIGINAL_SIZE in NUMBER,
  X_PARENT_CELL_ID in NUMBER,
  X_CELL_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_CELL_ID in NUMBER
);
procedure ADD_LANGUAGE;

PROCEDURE TRANSLATE_ROW (
   x_cell_id      IN NUMBER,
   x_cell_name    IN VARCHAR2,
   x_description  IN VARCHAR2,
   x_owner        IN VARCHAR2
);

PROCEDURE LOAD_ROW (
  X_CELL_ID in NUMBER,
  X_OWNER_ID in NUMBER,
  X_CELL_CODE in VARCHAR2,
  X_MARKET_SEGMENT_FLAG in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_ORIGINAL_SIZE in NUMBER,
  X_PARENT_CELL_ID in NUMBER,
  X_CELL_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  x_owner         IN VARCHAR2
);

end AMS_CELLS_ALL_PKG;

 

/
