--------------------------------------------------------
--  DDL for Package AMS_MEDIA_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AMS_MEDIA_PKG" AUTHID CURRENT_USER as
/* $Header: amslmdas.pls 115.8 2002/11/20 19:55:10 dbiswas ship $ */
procedure INSERT_ROW (
  X_ROWID in OUT NOCOPY VARCHAR2,
  X_MEDIA_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_MEDIA_TYPE_CODE in VARCHAR2,
  X_INBOUND_FLAG in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_DEDUPE_RULE_ID in VARCHAR2,
  X_MEDIA_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);

procedure UPDATE_ROW (
  X_MEDIA_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_MEDIA_TYPE_CODE in VARCHAR2,
  X_INBOUND_FLAG in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_DEDUPE_RULE_ID in VARCHAR2,
  X_MEDIA_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_MEDIA_ID in NUMBER
);
procedure ADD_LANGUAGE;

procedure TRANSLATE_ROW(
       x_media_id    in NUMBER
     , x_media_name  in VARCHAR2
     , x_description    in VARCHAR2
     , x_owner   in VARCHAR2
 ) ;

 procedure  LOAD_ROW(
  X_MEDIA_ID   IN NUMBER,
  X_MEDIA_TYPE_CODE in VARCHAR2 DEFAULT NULL,
  X_INBOUND_FLAG in VARCHAR2 DEFAULT 'N',
  X_ENABLED_FLAG in VARCHAR2  DEFAULT 'Y',
  X_ATTRIBUTE_CATEGORY in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE1 in VARCHAR2  DEFAULT NULL ,
  X_ATTRIBUTE2 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE3 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE4 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE5 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE6 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE7 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE8 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE9 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE10 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE11 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE12 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE13 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE14 in VARCHAR2  DEFAULT NULL,
  X_ATTRIBUTE15 in VARCHAR2  DEFAULT NULL,
  X_DEDUPE_RULE_ID in VARCHAR2 DEFAULT NULL,
  X_MEDIA_NAME in VARCHAR2  DEFAULT NULL,
  X_DESCRIPTION in VARCHAR2  DEFAULT NULL ,
  X_Owner              VARCHAR2
);

end AMS_MEDIA_PKG;

 

/
