--------------------------------------------------------
--  DDL for Package AMS_MET_TPL_HEADERS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AMS_MET_TPL_HEADERS_PKG" AUTHID CURRENT_USER as
/* $Header: amslmths.pls 115.1 2000/01/09 17:55:08 pkm ship     $ */
procedure INSERT_ROW (
  X_ROWID in out VARCHAR2,
  X_METRIC_TPL_HEADER_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_METRIC_TPL_HEADER_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_ARC_ACT_METRIC_USED_BY in VARCHAR2,
  X_ACT_METRIC_USED_BY_TYPE in VARCHAR2,
  X_ACT_METRIC_USED_BY_SUBTYPE in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);

procedure UPDATE_ROW (
  X_METRIC_TPL_HEADER_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_METRIC_TPL_HEADER_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_ARC_ACT_METRIC_USED_BY in VARCHAR2,
  X_ACT_METRIC_USED_BY_TYPE in VARCHAR2,
  X_ACT_METRIC_USED_BY_SUBTYPE in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);

procedure DELETE_ROW (
  X_METRIC_TPL_HEADER_ID in NUMBER
);

procedure LOAD_ROW (
  X_METRIC_TPL_HEADER_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_METRIC_TPL_HEADER_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_ARC_ACT_METRIC_USED_BY in VARCHAR2,
  X_ACT_METRIC_USED_BY_TYPE in VARCHAR2,
  X_ACT_METRIC_USED_BY_SUBTYPE in VARCHAR2,
  X_Owner              VARCHAR2
  );

end AMS_MET_TPL_HEADERS_PKG;

 

/
