--------------------------------------------------------
--  DDL for Package AP_APXTRSWP_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AP_APXTRSWP_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: APXTRSWPS.pls 120.0 2007/12/27 08:42:09 vjaganat noship $ */
	P_DEBUG_SWITCH	varchar2(1);
	P_CONC_REQUEST_ID	number;
	P_MIN_PRECISION	number;
	P_FLEXDATA	varchar2(600);
	P_SET_OF_BOOKS_ID	number;
	P_TRACE_SWITCH	varchar2(1);
	P_AIP_ORG_WHERE	varchar2(2000);
	P_AC_ORG_WHERE	varchar2(2000);
	P_APH_ORG_WHERE	varchar2(2000);
	P_AI_ORG_WHERE	varchar2(2000);
	P_AID_ORG_WHERE	varchar2(2000);
	P_PH_ORG_WHERE	varchar2(2000);
	P_PLL_ORG_WHERE	varchar2(2000);
	P_SWEEP_NOW	varchar2(1);
	P_SWEEP_NOW_1   varchar2(1);
	P_REPORTING_ENTITY_ID	number;
	P_REPORTING_LEVEL	varchar2(30);
	P_PERIOD_NAME	varchar2(15);
	P_TO_PERIOD	varchar2(15);
	P_FROM_ACCTG_DATE	date;
	P_TO_ACCTG_DATE	date;
	P_entity_name	varchar2(240);
	P_level_name	varchar2(200);
	P_AH_ORG_WHERE	varchar2(2000);
	P_UNACC_TRANS_SWP	varchar2(200);
	P_UNACC_SWP_REV	varchar2(200);
	P_UNACC_TRANS_REP	varchar2(200);
	P_ACCT_METHOD	varchar2(1);
	P_START_DATE	date;
	P_END_DATE	date;
	P_UNACCT_RPT	varchar2(1);
	C_NLS_YES	varchar2(80);
	C_NLS_NO	varchar2(80);
	C_NLS_ALL	varchar2(80);
	C_NLS_NO_DATA_EXISTS	varchar2(240);
	C_NLS_VOID	varchar2(80);
	C_NLS_NA	varchar2(80);
	C_NLS_END_OF_REPORT	varchar2(100);
	C_REPORT_START_DATE	date;
	C_COMPANY_NAME_HEADER	varchar2(50);
	C_BASE_CURRENCY_CODE	varchar2(15);
	C_BASE_PRECISION	number;
	C_BASE_MIN_ACCT_UNIT	number;
	C_BASE_DESCRIPTION	varchar2(240);
	C_CHART_OF_ACCOUNTS_ID	number;
	--Applications Template Report	varchar2(1);
	  Applications_Template_Report	varchar2(1);
	--C_AIP_MULTI_ORG_WHERE	varchar2(2000) := := 'AND 1=1' ;
	  C_AIP_MULTI_ORG_WHERE	varchar2(2000) :=  'AND 1=1' ;
	--C_APH_MULTI_ORG_WHERE	varchar2(2000) := := 'AND 1=1' ;
	  C_APH_MULTI_ORG_WHERE	varchar2(2000) :=  'AND 1=1' ;
	--C_PMTS_MULTI_ORG_WHERE	varchar2(2000) := := 'AND 1=1' ;
	  C_PMTS_MULTI_ORG_WHERE	varchar2(2000) := 'AND 1=1' ;
	--C_INV_MULTI_ORG_WHERE	varchar2(2000) := := 'AND 1=1' ;
	  C_INV_MULTI_ORG_WHERE	varchar2(2000) :=  'AND 1=1' ;
	--C_ORG_FROM_TABLES	varchar2(200) := := 'sys.dual' ;
	  C_ORG_FROM_TABLES	varchar2(200) :=  'sys.dual' ;
	--C_SELECT_LE	varchar2(20) := := ''Legal Entity'' ;
	  C_SELECT_LE	varchar2(20) :=  'Legal Entity' ;
	--C_SELECT_OU	varchar2(20) := := ''Operating Unit'' ;
	  C_SELECT_OU	varchar2(20) :=  'Operating Unit' ;
	C_REP_TITLE	varchar2(50);
	C_SWEEP_TO_DATE	date;
	LEDGER_PART varchar2(3);
	C_ACCRUAL_BASIS_IN_USE	varchar2(1);
	C_FROM_ACCTG_DATE	date;
	C_TO_ACCTG_DATE	date;
	C_APH_ACCTG_DATE	varchar2(45);
	C_SWEEP_NOW	varchar2(80);
	C_DATE_FILTER_INV	varchar2(2000);
	C_DATE_FILTER_PAY	varchar2(2000);
	C_DATE_FILTER_PAYHIST	varchar2(2000);
	C_LEDGER_PARTIAL_OU	varchar2(240);
	FUNCTION  get_base_curr_data  RETURN BOOLEAN  ;
	FUNCTION  custom_init         RETURN BOOLEAN  ;
	FUNCTION  get_cover_page_values   RETURN BOOLEAN  ;
	FUNCTION  get_nls_strings     RETURN BOOLEAN  ;
	function BeforeReport return boolean ;
	function AfterReport return boolean ;
	FUNCTION  get_company_name    RETURN BOOLEAN  ;
	FUNCTION get_flexdata RETURN BOOLEAN  ;
	FUNCTION GET_ORG_PLACEHOLDERS RETURN BOOLEAN  ;
	FUNCTION UPDATE_PO_CLOSE_DATE RETURN BOOLEAN  ;
	FUNCTION UPDATE_ACCTG_DATES RETURN BOOLEAN ;
	FUNCTION GET_ACCTG_DATE RETURN BOOLEAN  ;
	function AfterPForm return boolean  ;
	--FUNCTION GET_ACCRUAL_BAS ;
	  FUNCTION GET_ACCRUAL_BASIS return boolean;
	FUNCTION get_filtered_dates RETURN BOOLEAN  ;
	function g_1_orgsgroupfilter(CO_org_id in number) return boolean  ;
	Function C_NLS_YES_p return varchar2;
	Function C_NLS_NO_p return varchar2;
	Function C_NLS_ALL_p return varchar2;
	Function C_NLS_NO_DATA_EXISTS_p return varchar2;
	Function C_NLS_VOID_p return varchar2;
	Function C_NLS_NA_p return varchar2;
	Function C_NLS_END_OF_REPORT_p return varchar2;
	Function C_REPORT_START_DATE_p return date;
	Function C_COMPANY_NAME_HEADER_p return varchar2;
	Function C_BASE_CURRENCY_CODE_p return varchar2;
	Function C_BASE_PRECISION_p return number;
	Function C_BASE_MIN_ACCT_UNIT_p return number;
	Function C_BASE_DESCRIPTION_p return varchar2;
	Function C_CHART_OF_ACCOUNTS_ID_p return number;
	--Function Applications Template Report_p return varchar2;
	  Function Applications_Template_Report_p return varchar2;
	Function C_AIP_MULTI_ORG_WHERE_p return varchar2;
	Function C_APH_MULTI_ORG_WHERE_p return varchar2;
	Function C_PMTS_MULTI_ORG_WHERE_p return varchar2;
	Function C_INV_MULTI_ORG_WHERE_p return varchar2;
	Function C_ORG_FROM_TABLES_p return varchar2;
	Function C_SELECT_LE_p return varchar2;
	Function C_SELECT_OU_p return varchar2;
	Function C_REP_TITLE_p return varchar2;
	Function C_SWEEP_TO_DATE_p return date;
	Function C_ACCRUAL_BASIS_IN_USE_p return varchar2;
	Function C_FROM_ACCTG_DATE_p return date;
	Function C_TO_ACCTG_DATE_p return date;
	Function C_APH_ACCTG_DATE_p return varchar2;
	Function C_SWEEP_NOW_p return varchar2;
	Function C_DATE_FILTER_INV_p return varchar2;
	Function C_DATE_FILTER_PAY_p return varchar2;
	Function C_DATE_FILTER_PAYHIST_p return varchar2;
	Function C_LEDGER_PARTIAL_OU_p return varchar2;
	function M_G_4_FUTURE_PAY_GRPFRFormatTr(co_org_id number) return varchar2;
	function M_G_5_PAY_BATCH_GRPFRFormatTri(co_org_id number) return varchar2;
	function M_G_6_UNTRANS_ACCT_GRPFRFormat(co_org_id number) return varchar2;
	function M_G_3_UNACCT_PAY_GRPFRFormatTr(co_org_id number) return varchar2;
	function M_G_2_UNACCT_INV_GRPFRFormatTr(co_org_id number) return varchar2;
	function F_END_OF_REPORT1FormatTrigger return number;
END AP_APXTRSWP_XMLP_PKG;



/
