--------------------------------------------------------
--  DDL for Package AP_APXINAGE_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AP_APXINAGE_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: APXINAGES.pls 120.0 2007/12/27 07:48:28 vjaganat noship $ */
	P_DEBUG_SWITCH	varchar2(1);
	P_CONC_REQUEST_ID	number;
	P_MIN_PRECISION	number;
	P_FLEXDATA	varchar2(600);
	P_SET_OF_BOOKS_ID	number;
	P_SORT_OPTION	varchar2(32767);
	P_SORT_OPTION_UPPER	varchar2(32767);
	P_SUMMARY_OPTION	varchar2(15);
	P_FORMAT_OPTION	varchar2(32767);
	P_FORMAT_OPTION_UPPER	varchar2(32767);
	P_AMOUNT_DUE_LOW	number;
	P_AMOUNT_DUE_HIGH	number;
	P_INVOICE_TYPE	varchar2(30);
	P_PARTY_ID	varchar2(30);
	P_PERIOD_TYPE	varchar2(50);
	P_ORDER_BY	varchar2(1000) := ' ';
	P_PARTY_PREDICATE	varchar2(100) := ' ';
	P_TRACE_SWITCH	varchar2(1);
	P_AMT_DUE_LOW	number;
	P_AMT_DUE_HIGH	number;
	P_AMOUNT_PREDICATE	varchar2(200) := ' ';
	SORT_BY_ALTERNATE	varchar2(5);
	C_BASE_CURRENCY_CODE	varchar2(15);
	C_BASE_PRECISION	number;
	C_BASE_MIN_ACCT_UNIT	number;
	C_BASE_DESCRIPTION	varchar2(240);
	C_COMPANY_NAME_HEADER	varchar2(50);
	C_REPORT_START_DATE	date;
	C_NLS_YES	varchar2(80);
	C_NLS_NO	varchar2(80);
	C_NLS_ALL	varchar2(80);
	C_NLS_NO_DATA_EXISTS	varchar2(240);
	C_REPORT_RUN_TIME	varchar2(8);
	C_CHART_OF_ACCOUNTS_ID	number;
	C_VENDOR_NAME_SELECT	varchar2(240);
	C_INVOICE_TYPE_SELECT	varchar2(80);
	C_MINDAYS	number;
	C_MAXDAYS	number;
	C_INV_DUE_1_HEAD_1	varchar2(15);
	C_INV_DUE_1_HEAD_2	varchar2(15);
	C_INV_DUE_2_HEAD_1	varchar2(15);
	C_INV_DUE_2_HEAD_2	varchar2(15);
	C_INV_DUE_3_HEAD_1	varchar2(15);
	C_INV_DUE_3_HEAD_2	varchar2(15);
	C_INV_DUE_4_HEAD_1	varchar2(15);
	C_INV_DUE_4_HEAD_2	varchar2(15);
	C_INV_DUE_1_RANGE_FR	number;
	C_INV_DUE_1_RANGE_TO	number;
	C_INV_DUE_2_RANGE_FR	number;
	C_INV_DUE_2_RANGE_TO	number;
	C_INV_DUE_3_RANGE_FR	number;
	C_INV_DUE_3_RANGE_TO	number;
	C_INV_DUE_4_RANGE_FR	number;
	C_INV_DUE_4_RANGE_TO	number;
	C_HEAD_INVOICE_TYPE	varchar2(80);
	C_HEAD_SORT_OPTION	varchar2(80);
	C_HEAD_VENDOR_NAME	varchar2(240);
	C_REP_DATA_CONVERTED	varchar2(1);
	C_NLS_END_OF_REPORT	varchar2(100);
	C_HEAD_SUMMARY_OPTION	varchar2(80);
	C_HEAD_FORMAT_OPTION	varchar2(80);
	FUNCTION  get_base_curr_data  RETURN BOOLEAN  ;
	FUNCTION  custom_init         RETURN BOOLEAN  ;
	FUNCTION  get_cover_page_values   RETURN BOOLEAN  ;
	FUNCTION  get_nls_strings     RETURN BOOLEAN  ;
	function BeforeReport return boolean ;
	function AfterReport return boolean  ;
	FUNCTION  get_company_name    RETURN BOOLEAN  ;
	FUNCTION get_flexdata RETURN BOOLEAN  ;
	FUNCTION  set_order_by     RETURN BOOLEAN  ;
	FUNCTION  get_period_info     RETURN BOOLEAN  ;
	function c_contact_lineformula(C_CONTACT_SITE_ID in number) return varchar2  ;
	function c_percent_remainingformula(C_AMT_DUE_ORIGINAL in number, C_AMT_DUE_REMAINING in number) return number  ;
	function c_inv_due_amt_1formula(C_DAYS_PAST_DUE in number, C_AMT_DUE_REMAINING in number) return number  ;
	function c_inv_due_amt_2formula(C_DAYS_PAST_DUE in number, C_AMT_DUE_REMAINING in number) return number  ;
	function c_inv_due_amt_3formula(C_DAYS_PAST_DUE in number, C_AMT_DUE_REMAINING in number) return number  ;
	function c_inv_due_amt_4formula(C_DAYS_PAST_DUE in number, C_AMT_DUE_REMAINING in number) return number  ;
	function c_per_v_inv_amt_1formula(C_SUM_V_INV_AMT_1 in number, C_SUM_V_DUE_REMAINING in number) return number  ;
	function c_per_v_inv_amt_2formula(C_SUM_V_INV_AMT_2 in number, C_SUM_V_DUE_REMAINING in number) return number  ;
	function c_per_v_inv_amt_3formula(C_SUM_V_INV_AMT_3 in number, C_SUM_V_DUE_REMAINING in number) return number  ;
	function c_per_v_inv_amt_4formula(C_SUM_V_INV_AMT_4 in number, C_SUM_V_DUE_REMAINING in number) return number  ;
	function c_check_data_convertedformula(C_DATA_CONVERTED in varchar2) return number  ;
	function c_per_inv_due_amt_1formula(C_SUM_INV_DUE_AMT_1 in number, C_SUM_AMT_REMAINING in number) return number  ;
	function c_per_inv_due_amt_2formula(C_SUM_INV_DUE_AMT_2 in number, C_SUM_AMT_REMAINING in number) return number  ;
	function c_per_inv_due_amt_3formula(C_SUM_INV_DUE_AMT_3 in number, C_SUM_AMT_REMAINING in number) return number  ;
	function c_per_inv_due_amt_4formula(C_SUM_INV_DUE_AMT_4 in number, C_SUM_AMT_REMAINING in number) return number  ;
	function c_pgbrk_data_convertedformula(C_SUM_DATA_CONVERTED in number) return varchar2  ;
	function c_v_data_convertedformula(C_SUM_V_DATA_CONVERTED in number) return varchar2  ;
	function c_tot_per_inv_due_1formula(C_TOT_INV_DUE_AMT_1 in number, C_TOT_AMT_REMAINING in number) return number  ;
	function c_tot_per_inv_due_2formula(C_TOT_INV_DUE_AMT_2 in number, C_TOT_AMT_REMAINING in number) return number  ;
	function c_tot_per_inv_due_3formula(C_TOT_INV_DUE_AMT_3 in number, C_TOT_AMT_REMAINING in number) return number  ;
	function c_tot_per_inv_due_4formula(C_TOT_INV_DUE_AMT_4 in number, C_TOT_AMT_REMAINING in number) return number  ;
	Function C_BASE_CURRENCY_CODE_p return varchar2;
	Function C_BASE_PRECISION_p return number;
	Function C_BASE_MIN_ACCT_UNIT_p return number;
	Function C_BASE_DESCRIPTION_p return varchar2;
	Function C_COMPANY_NAME_HEADER_p return varchar2;
	Function C_REPORT_START_DATE_p return date;
	Function C_NLS_YES_p return varchar2;
	Function C_NLS_NO_p return varchar2;
	Function C_NLS_ALL_p return varchar2;
	Function C_NLS_NO_DATA_EXISTS_p return varchar2;
	Function C_REPORT_RUN_TIME_p return varchar2;
	Function C_CHART_OF_ACCOUNTS_ID_p return number;
	Function C_VENDOR_NAME_SELECT_p return varchar2;
	Function C_INVOICE_TYPE_SELECT_p return varchar2;
	Function C_MINDAYS_p return number;
	Function C_MAXDAYS_p return number;
	Function C_INV_DUE_1_HEAD_1_p return varchar2;
	Function C_INV_DUE_1_HEAD_2_p return varchar2;
	Function C_INV_DUE_2_HEAD_1_p return varchar2;
	Function C_INV_DUE_2_HEAD_2_p return varchar2;
	Function C_INV_DUE_3_HEAD_1_p return varchar2;
	Function C_INV_DUE_3_HEAD_2_p return varchar2;
	Function C_INV_DUE_4_HEAD_1_p return varchar2;
	Function C_INV_DUE_4_HEAD_2_p return varchar2;
	Function C_INV_DUE_1_RANGE_FR_p return number;
	Function C_INV_DUE_1_RANGE_TO_p return number;
	Function C_INV_DUE_2_RANGE_FR_p return number;
	Function C_INV_DUE_2_RANGE_TO_p return number;
	Function C_INV_DUE_3_RANGE_FR_p return number;
	Function C_INV_DUE_3_RANGE_TO_p return number;
	Function C_INV_DUE_4_RANGE_FR_p return number;
	Function C_INV_DUE_4_RANGE_TO_p return number;
	Function C_HEAD_INVOICE_TYPE_p return varchar2;
	Function C_HEAD_SORT_OPTION_p return varchar2;
	Function C_HEAD_VENDOR_NAME_p return varchar2;
	Function C_REP_DATA_CONVERTED_p return varchar2;
	Function C_NLS_END_OF_REPORT_p return varchar2;
	Function C_HEAD_SUMMARY_OPTION_p return varchar2;
	Function C_HEAD_FORMAT_OPTION_p return varchar2;
END AP_APXINAGE_XMLP_PKG;


/
