--------------------------------------------------------
--  DDL for Package AP_WEB_VALIDATE_UTIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AP_WEB_VALIDATE_UTIL" AUTHID CURRENT_USER AS
/* $Header: apwvutls.pls 120.16 2006/06/28 20:55:03 abordia ship $ */

PROCEDURE ValidateExpLinesCustomFields(
        p_report_header_info  IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportHeaderRec,
        p_report_lines_info   IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportLines_A,
        p_custom1_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom2_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom3_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom4_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom5_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom6_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom7_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom8_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom9_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom10_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom11_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom12_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom13_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom14_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom15_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_num_max_flex_field  IN NUMBER,
        P_IsSessionTaxEnabled IN VARCHAR2,
        P_IsSessionProjectEnabled IN VARCHAR2,
	p_receipts_count      IN     BINARY_INTEGER,
	p_receipt_errors      IN OUT NOCOPY AP_WEB_UTILITIES_PKG.receipt_error_stack,
	p_receipts_with_errors_count  IN OUT NOCOPY BINARY_INTEGER,
	p_calculate_receipt_index     IN BINARY_INTEGER,
        p_error               IN OUT NOCOPY    AP_WEB_UTILITIES_PKG.expError,
        p_addon_rates                      IN OIE_ADDON_RATES_T DEFAULT NULL,
        p_report_line_id                IN      NUMBER DEFAULT NULL,
        p_daily_breakup_id              IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_start_date                    IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_end_date                      IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_amount                        IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_number_of_meals               IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_meals_amount                  IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_breakfast_flag                IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_lunch_flag                    IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_dinner_flag                   IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_accommodation_amount          IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_accommodation_flag            IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_hotel_name                    IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_Type               IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_amount             IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_rate                      IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_rate_Type_code                IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_pdm_breakup_dest_id           IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_destination_id            IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_dest_start_date               IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_dest_end_date                 IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_location_id                   IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_cust_meals_amount             IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_accommodation_amount     IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_night_rate_amount        IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_pdm_rate                 IN OUT  NOCOPY OIE_PDM_NUMBER_T

	);


PROCEDURE ValidateApprover(p_employee_id in varchar2,
                             p_approverName in out nocopy varchar2,
                             p_approverID  in out nocopy varchar2,
                             p_ap_error out nocopy varchar2
                             );

PROCEDURE ValidateCostCenter(p_costcenter in AP_EXPENSE_FEED_DISTS.cost_center%TYPE,
                             p_cs_error out nocopy varchar2,
                             p_employee_id  in  number default null);


PROCEDURE ValidateExpLine(
    	p_userId		      	        IN 	NUMBER,
        p_report_header_info  IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportHeaderRec,
        p_report_line_info   IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportLineRec,
        p_custom1_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom2_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom3_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom4_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom5_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom6_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom7_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom8_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom9_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom10_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom11_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom12_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom13_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom14_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom15_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_has_core_field_errors     OUT NOCOPY BOOLEAN,
        p_has_custom_field_errors     OUT NOCOPY BOOLEAN,
	p_receipts_errors     		IN OUT NOCOPY AP_WEB_UTILITIES_PKG.receipt_error_stack,
	p_receipts_with_errors_count  	IN OUT NOCOPY BINARY_INTEGER,
        p_IsSessionProjectEnabled  	IN VARCHAR2,
	p_receipt_index			IN BINARY_INTEGER,
        p_calculate_receipt_index      	IN BINARY_INTEGER DEFAULT NULL,
	p_bCalling_from_disconnected    IN BOOLEAN,
        p_addon_rates                      IN OIE_ADDON_RATES_T DEFAULT NULL,
        p_report_line_id                IN      NUMBER DEFAULT NULL,
        p_daily_breakup_id              IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_start_date                    IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_end_date                      IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_amount                        IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_number_of_meals               IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_meals_amount                  IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_breakfast_flag                IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_lunch_flag                    IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_dinner_flag                   IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_accommodation_amount          IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_accommodation_flag            IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_hotel_name                    IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_Type               IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_amount             IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_rate                      IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_rate_Type_code                IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_pdm_breakup_dest_id           IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_destination_id            IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_dest_start_date               IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_dest_end_date                 IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_location_id                   IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_cust_meals_amount             IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_accommodation_amount     IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_night_rate_amount        IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_pdm_rate                 IN OUT  NOCOPY OIE_PDM_NUMBER_T

);

PROCEDURE ValidateExpLines(
    	p_userId	      IN 	NUMBER,
        p_report_header_info  IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportHeaderRec,
        p_report_line_info   IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportLines_A,
        p_custom1_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom2_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom3_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom4_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom5_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom6_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom7_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom8_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom9_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom10_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom11_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom12_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom13_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom14_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom15_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_has_core_field_errors   OUT NOCOPY BOOLEAN,
        p_has_custom_field_errors OUT NOCOPY BOOLEAN,
        p_receipts_errors            IN OUT NOCOPY AP_WEB_UTILITIES_PKG.receipt_error_stack,
        p_receipts_with_errors_count IN OUT NOCOPY BINARY_INTEGER,
        p_IsSessionProjectEnabled       IN VARCHAR2,
        p_calculate_receipt_index       IN BINARY_INTEGER DEFAULT NULL,
	p_bCalling_from_disconnected    IN BOOLEAN,
        p_addon_rates                      IN OIE_ADDON_RATES_T DEFAULT NULL,
        p_report_line_id                IN      NUMBER DEFAULT NULL,
        p_daily_breakup_id              IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_start_date                    IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_end_date                      IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_amount                        IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_number_of_meals               IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_meals_amount                  IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_breakfast_flag                IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_lunch_flag                    IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_dinner_flag                   IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_accommodation_amount          IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_accommodation_flag            IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_hotel_name                    IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_Type               IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_amount             IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_rate                      IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_rate_Type_code                IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_pdm_breakup_dest_id           IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_destination_id            IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_dest_start_date               IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_dest_end_date                 IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_location_id                   IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_cust_meals_amount             IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_accommodation_amount     IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_night_rate_amount        IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_pdm_rate                 IN OUT  NOCOPY OIE_PDM_NUMBER_T
);

FUNCTION IsReceiptRequired
        (p_require_receipt_amount number,
        p_amount varchar2,
        p_reimb_curr varchar2,
        p_base_currency varchar2) RETURN BOOLEAN;

PROCEDURE ValidateReportHeader(
	ExpReportHeaderInfo IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportHeaderRec,
	p_error             IN OUT NOCOPY    	AP_WEB_UTILITIES_PKG.expError);

PROCEDURE ValidateHeaderNoValidSession(
        p_user_id           IN          NUMBER, -- 2242176
	ExpReportHeaderInfo IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportHeaderRec,
	p_error             IN OUT NOCOPY    	AP_WEB_UTILITIES_PKG.expError,
	p_bFull_Approver_Validation  IN BOOLEAN);


PROCEDURE ValidateExpLineCoreFields(
        p_user_id               IN NUMBER, -- 2242176
	p_report_header_info 	IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportHeaderRec,
        p_report_line_info  	IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportLineRec,
	p_receiptcount 		IN NUMBER,
	p_allow_credit_lines	IN BOOLEAN,
	p_justreq_array		IN AP_WEB_PARENT_PKG.Number_Array,
	p_reimbcurr_precision	IN FND_CURRENCIES_VL.PRECISION%TYPE,
	p_calculate_receipt_index  IN BINARY_INTEGER,
	p_exp_error		IN OUT NOCOPY AP_WEB_UTILITIES_PKG.expError);

PROCEDURE ValidateExpLineCustomFields(
    	p_userId	      IN 	NUMBER,
        p_report_header_info  IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportHeaderRec,
        p_report_line_info   IN OUT NOCOPY AP_WEB_DFLEX_PKG.ExpReportLineRec,
	p_receipt_index	      IN INTEGER,
	p_SysInfoRec	      IN AP_WEB_DB_AP_INT_PKG.APSysInfoRec,
	p_DefaultExchangeRate IN NUMBER,
	p_EndExpenseDate      IN DATE,
	p_DateFormat	      IN VARCHAR2,
        p_custom1_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom2_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom3_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom4_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom5_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom6_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom7_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom8_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom9_array       IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom10_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom11_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom12_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom13_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom14_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        p_custom15_array      IN OUT NOCOPY AP_WEB_DFLEX_PKG.CustomFields_A,
        P_IsSessionTaxEnabled IN VARCHAR2,
        P_IsSessionProjectEnabled IN VARCHAR2,
	p_receipt_errors      IN OUT NOCOPY AP_WEB_UTILITIES_PKG.receipt_error_stack,
	p_calculate_receipt_index     IN BINARY_INTEGER,
        p_errors               IN OUT NOCOPY  AP_WEB_UTILITIES_PKG.expError,
	p_receipts_with_errors_count  IN OUT NOCOPY BINARY_INTEGER,
	p_DataDefaultedUpdateable     IN OUT NOCOPY BOOLEAN,
	p_bCalling_from_disconnected  IN BOOLEAN,
	p_bForBlueGray		      IN BOOLEAN DEFAULT FALSE,
        p_addon_rates                      IN OIE_ADDON_RATES_T DEFAULT NULL,
        p_report_line_id                IN      NUMBER DEFAULT NULL,
        p_daily_breakup_id              IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_start_date                    IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_end_date                      IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_amount                        IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_number_of_meals               IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_meals_amount                  IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_breakfast_flag                IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_lunch_flag                    IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_dinner_flag                   IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_accommodation_amount          IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_accommodation_flag            IN      OIE_PDM_VARCHAR_1_T DEFAULT NULL,
        p_hotel_name                    IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_Type               IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_night_rate_amount             IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_rate                      IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_rate_Type_code                IN      OIE_PDM_VARCHAR_80_T DEFAULT NULL,
        p_pdm_breakup_dest_id           IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_pdm_destination_id            IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_dest_start_date               IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_dest_end_date                 IN      OIE_PDM_DATE_T DEFAULT NULL,
        p_location_id                   IN      OIE_PDM_NUMBER_T DEFAULT NULL,
        p_cust_meals_amount             IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_accommodation_amount     IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_night_rate_amount        IN OUT  NOCOPY OIE_PDM_NUMBER_T,
        p_cust_pdm_rate                 IN OUT  NOCOPY OIE_PDM_NUMBER_T
);

PROCEDURE MapColumnToCustomFields(
  p_userId           IN      NUMBER,
  P_ReceiptIndex     IN      NUMBER,
  Attribute_Array    IN      AP_WEB_PARENT_PKG.BigString_Array,
  ExpReportLinesInfo IN OUT NOCOPY  AP_WEB_DFLEX_PKG.ExpReportLines_A,
  Custom1_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom2_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom3_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom4_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom5_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom6_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom7_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom8_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom9_Array      IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom10_Array     IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom11_Array     IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom12_Array     IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom13_Array     IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom14_Array     IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A,
  Custom15_Array     IN OUT NOCOPY  AP_WEB_DFLEX_PKG.CustomFields_A);



END AP_WEB_VALIDATE_UTIL;

 

/
