--------------------------------------------------------
--  DDL for Package AR_ARHLERPT_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AR_ARHLERPT_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: ARHLERPTS.pls 120.0 2008/01/24 14:46:12 dwkrishn noship $ */

   P_ORIG_SYS VARCHAR2(40);

  P_BATCH_ID NUMBER;

  P_BATCH_NAME VARCHAR2(255);

  P_CRE_DT DATE;

  P_CRE_DT1 VARCHAR2(30);

  P_TOT_REC_IMP NUMBER;

  P_TOT_B_REC NUMBER;

  P_LOAD_TYPE VARCHAR2(30);

  P_CONC_REQUEST_ID NUMBER;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

END AR_ARHLERPT_XMLP_PKG;

/
