--------------------------------------------------------
--  DDL for Package AR_ARBRATBR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AR_ARBRATBR_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: ARBRATBRS.pls 120.0 2007/12/27 13:17:10 abraghun noship $ */
  P_VERSION VARCHAR2(32767);

  P_BATCH NUMBER;

  P_REQUEST_ID NUMBER;

  P_SET_OF_BOOKS_ID NUMBER;

  P_CONC_REQUEST_ID NUMBER;

  CP_SOB VARCHAR2(30);

  CP_PRECISION NUMBER;

  CP_FUNC_CURR VARCHAR2(20);

  CP_VERSION VARCHAR2(20);

  CP_REQUEST_ID NUMBER;

  CP_BATCH_NAME VARCHAR2(50);

  CP_BATCH_STATUS VARCHAR2(80);

  CP_DUE_DATE_LOW VARCHAR2(21);

  CP_DUE_DATE_HIGH VARCHAR2(21);

  CP_TRX_DATE_LOW VARCHAR2(21);

  CP_TRX_DATE_HIGH VARCHAR2(21);

  CP_TRX_NUMBER_LOW VARCHAR2(255);

  CP_TRX_NUMBER_HIGH VARCHAR2(255);

  CP_PAYMENT_METHOD VARCHAR2(30);

  CP_ISSUE_DATE VARCHAR2(21);

  CP_CUSTOMER_CLASS VARCHAR2(80);

  CP_CUSTOMER_CATEGORY VARCHAR2(80);

  CP_CUSTOMER_NAME VARCHAR2(50);

  CP_CUSTOMER_NUMBER VARCHAR2(30);

  CP_LOCATION VARCHAR2(40);

  CP_BANK_NAME VARCHAR2(80);

  CP_TRX_TYPE VARCHAR2(20);

  CP_CURRENCY_CODE VARCHAR2(15);

  CP_SOURCE VARCHAR2(50);

  FUNCTION CF_MATURITY_DATEFORMULA(MATURITY_DATE IN DATE) RETURN CHAR;

  FUNCTION CF_SYSDATEFORMULA RETURN CHAR;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_TRX_DATEFORMULA(TRX_DATE IN DATE) RETURN CHAR;

  FUNCTION CF_FUNC_AMT_ASSIGNEDFORMULA(EXCHANGE_RATE IN NUMBER
                                      ,AMOUNT_ASSIGNED IN NUMBER) RETURN NUMBER;

  FUNCTION CF_REPORT_TITLEFORMULA RETURN CHAR;

  FUNCTION CF_DUE_DATE_LOWFORMULA RETURN CHAR;

  FUNCTION CF_DUE_DATE_HIGHFORMULA RETURN CHAR;

  FUNCTION CF_TRX_DATE_LOWFORMULA RETURN CHAR;

  FUNCTION CF_TRX_DATE_HIGHFORMULA RETURN CHAR;

  FUNCTION CF_ISSUE_DATEFORMULA RETURN CHAR;

  FUNCTION CP_SOB_P RETURN VARCHAR2;

  FUNCTION CP_PRECISION_P RETURN NUMBER;

  FUNCTION CP_FUNC_CURR_P RETURN VARCHAR2;

  FUNCTION CP_VERSION_P RETURN VARCHAR2;

  FUNCTION CP_REQUEST_ID_P RETURN NUMBER;

  FUNCTION CP_BATCH_NAME_P RETURN VARCHAR2;

  FUNCTION CP_BATCH_STATUS_P RETURN VARCHAR2;

  FUNCTION CP_DUE_DATE_LOW_P RETURN VARCHAR2;

  FUNCTION CP_DUE_DATE_HIGH_P RETURN VARCHAR2;

  FUNCTION CP_TRX_DATE_LOW_P RETURN VARCHAR2;

  FUNCTION CP_TRX_DATE_HIGH_P RETURN VARCHAR2;

  FUNCTION CP_TRX_NUMBER_LOW_P RETURN VARCHAR2;

  FUNCTION CP_TRX_NUMBER_HIGH_P RETURN VARCHAR2;

  FUNCTION CP_PAYMENT_METHOD_P RETURN VARCHAR2;

  FUNCTION CP_ISSUE_DATE_P RETURN VARCHAR2;

  FUNCTION CP_CUSTOMER_CLASS_P RETURN VARCHAR2;

  FUNCTION CP_CUSTOMER_CATEGORY_P RETURN VARCHAR2;

  FUNCTION CP_CUSTOMER_NAME_P RETURN VARCHAR2;

  FUNCTION CP_CUSTOMER_NUMBER_P RETURN VARCHAR2;

  FUNCTION CP_LOCATION_P RETURN VARCHAR2;

  FUNCTION CP_BANK_NAME_P RETURN VARCHAR2;

  FUNCTION CP_TRX_TYPE_P RETURN VARCHAR2;

  FUNCTION CP_CURRENCY_CODE_P RETURN VARCHAR2;

  FUNCTION CP_SOURCE_P RETURN VARCHAR2;

END AR_ARBRATBR_XMLP_PKG;


/
