--------------------------------------------------------
--  DDL for Package AR_ARXRBRD_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AR_ARXRBRD_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: ARXRBRDS.pls 120.0 2007/12/27 14:03:32 abraghun noship $ */
  P_BANK_ACCOUNT_NAME VARCHAR2(25);

  P_BNK_BRANCH_ID VARCHAR2(40);

  LP_BANK_ACCOUNT VARCHAR2(100);

  P_CONC_REQUEST_ID NUMBER := 0;

  C_FUNCTIONAL_CURRENCY VARCHAR2(3);

  C_COMPANY_NAME VARCHAR2(50);

  C_NO_DATA_MESSAGE VARCHAR2(2000);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION C_FUNCTIONAL_CURRENCY_P RETURN VARCHAR2;

  FUNCTION C_COMPANY_NAME_P RETURN VARCHAR2;

  FUNCTION C_NO_DATA_MESSAGE_P RETURN VARCHAR2;

END AR_ARXRBRD_XMLP_PKG;


/
