--------------------------------------------------------
--  DDL for Package AR_BPA_DATASRC_VIEWS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."AR_BPA_DATASRC_VIEWS_PKG" AUTHID CURRENT_USER as
/* $Header: ARBPDSVS.pls 120.2 2005/10/30 04:13:29 appldev noship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_DATA_SOURCE_ID in NUMBER,
  X_OBJECT_TYPE in VARCHAR2,
  X_OBJECT_NAME in VARCHAR2,
  X_VO_USAGE_NAME in VARCHAR2,
  X_VO_USAGE_FULL_NAME in VARCHAR2,
  X_VO_INIT_SEQUENCE in NUMBER,
  X_DISPLAY_LEVEL in VARCHAR2,
  X_LINK_TO_DATA_SOURCE_ID in NUMBER,
  X_INVOICED_LINE_ACCTG_LEVEL in VARCHAR2,
  X_TAX_SOURCE_FLAG in VARCHAR2,
  X_SOURCE_LINE_TYPE in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_DATASRC_VIEW_NAME in VARCHAR2,
  X_DATASRC_VIEW_DESC in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);

procedure LOCK_ROW (
  X_DATA_SOURCE_ID in NUMBER,
  X_OBJECT_TYPE in VARCHAR2,
  X_OBJECT_NAME in VARCHAR2,
  X_VO_USAGE_NAME in VARCHAR2,
  X_VO_USAGE_FULL_NAME in VARCHAR2,
  X_VO_INIT_SEQUENCE in NUMBER,
  X_DISPLAY_LEVEL in VARCHAR2,
  X_LINK_TO_DATA_SOURCE_ID in NUMBER,
  X_INVOICED_LINE_ACCTG_LEVEL in VARCHAR2,
  X_TAX_SOURCE_FLAG in VARCHAR2,
  X_SOURCE_LINE_TYPE in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_DATASRC_VIEW_NAME in VARCHAR2,
  X_DATASRC_VIEW_DESC in VARCHAR2
);

procedure UPDATE_ROW (
  X_DATA_SOURCE_ID in NUMBER,
  X_OBJECT_TYPE in VARCHAR2,
  X_OBJECT_NAME in VARCHAR2,
  X_VO_USAGE_NAME in VARCHAR2,
  X_VO_USAGE_FULL_NAME in VARCHAR2,
  X_VO_INIT_SEQUENCE in NUMBER,
  X_DISPLAY_LEVEL in VARCHAR2,
  X_LINK_TO_DATA_SOURCE_ID in NUMBER,
  X_INVOICED_LINE_ACCTG_LEVEL in VARCHAR2,
  X_TAX_SOURCE_FLAG in VARCHAR2,
  X_SOURCE_LINE_TYPE in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_DATASRC_VIEW_NAME in VARCHAR2,
  X_DATASRC_VIEW_DESC in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);

procedure DELETE_ROW (
  X_DATA_SOURCE_ID in NUMBER
);

procedure ADD_LANGUAGE;

procedure TRANSLATE_ROW (
  X_DATA_SOURCE_ID in NUMBER,
  X_DATASRC_VIEW_NAME in VARCHAR2,
  X_DATASRC_VIEW_DESC in VARCHAR2,
  X_OWNER in VARCHAR2
);

procedure LOAD_ROW (
  X_DATA_SOURCE_ID in NUMBER,
  X_OBJECT_TYPE in VARCHAR2,
  X_OBJECT_NAME in VARCHAR2,
  X_VO_USAGE_NAME in VARCHAR2,
  X_VO_USAGE_FULL_NAME in VARCHAR2,
  X_VO_INIT_SEQUENCE in NUMBER,
  X_DISPLAY_LEVEL in VARCHAR2,
  X_LINK_TO_DATA_SOURCE_ID in NUMBER,
  X_INVOICED_LINE_ACCTG_LEVEL in VARCHAR2,
  X_TAX_SOURCE_FLAG in VARCHAR2,
  X_SOURCE_LINE_TYPE in VARCHAR2,
  X_ENABLED_FLAG in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_DATASRC_VIEW_NAME in VARCHAR2,
  X_DATASRC_VIEW_DESC in VARCHAR2,
  X_OWNER IN VARCHAR2
);
end AR_BPA_DATASRC_VIEWS_PKG;

 

/
