--------------------------------------------------------
--  DDL for Package BEN_ABS_LER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."BEN_ABS_LER" AUTHID CURRENT_USER as
/*$Header: beabatrg.pkh 115.8 2003/12/18 03:01:09 hmani ship $*/
TYPE g_abs_ler_rec is RECORD
(PERSON_ID NUMBER
,BUSINESS_GROUP_ID NUMBER
,DATE_START DATE
,DATE_END DATE
,ABSENCE_ATTENDANCE_TYPE_ID NUMBER
,ABS_ATTENDANCE_REASON_ID  NUMBER
,ABSENCE_ATTENDANCE_ID NUMBER
--
-- ABSENCES : New columns
--
 ,AUTHORISING_PERSON_ID    NUMBER(10)
 ,REPLACEMENT_PERSON_ID    NUMBER(10)
 ,PERIOD_OF_INCAPACITY_ID  NUMBER(9)
 ,ABSENCE_DAYS             NUMBER(9,4)
 ,ABSENCE_HOURS            NUMBER(9,4)
 ,DATE_NOTIFICATION        DATE
 ,DATE_PROJECTED_END       DATE
 ,DATE_PROJECTED_START     DATE
 ,OCCURRENCE               NUMBER(15)
 ,SSP1_ISSUED              VARCHAR2(30)
 ,TIME_END                 VARCHAR2(5)
 ,TIME_PROJECTED_END       VARCHAR2(5)
 ,TIME_PROJECTED_START     VARCHAR2(5)
 ,TIME_START               VARCHAR2(5)
 ,ATTRIBUTE_CATEGORY       VARCHAR2(30)
 ,ATTRIBUTE1               VARCHAR2(150)
 ,ATTRIBUTE2               VARCHAR2(150)
 ,ATTRIBUTE3               VARCHAR2(150)
 ,ATTRIBUTE4               VARCHAR2(150)
 ,ATTRIBUTE5               VARCHAR2(150)
 ,ATTRIBUTE6               VARCHAR2(150)
 ,ATTRIBUTE7               VARCHAR2(150)
 ,ATTRIBUTE8               VARCHAR2(150)
 ,ATTRIBUTE9               VARCHAR2(150)
 ,ATTRIBUTE10               VARCHAR2(150)
 ,ATTRIBUTE11               VARCHAR2(150)
 ,ATTRIBUTE12               VARCHAR2(150)
 ,ATTRIBUTE13               VARCHAR2(150)
 ,ATTRIBUTE14               VARCHAR2(150)
 ,ATTRIBUTE15               VARCHAR2(150)
 ,ATTRIBUTE16               VARCHAR2(150)
 ,ATTRIBUTE17               VARCHAR2(150)
 ,ATTRIBUTE18               VARCHAR2(150)
 ,ATTRIBUTE19               VARCHAR2(150)
 ,ATTRIBUTE20               VARCHAR2(150)
 ,MATERNITY_ID              NUMBER
 ,SICKNESS_START_DATE       DATE
 ,SICKNESS_END_DATE         DATE
 ,PREGNANCY_RELATED_ILLNESS        VARCHAR2(30)
 ,REASON_FOR_NOTIFICATION_DELAY    VARCHAR2(2000)
 ,ACCEPT_LATE_NOTIFICATION_FLAG    VARCHAR2(30)
 ,LINKED_ABSENCE_ID                NUMBER
 ,BATCH_ID    NUMBER(9)
 ,ABS_INFORMATION_CATEGORY    VARCHAR2(30)
 ,ABS_INFORMATION1    VARCHAR2(150)
 ,ABS_INFORMATION2    VARCHAR2(150)
 ,ABS_INFORMATION3    VARCHAR2(150)
 ,ABS_INFORMATION4    VARCHAR2(150)
 ,ABS_INFORMATION5    VARCHAR2(150)
 ,ABS_INFORMATION6    VARCHAR2(150)
 ,ABS_INFORMATION7    VARCHAR2(150)
 ,ABS_INFORMATION8    VARCHAR2(150)
 ,ABS_INFORMATION9    VARCHAR2(150)
 ,ABS_INFORMATION10    VARCHAR2(150)
 ,ABS_INFORMATION11    VARCHAR2(150)
 ,ABS_INFORMATION12    VARCHAR2(150)
 ,ABS_INFORMATION13    VARCHAR2(150)
 ,ABS_INFORMATION14    VARCHAR2(150)
 ,ABS_INFORMATION15    VARCHAR2(150)
 ,ABS_INFORMATION16    VARCHAR2(150)
 ,ABS_INFORMATION17    VARCHAR2(150)
 ,ABS_INFORMATION18    VARCHAR2(150)
 ,ABS_INFORMATION19    VARCHAR2(150)
 ,ABS_INFORMATION20    VARCHAR2(150)
 ,ABS_INFORMATION21    VARCHAR2(150)
 ,ABS_INFORMATION22    VARCHAR2(150)
 ,ABS_INFORMATION23    VARCHAR2(150)
 ,ABS_INFORMATION24    VARCHAR2(150)
 ,ABS_INFORMATION25    VARCHAR2(150)
 ,ABS_INFORMATION26    VARCHAR2(150)
 ,ABS_INFORMATION27    VARCHAR2(150)
 ,ABS_INFORMATION28    VARCHAR2(150)
 ,ABS_INFORMATION29    VARCHAR2(150)
 ,ABS_INFORMATION30    VARCHAR2(150)
);

procedure ler_chk(p_old IN g_abs_ler_rec
                 ,p_new IN g_abs_ler_rec
                 ,p_effective_date in date default null );
end;

 

/
