--------------------------------------------------------
--  DDL for Package BNE_VIEWERS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."BNE_VIEWERS_PKG" AUTHID CURRENT_USER as
/* $Header: bneviews.pls 120.3 2005/08/18 06:39:08 dagroves noship $ */

procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_APPLICATION_ID in NUMBER,
  X_VIEWER_CODE in VARCHAR2,
  X_PARAM_LIST_APP_ID in NUMBER,
  X_PARAM_LIST_CODE in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_VIEWER_JAVA_CLASS in VARCHAR2,
  X_USER_NAME in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_CREATE_DOC_LIST_APP_ID in NUMBER DEFAULT NULL,
  X_CREATE_DOC_LIST_CODE in VARCHAR2 DEFAULT NULL,
  X_ENABLED_FLAG in VARCHAR2 DEFAULT NULL
);
procedure LOCK_ROW (
  X_APPLICATION_ID in NUMBER,
  X_VIEWER_CODE in VARCHAR2,
  X_PARAM_LIST_APP_ID in NUMBER,
  X_PARAM_LIST_CODE in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_VIEWER_JAVA_CLASS in VARCHAR2,
  X_USER_NAME in VARCHAR2,
  X_CREATE_DOC_LIST_APP_ID in NUMBER DEFAULT NULL,
  X_CREATE_DOC_LIST_CODE in VARCHAR2 DEFAULT NULL,
  X_ENABLED_FLAG in VARCHAR2 DEFAULT NULL
);
procedure UPDATE_ROW (
  X_APPLICATION_ID in NUMBER,
  X_VIEWER_CODE in VARCHAR2,
  X_PARAM_LIST_APP_ID in NUMBER,
  X_PARAM_LIST_CODE in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_VIEWER_JAVA_CLASS in VARCHAR2,
  X_USER_NAME in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_CREATE_DOC_LIST_APP_ID in NUMBER DEFAULT NULL,
  X_CREATE_DOC_LIST_CODE in VARCHAR2 DEFAULT NULL,
  X_ENABLED_FLAG in VARCHAR2 DEFAULT NULL
);
procedure DELETE_ROW (
  X_APPLICATION_ID in NUMBER,
  X_VIEWER_CODE in VARCHAR2
);
procedure ADD_LANGUAGE;
procedure LOAD_ROW(
  x_viewer_asn            IN VARCHAR2,
  x_viewer_code           IN VARCHAR2,
  x_object_version_number IN VARCHAR2,
  x_viewer_java_class     IN VARCHAR2,
  x_param_list_asn        IN VARCHAR2,
  x_param_list_code       IN VARCHAR2,
  x_user_name             IN VARCHAR2,
  x_owner                 IN VARCHAR2,
  x_last_update_date      IN VARCHAR2,
  x_custom_mode           IN VARCHAR2,
  x_create_doc_list_asn   in VARCHAR2 DEFAULT NULL,
  x_create_doc_list_code  in VARCHAR2 DEFAULT NULL,
  x_enabled_flag          in VARCHAR2 DEFAULT NULL
);
procedure TRANSLATE_ROW(
  x_viewer_asn            IN VARCHAR2,
  x_viewer_code           IN VARCHAR2,
  x_user_name             IN VARCHAR2,
  x_owner                 IN VARCHAR2,
  x_last_update_date      IN VARCHAR2,
  x_custom_mode           IN VARCHAR2
);

end BNE_VIEWERS_PKG;

 

/
