--------------------------------------------------------
--  DDL for Package BOM_CSTRACTC_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."BOM_CSTRACTC_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CSTRACTCS.pls 120.0 2007/12/24 09:51:32 dwkrishn noship $ */
  P_ORG_ID NUMBER;

  P_CURRENCY_CODE VARCHAR2(15);

  P_RPT_TYPE VARCHAR2(40);

  P_DEPT_FROM VARCHAR2(10);

  P_DEPT_TO VARCHAR2(10);

  P_MAINT_ITEM_FROM VARCHAR2(800);

  P_MAINT_ITEM_TO VARCHAR2(800);

  P_MAINT_UNIT_FROM VARCHAR2(30);

  P_MAINT_UNIT_TO VARCHAR2(30);

  P_PERIOD_DATE_FROM DATE;

  P_PERIOD_DATE_TO DATE;

  P_PERIOD_ID_FROM NUMBER;

  P_PERIOD_ID_TO NUMBER;

  P_MAINT_UNIT_AI_WHERE VARCHAR2(2400);

  P_MAINT_ITEM_WHERE VARCHAR2(2400) := 'and 1 =1 ';

  P_DEPT_WHERE VARCHAR2(2400) := ' ';

  P_PERIOD_WHERE VARCHAR2(2400) := 'and 1 =1 ';

  P_ORG_NAME VARCHAR2(240);

  P_MAINT_ITEM VARCHAR2(2400);

  P_CURRENCY_DSP VARCHAR2(40);

  P_ROUND_UNIT NUMBER;

  P_EXCHANGE_RATE NUMBER;

  P_EXCHANGE_RATE_CHAR VARCHAR2(32767);

  P_CONC_REQUEST_ID NUMBER;

  P_ITEM_TYPE NUMBER;

  P_MAINT_UNIT_RI_WHERE VARCHAR2(2400) := 'and 1 =1 ';

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

END BOM_CSTRACTC_XMLP_PKG;


/
