--------------------------------------------------------
--  DDL for Package BOM_CSTRPDSS_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."BOM_CSTRPDSS_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CSTRPDSSS.pls 120.0 2007/12/24 10:12:42 dwkrishn noship $ */
  P_ACCT_TO VARCHAR2(900);

  P_ACCT_FROM VARCHAR2(900);

  P_SORT_ID NUMBER;

  PLEX_ACCOUNT_WHERE VARCHAR2(2000);

  P_ITEM_STRUCT_NUM NUMBER;

  PLEX_ACCOUNT_FLEX VARCHAR2(2000);

  PLEX_ITEM_FLEX VARCHAR2(2000) := ' ';

  P_CONC_REQUEST_ID NUMBER;

  P_WIP NUMBER;

  P_COST_GROUP_ID NUMBER;

  P_COST_TYPE_ID NUMBER;

  P_PERIOD_ID NUMBER;

  P_GL_STRUCT_NUM NUMBER;

  P_SORT_OPTION VARCHAR2(2000) := '(TO_CHAR(3))';

  P_MAT_TABLE_FROM VARCHAR2(200);

  P_MAT_WHERE VARCHAR2(300) := ' ';

  P_RCV_TABLE_FROM VARCHAR2(200);

  P_RCV_WHERE VARCHAR2(300);

  P_QUANTITY_PRECISION NUMBER;

  CP_RESPONSIBILITY VARCHAR2(200);

  CP_REQUEST_TIME VARCHAR2(30);

  CP_APPLICATION VARCHAR2(240);

  CP_REQUESTED_BY VARCHAR2(100);

  CP_LEGAL_ENTITY VARCHAR2(240);

  CP_ACCT_ID NUMBER;

  CP_COST_GROUP VARCHAR2(32767);

  CP_COST_TYPE VARCHAR2(32767);

  R_CURRENCY_CODE VARCHAR2(17);

  CP_PERIOD_NAME VARCHAR2(15);

  CP_PRECISION NUMBER;

  QTY_PRECISION varchar2(50);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION C_item(C_item_field_p varchar2) RETURN varchar2;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION C_ACCT_PADFORMULA(C_ACCT_PAD IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  --PROCEDURE FORMAT_QUANTITY(P_PRECISION IN NUMBER);

  FUNCTION CF_NET_ACTIVITY_RFORMULA(NET_ACTIVITY IN NUMBER) RETURN NUMBER;

  FUNCTION CF_SUM_CREDITS_RFORMULA(SUM_CREDITS IN NUMBER) RETURN NUMBER;

  FUNCTION CF_SUM_DEBITS_RFORMULA(SUM_DEBITS IN NUMBER) RETURN NUMBER;

  FUNCTION CF_ACCT_TOT_RFORMULA(C_ACCT_TOT IN NUMBER) RETURN NUMBER;

  FUNCTION CF_CR_ACCT_TOT_RFORMULA(C_CR_ACCT_TOT IN NUMBER) RETURN NUMBER;

  FUNCTION CF_DR_ACCT_TOT_RFORMULA(C_DR_ACCT_TOT IN NUMBER) RETURN NUMBER;

  FUNCTION CF_CR_TOT_RFORMULA(C_CR_TOT IN NUMBER) RETURN NUMBER;

  FUNCTION CF_DR_TOT_RFORMULA(C_DR_TOT IN NUMBER) RETURN NUMBER;

  FUNCTION CF_REPORT_TOT_RFORMULA(C_REPORT_TOT IN NUMBER) RETURN NUMBER;

  FUNCTION CP_RESPONSIBILITY_P RETURN VARCHAR2;

  FUNCTION CP_REQUEST_TIME_P RETURN VARCHAR2;

  FUNCTION CP_APPLICATION_P RETURN VARCHAR2;

  FUNCTION CP_REQUESTED_BY_P RETURN VARCHAR2;

  FUNCTION CP_LEGAL_ENTITY_P RETURN VARCHAR2;

  FUNCTION CP_ACCT_ID_P RETURN NUMBER;

  FUNCTION CP_COST_GROUP_P RETURN VARCHAR2;

  FUNCTION CP_COST_TYPE_P RETURN VARCHAR2;

  FUNCTION R_CURRENCY_CODE_P RETURN VARCHAR2;

  FUNCTION CP_PERIOD_NAME_P RETURN VARCHAR2;

  FUNCTION CP_PRECISION_P RETURN NUMBER;

END BOM_CSTRPDSS_XMLP_PKG;


/
