--------------------------------------------------------
--  DDL for Package CE_CEZBAERR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CE_CEZBAERR_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CEZBAERRS.pls 120.0 2007/12/28 07:58:45 abraghun noship $ */
  P_BANK_BRANCH_ID NUMBER;

  P_BANK_ACCOUNT_ID NUMBER;

  P_STAT_DATE_FROM DATE;

  P_STAT_DATE_TO DATE;

  P_STAT_NUMBER_FROM VARCHAR2(40);
  LP_STAT_DATE_FROM VARCHAR2(11);

  P_STAT_NUMBER_TO VARCHAR2(40);
  LP_STAT_DATE_TO VARCHAR2(11);

  P_CONC_REQUEST_ID NUMBER := 0;

  P_DEBUG_MODE VARCHAR2(1);

  P_MIN_PRECISION NUMBER;

  P_SET_OF_BOOKS_ID NUMBER;

  P_SQL_TRACE VARCHAR2(1);

  C_BANK_ACCOUNT_NUM_DSP VARCHAR2(60);

  C_BANK_ACCOUNT_NAME_DSP VARCHAR2(60);

  C_BANK_BRANCH_NAME_DSP VARCHAR2(60);

  C_BANK_NAME_DSP VARCHAR2(60);

  C_BANK_CURRENCY_CODE_DSP VARCHAR2(60);

  C_BASE_CURRENCY_CODE_DSP VARCHAR2(20);

  C_COMPANY_NAME_HEADER VARCHAR2(60);

  C_ALL_TRANSLATION VARCHAR2(60);

  C_THE_END VARCHAR2(1) := 'N';

  C_PROFILE VARCHAR2(20);

  FUNCTION C_PRT_MESSAGE_NAMEFORMULA(MESSAGE_NAME IN VARCHAR2) RETURN CHAR;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION G_STATEMENT_NOGROUPFILTER(STATEMENT_DATE IN DATE) RETURN BOOLEAN;

  FUNCTION CF_LINE_COUNTFORMULA(BREAK_GROUP IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_1FORMULA(BREAK_GROUP IN VARCHAR2) RETURN CHAR;

  FUNCTION C_DATEFORMATFORMULA(C_DATEFORMAT IN VARCHAR2) RETURN CHAR;

  FUNCTION C_BANK_ACCOUNT_NUM_DSP_P RETURN VARCHAR2;

  FUNCTION C_BANK_ACCOUNT_NAME_DSP_P RETURN VARCHAR2;

  FUNCTION C_BANK_BRANCH_NAME_DSP_P RETURN VARCHAR2;

  FUNCTION C_BANK_NAME_DSP_P RETURN VARCHAR2;

  FUNCTION C_BANK_CURRENCY_CODE_DSP_P RETURN VARCHAR2;

  FUNCTION C_BASE_CURRENCY_CODE_DSP_P RETURN VARCHAR2;

  FUNCTION C_COMPANY_NAME_HEADER_P RETURN VARCHAR2;

  FUNCTION C_ALL_TRANSLATION_P RETURN VARCHAR2;

  FUNCTION C_THE_END_P RETURN VARCHAR2;

  FUNCTION C_PROFILE_P RETURN VARCHAR2;

  PROCEDURE SET_NAME(APPLICATION IN VARCHAR2
                    ,NAME IN VARCHAR2);

  /*PROCEDURE SET_TOKEN(TOKEN IN VARCHAR2
                     ,VALUE IN VARCHAR2
                     ,TRANSLATE IN BOOLEAN);*/

  /*PROCEDURE RETRIEVE(MSGOUT OUT NOCOPY VARCHAR2);*/

  /*PROCEDURE CLEAR;*/

  /*FUNCTION GET_STRING(APPIN IN VARCHAR2
                     ,NAMEIN IN VARCHAR2) RETURN VARCHAR2;*/

  /*FUNCTION GET_NUMBER(APPIN IN VARCHAR2
                     ,NAMEIN IN VARCHAR2) RETURN NUMBER;*/

  FUNCTION GET RETURN VARCHAR2;

  /*FUNCTION GET_ENCODED RETURN VARCHAR2;*/

  /*PROCEDURE PARSE_ENCODED(ENCODED_MESSAGE IN VARCHAR2
                         ,APP_SHORT_NAME OUT NOCOPY VARCHAR2
                         ,MESSAGE_NAME OUT NOCOPY VARCHAR2);*/

  PROCEDURE SET_ENCODED(ENCODED_MESSAGE IN VARCHAR2);

  /*PROCEDURE RAISE_ERROR;*/

  /*PROCEDURE DEBUG(LINE IN VARCHAR2);*/

  /*PROCEDURE ENABLE_DEBUG;*/

  /*PROCEDURE DISABLE_DEBUG;*/

  PROCEDURE INIT_SECURITY;

  FUNCTION GET_WINDOW_SESSION_TITLE RETURN VARCHAR2;

  /*FUNCTION GET_EFFECTIVE_DATE(P_BANK_ACCOUNT_ID IN NUMBER
                             ,P_TRX_CODE IN VARCHAR2
                             ,P_RECEIPT_DATE IN DATE) RETURN DATE;*/

END CE_CEZBAERR_XMLP_PKG;


/
