--------------------------------------------------------
--  DDL for Package CE_CEXTRXCD_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CE_CEXTRXCD_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CEXTRXCDS.pls 120.0 2007/12/28 07:58:15 abraghun noship $ */
  P_BANK_ACCOUNT_ID NUMBER;
  P_DEBUG_MODE VARCHAR2(1);
  P_SQL_TRACE VARCHAR2(1);
  P_CONC_REQUEST_ID NUMBER := 0;
  C_THE_END VARCHAR2(1) := 'N';
  C_BANK_ACCOUNT_NAME VARCHAR2(80);
  C_BANK_ACCOUNT_NUM VARCHAR2(80);
  C_BANK_NAME VARCHAR2(80);
  C_BANK_BRANCH_NAME VARCHAR2(80);
  C_BANK_CURRENCY_CODE VARCHAR2(80);
  C_COMPANY_NAME_HEADER VARCHAR2(80);
  FUNCTION BEFOREREPORT RETURN BOOLEAN;
  FUNCTION AFTERREPORT RETURN BOOLEAN;
  FUNCTION G_BANK_ACCOUNTGROUPFILTER(TYPE_DSP IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION C_DATEFORMATFORMULA(C_DATEFORMAT IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION C_THE_END_P RETURN VARCHAR2;
  FUNCTION C_BANK_ACCOUNT_NAME_P RETURN VARCHAR2;
  FUNCTION C_BANK_ACCOUNT_NUM_P RETURN VARCHAR2;
  FUNCTION C_BANK_NAME_P RETURN VARCHAR2;
  FUNCTION C_BANK_BRANCH_NAME_P RETURN VARCHAR2;
  FUNCTION C_BANK_CURRENCY_CODE_P RETURN VARCHAR2;
  FUNCTION C_COMPANY_NAME_HEADER_P RETURN VARCHAR2;
 PROCEDURE SET_NAME(APPLICATION IN VARCHAR2
                    ,NAME IN VARCHAR2);
/*  PROCEDURE SET_TOKEN(TOKEN IN VARCHAR2
                     ,VALUE IN VARCHAR2
                     ,TRANSLATE IN BOOLEAN);
  PROCEDURE RETRIEVE(MSGOUT OUT NOCOPY VARCHAR2);
  PROCEDURE CLEAR;
  FUNCTION GET_STRING(APPIN IN VARCHAR2
                     ,NAMEIN IN VARCHAR2) RETURN VARCHAR2;*/
  FUNCTION GET RETURN VARCHAR2;
/*  FUNCTION GET_ENCODED RETURN VARCHAR2;
  PROCEDURE PARSE_ENCODED(ENCODED_MESSAGE IN VARCHAR2
                         ,APP_SHORT_NAME OUT NOCOPY VARCHAR2
                         ,MESSAGE_NAME OUT NOCOPY VARCHAR2);
  PROCEDURE SET_ENCODED(ENCODED_MESSAGE IN VARCHAR2);
  PROCEDURE RAISE_ERROR;
  PROCEDURE DEBUG(LINE IN VARCHAR2);
  PROCEDURE ENABLE_DEBUG;
  PROCEDURE DISABLE_DEBUG;*/
  PROCEDURE INIT_SECURITY;
/*  FUNCTION GET_WINDOW_SESSION_TITLE RETURN VARCHAR2;
  FUNCTION GET_EFFECTIVE_DATE(P_BANK_ACCOUNT_ID IN NUMBER
                             ,P_TRX_CODE IN VARCHAR2
                             ,P_RECEIPT_DATE IN DATE) RETURN DATE;*/
END CE_CEXTRXCD_XMLP_PKG;


/
