--------------------------------------------------------
--  DDL for Package CN_RATE_SCH_DIMS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CN_RATE_SCH_DIMS_PKG" AUTHID CURRENT_USER AS
/* $Header: cntschds.pls 120.2 2005/10/05 23:27:55 kjayapau ship $ */

procedure INSERT_ROW (
  X_RATE_SCH_DIM_ID       IN OUT NOCOPY CN_RATE_SCH_DIMS.RATE_SCH_DIM_ID%TYPE,
  X_RATE_DIMENSION_ID     IN     CN_RATE_SCH_DIMS.RATE_DIMENSION_ID%TYPE,
  X_RATE_SCHEDULE_ID      IN     CN_RATE_SCH_DIMS.RATE_SCHEDULE_ID%TYPE,
  X_RATE_DIM_SEQUENCE     IN     CN_RATE_SCH_DIMS.RATE_DIM_SEQUENCE%TYPE,
  --R12 MOAC Changes--Start
  X_ORG_ID                IN     CN_RATE_SCH_DIMS.ORG_ID%TYPE, --new
  --R12 MOAC Changes--End
  X_ATTRIBUTE_CATEGORY    IN     CN_RATE_SCH_DIMS.ATTRIBUTE_CATEGORY%TYPE := NULL,
  X_ATTRIBUTE1            IN     CN_RATE_SCH_DIMS.ATTRIBUTE1%TYPE := NULL,
  X_ATTRIBUTE2            IN     CN_RATE_SCH_DIMS.ATTRIBUTE2%TYPE := NULL,
  X_ATTRIBUTE3            IN     CN_RATE_SCH_DIMS.ATTRIBUTE3%TYPE := NULL,
  X_ATTRIBUTE4            IN     CN_RATE_SCH_DIMS.ATTRIBUTE4%TYPE := NULL,
  X_ATTRIBUTE5            IN     CN_RATE_SCH_DIMS.ATTRIBUTE5%TYPE := NULL,
  X_ATTRIBUTE6            IN     CN_RATE_SCH_DIMS.ATTRIBUTE6%TYPE := NULL,
  X_ATTRIBUTE7            IN     CN_RATE_SCH_DIMS.ATTRIBUTE7%TYPE := NULL,
  X_ATTRIBUTE8            IN     CN_RATE_SCH_DIMS.ATTRIBUTE8%TYPE := NULL,
  X_ATTRIBUTE9            IN     CN_RATE_SCH_DIMS.ATTRIBUTE9%TYPE := NULL,
  X_ATTRIBUTE10           IN     CN_RATE_SCH_DIMS.ATTRIBUTE10%TYPE := NULL,
  X_ATTRIBUTE11           IN     CN_RATE_SCH_DIMS.ATTRIBUTE11%TYPE := NULL,
  X_ATTRIBUTE12           IN     CN_RATE_SCH_DIMS.ATTRIBUTE12%TYPE := NULL,
  X_ATTRIBUTE13           IN     CN_RATE_SCH_DIMS.ATTRIBUTE13%TYPE := NULL,
  X_ATTRIBUTE14           IN     CN_RATE_SCH_DIMS.ATTRIBUTE14%TYPE := NULL,
  X_ATTRIBUTE15           IN     CN_RATE_SCH_DIMS.ATTRIBUTE15%TYPE := NULL,
  X_CREATION_DATE         IN     CN_RATE_SCH_DIMS.CREATION_DATE%TYPE    := SYSDATE,
  X_CREATED_BY            IN     CN_RATE_SCH_DIMS.CREATED_BY%TYPE       := FND_GLOBAL.USER_ID,
  X_LAST_UPDATE_DATE      IN     CN_RATE_SCH_DIMS.LAST_UPDATE_DATE%TYPE := SYSDATE,
  X_LAST_UPDATED_BY       IN     CN_RATE_SCH_DIMS.LAST_UPDATED_BY%TYPE  := FND_GLOBAL.USER_ID,
  X_LAST_UPDATE_LOGIN     IN     CN_RATE_SCH_DIMS.LAST_UPDATE_LOGIN%TYPE:= FND_GLOBAL.LOGIN_ID);

procedure LOCK_ROW (
  X_RATE_SCH_DIM_ID       IN     CN_RATE_SCH_DIMS.RATE_SCH_DIM_ID%TYPE,
  X_OBJECT_VERSION_NUMBER IN     CN_RATE_SCH_DIMS.OBJECT_VERSION_NUMBER%TYPE);

procedure UPDATE_ROW (
  X_RATE_SCH_DIM_ID       IN     CN_RATE_SCH_DIMS.RATE_SCH_DIM_ID%TYPE,
  X_RATE_DIMENSION_ID     IN     CN_RATE_SCH_DIMS.RATE_DIMENSION_ID%TYPE  := cn_api.g_miss_num,
  X_RATE_SCHEDULE_ID      IN     CN_RATE_SCH_DIMS.RATE_SCHEDULE_ID%TYPE   := cn_api.g_miss_num,
  X_RATE_DIM_SEQUENCE     IN     CN_RATE_SCH_DIMS.RATE_DIM_SEQUENCE%TYPE  := cn_api.g_miss_num,
  X_ATTRIBUTE_CATEGORY    IN     CN_RATE_SCH_DIMS.ATTRIBUTE_CATEGORY%TYPE := cn_api.g_miss_char,
  X_ATTRIBUTE1            IN     CN_RATE_SCH_DIMS.ATTRIBUTE1%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE2            IN     CN_RATE_SCH_DIMS.ATTRIBUTE2%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE3            IN     CN_RATE_SCH_DIMS.ATTRIBUTE3%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE4            IN     CN_RATE_SCH_DIMS.ATTRIBUTE4%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE5            IN     CN_RATE_SCH_DIMS.ATTRIBUTE5%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE6            IN     CN_RATE_SCH_DIMS.ATTRIBUTE6%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE7            IN     CN_RATE_SCH_DIMS.ATTRIBUTE7%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE8            IN     CN_RATE_SCH_DIMS.ATTRIBUTE8%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE9            IN     CN_RATE_SCH_DIMS.ATTRIBUTE9%TYPE         := cn_api.g_miss_char,
  X_ATTRIBUTE10           IN     CN_RATE_SCH_DIMS.ATTRIBUTE10%TYPE        := cn_api.g_miss_char,
  X_ATTRIBUTE11           IN     CN_RATE_SCH_DIMS.ATTRIBUTE11%TYPE        := cn_api.g_miss_char,
  X_ATTRIBUTE12           IN     CN_RATE_SCH_DIMS.ATTRIBUTE12%TYPE        := cn_api.g_miss_char,
  X_ATTRIBUTE13           IN     CN_RATE_SCH_DIMS.ATTRIBUTE13%TYPE        := cn_api.g_miss_char,
  X_ATTRIBUTE14           IN     CN_RATE_SCH_DIMS.ATTRIBUTE14%TYPE        := cn_api.g_miss_char,
  X_ATTRIBUTE15           IN     CN_RATE_SCH_DIMS.ATTRIBUTE15%TYPE        := cn_api.g_miss_char,
  X_OBJECT_VERSION_NUMBER IN OUT NOCOPY    CN_RATE_SCH_DIMS.OBJECT_VERSION_NUMBER%TYPE,
  X_LAST_UPDATE_DATE      IN     CN_RATE_SCH_DIMS.LAST_UPDATE_DATE%TYPE := SYSDATE,
  X_LAST_UPDATED_BY       IN     CN_RATE_SCH_DIMS.LAST_UPDATED_BY%TYPE  := FND_GLOBAL.USER_ID,
  X_LAST_UPDATE_LOGIN     IN     CN_RATE_SCH_DIMS.LAST_UPDATE_LOGIN%TYPE:= FND_GLOBAL.LOGIN_ID);

procedure DELETE_ROW (
  X_RATE_SCH_DIM_ID       IN     CN_RATE_SCH_DIMS.RATE_SCH_DIM_ID%TYPE);
end CN_RATE_SCH_DIMS_PKG;

 

/
