--------------------------------------------------------
--  DDL for Package CS_CSXSRDET_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CS_CSXSRDET_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CSXSRDETS.pls 120.0 2008/01/24 13:33:47 dwkrishn noship $ */

   P_CUSTOMER_NUM_LOW VARCHAR2(30);

  P_CUSTOMER_NUM_HIGH VARCHAR2(30);

  P_ITEM_LOW VARCHAR2(30);

  P_ITEM_HIGH VARCHAR2(30);

  P_REQUEST_LOW VARCHAR2(30);

  P_REQUEST_HIGH VARCHAR2(30);

  P_TYPE VARCHAR2(30);

  P_INSTALL_LOCATION VARCHAR2(30);

  P_SEVERITY VARCHAR2(30);

  P_URGENCY VARCHAR2(30);

  P_PROBLEM_CODE VARCHAR2(30);

  P_RESOLUTION_CODE VARCHAR2(30);

  P_CLOSED_FLAG VARCHAR2(30);

  P_RETURN VARCHAR2(30);

  P_LOGGED_BY VARCHAR2(30);

  P_ACTIVEWORKFLOW VARCHAR2(30);

  P_STATUS VARCHAR2(30);

  P_CLOSED_DATE DATE;

  P_OWNER VARCHAR2(30);

  LP_CUSTOMER_NUMBER VARCHAR2(300);

  LP_ITEM_NUMBER VARCHAR2(300);

  LP_REQUEST_NUMBER VARCHAR2(300);

  LP_TYPE VARCHAR2(300);

  LP_INSTALL_LOCATION VARCHAR2(300);

  LP_SEVERITY VARCHAR2(300);

  LP_URGENCY VARCHAR2(300);

  LP_PROBLEM_CODE VARCHAR2(300);

  LP_RESOLUTION_CODE VARCHAR2(300);

  LP_CLOSED_FLAG VARCHAR2(300);

  LP_RETURN VARCHAR2(300);

  LP_LOGGEDBY VARCHAR2(300);

  LP_ACTIVE_WORKFLOW VARCHAR2(300);

  LP_STATUS VARCHAR2(300);

  LP_CLOSEDDATE VARCHAR2(300);

  LP_OWNER VARCHAR2(300);

  P_SOB_ID NUMBER;

  P_ORGANIZATION_ID NUMBER;

  P_CONC_REQUEST_ID NUMBER;

  P_ITEM_STRUCT_NUM VARCHAR2(40);

  P_ITEM_WHERE VARCHAR2(200);

  P_FLEX_ITEM_CODE VARCHAR2(800);

  LP_TASK_NOTES_STATUS VARCHAR2(40);

  LP_SR_NOTES_STATUS VARCHAR2(40);

  P_TASK_NOTES_STATUS VARCHAR2(32767);

  P_SR_NOTES_STATUS VARCHAR2(32767);

  P_USER_ID NUMBER;

  RP_REPORT_NAME VARCHAR2(50) := 'Service Request Detail Report';

  RP_COMPANY_NAME VARCHAR2(50);

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION AFTERPARAMFORM RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION RP_REPORT_NAME_P RETURN VARCHAR2;

  FUNCTION RP_COMPANY_NAME_P RETURN VARCHAR2;

 --PROCEDURE PUT(NAME IN VARCHAR2
   --            ,VAL IN VARCHAR2);

 --FUNCTION DEFINED(NAME IN VARCHAR2) RETURN BOOLEAN;

  --PROCEDURE GET(NAME IN VARCHAR2
    --           ,VAL OUT NOCOPY VARCHAR2);

  --FUNCTION VALUE(NAME IN VARCHAR2) RETURN VARCHAR2;

  --FUNCTION VALUE_WNPS(NAME IN VARCHAR2) RETURN VARCHAR2;

  --FUNCTION SAVE_USER(X_NAME IN VARCHAR2
                    --,X_VALUE IN VARCHAR2) RETURN BOOLEAN;

  /*FUNCTION SAVE(X_NAME IN VARCHAR2
               ,X_VALUE IN VARCHAR2
               ,X_LEVEL_NAME IN VARCHAR2
               ,X_LEVEL_VALUE IN VARCHAR2
               ,X_LEVEL_VALUE_APP_ID IN VARCHAR2) RETURN BOOLEAN;*/

  /*PROCEDURE GET_SPECIFIC(NAME_Z IN VARCHAR2
                        ,USER_ID_Z IN NUMBER
                        ,RESPONSIBILITY_ID_Z IN NUMBER
                        ,APPLICATION_ID_Z IN NUMBER
                        ,VAL_Z OUT NOCOPY VARCHAR2
                        ,DEFINED_Z OUT NOCOPY BOOLEAN);*/

/*  FUNCTION VALUE_SPECIFIC(NAME IN VARCHAR2
                         ,USER_ID IN NUMBER
                         ,RESPONSIBILITY_ID IN NUMBER
                         ,APPLICATION_ID IN NUMBER) RETURN VARCHAR2;*/

/*  PROCEDURE INITIALIZE(USER_ID_Z IN NUMBER
                      ,RESPONSIBILITY_ID_Z IN NUMBER
                      ,APPLICATION_ID_Z IN NUMBER
                      ,SITE_ID_Z IN NUMBER);*/

/*  PROCEDURE PUTMULTIPLE(NAMES IN VARCHAR2
                       ,VALS IN VARCHAR2
                       ,NUM IN NUMBER);*/

  PROCEDURE CS_GET_COMPANY_NAME(RP_COMPANY_NAME IN OUT NOCOPY VARCHAR2
                               ,P_SOB_ID IN NUMBER);

  PROCEDURE CS_GET_REPORT_NAME(RP_REPORT_NAME IN OUT NOCOPY VARCHAR2
                              ,P_CONC_REQUEST_ID IN NUMBER
                              ,P_REPORT_NAME IN VARCHAR2);

/*  PROCEDURE GET_P_STRUCT_NUM(P_ITEM_STRUCT_NUM IN OUT NOCOPY VARCHAR2
                            ,RETURN_VALUE IN OUT NOCOPY NUMBER);*/

END CS_CSXSRDET_XMLP_PKG;

/
