--------------------------------------------------------
--  DDL for Package CS_SERVICEREQUEST_VERT_HOOKS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CS_SERVICEREQUEST_VERT_HOOKS" AUTHID CURRENT_USER AS
/* $Header: csvtsrs.pls 115.3 2000/05/19 16:22:18 pkm ship    $ */
PROCEDURE create_servicerequest_post  (
  p_service_request_rec IN     CS_SERVICEREQUEST_PVT.service_request_rec_type
);

PROCEDURE create_servicerequest_pre  (
  p_service_request_rec IN OUT CS_SERVICEREQUEST_PVT.service_request_rec_type
);

--
-- The request_date field in the service_request_rec_type will be ignored for update.
--
PROCEDURE update_servicerequest_post  (
  p_service_request_rec IN     CS_SERVICEREQUEST_PVT.service_request_rec_type,
  p_update_desc_flex    IN     VARCHAR2
);

PROCEDURE UPDATE_SERVICEREQUEST_PRE  (
  p_service_request_rec IN OUT CS_SERVICEREQUEST_PVT.service_request_rec_type,
  p_update_desc_flex    IN OUT VARCHAR2
);

PROCEDURE UPDATE_OWNER_POST  (
P_OWNER_ID			IN     NUMBER,
P_RESOURCE_TYPE			IN     VARCHAR2,
P_AUDIT_COMMENTS			IN     VARCHAR2,
P_CALLED_BY_WORKFLOW			IN     VARCHAR2,
P_WORKFLOW_PROCESS_ID			IN     NUMBER,
P_COMMENTS			IN     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN     VARCHAR2
);

PROCEDURE UPDATE_OWNER_PRE  (
P_OWNER_ID			IN OUT     NUMBER,
P_RESOURCE_TYPE			IN OUT     VARCHAR2,
P_AUDIT_COMMENTS			IN OUT     VARCHAR2,
P_CALLED_BY_WORKFLOW			IN OUT     VARCHAR2,
P_WORKFLOW_PROCESS_ID			IN OUT     NUMBER,
P_COMMENTS			IN OUT     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN OUT     VARCHAR2
);

PROCEDURE UPDATE_SEVERITY_POST  (
P_SEVERITY_ID			IN     NUMBER,
P_SEVERITY			IN     VARCHAR2,
P_AUDIT_COMMENTS			IN     VARCHAR2,
P_COMMENTS			IN     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN     VARCHAR2
);

PROCEDURE UPDATE_SEVERITY_PRE  (
P_SEVERITY_ID			IN OUT     NUMBER,
P_SEVERITY			IN OUT     VARCHAR2,
P_AUDIT_COMMENTS			IN OUT     VARCHAR2,
P_COMMENTS			IN OUT     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN OUT     VARCHAR2
);

PROCEDURE UPDATE_STATUS_POST  (
P_STATUS_ID			IN     NUMBER,
P_STATUS			IN     VARCHAR2,
P_CLOSED_DATE			IN     DATE,
P_AUDIT_COMMENTS			IN     VARCHAR2,
P_CALLED_BY_WORKFLOW			IN     VARCHAR2,
P_WORKFLOW_PROCESS_ID			IN     NUMBER,
P_COMMENTS			IN     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN     VARCHAR2
);

PROCEDURE UPDATE_STATUS_PRE  (
P_STATUS_ID			IN OUT     NUMBER,
P_STATUS			IN OUT     VARCHAR2,
P_CLOSED_DATE			IN OUT     DATE,
P_AUDIT_COMMENTS			IN OUT     VARCHAR2,
P_CALLED_BY_WORKFLOW			IN OUT     VARCHAR2,
P_WORKFLOW_PROCESS_ID			IN OUT     NUMBER,
P_COMMENTS			IN OUT     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN OUT     VARCHAR2
);

PROCEDURE UPDATE_URGENCY_POST  (
P_URGENCY_ID			IN     NUMBER,
P_URGENCY			IN     VARCHAR2,
P_AUDIT_COMMENTS			IN     VARCHAR2,
P_COMMENTS			IN     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN     VARCHAR2
);

PROCEDURE UPDATE_URGENCY_PRE  (
P_URGENCY_ID			IN OUT     NUMBER,
P_URGENCY			IN OUT     VARCHAR2,
P_AUDIT_COMMENTS			IN OUT     VARCHAR2,
P_COMMENTS			IN OUT     VARCHAR2,
P_PUBLIC_COMMENT_FLAG			IN OUT     VARCHAR2
);

END cs_servicerequest_vert_hooks;

 

/
