--------------------------------------------------------
--  DDL for Package CS_TXNGRP_PVT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CS_TXNGRP_PVT" AUTHID CURRENT_USER AS
/* $Header: csctxngs.pls 115.0 99/07/16 08:56:12 porting ship  $ */
  ---------------------------------------------------------------------------
  -- GLOBAL DATASTRUCTURES
  ---------------------------------------------------------------------------
  TYPE TxnGrp_Rec_Type IS RECORD (
    coverage_txn_group_id          NUMBER := NULL,
    offset_duration                NUMBER := NULL,
    offset_period                  CS_COVERAGE_TXN_GROUPS.OFFSET_PERIOD%TYPE := NULL,
    coverage_start_date            CS_COVERAGE_TXN_GROUPS.COVERAGE_START_DATE%TYPE := NULL,
    coverage_end_date              CS_COVERAGE_TXN_GROUPS.COVERAGE_END_DATE%TYPE := NULL,
    price_list_id                  NUMBER := NULL,
    manufacturing_org_id           NUMBER := NULL,
    subinventory_code              CS_COVERAGE_TXN_GROUPS.SUBINVENTORY_CODE%TYPE := NULL,
    coverage_id                    NUMBER := NULL,
    discount_id                    NUMBER := NULL,
    business_process_id            NUMBER := NULL,
    sunday_end_time                CS_COVERAGE_TXN_GROUPS.SUNDAY_END_TIME%TYPE := NULL,
    sunday_start_time              CS_COVERAGE_TXN_GROUPS.SUNDAY_START_TIME%TYPE := NULL,
    monday_start_time              CS_COVERAGE_TXN_GROUPS.MONDAY_START_TIME%TYPE := NULL,
    monday_end_time                CS_COVERAGE_TXN_GROUPS.MONDAY_END_TIME%TYPE := NULL,
    tuesday_start_time             CS_COVERAGE_TXN_GROUPS.TUESDAY_START_TIME%TYPE := NULL,
    tuesday_end_time               CS_COVERAGE_TXN_GROUPS.TUESDAY_END_TIME%TYPE := NULL,
    wednesday_start_time           CS_COVERAGE_TXN_GROUPS.WEDNESDAY_START_TIME%TYPE := NULL,
    wednesday_end_time             CS_COVERAGE_TXN_GROUPS.WEDNESDAY_END_TIME%TYPE := NULL,
    thursday_start_time            CS_COVERAGE_TXN_GROUPS.THURSDAY_START_TIME%TYPE := NULL,
    thursday_end_time              CS_COVERAGE_TXN_GROUPS.THURSDAY_END_TIME%TYPE := NULL,
    friday_start_time              CS_COVERAGE_TXN_GROUPS.FRIDAY_START_TIME%TYPE := NULL,
    friday_end_time                CS_COVERAGE_TXN_GROUPS.FRIDAY_END_TIME%TYPE := NULL,
    saturday_start_time            CS_COVERAGE_TXN_GROUPS.SATURDAY_START_TIME%TYPE := NULL,
    saturday_end_time              CS_COVERAGE_TXN_GROUPS.SATURDAY_END_TIME%TYPE := NULL,
    preferred_engineer1            CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER1%TYPE := NULL,
    time_zone_id                   NUMBER := NULL,
    preferred_engineer2            CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER2%TYPE := NULL,
    last_update_date               CS_COVERAGE_TXN_GROUPS.LAST_UPDATE_DATE%TYPE := NULL,
    last_updated_by                NUMBER := NULL,
    creation_date                  CS_COVERAGE_TXN_GROUPS.CREATION_DATE%TYPE := NULL,
    created_by                     NUMBER := NULL,
    last_update_login              NUMBER := NULL,
    attribute1                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE1%TYPE := NULL,
    attribute2                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE2%TYPE := NULL,
    attribute3                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE3%TYPE := NULL,
    attribute4                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE4%TYPE := NULL,
    attribute5                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE5%TYPE := NULL,
    attribute6                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE6%TYPE := NULL,
    attribute7                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE7%TYPE := NULL,
    attribute8                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE8%TYPE := NULL,
    attribute9                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE9%TYPE := NULL,
    attribute10                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE10%TYPE := NULL,
    attribute11                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE11%TYPE := NULL,
    attribute12                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE12%TYPE := NULL,
    attribute13                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE13%TYPE := NULL,
    attribute14                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE14%TYPE := NULL,
    attribute15                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE15%TYPE := NULL,
    context                        CS_COVERAGE_TXN_GROUPS.CONTEXT%TYPE := NULL,
    object_version_number          NUMBER := NULL);
  G_MISS_txngrp_rec                       TxnGrp_Rec_Type;
  TYPE TxnGrp_Val_Rec_Type IS RECORD (
    coverage_txn_group_id          NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    offset_duration                NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    offset_period                  CS_COVERAGE_TXN_GROUPS.OFFSET_PERIOD%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    coverage_start_date            CS_COVERAGE_TXN_GROUPS.COVERAGE_START_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    coverage_end_date              CS_COVERAGE_TXN_GROUPS.COVERAGE_END_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    price_list_id                  NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    manufacturing_org_id           NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    subinventory_code              CS_COVERAGE_TXN_GROUPS.SUBINVENTORY_CODE%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    coverage_id                    NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    discount_id                    NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    business_process_id            NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    sunday_end_time                CS_COVERAGE_TXN_GROUPS.SUNDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    sunday_start_time              CS_COVERAGE_TXN_GROUPS.SUNDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    monday_start_time              CS_COVERAGE_TXN_GROUPS.MONDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    monday_end_time                CS_COVERAGE_TXN_GROUPS.MONDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    tuesday_start_time             CS_COVERAGE_TXN_GROUPS.TUESDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    tuesday_end_time               CS_COVERAGE_TXN_GROUPS.TUESDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    wednesday_start_time           CS_COVERAGE_TXN_GROUPS.WEDNESDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    wednesday_end_time             CS_COVERAGE_TXN_GROUPS.WEDNESDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    thursday_start_time            CS_COVERAGE_TXN_GROUPS.THURSDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    thursday_end_time              CS_COVERAGE_TXN_GROUPS.THURSDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    friday_start_time              CS_COVERAGE_TXN_GROUPS.FRIDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    friday_end_time                CS_COVERAGE_TXN_GROUPS.FRIDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    saturday_start_time            CS_COVERAGE_TXN_GROUPS.SATURDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    saturday_end_time              CS_COVERAGE_TXN_GROUPS.SATURDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    preferred_engineer1            CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER1%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    time_zone_id                   NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    preferred_engineer2            CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER2%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    last_update_date               CS_COVERAGE_TXN_GROUPS.LAST_UPDATE_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    last_updated_by                NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    creation_date                  CS_COVERAGE_TXN_GROUPS.CREATION_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    created_by                     NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    last_update_login              NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    attribute1                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE1%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute2                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE2%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute3                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE3%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute4                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE4%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute5                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE5%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute6                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE6%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute7                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE7%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute8                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE8%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute9                     CS_COVERAGE_TXN_GROUPS.ATTRIBUTE9%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute10                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE10%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute11                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE11%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute12                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE12%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute13                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE13%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute14                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE14%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    attribute15                    CS_COVERAGE_TXN_GROUPS.ATTRIBUTE15%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    context                        CS_COVERAGE_TXN_GROUPS.CONTEXT%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    object_version_number          NUMBER := TAPI_DEV_KIT.G_MISS_NUM);
  G_MISS_txngrp_val_rec                   TxnGrp_Val_Rec_Type;
  ---------------------------------------------------------------------------
  -- GLOBAL MESSAGE CONSTANTS
  ---------------------------------------------------------------------------
  G_FND_APP			CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_FND_APP;
  G_FORM_UNABLE_TO_RESERVE_REC	CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_FORM_UNABLE_TO_RESERVE_REC;
  G_FORM_RECORD_DELETED		CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_FORM_RECORD_DELETED;
  G_FORM_RECORD_CHANGED		CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_FORM_RECORD_CHANGED;
  G_RECORD_LOGICALLY_DELETED	CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_RECORD_LOGICALLY_DELETED;
  G_REQUIRED_VALUE		CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_REQUIRED_VALUE;
  G_INVALID_VALUE			CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_INVALID_VALUE;
  G_COL_NAME_TOKEN		CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_COL_NAME_TOKEN;
  G_PARENT_TABLE_TOKEN		CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_PARENT_TABLE_TOKEN;
  G_CHILD_TABLE_TOKEN		CONSTANT VARCHAR2(200) := TAPI_DEV_KIT.G_CHILD_TABLE_TOKEN;
  ---------------------------------------------------------------------------
  -- GLOBAL VARIABLES
  ---------------------------------------------------------------------------
  G_PKG_NAME			CONSTANT	VARCHAR2(200) := 'CS_TXNGRP_PVT';
  G_APP_NAME			CONSTANT 	VARCHAR2(3) :=  TAPI_DEV_KIT.G_APP_NAME;
  ---------------------------------------------------------------------------
  -- Procedures and Functions
  ---------------------------------------------------------------------------

  PROCEDURE insert_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_txngrp_rec                   IN TxnGrp_Rec_Type := G_MISS_TXNGRP_REC,
    x_coverage_txn_group_id        OUT NUMBER,
    x_object_version_number        OUT NUMBER);
  PROCEDURE insert_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_offset_duration              IN NUMBER := NULL,
    p_offset_period                IN CS_COVERAGE_TXN_GROUPS.OFFSET_PERIOD%TYPE := NULL,
    p_coverage_start_date          IN CS_COVERAGE_TXN_GROUPS.COVERAGE_START_DATE%TYPE := NULL,
    p_coverage_end_date            IN CS_COVERAGE_TXN_GROUPS.COVERAGE_END_DATE%TYPE := NULL,
    p_price_list_id                IN NUMBER := NULL,
    p_manufacturing_org_id         IN NUMBER := NULL,
    p_subinventory_code            IN CS_COVERAGE_TXN_GROUPS.SUBINVENTORY_CODE%TYPE := NULL,
    p_coverage_id                  IN NUMBER := NULL,
    p_discount_id                  IN NUMBER := NULL,
    p_business_process_id          IN NUMBER := NULL,
    p_sunday_end_time              IN CS_COVERAGE_TXN_GROUPS.SUNDAY_END_TIME%TYPE := NULL,
    p_sunday_start_time            IN CS_COVERAGE_TXN_GROUPS.SUNDAY_START_TIME%TYPE := NULL,
    p_monday_start_time            IN CS_COVERAGE_TXN_GROUPS.MONDAY_START_TIME%TYPE := NULL,
    p_monday_end_time              IN CS_COVERAGE_TXN_GROUPS.MONDAY_END_TIME%TYPE := NULL,
    p_tuesday_start_time           IN CS_COVERAGE_TXN_GROUPS.TUESDAY_START_TIME%TYPE := NULL,
    p_tuesday_end_time             IN CS_COVERAGE_TXN_GROUPS.TUESDAY_END_TIME%TYPE := NULL,
    p_wednesday_start_time         IN CS_COVERAGE_TXN_GROUPS.WEDNESDAY_START_TIME%TYPE := NULL,
    p_wednesday_end_time           IN CS_COVERAGE_TXN_GROUPS.WEDNESDAY_END_TIME%TYPE := NULL,
    p_thursday_start_time          IN CS_COVERAGE_TXN_GROUPS.THURSDAY_START_TIME%TYPE := NULL,
    p_thursday_end_time            IN CS_COVERAGE_TXN_GROUPS.THURSDAY_END_TIME%TYPE := NULL,
    p_friday_start_time            IN CS_COVERAGE_TXN_GROUPS.FRIDAY_START_TIME%TYPE := NULL,
    p_friday_end_time              IN CS_COVERAGE_TXN_GROUPS.FRIDAY_END_TIME%TYPE := NULL,
    p_saturday_start_time          IN CS_COVERAGE_TXN_GROUPS.SATURDAY_START_TIME%TYPE := NULL,
    p_saturday_end_time            IN CS_COVERAGE_TXN_GROUPS.SATURDAY_END_TIME%TYPE := NULL,
    p_preferred_engineer1          IN CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER1%TYPE := NULL,
    p_time_zone_id                 IN NUMBER := NULL,
    p_preferred_engineer2          IN CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER2%TYPE := NULL,
    p_last_update_date             IN CS_COVERAGE_TXN_GROUPS.LAST_UPDATE_DATE%TYPE := NULL,
    p_last_updated_by              IN NUMBER := NULL,
    p_creation_date                IN CS_COVERAGE_TXN_GROUPS.CREATION_DATE%TYPE := NULL,
    p_created_by                   IN NUMBER := NULL,
    p_last_update_login            IN NUMBER := NULL,
    p_attribute1                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE1%TYPE := NULL,
    p_attribute2                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE2%TYPE := NULL,
    p_attribute3                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE3%TYPE := NULL,
    p_attribute4                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE4%TYPE := NULL,
    p_attribute5                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE5%TYPE := NULL,
    p_attribute6                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE6%TYPE := NULL,
    p_attribute7                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE7%TYPE := NULL,
    p_attribute8                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE8%TYPE := NULL,
    p_attribute9                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE9%TYPE := NULL,
    p_attribute10                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE10%TYPE := NULL,
    p_attribute11                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE11%TYPE := NULL,
    p_attribute12                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE12%TYPE := NULL,
    p_attribute13                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE13%TYPE := NULL,
    p_attribute14                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE14%TYPE := NULL,
    p_attribute15                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE15%TYPE := NULL,
    p_context                      IN CS_COVERAGE_TXN_GROUPS.CONTEXT%TYPE := NULL,
    p_object_version_number        IN NUMBER := NULL,
    x_coverage_txn_group_id        OUT NUMBER,
    x_object_version_number        OUT NUMBER);
  Procedure lock_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_coverage_txn_group_id        IN NUMBER,
    p_object_version_number        IN NUMBER);
  Procedure update_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_txngrp_val_rec               IN TxnGrp_Val_Rec_Type := G_MISS_TXNGRP_VAL_REC,
    x_object_version_number        OUT NUMBER);
  Procedure update_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_coverage_txn_group_id        IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_offset_duration              IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_offset_period                IN CS_COVERAGE_TXN_GROUPS.OFFSET_PERIOD%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_coverage_start_date          IN CS_COVERAGE_TXN_GROUPS.COVERAGE_START_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_coverage_end_date            IN CS_COVERAGE_TXN_GROUPS.COVERAGE_END_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_price_list_id                IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_manufacturing_org_id         IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_subinventory_code            IN CS_COVERAGE_TXN_GROUPS.SUBINVENTORY_CODE%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_coverage_id                  IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_discount_id                  IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_business_process_id          IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_sunday_end_time              IN CS_COVERAGE_TXN_GROUPS.SUNDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_sunday_start_time            IN CS_COVERAGE_TXN_GROUPS.SUNDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_monday_start_time            IN CS_COVERAGE_TXN_GROUPS.MONDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_monday_end_time              IN CS_COVERAGE_TXN_GROUPS.MONDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_tuesday_start_time           IN CS_COVERAGE_TXN_GROUPS.TUESDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_tuesday_end_time             IN CS_COVERAGE_TXN_GROUPS.TUESDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_wednesday_start_time         IN CS_COVERAGE_TXN_GROUPS.WEDNESDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_wednesday_end_time           IN CS_COVERAGE_TXN_GROUPS.WEDNESDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_thursday_start_time          IN CS_COVERAGE_TXN_GROUPS.THURSDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_thursday_end_time            IN CS_COVERAGE_TXN_GROUPS.THURSDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_friday_start_time            IN CS_COVERAGE_TXN_GROUPS.FRIDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_friday_end_time              IN CS_COVERAGE_TXN_GROUPS.FRIDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_saturday_start_time          IN CS_COVERAGE_TXN_GROUPS.SATURDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_saturday_end_time            IN CS_COVERAGE_TXN_GROUPS.SATURDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_preferred_engineer1          IN CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER1%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_time_zone_id                 IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_preferred_engineer2          IN CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER2%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_last_update_date             IN CS_COVERAGE_TXN_GROUPS.LAST_UPDATE_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_last_updated_by              IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_creation_date                IN CS_COVERAGE_TXN_GROUPS.CREATION_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_created_by                   IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_last_update_login            IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_attribute1                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE1%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute2                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE2%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute3                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE3%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute4                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE4%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute5                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE5%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute6                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE6%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute7                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE7%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute8                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE8%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute9                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE9%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute10                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE10%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute11                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE11%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute12                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE12%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute13                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE13%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute14                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE14%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute15                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE15%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_context                      IN CS_COVERAGE_TXN_GROUPS.CONTEXT%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_object_version_number        IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    x_object_version_number        OUT NUMBER);
  Procedure delete_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_coverage_txn_group_id        IN NUMBER);
  PROCEDURE validate_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_txngrp_val_rec               IN TxnGrp_Val_Rec_Type := G_MISS_TXNGRP_VAL_REC);
  PROCEDURE validate_row
  (
    p_api_version                  IN NUMBER,
    p_init_msg_list                IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    p_validation_level             IN NUMBER,
    p_commit                       IN VARCHAR2 := TAPI_DEV_KIT.G_FALSE,
    x_return_status                OUT VARCHAR2,
    x_msg_count                    OUT NUMBER,
    x_msg_data                     OUT VARCHAR2,
    p_coverage_txn_group_id        IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_offset_duration              IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_offset_period                IN CS_COVERAGE_TXN_GROUPS.OFFSET_PERIOD%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_coverage_start_date          IN CS_COVERAGE_TXN_GROUPS.COVERAGE_START_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_coverage_end_date            IN CS_COVERAGE_TXN_GROUPS.COVERAGE_END_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_price_list_id                IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_manufacturing_org_id         IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_subinventory_code            IN CS_COVERAGE_TXN_GROUPS.SUBINVENTORY_CODE%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_coverage_id                  IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_discount_id                  IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_business_process_id          IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_sunday_end_time              IN CS_COVERAGE_TXN_GROUPS.SUNDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_sunday_start_time            IN CS_COVERAGE_TXN_GROUPS.SUNDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_monday_start_time            IN CS_COVERAGE_TXN_GROUPS.MONDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_monday_end_time              IN CS_COVERAGE_TXN_GROUPS.MONDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_tuesday_start_time           IN CS_COVERAGE_TXN_GROUPS.TUESDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_tuesday_end_time             IN CS_COVERAGE_TXN_GROUPS.TUESDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_wednesday_start_time         IN CS_COVERAGE_TXN_GROUPS.WEDNESDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_wednesday_end_time           IN CS_COVERAGE_TXN_GROUPS.WEDNESDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_thursday_start_time          IN CS_COVERAGE_TXN_GROUPS.THURSDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_thursday_end_time            IN CS_COVERAGE_TXN_GROUPS.THURSDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_friday_start_time            IN CS_COVERAGE_TXN_GROUPS.FRIDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_friday_end_time              IN CS_COVERAGE_TXN_GROUPS.FRIDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_saturday_start_time          IN CS_COVERAGE_TXN_GROUPS.SATURDAY_START_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_saturday_end_time            IN CS_COVERAGE_TXN_GROUPS.SATURDAY_END_TIME%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_preferred_engineer1          IN CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER1%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_time_zone_id                 IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_preferred_engineer2          IN CS_COVERAGE_TXN_GROUPS.PREFERRED_ENGINEER2%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_last_update_date             IN CS_COVERAGE_TXN_GROUPS.LAST_UPDATE_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_last_updated_by              IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_creation_date                IN CS_COVERAGE_TXN_GROUPS.CREATION_DATE%TYPE := TAPI_DEV_KIT.G_MISS_DATE,
    p_created_by                   IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_last_update_login            IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM,
    p_attribute1                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE1%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute2                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE2%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute3                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE3%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute4                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE4%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute5                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE5%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute6                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE6%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute7                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE7%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute8                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE8%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute9                   IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE9%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute10                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE10%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute11                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE11%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute12                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE12%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute13                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE13%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute14                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE14%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_attribute15                  IN CS_COVERAGE_TXN_GROUPS.ATTRIBUTE15%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_context                      IN CS_COVERAGE_TXN_GROUPS.CONTEXT%TYPE := TAPI_DEV_KIT.G_MISS_CHAR,
    p_object_version_number        IN NUMBER := TAPI_DEV_KIT.G_MISS_NUM);
END CS_TXNGRP_PVT;

 

/
