--------------------------------------------------------
--  DDL for Package CSE_CSELOSDR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CSE_CSELOSDR_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CSELOSDRS.pls 120.0 2007/12/24 12:56:51 nchinnam noship $ */
  P_ORGANIZATION_NAME VARCHAR2(60);

  P_PROJECT_NUMBER VARCHAR2(40);

  P_TASK_NUMBER VARCHAR2(40);

  P_INV_ITEM VARCHAR2(40);

  P_REPORT_TYPE VARCHAR2(30);

  P_DAY NUMBER;

  P_TRANSACTION_DATE VARCHAR2(40);

  P_CONC_REQUEST_ID NUMBER;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

END CSE_CSELOSDR_XMLP_PKG;


/
