--------------------------------------------------------
--  DDL for Package CSI_SYSTEMS_H_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CSI_SYSTEMS_H_PKG" AUTHID CURRENT_USER AS
/* $Header: csitsyhs.pls 115.13 2003/09/04 00:23:07 sguthiva ship $ */
-- start of comments
-- package name     : csi_systems_h_pkg
-- purpose          :
-- history          :
-- note             :
-- end of comments

PROCEDURE insert_row(
          px_system_history_id   IN OUT NOCOPY     NUMBER,
          p_system_id                       NUMBER      :=fnd_api.g_miss_num,
          p_transaction_id                  NUMBER      :=fnd_api.g_miss_num,
          p_old_customer_id                 NUMBER      :=fnd_api.g_miss_num,
          p_new_customer_id                 NUMBER      :=fnd_api.g_miss_num,
          p_old_system_type_code            VARCHAR2    :=fnd_api.g_miss_char,
          p_new_system_type_code            VARCHAR2    :=fnd_api.g_miss_char,
          p_old_system_NUMBER               VARCHAR2    :=fnd_api.g_miss_char,
          p_new_system_NUMBER               VARCHAR2    :=fnd_api.g_miss_char,
          p_old_parent_system_id            NUMBER      :=fnd_api.g_miss_num,
          p_new_parent_system_id            NUMBER      :=fnd_api.g_miss_num,
          p_old_ship_to_contact_id          NUMBER      :=fnd_api.g_miss_num,
          p_new_ship_to_contact_id          NUMBER      :=fnd_api.g_miss_num,
          p_old_bill_to_contact_id          NUMBER      :=fnd_api.g_miss_num,
          p_new_bill_to_contact_id          NUMBER      :=fnd_api.g_miss_num,
          p_old_technical_contact_id        NUMBER      :=fnd_api.g_miss_num,
          p_new_technical_contact_id        NUMBER      :=fnd_api.g_miss_num,
          p_old_service_admin_contact_id    NUMBER      :=fnd_api.g_miss_num,
          p_new_service_admin_contact_id    NUMBER      :=fnd_api.g_miss_num,
          p_old_ship_to_site_use_id         NUMBER      :=fnd_api.g_miss_num,
          p_new_ship_to_site_use_id         NUMBER      :=fnd_api.g_miss_num,
          p_old_install_site_use_id         NUMBER      :=fnd_api.g_miss_num,
          p_new_install_site_use_id         NUMBER      :=fnd_api.g_miss_num,
          p_old_bill_to_site_use_id         NUMBER      :=fnd_api.g_miss_num,
          p_new_bill_to_site_use_id         NUMBER      :=fnd_api.g_miss_num,
          p_old_coterminate_day_month       VARCHAR2    :=fnd_api.g_miss_char,
          p_new_coterminate_day_month       VARCHAR2    :=fnd_api.g_miss_char,
          p_old_start_date_active           DATE        :=fnd_api.g_miss_date,
          p_new_start_date_active           DATE        :=fnd_api.g_miss_date,
          p_old_end_date_active             DATE        :=fnd_api.g_miss_date,
          p_new_end_date_active             DATE        :=fnd_api.g_miss_date,
          p_old_autocreated_FROM_system     NUMBER      :=fnd_api.g_miss_num,
          p_new_autocreated_FROM_system     NUMBER      :=fnd_api.g_miss_num,
          p_old_config_system_type          VARCHAR2    :=fnd_api.g_miss_char,
          p_new_config_system_type          VARCHAR2    :=fnd_api.g_miss_char,
          p_old_context                     VARCHAR2    :=fnd_api.g_miss_char,
          p_new_context                     VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute1                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute1                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute2                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute2                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute3                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute3                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute4                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute4                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute5                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute5                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute6                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute6                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute7                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute7                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute8                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute8                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute9                  VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute9                  VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute10                 VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute10                 VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute11                 VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute11                 VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute12                 VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute12                 VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute13                 VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute13                 VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute14                 VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute14                 VARCHAR2    :=fnd_api.g_miss_char,
          p_old_attribute15                 VARCHAR2    :=fnd_api.g_miss_char,
          p_new_attribute15                 VARCHAR2    :=fnd_api.g_miss_char,
          p_full_dump_flag                  VARCHAR2    := fnd_api.g_miss_char,
          p_created_by                      NUMBER      :=fnd_api.g_miss_num,
          p_creation_date                   DATE        :=fnd_api.g_miss_date,
          p_last_updated_by                 NUMBER      :=fnd_api.g_miss_num,
          p_last_update_date                DATE        :=fnd_api.g_miss_date,
          p_last_update_login               NUMBER      :=fnd_api.g_miss_num,
          p_object_version_number           NUMBER      :=fnd_api.g_miss_num,
          p_old_name                        VARCHAR2    :=fnd_api.g_miss_char,
          p_new_name                        VARCHAR2    :=fnd_api.g_miss_char,
          p_old_description                 VARCHAR2    :=fnd_api.g_miss_char,
          p_new_description                 VARCHAR2    :=fnd_api.g_miss_char,
		p_old_operating_unit_id           NUMBER      :=fnd_api.g_miss_num,
		p_new_operating_unit_id           NUMBER      :=fnd_api.g_miss_num);

PROCEDURE Update_Row(
          p_system_history_id               NUMBER  ,
          p_system_id                       NUMBER  ,
          p_transaction_id                  NUMBER  ,
          p_old_customer_id                 NUMBER  ,
          p_new_customer_id                 NUMBER  ,
          p_old_system_type_code            VARCHAR2,
          p_new_system_type_code            VARCHAR2,
          p_old_system_number               VARCHAR2,
          p_new_system_number               VARCHAR2,
          p_old_parent_system_id            NUMBER  ,
          p_new_parent_system_id            NUMBER  ,
          p_old_ship_to_contact_id          NUMBER  ,
          p_new_ship_to_contact_id          NUMBER  ,
          p_old_bill_to_contact_id          NUMBER  ,
          p_new_bill_to_contact_id          NUMBER  ,
          p_old_technical_contact_id        NUMBER  ,
          p_new_technical_contact_id        NUMBER  ,
          p_old_service_admin_contact_id    NUMBER  ,
          p_new_service_admin_contact_id    NUMBER  ,
          p_old_ship_to_site_use_id         NUMBER  ,
          p_new_ship_to_site_use_id         NUMBER  ,
          p_old_install_site_use_id         NUMBER  ,
          p_new_install_site_use_id         NUMBER  ,
          p_old_bill_to_site_use_id         NUMBER  ,
          p_new_bill_to_site_use_id         NUMBER  ,
          p_old_coterminate_day_month       VARCHAR2,
          p_new_coterminate_day_month       VARCHAR2,
          p_old_start_date_active           DATE    ,
          p_new_start_date_active           DATE    ,
          p_old_end_date_active             DATE    ,
          p_new_end_date_active             DATE    ,
          p_old_autocreated_from_system     NUMBER  ,
          p_new_autocreated_from_system     NUMBER  ,
          p_old_config_system_type          VARCHAR2,
          p_new_config_system_type          VARCHAR2,
          p_old_context                     VARCHAR2,
          p_new_context                     VARCHAR2,
          p_old_attribute1                  VARCHAR2,
          p_new_attribute1                  VARCHAR2,
          p_old_attribute2                  VARCHAR2,
          p_new_attribute2                  VARCHAR2,
          p_old_attribute3                  VARCHAR2,
          p_new_attribute3                  VARCHAR2,
          p_old_attribute4                  VARCHAR2,
          p_new_attribute4                  VARCHAR2,
          p_old_attribute5                  VARCHAR2,
          p_new_attribute5                  VARCHAR2,
          p_old_attribute6                  VARCHAR2,
          p_new_attribute6                  VARCHAR2,
          p_old_attribute7                  VARCHAR2,
          p_new_attribute7                  VARCHAR2,
          p_old_attribute8                  VARCHAR2,
          p_new_attribute8                  VARCHAR2,
          p_old_attribute9                  VARCHAR2,
          p_new_attribute9                  VARCHAR2,
          p_old_attribute10                 VARCHAR2,
          p_new_attribute10                 VARCHAR2,
          p_old_attribute11                 VARCHAR2,
          p_new_attribute11                 VARCHAR2,
          p_old_attribute12                 VARCHAR2,
          p_new_attribute12                 VARCHAR2,
          p_old_attribute13                 VARCHAR2,
          p_new_attribute13                 VARCHAR2,
          p_old_attribute14                 VARCHAR2,
          p_new_attribute14                 VARCHAR2,
          p_old_attribute15                 VARCHAR2,
          p_new_attribute15                 VARCHAR2,
          p_full_dump_flag                  VARCHAR2,
          p_created_by                      NUMBER  ,
          p_creation_date                   DATE    ,
          p_last_updated_by                 NUMBER  ,
          p_last_update_date                DATE    ,
          p_last_update_login               NUMBER  ,
          p_object_version_number           NUMBER  ,
          p_old_name                        VARCHAR2,
          p_new_name                        VARCHAR2,
          p_old_description                 VARCHAR2,
          p_new_description                 VARCHAR2,
		p_old_operating_unit_id           NUMBER,
		p_new_operating_unit_id           NUMBER);

end csi_systems_h_pkg;

 

/
