--------------------------------------------------------
--  DDL for Package CSI_CSICPREP_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CSI_CSICPREP_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CSICPREPS.pls 120.0 2007/12/24 12:59:25 nchinnam noship $ */
  P_CONC_REQUEST_ID NUMBER;
  P_FLEX_ITEM_CODE VARCHAR2(800);
  P_ITEM_STRUCT_NUM NUMBER;
  P_SOB_ID NUMBER;
  P_CUSTOMER_NUMBER_LOW VARCHAR2(30);
  P_CUSTOMER_NUMBER_HIGH VARCHAR2(30);
  LP_CUSTOMER_RANGE VARCHAR2(200) :='and 1=1';
  P_ITEM_LO VARCHAR2(900);
  P_ITEM_HIGH VARCHAR2(900);
  LP_ITEM_RANGE VARCHAR2(900) :='and 1=1';
  P_INSTALL_LOCATION VARCHAR2(40) :='and 1=1';
  P_CP_STATUS VARCHAR2(30);
  LP_INSTALL_LOCATION VARCHAR2(200) := 'and 1=1';
  LP_CP_STATUS VARCHAR2(200) :='and 1=1';
  P_ITEM_WHERE VARCHAR2(200) :='and 1=1';
  P_ORDER_BY VARCHAR2(300);
  P_ORGANIZATION_ID NUMBER;
  RP_REPORT_NAME VARCHAR2(80) := 'Customer Products - Summary';
  RP_COMPANY_NAME VARCHAR2(50);
  FUNCTION BEFOREREPORT RETURN BOOLEAN;
  FUNCTION AFTERREPORT RETURN BOOLEAN;
  FUNCTION P_SOB_IDVALIDTRIGGER RETURN BOOLEAN;
  FUNCTION AFTERPFORM RETURN BOOLEAN;
  FUNCTION RP_REPORT_NAME_P RETURN VARCHAR2;
  FUNCTION RP_COMPANY_NAME_P RETURN VARCHAR2;
END CSI_CSICPREP_XMLP_PKG;


/
