--------------------------------------------------------
--  DDL for Package CSM_HA_PROCESS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."CSM_HA_PROCESS_PKG" AUTHID CURRENT_USER  AS
/* $Header: csmhaps.pls 120.0.12010000.3 2010/05/05 05:42:05 trajasek noship $*/

G_HA_START_TIME TIMESTAMP;
G_HA_END_TIME  TIMESTAMP;
G_HA_PAYLOAD_SEQUENCE_START NUMBER;
G_HA_PAYLOAD_SEQUENCE_END NUMBER;
G_HA_SESSION_SEQUENCE NUMBER;
G_CON_REQUEST_ID      NUMBER;
PROCEDURE PARSE_XML(p_HA_PAYLOAD_ID    IN NUMBER,
                    x_COL_NAME_LIST  OUT NOCOPY  CSM_VARCHAR_LIST,
                    X_COL_VALUE_LIST OUT NOCOPY  CSM_VARCHAR_LIST,
                    X_CON_NAME_LIST  OUT NOCOPY  CSM_VARCHAR_LIST,
                    X_CON_VALUE_LIST OUT NOCOPY  CSM_VARCHAR_LIST,
                    x_RETURN_STATUS OUT NOCOPY VARCHAR2,
                    x_ERROR_MESSAGE OUT NOCOPY VARCHAR2);

PROCEDURE PROCESS_HA(x_RETURN_STATUS OUT NOCOPY VARCHAR2,
                    x_ERROR_MESSAGE OUT NOCOPY VARCHAR2);

FUNCTION PROCESS_HA RETURN NUMBER;

PROCEDURE SET_CONTEXT(  P_CON_NAME_LIST  CSM_VARCHAR_LIST,
                        p_CON_VALUE_LIST CSM_VARCHAR_LIST,
                        X_RETURN_STATUS OUT NOCOPY VARCHAR2,
                        X_ERROR_MESSAGE OUT NOCOPY VARCHAR2);

PROCEDURE PROCESS_DIRECT_DML(P_PAYLOAD_ID IN NUMBER
                            ,X_RETURN_STATUS OUT NOCOPY VARCHAR2
                					  ,X_ERROR_MESSAGE OUT NOCOPY VARCHAR2);

PROCEDURE SET_HA_PROFILE(P_VALUE IN VARCHAR2);

FUNCTION CLOB_TO_BLOB( P_CLOB_DATA IN CLOB ) RETURN BLOB;

END CSM_HA_PROCESS_PKG; -- Package spec

/
