--------------------------------------------------------
--  DDL for Package DOM_DOC_REV_VERSIONS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."DOM_DOC_REV_VERSIONS_PKG" AUTHID CURRENT_USER as
/* $Header: DOMVERS.pls 120.2 2006/04/13 06:54:16 sabatra noship $ */

procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_DOCUMENT_ID in NUMBER,
  X_REVISION_ID in NUMBER,
  X_VERSION_ID in NUMBER,
  X_VERSION in NUMBER,
  X_STATUS_CODE in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);

procedure LOCK_ROW (
  X_DOCUMENT_ID in NUMBER,
  X_REVISION_ID in NUMBER,
  X_VERSION_ID in NUMBER,
  X_VERSION in NUMBER,
  X_STATUS_CODE in VARCHAR2,
  X_COMMENTS in VARCHAR2
);

procedure UPDATE_ROW (
  X_DOCUMENT_ID in NUMBER,
  X_REVISION_ID in NUMBER,
  X_VERSION_ID in NUMBER,
  X_VERSION in NUMBER,
  X_STATUS_CODE in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);

procedure DELETE_ROW (
  X_VERSION_ID in NUMBER
);

procedure ADD_LANGUAGE;

end DOM_DOC_REV_VERSIONS_PKG;


 

/
