--------------------------------------------------------
--  DDL for Package DPP_BPEL_GETPROMOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."DPP_BPEL_GETPROMOS" AUTHID CURRENT_USER AS
/* $Header: dppvbuns.pls 120.1 2007/12/12 06:04:29 sdasan noship $ */
	-- Declare the conversion functions the PL/SQL type DPP_PRICING_PVT.DPP_PL_NOTIFY_REC_TYPE
	FUNCTION PL_TO_SQL16(aPlsqlItem DPP_PRICING_PVT.DPP_PL_NOTIFY_REC_TYPE)
 	RETURN DPP_PRICING_PVT_DPP_PL_NOTI14;
	FUNCTION SQL_TO_PL16(aSqlItem DPP_PRICING_PVT_DPP_PL_NOTI14)
	RETURN DPP_PRICING_PVT.DPP_PL_NOTIFY_REC_TYPE;
	-- Declare the conversion functions the PL/SQL type DPP_PRICING_PVT.DPP_OBJECT_NAME_TBL_TYPE
	FUNCTION PL_TO_SQL18(aPlsqlItem DPP_PRICING_PVT.DPP_OBJECT_NAME_TBL_TYPE)
 	RETURN DPPPRICINGPVTDPPPLNOTI16_DPP_;
	FUNCTION SQL_TO_PL18(aSqlItem DPPPRICINGPVTDPPPLNOTI16_DPP_)
	RETURN DPP_PRICING_PVT.DPP_OBJECT_NAME_TBL_TYPE;
	-- Declare the conversion functions the PL/SQL type DPP_PRICING_PVT.DPP_PL_NOTIFY_LINE_REC_TYPE
	FUNCTION PL_TO_SQL19(aPlsqlItem DPP_PRICING_PVT.DPP_PL_NOTIFY_LINE_REC_TYPE)
 	RETURN DPP_PRICING_PVT_DPP_PL_NOTI16;
	FUNCTION SQL_TO_PL19(aSqlItem DPP_PRICING_PVT_DPP_PL_NOTI16)
	RETURN DPP_PRICING_PVT.DPP_PL_NOTIFY_LINE_REC_TYPE;
	-- Declare the conversion functions the PL/SQL type DPP_PRICING_PVT.DPP_PL_NOTIFY_LINE_TBL_TYPE
	FUNCTION PL_TO_SQL17(aPlsqlItem DPP_PRICING_PVT.DPP_PL_NOTIFY_LINE_TBL_TYPE)
 	RETURN DPP_PRICING_PVT_DPP_PL_NOTI15;
	FUNCTION SQL_TO_PL17(aSqlItem DPP_PRICING_PVT_DPP_PL_NOTI15)
	RETURN DPP_PRICING_PVT.DPP_PL_NOTIFY_LINE_TBL_TYPE;
   PROCEDURE DPP_PRICING_PVT$NOTIFY_PROMOT (P_API_VERSION NUMBER,P_INIT_MSG_LIST VARCHAR2,P_COMMIT VARCHAR2,P_VALIDATION_LEVEL NUMBER,
   X_RETURN_STATUS OUT NOCOPY VARCHAR2,X_MSG_COUNT OUT NOCOPY NUMBER,X_MSG_DATA OUT NOCOPY VARCHAR2,
   P_PL_NOTIFY_HDR_REC IN OUT NOCOPY DPP_PRICING_PVT_DPP_PL_NOTI14,P_PL_NOTIFY_LINE_TBL IN OUT NOCOPY DPP_PRICING_PVT_DPP_PL_NOTI15);
END DPP_BPEL_GETPROMOS;

/
