--------------------------------------------------------
--  DDL for Package ECX_XREF_HDR_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ECX_XREF_HDR_PKG" AUTHID CURRENT_USER as
/* $Header: ECXXRFHS.pls 120.2 2005/06/30 11:19:15 appldev ship $ */

procedure TRANSLATE_ROW (
  X_XREF_CATEGORY_CODE          IN      VARCHAR2,
  X_DESCRIPTION                 IN      VARCHAR2,
  X_OWNER                       IN      VARCHAR2,
  X_CUSTOM_MODE                 IN      VARCHAR2
);
procedure LOAD_ROW (
  X_XREF_CATEGORY_CODE  IN      VARCHAR2,
  X_DESCRIPTION         IN      VARCHAR2,
  X_OWNER               IN      VARCHAR2,
  X_CUSTOM_MODE         IN      VARCHAR2
);
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_XREF_CATEGORY_ID in NUMBER,
  X_XREF_CATEGORY_CODE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_XREF_CATEGORY_ID in NUMBER,
  X_XREF_CATEGORY_CODE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2
);
procedure UPDATE_ROW (
  X_XREF_CATEGORY_ID in NUMBER,
  X_XREF_CATEGORY_CODE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_XREF_CATEGORY_ID in NUMBER
);
procedure ADD_LANGUAGE;
end ECX_XREF_HDR_PKG;

 

/
