--------------------------------------------------------
--  DDL for Package ENG_CHANGE_MGMT_TYPES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ENG_CHANGE_MGMT_TYPES_PKG" AUTHID CURRENT_USER as
/* $Header: ENGTYPES.pls 115.2 2002/12/03 19:43:44 sshrikha noship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_CHANGE_MGMT_TYPE_CODE in VARCHAR2,
  X_ENABLE_REV_ITEMS_FLAG in VARCHAR2,
  X_ENABLE_TASKS_FLAG in VARCHAR2,
  X_DISABLE_FLAG in VARCHAR2,
  X_SEQUENCE_NUMBER in NUMBER,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_TAB_TEXT in VARCHAR2,
  X_FORM_FUNCTION_NAME in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_CHANGE_MGMT_TYPE_CODE in VARCHAR2,
  X_ENABLE_REV_ITEMS_FLAG in VARCHAR2,
  X_ENABLE_TASKS_FLAG in VARCHAR2,
  X_DISABLE_FLAG in VARCHAR2,
  X_SEQUENCE_NUMBER in NUMBER,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_TAB_TEXT in VARCHAR2,
  X_FORM_FUNCTION_NAME in VARCHAR2
);
procedure UPDATE_ROW (
  X_CHANGE_MGMT_TYPE_CODE in VARCHAR2,
  X_ENABLE_REV_ITEMS_FLAG in VARCHAR2,
  X_ENABLE_TASKS_FLAG in VARCHAR2,
  X_DISABLE_FLAG in VARCHAR2,
  X_SEQUENCE_NUMBER in NUMBER,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_TAB_TEXT in VARCHAR2,
  X_FORM_FUNCTION_NAME in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_CHANGE_MGMT_TYPE_CODE in VARCHAR2
);
procedure ADD_LANGUAGE;
end ENG_CHANGE_MGMT_TYPES_PKG;

 

/
