--------------------------------------------------------
--  DDL for Package ENG_CHANGE_STATUSES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ENG_CHANGE_STATUSES_PKG" AUTHID CURRENT_USER as
/* $Header: ENGUSTSS.pls 120.1 2006/01/30 02:24:56 pdutta noship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_STATUS_CODE in NUMBER,
  X_SORT_SEQUENCE_NUM in NUMBER,
  X_DISABLE_DATE in DATE,
  X_STATUS_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_STATUS_TYPE in NUMBER,
  X_OBJECT_NAME in VARCHAR2);

procedure LOCK_ROW (
  X_STATUS_CODE in NUMBER,
  X_SORT_SEQUENCE_NUM in NUMBER,
  X_DISABLE_DATE in DATE,
  X_STATUS_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_STATUS_TYPE in NUMBER,
  X_OBJECT_NAME in VARCHAR2
);

procedure UPDATE_ROW (
  X_STATUS_CODE in NUMBER,
  X_SORT_SEQUENCE_NUM in NUMBER,
  X_DISABLE_DATE in DATE,
  X_STATUS_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_STATUS_TYPE in NUMBER,
  X_OBJECT_NAME in VARCHAR2
);
procedure DELETE_ROW (
  X_STATUS_CODE in NUMBER
);
procedure ADD_LANGUAGE;
end ENG_CHANGE_STATUSES_PKG;

 

/
