--------------------------------------------------------
--  DDL for Package FA_INS_LINES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."FA_INS_LINES_PKG" AUTHID CURRENT_USER as
/* $Header: faxinsls.pls 120.2.12010000.2 2009/07/19 10:26:52 glchen ship $ */

PROCEDURE Insert_Row(	X_Rowid			 IN OUT NOCOPY VARCHAR2,
			X_Asset_policy_id	 NUMBER,
                        X_Vendor_id		 NUMBER,
			X_Policy_number		 VARCHAR2,
			X_Asset_id		 NUMBER,
			X_policy_line		 NUMBER,
			X_insurance_category	 VARCHAR2,
			X_hazard_class  	 VARCHAR2,
			X_comments 		 VARCHAR2,
                        X_Last_update_date       DATE,
                        X_Last_updated_by        VARCHAR2,
                        X_Last_update_login      VARCHAR2,
                        X_Creation_date          DATE,
                        X_Created_by             VARCHAR2,
                        X_Attribute_category     VARCHAR2,
                        X_Attribute1             VARCHAR2,
                        X_Attribute2             VARCHAR2,
                        X_Attribute3             VARCHAR2,
                        X_Attribute4             VARCHAR2,
                        X_Attribute5             VARCHAR2,
                        X_Attribute6             VARCHAR2,
                        X_Attribute7             VARCHAR2,
                        X_Attribute8             VARCHAR2,
                        X_Attribute9             VARCHAR2,
                        X_Attribute10            VARCHAR2,
                        X_Attribute11            VARCHAR2,
                        X_Attribute12            VARCHAR2,
                        X_Attribute13            VARCHAR2,
                        X_Attribute14            VARCHAR2,
                        X_Attribute15            VARCHAR2,
                        X_Attribute16            VARCHAR2,
                        X_Attribute17            VARCHAR2,
                        X_Attribute18            VARCHAR2,
                        X_Attribute19            VARCHAR2,
                        X_Attribute20            VARCHAR2
		    , p_log_level_rec        IN     FA_API_TYPES.log_level_rec_type);

PROCEDURE Lock_Row(     X_Rowid                  VARCHAR2,
                        X_Asset_policy_id        NUMBER,
                        X_Vendor_id              NUMBER,
                        X_Policy_number          VARCHAR2,
                        X_Asset_id               NUMBER,
                        X_policy_line            NUMBER,
                        X_insurance_category     VARCHAR2,
                        X_hazard_class           VARCHAR2,
                        X_comments               VARCHAR2,
                        X_Last_update_date       DATE,
                        X_Last_updated_by        VARCHAR2,
                        X_Last_update_login      VARCHAR2,
                        X_Creation_date          DATE,
                        X_Created_by             VARCHAR2,
                        X_Attribute_category     VARCHAR2,
                        X_Attribute1             VARCHAR2,
                        X_Attribute2             VARCHAR2,
                        X_Attribute3             VARCHAR2,
                        X_Attribute4             VARCHAR2,
                        X_Attribute5             VARCHAR2,
                        X_Attribute6             VARCHAR2,
                        X_Attribute7             VARCHAR2,
                        X_Attribute8             VARCHAR2,
                        X_Attribute9             VARCHAR2,
                        X_Attribute10            VARCHAR2,
                        X_Attribute11            VARCHAR2,
                        X_Attribute12            VARCHAR2,
                        X_Attribute13            VARCHAR2,
                        X_Attribute14            VARCHAR2,
                        X_Attribute15            VARCHAR2,
                        X_Attribute16            VARCHAR2,
                        X_Attribute17            VARCHAR2,
                        X_Attribute18            VARCHAR2,
                        X_Attribute19            VARCHAR2,
                        X_Attribute20            VARCHAR2
                    , p_log_level_rec        IN     FA_API_TYPES.log_level_rec_type);

PROCEDURE Update_Row(   X_Rowid                  VARCHAR2,
                        X_Asset_policy_id        NUMBER,
                        X_Vendor_id              NUMBER,
                        X_Policy_number          VARCHAR2,
                        X_Asset_id               NUMBER,
                        X_policy_line            NUMBER,
                        X_insurance_category     VARCHAR2,
                        X_hazard_class           VARCHAR2,
                        X_comments               VARCHAR2,
                        X_Last_update_date       DATE,
                        X_Last_updated_by        VARCHAR2,
                        X_Last_update_login      VARCHAR2,
                        X_Creation_date          DATE,
                        X_Created_by             VARCHAR2,
                        X_Attribute_category     VARCHAR2,
                        X_Attribute1             VARCHAR2,
                        X_Attribute2             VARCHAR2,
                        X_Attribute3             VARCHAR2,
                        X_Attribute4             VARCHAR2,
                        X_Attribute5             VARCHAR2,
                        X_Attribute6             VARCHAR2,
                        X_Attribute7             VARCHAR2,
                        X_Attribute8             VARCHAR2,
                        X_Attribute9             VARCHAR2,
                        X_Attribute10            VARCHAR2,
                        X_Attribute11            VARCHAR2,
                        X_Attribute12            VARCHAR2,
                        X_Attribute13            VARCHAR2,
                        X_Attribute14            VARCHAR2,
                        X_Attribute15            VARCHAR2,
                        X_Attribute16            VARCHAR2,
                        X_Attribute17            VARCHAR2,
                        X_Attribute18            VARCHAR2,
                        X_Attribute19            VARCHAR2,
                        X_Attribute20            VARCHAR2
                    , p_log_level_rec        IN     FA_API_TYPES.log_level_rec_type);

PROCEDURE Delete_Row(   X_Rowid                 VARCHAR2, p_log_level_rec        IN     FA_API_TYPES.log_level_rec_type);

END FA_INS_LINES_PKG;

/
