--------------------------------------------------------
--  DDL for Package FA_TRANS_API_PUB
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."FA_TRANS_API_PUB" AUTHID CURRENT_USER AS
/* $Header: FAPTAPIS.pls 120.11.12010000.2 2009/07/19 12:04:57 glchen ship $ */

PROCEDURE do_addition (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_asset_id                        OUT NOCOPY NUMBER,
     x_asset_number                    OUT NOCOPY VARCHAR2,
     x_transaction_header_id           OUT NOCOPY NUMBER,
     x_dist_transaction_header_id      OUT NOCOPY NUMBER,
     -- Transaction Info (Books) --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_transaction_subtype          IN     VARCHAR2 DEFAULT NULL,
     p_amortization_start_date      IN     DATE     DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Transaction Info (Distributions) --
     p_dist_transaction_name        IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute1              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute2              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute3              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute4              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute5              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute6              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute7              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute8              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute9              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute10             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute11             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute12             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute13             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute14             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute15             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute_category_code IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER   DEFAULT NULL,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Description Info --
     p_asset_number                 IN     VARCHAR2 DEFAULT NULL,
     p_description                  IN     VARCHAR2,
     p_tag_number                   IN     VARCHAR2 DEFAULT NULL,
     p_serial_number                IN     VARCHAR2 DEFAULT NULL,
     p_asset_key_ccid               IN     NUMBER   DEFAULT NULL,
     p_parent_asset_id              IN     NUMBER   DEFAULT NULL,
     p_status                       IN     VARCHAR2 DEFAULT NULL,
     p_manufacturer_name            IN     VARCHAR2 DEFAULT NULL,
     p_model_number                 IN     VARCHAR2 DEFAULT NULL,
     p_warranty_id                  IN     NUMBER   DEFAULT NULL,
     p_property_type_code           IN     VARCHAR2,
     p_property_1245_1250_code      IN     VARCHAR2,
     p_in_use_flag                  IN     VARCHAR2,
     p_inventorial                  IN     VARCHAR2 DEFAULT NULL,
     p_commitment		    IN     VARCHAR2 DEFAULT NULL,
     p_investment_law		    IN     VARCHAR2 DEFAULT NULL,
     p_owned_leased                 IN     VARCHAR2,
     p_new_used                     IN     VARCHAR2,
     p_lease_id                     IN     NUMBER   DEFAULT NULL,
     p_ls_attribute1                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute2                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute3                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute4                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute5                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute6                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute7                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute8                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute9                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute10               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute11               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute12               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute13               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute14               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute15               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute_category_code   IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute1         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute2         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute3         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute4         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute5         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute6         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute7         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute8         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute9         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute10        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute11        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute12        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute13        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute14        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute15        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute16        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute17        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute18        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute19        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute20        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute_category IN     VARCHAR2 DEFAULT NULL,
     -- Asset Type Info --
     p_asset_type                   IN     VARCHAR2,
     -- Asset Category Info --
     p_category_id                  IN     NUMBER,
     p_cat_attribute1               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute2               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute3               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute4               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute5               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute6               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute7               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute8               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute9               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute10              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute11              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute12              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute13              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute14              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute15              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute16              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute17              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute18              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute19              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute20              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute21              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute22              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute23              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute24              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute25              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute26              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute27              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute28              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute29              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute30              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute_category_code  IN     VARCHAR2 DEFAULT NULL,
     p_context                      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Hierarchy Info --
     p_parent_hierarchy_id          IN     NUMBER   DEFAULT NULL,
     -- Asset Financial Info --
     p_cost                         IN     NUMBER,
     p_original_cost                IN     NUMBER,
     p_unrevalued_cost              IN     NUMBER   DEFAULT NULL,
     p_salvage_value                IN     NUMBER,
     p_ceiling_name                 IN     VARCHAR2 DEFAULT NULL,
     p_reval_ceiling                IN     NUMBER   DEFAULT NULL,
     p_depreciate_flag              IN     VARCHAR2,
     -- HH group ed.
     p_disabled_flag                IN     VARCHAR2 DEFAULT NULL,
     p_date_placed_in_service       IN     DATE,
     p_prorate_convention_code      IN     VARCHAR2,
     p_deprn_method_code            IN     VARCHAR2,
     p_life_in_months               IN     NUMBER   DEFAULT NULL,
     p_basic_rate                   IN     NUMBER   DEFAULT NULL,
     p_adjusted_rate                IN     NUMBER   DEFAULT NULL,
     p_production_capacity          IN     NUMBER   DEFAULT NULL,
     p_unit_of_measure              IN     VARCHAR2 DEFAULT NULL,
     p_bonus_rule                   IN     VARCHAR2 DEFAULT NULL,
     p_itc_amount_id                IN     NUMBER   DEFAULT NULL,
     p_short_fiscal_year_flag       IN     VARCHAR2 DEFAULT NULL,
     p_conversion_date              IN     DATE     DEFAULT NULL,
     p_orig_deprn_start_date        IN     DATE     DEFAULT NULL,
     p_group_asset_id               IN     NUMBER   DEFAULT NULL,
/* toru */
     -- Addition for Group Depreciation
     p_percent_salvage_value        IN     NUMBER   DEFAULT NULL,
     p_allowed_deprn_limit          IN     NUMBER   DEFAULT NULL,
     p_allowed_deprn_limit_amount   IN     NUMBER   DEFAULT NULL,
     p_super_group_id               IN     NUMBER   DEFAULT NULL,
     p_reduction_rate               IN     NUMBER   DEFAULT NULL,
     p_reduce_addition_flag         IN     VARCHAR2 DEFAULT NULL,
     p_reduce_adjustment_flag       IN     VARCHAR2 DEFAULT NULL,
     p_reduce_retirement_flag       IN     VARCHAR2 DEFAULT NULL,
     p_over_depreciate_option       IN     VARCHAR2 DEFAULT NULL,
     p_recognize_gain_loss          IN     VARCHAR2 DEFAULT NULL,
     p_recapture_reserve_flag       IN     VARCHAR2 DEFAULT NULL,
     p_limit_proceeds_flag          IN     VARCHAR2 DEFAULT NULL,
     p_terminal_gain_loss           IN     VARCHAR2 DEFAULT NULL,
     p_exclude_proceeds_from_basis  IN     VARCHAR2 DEFAULT NULL,
     p_retirement_deprn_option      IN     VARCHAR2 DEFAULT NULL,
     p_salvage_type                 IN     VARCHAR2 DEFAULT NULL,
     p_deprn_limit_type             IN     VARCHAR2 DEFAULT NULL,
     p_tracking_method              IN     VARCHAR2 DEFAULT NULL,
     p_allocate_to_fully_rsv_flag   IN     VARCHAR2 DEFAULT NULL,
     p_allocate_to_fully_ret_flag   IN     VARCHAR2 DEFAULT NULL,
     p_excess_allocation_option     IN     VARCHAR2 DEFAULT NULL,
     p_depreciation_option          IN     VARCHAR2 DEFAULT NULL,
     p_member_rollup_flag           IN     VARCHAR2 DEFAULT NULL,
     p_ytd_proceeds                 IN     NUMBER   DEFAULT NULL,
     p_ltd_proceeds                 IN     NUMBER   DEFAULT NULL,
     p_exclude_fully_rsv_flag       IN     VARCHAR2 DEFAULT NULL,
     p_eofy_reserve                 IN     NUMBER   DEFAULT NULL,
     p_reclass_transfer_type        IN     VARCHAR2 DEFAULT NULL,
     p_reclass_transfer_amount      IN     NUMBER   DEFAULT NULL,
     p_reclass_src_expense          IN     NUMBER   DEFAULT NULL,
     p_reclass_dest_expense         IN     NUMBER   DEFAULT NULL,
     p_reclass_src_eofy_reserve     IN     NUMBER   DEFAULT NULL,
     p_reclass_dest_eofy_reserve    IN     NUMBER   DEFAULT NULL,
     -- End of Addition for Group Depreciation
/* Etoru */
     p_bk_global_attribute1         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute2         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute3         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute4         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute5         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute6         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute7         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute8         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute9         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute10        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute11        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute12        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute13        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute14        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute15        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute16        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute17        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute18        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute19        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute20        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute_category IN     VARCHAR2 DEFAULT NULL,
     -- Asset Depreciation Info --
     p_ytd_deprn                    IN     NUMBER   DEFAULT NULL,
     p_deprn_reserve                IN     NUMBER   DEFAULT NULL,
     p_reval_deprn_reserve          IN     NUMBER   DEFAULT NULL,
     p_ytd_production               IN     NUMBER   DEFAULT NULL,
     p_ltd_production                IN     NUMBER   DEFAULT NULL,
     -- IAS36 Impairment Info --
     p_cash_generating_unit_id       IN     NUMBER   DEFAULT NULL,
     p_nbv_at_switch                 IN     NUMBER   DEFAULT NULL,  -- Changes made as per the ER No.s 6606548 and 6606552 by Sbyreddy Start
     p_prior_deprn_limit_type        IN     VARCHAR2 DEFAULT NULL,
     p_prior_deprn_limit_amount      IN     NUMBER   DEFAULT NULL,
     p_prior_deprn_limit             IN     NUMBER   DEFAULT NULL,
     p_period_counter_fully_rsrved   IN     NUMBER   DEFAULT NULL,
     p_extended_depreciation_period  IN     NUMBER   DEFAULT NULL,
     p_prior_deprn_method            IN     VARCHAR2 DEFAULT NULL,
     p_prior_life_in_months          IN     NUMBER   DEFAULT NULL,
     p_prior_basic_rate              IN     NUMBER   DEFAULT NULL,
     p_prior_adjusted_rate           IN     NUMBER   DEFAULT NULL,
     p_extended_deprn_flag          IN     VARCHAR2 DEFAULT NULL
-- Changes made as per the ER No.s 6606548 and 6606552 by Sbyreddy End

);


PROCEDURE do_adjustment (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                    IN    VARCHAR2 DEFAULT 'NO',
     p_reset_miss_flag               IN    VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info (Books) --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_transaction_subtype          IN     VARCHAR2 DEFAULT NULL,
     p_amortization_start_date      IN     DATE     DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Financial Info --
     p_cost                         IN     NUMBER   DEFAULT NULL,
     p_original_cost                IN     NUMBER   DEFAULT NULL,
     p_unrevalued_cost              IN     NUMBER   DEFAULT NULL,
     p_recoverable_cost             IN     NUMBER   DEFAULT NULL,
     p_salvage_value                IN     NUMBER   DEFAULT NULL,
     p_ceiling_name                 IN     VARCHAR2 DEFAULT NULL,
     p_reval_ceiling                IN     NUMBER   DEFAULT NULL,
     p_depreciate_flag              IN     VARCHAR2 DEFAULT NULL,
     -- HH group ed.
     p_disabled_flag                IN     VARCHAR2 DEFAULT NULL,
     p_date_placed_in_service       IN     DATE     DEFAULT NULL,
     p_prorate_convention_code      IN     VARCHAR2 DEFAULT NULL,
     p_deprn_method_code            IN     VARCHAR2 DEFAULT NULL,
     p_life_in_months               IN     NUMBER   DEFAULT NULL,
     p_basic_rate                   IN     NUMBER   DEFAULT NULL,
     p_adjusted_rate                IN     NUMBER   DEFAULT NULL,
     p_production_capacity          IN     NUMBER   DEFAULT NULL,
     p_unit_of_measure              IN     VARCHAR2 DEFAULT NULL,
     p_bonus_rule                   IN     VARCHAR2 DEFAULT NULL,
     p_itc_amount_id                IN     NUMBER   DEFAULT NULL,
     p_short_fiscal_year_flag       IN     VARCHAR2 DEFAULT NULL,
     p_conversion_date              IN     DATE     DEFAULT NULL,
     p_orig_deprn_start_date        IN     DATE     DEFAULT NULL,
     p_group_asset_id               IN     NUMBER   DEFAULT NULL,
/* toru */
     -- Addition for Group Depreciation
     p_percent_salvage_value        IN     NUMBER   DEFAULT NULL,
     p_allowed_deprn_limit          IN     NUMBER   DEFAULT NULL,
     p_allowed_deprn_limit_amount   IN     NUMBER   DEFAULT NULL,
     p_super_group_id               IN     NUMBER   DEFAULT NULL,
     p_reduction_rate               IN     NUMBER   DEFAULT NULL,
     p_reduce_addition_flag         IN     VARCHAR2 DEFAULT NULL,
     p_reduce_adjustment_flag       IN     VARCHAR2 DEFAULT NULL,
     p_reduce_retirement_flag       IN     VARCHAR2 DEFAULT NULL,
     p_over_depreciate_option       IN     VARCHAR2 DEFAULT NULL,
     p_recognize_gain_loss          IN     VARCHAR2 DEFAULT NULL,
     p_recapture_reserve_flag       IN     VARCHAR2 DEFAULT NULL,
     p_limit_proceeds_flag          IN     VARCHAR2 DEFAULT NULL,
     p_terminal_gain_loss           IN     VARCHAR2 DEFAULT NULL,
     p_exclude_proceeds_from_basis  IN     VARCHAR2 DEFAULT NULL,
     p_retirement_deprn_option      IN     VARCHAR2 DEFAULT NULL,
     p_salvage_type                 IN     VARCHAR2 DEFAULT NULL,
     p_deprn_limit_type             IN     VARCHAR2 DEFAULT NULL,
     p_tracking_method              IN     VARCHAR2 DEFAULT NULL,
     p_allocate_to_fully_rsv_flag   IN     VARCHAR2 DEFAULT NULL,
     p_allocate_to_fully_ret_flag   IN     VARCHAR2 DEFAULT NULL,
     p_excess_allocation_option     IN     VARCHAR2 DEFAULT NULL,
     p_depreciation_option          IN     VARCHAR2 DEFAULT NULL,
     p_member_rollup_flag           IN     VARCHAR2 DEFAULT NULL,
     p_ytd_proceeds                 IN     NUMBER   DEFAULT NULL,
     p_ltd_proceeds                 IN     NUMBER   DEFAULT NULL,
     p_exclude_fully_rsv_flag       IN     VARCHAR2 DEFAULT NULL,
     p_eofy_reserve                 IN     NUMBER   DEFAULT NULL,
     p_reclass_transfer_type        IN     VARCHAR2 DEFAULT NULL,
     p_reclass_transfer_amount      IN     NUMBER   DEFAULT NULL,
     p_reclass_src_expense          IN     NUMBER   DEFAULT NULL,
     p_reclass_dest_expense         IN     NUMBER   DEFAULT NULL,
     p_reclass_src_eofy_reserve     IN     NUMBER   DEFAULT NULL,
     p_reclass_dest_eofy_reserve    IN     NUMBER   DEFAULT NULL,
     -- End of Addition for Group Depreciation
/* Etoru */
     p_bk_global_attribute1         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute2         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute3         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute4         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute5         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute6         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute7         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute8         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute9         IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute10        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute11        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute12        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute13        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute14        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute15        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute16        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute17        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute18        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute19        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute20        IN     VARCHAR2 DEFAULT NULL,
     p_bk_global_attribute_category IN     VARCHAR2 DEFAULT NULL,
     -- Asset Depreciation Info --
     p_ytd_deprn                    IN     NUMBER   DEFAULT NULL,
     p_deprn_reserve                IN     NUMBER   DEFAULT NULL,
     p_reval_deprn_reserve          IN     NUMBER   DEFAULT NULL,
     p_ytd_production               IN     NUMBER   DEFAULT NULL,
     p_ltd_production               IN     NUMBER   DEFAULT NULL,
     -- Invoice Info --
     p_invoice_transaction_type     IN     VARCHAR2 DEFAULT NULL,
     -- Group Reclass Options --
     p_transfer_flag                IN     VARCHAR2 DEFAULT NULL,
     p_manual_amount                IN     NUMBER   DEFAULT NULL,
     p_manual_flag                  IN     VARCHAR2 DEFAULT NULL,
     -- IAS36 Impairment Info --
     p_cash_generating_unit_id      IN     NUMBER   DEFAULT NULL,
     p_nbv_at_switch                 IN     NUMBER   DEFAULT NULL,   -- Changes made as per the ER No.s 6606548 and 6606552 by Sbyreddy Start
     p_prior_deprn_limit_type        IN     VARCHAR2 DEFAULT NULL,
     p_prior_deprn_limit_amount      IN     NUMBER   DEFAULT NULL,
     p_prior_deprn_limit             IN     NUMBER   DEFAULT NULL,
     p_period_counter_fully_rsrved   IN     VARCHAR2 DEFAULT NULL,
     p_extended_depreciation_period  IN     VARCHAR2 DEFAULT NULL,
     p_prior_deprn_method            IN     VARCHAR2 DEFAULT NULL,
     p_prior_life_in_months          IN     NUMBER   DEFAULT NULL,
     p_prior_basic_rate              IN     NUMBER   DEFAULT NULL,
     p_prior_adjusted_rate           IN     NUMBER   DEFAULT NULL,
     p_extended_deprn_flag          IN     VARCHAR2 DEFAULT NULL
 -- Changes made as per the ER No.s 6606548 and 6606552 by Sbyreddy End
);

PROCEDURE do_unit_adjustment(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL
);

PROCEDURE do_transfer(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL
);

PROCEDURE do_invoice_transfer (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_src_transaction_header_id           OUT NOCOPY NUMBER,
     x_dest_transaction_header_id          OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_amortization_start_date      IN     DATE     DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     -- Source Asset Header Info --
     p_src_asset_id                 IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Destination Asset Header Info --
     p_dest_asset_id                IN     NUMBER
);

PROCEDURE do_reclass(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_transaction_subtype          IN     VARCHAR2 DEFAULT NULL,
     p_amortization_start_date      IN     DATE     DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     -- Asset Category Info --
     p_new_category_id              IN     NUMBER,
     p_cat_attribute1               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute2               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute3               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute4               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute5               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute6               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute7               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute8               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute9               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute10              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute11              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute12              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute13              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute14              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute15              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute16              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute17              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute18              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute19              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute20              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute21              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute22              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute23              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute24              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute25              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute26              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute27              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute28              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute29              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute30              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute_category_code  IN     VARCHAR2 DEFAULT NULL,
     p_context                      IN     VARCHAR2 DEFAULT NULL,
     -- Reclass Options Info --
     p_copy_cat_desc_flag           IN     VARCHAR2 DEFAULT 'NO',
     p_redefault_flag               IN     VARCHAR2 DEFAULT 'NO'
);

PROCEDURE do_retirement(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_retirement_id                   OUT NOCOPY NUMBER,
     x_transaction_header_id           OUT NOCOPY NUMBER,
     x_dist_transaction_header_id      OUT NOCOPY NUMBER,
     -- Transaction Info (Retirement) --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Transaction Info (Distributions) --
     p_dist_transaction_name        IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute1              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute2              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute3              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute4              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute5              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute6              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute7              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute8              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute9              IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute10             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute11             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute12             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute13             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute14             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute15             IN     VARCHAR2 DEFAULT NULL,
     p_dist_attribute_category_code IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Retirement Info --
     p_calculate_gain_loss          IN     VARCHAR2 DEFAULT FND_API.G_FALSE,
     p_units_retired                IN     NUMBER   DEFAULT NULL,
     p_cost_retired                 IN     NUMBER   DEFAULT NULL,
     p_proceeds_of_sale             IN     NUMBER   DEFAULT NULL,
     p_cost_of_removal              IN     NUMBER   DEFAULT NULL,
     p_retirement_type_code         IN     VARCHAR2 DEFAULT NULL,
     p_retire_prorate_convention    IN     VARCHAR2 DEFAULT NULL,
     p_stl_method_code              IN     VARCHAR2 DEFAULT NULL,
     p_stl_life_in_months           IN     NUMBER   DEFAULT NULL,
     p_sold_to                      IN     VARCHAR2 DEFAULT NULL,
     p_trade_in_asset_id            IN     NUMBER   DEFAULT NULL,
     p_status                       IN     VARCHAR2 DEFAULT NULL,
     p_reference_num                IN     VARCHAR2 DEFAULT NULL,
     p_recognize_gain_loss          IN     VARCHAR2 DEFAULT NULL,
     p_recapture_reserve_flag       IN     VARCHAR2 DEFAULT NULL,
     p_limit_proceeds_flag          IN     VARCHAR2 DEFAULT NULL,
     p_terminal_gain_loss           IN     VARCHAR2 DEFAULT NULL,
     p_reduction_rate               IN     NUMBER   DEFAULT NULL,
     p_reserve_retired              IN     NUMBER   DEFAULT NULL,
     p_eofy_reserve                 IN     NUMBER   DEFAULT NULL,
     p_ret_attribute1               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute2               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute3               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute4               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute5               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute6               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute7               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute8               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute9               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute10              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute11              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute12              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute13              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute14              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute15              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute_category_code  IN     VARCHAR2 DEFAULT NULL
);

PROCEDURE undo_retirement(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Transaction Info (Retirement) --
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_last_update_login            IN     NUMBER,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Retirement Info --
     p_retirement_id                IN     NUMBER   DEFAULT NULL,
     p_status                       IN     VARCHAR2 DEFAULT NULL
);

PROCEDURE do_reinstatement(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Retirement Info --
     p_calculate_gain_loss          IN     VARCHAR2 DEFAULT FND_API.G_FALSE,
     p_retirement_id                IN     NUMBER   DEFAULT NULL,
     p_proceeds_of_sale             IN     NUMBER   DEFAULT NULL,
     p_cost_of_removal              IN     NUMBER   DEFAULT NULL,
     p_retirement_type_code         IN     VARCHAR2 DEFAULT NULL,
     p_retire_prorate_convention    IN     VARCHAR2 DEFAULT NULL,
     p_sold_to                      IN     VARCHAR2 DEFAULT NULL,
     p_trade_in_asset_id            IN     NUMBER   DEFAULT NULL,
     p_status                       IN     VARCHAR2 DEFAULT NULL,
     p_reference_num                IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute1               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute2               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute3               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute4               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute5               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute6               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute7               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute8               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute9               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute10              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute11              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute12              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute13              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute14              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute15              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute_category_code  IN     VARCHAR2 DEFAULT NULL
);

PROCEDURE undo_reinstatement(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Transaction Info (Retirement) --
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_last_update_login            IN     NUMBER,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Retirement Info --
     p_retirement_id                IN     NUMBER   DEFAULT NULL,
     p_status                       IN     VARCHAR2 DEFAULT NULL
);

PROCEDURE do_capitalization (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Financial Info --
     p_date_placed_in_service       IN     DATE
);

PROCEDURE do_reverse (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Financial Info --
     p_date_placed_in_service       IN     DATE
);

PROCEDURE do_asset_desc_update (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     p_reset_miss_flag              IN     VARCHAR2 DEFAULT 'NO',
     -- Transaction Info --
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_last_update_login            IN     NUMBER,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     -- Asset Description Info --
     p_asset_number                 IN     VARCHAR2 DEFAULT NULL,
     p_description                  IN     VARCHAR2 DEFAULT NULL,
     p_tag_number                   IN     VARCHAR2 DEFAULT NULL,
     p_serial_number                IN     VARCHAR2 DEFAULT NULL,
     p_asset_key_ccid               IN     NUMBER   DEFAULT NULL,
     p_current_units                IN     NUMBER   DEFAULT NULL,
     p_parent_asset_id              IN     NUMBER   DEFAULT NULL,
     p_status                       IN     VARCHAR2 DEFAULT NULL,
     p_manufacturer_name            IN     VARCHAR2 DEFAULT NULL,
     p_model_number                 IN     VARCHAR2 DEFAULT NULL,
     p_warranty_id                  IN     NUMBER   DEFAULT NULL,
     p_property_type_code           IN     VARCHAR2 DEFAULT NULL,
     p_property_1245_1250_code      IN     VARCHAR2 DEFAULT NULL,
     p_in_use_flag                  IN     VARCHAR2 DEFAULT NULL,
     p_inventorial                  IN     VARCHAR2 DEFAULT NULL,
     p_commitment		    IN     VARCHAR2 DEFAULT NULL,
     p_investment_law		    IN     VARCHAR2 DEFAULT NULL,
     p_owned_leased                 IN     VARCHAR2 DEFAULT NULL,
     p_new_used                     IN     VARCHAR2 DEFAULT NULL,
     p_lease_id                     IN     NUMBER   DEFAULT NULL,
     p_ls_attribute1                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute2                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute3                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute4                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute5                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute6                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute7                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute8                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute9                IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute10               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute11               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute12               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute13               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute14               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute15               IN     VARCHAR2 DEFAULT NULL,
     p_ls_attribute_category_code   IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute1         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute2         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute3         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute4         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute5         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute6         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute7         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute8         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute9         IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute10        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute11        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute12        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute13        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute14        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute15        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute16        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute17        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute18        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute19        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute20        IN     VARCHAR2 DEFAULT NULL,
     p_ad_global_attribute_category IN     VARCHAR2 DEFAULT NULL,
     -- Asset Category Info --
     p_cat_attribute1               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute2               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute3               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute4               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute5               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute6               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute7               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute8               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute9               IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute10              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute11              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute12              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute13              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute14              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute15              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute16              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute17              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute18              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute19              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute20              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute21              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute22              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute23              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute24              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute25              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute26              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute27              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute28              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute29              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute30              IN     VARCHAR2 DEFAULT NULL,
     p_cat_attribute_category_code  IN     VARCHAR2 DEFAULT NULL,
     p_context                      IN     VARCHAR2 DEFAULT NULL
);

PROCEDURE do_invoice_desc_update (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     p_reset_miss_flag              IN     VARCHAR2 DEFAULT 'NO',
     -- Transaction Info --
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_last_update_login            IN     NUMBER,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL
);

PROCEDURE do_retirement_desc_update (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     p_reset_miss_flag              IN     VARCHAR2 DEFAULT 'NO',
     -- Transaction Info (Retirement) --
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_last_update_login            IN     NUMBER,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Asset Retirement Info --
     p_retirement_id                IN     NUMBER,
     p_proceeds_of_sale             IN     NUMBER   DEFAULT NULL,
     p_cost_of_removal              IN     NUMBER   DEFAULT NULL,
     p_retirement_type_code         IN     VARCHAR2 DEFAULT NULL,
     p_retire_prorate_convention    IN     VARCHAR2 DEFAULT NULL,
     p_sold_to                      IN     VARCHAR2 DEFAULT NULL,
     p_trade_in_asset_id            IN     NUMBER   DEFAULT NULL,
     p_status                       IN     VARCHAR2 DEFAULT NULL,
     p_reference_num                IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute1               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute2               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute3               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute4               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute5               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute6               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute7               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute8               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute9               IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute10              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute11              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute12              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute13              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute14              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute15              IN     VARCHAR2 DEFAULT NULL,
     p_ret_attribute_category_code  IN     VARCHAR2 DEFAULT NULL
);

PROCEDURE do_unplanned (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_transaction_subtype          IN     VARCHAR2 DEFAULT NULL,
     p_amortization_start_date      IN     DATE     DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     p_set_of_books_id              IN     NUMBER   DEFAULT NULL,
     -- Unplanned Depreciation Info --
     p_code_combination_id          IN     NUMBER,
     p_unplanned_amount             IN     NUMBER,
     p_unplanned_type               IN     VARCHAR2 DEFAULT NULL
);

PROCEDURE do_reserve_transfer (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_src_transaction_header_id       OUT NOCOPY NUMBER,
     x_dest_transaction_header_id      OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_transaction_subtype          IN     VARCHAR2 DEFAULT NULL,
     p_amortization_start_date      IN     DATE     DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_src_asset_id                     IN     NUMBER,  -- Source Asset Id
     p_book_type_code               IN     VARCHAR2,-- Source Book Type Code
     -- Reserve Transfer Info --
     p_transfer_amount              IN     NUMBER,
     p_dest_asset_id                IN     NUMBER   -- Destination Asset Id
);

PROCEDURE do_retirement_adjustment (
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_date_entered     IN     DATE     DEFAULT NULL,
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_transaction_subtype          IN     VARCHAR2 DEFAULT NULL,
     p_amortization_start_date      IN     DATE     DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     -- Retirement Adjustment Info --
     p_proceeds_of_sale             IN     NUMBER,
     p_cost_of_removal              IN     NUMBER
);

PROCEDURE do_tax_reserve_adjustment(
     -- Standard Parameters --
     p_api_version                  IN     NUMBER,
     p_init_msg_list                IN     VARCHAR2 := FND_API.G_TRUE,
     p_commit                       IN     VARCHAR2 := FND_API.G_FALSE,
     p_validation_level             IN     NUMBER := FND_API.G_VALID_LEVEL_FULL,
     x_return_status                   OUT NOCOPY VARCHAR2,
     x_msg_count                       OUT NOCOPY NUMBER,
     x_msg_data                        OUT NOCOPY VARCHAR2,
     p_calling_fn                   IN     VARCHAR2,
     -- API Options --
     p_debug_flag                   IN     VARCHAR2 DEFAULT 'NO',
     -- Out Parameters --
     x_transaction_header_id           OUT NOCOPY NUMBER,
     -- Transaction Info --
     p_transaction_name             IN     VARCHAR2 DEFAULT NULL,
     p_mass_reference_id            IN     NUMBER   DEFAULT NULL,
     p_calling_interface            IN     VARCHAR2 DEFAULT 'CUSTOM',
     p_last_update_date             IN     DATE,
     p_last_updated_by              IN     NUMBER,
     p_created_by                   IN     NUMBER,
     p_creation_date                IN     DATE,
     p_last_update_login            IN     NUMBER,
     p_attribute1                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute2                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute3                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute4                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute5                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute6                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute7                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute8                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute9                   IN     VARCHAR2 DEFAULT NULL,
     p_attribute10                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute11                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute12                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute13                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute14                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute15                  IN     VARCHAR2 DEFAULT NULL,
     p_attribute_category_code      IN     VARCHAR2 DEFAULT NULL,
     -- Asset Header Info --
     p_asset_id                     IN     NUMBER,
     p_book_type_code               IN     VARCHAR2,
     -- Tax Reserve Adjustment Info --
     p_fiscal_year                  IN     NUMBER,
     p_adjusted_ytd_deprn           IN OUT NOCOPY NUMBER,      -- Delta (New_FY_Ytd_Deprn - Old_FY_Ytd_Deprn)
     p_deprn_basis_formula          IN     NUMBER,
     p_run_mode                     IN     VARCHAR2 DEFAULT 'RUN'
);

END FA_TRANS_API_PUB;

/
