--------------------------------------------------------
--  DDL for Package FND_GUIDELINES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."FND_GUIDELINES" AUTHID CURRENT_USER AS
   /* $Header: AFSCGDLS.pls 120.0.12010000.6 2021/02/01 16:18:14 dgooty noship $*/
    -- UTIL METHODS/PROCEDURES
    FUNCTION check_status_table(
      p_code IN VARCHAR2)
    RETURN VARCHAR2;
    PROCEDURE update_status_table(
      p_code    IN VARCHAR2,
      p_status  IN VARCHAR2,
      P_DETAILS IN VARCHAR2);
    PROCEDURE set_detailed_response(
	  p_status IN varchar2);
    PROCEDURE ADD_DETAILED_RESPONSE(
	  P_MESSAGE IN CLOB,
      P_RESPONSE IN OUT NOCOPY CLOB);
    FUNCTION BOOL_TO_CHAR(
	  P_BOOL IN BOOLEAN)
	  RETURN VARCHAR2;

    -- ENTRY POINT PROCEDURES
    PROCEDURE CHECK_ALL;
    PROCEDURE check_guideline(
      p_code        IN VARCHAR2,
      P_STATUS_CODE OUT NOCOPY VARCHAR2);
    PROCEDURE check_guideline(
      p_code        IN VARCHAR2,
      p_status_code OUT NOCOPY VARCHAR2,
      p_message		OUT NOCOPY VARCHAR2,
      p_details    OUT NOCOPY CLOB);
    PROCEDURE fix_guideline(
      p_code        IN VARCHAR2,
      p_status_code OUT NOCOPY VARCHAR2,
      p_message		OUT NOCOPY VARCHAR2,
      p_details    OUT NOCOPY CLOB);

    -- CHECK PROCEDURES
    PROCEDURE check_fnd_apps_def_pswd(
      P_STATUS  OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      p_details OUT NOCOPY CLOB);
    PROCEDURE check_fnd_db_def_pswd(
      p_status  OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      p_details OUT NOCOPY CLOB);
    PROCEDURE check_fnd_applsyspub(
	  p_status OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      p_details OUT NOCOPY CLOB);
    PROCEDURE check_fnd_cookie_dom(
	  p_status OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      p_details OUT NOCOPY CLOB);
	PROCEDURE check_FND_PROF_ERRORS(
	  p_status OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      p_details OUT NOCOPY CLOB);
    PROCEDURE CHECK_FND_UNREST_REDIR(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE CHECK_FND_PSWD_HASH(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE CHECK_FND_SERVER_SEC(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE check_FND_MISS_PROF(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE check_FND_MISS_ATT_PROF(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE check_FND_SSL_ENABLED(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE check_FND_JSP_UNREST_ACC(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE check_FND_AUDIT_PROF(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE check_FND_APPS_IND_PUBLIC(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE check_WF_ADMIN_NOT_PUBLIC(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
  PROCEDURE check_FND_INIT_ORA_PARAMS(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);

 -- New checks introduce in Bug 25768750
  PROCEDURE check_WF_EMAIL_LOGIN(
	  P_STATUS OUT NOCOPY VARCHAR2,
	  P_MESSAGE OUT NOCOPY VARCHAR2,
	  P_DETAILS OUT NOCOPY CLOB);
  PROCEDURE check_SEC_DB_PSWD_PROF(
	  P_STATUS OUT NOCOPY VARCHAR2,
	  P_MESSAGE OUT NOCOPY VARCHAR2,
	  P_DETAILS OUT NOCOPY CLOB);
  PROCEDURE check_IREC_FILE_UPLOAD(
	  P_STATUS OUT NOCOPY VARCHAR2,
	  P_MESSAGE OUT NOCOPY VARCHAR2,
	  P_DETAILS OUT NOCOPY CLOB);
  PROCEDURE check_FND_ATTCH_FILE_PROF(
	  P_STATUS OUT NOCOPY VARCHAR2,
	  P_MESSAGE OUT NOCOPY VARCHAR2,
	  P_DETAILS OUT NOCOPY CLOB);

    -- FIX PROCEDURES
    PROCEDURE FIX_FND_APPLSYSPUB(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
	  P_DETAILS OUT NOCOPY CLOB);
    PROCEDURE FIX_FND_COOKIE_DOM(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
    PROCEDURE FIX_FND_UNREST_REDIR(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE fix_FND_JSP_UNREST_ACC(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE fix_FND_PROF_ERRORS(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE fix_FND_AUDIT_PROF(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
	PROCEDURE fix_IREC_FILE_UPLOAD(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
    PROCEDURE check_db_network_acl(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
    PROCEDURE check_FNDGFM_authorization(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);
    PROCEDURE check_unused_resources(
	  P_STATUS OUT NOCOPY VARCHAR2,
      P_MESSAGE OUT NOCOPY VARCHAR2,
      P_DETAILS OUT NOCOPY CLOB);

  function allowed_resources_prof_exist return boolean;
  function allowed_jsps_prof_exist return boolean;

  END fnd_guidelines;

/
