--------------------------------------------------------
--  DDL for Package GMF_CMR10USR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."GMF_CMR10USR_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CMR10USRS.pls 120.0 2007/12/24 13:22:43 nchinnam noship $ */
  FROM_ALLOC_CODE VARCHAR2(40);

  P_FROM_ALLOC_CODE VARCHAR2(40);

  TO_ALLOC_CODE VARCHAR2(40);

  P_TO_ALLOC_CODE VARCHAR2(40);

  USER_ID NUMBER;

  SY_ALL VARCHAR2(5);

  NONBLOCKSQL VARCHAR2(5);

  LEGAL_ENTITY_ID NUMBER;

  P_CONC_REQUEST_ID NUMBER;

  ALLOCATIONCP VARCHAR2(600);

  FUNCTION ALLOCATIONCFFORMULA RETURN VARCHAR2;

  FUNCTION ALLOCATIONCPFORMULA(ALLOCATIONCF IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  PROCEDURE GMF_CMR10USR_XMLP_PKG_HEADER;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION CF_LEGAL_ENTITYFORMULA RETURN CHAR;

  FUNCTION FROM_ACCOUNTFORMULA(FROM_ACCOUNT_ID IN NUMBER) RETURN CHAR;

  FUNCTION TO_ACCOUNTFORMULA(TO_ACCOUNT_ID IN NUMBER) RETURN CHAR;

  FUNCTION BASIS_ACCOUNT_CODEFORMULA(BASIS_ACCOUNT_ID IN NUMBER) RETURN CHAR;

  FUNCTION BASIS_ACCOUNT_DESCFORMULA(BASIS_ACCOUNT_ID IN NUMBER) RETURN CHAR;

  FUNCTION FROM_ACCOUNT_DESCFORMULA(FROM_ACCOUNT_ID IN NUMBER) RETURN CHAR;

  FUNCTION TO_ACCOUNT_DESCFORMULA(TO_ACCOUNT_ID IN NUMBER) RETURN CHAR;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION ALLOCATIONCP_P RETURN VARCHAR2;

END GMF_CMR10USR_XMLP_PKG;


/
