--------------------------------------------------------
--  DDL for Package GMI_RILSM_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."GMI_RILSM_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: RILSMS.pls 120.0 2007/12/24 13:27:46 nchinnam noship $ */
  FROM_STATUS VARCHAR2(4);

  TO_STATUS VARCHAR2(4);

  SELECT_CRITERIA VARCHAR2(7);

  ORDER1 VARCHAR2(10);

  P_ORGN VARCHAR2(4);

  USER_ID NUMBER;

  USER_ID_1 NUMBER;

  NONBLOCKSQL VARCHAR2(3);

  P_CONC_REQUEST_ID NUMBER;

  FROM_STATUSCP VARCHAR2(4);

  TO_STATUSCP VARCHAR2(4);

  FUNCTION RANGECFFORMULA RETURN VARCHAR2;

  FUNCTION ORDERCFFORMULA RETURN VARCHAR2;

  FUNCTION USERCFFORMULA RETURN VARCHAR2;

  FUNCTION FROM_ITEMCFFORMULA RETURN VARCHAR2;

  FUNCTION TO_STATUSCFFORMULA RETURN VARCHAR2;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION FROM_STATUSCP_P RETURN VARCHAR2;

  FUNCTION TO_STATUSCP_P RETURN VARCHAR2;

END GMI_RILSM_XMLP_PKG;


/
