--------------------------------------------------------
--  DDL for Package GMI_CMXFER01_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."GMI_CMXFER01_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: CMXFER01S.pls 120.0 2007/12/24 13:12:56 nchinnam noship $ */
  P_FROM_RELEASE_DATE DATE;

  P_TO_RELEASE_DATE DATE;

  P_FROM_WAREHOUSE VARCHAR2(10);

  P_TO_WAREHOUSE VARCHAR2(10);

  P_FROM_DESTINATION_WAREHOUSE VARCHAR2(10);

  P_TO_DESTINATION_WAREHOUSE VARCHAR2(10);

  P_FROM_TRANSFER_STATUS VARCHAR2(80);

  P_TO_TRANSFER_STATUS VARCHAR2(80);

  LP_FROM_RELEASE_DATE varchar2(25);
LP_TO_RELEASE_DATE varchar2(25);
LP_FROM_SCHEDULED_RELEASE_DATE varchar2(25);
LP_TO_SCHEDULED_RELEASE_DATE varchar2(25);
LP_FROM_ACTUAL_RECEIVE_DATE varchar2(25);
LP_TO_ACTUAL_RECEIVE_DATE varchar2(25);
LP_FROM_CANCEL_DATE varchar2(25);
LP_TO_CANCEL_DATE varchar2(25);

LP_FROM_WAREHOUSE VARCHAR2(10);

  LP_TO_WAREHOUSE VARCHAR2(10);

  LP_FROM_DESTINATION_WAREHOUSE VARCHAR2(10);

  LP_TO_DESTINATION_WAREHOUSE VARCHAR2(10);

  LP_FROM_TRANSFER_STATUS VARCHAR2(80);

  LP_TO_TRANSFER_STATUS VARCHAR2(80);

  P_FROM_ACTUAL_RECEIVE_DATE DATE;

  P_TO_ACTUAL_RECEIVE_DATE DATE;

  P_FROM_CANCEL_DATE DATE;

  P_TO_CANCEL_DATE DATE;

  P_FROM_SCHEDULED_RELEASE_DATE DATE;

  P_TO_SCHEDULED_RELEASE_DATE DATE;

  USER_ID VARCHAR2(40);

  P_ORGN VARCHAR2(40);

  P_CONC_REQUEST_ID NUMBER;

  RELEASEDATECP VARCHAR2(200);

  SOURCEWAREHOUSECP VARCHAR2(200);

  DESTINATIONWAREHOUSECP VARCHAR2(200);

  TRANSFERSTATUSCP VARCHAR2(200);

  SCHEDULEDSHIPDATECP VARCHAR2(200);

  CANCELDATECP VARCHAR2(200);

  ACTUALRECEIVEDATECP VARCHAR2(200);

  FUNCTION RELEASEDATECFFORMULA RETURN VARCHAR2;

  FUNCTION SOURCEWAREHOUSECFFORMULA RETURN VARCHAR2;

  FUNCTION DESTINATIONWAREHOUSECFFORMULA RETURN VARCHAR2;

  FUNCTION TREANSFERSTATUSCFFORMULA RETURN VARCHAR2;

  FUNCTION SCHEDULEDSHIPDATECFFORMULA RETURN VARCHAR2;

  FUNCTION CANCELDATECFFORMULA RETURN VARCHAR2;

  FUNCTION ACTUALRECEIVEDATECFFORMULA RETURN VARCHAR2;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  PROCEDURE HEADER;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION RELEASEDATECP_P RETURN VARCHAR2;

  FUNCTION SOURCEWAREHOUSECP_P RETURN VARCHAR2;

  FUNCTION DESTINATIONWAREHOUSECP_P RETURN VARCHAR2;

  FUNCTION TRANSFERSTATUSCP_P RETURN VARCHAR2;

  FUNCTION SCHEDULEDSHIPDATECP_P RETURN VARCHAR2;

  FUNCTION CANCELDATECP_P RETURN VARCHAR2;

  FUNCTION ACTUALRECEIVEDATECP_P RETURN VARCHAR2;

END GMI_CMXFER01_XMLP_PKG;


/
