--------------------------------------------------------
--  DDL for Package GMO_DATATYPES_GRP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."GMO_DATATYPES_GRP" AUTHID CURRENT_USER AS
/* $Header: GMOGDTPS.pls 120.0 2005/06/27 23:47 swasubra noship $ */


TYPE CONTEXT_PARAMS_REC_TYPE IS RECORD (NAME VARCHAR2(200), VALUE VARCHAR2(400));
TYPE CONTEXT_PARAMS_TBL_TYPE IS TABLE OF CONTEXT_PARAMS_REC_TYPE INDEX BY BINARY_INTEGER;

TYPE GMO_TABLE_OF_VARCHAR2_255 IS TABLE OF VARCHAR2(255)
INDEX BY BINARY_INTEGER;

TYPE GMO_DEFINITION_PARAM_REC_TYPE IS RECORD
(
    NAME VARCHAR2(100),
    VALUE VARCHAR2(1000)
);

TYPE GMO_DEFINITION_PARAM_TBL_TYPE IS TABLE OF GMO_DEFINITION_PARAM_REC_TYPE
INDEX BY BINARY_INTEGER;

TYPE GMO_INSTRUCTION_REC_TYPE IS RECORD
(
    INSTRUCTION_ID NUMBER,
    INSTRUCTION_SET_ID NUMBER,
    INSTRUCTION_TEXT VARCHAR2(4000),
    TASK_NAME VARCHAR2(200),
    TASK_ATTRIBUTE VARCHAR2(200),
    TASK_DISPLAY_NAME VARCHAR2(1000)
);

TYPE GMO_INSTRUCTION_TBL_TYPE IS TABLE OF GMO_INSTRUCTION_REC_TYPE
INDEX BY BINARY_INTEGER;


END GMO_DATATYPES_GRP;

 

/
