--------------------------------------------------------
--  DDL for Package GMO_INSTR_INSTANCE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."GMO_INSTR_INSTANCE_PKG" AUTHID CURRENT_USER as
/* $Header: GMOINIPS.pls 120.0 2005/06/29 04:24 shthakke noship $ */

procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_INSTRUCTION_ID in NUMBER,
  X_OPERATOR_ACKN in VARCHAR2,
  X_TASK_ATTRIBUTE in VARCHAR2,
  X_TASK_ATTRIBUTE_ID in VARCHAR2,
  X_INSTRUCTION_SET_ID in NUMBER,
  X_INSTR_NUMBER in VARCHAR2,
  X_INSTR_STATUS in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_TASK_ACKN_DATE in DATE,
  X_TASK_ACKN_STATUS in VARCHAR2,
  X_INSTR_SEQ in NUMBER,
  X_INSTR_ACKN_TYPE in VARCHAR2,
  X_INSTRUCTION_TEXT in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_TASK_LABEL in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_INSTRUCTION_ID in NUMBER,
  X_OPERATOR_ACKN in VARCHAR2,
  X_TASK_ATTRIBUTE in VARCHAR2,
  X_TASK_ATTRIBUTE_ID in VARCHAR2,
  X_INSTRUCTION_SET_ID in NUMBER,
  X_INSTR_NUMBER in VARCHAR2,
  X_INSTR_STATUS in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_TASK_ACKN_DATE in DATE,
  X_TASK_ACKN_STATUS in VARCHAR2,
  X_INSTR_SEQ in NUMBER,
  X_INSTR_ACKN_TYPE in VARCHAR2,
  X_INSTRUCTION_TEXT in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_TASK_LABEL in VARCHAR2
);
procedure UPDATE_ROW (
  X_INSTRUCTION_ID in NUMBER,
  X_OPERATOR_ACKN in VARCHAR2,
  X_TASK_ATTRIBUTE in VARCHAR2,
  X_TASK_ATTRIBUTE_ID in VARCHAR2,
  X_INSTRUCTION_SET_ID in NUMBER,
  X_INSTR_NUMBER in VARCHAR2,
  X_INSTR_STATUS in VARCHAR2,
  X_TASK_ID in NUMBER,
  X_TASK_ACKN_DATE in DATE,
  X_TASK_ACKN_STATUS in VARCHAR2,
  X_INSTR_SEQ in NUMBER,
  X_INSTR_ACKN_TYPE in VARCHAR2,
  X_INSTRUCTION_TEXT in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_TASK_LABEL in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_INSTRUCTION_ID in NUMBER
);
procedure ADD_LANGUAGE;
end GMO_INSTR_INSTANCE_PKG;

 

/
