--------------------------------------------------------
--  DDL for Package HR_DOCUMENT_TYPES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HR_DOCUMENT_TYPES_PKG" AUTHID CURRENT_USER as
/* $Header: perditlct.pkh 120.0 2005/06/24 07:52:47 appldev noship $ */
--
procedure INSERT_ROW (
  X_DOCUMENT_TYPE_ID in NUMBER,
  X_SYSTEM_DOCUMENT_TYPE in VARCHAR2,
  X_CATEGORY_CODE in VARCHAR2,
  X_SUB_CATEGORY_CODE in VARCHAR2,
  X_ACTIVE_INACTIVE_FLAG in VARCHAR2,
  X_MULTIPLE_OCCURENCES_FLAG in VARCHAR2,
  X_LEGISLATION_CODE in VARCHAR2,
  X_AUTHORIZATION_REQUIRED in VARCHAR2,
  X_WARNING_PERIOD in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DOCUMENT_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
--
procedure UPDATE_ROW (
  X_DOCUMENT_TYPE_ID in NUMBER,
  X_SYSTEM_DOCUMENT_TYPE in VARCHAR2,
  X_CATEGORY_CODE in VARCHAR2,
  X_SUB_CATEGORY_CODE in VARCHAR2,
  X_ACTIVE_INACTIVE_FLAG in VARCHAR2,
  X_MULTIPLE_OCCURENCES_FLAG in VARCHAR2,
  X_LEGISLATION_CODE in VARCHAR2,
  X_AUTHORIZATION_REQUIRED in VARCHAR2,
  X_WARNING_PERIOD in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DOCUMENT_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
--
procedure DELETE_ROW (
  X_DOCUMENT_TYPE_ID in NUMBER
);
--
procedure ADD_LANGUAGE;
--
procedure LOAD_ROW (
  X_SYSTEM_DOCUMENT_TYPE in VARCHAR2,
  X_CATEGORY_CODE in VARCHAR2,
  X_SUB_CATEGORY_CODE in VARCHAR2,
  X_ACTIVE_INACTIVE_FLAG in VARCHAR2,
  X_MULTIPLE_OCCURENCES_FLAG in VARCHAR2,
  X_LEGISLATION_CODE in VARCHAR2,
  X_AUTHORIZATION_REQUIRED in VARCHAR2,
  X_WARNING_PERIOD in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_OWNER in VARCHAR2,
  X_DOCUMENT_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2
);
--
procedure TRANSLATE_ROW (
  X_SYSTEM_DOCUMENT_TYPE in VARCHAR2,
  X_LEGISLATION_CODE in VARCHAR2,
  X_DOCUMENT_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_OWNER in VARCHAR2
);
--
end HR_DOCUMENT_TYPES_PKG;

 

/
