--------------------------------------------------------
--  DDL for Package HR_LEGISLATION_SUBGROUPS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HR_LEGISLATION_SUBGROUPS_PKG" AUTHID CURRENT_USER as
/* $Header: pelsg01t.pkh 115.0 99/07/22 06:41:53 porting shi $ */
procedure INSERT_ROW (
  X_LEGISLATION_CODE in VARCHAR2,
  X_LEGISLATION_SUBGROUP in VARCHAR2,
  X_ACTIVE_INACTIVE_FLAG in VARCHAR2,
  X_LEGISLATION_SUBGROUP_NAME in VARCHAR2
);
procedure LOCK_ROW (
  X_LEGISLATION_CODE in VARCHAR2,
  X_LEGISLATION_SUBGROUP in VARCHAR2,
  X_ACTIVE_INACTIVE_FLAG in VARCHAR2
);
procedure UPDATE_ROW (
  X_LEGISLATION_CODE in VARCHAR2,
  X_LEGISLATION_SUBGROUP in VARCHAR2,
  X_ACTIVE_INACTIVE_FLAG in VARCHAR2,
  X_LEGISLATION_SUBGROUP_NAME in VARCHAR2
);
procedure DELETE_ROW (
  X_LEGISLATION_CODE in VARCHAR2,
  X_LEGISLATION_SUBGROUP in VARCHAR2
);
procedure LOAD_ROW (
  X_LEGISLATION_CODE in VARCHAR2,
  X_LEGISLATION_SUBGROUP in VARCHAR2,
  X_ACTIVE_INACTIVE_FLAG in VARCHAR2,
  X_LEGISLATION_SUBGROUP_NAME in VARCHAR2,
  X_OWNER in VARCHAR2
);
procedure TRANSLATE_ROW (
  X_LEGISLATION_CODE in VARCHAR2,
  X_LEGISLATION_SUBGROUP in VARCHAR2,
  X_LEGISLATION_SUBGROUP_NAME in VARCHAR2,
  X_OWNER in VARCHAR2
);
end HR_LEGISLATION_SUBGROUPS_PKG;

 

/
