--------------------------------------------------------
--  DDL for Package HR_PREVIOUS_EMPLOYMENT_BE5
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HR_PREVIOUS_EMPLOYMENT_BE5" AUTHID CURRENT_USER as 
--Code generated on 29/08/2013 10:00:57
/* $Header: hrapiwfe.pkb 120.4.12010000.2 2008/09/29 12:54:07 srgnanas ship $*/
procedure update_previous_job_a (
p_effective_date               date,
p_previous_job_id              number,
p_start_date                   date,
p_end_date                     date,
p_period_years                 number,
p_period_months                number,
p_period_days                  number,
p_job_name                     varchar2,
p_employment_category          varchar2,
p_description                  varchar2,
p_all_assignments              varchar2,
p_pjo_attribute_category       varchar2,
p_pjo_attribute1               varchar2,
p_pjo_attribute2               varchar2,
p_pjo_attribute3               varchar2,
p_pjo_attribute4               varchar2,
p_pjo_attribute5               varchar2,
p_pjo_attribute6               varchar2,
p_pjo_attribute7               varchar2,
p_pjo_attribute8               varchar2,
p_pjo_attribute9               varchar2,
p_pjo_attribute10              varchar2,
p_pjo_attribute11              varchar2,
p_pjo_attribute12              varchar2,
p_pjo_attribute13              varchar2,
p_pjo_attribute14              varchar2,
p_pjo_attribute15              varchar2,
p_pjo_attribute16              varchar2,
p_pjo_attribute17              varchar2,
p_pjo_attribute18              varchar2,
p_pjo_attribute19              varchar2,
p_pjo_attribute20              varchar2,
p_pjo_attribute21              varchar2,
p_pjo_attribute22              varchar2,
p_pjo_attribute23              varchar2,
p_pjo_attribute24              varchar2,
p_pjo_attribute25              varchar2,
p_pjo_attribute26              varchar2,
p_pjo_attribute27              varchar2,
p_pjo_attribute28              varchar2,
p_pjo_attribute29              varchar2,
p_pjo_attribute30              varchar2,
p_pjo_information_category     varchar2,
p_pjo_information1             varchar2,
p_pjo_information2             varchar2,
p_pjo_information3             varchar2,
p_pjo_information4             varchar2,
p_pjo_information5             varchar2,
p_pjo_information6             varchar2,
p_pjo_information7             varchar2,
p_pjo_information8             varchar2,
p_pjo_information9             varchar2,
p_pjo_information10            varchar2,
p_pjo_information11            varchar2,
p_pjo_information12            varchar2,
p_pjo_information13            varchar2,
p_pjo_information14            varchar2,
p_pjo_information15            varchar2,
p_pjo_information16            varchar2,
p_pjo_information17            varchar2,
p_pjo_information18            varchar2,
p_pjo_information19            varchar2,
p_pjo_information20            varchar2,
p_pjo_information21            varchar2,
p_pjo_information22            varchar2,
p_pjo_information23            varchar2,
p_pjo_information24            varchar2,
p_pjo_information25            varchar2,
p_pjo_information26            varchar2,
p_pjo_information27            varchar2,
p_pjo_information28            varchar2,
p_pjo_information29            varchar2,
p_pjo_information30            varchar2,
p_object_version_number        number);
end hr_previous_employment_be5;

/
