--------------------------------------------------------
--  DDL for Package HRDPP_CREATE_ELEMENT_ENTRY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HRDPP_CREATE_ELEMENT_ENTRY" as
/*
 * Generated by hr_pump_meta_mapper at: 2018/06/16 10:06:07
 * Generated for API: PY_ELEMENT_ENTRY_API.CREATE_ELEMENT_ENTRY
 */
--
g_generator_version constant varchar2(128) default '$Revision: 120.4.12010000.1 $';
--

function dc(p in date) return varchar2;
pragma restrict_references(dc,WNDS);

function d(p in varchar2) return date;
pragma restrict_references(d,WNDS);
function n(p in varchar2) return number;
pragma restrict_references(n,WNDS);
function dd(p in date,i in varchar2) return varchar2;
pragma restrict_references(dd,WNDS);
function nd(p in number,i in varchar2) return varchar2;
pragma restrict_references(nd,WNDS);
--
procedure insert_batch_lines
(p_batch_id      in number
,p_data_pump_batch_line_id in number default null
,p_data_pump_business_grp_name in varchar2 default null
,p_user_sequence in number default null
,p_link_value    in number default null
,P_EFFECTIVE_DATE in date
,P_ENTRY_TYPE in varchar2
,P_CREATOR_TYPE in varchar2 default null
,P_UPDATING_ACTION_TYPE in varchar2 default null
,P_REASON in varchar2 default null
,P_SUBPRIORITY in number default null
,P_DATE_EARNED in date default null
,P_ATTRIBUTE_CATEGORY in varchar2 default null
,P_ATTRIBUTE1 in varchar2 default null
,P_ATTRIBUTE2 in varchar2 default null
,P_ATTRIBUTE3 in varchar2 default null
,P_ATTRIBUTE4 in varchar2 default null
,P_ATTRIBUTE5 in varchar2 default null
,P_ATTRIBUTE6 in varchar2 default null
,P_ATTRIBUTE7 in varchar2 default null
,P_ATTRIBUTE8 in varchar2 default null
,P_ATTRIBUTE9 in varchar2 default null
,P_ATTRIBUTE10 in varchar2 default null
,P_ATTRIBUTE11 in varchar2 default null
,P_ATTRIBUTE12 in varchar2 default null
,P_ATTRIBUTE13 in varchar2 default null
,P_ATTRIBUTE14 in varchar2 default null
,P_ATTRIBUTE15 in varchar2 default null
,P_ATTRIBUTE16 in varchar2 default null
,P_ATTRIBUTE17 in varchar2 default null
,P_ATTRIBUTE18 in varchar2 default null
,P_ATTRIBUTE19 in varchar2 default null
,P_ATTRIBUTE20 in varchar2 default null
,P_ENTRY_VALUE1 in varchar2 default null
,P_ENTRY_VALUE2 in varchar2 default null
,P_ENTRY_VALUE3 in varchar2 default null
,P_ENTRY_VALUE4 in varchar2 default null
,P_ENTRY_VALUE5 in varchar2 default null
,P_ENTRY_VALUE6 in varchar2 default null
,P_ENTRY_VALUE7 in varchar2 default null
,P_ENTRY_VALUE8 in varchar2 default null
,P_ENTRY_VALUE9 in varchar2 default null
,P_ENTRY_VALUE10 in varchar2 default null
,P_ENTRY_VALUE11 in varchar2 default null
,P_ENTRY_VALUE12 in varchar2 default null
,P_ENTRY_VALUE13 in varchar2 default null
,P_ENTRY_VALUE14 in varchar2 default null
,P_ENTRY_VALUE15 in varchar2 default null
,P_ENTRY_INFORMATION_CATEGORY in varchar2 default null
,P_ENTRY_INFORMATION1 in varchar2 default null
,P_ENTRY_INFORMATION2 in varchar2 default null
,P_ENTRY_INFORMATION3 in varchar2 default null
,P_ENTRY_INFORMATION4 in varchar2 default null
,P_ENTRY_INFORMATION5 in varchar2 default null
,P_ENTRY_INFORMATION6 in varchar2 default null
,P_ENTRY_INFORMATION7 in varchar2 default null
,P_ENTRY_INFORMATION8 in varchar2 default null
,P_ENTRY_INFORMATION9 in varchar2 default null
,P_ENTRY_INFORMATION10 in varchar2 default null
,P_ENTRY_INFORMATION11 in varchar2 default null
,P_ENTRY_INFORMATION12 in varchar2 default null
,P_ENTRY_INFORMATION13 in varchar2 default null
,P_ENTRY_INFORMATION14 in varchar2 default null
,P_ENTRY_INFORMATION15 in varchar2 default null
,P_ENTRY_INFORMATION16 in varchar2 default null
,P_ENTRY_INFORMATION17 in varchar2 default null
,P_ENTRY_INFORMATION18 in varchar2 default null
,P_ENTRY_INFORMATION19 in varchar2 default null
,P_ENTRY_INFORMATION20 in varchar2 default null
,P_ENTRY_INFORMATION21 in varchar2 default null
,P_ENTRY_INFORMATION22 in varchar2 default null
,P_ENTRY_INFORMATION23 in varchar2 default null
,P_ENTRY_INFORMATION24 in varchar2 default null
,P_ENTRY_INFORMATION25 in varchar2 default null
,P_ENTRY_INFORMATION26 in varchar2 default null
,P_ENTRY_INFORMATION27 in varchar2 default null
,P_ENTRY_INFORMATION28 in varchar2 default null
,P_ENTRY_INFORMATION29 in varchar2 default null
,P_ENTRY_INFORMATION30 in varchar2 default null
,P_OVERRIDE_USER_ENT_CHK in varchar2 default null
,P_ELEMENT_ENTRY_USER_KEY in varchar2
,P_ORIGINAL_ENTRY_USER_KEY in varchar2 default null
,P_ASSIGNMENT_USER_KEY in varchar2
,P_ELEMENT_LINK_USER_KEY in varchar2
,P_COST_ALLOC_KEYFLEX_USER_KEY in varchar2 default null
,P_UPDATING_ACTION_USER_KEY in varchar2 default null
,P_COMMENT_USER_KEY in varchar2 default null
,P_TARGET_ENTRY_USER_KEY in varchar2 default null
,P_PERSONAL_PAY_METHOD_USER_KEY in varchar2 default null
,P_INPUT_VALUE_NAME1 in varchar2 default null
,P_ELEMENT_NAME in varchar2 default null
,P_LANGUAGE_CODE in varchar2 default null
,P_INPUT_VALUE_NAME2 in varchar2 default null
,P_INPUT_VALUE_NAME3 in varchar2 default null
,P_INPUT_VALUE_NAME4 in varchar2 default null
,P_INPUT_VALUE_NAME5 in varchar2 default null
,P_INPUT_VALUE_NAME6 in varchar2 default null
,P_INPUT_VALUE_NAME7 in varchar2 default null
,P_INPUT_VALUE_NAME8 in varchar2 default null
,P_INPUT_VALUE_NAME9 in varchar2 default null
,P_INPUT_VALUE_NAME10 in varchar2 default null
,P_INPUT_VALUE_NAME11 in varchar2 default null
,P_INPUT_VALUE_NAME12 in varchar2 default null
,P_INPUT_VALUE_NAME13 in varchar2 default null
,P_INPUT_VALUE_NAME14 in varchar2 default null
,P_INPUT_VALUE_NAME15 in varchar2 default null);
--
procedure call
(p_business_group_id in number,
p_batch_line_id     in number);
end hrdpp_CREATE_ELEMENT_ENTRY;

/
