--------------------------------------------------------
--  DDL for Package HRDPP_UPDATE_LIFE_EVENT_REASON
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HRDPP_UPDATE_LIFE_EVENT_REASON" as
/*
 * Generated by hr_pump_meta_mapper at: 2007/01/04 13:01:57
 * Generated for API: ben_life_event_reason_api.UPDATE_LIFE_EVENT_REASON
 */
--
g_generator_version constant varchar2(128) default '$Revision: 120.4  $';
--

function dc(p in date) return varchar2;
pragma restrict_references(dc,WNDS);

function d(p in varchar2) return date;
pragma restrict_references(d,WNDS);
function n(p in varchar2) return number;
pragma restrict_references(n,WNDS);
function dd(p in date,i in varchar2) return varchar2;
pragma restrict_references(dd,WNDS);
function nd(p in number,i in varchar2) return varchar2;
pragma restrict_references(nd,WNDS);
--
procedure insert_batch_lines
(p_batch_id      in number
,p_data_pump_batch_line_id in number default null
,p_data_pump_business_grp_name in varchar2 default null
,p_user_sequence in number default null
,p_link_value    in number default null
,P_NAME in varchar2 default null
,P_TYP_CD in varchar2 default null
,P_LF_EVT_OPER_CD in varchar2 default null
,P_SHORT_NAME in varchar2 default null
,P_SHORT_CODE in varchar2 default null
,P_PTNL_LER_TRTMT_CD in varchar2 default null
,P_CK_RLTD_PER_ELIG_FLAG in varchar2 default null
,P_LER_EVAL_RL in number default null
,I_LER_EVAL_RL in varchar2 default 'N'
,P_CM_APLY_FLAG in varchar2 default null
,P_OVRIDG_LE_FLAG in varchar2 default null
,P_QUALG_EVT_FLAG in varchar2 default null
,P_WHN_TO_PRCS_CD in varchar2 default null
,P_DESC_TXT in varchar2 default null
,P_TMLNS_EVAL_CD in varchar2 default null
,P_TMLNS_PERD_CD in varchar2 default null
,P_TMLNS_DYS_NUM in number default null
,I_TMLNS_DYS_NUM in varchar2 default 'N'
,P_TMLNS_PERD_RL in number default null
,I_TMLNS_PERD_RL in varchar2 default 'N'
,P_OCRD_DT_DET_CD in varchar2 default null
,P_LER_STAT_CD in varchar2 default null
,P_SLCTBL_SLF_SVC_CD in varchar2 default null
,P_LER_ATTRIBUTE_CATEGORY in varchar2 default null
,P_LER_ATTRIBUTE1 in varchar2 default null
,P_LER_ATTRIBUTE2 in varchar2 default null
,P_LER_ATTRIBUTE3 in varchar2 default null
,P_LER_ATTRIBUTE4 in varchar2 default null
,P_LER_ATTRIBUTE5 in varchar2 default null
,P_LER_ATTRIBUTE6 in varchar2 default null
,P_LER_ATTRIBUTE7 in varchar2 default null
,P_LER_ATTRIBUTE8 in varchar2 default null
,P_LER_ATTRIBUTE9 in varchar2 default null
,P_LER_ATTRIBUTE10 in varchar2 default null
,P_LER_ATTRIBUTE11 in varchar2 default null
,P_LER_ATTRIBUTE12 in varchar2 default null
,P_LER_ATTRIBUTE13 in varchar2 default null
,P_LER_ATTRIBUTE14 in varchar2 default null
,P_LER_ATTRIBUTE15 in varchar2 default null
,P_LER_ATTRIBUTE16 in varchar2 default null
,P_LER_ATTRIBUTE17 in varchar2 default null
,P_LER_ATTRIBUTE18 in varchar2 default null
,P_LER_ATTRIBUTE19 in varchar2 default null
,P_LER_ATTRIBUTE20 in varchar2 default null
,P_LER_ATTRIBUTE21 in varchar2 default null
,P_LER_ATTRIBUTE22 in varchar2 default null
,P_LER_ATTRIBUTE23 in varchar2 default null
,P_LER_ATTRIBUTE24 in varchar2 default null
,P_LER_ATTRIBUTE25 in varchar2 default null
,P_LER_ATTRIBUTE26 in varchar2 default null
,P_LER_ATTRIBUTE27 in varchar2 default null
,P_LER_ATTRIBUTE28 in varchar2 default null
,P_LER_ATTRIBUTE29 in varchar2 default null
,P_LER_ATTRIBUTE30 in varchar2 default null
,P_EFFECTIVE_DATE in date
,P_DATETRACK_MODE in varchar2
,P_LIFE_EVENT_REASON in varchar2);
--
procedure call
(p_business_group_id in number,
p_batch_line_id     in number);
end hrdpp_UPDATE_LIFE_EVENT_REASON;
 

/
