--------------------------------------------------------
--  DDL for Package HRDPP_CREATE_BUSINESS_GROUP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HRDPP_CREATE_BUSINESS_GROUP" as
/*
 * Generated by hr_pump_meta_mapper at: 2013/08/30 12:08:09
 * Generated for API: HR_ORGANIZATION_API.CREATE_BUSINESS_GROUP
 */
--
g_generator_version constant varchar2(128) default '$Revision: 120.4.12010000.1 $';
--

function dc(p in date) return varchar2;
pragma restrict_references(dc,WNDS);

function d(p in varchar2) return date;
pragma restrict_references(d,WNDS);
function n(p in varchar2) return number;
pragma restrict_references(n,WNDS);
function dd(p in date,i in varchar2) return varchar2;
pragma restrict_references(dd,WNDS);
function nd(p in number,i in varchar2) return varchar2;
pragma restrict_references(nd,WNDS);
--
procedure insert_batch_lines
(p_batch_id      in number
,p_data_pump_batch_line_id in number default null
,p_data_pump_business_grp_name in varchar2 default null
,p_user_sequence in number default null
,p_link_value    in number default null
,P_EFFECTIVE_DATE in date
,P_LANGUAGE_CODE in varchar2
,P_DATE_FROM in date
,P_NAME in varchar2
,P_TYPE in varchar2
,P_INTERNAL_EXTERNAL_FLAG in varchar2
,P_SHORT_NAME in varchar2
,P_EMP_GEN_METHOD in varchar2
,P_APP_GEN_METHOD in varchar2
,P_CWK_GEN_METHOD in varchar2
,P_LEGISLATION_CODE in varchar2
,P_CURRENCY_CODE in varchar2
,P_FISCAL_YEAR_START in varchar2
,P_MIN_WORK_AGE in varchar2
,P_MAX_WORK_AGE in varchar2
,P_ORG_USER_KEY in varchar2
,P_LOCATION_CODE in varchar2
,P_GRADE_FLEX_STRU_CODE in varchar2
,P_GROUP_FLEX_STRU_CODE in varchar2
,P_JOB_FLEX_STRU_CODE in varchar2
,P_COST_FLEX_STRU_CODE in varchar2
,P_POSITION_FLEX_STRU_CODE in varchar2
,P_SECURITY_GROUP_NAME in varchar2
,P_COMPETENCE_FLEX_STRU_CODE in varchar2);
--
procedure call
(p_business_group_id in number,
p_batch_line_id     in number);
end hrdpp_CREATE_BUSINESS_GROUP;

/
