--------------------------------------------------------
--  DDL for Package HRDPP_CREATE_CONTACT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HRDPP_CREATE_CONTACT" as
/*
 * Generated by hr_pump_meta_mapper at: 2018/06/16 10:06:06
 * Generated for API: HR_CONTACT_REL_API.CREATE_CONTACT
 */
--
g_generator_version constant varchar2(128) default '$Revision: 120.4.12010000.1 $';
--

function dc(p in date) return varchar2;
pragma restrict_references(dc,WNDS);

function d(p in varchar2) return date;
pragma restrict_references(d,WNDS);
function n(p in varchar2) return number;
pragma restrict_references(n,WNDS);
function dd(p in date,i in varchar2) return varchar2;
pragma restrict_references(dd,WNDS);
function nd(p in number,i in varchar2) return varchar2;
pragma restrict_references(nd,WNDS);
--
procedure insert_batch_lines
(p_batch_id      in number
,p_data_pump_batch_line_id in number default null
,p_data_pump_business_grp_name in varchar2 default null
,p_user_sequence in number default null
,p_link_value    in number default null
,P_START_DATE in date
,P_CONTACT_TYPE in varchar2
,P_CTR_COMMENTS in varchar2 default null
,P_PRIMARY_CONTACT_FLAG in varchar2 default null
,P_DATE_START in date default null
,P_DATE_END in date default null
,P_RLTD_PER_RSDS_W_DSGNTR_FLAG in varchar2 default null
,P_PERSONAL_FLAG in varchar2 default null
,P_SEQUENCE_NUMBER in number default null
,P_CONT_ATTRIBUTE_CATEGORY in varchar2 default null
,P_CONT_ATTRIBUTE1 in varchar2 default null
,P_CONT_ATTRIBUTE2 in varchar2 default null
,P_CONT_ATTRIBUTE3 in varchar2 default null
,P_CONT_ATTRIBUTE4 in varchar2 default null
,P_CONT_ATTRIBUTE5 in varchar2 default null
,P_CONT_ATTRIBUTE6 in varchar2 default null
,P_CONT_ATTRIBUTE7 in varchar2 default null
,P_CONT_ATTRIBUTE8 in varchar2 default null
,P_CONT_ATTRIBUTE9 in varchar2 default null
,P_CONT_ATTRIBUTE10 in varchar2 default null
,P_CONT_ATTRIBUTE11 in varchar2 default null
,P_CONT_ATTRIBUTE12 in varchar2 default null
,P_CONT_ATTRIBUTE13 in varchar2 default null
,P_CONT_ATTRIBUTE14 in varchar2 default null
,P_CONT_ATTRIBUTE15 in varchar2 default null
,P_CONT_ATTRIBUTE16 in varchar2 default null
,P_CONT_ATTRIBUTE17 in varchar2 default null
,P_CONT_ATTRIBUTE18 in varchar2 default null
,P_CONT_ATTRIBUTE19 in varchar2 default null
,P_CONT_ATTRIBUTE20 in varchar2 default null
,P_CONT_INFORMATION_CATEGORY in varchar2 default null
,P_CONT_INFORMATION1 in varchar2 default null
,P_CONT_INFORMATION2 in varchar2 default null
,P_CONT_INFORMATION3 in varchar2 default null
,P_CONT_INFORMATION4 in varchar2 default null
,P_CONT_INFORMATION5 in varchar2 default null
,P_CONT_INFORMATION6 in varchar2 default null
,P_CONT_INFORMATION7 in varchar2 default null
,P_CONT_INFORMATION8 in varchar2 default null
,P_CONT_INFORMATION9 in varchar2 default null
,P_CONT_INFORMATION10 in varchar2 default null
,P_CONT_INFORMATION11 in varchar2 default null
,P_CONT_INFORMATION12 in varchar2 default null
,P_CONT_INFORMATION13 in varchar2 default null
,P_CONT_INFORMATION14 in varchar2 default null
,P_CONT_INFORMATION15 in varchar2 default null
,P_CONT_INFORMATION16 in varchar2 default null
,P_CONT_INFORMATION17 in varchar2 default null
,P_CONT_INFORMATION18 in varchar2 default null
,P_CONT_INFORMATION19 in varchar2 default null
,P_CONT_INFORMATION20 in varchar2 default null
,P_THIRD_PARTY_PAY_FLAG in varchar2 default null
,P_BONDHOLDER_FLAG in varchar2 default null
,P_DEPENDENT_FLAG in varchar2 default null
,P_BENEFICIARY_FLAG in varchar2 default null
,P_LAST_NAME in varchar2 default null
,P_SEX in varchar2 default null
,P_PER_COMMENTS in varchar2 default null
,P_DATE_OF_BIRTH in date default null
,P_EMAIL_ADDRESS in varchar2 default null
,P_FIRST_NAME in varchar2 default null
,P_KNOWN_AS in varchar2 default null
,P_MARITAL_STATUS in varchar2 default null
,P_MIDDLE_NAMES in varchar2 default null
,P_NATIONALITY in varchar2 default null
,P_NATIONAL_IDENTIFIER in varchar2 default null
,P_PREVIOUS_LAST_NAME in varchar2 default null
,P_REGISTERED_DISABLED_FLAG in varchar2 default null
,P_TITLE in varchar2 default null
,P_WORK_TELEPHONE in varchar2 default null
,P_ATTRIBUTE_CATEGORY in varchar2 default null
,P_ATTRIBUTE1 in varchar2 default null
,P_ATTRIBUTE2 in varchar2 default null
,P_ATTRIBUTE3 in varchar2 default null
,P_ATTRIBUTE4 in varchar2 default null
,P_ATTRIBUTE5 in varchar2 default null
,P_ATTRIBUTE6 in varchar2 default null
,P_ATTRIBUTE7 in varchar2 default null
,P_ATTRIBUTE8 in varchar2 default null
,P_ATTRIBUTE9 in varchar2 default null
,P_ATTRIBUTE10 in varchar2 default null
,P_ATTRIBUTE11 in varchar2 default null
,P_ATTRIBUTE12 in varchar2 default null
,P_ATTRIBUTE13 in varchar2 default null
,P_ATTRIBUTE14 in varchar2 default null
,P_ATTRIBUTE15 in varchar2 default null
,P_ATTRIBUTE16 in varchar2 default null
,P_ATTRIBUTE17 in varchar2 default null
,P_ATTRIBUTE18 in varchar2 default null
,P_ATTRIBUTE19 in varchar2 default null
,P_ATTRIBUTE20 in varchar2 default null
,P_ATTRIBUTE21 in varchar2 default null
,P_ATTRIBUTE22 in varchar2 default null
,P_ATTRIBUTE23 in varchar2 default null
,P_ATTRIBUTE24 in varchar2 default null
,P_ATTRIBUTE25 in varchar2 default null
,P_ATTRIBUTE26 in varchar2 default null
,P_ATTRIBUTE27 in varchar2 default null
,P_ATTRIBUTE28 in varchar2 default null
,P_ATTRIBUTE29 in varchar2 default null
,P_ATTRIBUTE30 in varchar2 default null
,P_PER_INFORMATION_CATEGORY in varchar2 default null
,P_PER_INFORMATION1 in varchar2 default null
,P_PER_INFORMATION2 in varchar2 default null
,P_PER_INFORMATION3 in varchar2 default null
,P_PER_INFORMATION4 in varchar2 default null
,P_PER_INFORMATION5 in varchar2 default null
,P_PER_INFORMATION6 in varchar2 default null
,P_PER_INFORMATION7 in varchar2 default null
,P_PER_INFORMATION8 in varchar2 default null
,P_PER_INFORMATION9 in varchar2 default null
,P_PER_INFORMATION10 in varchar2 default null
,P_PER_INFORMATION11 in varchar2 default null
,P_PER_INFORMATION12 in varchar2 default null
,P_PER_INFORMATION13 in varchar2 default null
,P_PER_INFORMATION14 in varchar2 default null
,P_PER_INFORMATION15 in varchar2 default null
,P_PER_INFORMATION16 in varchar2 default null
,P_PER_INFORMATION17 in varchar2 default null
,P_PER_INFORMATION18 in varchar2 default null
,P_PER_INFORMATION19 in varchar2 default null
,P_PER_INFORMATION20 in varchar2 default null
,P_PER_INFORMATION21 in varchar2 default null
,P_PER_INFORMATION22 in varchar2 default null
,P_PER_INFORMATION23 in varchar2 default null
,P_PER_INFORMATION24 in varchar2 default null
,P_PER_INFORMATION25 in varchar2 default null
,P_PER_INFORMATION26 in varchar2 default null
,P_PER_INFORMATION27 in varchar2 default null
,P_PER_INFORMATION28 in varchar2 default null
,P_PER_INFORMATION29 in varchar2 default null
,P_PER_INFORMATION30 in varchar2 default null
,P_CORRESPONDENCE_LANGUAGE in varchar2 default null
,P_HONORS in varchar2 default null
,P_PRE_NAME_ADJUNCT in varchar2 default null
,P_SUFFIX in varchar2 default null
,P_CREATE_MIRROR_FLAG in varchar2 default null
,P_MIRROR_TYPE in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE_CAT in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE1 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE2 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE3 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE4 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE5 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE6 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE7 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE8 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE9 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE10 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE11 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE12 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE13 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE14 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE15 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE16 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE17 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE18 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE19 in varchar2 default null
,P_MIRROR_CONT_ATTRIBUTE20 in varchar2 default null
,P_MIRROR_CONT_INFORMATION_CAT in varchar2 default null
,P_MIRROR_CONT_INFORMATION1 in varchar2 default null
,P_MIRROR_CONT_INFORMATION2 in varchar2 default null
,P_MIRROR_CONT_INFORMATION3 in varchar2 default null
,P_MIRROR_CONT_INFORMATION4 in varchar2 default null
,P_MIRROR_CONT_INFORMATION5 in varchar2 default null
,P_MIRROR_CONT_INFORMATION6 in varchar2 default null
,P_MIRROR_CONT_INFORMATION7 in varchar2 default null
,P_MIRROR_CONT_INFORMATION8 in varchar2 default null
,P_MIRROR_CONT_INFORMATION9 in varchar2 default null
,P_MIRROR_CONT_INFORMATION10 in varchar2 default null
,P_MIRROR_CONT_INFORMATION11 in varchar2 default null
,P_MIRROR_CONT_INFORMATION12 in varchar2 default null
,P_MIRROR_CONT_INFORMATION13 in varchar2 default null
,P_MIRROR_CONT_INFORMATION14 in varchar2 default null
,P_MIRROR_CONT_INFORMATION15 in varchar2 default null
,P_MIRROR_CONT_INFORMATION16 in varchar2 default null
,P_MIRROR_CONT_INFORMATION17 in varchar2 default null
,P_MIRROR_CONT_INFORMATION18 in varchar2 default null
,P_MIRROR_CONT_INFORMATION19 in varchar2 default null
,P_MIRROR_CONT_INFORMATION20 in varchar2 default null
,P_PER_PERSON_USER_KEY in varchar2
,P_PERSON_USER_KEY in varchar2
,P_CONTACT_PERSON_USER_KEY in varchar2 default null
,P_START_LIFE_REASON in varchar2 default null
,P_END_LIFE_REASON in varchar2 default null
,P_USER_PERSON_TYPE in varchar2 default null
,P_LANGUAGE_CODE in varchar2 default null);
--
procedure call
(p_business_group_id in number,
p_batch_line_id     in number);
end hrdpp_CREATE_CONTACT;

/
