--------------------------------------------------------
--  DDL for Package HRDPP_CREATE_IN_SECONDARY_CWK_
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HRDPP_CREATE_IN_SECONDARY_CWK_" as
/*
 * Generated by hr_pump_meta_mapper at: 2007/01/04 09:01:36
 * Generated for API: hr_in_assignment_api.create_in_secondary_cwk_asg
 */
--
g_generator_version constant varchar2(128) default '$Revision: 120.4  $';
--

function dc(p in date) return varchar2;
pragma restrict_references(dc,WNDS);

function d(p in varchar2) return date;
pragma restrict_references(d,WNDS);
function n(p in varchar2) return number;
pragma restrict_references(n,WNDS);
function dd(p in date,i in varchar2) return varchar2;
pragma restrict_references(dd,WNDS);
function nd(p in number,i in varchar2) return varchar2;
pragma restrict_references(nd,WNDS);
--
procedure insert_batch_lines
(p_batch_id      in number
,p_data_pump_batch_line_id in number default null
,p_data_pump_business_grp_name in varchar2 default null
,p_user_sequence in number default null
,p_link_value    in number default null
,P_EFFECTIVE_DATE in date
,P_ASSIGNMENT_NUMBER in varchar2
,P_ASSIGNMENT_CATEGORY in varchar2 default null
,P_CHANGE_REASON in varchar2 default null
,P_COMMENTS in varchar2 default null
,P_FREQUENCY in varchar2 default null
,P_INTERNAL_ADDRESS_LINE in varchar2 default null
,P_LABOUR_UNION_MEMBER_FLAG in varchar2 default null
,P_MANAGER_FLAG in varchar2 default null
,P_NORMAL_HOURS in number default null
,P_PROJECT_TITLE in varchar2 default null
,P_SOURCE_TYPE in varchar2 default null
,P_TIME_NORMAL_FINISH in varchar2 default null
,P_TIME_NORMAL_START in varchar2 default null
,P_TITLE in varchar2 default null
,P_VENDOR_ASSIGNMENT_NUMBER in varchar2 default null
,P_VENDOR_EMPLOYEE_NUMBER in varchar2 default null
,P_PROJECTED_ASSIGNMENT_END in date default null
,P_ATTRIBUTE_CATEGORY in varchar2 default null
,P_ATTRIBUTE1 in varchar2 default null
,P_ATTRIBUTE2 in varchar2 default null
,P_ATTRIBUTE3 in varchar2 default null
,P_ATTRIBUTE4 in varchar2 default null
,P_ATTRIBUTE5 in varchar2 default null
,P_ATTRIBUTE6 in varchar2 default null
,P_ATTRIBUTE7 in varchar2 default null
,P_ATTRIBUTE8 in varchar2 default null
,P_ATTRIBUTE9 in varchar2 default null
,P_ATTRIBUTE10 in varchar2 default null
,P_ATTRIBUTE11 in varchar2 default null
,P_ATTRIBUTE12 in varchar2 default null
,P_ATTRIBUTE13 in varchar2 default null
,P_ATTRIBUTE14 in varchar2 default null
,P_ATTRIBUTE15 in varchar2 default null
,P_ATTRIBUTE16 in varchar2 default null
,P_ATTRIBUTE17 in varchar2 default null
,P_ATTRIBUTE18 in varchar2 default null
,P_ATTRIBUTE19 in varchar2 default null
,P_ATTRIBUTE20 in varchar2 default null
,P_ATTRIBUTE21 in varchar2 default null
,P_ATTRIBUTE22 in varchar2 default null
,P_ATTRIBUTE23 in varchar2 default null
,P_ATTRIBUTE24 in varchar2 default null
,P_ATTRIBUTE25 in varchar2 default null
,P_ATTRIBUTE26 in varchar2 default null
,P_ATTRIBUTE27 in varchar2 default null
,P_ATTRIBUTE28 in varchar2 default null
,P_ATTRIBUTE29 in varchar2 default null
,P_ATTRIBUTE30 in varchar2 default null
,P_PGP_SEGMENT1 in varchar2 default null
,P_PGP_SEGMENT2 in varchar2 default null
,P_PGP_SEGMENT3 in varchar2 default null
,P_PGP_SEGMENT4 in varchar2 default null
,P_PGP_SEGMENT5 in varchar2 default null
,P_PGP_SEGMENT6 in varchar2 default null
,P_PGP_SEGMENT7 in varchar2 default null
,P_PGP_SEGMENT8 in varchar2 default null
,P_PGP_SEGMENT9 in varchar2 default null
,P_PGP_SEGMENT10 in varchar2 default null
,P_PGP_SEGMENT11 in varchar2 default null
,P_PGP_SEGMENT12 in varchar2 default null
,P_PGP_SEGMENT13 in varchar2 default null
,P_PGP_SEGMENT14 in varchar2 default null
,P_PGP_SEGMENT15 in varchar2 default null
,P_PGP_SEGMENT16 in varchar2 default null
,P_PGP_SEGMENT17 in varchar2 default null
,P_PGP_SEGMENT18 in varchar2 default null
,P_PGP_SEGMENT19 in varchar2 default null
,P_PGP_SEGMENT20 in varchar2 default null
,P_PGP_SEGMENT21 in varchar2 default null
,P_PGP_SEGMENT22 in varchar2 default null
,P_PGP_SEGMENT23 in varchar2 default null
,P_PGP_SEGMENT24 in varchar2 default null
,P_PGP_SEGMENT25 in varchar2 default null
,P_PGP_SEGMENT26 in varchar2 default null
,P_PGP_SEGMENT27 in varchar2 default null
,P_PGP_SEGMENT28 in varchar2 default null
,P_PGP_SEGMENT29 in varchar2 default null
,P_PGP_SEGMENT30 in varchar2 default null
,P_SCL_CONCAT_SEGMENTS in varchar2 default null
,P_PGP_CONCAT_SEGMENTS in varchar2 default null
,P_ASSIGNMENT_USER_KEY in varchar2
,P_PERSON_USER_KEY in varchar2
,P_ORGANIZATION_NAME in varchar2
,P_LANGUAGE_CODE in varchar2
,P_USER_STATUS in varchar2 default null
,P_DEFAULT_CODE_COMB_USER_KEY in varchar2 default null
,P_ESTABLISHMENT_ORG_NAME in varchar2 default null
,P_JOB_NAME in varchar2 default null
,P_LOCATION_CODE in varchar2 default null
,P_POSITION_NAME in varchar2 default null
,P_GRADE_NAME in varchar2 default null
,P_SET_OF_BOOKS_NAME in varchar2 default null
,P_SUPERVISOR_USER_KEY in varchar2 default null
,P_VENDOR_NAME in varchar2 default null
,P_VENDOR_SITE_ID in number default null
,P_PO_HEADER_ID in number default null
,P_PO_LINE_ID in number default null
,P_SCL_CONTRACTOR_NAME in varchar2 default null
,P_SVR_ASSIGNMENT_USER_KEY in varchar2 default null);
--
procedure call
(p_business_group_id in number,
p_batch_line_id     in number);
end hrdpp_create_in_secondary_cwk_;
 

/
