--------------------------------------------------------
--  DDL for Package HZ_ACCT_CREATE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HZ_ACCT_CREATE_PKG" AUTHID CURRENT_USER as
/* $Header: ARHACTFS.pls 120.2 2005/06/16 21:08:15 jhuang ship $ */
 PROCEDURE insert_row(
                       c_cust_account_id                IN OUT NOCOPY NUMBER ,
                       c_party_id                       IN OUT NOCOPY NUMBER,
                       c_account_number                  IN OUT NOCOPY VARCHAR2,
                       c_Attribute_Category              IN VARCHAR2,
                       c_Attribute1                      IN VARCHAR2,
                       c_Attribute2                      IN VARCHAR2,
                       c_Attribute3                      IN VARCHAR2,
                       c_Attribute4                      IN VARCHAR2,
                       c_Attribute5                      IN VARCHAR2,
                       c_Attribute6                      IN VARCHAR2,
                       c_attribute7                      IN VARCHAR2,
                       c_Attribute8                      IN VARCHAR2,
                       c_Attribute9                      IN VARCHAR2,
                       c_Attribute10                     IN VARCHAR2,
                       c_Attribute11                     IN VARCHAR2,
                       c_Attribute12                     IN VARCHAR2,
                       c_Attribute13                     IN VARCHAR2,
                       c_Attribute14                     IN VARCHAR2,
                       c_Attribute15                     IN VARCHAR2,
                       c_Attribute16                     IN VARCHAR2,
                       c_Attribute17                     IN VARCHAR2,
                       c_Attribute18                     IN VARCHAR2,
                       c_Attribute19                     IN VARCHAR2,
                       c_Attribute20                     IN VARCHAR2,
                       c_global_attribute_category         IN VARCHAR2,
                       c_global_attribute1                 IN VARCHAR2,
                       c_global_attribute2                 IN VARCHAR2,
                       c_global_attribute3                 IN VARCHAR2,
                       c_global_attribute4                 IN VARCHAR2,
                       c_global_attribute5                 IN VARCHAR2,
                       c_global_attribute6                 IN VARCHAR2,
                       c_global_attribute7                 IN VARCHAR2,
                       c_global_attribute8                 IN VARCHAR2,
                       c_global_attribute9                 IN VARCHAR2,
                       c_global_attribute10                IN VARCHAR2,
                       c_global_attribute11                IN VARCHAR2,
                       c_global_attribute12                IN VARCHAR2,
                       c_global_attribute13                IN VARCHAR2,
                       c_global_attribute14                IN VARCHAR2,
                       c_global_attribute15                IN VARCHAR2,
                       c_global_attribute16                IN VARCHAR2,
                       c_global_attribute17                IN VARCHAR2,
                       c_global_attribute18                IN VARCHAR2,
                       c_global_attribute19                IN VARCHAR2,
                       c_global_attribute20                IN VARCHAR2,
                       c_orig_system_reference                   IN VARCHAR2,
                       c_status                                  IN VARCHAR2,
                       c_customer_type                           IN VARCHAR2,
                       c_customer_class_code                     IN VARCHAR2,
                       c_primary_salesrep_id                    IN NUMBER ,
                       c_sales_channel_code                      IN VARCHAR2,
                       c_order_type_id                          IN NUMBER,
                       c_price_list_id                          IN NUMBER ,
                       c_category_code                           IN VARCHAR2,
                       c_reference_use_flag                      IN VARCHAR2,
                       c_tax_code                                IN VARCHAR2,
                       c_third_party_flag                        IN VARCHAR2,
                       c_competitor_flag                         IN VARCHAR2,
                       c_fob_point                               IN VARCHAR2,
                       c_tax_header_level_flag                   IN VARCHAR2,
                       c_tax_rounding_rule                       IN VARCHAR2,
                       c_account_name                            IN VARCHAR2,
                       c_freight_term                            IN VARCHAR2,
                       c_ship_partial                            IN VARCHAR2,
                       c_ship_via                                IN VARCHAR2,
                       c_warehouse_id                           IN NUMBER,
                       c_payment_term_id                        IN NUMBER ,
                       c_DATES_NEGATIVE_TOLERANCE               IN NUMBER,
                       c_DATES_POSITIVE_TOLERANCE               IN NUMBER,
                       c_DATE_TYPE_PREFERENCE                   IN VARCHAR2,
                       c_OVER_SHIPMENT_TOLERANCE                IN NUMBER,
                       c_UNDER_SHIPMENT_TOLERANCE               IN NUMBER,
                       c_ITEM_CROSS_REF_PREF                    IN VARCHAR2,
                       c_OVER_RETURN_TOLERANCE                  IN NUMBER,
                       c_UNDER_RETURN_TOLERANCE                 IN NUMBER,
                       c_SHIP_SETS_INCLUDE_LINES_FLAG           IN VARCHAR2,
                       c_ARRIVALSETS_INCL_LINES_FLAG            IN VARCHAR2,
                       c_SCHED_DATE_PUSH_FLAG                   IN VARCHAR2,
                       c_INVOICE_QUANTITY_RULE                  IN VARCHAR2,
                       t_party_id                        IN NUMBER ,
                       t_party_number                     IN OUT NOCOPY VARCHAR2,
                       t_customer_key                     IN VARCHAR2,
                       t_Attribute_Category              IN VARCHAR2,
                       t_Attribute1                      IN VARCHAR2,
                       t_Attribute2                      IN VARCHAR2,
                       t_Attribute3                      IN VARCHAR2,
                       t_Attribute4                      IN VARCHAR2,
                       t_Attribute5                      IN VARCHAR2,
                       t_Attribute6                      IN VARCHAR2,
                       t_Attribute7                      IN VARCHAR2,
                       t_Attribute8                      IN VARCHAR2,
                       t_Attribute9                      IN VARCHAR2,
                       t_Attribute10                     IN VARCHAR2,
                       t_Attribute11                     IN VARCHAR2,
                       t_Attribute12                     IN VARCHAR2,
                       t_Attribute13                     IN VARCHAR2,
                       t_Attribute14                     IN VARCHAR2,
                       t_Attribute15                     IN VARCHAR2,
                       t_Attribute16                     IN VARCHAR2,
                       t_Attribute17                     IN VARCHAR2,
                       t_Attribute18                     IN VARCHAR2,
                       t_Attribute19                     IN VARCHAR2,
                       t_Attribute20                     IN VARCHAR2,
                       t_global_attribute_category         IN VARCHAR2,
                       t_global_attribute1                 IN VARCHAR2,
                       t_global_attribute2                 IN VARCHAR2,
                       t_global_attribute3                 IN VARCHAR2,
                       t_global_attribute4                 IN VARCHAR2,
                       t_global_attribute5                 IN VARCHAR2,
                       t_global_attribute6                 IN VARCHAR2,
                       t_global_attribute7                 IN VARCHAR2,
                       t_global_attribute8                 IN VARCHAR2,
                       t_global_attribute9                 IN VARCHAR2,
                       t_global_attribute10                IN VARCHAR2,
                       t_global_attribute11                IN VARCHAR2,
                       t_global_attribute12                IN VARCHAR2,
                       t_global_attribute13                IN VARCHAR2,
                       t_global_attribute14                IN VARCHAR2,
                       t_global_attribute15                IN VARCHAR2,
                       t_global_attribute16                IN VARCHAR2,
                       t_global_attribute17                IN VARCHAR2,
                       t_global_attribute18                IN VARCHAR2,
                       t_global_attribute19                IN VARCHAR2,
                       t_global_attribute20                IN VARCHAR2,
                       o_party_name                       IN VARCHAR2,
                       o_sic_code                         IN VARCHAR2,
                       o_sic_code_type                    IN VARCHAR2,
                       o_analysis_fy                      IN VARCHAR2,
                       o_fiscal_yearend_month             IN VARCHAR2,
                       o_num_of_employees                IN NUMBER ,
                       o_curr_fy_potential_revenue       IN NUMBER ,
                       o_next_fy_potential_revenue       IN NUMBER ,
                       o_tax_reference                    IN VARCHAR2,
                       o_year_established                IN NUMBER ,
                       o_gsa_indicator_flag               IN VARCHAR2,
                       o_mission_statement                IN VARCHAR2,
                       o_duns_number			  IN NUMBER,
                       o_tax_name                         IN VARCHAR2,
                       o_organization_type                IN VARCHAR2,
                       o_taxpayer_id                      IN VARCHAR2,
                       o_party_name_phonetic              IN VARCHAR2,
                       p_cust_account_profile_id         IN NUMBER ,
                       p_cust_account_id                 IN NUMBER ,
                       p_status                           IN VARCHAR2,
 		       p_collector_id                    IN NUMBER ,
 		       p_credit_analyst_id                        IN NUMBER ,
 		       p_credit_checking                           IN VARCHAR2,
 		       p_next_credit_review_date                  DATE ,
 		       p_tolerance                                IN NUMBER,
 		       p_discount_terms                            IN VARCHAR2,
 		       p_dunning_letters                           IN VARCHAR2,
                       p_interest_charges                          IN VARCHAR2,
 		       p_send_statements                           IN VARCHAR2,
 		       p_credit_balance_statements                 IN VARCHAR2,
 		       p_credit_hold                               IN VARCHAR2,
		       p_profile_class_id                         IN NUMBER ,
 		       p_site_use_id                              IN NUMBER ,
 		       p_credit_rating                             IN VARCHAR2,
 	     	       p_risk_code                                 IN VARCHAR2,
 		       p_standard_terms                           IN NUMBER ,
 		       p_override_terms                            IN VARCHAR2,
 		       p_dunning_letter_set_id                    IN NUMBER,
 		       p_interest_period_days                     IN NUMBER,
 		       p_payment_grace_days                       IN NUMBER,
 		       p_discount_grace_days                      IN NUMBER,
 		       p_statement_cycle_id                       IN NUMBER ,
 		       p_account_status                            IN VARCHAR2,
 		       p_percent_collectable                      IN NUMBER ,
 		       p_autocash_hierarchy_id                    IN NUMBER,
                       p_Attribute_Category              IN VARCHAR2,
                       p_Attribute1                      IN VARCHAR2,
                       p_Attribute2                      IN VARCHAR2,
                       p_Attribute3                      IN VARCHAR2,
                       p_Attribute4                      IN VARCHAR2,
                       p_Attribute5                      IN VARCHAR2,
                       p_Attribute6                      IN VARCHAR2,
                       p_Attribute7                      IN VARCHAR2,
                       p_Attribute8                      IN VARCHAR2,
                       p_Attribute9                      IN VARCHAR2,
                       p_Attribute10                     IN VARCHAR2,
                       p_Attribute11                     IN VARCHAR2,
                       p_Attribute12                     IN VARCHAR2,
                       p_Attribute13                     IN VARCHAR2,
                       p_Attribute14                     IN VARCHAR2,
                       p_Attribute15                     IN VARCHAR2,
		       p_auto_rec_incl_disputed_flag               IN VARCHAR2,
 	  	       p_tax_printing_option                       IN VARCHAR2,
		       p_charge_on_fin_charge_flag             IN VARCHAR2,
 		       p_grouping_rule_id                         IN NUMBER ,
 		       p_clearing_days                            IN NUMBER,
 		       p_jgzz_attribute_category                   IN VARCHAR2,
 		       p_jgzz_attribute1                           IN VARCHAR2,
 		       p_jgzz_attribute2                           IN VARCHAR2,
 		       p_jgzz_attribute3                           IN VARCHAR2,
 		       p_jgzz_attribute4                           IN VARCHAR2,
 		       p_jgzz_attribute5                           IN VARCHAR2,
 		       p_jgzz_attribute6                           IN VARCHAR2,
 		       p_jgzz_attribute7                           IN VARCHAR2,
 		       p_jgzz_attribute8                           IN VARCHAR2,
 		       p_jgzz_attribute9                           IN VARCHAR2,
 		       p_jgzz_attribute10                          IN VARCHAR2,
 		       p_jgzz_attribute11                          IN VARCHAR2,
 		       p_jgzz_attribute12                          IN VARCHAR2,
 		       p_jgzz_attribute13                          IN VARCHAR2,
 		       p_jgzz_attribute14                          IN VARCHAR2,
 		       p_jgzz_attribute15                          IN VARCHAR2,
                       p_global_attribute_category         IN VARCHAR2,
                       p_global_attribute1                 IN VARCHAR2,
                       p_global_attribute2                 IN VARCHAR2,
                       p_global_attribute3                 IN VARCHAR2,
                       p_global_attribute4                 IN VARCHAR2,
                       p_global_attribute5                 IN VARCHAR2,
                       p_global_attribute6                 IN VARCHAR2,
                       p_global_attribute7                 IN VARCHAR2,
                       p_global_attribute8                 IN VARCHAR2,
                       p_global_attribute9                 IN VARCHAR2,
                       p_global_attribute10                IN VARCHAR2,
                       p_global_attribute11                IN VARCHAR2,
                       p_global_attribute12                IN VARCHAR2,
                       p_global_attribute13                IN VARCHAR2,
                       p_global_attribute14                IN VARCHAR2,
                       p_global_attribute15                IN VARCHAR2,
                       p_global_attribute16                IN VARCHAR2,
                       p_global_attribute17                IN VARCHAR2,
                       p_global_attribute18                IN VARCHAR2,
                       p_global_attribute19                IN VARCHAR2,
                       p_global_attribute20                IN VARCHAR2,
 		       p_cons_inv_flag                     IN VARCHAR2,
 		       p_cons_inv_type                     IN VARCHAR2,
 		       p_autocash_hier_id_for_adr    IN NUMBER ,
 		       p_lockbox_matching_option           IN VARCHAR2,
--{2310474
                       p_party_id                          IN NUMBER    DEFAULT NULL,
                       p_review_cycle                      IN VARCHAR2  DEFAULT NULL,
                       p_credit_classification             IN VARCHAR2  DEFAULT NULL,
                       p_last_credit_review_date           IN DATE      DEFAULT NULL,
--}
                       o_organization_profile_id         in out NOCOPY number,
                       x_msg_count                        OUT NOCOPY NUMBER,
                       x_msg_data                          OUT NOCOPY varchar2,
                       x_return_status                     OUT NOCOPY VARCHAR2,
                       o_duns_number_c                IN VARCHAR2 DEFAULT FND_API.G_MISS_CHAR
);



 PROCEDURE insert_person_row(
                       c_cust_account_id                IN OUT NOCOPY NUMBER ,
                       c_party_id                       IN OUT NOCOPY NUMBER,
                       c_account_number                  IN OUT NOCOPY VARCHAR2,
                       c_Attribute_Category              IN VARCHAR2,
                       c_Attribute1                      IN VARCHAR2,
                       c_Attribute2                      IN VARCHAR2,
                       c_Attribute3                      IN VARCHAR2,
                       c_Attribute4                      IN VARCHAR2,
                       c_Attribute5                      IN VARCHAR2,
                       c_Attribute6                      IN VARCHAR2,
                       c_Attribute7                      IN VARCHAR2,
                       c_Attribute8                      IN VARCHAR2,
                       c_Attribute9                      IN VARCHAR2,
                       c_Attribute10                     IN VARCHAR2,
                       c_Attribute11                     IN VARCHAR2,
                       c_Attribute12                     IN VARCHAR2,
                       c_Attribute13                     IN VARCHAR2,
                       c_Attribute14                     IN VARCHAR2,
                       c_Attribute15                     IN VARCHAR2,
                       c_Attribute16                     IN VARCHAR2,
                       c_Attribute17                     IN VARCHAR2,
                       c_Attribute18                     IN VARCHAR2,
                       c_Attribute19                     IN VARCHAR2,
                       c_Attribute20                     IN VARCHAR2,
                       c_global_attribute_category         IN VARCHAR2,
                       c_global_attribute1                 IN VARCHAR2,
                       c_global_attribute2                 IN VARCHAR2,
                       c_global_attribute3                 IN VARCHAR2,
                       c_global_attribute4                 IN VARCHAR2,
                       c_global_attribute5                 IN VARCHAR2,
                       c_global_attribute6                 IN VARCHAR2,
                       c_global_attribute7                 IN VARCHAR2,
                       c_global_attribute8                 IN VARCHAR2,
                       c_global_attribute9                 IN VARCHAR2,
                       c_global_attribute10                IN VARCHAR2,
                       c_global_attribute11                IN VARCHAR2,
                       c_global_attribute12                IN VARCHAR2,
                       c_global_attribute13                IN VARCHAR2,
                       c_global_attribute14                IN VARCHAR2,
                       c_global_attribute15                IN VARCHAR2,
                       c_global_attribute16                IN VARCHAR2,
                       c_global_attribute17                IN VARCHAR2,
                       c_global_attribute18                IN VARCHAR2,
                       c_global_attribute19                IN VARCHAR2,
                       c_global_attribute20                IN VARCHAR2,
                       c_orig_system_reference                   IN VARCHAR2,
                       c_status                                  IN VARCHAR2,
                       c_customer_type                           IN VARCHAR2,
                       c_customer_class_code                     IN VARCHAR2,
                       c_primary_salesrep_id                    IN NUMBER ,
                       c_sales_channel_code                      IN VARCHAR2,
                       c_order_type_id                          IN NUMBER,
                       c_price_list_id                          IN NUMBER ,
                       c_category_code                           IN VARCHAR2,
                       c_reference_use_flag                      IN VARCHAR2,
                       c_tax_code                                IN VARCHAR2,
                       c_third_party_flag                        IN VARCHAR2,
                       c_competitor_flag                         IN VARCHAR2,
                       c_fob_point                               IN VARCHAR2,
                       c_tax_header_level_flag                   IN VARCHAR2,
                       c_tax_rounding_rule                       IN VARCHAR2,
                       c_account_name                            IN VARCHAR2,
                       c_freight_term                            IN VARCHAR2,
                       c_ship_partial                            IN VARCHAR2,
                       c_ship_via                                IN VARCHAR2,
                       c_warehouse_id                           IN NUMBER,
                       c_payment_term_id                        IN NUMBER ,
                       c_DATES_NEGATIVE_TOLERANCE               IN NUMBER,
                       c_DATES_POSITIVE_TOLERANCE               IN NUMBER,
                       c_DATE_TYPE_PREFERENCE                   IN VARCHAR2,
                       c_OVER_SHIPMENT_TOLERANCE                IN NUMBER,
                       c_UNDER_SHIPMENT_TOLERANCE               IN NUMBER,
                       c_ITEM_CROSS_REF_PREF                    IN VARCHAR2,
                       c_OVER_RETURN_TOLERANCE                  IN NUMBER,
                       c_UNDER_RETURN_TOLERANCE                 IN NUMBER,
                       c_SHIP_SETS_INCLUDE_LINES_FLAG           IN VARCHAR2,
                       c_ARRIVALSETS_INCL_LINES_FLAG            IN VARCHAR2,
                       c_SCHED_DATE_PUSH_FLAG                   IN VARCHAR2,
                       c_INVOICE_QUANTITY_RULE                  IN VARCHAR2,
                       t_party_id                        IN NUMBER ,
                       t_party_number                     IN OUT NOCOPY VARCHAR2,
                       t_customer_key                     IN VARCHAR2,
                       t_Attribute_Category              IN VARCHAR2,
                       t_Attribute1                      IN VARCHAR2,
                       t_Attribute2                      IN VARCHAR2,
                       t_Attribute3                      IN VARCHAR2,
                       t_Attribute4                      IN VARCHAR2,
                       t_Attribute5                      IN VARCHAR2,
                       t_Attribute6                      IN VARCHAR2,
                       t_Attribute7                      IN VARCHAR2,
                       t_Attribute8                      IN VARCHAR2,
                       t_Attribute9                      IN VARCHAR2,
                       t_Attribute10                     IN VARCHAR2,
                       t_Attribute11                     IN VARCHAR2,
                       t_Attribute12                     IN VARCHAR2,
                       t_Attribute13                     IN VARCHAR2,
                       t_Attribute14                     IN VARCHAR2,
                       t_Attribute15                     IN VARCHAR2,
                       t_Attribute16                     IN VARCHAR2,
                       t_Attribute17                     IN VARCHAR2,
                       t_Attribute18                     IN VARCHAR2,
                       t_Attribute19                     IN VARCHAR2,
                       t_Attribute20                     IN VARCHAR2,
                       t_global_attribute_category         IN VARCHAR2,
                       t_global_attribute1                 IN VARCHAR2,
                       t_global_attribute2                 IN VARCHAR2,
                       t_global_attribute3                 IN VARCHAR2,
                       t_global_attribute4                 IN VARCHAR2,
                       t_global_attribute5                 IN VARCHAR2,
                       t_global_attribute6                 IN VARCHAR2,
                       t_global_attribute7                 IN VARCHAR2,
                       t_global_attribute8                 IN VARCHAR2,
                       t_global_attribute9                 IN VARCHAR2,
                       t_global_attribute10                IN VARCHAR2,
                       t_global_attribute11                IN VARCHAR2,
                       t_global_attribute12                IN VARCHAR2,
                       t_global_attribute13                IN VARCHAR2,
                       t_global_attribute14                IN VARCHAR2,
                       t_global_attribute15                IN VARCHAR2,
                       t_global_attribute16                IN VARCHAR2,
                       t_global_attribute17                IN VARCHAR2,
                       t_global_attribute18                IN VARCHAR2,
                       t_global_attribute19                IN VARCHAR2,
                       t_global_attribute20                IN VARCHAR2,
                       o_pre_name_adjunct                  IN VARCHAR2,
                       o_first_name                        IN VARCHAR2,
                       o_middle_name                       IN VARCHAR2,
                       o_last_name                         IN VARCHAR2,
                       o_name_suffix                       IN VARCHAR2 ,
                       o_tax_reference                     IN VARCHAR2,
                       o_taxpayer_id                      IN VARCHAR2,
                       o_party_name_phonetic              IN VARCHAR2,
                       p_cust_account_profile_id         IN NUMBER ,
                       p_cust_account_id                 IN NUMBER ,
                       p_status                           IN VARCHAR2,
                       p_collector_id                    IN NUMBER ,
                       p_credit_analyst_id                        IN NUMBER ,
                       p_credit_checking                           IN VARCHAR2,
                       p_next_credit_review_date                  DATE ,
                       p_tolerance                                IN NUMBER,
                       p_discount_terms                            IN VARCHAR2,
                       p_dunning_letters                           IN VARCHAR2,
                       p_interest_charges                          IN VARCHAR2,
                       p_send_statements                           IN VARCHAR2,
                       p_credit_balance_statements                 IN VARCHAR2,
                       p_credit_hold                               IN VARCHAR2,
                       p_profile_class_id                         IN NUMBER ,
                       p_site_use_id                              IN NUMBER ,
                       p_credit_rating                             IN VARCHAR2,
                       p_risk_code                                 IN VARCHAR2,
                       p_standard_terms                           IN NUMBER ,
                       p_override_terms                            IN VARCHAR2,
                       p_dunning_letter_set_id                    IN NUMBER,
                       p_interest_period_days                     IN NUMBER,
                       p_payment_grace_days                       IN NUMBER,
                       p_discount_grace_days                      IN NUMBER,
                       p_statement_cycle_id                       IN NUMBER ,
                       p_account_status                            IN VARCHAR2,
                       p_percent_collectable                      IN NUMBER ,
                       p_autocash_hierarchy_id                    IN NUMBER,
                       p_Attribute_Category              IN VARCHAR2,
                       p_Attribute1                      IN VARCHAR2,
                       p_Attribute2                      IN VARCHAR2,
                       p_Attribute3                      IN VARCHAR2,
                       p_Attribute4                      IN VARCHAR2,
                       p_Attribute5                      IN VARCHAR2,
                       p_Attribute6                      IN VARCHAR2,
                       p_Attribute7                      IN VARCHAR2,
                       p_Attribute8                      IN VARCHAR2,
                       p_Attribute9                      IN VARCHAR2,
                       p_Attribute10                     IN VARCHAR2,
                       p_Attribute11                     IN VARCHAR2,
                       p_Attribute12                     IN VARCHAR2,
                       p_Attribute13                     IN VARCHAR2,
                       p_Attribute14                     IN VARCHAR2,
                       p_Attribute15                     IN VARCHAR2,
                       p_auto_rec_incl_disputed_flag               IN VARCHAR2,
                       p_tax_printing_option                       IN VARCHAR2,
                       p_charge_on_fin_charge_flag             IN VARCHAR2,
                       p_grouping_rule_id                         IN NUMBER ,
                       p_clearing_days                            IN NUMBER,
                       p_jgzz_attribute_category                   IN VARCHAR2,
                       p_jgzz_attribute1                           IN VARCHAR2,
                       p_jgzz_attribute2                           IN VARCHAR2,
                       p_jgzz_attribute3                           IN VARCHAR2,
                       p_jgzz_attribute4                           IN VARCHAR2,
                       p_jgzz_attribute5                           IN VARCHAR2,
                       p_jgzz_attribute6                           IN VARCHAR2,
                       p_jgzz_attribute7                           IN VARCHAR2,
                       p_jgzz_attribute8                           IN VARCHAR2,
                       p_jgzz_attribute9                           IN VARCHAR2,
                       p_jgzz_attribute10                          IN VARCHAR2,
                       p_jgzz_attribute11                          IN VARCHAR2,
                       p_jgzz_attribute12                          IN VARCHAR2,
                       p_jgzz_attribute13                          IN VARCHAR2,
                       p_jgzz_attribute14                          IN VARCHAR2,
                       p_jgzz_attribute15                          IN VARCHAR2,
                       p_global_attribute_category         IN VARCHAR2,
                       p_global_attribute1                 IN VARCHAR2,
                       p_global_attribute2                 IN VARCHAR2,
                       p_global_attribute3                 IN VARCHAR2,
                       p_global_attribute4                 IN VARCHAR2,
                       p_global_attribute5                 IN VARCHAR2,
                       p_global_attribute6                 IN VARCHAR2,
                       p_global_attribute7                 IN VARCHAR2,
                       p_global_attribute8                 IN VARCHAR2,
                       p_global_attribute9                 IN VARCHAR2,
                       p_global_attribute10                IN VARCHAR2,
                       p_global_attribute11                IN VARCHAR2,
                       p_global_attribute12                IN VARCHAR2,
                       p_global_attribute13                IN VARCHAR2,
                       p_global_attribute14                IN VARCHAR2,
                       p_global_attribute15                IN VARCHAR2,
                       p_global_attribute16                IN VARCHAR2,
                       p_global_attribute17                IN VARCHAR2,
                       p_global_attribute18                IN VARCHAR2,
                       p_global_attribute19                IN VARCHAR2,
                       p_global_attribute20                IN VARCHAR2,
                       p_cons_inv_flag                     IN VARCHAR2,
                       p_cons_inv_type                     IN VARCHAR2,
                       p_autocash_hier_id_for_adr          IN NUMBER ,
                       p_lockbox_matching_option           IN VARCHAR2,
--{2310474
                       p_party_id                          IN NUMBER    DEFAULT NULL,
                       p_review_cycle                      IN VARCHAR2  DEFAULT NULL,
                       p_credit_classification             IN VARCHAR2  DEFAULT NULL,
                       p_last_credit_review_date           IN DATE      DEFAULT NULL,
--}
                       o_person_profile_id         in out NOCOPY number,
                       x_msg_count                         OUT NOCOPY NUMBER,
                       x_msg_data                          OUT NOCOPY varchar2,
                       x_return_status                     OUT NOCOPY VARCHAR2);


 PROCEDURE update_row(
                       c_cust_account_id                IN OUT NOCOPY NUMBER ,
                       c_party_id                       IN NUMBER,
                       c_account_number                  IN VARCHAR2,
                       c_Attribute_Category              IN VARCHAR2,
                       c_Attribute1                      IN VARCHAR2,
                       c_Attribute2                      IN VARCHAR2,
                       c_Attribute3                      IN VARCHAR2,
                       c_Attribute4                      IN VARCHAR2,
                       c_Attribute5                      IN VARCHAR2,
                       c_Attribute6                      IN VARCHAR2,
                       c_Attribute7                      IN VARCHAR2,
                       c_Attribute8                      IN VARCHAR2,
                       c_Attribute9                      IN VARCHAR2,
                       c_Attribute10                     IN VARCHAR2,
                       c_Attribute11                     IN VARCHAR2,
                       c_Attribute12                     IN VARCHAR2,
                       c_Attribute13                     IN VARCHAR2,
                       c_Attribute14                     IN VARCHAR2,
                       c_Attribute15                     IN VARCHAR2,
                       c_Attribute16                     IN VARCHAR2,
                       c_Attribute17                     IN VARCHAR2,
                       c_Attribute18                     IN VARCHAR2,
                       c_Attribute19                     IN VARCHAR2,
                       c_Attribute20                     IN VARCHAR2,
                       c_global_attribute_category         IN VARCHAR2,
                       c_global_attribute1                 IN VARCHAR2,
                       c_global_attribute2                 IN VARCHAR2,
                       c_global_attribute3                 IN VARCHAR2,
                       c_global_attribute4                 IN VARCHAR2,
                       c_global_attribute5                 IN VARCHAR2,
                       c_global_attribute6                 IN VARCHAR2,
                       c_global_attribute7                 IN VARCHAR2,
                       c_global_attribute8                 IN VARCHAR2,
                       c_global_attribute9                 IN VARCHAR2,
                       c_global_attribute10                IN VARCHAR2,
                       c_global_attribute11                IN VARCHAR2,
                       c_global_attribute12                IN VARCHAR2,
                       c_global_attribute13                IN VARCHAR2,
                       c_global_attribute14                IN VARCHAR2,
                       c_global_attribute15                IN VARCHAR2,
                       c_global_attribute16                IN VARCHAR2,
                       c_global_attribute17                IN VARCHAR2,
                       c_global_attribute18                IN VARCHAR2,
                       c_global_attribute19                IN VARCHAR2,
                       c_global_attribute20                IN VARCHAR2,
                       c_orig_system_reference                   IN VARCHAR2,
                       c_status                                  IN VARCHAR2,
                       c_customer_type                           IN VARCHAR2,
                       c_customer_class_code                     IN VARCHAR2,
                       c_primary_salesrep_id                    IN NUMBER ,
                       c_sales_channel_code                      IN VARCHAR2,
                       c_order_type_id                          IN NUMBER,
                       c_price_list_id                          IN NUMBER ,
                       c_category_code                           IN VARCHAR2,
                       c_reference_use_flag                      IN VARCHAR2,
                       c_tax_code                                IN VARCHAR2,
                       c_third_party_flag                        IN VARCHAR2,
                       c_competitor_flag                         IN VARCHAR2,
                       c_fob_point                               IN VARCHAR2,
                       c_tax_header_level_flag                   IN VARCHAR2,
                       c_tax_rounding_rule                       IN VARCHAR2,
                       c_account_name                            IN VARCHAR2,
                       c_freight_term                            IN VARCHAR2,
                       c_ship_partial                            IN VARCHAR2,
                       c_ship_via                                IN VARCHAR2,
                       c_warehouse_id                           IN NUMBER,
                       c_payment_term_id                        IN NUMBER ,
                       c_analysis_fy                            IN VARCHAR2,
                       c_fiscal_yearend_month                   IN VARCHAR2,
                       c_employees_total                        IN NUMBER,
                       c_cr_fy_potential_revenue                IN NUMBER,
                       c_next_fy_potential_revenue              IN NUMBER,
                       c_tax_reference                          IN VARCHAR2,
                       c_year_established                       IN NUMBER,
                       c_gsa_indicator_flag                     IN VARCHAR2,
                       c_jgzz_fiscal_code                       IN VARCHAR2,
                       c_do_not_mail_flag                       IN VARCHAR2,
                       c_mission_statement                      IN VARCHAR2,
                       c_org_name_phonetic                      IN VARCHAR2,
                       c_url                                    IN VARCHAR2,
                       c_person_suffix                          IN VARCHAR2,
                       c_first_name                             IN VARCHAR2,
                       c_middle_name                            IN VARCHAR2,
                       c_last_name                              IN VARCHAR2,
                       c_person_prefix                          IN VARCHAR2,
                       c_sic_code                               IN VARCHAR2,
                       c_sic_code_type                          IN VARCHAR2,
                       c_duns_number                            IN NUMBER,
                       c_DATES_NEGATIVE_TOLERANCE               IN NUMBER,
                       c_DATES_POSITIVE_TOLERANCE               IN NUMBER,
                       c_DATE_TYPE_PREFERENCE                   IN VARCHAR2,
                       c_OVER_SHIPMENT_TOLERANCE                IN NUMBER,
                       c_UNDER_SHIPMENT_TOLERANCE               IN NUMBER,
                       c_ITEM_CROSS_REF_PREF                    IN VARCHAR2,
                       c_OVER_RETURN_TOLERANCE                  IN NUMBER,
                       c_UNDER_RETURN_TOLERANCE                 IN NUMBER,
                       c_SHIP_SETS_INCLUDE_LINES_FLAG           IN VARCHAR2,
                       c_ARRIVALSETS_INCL_LINES_FLAG            IN VARCHAR2,
                       c_SCHED_DATE_PUSH_FLAG                   IN VARCHAR2,
                       c_INVOICE_QUANTITY_RULE                  IN VARCHAR2,
                       c_account_alias                          IN VARCHAR2 DEFAULT NULL,
                       p_cust_account_profile_id         IN NUMBER ,
                       p_cust_account_id                 IN NUMBER ,
                       p_status                           IN VARCHAR2,
 		       p_collector_id                    IN NUMBER ,
 		       p_credit_analyst_id                        IN NUMBER ,
 		       p_credit_checking                           IN VARCHAR2,
 		       p_next_credit_review_date                  DATE ,
 		       p_tolerance                                IN NUMBER,
 		       p_discount_terms                            IN VARCHAR2,
 		       p_dunning_letters                           IN VARCHAR2,
                       p_interest_charges                          IN VARCHAR2,
 		       p_send_statements                           IN VARCHAR2,
 		       p_credit_balance_statements                 IN VARCHAR2,
 		       p_credit_hold                               IN VARCHAR2,
		       p_profile_class_id                         IN NUMBER ,
 		       p_site_use_id                              IN NUMBER ,
 		       p_credit_rating                             IN VARCHAR2,
 	     	       p_risk_code                                 IN VARCHAR2,
 		       p_standard_terms                           IN NUMBER ,
 		       p_override_terms                            IN VARCHAR2,
 		       p_dunning_letter_set_id                    IN NUMBER,
 		       p_interest_period_days                     IN NUMBER,
 		       p_payment_grace_days                       IN NUMBER,
 		       p_discount_grace_days                      IN NUMBER,
 		       p_statement_cycle_id                       IN NUMBER ,
 		       p_account_status                            IN VARCHAR2,
 		       p_percent_collectable                      IN NUMBER ,
 		       p_autocash_hierarchy_id                    IN NUMBER,
                       p_Attribute_Category              IN VARCHAR2,
                       p_Attribute1                      IN VARCHAR2,
                       p_Attribute2                      IN VARCHAR2,
                       p_Attribute3                      IN VARCHAR2,
                       p_Attribute4                      IN VARCHAR2,
                       p_Attribute5                      IN VARCHAR2,
                       p_Attribute6                      IN VARCHAR2,
                       p_Attribute7                      IN VARCHAR2,
                       p_Attribute8                      IN VARCHAR2,
                       p_Attribute9                      IN VARCHAR2,
                       p_Attribute10                     IN VARCHAR2,
                       p_Attribute11                     IN VARCHAR2,
                       p_Attribute12                     IN VARCHAR2,
                       p_Attribute13                     IN VARCHAR2,
                       p_Attribute14                     IN VARCHAR2,
                       p_Attribute15                     IN VARCHAR2,
		       p_auto_rec_incl_disputed_flag               IN VARCHAR2,
 	  	       p_tax_printing_option                       IN VARCHAR2,
		       p_charge_on_fin_charge_flag                 IN VARCHAR2,
 		       p_grouping_rule_id                          IN NUMBER ,
 		       p_clearing_days                             IN NUMBER,
 		       p_jgzz_attribute_category                   IN VARCHAR2,
 		       p_jgzz_attribute1                           IN VARCHAR2,
 		       p_jgzz_attribute2                           IN VARCHAR2,
 		       p_jgzz_attribute3                           IN VARCHAR2,
 		       p_jgzz_attribute4                           IN VARCHAR2,
 		       p_jgzz_attribute5                           IN VARCHAR2,
 		       p_jgzz_attribute6                           IN VARCHAR2,
 		       p_jgzz_attribute7                           IN VARCHAR2,
 		       p_jgzz_attribute8                           IN VARCHAR2,
 		       p_jgzz_attribute9                           IN VARCHAR2,
 		       p_jgzz_attribute10                          IN VARCHAR2,
 		       p_jgzz_attribute11                          IN VARCHAR2,
 		       p_jgzz_attribute12                          IN VARCHAR2,
 		       p_jgzz_attribute13                          IN VARCHAR2,
 		       p_jgzz_attribute14                          IN VARCHAR2,
 		       p_jgzz_attribute15                          IN VARCHAR2,
                       p_global_attribute_category         IN VARCHAR2,
                       p_global_attribute1                 IN VARCHAR2,
                       p_global_attribute2                 IN VARCHAR2,
                       p_global_attribute3                 IN VARCHAR2,
                       p_global_attribute4                 IN VARCHAR2,
                       p_global_attribute5                 IN VARCHAR2,
                       p_global_attribute6                 IN VARCHAR2,
                       p_global_attribute7                 IN VARCHAR2,
                       p_global_attribute8                 IN VARCHAR2,
                       p_global_attribute9                 IN VARCHAR2,
                       p_global_attribute10                IN VARCHAR2,
                       p_global_attribute11                IN VARCHAR2,
                       p_global_attribute12                IN VARCHAR2,
                       p_global_attribute13                IN VARCHAR2,
                       p_global_attribute14                IN VARCHAR2,
                       p_global_attribute15                IN VARCHAR2,
                       p_global_attribute16                IN VARCHAR2,
                       p_global_attribute17                IN VARCHAR2,
                       p_global_attribute18                IN VARCHAR2,
                       p_global_attribute19                IN VARCHAR2,
                       p_global_attribute20                IN VARCHAR2,
 		       p_cons_inv_flag                     IN VARCHAR2,
 		       p_cons_inv_type                     IN VARCHAR2,
 		       p_autocash_hier_id_for_adr          IN NUMBER ,
 		       p_lockbox_matching_option           IN VARCHAR2,
--{2310474
                       p_party_id                          IN NUMBER    DEFAULT NULL,
                       p_review_cycle                      IN VARCHAR2  DEFAULT NULL,
                       p_credit_classification             IN VARCHAR2  DEFAULT NULL,
                       p_last_credit_review_date           IN DATE      DEFAULT NULL,
--}
                       a_last_update_date                  IN OUT NOCOPY DATE,
                       p_last_update_date                  IN OUT NOCOPY DATE,
                       x_cr_last_update_date                  IN OUT NOCOPY DATE,
                       x_pt_last_update_date                  IN OUT NOCOPY DATE,
                       x_cp_last_update_date                  IN OUT NOCOPY DATE,
                       x_op_last_update_date                  IN OUT NOCOPY DATE,
                       x_pp_last_update_date                  IN OUT NOCOPY DATE,
                       x_account_type                         IN VARCHAR,
                       o_organization_profile_id         in out NOCOPY number,
                       o_person_profile_id         in out NOCOPY number,
                       x_msg_count                         OUT NOCOPY NUMBER,
                       x_msg_data                          OUT NOCOPY varchar2,
                       x_return_status                     OUT NOCOPY VARCHAR2,
                       c_duns_number_c                IN VARCHAR2 DEFAULT FND_API.G_MISS_CHAR,
                       x_cust_acct_object_version       IN NUMBER   DEFAULT -1,
                       x_cust_prof_object_version       IN NUMBER   DEFAULT -1,
                       x_party_object_version           IN NUMBER   DEFAULT -1);

--
-- Overload method for V2 uptake with the bug 1736839
--
 PROCEDURE update_row(
                       c_cust_account_id                IN OUT NOCOPY NUMBER ,
                       c_party_id                       IN NUMBER,
                       c_account_number                 IN VARCHAR2,
                       c_Attribute_Category             IN VARCHAR2,
                       c_Attribute1                     IN VARCHAR2,
                       c_Attribute2                     IN VARCHAR2,
                       c_Attribute3                     IN VARCHAR2,
                       c_Attribute4                     IN VARCHAR2,
                       c_Attribute5                     IN VARCHAR2,
                       c_Attribute6                     IN VARCHAR2,
                       c_Attribute7                     IN VARCHAR2,
                       c_Attribute8                     IN VARCHAR2,
                       c_Attribute9                     IN VARCHAR2,
                       c_Attribute10                    IN VARCHAR2,
                       c_Attribute11                    IN VARCHAR2,
                       c_Attribute12                    IN VARCHAR2,
                       c_Attribute13                    IN VARCHAR2,
                       c_Attribute14                    IN VARCHAR2,
                       c_Attribute15                    IN VARCHAR2,
                       c_Attribute16                    IN VARCHAR2,
                       c_Attribute17                    IN VARCHAR2,
                       c_Attribute18                    IN VARCHAR2,
                       c_Attribute19                    IN VARCHAR2,
                       c_Attribute20                    IN VARCHAR2,
                       c_global_attribute_category      IN VARCHAR2,
                       c_global_attribute1              IN VARCHAR2,
                       c_global_attribute2              IN VARCHAR2,
                       c_global_attribute3              IN VARCHAR2,
                       c_global_attribute4              IN VARCHAR2,
                       c_global_attribute5              IN VARCHAR2,
                       c_global_attribute6              IN VARCHAR2,
                       c_global_attribute7              IN VARCHAR2,
                       c_global_attribute8              IN VARCHAR2,
                       c_global_attribute9              IN VARCHAR2,
                       c_global_attribute10             IN VARCHAR2,
                       c_global_attribute11             IN VARCHAR2,
                       c_global_attribute12             IN VARCHAR2,
                       c_global_attribute13             IN VARCHAR2,
                       c_global_attribute14             IN VARCHAR2,
                       c_global_attribute15             IN VARCHAR2,
                       c_global_attribute16             IN VARCHAR2,
                       c_global_attribute17             IN VARCHAR2,
                       c_global_attribute18             IN VARCHAR2,
                       c_global_attribute19             IN VARCHAR2,
                       c_global_attribute20             IN VARCHAR2,
                       c_orig_system_reference          IN VARCHAR2,
                       c_status                         IN VARCHAR2,
                       c_customer_type                  IN VARCHAR2,
                       c_customer_class_code            IN VARCHAR2,
                       c_primary_salesrep_id            IN NUMBER ,
                       c_sales_channel_code             IN VARCHAR2,
                       c_order_type_id                  IN NUMBER,
                       c_price_list_id                  IN NUMBER ,
                       c_category_code                  IN VARCHAR2,
                       c_reference_use_flag             IN VARCHAR2,
                       c_tax_code                       IN VARCHAR2,
                       c_third_party_flag               IN VARCHAR2,
                       c_competitor_flag                IN VARCHAR2,
                       c_fob_point                      IN VARCHAR2,
                       c_tax_header_level_flag          IN VARCHAR2,
                       c_tax_rounding_rule              IN VARCHAR2,
                       c_account_name                   IN VARCHAR2,
                       c_freight_term                   IN VARCHAR2,
                       c_ship_partial                   IN VARCHAR2,
                       c_ship_via                       IN VARCHAR2,
                       c_warehouse_id                   IN NUMBER,
                       c_payment_term_id                IN NUMBER ,
                       c_analysis_fy                    IN VARCHAR2,
                       c_fiscal_yearend_month           IN VARCHAR2,
                       c_employees_total                IN NUMBER,
                       c_cr_fy_potential_revenue        IN NUMBER,
                       c_next_fy_potential_revenue      IN NUMBER,
                       c_tax_reference                  IN VARCHAR2,
                       c_year_established               IN NUMBER,
                       c_gsa_indicator_flag             IN VARCHAR2,
                       c_jgzz_fiscal_code               IN VARCHAR2,
                       c_do_not_mail_flag               IN VARCHAR2,
                       c_mission_statement              IN VARCHAR2,
                       c_org_name_phonetic              IN VARCHAR2,
                       c_url                            IN VARCHAR2,
                       c_person_suffix                  IN VARCHAR2,
                       c_first_name                     IN VARCHAR2,
                       c_middle_name                    IN VARCHAR2,
                       c_last_name                      IN VARCHAR2,
                       c_person_prefix                  IN VARCHAR2,
                       c_sic_code                       IN VARCHAR2,
                       c_sic_code_type                  IN VARCHAR2,
                       c_duns_number                    IN NUMBER,
                       c_DATES_NEGATIVE_TOLERANCE       IN NUMBER,
                       c_DATES_POSITIVE_TOLERANCE       IN NUMBER,
                       c_DATE_TYPE_PREFERENCE           IN VARCHAR2,
                       c_OVER_SHIPMENT_TOLERANCE        IN NUMBER,
                       c_UNDER_SHIPMENT_TOLERANCE       IN NUMBER,
                       c_ITEM_CROSS_REF_PREF            IN VARCHAR2,
                       c_OVER_RETURN_TOLERANCE          IN NUMBER,
                       c_UNDER_RETURN_TOLERANCE         IN NUMBER,
                       c_SHIP_SETS_INCLUDE_LINES_FLAG   IN VARCHAR2,
                       c_ARRIVALSETS_INCL_LINES_FLAG    IN VARCHAR2,
                       c_SCHED_DATE_PUSH_FLAG           IN VARCHAR2,
                       c_INVOICE_QUANTITY_RULE          IN VARCHAR2,
                       c_account_alias                  IN VARCHAR2 DEFAULT NULL,
                       p_cust_account_profile_id        IN NUMBER ,
                       p_cust_account_id                IN NUMBER ,
                       p_status                         IN VARCHAR2,
                       p_collector_id                   IN NUMBER ,
                       p_credit_analyst_id              IN NUMBER ,
                       p_credit_checking                IN VARCHAR2,
                       p_next_credit_review_date           DATE ,
                       p_tolerance                      IN NUMBER,
                       p_discount_terms                 IN VARCHAR2,
                       p_dunning_letters                IN VARCHAR2,
                       p_interest_charges               IN VARCHAR2,
                       p_send_statements                IN VARCHAR2,
                       p_credit_balance_statements      IN VARCHAR2,
                       p_credit_hold                    IN VARCHAR2,
                       p_profile_class_id               IN NUMBER ,
                       p_site_use_id                    IN NUMBER ,
                       p_credit_rating                  IN VARCHAR2,
                       p_risk_code                      IN VARCHAR2,
                       p_standard_terms                 IN NUMBER ,
                       p_override_terms                 IN VARCHAR2,
                       p_dunning_letter_set_id          IN NUMBER,
                       p_interest_period_days           IN NUMBER,
                       p_payment_grace_days             IN NUMBER,
                       p_discount_grace_days            IN NUMBER,
                       p_statement_cycle_id             IN NUMBER ,
                       p_account_status                 IN VARCHAR2,
                       p_percent_collectable            IN NUMBER ,
                       p_autocash_hierarchy_id          IN NUMBER,
                       p_Attribute_Category             IN VARCHAR2,
                       p_Attribute1                     IN VARCHAR2,
                       p_Attribute2                     IN VARCHAR2,
                       p_Attribute3                     IN VARCHAR2,
                       p_Attribute4                     IN VARCHAR2,
                       p_Attribute5                     IN VARCHAR2,
                       p_Attribute6                     IN VARCHAR2,
                       p_Attribute7                     IN VARCHAR2,
                       p_Attribute8                     IN VARCHAR2,
                       p_Attribute9                     IN VARCHAR2,
                       p_Attribute10                    IN VARCHAR2,
                       p_Attribute11                    IN VARCHAR2,
                       p_Attribute12                    IN VARCHAR2,
                       p_Attribute13                    IN VARCHAR2,
                       p_Attribute14                    IN VARCHAR2,
                       p_Attribute15                    IN VARCHAR2,
                       p_auto_rec_incl_disputed_flag    IN VARCHAR2,
                       p_tax_printing_option            IN VARCHAR2,
                       p_charge_on_fin_charge_flag      IN VARCHAR2,
                       p_grouping_rule_id               IN NUMBER ,
                       p_clearing_days                  IN NUMBER,
                       p_jgzz_attribute_category        IN VARCHAR2,
                       p_jgzz_attribute1                IN VARCHAR2,
                       p_jgzz_attribute2                IN VARCHAR2,
                       p_jgzz_attribute3                IN VARCHAR2,
                       p_jgzz_attribute4                IN VARCHAR2,
                       p_jgzz_attribute5                IN VARCHAR2,
                       p_jgzz_attribute6                IN VARCHAR2,
                       p_jgzz_attribute7                IN VARCHAR2,
                       p_jgzz_attribute8                IN VARCHAR2,
                       p_jgzz_attribute9                IN VARCHAR2,
                       p_jgzz_attribute10               IN VARCHAR2,
                       p_jgzz_attribute11               IN VARCHAR2,
                       p_jgzz_attribute12               IN VARCHAR2,
                       p_jgzz_attribute13               IN VARCHAR2,
                       p_jgzz_attribute14               IN VARCHAR2,
                       p_jgzz_attribute15               IN VARCHAR2,
                       p_global_attribute_category      IN VARCHAR2,
                       p_global_attribute1              IN VARCHAR2,
                       p_global_attribute2              IN VARCHAR2,
                       p_global_attribute3              IN VARCHAR2,
                       p_global_attribute4              IN VARCHAR2,
                       p_global_attribute5              IN VARCHAR2,
                       p_global_attribute6              IN VARCHAR2,
                       p_global_attribute7              IN VARCHAR2,
                       p_global_attribute8              IN VARCHAR2,
                       p_global_attribute9              IN VARCHAR2,
                       p_global_attribute10             IN VARCHAR2,
                       p_global_attribute11             IN VARCHAR2,
                       p_global_attribute12             IN VARCHAR2,
                       p_global_attribute13             IN VARCHAR2,
                       p_global_attribute14             IN VARCHAR2,
                       p_global_attribute15             IN VARCHAR2,
                       p_global_attribute16             IN VARCHAR2,
                       p_global_attribute17             IN VARCHAR2,
                       p_global_attribute18             IN VARCHAR2,
                       p_global_attribute19             IN VARCHAR2,
                       p_global_attribute20             IN VARCHAR2,
                       p_cons_inv_flag                  IN VARCHAR2,
                       p_cons_inv_type                  IN VARCHAR2,
                       p_autocash_hier_id_for_adr       IN NUMBER ,
                       p_lockbox_matching_option        IN VARCHAR2,
--{2310474
                       p_party_id                          IN NUMBER    DEFAULT NULL,
                       p_review_cycle                      IN VARCHAR2  DEFAULT NULL,
                       p_credit_classification             IN VARCHAR2  DEFAULT NULL,
                       p_last_credit_review_date           IN DATE      DEFAULT NULL,
--}
                       a_last_update_date               IN OUT NOCOPY DATE,
                       a_object_version                 IN OUT NOCOPY NUMBER,
                       p_last_update_date               IN OUT NOCOPY DATE,
                       x_cr_last_update_date            IN OUT NOCOPY DATE,
                       x_pt_last_update_date            IN OUT NOCOPY DATE,
                       x_cp_last_update_date            IN OUT NOCOPY DATE,
                       x_op_last_update_date            IN OUT NOCOPY DATE,
                       x_pp_last_update_date            IN OUT NOCOPY DATE,
                       x_account_type                   IN VARCHAR,
                       o_organization_profile_id        in out NOCOPY number,
                       o_person_profile_id              in out NOCOPY number,
                       x_msg_count                      OUT NOCOPY NUMBER,
                       x_msg_data                       OUT NOCOPY varchar2,
                       x_return_status                  OUT NOCOPY VARCHAR2,
                       c_duns_number_c                  IN VARCHAR2 DEFAULT FND_API.G_MISS_CHAR,
                       x_cust_acct_object_version       IN NUMBER   DEFAULT -1,
                       x_cust_prof_object_version       IN NUMBER   DEFAULT -1,
                       x_party_object_version           IN NUMBER   DEFAULT -1);

procedure check_unique_party_number(p_rowid in varchar2,
                                       p_party_number in varchar2
                                      );

end hz_acct_create_pkg;

 

/
