--------------------------------------------------------
--  DDL for Package HZ_TRANS_ATTRIBUTES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HZ_TRANS_ATTRIBUTES_PKG" AUTHID CURRENT_USER AS
/*$Header: ARHDQTAS.pls 120.4 2005/10/30 04:19:26 appldev noship $: ARHDQTAS.pls */

procedure INSERT_ROW (
  X_ATTRIBUTE_ID in out nocopy NUMBER,
  X_ENTITY_NAME in VARCHAR2,
  X_CUSTOM_ATTRIBUTE_PROCEDURE in VARCHAR2,
  X_SOURCE_TABLE in VARCHAR2,
  X_ATTRIBUTE_NAME in VARCHAR2,
  X_USER_DEFINED_ATTRIBUTE_NAME in VARCHAR2,
  X_DENORM_FLAG in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_OBJECT_VERSION_NUMBER NUMBER);

procedure LOCK_ROW (
  X_ATTRIBUTE_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER NUMBER
);

procedure LOCK_ROW (                               -- added due to bug 3621943
  X_ATTRIBUTE_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER NUMBER,
  X_USER_DEFINED_ATTRIBUTE_NAME in VARCHAR2
);

procedure UPDATE_ROW (
  X_ATTRIBUTE_ID in NUMBER,
  X_ENTITY_NAME in VARCHAR2,
  X_CUSTOM_ATTRIBUTE_PROCEDURE in VARCHAR2,
  X_SOURCE_TABLE in VARCHAR2,
  X_ATTRIBUTE_NAME in VARCHAR2,
  X_USER_DEFINED_ATTRIBUTE_NAME in VARCHAR2,
  X_DENORM_FLAG in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_OBJECT_VERSION_NUMBER  in out nocopy NUMBER
);
procedure DELETE_ROW (
  X_ATTRIBUTE_ID in NUMBER
 );
procedure ADD_LANGUAGE;

procedure LOAD_ROW (
  X_ATTRIBUTE_ID in NUMBER,
  X_ENTITY_NAME in VARCHAR2,
  X_CUSTOM_ATTRIBUTE_PROCEDURE in VARCHAR2,
  X_SOURCE_TABLE in VARCHAR2,
  X_ATTRIBUTE_NAME in VARCHAR2,
  X_USER_DEFINED_ATTRIBUTE_NAME in VARCHAR2,
  X_DENORM_FLAG in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_OWNER in VARCHAR2);

procedure TRANSLATE_ROW (
  X_ATTRIBUTE_ID in NUMBER,
  X_USER_DEFINED_ATTRIBUTE_NAME in VARCHAR2,
  X_OWNER in VARCHAR2);

end HZ_TRANS_ATTRIBUTES_PKG;

 

/
