--------------------------------------------------------
--  DDL for Package HZP_CPROF_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."HZP_CPROF_PKG" AUTHID CURRENT_USER as
/* $Header: ARHCPRFS.pls 120.8 2005/06/16 21:09:32 jhuang ship $ */

  PROCEDURE Insert_Row(
                       X_Customer_Profile_Id     IN OUT NOCOPY NUMBER,
                       X_Auto_Rec_Incl_Disputed_Flag    VARCHAR2,
                       X_Collector_Id                   NUMBER,
                       X_Created_By                     NUMBER,
                       X_Creation_Date                  DATE,
                       X_Credit_Balance_Statements	VARCHAR2,
                       X_Credit_Checking                VARCHAR2,
                       X_Credit_Hold                    VARCHAR2,
                       X_Customer_Id                    NUMBER,
                       X_Discount_Terms                 VARCHAR2,
                       X_Dunning_Letters                VARCHAR2,
                       X_Interest_Charges               VARCHAR2,
                       X_Last_Updated_By                NUMBER,
                       X_Last_Update_Date               DATE,
                       X_Statements                     VARCHAR2,
                       X_Status                         VARCHAR2,
                       X_Tolerance                      NUMBER,
                       X_Tax_Printing_Option            VARCHAR2,
                       X_Account_Status                 VARCHAR2,
                       X_Autocash_Hierarchy_Id          NUMBER,
                       X_Credit_Rating                  VARCHAR2,
                       X_Customer_Profile_Class_Id      NUMBER,
                       X_Discount_Grace_Days            NUMBER,
                       X_Dunning_Letter_Set_Id          NUMBER,
                       X_Interest_Period_Days           NUMBER,
                       X_Last_Update_Login              NUMBER,
                       X_Override_Terms                 VARCHAR2,
                       X_Payment_Grace_Days             NUMBER,
                       X_Percent_Collectable            NUMBER,
                       X_Risk_Code                      VARCHAR2,
                       X_Site_Use_Id                    NUMBER,
                       X_Standard_Terms                 NUMBER,
                       X_Statement_Cycle_Id             NUMBER,
                       X_Attribute_Category             VARCHAR2,
                       X_Attribute1                     VARCHAR2,
                       X_Attribute2                     VARCHAR2,
                       X_Attribute3                     VARCHAR2,
                       X_Attribute4                     VARCHAR2,
                       X_Attribute5                     VARCHAR2,
                       X_Attribute6                     VARCHAR2,
                       X_Attribute7                     VARCHAR2,
                       X_Attribute8                     VARCHAR2,
                       X_Attribute9                     VARCHAR2,
                       X_Attribute10                    VARCHAR2,
                       X_Attribute11                    VARCHAR2,
                       X_Attribute12                    VARCHAR2,
                       X_Attribute13                    VARCHAR2,
                       X_Attribute14                    VARCHAR2,
                       X_Attribute15                    VARCHAR2,
                       X_Charge_On_Fin_Charge_Flag   	VARCHAR2,
                       X_Grouping_Rule_Id               NUMBER,
                       X_Cons_Inv_Flag                  VARCHAR2,
                       X_Cons_Inv_Type                  VARCHAR2,
                       X_Clearing_Days                  NUMBER,
                       X_Jgzz_attribute_Category        VARCHAR2,
                       X_Jgzz_attribute1                VARCHAR2,
                       X_Jgzz_attribute2                VARCHAR2,
                       X_Jgzz_attribute3                VARCHAR2,
                       X_Jgzz_attribute4                VARCHAR2,
                       X_Jgzz_attribute5                VARCHAR2,
                       X_Jgzz_attribute6                VARCHAR2,
                       X_Jgzz_attribute7                VARCHAR2,
                       X_Jgzz_attribute8                VARCHAR2,
                       X_Jgzz_attribute9                VARCHAR2,
                       X_Jgzz_attribute10               VARCHAR2,
                       X_Jgzz_attribute11               VARCHAR2,
                       X_Jgzz_attribute12               VARCHAR2,
                       X_Jgzz_attribute13               VARCHAR2,
                       X_Jgzz_attribute14               VARCHAR2,
                       X_Jgzz_attribute15               VARCHAR2,
                       X_global_attribute_category        VARCHAR2,
                       X_global_attribute1                VARCHAR2,
                       X_global_attribute2                VARCHAR2,
                       X_global_attribute3                VARCHAR2,
                       X_global_attribute4                VARCHAR2,
                       X_global_attribute5                VARCHAR2,
                       X_global_attribute6                VARCHAR2,
                       X_global_attribute7                VARCHAR2,
                       X_global_attribute8                VARCHAR2,
                       X_global_attribute9                VARCHAR2,
                       X_global_attribute10               VARCHAR2,
                       X_global_attribute11               VARCHAR2,
                       X_global_attribute12               VARCHAR2,
                       X_global_attribute13               VARCHAR2,
                       X_global_attribute14               VARCHAR2,
                       X_global_attribute15               VARCHAR2,
                       X_global_attribute16               VARCHAR2,
                       X_global_attribute17               VARCHAR2,
                       X_global_attribute18               VARCHAR2,
                       X_global_attribute19               VARCHAR2,
                       X_global_attribute20               VARCHAR2,
                       X_lockbox_matching_option          VARCHAR2,
                       X_autocash_hierarchy_id_adr      NUMBER,
--{BUG 2310474
                       X_Review_Cycle                     VARCHAR2 DEFAULT NULL,
                       X_Credit_Classification            VARCHAR2 DEFAULT NULL,
                       X_Next_Credit_Review_Date          DATE     DEFAULT NULL,
                       X_Last_Credit_Review_Date          DATE     DEFAULT NULL,
                       X_Credit_Analyst_id                NUMBER   DEFAULT NULL,
                       X_Party_id                         NUMBER   DEFAULT NULL,
--}
                        x_return_status                 out NOCOPY varchar2,
                        x_msg_count                     out NOCOPY number,
                        x_msg_data                      out NOCOPY varchar2
                      );

  PROCEDURE insert_row(	x_customer_id			number,
			x_site_use_id			number,
			x_customer_profile_class_id	number,
--{2310474
                     x_party_id                   NUMBER DEFAULT NULL,
                     x_last_credit_review_date    DATE   DEFAULT NULL,
                     x_next_credit_review_date    DATE   DEFAULT NULL
--}
);




  PROCEDURE Update_Row(X_Rowid                          VARCHAR2,
                       X_Customer_Profile_Id            NUMBER,
                       X_Auto_Rec_Incl_Disputed_Flag    VARCHAR2,
                       X_Collector_Id                   NUMBER,
                       X_Credit_Balance_Statements      VARCHAR2,
                       X_Credit_Checking                VARCHAR2,
                       X_Credit_Hold                    VARCHAR2,
                       X_Customer_Id                    NUMBER,
                       X_Discount_Terms                 VARCHAR2,
                       X_Dunning_Letters                VARCHAR2,
                       X_Interest_Charges               VARCHAR2,
                       X_Last_Updated_By                NUMBER,
                       X_Last_Update_Date               DATE,
                       X_Statements                     VARCHAR2,
                       X_Status                         VARCHAR2,
                       X_Tolerance                      NUMBER,
                       X_Tax_Printing_Option            VARCHAR2,
                       X_Account_Status                 VARCHAR2,
                       X_Autocash_Hierarchy_Id          NUMBER,
                       X_Credit_Rating                  VARCHAR2,
                       X_Customer_Profile_Class_Id      NUMBER,
                       X_Discount_Grace_Days            NUMBER,
                       X_Dunning_Letter_Set_Id          NUMBER,
                       X_Interest_Period_Days           NUMBER,
                       X_Last_Update_Login              NUMBER,
                       X_Override_Terms                 VARCHAR2,
                       X_Payment_Grace_Days             NUMBER,
                       X_Percent_Collectable            NUMBER,
                       X_Risk_Code                      VARCHAR2,
                       X_Site_Use_Id                    NUMBER,
                       X_Standard_Terms                 NUMBER,
                       X_Statement_Cycle_Id             NUMBER,
                       X_Attribute_Category             VARCHAR2,
                       X_Attribute1                     VARCHAR2,
                       X_Attribute2                     VARCHAR2,
                       X_Attribute3                     VARCHAR2,
                       X_Attribute4                     VARCHAR2,
                       X_Attribute5                     VARCHAR2,
                       X_Attribute6                     VARCHAR2,
                       X_Attribute7                     VARCHAR2,
                       X_Attribute8                     VARCHAR2,
                       X_Attribute9                     VARCHAR2,
                       X_Attribute10                    VARCHAR2,
                       X_Attribute11                    VARCHAR2,
                       X_Attribute12                    VARCHAR2,
                       X_Attribute13                    VARCHAR2,
                       X_Attribute14                    VARCHAR2,
                       X_Attribute15                    VARCHAR2,
                       X_Charge_On_Fin_Charge_Flag  	VARCHAR2,
                       X_Grouping_Rule_Id               NUMBER,
                       X_Cons_Inv_Flag                  VARCHAR2,
                       X_Cons_Inv_Type                  VARCHAR2,
                       X_Clearing_Days                  NUMBER,
                       X_Jgzz_attribute_Category        VARCHAR2,
                       X_Jgzz_attribute1                VARCHAR2,
                       X_Jgzz_attribute2                VARCHAR2,
                       X_Jgzz_attribute3                VARCHAR2,
                       X_Jgzz_attribute4                VARCHAR2,
                       X_Jgzz_attribute5                VARCHAR2,
                       X_Jgzz_attribute6                VARCHAR2,
                       X_Jgzz_attribute7                VARCHAR2,
                       X_Jgzz_attribute8                VARCHAR2,
                       X_Jgzz_attribute9                VARCHAR2,
                       X_Jgzz_attribute10               VARCHAR2,
                       X_Jgzz_attribute11               VARCHAR2,
                       X_Jgzz_attribute12               VARCHAR2,
                       X_Jgzz_attribute13               VARCHAR2,
                       X_Jgzz_attribute14               VARCHAR2,
                       X_Jgzz_attribute15               VARCHAR2,
                     X_global_attribute_category        VARCHAR2,
                     X_global_attribute1                VARCHAR2,
                     X_global_attribute2                VARCHAR2,
                     X_global_attribute3                VARCHAR2,
                     X_global_attribute4                VARCHAR2,
                     X_global_attribute5                VARCHAR2,
                     X_global_attribute6                VARCHAR2,
                     X_global_attribute7                VARCHAR2,
                     X_global_attribute8                VARCHAR2,
                     X_global_attribute9                VARCHAR2,
                     X_global_attribute10               VARCHAR2,
                     X_global_attribute11               VARCHAR2,
                     X_global_attribute12               VARCHAR2,
                     X_global_attribute13               VARCHAR2,
                     X_global_attribute14               VARCHAR2,
                     X_global_attribute15               VARCHAR2,
                     X_global_attribute16               VARCHAR2,
                     X_global_attribute17               VARCHAR2,
                     X_global_attribute18               VARCHAR2,
                     X_global_attribute19               VARCHAR2,
                     X_global_attribute20               VARCHAR2,
                     X_lockbox_matching_option          VARCHAR2,
                     X_autocash_hierarchy_id_adr        NUMBER,
--{2310474
                       X_party_id                         NUMBER    DEFAULT NULL,
                       X_review_cycle                     VARCHAR2  DEFAULT NULL,
                       X_credit_classification            VARCHAR2  DEFAULT NULL,
                       X_credit_analyst_id                NUMBER    DEFAULT NULL,
                       X_last_credit_review_date          DATE      DEFAULT NULL,
                       X_next_credit_review_date          DATE      DEFAULT NULL,
--}
                     X_OBJECT_VERSION                   IN NUMBER DEFAULT -1
                      );

  PROCEDURE create_profile_from_class
		( 	x_customer_profile_class_id	in number,
			x_customer_profile_id		in out NOCOPY number,
			x_customer_id			in out NOCOPY number,
			x_site_use_id			in number,
			x_collector_id 			out NOCOPY number,
 			x_collector_name 		out NOCOPY varchar2,
 			x_credit_checking		out NOCOPY varchar2,
 			x_tolerance			out NOCOPY number,
 			x_interest_charges		out NOCOPY varchar2,
 			x_charge_on_fin_charge_flag	out NOCOPY varchar2,
 			x_interest_period_days		out NOCOPY number,
 			x_discount_terms 		out NOCOPY varchar2,
 			x_discount_grace_days		out NOCOPY number,
 			x_statements			out NOCOPY varchar2,
 			x_statement_cycle_id		out NOCOPY number,
 			x_statement_cycle_name		out NOCOPY varchar2,
 			x_credit_balance_statements	out NOCOPY varchar2,
 			x_standard_terms 		out NOCOPY number,
 			x_standard_terms_name		out NOCOPY varchar2,
 			x_override_terms 		out NOCOPY varchar2,
 			x_payment_grace_days		out NOCOPY number,
 			x_dunning_letters		out NOCOPY varchar2,
 			x_dunning_letter_set_id		out NOCOPY number,
 			x_dunning_letter_set_name	out NOCOPY varchar2,
 			x_autocash_hierarchy_id		out NOCOPY number,
 			x_autocash_hierarchy_name	out NOCOPY varchar2,
 			x_auto_rec_incl_disputed_flag	out NOCOPY varchar2,
 			x_tax_printing_option		out NOCOPY varchar2,
 			x_grouping_rule_id		out NOCOPY number,
 			x_grouping_rule_name		out NOCOPY varchar2,
                        x_cons_inv_flag                 out NOCOPY varchar2,
                        x_cons_inv_type                 out NOCOPY varchar2,
 			x_attribute_category		out NOCOPY varchar2,
 			x_attribute1			out NOCOPY varchar2,
 			x_attribute2			out NOCOPY varchar2,
 			x_attribute3			out NOCOPY varchar2,
 			x_attribute4			out NOCOPY varchar2,
 			x_attribute5			out NOCOPY varchar2,
 			x_attribute6			out NOCOPY varchar2,
 			x_attribute7			out NOCOPY varchar2,
 			x_attribute8			out NOCOPY varchar2,
 			x_attribute9			out NOCOPY varchar2,
 			x_attribute10			out NOCOPY varchar2,
 			x_attribute11			out NOCOPY varchar2,
 			x_attribute12			out NOCOPY varchar2,
 			x_attribute13			out NOCOPY varchar2,
 			x_attribute14			out NOCOPY varchar2,
 			x_attribute15			out NOCOPY varchar2,
 			x_jgzz_attribute_category	out NOCOPY varchar2,
 			x_jgzz_attribute1		out NOCOPY varchar2,
 			x_jgzz_attribute2		out NOCOPY varchar2,
 			x_jgzz_attribute3		out NOCOPY varchar2,
 			x_jgzz_attribute4		out NOCOPY varchar2,
 			x_jgzz_attribute5		out NOCOPY varchar2,
 			x_jgzz_attribute6		out NOCOPY varchar2,
 			x_jgzz_attribute7		out NOCOPY varchar2,
 			x_jgzz_attribute8		out NOCOPY varchar2,
 			x_jgzz_attribute9		out NOCOPY varchar2,
 			x_jgzz_attribute10		out NOCOPY varchar2,
 			x_jgzz_attribute11		out NOCOPY varchar2,
 			x_jgzz_attribute12		out NOCOPY varchar2,
 			x_jgzz_attribute13		out NOCOPY varchar2,
 			x_jgzz_attribute14		out NOCOPY varchar2,
 			x_jgzz_attribute15		out NOCOPY varchar2,
                        x_lockbox_matching_option       out NOCOPY varchar2,
                        x_lockbox_matching_name         out NOCOPY varchar2,
                        x_autocash_hierarchy_id_adr     out NOCOPY number,
                        x_autocash_hierarchy_name_adr   out NOCOPY varchar2,
                        x_return_status                 out NOCOPY varchar2,
                        x_msg_count                     out NOCOPY number,
                        x_msg_data                      out NOCOPY varchar2,
                        --{BUG#3046535
                        p_keep_replace                  IN VARCHAR2 DEFAULT 'KEEP'
                        --}
			);

--
  PROCEDURE create_profile_from_class
		( 	x_customer_profile_class_id	in number,
			x_customer_profile_id		in out NOCOPY number,
			x_customer_id			in out NOCOPY number,
			x_site_use_id			in number,
			x_collector_id 			out NOCOPY number,
 			x_collector_name 		out NOCOPY varchar2,
 			x_credit_checking		out NOCOPY varchar2,
 			x_tolerance			out NOCOPY number,
 			x_interest_charges		out NOCOPY varchar2,
 			x_charge_on_fin_charge_flag	out NOCOPY varchar2,
 			x_interest_period_days		out NOCOPY number,
 			x_discount_terms 		out NOCOPY varchar2,
 			x_discount_grace_days		out NOCOPY number,
 			x_statements			out NOCOPY varchar2,
 			x_statement_cycle_id		out NOCOPY number,
 			x_statement_cycle_name		out NOCOPY varchar2,
 			x_credit_balance_statements	out NOCOPY varchar2,
 			x_standard_terms 		out NOCOPY number,
 			x_standard_terms_name		out NOCOPY varchar2,
 			x_override_terms 		out NOCOPY varchar2,
 			x_payment_grace_days		out NOCOPY number,
 			x_dunning_letters		out NOCOPY varchar2,
 			x_dunning_letter_set_id		out NOCOPY number,
 			x_dunning_letter_set_name	out NOCOPY varchar2,
 			x_autocash_hierarchy_id		out NOCOPY number,
 			x_autocash_hierarchy_name	out NOCOPY varchar2,
 			x_auto_rec_incl_disputed_flag	out NOCOPY varchar2,
 			x_tax_printing_option		out NOCOPY varchar2,
 			x_grouping_rule_id		out NOCOPY number,
 			x_grouping_rule_name		out NOCOPY varchar2,
                        x_cons_inv_flag                 out NOCOPY varchar2,
                        x_cons_inv_type                 out NOCOPY varchar2,
 			x_attribute_category		out NOCOPY varchar2,
 			x_attribute1			out NOCOPY varchar2,
 			x_attribute2			out NOCOPY varchar2,
 			x_attribute3			out NOCOPY varchar2,
 			x_attribute4			out NOCOPY varchar2,
 			x_attribute5			out NOCOPY varchar2,
 			x_attribute6			out NOCOPY varchar2,
 			x_attribute7			out NOCOPY varchar2,
 			x_attribute8			out NOCOPY varchar2,
 			x_attribute9			out NOCOPY varchar2,
 			x_attribute10			out NOCOPY varchar2,
 			x_attribute11			out NOCOPY varchar2,
 			x_attribute12			out NOCOPY varchar2,
 			x_attribute13			out NOCOPY varchar2,
 			x_attribute14			out NOCOPY varchar2,
 			x_attribute15			out NOCOPY varchar2,
 			x_jgzz_attribute_category	out NOCOPY varchar2,
 			x_jgzz_attribute1		out NOCOPY varchar2,
 			x_jgzz_attribute2		out NOCOPY varchar2,
 			x_jgzz_attribute3		out NOCOPY varchar2,
 			x_jgzz_attribute4		out NOCOPY varchar2,
 			x_jgzz_attribute5		out NOCOPY varchar2,
 			x_jgzz_attribute6		out NOCOPY varchar2,
 			x_jgzz_attribute7		out NOCOPY varchar2,
 			x_jgzz_attribute8		out NOCOPY varchar2,
 			x_jgzz_attribute9		out NOCOPY varchar2,
 			x_jgzz_attribute10		out NOCOPY varchar2,
 			x_jgzz_attribute11		out NOCOPY varchar2,
 			x_jgzz_attribute12		out NOCOPY varchar2,
 			x_jgzz_attribute13		out NOCOPY varchar2,
 			x_jgzz_attribute14		out NOCOPY varchar2,
 			x_jgzz_attribute15		out NOCOPY varchar2,
                        x_lockbox_matching_option       out NOCOPY varchar2,
                        x_lockbox_matching_name         out NOCOPY varchar2,
                        x_autocash_hierarchy_id_adr     out NOCOPY number,
                        x_autocash_hierarchy_name_adr   out NOCOPY varchar2,
--{2310474
                        x_review_cycle                  out NOCOPY varchar2,
                        x_credit_classification         out NOCOPY varchar2,
                        x_credit_classification_m       out NOCOPY varchar2,
                        x_review_cycle_name             out NOCOPY varchar2,
                        x_credit_analyst_id             out NOCOPY number,
                        x_credit_analyst_name           out NOCOPY varchar2,
--}
                        x_return_status                 out NOCOPY varchar2,
                        x_msg_count                     out NOCOPY number,
                        x_msg_data                      out NOCOPY varchar2,
                        --{BUG#3046535
                        p_keep_replace                  IN VARCHAR2 DEFAULT 'KEEP'
                        --}
			);

/*---------------------------------------------------------------+
 | PROCEDURE :  CREATE_PROFILE_AMOUNT                            |
 |                                                               |
 | PARAMETERS :                                                  |
 |   Arguments in the record type                                |
 |   Hz_Customer_Profile_V2pub.Cust_Profile_Amt_Rec_Type         |
 |                                                               |
 | DESCRIPTION :                                                 |
 |  From the arguments entered contruct the recors type and call |
 |  Hz_Customer_Profile_V2pub.create_cust_profile_amt            |
 |                                                               |
 | HISTORY :                                                     |
 |  12-DEC-2002   H. Yu   Created                                |
 | 16/07/04 Bhushan Dhotkar bug3751887 :Replaced 'TCA-FORM-WRAPPER'
 |                   to 'TCA_FORM_WRAPPER' for  created_by_module|
 +---------------------------------------------------------------*/
 PROCEDURE create_profile_amount
  ( p_cust_account_profile_id         IN    NUMBER,
    p_currency_code                   IN    VARCHAR2,
    p_trx_credit_limit                IN    NUMBER,
    p_overall_credit_limit            IN    NUMBER,
    p_min_dunning_amount              IN    NUMBER,
    p_min_dunning_invoice_amount      IN    NUMBER,
    p_max_interest_charge             IN    NUMBER,
    p_min_statement_amount            IN    NUMBER,
    p_auto_rec_min_receipt_amount     IN    NUMBER,
    p_interest_rate                   IN    NUMBER,
    p_attribute_category              IN    VARCHAR2 DEFAULT NULL,
    p_attribute1                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute2                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute3                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute4                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute5                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute6                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute7                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute8                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute9                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute10                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute11                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute12                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute13                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute14                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute15                     IN    VARCHAR2 DEFAULT NULL,
    p_min_fc_balance_amount           IN    NUMBER,
    p_min_fc_invoice_amount           IN    NUMBER,
    p_cust_account_id                 IN    NUMBER,
    p_site_use_id                     IN    NUMBER,
    p_expiration_date                 IN    DATE,
    p_jgzz_attribute_category         IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute1                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute2                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute3                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute4                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute5                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute6                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute7                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute8                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute9                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute10                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute11                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute12                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute13                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute14                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute15                IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute1               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute2               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute3               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute4               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute5               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute6               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute7               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute8               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute9               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute10              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute11              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute12              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute13              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute14              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute15              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute16              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute17              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute18              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute19              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute20              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute_category       IN    VARCHAR2 DEFAULT NULL,
    p_created_by_module               IN    VARCHAR2 DEFAULT 'TCA_FORM_WRAPPER',
    p_application_id                  IN    NUMBER   DEFAULT NULL,
    x_cust_acct_profile_amt_id        OUT   NOCOPY NUMBER,
    x_return_status                   OUT   NOCOPY VARCHAR2,
    x_msg_count                       OUT   NOCOPY NUMBER,
    x_msg_data                        OUT   NOCOPY VARCHAR2 );


/*---------------------------------------------------------------+
 | PROCEDURE :  UPDATE_PROFILE_AMOUNT                            |
 |                                                               |
 | PARAMETERS :                                                  |
 |   Arguments in the record type                                |
 |   Hz_Customer_Profile_V2pub.Cust_Profile_Amt_Rec_Type         |
 |                                                               |
 | DESCRIPTION :                                                 |
 |  From the arguments entered contruct the recors type and call |
 |  Hz_Customer_Profile_V2pub.update_cust_profile_amt            |
 |                                                               |
 | HISTORY :                                                     |
 |  12-DEC-2002   H. Yu   Created                                |
 +---------------------------------------------------------------*/
 PROCEDURE update_profile_amount
  ( p_cust_acct_profile_amt_id        IN    NUMBER,
    p_cust_account_profile_id         IN    NUMBER,
    p_currency_code                   IN    VARCHAR2,
    p_trx_credit_limit                IN    NUMBER,
    p_overall_credit_limit            IN    NUMBER,
    p_min_dunning_amount              IN    NUMBER,
    p_min_dunning_invoice_amount      IN    NUMBER,
    p_max_interest_charge             IN    NUMBER,
    p_min_statement_amount            IN    NUMBER,
    p_auto_rec_min_receipt_amount     IN    NUMBER,
    p_interest_rate                   IN    NUMBER,
    p_attribute_category              IN    VARCHAR2 DEFAULT NULL,
    p_attribute1                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute2                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute3                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute4                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute5                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute6                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute7                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute8                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute9                      IN    VARCHAR2 DEFAULT NULL,
    p_attribute10                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute11                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute12                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute13                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute14                     IN    VARCHAR2 DEFAULT NULL,
    p_attribute15                     IN    VARCHAR2 DEFAULT NULL,
    p_min_fc_balance_amount           IN    NUMBER,
    p_min_fc_invoice_amount           IN    NUMBER,
    p_cust_account_id                 IN    NUMBER,
    p_site_use_id                     IN    NUMBER,
    p_expiration_date                 IN    DATE,
    p_jgzz_attribute_category         IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute1                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute2                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute3                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute4                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute5                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute6                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute7                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute8                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute9                 IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute10                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute11                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute12                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute13                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute14                IN    VARCHAR2 DEFAULT NULL,
    p_jgzz_attribute15                IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute1               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute2               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute3               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute4               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute5               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute6               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute7               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute8               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute9               IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute10              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute11              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute12              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute13              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute14              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute15              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute16              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute17              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute18              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute19              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute20              IN    VARCHAR2 DEFAULT NULL,
    p_global_attribute_category       IN    VARCHAR2 DEFAULT NULL,
    x_return_status                   OUT   NOCOPY VARCHAR2,
    x_msg_count                       OUT   NOCOPY NUMBER,
    x_msg_data                        OUT   NOCOPY VARCHAR2,
    p_object_version                  IN    NUMBER DEFAULT -1,
    X_Last_Update_Date                IN    DATE);

/*---------------------------------------------------------------+
 | PROCEDURE :  DELETE_PROFILE_AMOUNT                            |
 |                                                               |
 | PARAMETERS :                                                  |
 |   NUMBER Customer_profile_amt_id                              |
 |                                                               |
 | DESCRIPTION :                                                 |
 |  Delete a record from Hz_Cust_Profile_Amts                    |
 |                                                               |
 | HISTORY :                                                     |
 |  12-DEC-2002   H. Yu   Created                                |
 +---------------------------------------------------------------*/
 PROCEDURE delete_profile_amount
 (p_cust_acct_profile_amt_id        IN    NUMBER,
  x_return_status                   OUT   NOCOPY VARCHAR2,
  x_msg_count                       OUT   NOCOPY NUMBER,
  x_msg_data                        OUT   NOCOPY VARCHAR2);

END hzp_cprof_pkg;

 

/
