--------------------------------------------------------
--  DDL for Package IBC_AUDIT_LOGS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IBC_AUDIT_LOGS_PKG" AUTHID CURRENT_USER AS
/* $Header: ibctlogs.pls 115.10 2002/11/15 00:31:15 svatsa noship $*/

-- Purpose: Table Handler for Ibc_Audit_Logs table.

-- MODIFICATION HISTORY
-- Person            Date        Comments
-- ---------         ------      ------------------------------------------
-- Sri Rangarajan    01/06/2002      Created Package
-- shitij.vatsa      11/04/2002      Updated for NOCOPY

PROCEDURE INSERT_ROW (
  px_AUDIT_LOG_ID IN OUT NOCOPY NUMBER,
  p_ACTIVITY IN VARCHAR2,
  p_parent_value  IN VARCHAR2,
  p_USER_ID IN NUMBER,
  p_TIME_STAMP IN DATE,
  p_OBJECT_TYPE IN VARCHAR2,
  p_OBJECT_VALUE1 IN VARCHAR2,
  p_OBJECT_VALUE2 IN VARCHAR2 DEFAULT NULL,
  p_OBJECT_VALUE3 IN VARCHAR2 DEFAULT NULL,
  p_OBJECT_VALUE4 IN VARCHAR2 DEFAULT NULL,
  p_OBJECT_VALUE5 IN VARCHAR2 DEFAULT NULL,
  p_DESCRIPTION IN VARCHAR2 DEFAULT NULL,

  P_OBJECT_STATUS IN VARCHAR2 DEFAULT NULL,
  P_INTERNAL_FLAG IN VARCHAR2 DEFAULT NULL,
  P_MESSAGE_APPLICATION IN VARCHAR2 DEFAULT NULL,
  P_MESSAGE_NAME IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_VALUE IN VARCHAR2 DEFAULT NULL,

  p_OBJECT_VERSION_NUMBER IN NUMBER,
  p_CREATION_DATE IN DATE      DEFAULT NULL,
  p_CREATED_BY IN NUMBER     DEFAULT NULL,
  p_LAST_UPDATE_DATE IN DATE    DEFAULT NULL,
  p_LAST_UPDATED_BY IN NUMBER   DEFAULT NULL,
  p_LAST_UPDATE_LOGIN IN NUMBER  DEFAULT NULL,
  x_ROWID OUT NOCOPY VARCHAR2);

PROCEDURE LOCK_ROW (
  p_AUDIT_LOG_ID IN NUMBER,
  p_ACTIVITY IN VARCHAR2,
  p_USER_ID IN NUMBER,
  p_TIME_STAMP IN DATE,
  p_OBJECT_TYPE IN VARCHAR2,
  p_OBJECT_VALUE1 IN VARCHAR2,
  p_OBJECT_VALUE2 IN VARCHAR2,
  p_OBJECT_VALUE3 IN VARCHAR2,
  p_OBJECT_VALUE4 IN VARCHAR2,
  p_OBJECT_VALUE5 IN VARCHAR2,
  p_DESCRIPTION IN VARCHAR2,

  P_OBJECT_STATUS IN VARCHAR2 DEFAULT NULL,
  P_INTERNAL_FLAG IN VARCHAR2 DEFAULT NULL,
  P_MESSAGE_APPLICATION IN VARCHAR2 DEFAULT NULL,
  P_MESSAGE_NAME IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_VALUE IN VARCHAR2 DEFAULT NULL,

  p_OBJECT_VERSION_NUMBER IN NUMBER
);

/*PROCEDURE UPDATE_ROW (
  p_AUDIT_LOG_ID    IN  NUMBER,
  p_ACTIVITY    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_parent_value  IN VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_DESCRIPTION    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_LAST_UPDATED_BY    IN  NUMBER DEFAULT  FND_API.G_MISS_NUM,
  p_LAST_UPDATE_DATE    IN  DATE DEFAULT  FND_API.G_MISS_DATE,
  p_LAST_UPDATE_LOGIN    IN  NUMBER DEFAULT  FND_API.G_MISS_NUM,
  p_OBJECT_TYPE    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_OBJECT_VALUE1    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_OBJECT_VALUE2    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_OBJECT_VALUE3    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_OBJECT_VALUE4    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,
  p_OBJECT_VALUE5    IN  VARCHAR2 DEFAULT  FND_API.G_MISS_CHAR,

  P_OBJECT_STATUS IN VARCHAR2 DEFAULT NULL,
  P_INTERNAL_FLAG IN VARCHAR2 DEFAULT NULL,
  P_MESSAGE_NAME IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO1_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO2_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO3_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO4_VALUE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_REF_TYPE IN VARCHAR2 DEFAULT NULL,
  P_EXTRA_INFO5_VALUE IN VARCHAR2 DEFAULT NULL,

  p_OBJECT_VERSION_NUMBER    IN  NUMBER DEFAULT  FND_API.G_MISS_NUM,
  p_TIME_STAMP    IN  DATE DEFAULT  FND_API.G_MISS_DATE,
  p_USER_ID    IN  NUMBER DEFAULT  FND_API.G_MISS_NUM
);
*/

PROCEDURE DELETE_ROW (
  p_AUDIT_LOG_ID IN NUMBER
);

END Ibc_Audit_Logs_Pkg;


 

/
