--------------------------------------------------------
--  DDL for Package ICX_CAT_CATEGORIES_PVT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ICX_CAT_CATEGORIES_PVT" AUTHID CURRENT_USER AS
/* $Header: ICXVCATS.pls 120.0 2005/10/20 06:47:53 srmani noship $ */

procedure INSERT_ROW (
  X_RT_CATEGORY_ID in NUMBER,
  X_CATEGORY_NAME in VARCHAR2,
  X_UPPER_CATEGORY_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_TYPE in NUMBER,
  X_KEY in VARCHAR2,
  X_TITLE in VARCHAR2,
  X_ITEM_COUNT in NUMBER,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_APPLICATION_ID in NUMBER,
  X_PROGRAM_ID in NUMBER,
  X_PROGRAM_UPDATE_DATE in DATE);

procedure LOCK_ROW (
  X_RT_CATEGORY_ID in NUMBER,
  X_CATEGORY_NAME in VARCHAR2,
  X_UPPER_CATEGORY_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_TYPE in NUMBER,
  X_KEY in VARCHAR2,
  X_TITLE in VARCHAR2,
  X_ITEM_COUNT in NUMBER);

procedure UPDATE_ROW (
  X_RT_CATEGORY_ID in NUMBER,
  X_CATEGORY_NAME in VARCHAR2,
  X_UPPER_CATEGORY_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_TYPE in NUMBER,
  X_KEY in VARCHAR2,
  X_TITLE in VARCHAR2,
  X_ITEM_COUNT in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_APPLICATION_ID in NUMBER,
  X_PROGRAM_ID in NUMBER,
  X_PROGRAM_UPDATE_DATE in DATE);

procedure DELETE_ROW (
  X_RT_CATEGORY_ID in NUMBER
);

procedure TRANSLATE_ROW(
      X_RT_CATEGORY_ID      in  VARCHAR2,
      X_OWNER		            in  VARCHAR2,
      X_CATEGORY_NAME       in  VARCHAR2,
      X_UPPER_CATEGORY_NAME in  VARCHAR2,
      X_DESCRIPTION         in  VARCHAR2,
      X_CUSTOM_MODE         IN VARCHAR2,
      X_LAST_UPDATE_DATE    IN VARCHAR2);

procedure LOAD_ROW(
      X_RT_CATEGORY_ID      in  VARCHAR2,
      X_OWNER		    in  VARCHAR2,
      X_CATEGORY_NAME       in  VARCHAR2,
      X_UPPER_CATEGORY_NAME in  VARCHAR2,
      X_DESCRIPTION         in  VARCHAR2,
      X_TYPE                in  VARCHAR2,
      X_KEY                 in  VARCHAR2,
      X_TITLE               in  VARCHAR2,
      X_ITEM_COUNT	        in  VARCHAR2,
      X_CUSTOM_MODE         IN VARCHAR2,
      X_LAST_UPDATE_DATE    IN VARCHAR2);

procedure ADD_LANGUAGE;

end ICX_CAT_CATEGORIES_PVT;

 

/
