--------------------------------------------------------
--  DDL for Package IEX_UWQ_DELIN_ENUMS_PVT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IEX_UWQ_DELIN_ENUMS_PVT" AUTHID CURRENT_USER as
/* $Header: iexendls.pls 120.2 2006/09/06 06:01:05 lkkumar ship $ */


PROCEDURE ENUMERATE_DELIN_NODES
  (P_RESOURCE_ID      IN NUMBER
  ,P_LANGUAGE         IN VARCHAR2
  ,P_SOURCE_LANG      IN VARCHAR2
  ,P_SEL_ENUM_ID      IN NUMBER
  );

PROCEDURE ENUMERATE_CU_DELIN_NODES
  (P_RESOURCE_ID      IN NUMBER
  ,P_LANGUAGE         IN VARCHAR2
  ,P_SOURCE_LANG      IN VARCHAR2
  ,P_SEL_ENUM_ID      IN NUMBER
  );

PROCEDURE ENUMERATE_ACC_DELIN_NODES
  (P_RESOURCE_ID      IN NUMBER
  ,P_LANGUAGE         IN VARCHAR2
  ,P_SOURCE_LANG      IN VARCHAR2
  ,P_SEL_ENUM_ID      IN NUMBER
  );

PROCEDURE ENUMERATE_BILLTO_DELIN_NODES
  (P_RESOURCE_ID      IN NUMBER
  ,P_LANGUAGE         IN VARCHAR2
  ,P_SOURCE_LANG      IN VARCHAR2
  ,P_SEL_ENUM_ID      IN NUMBER
  );

PROCEDURE SET_MO_GLOBAL;

end IEX_UWQ_DELIN_ENUMS_PVT;

/
