--------------------------------------------------------
--  DDL for Package IEX_DEL_STATUSES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IEX_DEL_STATUSES_PKG" AUTHID CURRENT_USER AS
/* $Header: iextdlss.pls 120.0 2004/01/24 03:21:56 appldev noship $ */
/* Insert_Row procedure */
PROCEDURE Insert_Row(x_rowid	IN OUT NOCOPY VARCHAR2
	,p_DEL_STATUS_ID		NUMBER
	,p_OBJECT_VERSION_NUMBER		NUMBER
	,p_SCORE_VALUE_LOW		NUMBER
	,p_SCORE_VALUE_HIGH		NUMBER
	,p_DEL_STATUS		VARCHAR2
	,p_SCORE_ID		NUMBER
	,p_REQUEST_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_APPLICATION_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_UPDATE_DATE		DATE	DEFAULT NULL
	,p_CREATED_BY		NUMBER
	,p_CREATION_DATE		DATE
	,p_LAST_UPDATED_BY		NUMBER
	,p_LAST_UPDATE_DATE		DATE
	,p_LAST_UPDATE_LOGIN		NUMBER	DEFAULT NULL
);


PROCEDURE Insert_Row_With_Defaults
	(x_rowid		IN OUT NOCOPY VARCHAR2
	,p_SCORE_VALUE_LOW		NUMBER
	,p_SCORE_VALUE_HIGH		NUMBER
	,p_DEL_STATUS			VARCHAR2
	,p_SCORE_ID			NUMBER
	,Commit_flag			VARCHAR2
);


/* Update_Row procedure */
PROCEDURE Update_Row(x_rowid	VARCHAR2
	,p_DEL_STATUS_ID		NUMBER
	,p_OBJECT_VERSION_NUMBER		NUMBER
	,p_SCORE_VALUE_LOW		NUMBER
	,p_SCORE_VALUE_HIGH		NUMBER
	,p_DEL_STATUS		VARCHAR2
	,p_SCORE_ID		NUMBER
	,p_REQUEST_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_APPLICATION_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_UPDATE_DATE		DATE	DEFAULT NULL
	,p_CREATED_BY		NUMBER
	,p_CREATION_DATE		DATE
	,p_LAST_UPDATED_BY		NUMBER
	,p_LAST_UPDATE_DATE		DATE
	,p_LAST_UPDATE_LOGIN		NUMBER	DEFAULT NULL
);

/* Delete_Row procedure */
PROCEDURE Delete_Row(x_rowid	VARCHAR2);

PROCEDURE Delete_del_config(p_scoreId NUMBER)  ;

/* Lock_Row procedure */
PROCEDURE Lock_Row(x_rowid	VARCHAR2
	,p_DEL_STATUS_ID		NUMBER
	,p_OBJECT_VERSION_NUMBER		NUMBER
	,p_SCORE_VALUE_LOW		NUMBER
	,p_SCORE_VALUE_HIGH		NUMBER
	,p_DEL_STATUS		VARCHAR2
	,p_SCORE_ID		NUMBER
	,p_REQUEST_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_APPLICATION_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_ID		NUMBER	DEFAULT NULL
	,p_PROGRAM_UPDATE_DATE		DATE	DEFAULT NULL
	,p_CREATED_BY		NUMBER
	,p_CREATION_DATE		DATE
	,p_LAST_UPDATED_BY		NUMBER
	,p_LAST_UPDATE_DATE		DATE
	,p_LAST_UPDATE_LOGIN		NUMBER	DEFAULT NULL
);
END;

 

/
