--------------------------------------------------------
--  DDL for Package IGC_CC_HEADER_HISTORY_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGC_CC_HEADER_HISTORY_PKG" AUTHID CURRENT_USER as
/* $Header: IGCCHDHS.pls 120.4.12010000.2 2008/08/04 14:50:49 sasukuma ship $ */


/* ==============================================================================================
                         PROCEDURE Insert_Row Overloaded Procedure for CC_REF_NUM addition
   =============================================================================================*/

  PROCEDURE Insert_Row(
                p_api_version               IN       NUMBER,
                p_init_msg_list             IN       VARCHAR2 := FND_API.G_FALSE,
                p_commit                    IN       VARCHAR2 := FND_API.G_FALSE,
                p_validation_level          IN       NUMBER   := FND_API.G_VALID_LEVEL_FULL,
                X_return_status             OUT NOCOPY      VARCHAR2,
                X_msg_count                 OUT NOCOPY      NUMBER,
                X_msg_data                  OUT NOCOPY      VARCHAR2,
                p_Rowid                  IN OUT NOCOPY      VARCHAR2,
                p_CC_Header_Id                    IGC_CC_HEADER_HISTORY.CC_Header_Id%TYPE,
                p_Org_id                          IGC_CC_HEADER_HISTORY.Org_id%TYPE,
                p_CC_Type                         IGC_CC_HEADER_HISTORY.CC_Type%TYPE,
                p_CC_Num                          IGC_CC_HEADER_HISTORY.CC_Num%TYPE,
                p_CC_Ref_Num                      IGC_CC_HEADER_HISTORY.CC_Ref_Num%TYPE,
                p_CC_Version_num                  IGC_CC_HEADER_HISTORY.CC_Version_Num%TYPE,
                p_CC_Version_Action               IGC_CC_HEADER_HISTORY.CC_Version_Action%TYPE,
                p_CC_State                        IGC_CC_HEADER_HISTORY.CC_State%TYPE,
                p_Parent_Header_Id                IGC_CC_HEADER_HISTORY.Parent_Header_Id%TYPE,
                p_CC_ctrl_status                  IGC_CC_HEADER_HISTORY.CC_ctrl_status%TYPE,
                p_CC_Encmbrnc_Status              IGC_CC_HEADER_HISTORY.CC_Encmbrnc_Status%TYPE,
                p_CC_Apprvl_Status                IGC_CC_HEADER_HISTORY.CC_Apprvl_Status%TYPE,
                p_Vendor_Id                       IGC_CC_HEADER_HISTORY.Vendor_Id%TYPE,
                p_Vendor_Site_Id                  IGC_CC_HEADER_HISTORY.Vendor_Site_Id%TYPE,
                p_Vendor_Contact_Id               IGC_CC_HEADER_HISTORY.Vendor_Contact_Id%TYPE,
                p_Term_Id                         IGC_CC_HEADER_HISTORY.Term_Id%TYPE,
                p_Location_Id                     IGC_CC_HEADER_HISTORY.Location_Id%TYPE,
                p_Set_Of_Books_Id                 IGC_CC_HEADER_HISTORY.Set_Of_Books_Id%TYPE,
                p_CC_Acct_Date                    IGC_CC_HEADER_HISTORY.CC_Acct_Date%TYPE,
                p_CC_Desc                         IGC_CC_HEADER_HISTORY.CC_Desc%TYPE,
                p_CC_Start_Date                   IGC_CC_HEADER_HISTORY.CC_Start_Date%TYPE,
                p_CC_End_Date                     IGC_CC_HEADER_HISTORY.CC_End_Date%TYPE,
                p_CC_Owner_User_Id                IGC_CC_HEADER_HISTORY.CC_Owner_User_Id%TYPE,
                p_CC_Preparer_User_Id             IGC_CC_HEADER_HISTORY.CC_Preparer_User_Id%TYPE,
                p_Currency_Code                   IGC_CC_HEADER_HISTORY.Currency_Code%TYPE,
                p_Conversion_Type                 IGC_CC_HEADER_HISTORY.Conversion_Type%TYPE,
                p_Conversion_Date                 IGC_CC_HEADER_HISTORY.Conversion_Date%TYPE,
                p_Conversion_Rate                 IGC_CC_HEADER_HISTORY.Conversion_Rate%TYPE,
                p_Last_Update_Date                IGC_CC_HEADER_HISTORY.Last_Update_Date%TYPE,
                p_Last_Updated_By                 IGC_CC_HEADER_HISTORY.Last_Updated_By%TYPE,
                p_Last_Update_Login               IGC_CC_HEADER_HISTORY.Last_Update_Login%TYPE,
                p_Created_By                      IGC_CC_HEADER_HISTORY.Created_By%TYPE,
                p_Creation_Date                   IGC_CC_HEADER_HISTORY.Creation_Date%TYPE,
                p_Wf_Item_Type                    IGC_CC_HEADER_HISTORY.Wf_Item_Type%TYPE,
                p_Wf_Item_Key                     IGC_CC_HEADER_HISTORY.Wf_Item_Key%TYPE,
                p_CC_Current_User_Id              IGC_CC_HEADERS.CC_Current_User_Id%TYPE,
                p_Attribute1                      IGC_CC_HEADER_HISTORY.Attribute1%TYPE,
                p_Attribute2                      IGC_CC_HEADER_HISTORY.Attribute2%TYPE,
                p_Attribute3                      IGC_CC_HEADER_HISTORY.Attribute3%TYPE,
                p_Attribute4                      IGC_CC_HEADER_HISTORY.Attribute4%TYPE,
                p_Attribute5                      IGC_CC_HEADER_HISTORY.Attribute5%TYPE,
                p_Attribute6                      IGC_CC_HEADER_HISTORY.Attribute6%TYPE,
                p_Attribute7                      IGC_CC_HEADER_HISTORY.Attribute7%TYPE,
                p_Attribute8                      IGC_CC_HEADER_HISTORY.Attribute8%TYPE,
                p_Attribute9                      IGC_CC_HEADER_HISTORY.Attribute9%TYPE,
                p_Attribute10                     IGC_CC_HEADER_HISTORY.Attribute10%TYPE,
                p_Attribute11                     IGC_CC_HEADER_HISTORY.Attribute11%TYPE,
                p_Attribute12                     IGC_CC_HEADER_HISTORY.Attribute12%TYPE,
                p_Attribute13                     IGC_CC_HEADER_HISTORY.Attribute13%TYPE,
                p_Attribute14                     IGC_CC_HEADER_HISTORY.Attribute14%TYPE,
                p_Attribute15                     IGC_CC_HEADER_HISTORY.Attribute15%TYPE,
                p_Context                         IGC_CC_HEADER_HISTORY.Context%TYPE,
                p_CC_Guarantee_Flag               IGC_CC_HEADER_HISTORY.CC_Guarantee_Flag%TYPE,
                G_FLAG                IN OUT NOCOPY      VARCHAR2
  );

/* ==============================================================================================
                         PROCEDURE Insert_Row
   =============================================================================================*/


  PROCEDURE Insert_Row(
                p_api_version               IN       NUMBER,
                p_init_msg_list             IN       VARCHAR2 := FND_API.G_FALSE,
                p_commit                    IN       VARCHAR2 := FND_API.G_FALSE,
                p_validation_level          IN       NUMBER   := FND_API.G_VALID_LEVEL_FULL,
                X_return_status             OUT NOCOPY      VARCHAR2,
                X_msg_count                 OUT NOCOPY      NUMBER,
                X_msg_data                  OUT NOCOPY      VARCHAR2,
                p_Rowid                  IN OUT NOCOPY      VARCHAR2,
                p_CC_Header_Id                    IGC_CC_HEADER_HISTORY.CC_Header_Id%TYPE,
                p_Org_id                          IGC_CC_HEADER_HISTORY.Org_id%TYPE,
                p_CC_Type                         IGC_CC_HEADER_HISTORY.CC_Type%TYPE,
                p_CC_Num                          IGC_CC_HEADER_HISTORY.CC_Num%TYPE,
                p_CC_Version_num                  IGC_CC_HEADER_HISTORY.CC_Version_Num%TYPE,
                p_CC_Version_Action               IGC_CC_HEADER_HISTORY.CC_Version_Action%TYPE,
                p_CC_State                        IGC_CC_HEADER_HISTORY.CC_State%TYPE,
                p_Parent_Header_Id                IGC_CC_HEADER_HISTORY.Parent_Header_Id%TYPE,
                p_CC_ctrl_status                  IGC_CC_HEADER_HISTORY.CC_ctrl_status%TYPE,
                p_CC_Encmbrnc_Status              IGC_CC_HEADER_HISTORY.CC_Encmbrnc_Status%TYPE,
                p_CC_Apprvl_Status                IGC_CC_HEADER_HISTORY.CC_Apprvl_Status%TYPE,
                p_Vendor_Id                       IGC_CC_HEADER_HISTORY.Vendor_Id%TYPE,
                p_Vendor_Site_Id                  IGC_CC_HEADER_HISTORY.Vendor_Site_Id%TYPE,
                p_Vendor_Contact_Id               IGC_CC_HEADER_HISTORY.Vendor_Contact_Id%TYPE,
                p_Term_Id                         IGC_CC_HEADER_HISTORY.Term_Id%TYPE,
                p_Location_Id                     IGC_CC_HEADER_HISTORY.Location_Id%TYPE,
                p_Set_Of_Books_Id                 IGC_CC_HEADER_HISTORY.Set_Of_Books_Id%TYPE,
                p_CC_Acct_Date                    IGC_CC_HEADER_HISTORY.CC_Acct_Date%TYPE,
                p_CC_Desc                         IGC_CC_HEADER_HISTORY.CC_Desc%TYPE,
                p_CC_Start_Date                   IGC_CC_HEADER_HISTORY.CC_Start_Date%TYPE,
                p_CC_End_Date                     IGC_CC_HEADER_HISTORY.CC_End_Date%TYPE,
                p_CC_Owner_User_Id                IGC_CC_HEADER_HISTORY.CC_Owner_User_Id%TYPE,
                p_CC_Preparer_User_Id             IGC_CC_HEADER_HISTORY.CC_Preparer_User_Id%TYPE,
                p_Currency_Code                   IGC_CC_HEADER_HISTORY.Currency_Code%TYPE,
                p_Conversion_Type                 IGC_CC_HEADER_HISTORY.Conversion_Type%TYPE,
                p_Conversion_Date                 IGC_CC_HEADER_HISTORY.Conversion_Date%TYPE,
                p_Conversion_Rate                 IGC_CC_HEADER_HISTORY.Conversion_Rate%TYPE,
                p_Last_Update_Date                IGC_CC_HEADER_HISTORY.Last_Update_Date%TYPE,
                p_Last_Updated_By                 IGC_CC_HEADER_HISTORY.Last_Updated_By%TYPE,
                p_Last_Update_Login               IGC_CC_HEADER_HISTORY.Last_Update_Login%TYPE,
                p_Created_By                      IGC_CC_HEADER_HISTORY.Created_By%TYPE,
                p_Creation_Date                   IGC_CC_HEADER_HISTORY.Creation_Date%TYPE,
                p_Wf_Item_Type                    IGC_CC_HEADER_HISTORY.Wf_Item_Type%TYPE,
                p_Wf_Item_Key                     IGC_CC_HEADER_HISTORY.Wf_Item_Key%TYPE,
                p_CC_Current_User_Id              IGC_CC_HEADERS.CC_Current_User_Id%TYPE,
                p_Attribute1                      IGC_CC_HEADER_HISTORY.Attribute1%TYPE,
                p_Attribute2                      IGC_CC_HEADER_HISTORY.Attribute2%TYPE,
                p_Attribute3                      IGC_CC_HEADER_HISTORY.Attribute3%TYPE,
                p_Attribute4                      IGC_CC_HEADER_HISTORY.Attribute4%TYPE,
                p_Attribute5                      IGC_CC_HEADER_HISTORY.Attribute5%TYPE,
                p_Attribute6                      IGC_CC_HEADER_HISTORY.Attribute6%TYPE,
                p_Attribute7                      IGC_CC_HEADER_HISTORY.Attribute7%TYPE,
                p_Attribute8                      IGC_CC_HEADER_HISTORY.Attribute8%TYPE,
                p_Attribute9                      IGC_CC_HEADER_HISTORY.Attribute9%TYPE,
                p_Attribute10                     IGC_CC_HEADER_HISTORY.Attribute10%TYPE,
                p_Attribute11                     IGC_CC_HEADER_HISTORY.Attribute11%TYPE,
                p_Attribute12                     IGC_CC_HEADER_HISTORY.Attribute12%TYPE,
                p_Attribute13                     IGC_CC_HEADER_HISTORY.Attribute13%TYPE,
                p_Attribute14                     IGC_CC_HEADER_HISTORY.Attribute14%TYPE,
                p_Attribute15                     IGC_CC_HEADER_HISTORY.Attribute15%TYPE,
                p_Context                         IGC_CC_HEADER_HISTORY.Context%TYPE,
                p_CC_Guarantee_Flag               IGC_CC_HEADER_HISTORY.CC_Guarantee_Flag%TYPE,
                G_FLAG                IN OUT NOCOPY      VARCHAR2
  );
/* ===============================================================================================
                             PROCEDURE Lock_Row
   ===============================================================================================*/
  PROCEDURE Lock_Row  (
                p_api_version               IN       NUMBER,
                p_init_msg_list             IN       VARCHAR2 := FND_API.G_FALSE,
                p_commit                    IN       VARCHAR2 := FND_API.G_FALSE,
                p_validation_level          IN       NUMBER   := FND_API.G_VALID_LEVEL_FULL,
                X_return_status             OUT NOCOPY      VARCHAR2,
                X_msg_count                 OUT NOCOPY      NUMBER,
                X_msg_data                  OUT NOCOPY      VARCHAR2,
                p_Rowid               IN OUT NOCOPY      VARCHAR2,
                p_CC_Header_Id                    IGC_CC_HEADER_HISTORY.CC_Header_Id%TYPE,
                p_Org_id                          IGC_CC_HEADER_HISTORY.Org_id%TYPE,
                p_CC_Type                         IGC_CC_HEADER_HISTORY.CC_Type%TYPE,
                p_CC_Num                          IGC_CC_HEADER_HISTORY.CC_Num%TYPE,
                p_CC_Version_num                  IGC_CC_HEADER_HISTORY.CC_Version_Num%TYPE,
                p_CC_Version_Action               IGC_CC_HEADER_HISTORY.CC_Version_Action%TYPE,
                p_CC_State                        IGC_CC_HEADER_HISTORY.CC_State%TYPE,
                p_Parent_Header_Id                IGC_CC_HEADER_HISTORY.Parent_Header_Id%TYPE,
                p_CC_ctrl_status                  IGC_CC_HEADER_HISTORY.CC_ctrl_status%TYPE,
                p_CC_Encmbrnc_Status              IGC_CC_HEADER_HISTORY.CC_Encmbrnc_Status%TYPE,
                p_CC_Apprvl_Status                IGC_CC_HEADER_HISTORY.CC_Apprvl_Status%TYPE,
                p_Vendor_Id                       IGC_CC_HEADER_HISTORY.Vendor_Id%TYPE,
                p_Vendor_Site_Id                  IGC_CC_HEADER_HISTORY.Vendor_Site_Id%TYPE,
                p_Vendor_Contact_Id               IGC_CC_HEADER_HISTORY.Vendor_Contact_Id%TYPE,
                p_Term_Id                         IGC_CC_HEADER_HISTORY.Term_Id%TYPE,
                p_Location_Id                     IGC_CC_HEADER_HISTORY.Location_Id%TYPE,
                p_Set_Of_Books_Id                 IGC_CC_HEADER_HISTORY.Set_Of_Books_Id%TYPE,
                p_CC_Acct_Date                    IGC_CC_HEADER_HISTORY.CC_Acct_Date%TYPE,
                p_CC_Desc                         IGC_CC_HEADER_HISTORY.CC_Desc%TYPE,
                p_CC_Start_Date                   IGC_CC_HEADER_HISTORY.CC_Start_Date%TYPE,
                p_CC_End_Date                     IGC_CC_HEADER_HISTORY.CC_End_Date%TYPE,
                p_CC_Owner_User_Id                IGC_CC_HEADER_HISTORY.CC_Owner_User_Id%TYPE,
                p_CC_Preparer_User_Id             IGC_CC_HEADER_HISTORY.CC_Preparer_User_Id%TYPE,
                p_Currency_Code                   IGC_CC_HEADER_HISTORY.Currency_Code%TYPE,
                p_Conversion_Type                 IGC_CC_HEADER_HISTORY.Conversion_Type%TYPE,
                p_Conversion_Date                 IGC_CC_HEADER_HISTORY.Conversion_Date%TYPE,
                p_Conversion_Rate                 IGC_CC_HEADER_HISTORY.Conversion_Rate%TYPE,
                p_Last_Update_Date                IGC_CC_HEADER_HISTORY.Last_Update_Date%TYPE,
                p_Last_Updated_By                 IGC_CC_HEADER_HISTORY.Last_Updated_By%TYPE,
                p_Last_Update_Login               IGC_CC_HEADER_HISTORY.Last_Update_Login%TYPE,
                p_Created_By                      IGC_CC_HEADER_HISTORY.Created_By%TYPE,
                p_Creation_Date                   IGC_CC_HEADER_HISTORY.Creation_Date%TYPE,
                p_Wf_Item_Type                    IGC_CC_HEADER_HISTORY.Wf_Item_Type%TYPE,
                p_Wf_Item_Key                     IGC_CC_HEADER_HISTORY.Wf_Item_Key%TYPE,
                p_CC_Current_User_Id              IGC_CC_HEADERS.CC_Current_User_Id%TYPE,
                p_Attribute1                      IGC_CC_HEADER_HISTORY.Attribute1%TYPE,
                p_Attribute2                      IGC_CC_HEADER_HISTORY.Attribute2%TYPE,
                p_Attribute3                      IGC_CC_HEADER_HISTORY.Attribute3%TYPE,
                p_Attribute4                      IGC_CC_HEADER_HISTORY.Attribute4%TYPE,
                p_Attribute5                      IGC_CC_HEADER_HISTORY.Attribute5%TYPE,
                p_Attribute6                      IGC_CC_HEADER_HISTORY.Attribute6%TYPE,
                p_Attribute7                      IGC_CC_HEADER_HISTORY.Attribute7%TYPE,
                p_Attribute8                      IGC_CC_HEADER_HISTORY.Attribute8%TYPE,
                p_Attribute9                      IGC_CC_HEADER_HISTORY.Attribute9%TYPE,
                p_Attribute10                     IGC_CC_HEADER_HISTORY.Attribute10%TYPE,
                p_Attribute11                     IGC_CC_HEADER_HISTORY.Attribute11%TYPE,
                p_Attribute12                     IGC_CC_HEADER_HISTORY.Attribute12%TYPE,
                p_Attribute13                     IGC_CC_HEADER_HISTORY.Attribute13%TYPE,
                p_Attribute14                     IGC_CC_HEADER_HISTORY.Attribute14%TYPE,
                p_Attribute15                     IGC_CC_HEADER_HISTORY.Attribute15%TYPE,
                p_Context                         IGC_CC_HEADER_HISTORY.Context%TYPE,
                p_CC_Guarantee_Flag               IGC_CC_HEADER_HISTORY.CC_Guarantee_Flag%TYPE,
                X_row_locked                OUT NOCOPY   VARCHAR2,
                G_FLAG                   IN OUT NOCOPY   VARCHAR2
  );

/* =================================================================================================
                           PROCEDURE Update_Row Overloaded Procedure for CC_REF_NUM addition
   ================================================================================================*/
  PROCEDURE Update_Row(
                p_api_version               IN       NUMBER,
                p_init_msg_list             IN       VARCHAR2 := FND_API.G_FALSE,
                p_commit                    IN       VARCHAR2 := FND_API.G_FALSE,
                p_validation_level          IN       NUMBER   := FND_API.G_VALID_LEVEL_FULL,
                X_return_status             OUT NOCOPY      VARCHAR2,
                X_msg_count                 OUT NOCOPY      NUMBER,
                X_msg_data                  OUT NOCOPY      VARCHAR2,
                p_Rowid               IN OUT NOCOPY      VARCHAR2,
                p_CC_Header_Id                    IGC_CC_HEADER_HISTORY.CC_Header_Id%TYPE,
                p_Org_id                          IGC_CC_HEADER_HISTORY.Org_id%TYPE,
                p_CC_Type                         IGC_CC_HEADER_HISTORY.CC_Type%TYPE,
                p_CC_Num                          IGC_CC_HEADER_HISTORY.CC_Num%TYPE,
                p_CC_Ref_Num                      IGC_CC_HEADER_HISTORY.CC_Ref_Num%TYPE,
                p_CC_Version_num                  IGC_CC_HEADER_HISTORY.CC_Version_Num%TYPE,
                p_CC_Version_Action               IGC_CC_HEADER_HISTORY.CC_Version_Action%TYPE,
                p_CC_State                        IGC_CC_HEADER_HISTORY.CC_State%TYPE,
                p_Parent_Header_Id                IGC_CC_HEADER_HISTORY.Parent_Header_Id%TYPE,
                p_CC_ctrl_status                  IGC_CC_HEADER_HISTORY.CC_ctrl_status%TYPE,
                p_CC_Encmbrnc_Status              IGC_CC_HEADER_HISTORY.CC_Encmbrnc_Status%TYPE,
                p_CC_Apprvl_Status                IGC_CC_HEADER_HISTORY.CC_Apprvl_Status%TYPE,
                p_Vendor_Id                       IGC_CC_HEADER_HISTORY.Vendor_Id%TYPE,
                p_Vendor_Site_Id                  IGC_CC_HEADER_HISTORY.Vendor_Site_Id%TYPE,
                p_Vendor_Contact_Id               IGC_CC_HEADER_HISTORY.Vendor_Contact_Id%TYPE,
                p_Term_Id                         IGC_CC_HEADER_HISTORY.Term_Id%TYPE,
                p_Location_Id                     IGC_CC_HEADER_HISTORY.Location_Id%TYPE,
                p_Set_Of_Books_Id                 IGC_CC_HEADER_HISTORY.Set_Of_Books_Id%TYPE,
                p_CC_Acct_Date                    IGC_CC_HEADER_HISTORY.CC_Acct_Date%TYPE,
                p_CC_Desc                         IGC_CC_HEADER_HISTORY.CC_Desc%TYPE,
                p_CC_Start_Date                   IGC_CC_HEADER_HISTORY.CC_Start_Date%TYPE,
                p_CC_End_Date                     IGC_CC_HEADER_HISTORY.CC_End_Date%TYPE,
                p_CC_Owner_User_Id                IGC_CC_HEADER_HISTORY.CC_Owner_User_Id%TYPE,
                p_CC_Preparer_User_Id             IGC_CC_HEADER_HISTORY.CC_Preparer_User_Id%TYPE,
                p_Currency_Code                   IGC_CC_HEADER_HISTORY.Currency_Code%TYPE,
                p_Conversion_Type                 IGC_CC_HEADER_HISTORY.Conversion_Type%TYPE,
                p_Conversion_Date                 IGC_CC_HEADER_HISTORY.Conversion_Date%TYPE,
                p_Conversion_Rate                 IGC_CC_HEADER_HISTORY.Conversion_Rate%TYPE,
                p_Last_Update_Date                IGC_CC_HEADER_HISTORY.Last_Update_Date%TYPE,
                p_Last_Updated_By                 IGC_CC_HEADER_HISTORY.Last_Updated_By%TYPE,
                p_Last_Update_Login               IGC_CC_HEADER_HISTORY.Last_Update_Login%TYPE,
                p_Created_By                      IGC_CC_HEADER_HISTORY.Created_By%TYPE,
                p_Creation_Date                   IGC_CC_HEADER_HISTORY.Creation_Date%TYPE,
                p_Wf_Item_Type                    IGC_CC_HEADER_HISTORY.Wf_Item_Type%TYPE,
                p_Wf_Item_Key                     IGC_CC_HEADER_HISTORY.Wf_Item_Key%TYPE,
                p_CC_Current_User_Id              IGC_CC_HEADERS.CC_Current_User_Id%TYPE,
                p_Attribute1                      IGC_CC_HEADER_HISTORY.Attribute1%TYPE,
                p_Attribute2                      IGC_CC_HEADER_HISTORY.Attribute2%TYPE,
                p_Attribute3                      IGC_CC_HEADER_HISTORY.Attribute3%TYPE,
                p_Attribute4                      IGC_CC_HEADER_HISTORY.Attribute4%TYPE,
                p_Attribute5                      IGC_CC_HEADER_HISTORY.Attribute5%TYPE,
                p_Attribute6                      IGC_CC_HEADER_HISTORY.Attribute6%TYPE,
                p_Attribute7                      IGC_CC_HEADER_HISTORY.Attribute7%TYPE,
                p_Attribute8                      IGC_CC_HEADER_HISTORY.Attribute8%TYPE,
                p_Attribute9                      IGC_CC_HEADER_HISTORY.Attribute9%TYPE,
                p_Attribute10                     IGC_CC_HEADER_HISTORY.Attribute10%TYPE,
                p_Attribute11                     IGC_CC_HEADER_HISTORY.Attribute11%TYPE,
                p_Attribute12                     IGC_CC_HEADER_HISTORY.Attribute12%TYPE,
                p_Attribute13                     IGC_CC_HEADER_HISTORY.Attribute13%TYPE,
                p_Attribute14                     IGC_CC_HEADER_HISTORY.Attribute14%TYPE,
                p_Attribute15                     IGC_CC_HEADER_HISTORY.Attribute15%TYPE,
                p_Context                         IGC_CC_HEADER_HISTORY.Context%TYPE,
                p_CC_Guarantee_Flag               IGC_CC_HEADER_HISTORY.CC_Guarantee_Flag%TYPE,
                G_FLAG                    IN OUT NOCOPY  VARCHAR2
      );

/* =================================================================================================
                           PROCEDURE Update_Row
   ================================================================================================*/
  PROCEDURE Update_Row(
                p_api_version               IN       NUMBER,
                p_init_msg_list             IN       VARCHAR2 := FND_API.G_FALSE,
                p_commit                    IN       VARCHAR2 := FND_API.G_FALSE,
                p_validation_level          IN       NUMBER   := FND_API.G_VALID_LEVEL_FULL,
                X_return_status             OUT NOCOPY      VARCHAR2,
                X_msg_count                 OUT NOCOPY      NUMBER,
                X_msg_data                  OUT NOCOPY      VARCHAR2,
                p_Rowid               IN OUT NOCOPY      VARCHAR2,
                p_CC_Header_Id                    IGC_CC_HEADER_HISTORY.CC_Header_Id%TYPE,
                p_Org_id                          IGC_CC_HEADER_HISTORY.Org_id%TYPE,
                p_CC_Type                         IGC_CC_HEADER_HISTORY.CC_Type%TYPE,
                p_CC_Num                          IGC_CC_HEADER_HISTORY.CC_Num%TYPE,
                p_CC_Version_num                  IGC_CC_HEADER_HISTORY.CC_Version_Num%TYPE,
                p_CC_Version_Action               IGC_CC_HEADER_HISTORY.CC_Version_Action%TYPE,
                p_CC_State                        IGC_CC_HEADER_HISTORY.CC_State%TYPE,
                p_Parent_Header_Id                IGC_CC_HEADER_HISTORY.Parent_Header_Id%TYPE,
                p_CC_ctrl_status                  IGC_CC_HEADER_HISTORY.CC_ctrl_status%TYPE,
                p_CC_Encmbrnc_Status              IGC_CC_HEADER_HISTORY.CC_Encmbrnc_Status%TYPE,
                p_CC_Apprvl_Status                IGC_CC_HEADER_HISTORY.CC_Apprvl_Status%TYPE,
                p_Vendor_Id                       IGC_CC_HEADER_HISTORY.Vendor_Id%TYPE,
                p_Vendor_Site_Id                  IGC_CC_HEADER_HISTORY.Vendor_Site_Id%TYPE,
                p_Vendor_Contact_Id               IGC_CC_HEADER_HISTORY.Vendor_Contact_Id%TYPE,
                p_Term_Id                         IGC_CC_HEADER_HISTORY.Term_Id%TYPE,
                p_Location_Id                     IGC_CC_HEADER_HISTORY.Location_Id%TYPE,
                p_Set_Of_Books_Id                 IGC_CC_HEADER_HISTORY.Set_Of_Books_Id%TYPE,
                p_CC_Acct_Date                    IGC_CC_HEADER_HISTORY.CC_Acct_Date%TYPE,
                p_CC_Desc                         IGC_CC_HEADER_HISTORY.CC_Desc%TYPE,
                p_CC_Start_Date                   IGC_CC_HEADER_HISTORY.CC_Start_Date%TYPE,
                p_CC_End_Date                     IGC_CC_HEADER_HISTORY.CC_End_Date%TYPE,
                p_CC_Owner_User_Id                IGC_CC_HEADER_HISTORY.CC_Owner_User_Id%TYPE,
                p_CC_Preparer_User_Id             IGC_CC_HEADER_HISTORY.CC_Preparer_User_Id%TYPE,
                p_Currency_Code                   IGC_CC_HEADER_HISTORY.Currency_Code%TYPE,
                p_Conversion_Type                 IGC_CC_HEADER_HISTORY.Conversion_Type%TYPE,
                p_Conversion_Date                 IGC_CC_HEADER_HISTORY.Conversion_Date%TYPE,
                p_Conversion_Rate                 IGC_CC_HEADER_HISTORY.Conversion_Rate%TYPE,
                p_Last_Update_Date                IGC_CC_HEADER_HISTORY.Last_Update_Date%TYPE,
                p_Last_Updated_By                 IGC_CC_HEADER_HISTORY.Last_Updated_By%TYPE,
                p_Last_Update_Login               IGC_CC_HEADER_HISTORY.Last_Update_Login%TYPE,
                p_Created_By                      IGC_CC_HEADER_HISTORY.Created_By%TYPE,
                p_Creation_Date                   IGC_CC_HEADER_HISTORY.Creation_Date%TYPE,
                p_Wf_Item_Type                    IGC_CC_HEADER_HISTORY.Wf_Item_Type%TYPE,
                p_Wf_Item_Key                     IGC_CC_HEADER_HISTORY.Wf_Item_Key%TYPE,
                p_CC_Current_User_Id              IGC_CC_HEADERS.CC_Current_User_Id%TYPE,
                p_Attribute1                      IGC_CC_HEADER_HISTORY.Attribute1%TYPE,
                p_Attribute2                      IGC_CC_HEADER_HISTORY.Attribute2%TYPE,
                p_Attribute3                      IGC_CC_HEADER_HISTORY.Attribute3%TYPE,
                p_Attribute4                      IGC_CC_HEADER_HISTORY.Attribute4%TYPE,
                p_Attribute5                      IGC_CC_HEADER_HISTORY.Attribute5%TYPE,
                p_Attribute6                      IGC_CC_HEADER_HISTORY.Attribute6%TYPE,
                p_Attribute7                      IGC_CC_HEADER_HISTORY.Attribute7%TYPE,
                p_Attribute8                      IGC_CC_HEADER_HISTORY.Attribute8%TYPE,
                p_Attribute9                      IGC_CC_HEADER_HISTORY.Attribute9%TYPE,
                p_Attribute10                     IGC_CC_HEADER_HISTORY.Attribute10%TYPE,
                p_Attribute11                     IGC_CC_HEADER_HISTORY.Attribute11%TYPE,
                p_Attribute12                     IGC_CC_HEADER_HISTORY.Attribute12%TYPE,
                p_Attribute13                     IGC_CC_HEADER_HISTORY.Attribute13%TYPE,
                p_Attribute14                     IGC_CC_HEADER_HISTORY.Attribute14%TYPE,
                p_Attribute15                     IGC_CC_HEADER_HISTORY.Attribute15%TYPE,
                p_Context                         IGC_CC_HEADER_HISTORY.Context%TYPE,
                p_CC_Guarantee_Flag               IGC_CC_HEADER_HISTORY.CC_Guarantee_Flag%TYPE,
                G_FLAG                    IN OUT NOCOPY  VARCHAR2
      );


/* ==============================================================================
                          PROCEDURE Delete_Row
   ============================================================================*/

PROCEDURE Delete_Row(
       p_api_version               IN       NUMBER,
       p_init_msg_list             IN       VARCHAR2 := FND_API.G_FALSE,
       p_commit                    IN       VARCHAR2 := FND_API.G_FALSE,
       p_validation_level          IN       NUMBER   := FND_API.G_VALID_LEVEL_FULL,
       X_return_status             OUT NOCOPY      VARCHAR2,
       X_msg_count                 OUT NOCOPY      NUMBER,
       X_msg_data                  OUT NOCOPY      VARCHAR2,
       p_Rowid                              VARCHAR2,
       G_FLAG                   IN OUT NOCOPY      VARCHAR2
      );

END IGC_CC_HEADER_HISTORY_PKG;

/
