--------------------------------------------------------
--  DDL for Package IGF_AP_ISIR_MATCHED_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGF_AP_ISIR_MATCHED_PKG" AUTHID CURRENT_USER AS
/* $Header: IGFAI09S.pls 120.0 2005/06/01 15:50:15 appldev noship $ */

  PROCEDURE insert_row (
    x_rowid                             IN OUT  NOCOPY VARCHAR2,
    x_isir_id                           IN OUT  NOCOPY NUMBER,
    x_base_id                           IN     NUMBER,
    x_batch_year                        IN     NUMBER,
    x_transaction_num                   IN     VARCHAR2,
    x_current_ssn                       IN     VARCHAR2,
    x_ssn_name_change                   IN     VARCHAR2,
    x_original_ssn                      IN     VARCHAR2,
    x_orig_name_id                      IN     VARCHAR2,
    x_last_name                         IN     VARCHAR2,
    x_first_name                        IN     VARCHAR2,
    x_middle_initial                    IN     VARCHAR2,
    x_perm_mail_add                     IN     VARCHAR2,
    x_perm_city                         IN     VARCHAR2,
    x_perm_state                        IN     VARCHAR2,
    x_perm_zip_code                     IN     VARCHAR2,
    x_date_of_birth                     IN     DATE,
    x_phone_number                      IN     VARCHAR2,
    x_driver_license_number             IN     VARCHAR2,
    x_driver_license_state              IN     VARCHAR2,
    x_citizenship_status                IN     VARCHAR2,
    x_alien_reg_number                  IN     VARCHAR2,
    x_s_marital_status                  IN     VARCHAR2,
    x_s_marital_status_date             IN     DATE,
    x_summ_enrl_status                  IN     VARCHAR2,
    x_fall_enrl_status                  IN     VARCHAR2,
    x_winter_enrl_status                IN     VARCHAR2,
    x_spring_enrl_status                IN     VARCHAR2,
    x_summ2_enrl_status                 IN     VARCHAR2,
    x_fathers_highest_edu_level         IN     VARCHAR2,
    x_mothers_highest_edu_level         IN     VARCHAR2,
    x_s_state_legal_residence           IN     VARCHAR2,
    x_legal_residence_before_date       IN     VARCHAR2,
    x_s_legal_resd_date                 IN     DATE,
    x_ss_r_u_male                       IN     VARCHAR2,
    x_selective_service_reg             IN     VARCHAR2,
    x_degree_certification              IN     VARCHAR2,
    x_grade_level_in_college            IN     VARCHAR2,
    x_high_school_diploma_ged           IN     VARCHAR2,
    x_first_bachelor_deg_by_date        IN     VARCHAR2,
    x_interest_in_loan                  IN     VARCHAR2,
    x_interest_in_stud_employment       IN     VARCHAR2,
    x_drug_offence_conviction           IN     VARCHAR2,
    x_s_tax_return_status               IN     VARCHAR2,
    x_s_type_tax_return                 IN     VARCHAR2,
    x_s_elig_1040ez                     IN     VARCHAR2,
    x_s_adjusted_gross_income           IN     NUMBER,
    x_s_fed_taxes_paid                  IN     NUMBER,
    x_s_exemptions                      IN     NUMBER,
    x_s_income_from_work                IN     NUMBER,
    x_spouse_income_from_work           IN     NUMBER,
    x_s_toa_amt_from_wsa                IN     NUMBER,
    x_s_toa_amt_from_wsb                IN     NUMBER,
    x_s_toa_amt_from_wsc                IN     NUMBER,
    x_s_investment_networth             IN     NUMBER,
    x_s_busi_farm_networth              IN     NUMBER,
    x_s_cash_savings                    IN     NUMBER,
    x_va_months                         IN     NUMBER,
    x_va_amount                         IN     NUMBER,
    x_stud_dob_before_date              IN     VARCHAR2,
    x_deg_beyond_bachelor               IN     VARCHAR2,
    x_s_married                         IN     VARCHAR2,
    x_s_have_children                   IN     VARCHAR2,
    x_legal_dependents                  IN     VARCHAR2,
    x_orphan_ward_of_court              IN     VARCHAR2,
    x_s_veteran                         IN     VARCHAR2,
    x_p_marital_status                  IN     VARCHAR2,
    x_father_ssn                        IN     VARCHAR2,
    x_f_last_name                       IN     VARCHAR2,
    x_mother_ssn                        IN     VARCHAR2,
    x_m_last_name                       IN     VARCHAR2,
    x_p_num_family_member               IN     NUMBER,
    x_p_num_in_college                  IN     NUMBER,
    x_p_state_legal_residence           IN     VARCHAR2,
    x_p_state_legal_res_before_dt       IN     VARCHAR2,
    x_p_legal_res_date                  IN     DATE,
    x_age_older_parent                  IN     NUMBER,
    x_p_tax_return_status               IN     VARCHAR2,
    x_p_type_tax_return                 IN     VARCHAR2,
    x_p_elig_1040aez                    IN     VARCHAR2,
    x_p_adjusted_gross_income           IN     NUMBER,
    x_p_taxes_paid                      IN     NUMBER,
    x_p_exemptions                      IN     NUMBER,
    x_f_income_work                     IN     NUMBER,
    x_m_income_work                     IN     NUMBER,
    x_p_income_wsa                      IN     NUMBER,
    x_p_income_wsb                      IN     NUMBER,
    x_p_income_wsc                      IN     NUMBER,
    x_p_investment_networth             IN     NUMBER,
    x_p_business_networth               IN     NUMBER,
    x_p_cash_saving                     IN     NUMBER,
    x_s_num_family_members              IN     NUMBER,
    x_s_num_in_college                  IN     NUMBER,
    x_first_college                     IN     VARCHAR2,
    x_first_house_plan                  IN     VARCHAR2,
    x_second_college                    IN     VARCHAR2,
    x_second_house_plan                 IN     VARCHAR2,
    x_third_college                     IN     VARCHAR2,
    x_third_house_plan                  IN     VARCHAR2,
    x_fourth_college                    IN     VARCHAR2,
    x_fourth_house_plan                 IN     VARCHAR2,
    x_fifth_college                     IN     VARCHAR2,
    x_fifth_house_plan                  IN     VARCHAR2,
    x_sixth_college                     IN     VARCHAR2,
    x_sixth_house_plan                  IN     VARCHAR2,
    x_date_app_completed                IN     DATE,
    x_signed_by                         IN     VARCHAR2,
    x_preparer_ssn                      IN     VARCHAR2,
    x_preparer_emp_id_number            IN     VARCHAR2,
    x_preparer_sign                     IN     VARCHAR2,
    x_transaction_receipt_date          IN     DATE,
    x_dependency_override_ind           IN     VARCHAR2,
    x_faa_fedral_schl_code              IN     VARCHAR2,
    x_faa_adjustment                    IN     VARCHAR2,
    x_input_record_type                 IN     VARCHAR2,
    x_serial_number                     IN     NUMBER,
    x_batch_number                      IN     VARCHAR2,
    x_early_analysis_flag               IN     VARCHAR2,
    x_app_entry_source_code             IN     VARCHAR2,
    x_eti_destination_code              IN     VARCHAR2,
    x_reject_override_b                 IN     VARCHAR2,
    x_reject_override_n                 IN     VARCHAR2,
    x_reject_override_w                 IN     VARCHAR2,
    x_assum_override_1                  IN     VARCHAR2,
    x_assum_override_2                  IN     VARCHAR2,
    x_assum_override_3                  IN     VARCHAR2,
    x_assum_override_4                  IN     VARCHAR2,
    x_assum_override_5                  IN     VARCHAR2,
    x_assum_override_6                  IN     VARCHAR2,
    x_dependency_status                 IN     VARCHAR2,
    x_s_email_address                   IN     VARCHAR2,
    x_nslds_reason_code                 IN     VARCHAR2,
    x_app_receipt_date                  IN     DATE,
    x_processed_rec_type                IN     VARCHAR2,
    x_hist_correction_for_tran_id       IN     NUMBER,
    x_system_generated_indicator        IN     VARCHAR2,
    x_dup_request_indicator             IN     VARCHAR2,
    x_source_of_correction              IN     VARCHAR2,
    x_p_cal_tax_status                  IN     VARCHAR2,
    x_s_cal_tax_status                  IN     VARCHAR2,
    x_graduate_flag                     IN     VARCHAR2,
    x_auto_zero_efc                     IN     VARCHAR2,
    x_efc_change_flag                   IN     VARCHAR2,
    x_sarc_flag                         IN     VARCHAR2,
    x_simplified_need_test              IN     VARCHAR2,
    x_reject_reason_codes               IN     VARCHAR2,
    x_select_service_match_flag         IN     VARCHAR2,
    x_select_service_reg_flag           IN     VARCHAR2,
    x_ins_match_flag                    IN     VARCHAR2,
    x_ins_verification_number           IN     NUMBER   DEFAULT NULL,
    x_sec_ins_match_flag                IN     VARCHAR2,
    x_sec_ins_ver_number                IN     NUMBER,
    x_ssn_match_flag                    IN     VARCHAR2,
    x_ssa_citizenship_flag              IN     VARCHAR2,
    x_ssn_date_of_death                 IN     DATE,
    x_nslds_match_flag                  IN     VARCHAR2,
    x_va_match_flag                     IN     VARCHAR2,
    x_prisoner_match                    IN     VARCHAR2,
    x_verification_flag                 IN     VARCHAR2,
    x_subsequent_app_flag               IN     VARCHAR2,
    x_app_source_site_code              IN     VARCHAR2,
    x_tran_source_site_code             IN     VARCHAR2,
    x_drn                               IN     NUMBER,
    x_tran_process_date                 IN     DATE,
    x_computer_batch_number             IN     NUMBER,
    x_correction_flags                  IN     VARCHAR2,
    x_highlight_flags                   IN     VARCHAR2,
    x_paid_efc                          IN     NUMBER,
    x_primary_efc                       IN     NUMBER,
    x_secondary_efc                     IN     NUMBER,
    x_fed_pell_grant_efc_type           IN     VARCHAR2,
    x_primary_efc_type                  IN     VARCHAR2,
    x_sec_efc_type                      IN     VARCHAR2,
    x_primary_alternate_month_1         IN     NUMBER,
    x_primary_alternate_month_2         IN     NUMBER,
    x_primary_alternate_month_3         IN     NUMBER,
    x_primary_alternate_month_4         IN     NUMBER,
    x_primary_alternate_month_5         IN     NUMBER,
    x_primary_alternate_month_6         IN     NUMBER,
    x_primary_alternate_month_7         IN     NUMBER,
    x_primary_alternate_month_8         IN     NUMBER,
    x_primary_alternate_month_10        IN     NUMBER,
    x_primary_alternate_month_11        IN     NUMBER,
    x_primary_alternate_month_12        IN     NUMBER,
    x_sec_alternate_month_1             IN     NUMBER,
    x_sec_alternate_month_2             IN     NUMBER,
    x_sec_alternate_month_3             IN     NUMBER,
    x_sec_alternate_month_4             IN     NUMBER,
    x_sec_alternate_month_5             IN     NUMBER,
    x_sec_alternate_month_6             IN     NUMBER,
    x_sec_alternate_month_7             IN     NUMBER,
    x_sec_alternate_month_8             IN     NUMBER,
    x_sec_alternate_month_10            IN     NUMBER,
    x_sec_alternate_month_11            IN     NUMBER,
    x_sec_alternate_month_12            IN     NUMBER,
    x_total_income                      IN     NUMBER,
    x_allow_total_income                IN     NUMBER,
    x_state_tax_allow                   IN     NUMBER,
    x_employment_allow                  IN     NUMBER,
    x_income_protection_allow           IN     NUMBER,
    x_available_income                  IN     NUMBER,
    x_contribution_from_ai              IN     NUMBER,
    x_discretionary_networth            IN     NUMBER,
    x_efc_networth                      IN     NUMBER,
    x_asset_protect_allow               IN     NUMBER,
    x_parents_cont_from_assets          IN     NUMBER,
    x_adjusted_available_income         IN     NUMBER,
    x_total_student_contribution        IN     NUMBER,
    x_total_parent_contribution         IN     NUMBER,
    x_parents_contribution              IN     NUMBER,
    x_student_total_income              IN     NUMBER,
    x_sati                              IN     NUMBER,
    x_sic                               IN     NUMBER,
    x_sdnw                              IN     NUMBER,
    x_sca                               IN     NUMBER,
    x_fti                               IN     NUMBER,
    x_secti                             IN     NUMBER,
    x_secati                            IN     NUMBER,
    x_secstx                            IN     NUMBER,
    x_secea                             IN     NUMBER,
    x_secipa                            IN     NUMBER,
    x_secai                             IN     NUMBER,
    x_seccai                            IN     NUMBER,
    x_secdnw                            IN     NUMBER,
    x_secnw                             IN     NUMBER,
    x_secapa                            IN     NUMBER,
    x_secpca                            IN     NUMBER,
    x_secaai                            IN     NUMBER,
    x_sectsc                            IN     NUMBER,
    x_sectpc                            IN     NUMBER,
    x_secpc                             IN     NUMBER,
    x_secsti                            IN     NUMBER,
    x_secsic                            IN     NUMBER,
    x_secsati                           IN     NUMBER,
    x_secsdnw                           IN     NUMBER,
    x_secsca                            IN     NUMBER,
    x_secfti                            IN     NUMBER,
    x_a_citizenship                     IN     VARCHAR2,
    x_a_student_marital_status          IN     VARCHAR2,
    x_a_student_agi                     IN     NUMBER,
    x_a_s_us_tax_paid                   IN     NUMBER,
    x_a_s_income_work                   IN     NUMBER,
    x_a_spouse_income_work              IN     NUMBER,
    x_a_s_total_wsc                     IN     NUMBER,
    x_a_date_of_birth                   IN     VARCHAR2,
    x_a_student_married                 IN     VARCHAR2,
    x_a_have_children                   IN     VARCHAR2,
    x_a_s_have_dependents               IN     VARCHAR2,
    x_a_va_status                       IN     VARCHAR2,
    x_a_s_num_in_family                 IN     NUMBER,
    x_a_s_num_in_college                IN     NUMBER,
    x_a_p_marital_status                IN     VARCHAR2,
    x_a_father_ssn                      IN     VARCHAR2,
    x_a_mother_ssn                      IN     VARCHAR2,
    x_a_parents_num_family              IN     NUMBER,
    x_a_parents_num_college             IN     NUMBER,
    x_a_parents_agi                     IN     NUMBER,
    x_a_p_us_tax_paid                   IN     NUMBER,
    x_a_f_work_income                   IN     NUMBER,
    x_a_m_work_income                   IN     NUMBER,
    x_a_p_total_wsc                     IN     NUMBER,
    x_comment_codes                     IN     VARCHAR2,
    x_sar_ack_comm_code                 IN     VARCHAR2,
    x_pell_grant_elig_flag              IN     VARCHAR2,
    x_reprocess_reason_code             IN     VARCHAR2,
    x_duplicate_date                    IN     DATE,
    x_isir_transaction_type             IN     VARCHAR2,
    x_fedral_schl_code_indicator        IN     VARCHAR2,
    x_multi_school_code_flags           IN     VARCHAR2,
    x_dup_ssn_indicator                 IN     VARCHAR2,
    x_payment_isir                      IN     VARCHAR2,
    x_receipt_status                    IN     VARCHAR2,
    x_isir_receipt_completed            IN     VARCHAR2,
    x_mode                              IN     VARCHAR2    DEFAULT 'R',
    x_system_record_type                IN     VARCHAR2    DEFAULT NULL,
    x_verif_track_flag                  IN     VARCHAR2    DEFAULT NULL,
    x_active_isir                       IN     VARCHAR2    DEFAULT NULL,
    x_fafsa_data_verify_flags           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_a                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_c                 IN     VARCHAR2    DEFAULT NULL,
    x_parent_marital_status_date        IN     DATE        DEFAULT NULL,
    x_legacy_record_flag                IN     VARCHAR2    DEFAULT NULL,
    x_father_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_father_step_father_birth_dt       IN     DATE        DEFAULT NULL,
    x_mother_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_mother_step_mother_birth_dt       IN     DATE        DEFAULT NULL,
    x_parents_email_address_txt         IN     VARCHAR2    DEFAULT NULL,
    x_address_change_type               IN     VARCHAR2    DEFAULT NULL,
    x_cps_pushed_isir_flag              IN     VARCHAR2    DEFAULT NULL,
    x_electronic_transaction_type       IN     VARCHAR2    DEFAULT NULL,
    x_sar_c_change_type                 IN     VARCHAR2    DEFAULT NULL,
    x_father_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_mother_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_g_flag            IN     VARCHAR2    DEFAULT NULL,
    x_dhs_verification_num_txt          IN     VARCHAR2    DEFAULT NULL,
    x_data_file_name_txt                IN     VARCHAR2    DEFAULT NULL,
    x_message_class_txt                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_3_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_12_flag           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_j_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_k_flag            IN     VARCHAR2    DEFAULT NULL,
    x_rejected_status_change_flag       IN     VARCHAR2    DEFAULT NULL,
    x_verification_selection_flag       IN     VARCHAR2    DEFAULT NULL
  );

  PROCEDURE lock_row (
    x_rowid                             IN     VARCHAR2,
    x_isir_id                           IN     NUMBER,
    x_base_id                           IN     NUMBER,
    x_batch_year                        IN     NUMBER,
    x_transaction_num                   IN     VARCHAR2,
    x_current_ssn                       IN     VARCHAR2,
    x_ssn_name_change                   IN     VARCHAR2,
    x_original_ssn                      IN     VARCHAR2,
    x_orig_name_id                      IN     VARCHAR2,
    x_last_name                         IN     VARCHAR2,
    x_first_name                        IN     VARCHAR2,
    x_middle_initial                    IN     VARCHAR2,
    x_perm_mail_add                     IN     VARCHAR2,
    x_perm_city                         IN     VARCHAR2,
    x_perm_state                        IN     VARCHAR2,
    x_perm_zip_code                     IN     VARCHAR2,
    x_date_of_birth                     IN     DATE,
    x_phone_number                      IN     VARCHAR2,
    x_driver_license_number             IN     VARCHAR2,
    x_driver_license_state              IN     VARCHAR2,
    x_citizenship_status                IN     VARCHAR2,
    x_alien_reg_number                  IN     VARCHAR2,
    x_s_marital_status                  IN     VARCHAR2,
    x_s_marital_status_date             IN     DATE,
    x_summ_enrl_status                  IN     VARCHAR2,
    x_fall_enrl_status                  IN     VARCHAR2,
    x_winter_enrl_status                IN     VARCHAR2,
    x_spring_enrl_status                IN     VARCHAR2,
    x_summ2_enrl_status                 IN     VARCHAR2,
    x_fathers_highest_edu_level         IN     VARCHAR2,
    x_mothers_highest_edu_level         IN     VARCHAR2,
    x_s_state_legal_residence           IN     VARCHAR2,
    x_legal_residence_before_date       IN     VARCHAR2,
    x_s_legal_resd_date                 IN     DATE,
    x_ss_r_u_male                       IN     VARCHAR2,
    x_selective_service_reg             IN     VARCHAR2,
    x_degree_certification              IN     VARCHAR2,
    x_grade_level_in_college            IN     VARCHAR2,
    x_high_school_diploma_ged           IN     VARCHAR2,
    x_first_bachelor_deg_by_date        IN     VARCHAR2,
    x_interest_in_loan                  IN     VARCHAR2,
    x_interest_in_stud_employment       IN     VARCHAR2,
    x_drug_offence_conviction           IN     VARCHAR2,
    x_s_tax_return_status               IN     VARCHAR2,
    x_s_type_tax_return                 IN     VARCHAR2,
    x_s_elig_1040ez                     IN     VARCHAR2,
    x_s_adjusted_gross_income           IN     NUMBER,
    x_s_fed_taxes_paid                  IN     NUMBER,
    x_s_exemptions                      IN     NUMBER,
    x_s_income_from_work                IN     NUMBER,
    x_spouse_income_from_work           IN     NUMBER,
    x_s_toa_amt_from_wsa                IN     NUMBER,
    x_s_toa_amt_from_wsb                IN     NUMBER,
    x_s_toa_amt_from_wsc                IN     NUMBER,
    x_s_investment_networth             IN     NUMBER,
    x_s_busi_farm_networth              IN     NUMBER,
    x_s_cash_savings                    IN     NUMBER,
    x_va_months                         IN     NUMBER,
    x_va_amount                         IN     NUMBER,
    x_stud_dob_before_date              IN     VARCHAR2,
    x_deg_beyond_bachelor               IN     VARCHAR2,
    x_s_married                         IN     VARCHAR2,
    x_s_have_children                   IN     VARCHAR2,
    x_legal_dependents                  IN     VARCHAR2,
    x_orphan_ward_of_court              IN     VARCHAR2,
    x_s_veteran                         IN     VARCHAR2,
    x_p_marital_status                  IN     VARCHAR2,
    x_father_ssn                        IN     VARCHAR2,
    x_f_last_name                       IN     VARCHAR2,
    x_mother_ssn                        IN     VARCHAR2,
    x_m_last_name                       IN     VARCHAR2,
    x_p_num_family_member               IN     NUMBER,
    x_p_num_in_college                  IN     NUMBER,
    x_p_state_legal_residence           IN     VARCHAR2,
    x_p_state_legal_res_before_dt       IN     VARCHAR2,
    x_p_legal_res_date                  IN     DATE,
    x_age_older_parent                  IN     NUMBER,
    x_p_tax_return_status               IN     VARCHAR2,
    x_p_type_tax_return                 IN     VARCHAR2,
    x_p_elig_1040aez                    IN     VARCHAR2,
    x_p_adjusted_gross_income           IN     NUMBER,
    x_p_taxes_paid                      IN     NUMBER,
    x_p_exemptions                      IN     NUMBER,
    x_f_income_work                     IN     NUMBER,
    x_m_income_work                     IN     NUMBER,
    x_p_income_wsa                      IN     NUMBER,
    x_p_income_wsb                      IN     NUMBER,
    x_p_income_wsc                      IN     NUMBER,
    x_p_investment_networth             IN     NUMBER,
    x_p_business_networth               IN     NUMBER,
    x_p_cash_saving                     IN     NUMBER,
    x_s_num_family_members              IN     NUMBER,
    x_s_num_in_college                  IN     NUMBER,
    x_first_college                     IN     VARCHAR2,
    x_first_house_plan                  IN     VARCHAR2,
    x_second_college                    IN     VARCHAR2,
    x_second_house_plan                 IN     VARCHAR2,
    x_third_college                     IN     VARCHAR2,
    x_third_house_plan                  IN     VARCHAR2,
    x_fourth_college                    IN     VARCHAR2,
    x_fourth_house_plan                 IN     VARCHAR2,
    x_fifth_college                     IN     VARCHAR2,
    x_fifth_house_plan                  IN     VARCHAR2,
    x_sixth_college                     IN     VARCHAR2,
    x_sixth_house_plan                  IN     VARCHAR2,
    x_date_app_completed                IN     DATE,
    x_signed_by                         IN     VARCHAR2,
    x_preparer_ssn                      IN     VARCHAR2,
    x_preparer_emp_id_number            IN     VARCHAR2,
    x_preparer_sign                     IN     VARCHAR2,
    x_transaction_receipt_date          IN     DATE,
    x_dependency_override_ind           IN     VARCHAR2,
    x_faa_fedral_schl_code              IN     VARCHAR2,
    x_faa_adjustment                    IN     VARCHAR2,
    x_input_record_type                 IN     VARCHAR2,
    x_serial_number                     IN     NUMBER,
    x_batch_number                      IN     VARCHAR2,
    x_early_analysis_flag               IN     VARCHAR2,
    x_app_entry_source_code             IN     VARCHAR2,
    x_eti_destination_code              IN     VARCHAR2,
    x_reject_override_b                 IN     VARCHAR2,
    x_reject_override_n                 IN     VARCHAR2,
    x_reject_override_w                 IN     VARCHAR2,
    x_assum_override_1                  IN     VARCHAR2,
    x_assum_override_2                  IN     VARCHAR2,
    x_assum_override_3                  IN     VARCHAR2,
    x_assum_override_4                  IN     VARCHAR2,
    x_assum_override_5                  IN     VARCHAR2,
    x_assum_override_6                  IN     VARCHAR2,
    x_dependency_status                 IN     VARCHAR2,
    x_s_email_address                   IN     VARCHAR2,
    x_nslds_reason_code                 IN     VARCHAR2,
    x_app_receipt_date                  IN     DATE,
    x_processed_rec_type                IN     VARCHAR2,
    x_hist_correction_for_tran_id       IN     NUMBER,
    x_system_generated_indicator        IN     VARCHAR2,
    x_dup_request_indicator             IN     VARCHAR2,
    x_source_of_correction              IN     VARCHAR2,
    x_p_cal_tax_status                  IN     VARCHAR2,
    x_s_cal_tax_status                  IN     VARCHAR2,
    x_graduate_flag                     IN     VARCHAR2,
    x_auto_zero_efc                     IN     VARCHAR2,
    x_efc_change_flag                   IN     VARCHAR2,
    x_sarc_flag                         IN     VARCHAR2,
    x_simplified_need_test              IN     VARCHAR2,
    x_reject_reason_codes               IN     VARCHAR2,
    x_select_service_match_flag         IN     VARCHAR2,
    x_select_service_reg_flag           IN     VARCHAR2,
    x_ins_match_flag                    IN     VARCHAR2,
    x_ins_verification_number           IN     NUMBER   DEFAULT NULL,
    x_sec_ins_match_flag                IN     VARCHAR2,
    x_sec_ins_ver_number                IN     NUMBER,
    x_ssn_match_flag                    IN     VARCHAR2,
    x_ssa_citizenship_flag              IN     VARCHAR2,
    x_ssn_date_of_death                 IN     DATE,
    x_nslds_match_flag                  IN     VARCHAR2,
    x_va_match_flag                     IN     VARCHAR2,
    x_prisoner_match                    IN     VARCHAR2,
    x_verification_flag                 IN     VARCHAR2,
    x_subsequent_app_flag               IN     VARCHAR2,
    x_app_source_site_code              IN     VARCHAR2,
    x_tran_source_site_code             IN     VARCHAR2,
    x_drn                               IN     NUMBER,
    x_tran_process_date                 IN     DATE,
    x_computer_batch_number             IN     NUMBER,
    x_correction_flags                  IN     VARCHAR2,
    x_highlight_flags                   IN     VARCHAR2,
    x_paid_efc                          IN     NUMBER,
    x_primary_efc                       IN     NUMBER,
    x_secondary_efc                     IN     NUMBER,
    x_fed_pell_grant_efc_type           IN     VARCHAR2,
    x_primary_efc_type                  IN     VARCHAR2,
    x_sec_efc_type                      IN     VARCHAR2,
    x_primary_alternate_month_1         IN     NUMBER,
    x_primary_alternate_month_2         IN     NUMBER,
    x_primary_alternate_month_3         IN     NUMBER,
    x_primary_alternate_month_4         IN     NUMBER,
    x_primary_alternate_month_5         IN     NUMBER,
    x_primary_alternate_month_6         IN     NUMBER,
    x_primary_alternate_month_7         IN     NUMBER,
    x_primary_alternate_month_8         IN     NUMBER,
    x_primary_alternate_month_10        IN     NUMBER,
    x_primary_alternate_month_11        IN     NUMBER,
    x_primary_alternate_month_12        IN     NUMBER,
    x_sec_alternate_month_1             IN     NUMBER,
    x_sec_alternate_month_2             IN     NUMBER,
    x_sec_alternate_month_3             IN     NUMBER,
    x_sec_alternate_month_4             IN     NUMBER,
    x_sec_alternate_month_5             IN     NUMBER,
    x_sec_alternate_month_6             IN     NUMBER,
    x_sec_alternate_month_7             IN     NUMBER,
    x_sec_alternate_month_8             IN     NUMBER,
    x_sec_alternate_month_10            IN     NUMBER,
    x_sec_alternate_month_11            IN     NUMBER,
    x_sec_alternate_month_12            IN     NUMBER,
    x_total_income                      IN     NUMBER,
    x_allow_total_income                IN     NUMBER,
    x_state_tax_allow                   IN     NUMBER,
    x_employment_allow                  IN     NUMBER,
    x_income_protection_allow           IN     NUMBER,
    x_available_income                  IN     NUMBER,
    x_contribution_from_ai              IN     NUMBER,
    x_discretionary_networth            IN     NUMBER,
    x_efc_networth                      IN     NUMBER,
    x_asset_protect_allow               IN     NUMBER,
    x_parents_cont_from_assets          IN     NUMBER,
    x_adjusted_available_income         IN     NUMBER,
    x_total_student_contribution        IN     NUMBER,
    x_total_parent_contribution         IN     NUMBER,
    x_parents_contribution              IN     NUMBER,
    x_student_total_income              IN     NUMBER,
    x_sati                              IN     NUMBER,
    x_sic                               IN     NUMBER,
    x_sdnw                              IN     NUMBER,
    x_sca                               IN     NUMBER,
    x_fti                               IN     NUMBER,
    x_secti                             IN     NUMBER,
    x_secati                            IN     NUMBER,
    x_secstx                            IN     NUMBER,
    x_secea                             IN     NUMBER,
    x_secipa                            IN     NUMBER,
    x_secai                             IN     NUMBER,
    x_seccai                            IN     NUMBER,
    x_secdnw                            IN     NUMBER,
    x_secnw                             IN     NUMBER,
    x_secapa                            IN     NUMBER,
    x_secpca                            IN     NUMBER,
    x_secaai                            IN     NUMBER,
    x_sectsc                            IN     NUMBER,
    x_sectpc                            IN     NUMBER,
    x_secpc                             IN     NUMBER,
    x_secsti                            IN     NUMBER,
    x_secsic                            IN     NUMBER,
    x_secsati                           IN     NUMBER,
    x_secsdnw                           IN     NUMBER,
    x_secsca                            IN     NUMBER,
    x_secfti                            IN     NUMBER,
    x_a_citizenship                     IN     VARCHAR2,
    x_a_student_marital_status          IN     VARCHAR2,
    x_a_student_agi                     IN     NUMBER,
    x_a_s_us_tax_paid                   IN     NUMBER,
    x_a_s_income_work                   IN     NUMBER,
    x_a_spouse_income_work              IN     NUMBER,
    x_a_s_total_wsc                     IN     NUMBER,
    x_a_date_of_birth                   IN     VARCHAR2,
    x_a_student_married                 IN     VARCHAR2,
    x_a_have_children                   IN     VARCHAR2,
    x_a_s_have_dependents               IN     VARCHAR2,
    x_a_va_status                       IN     VARCHAR2,
    x_a_s_num_in_family                 IN     NUMBER,
    x_a_s_num_in_college                IN     NUMBER,
    x_a_p_marital_status                IN     VARCHAR2,
    x_a_father_ssn                      IN     VARCHAR2,
    x_a_mother_ssn                      IN     VARCHAR2,
    x_a_parents_num_family              IN     NUMBER,
    x_a_parents_num_college             IN     NUMBER,
    x_a_parents_agi                     IN     NUMBER,
    x_a_p_us_tax_paid                   IN     NUMBER,
    x_a_f_work_income                   IN     NUMBER,
    x_a_m_work_income                   IN     NUMBER,
    x_a_p_total_wsc                     IN     NUMBER,
    x_comment_codes                     IN     VARCHAR2,
    x_sar_ack_comm_code                 IN     VARCHAR2,
    x_pell_grant_elig_flag              IN     VARCHAR2,
    x_reprocess_reason_code             IN     VARCHAR2,
    x_duplicate_date                    IN     DATE,
    x_isir_transaction_type             IN     VARCHAR2,
    x_fedral_schl_code_indicator        IN     VARCHAR2,
    x_multi_school_code_flags           IN     VARCHAR2,
    x_dup_ssn_indicator                 IN     VARCHAR2,
    x_payment_isir                      IN     VARCHAR2,
    x_receipt_status                    IN     VARCHAR2,
    x_isir_receipt_completed            IN     VARCHAR2,
    x_system_record_type                IN     VARCHAR2,
    x_verif_track_flag                  IN     VARCHAR2    DEFAULT NULL,
    x_active_isir                       IN     VARCHAR2    DEFAULT NULL,
    x_fafsa_data_verify_flags           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_a                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_c                 IN     VARCHAR2    DEFAULT NULL,
    x_parent_marital_status_date        IN     DATE        DEFAULT NULL,
    x_legacy_record_flag                IN     VARCHAR2    DEFAULT NULL,
    x_father_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_father_step_father_birth_dt       IN     DATE        DEFAULT NULL,
    x_mother_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_mother_step_mother_birth_dt       IN     DATE        DEFAULT NULL,
    x_parents_email_address_txt         IN     VARCHAR2    DEFAULT NULL,
    x_address_change_type               IN     VARCHAR2    DEFAULT NULL,
    x_cps_pushed_isir_flag              IN     VARCHAR2    DEFAULT NULL,
    x_electronic_transaction_type       IN     VARCHAR2    DEFAULT NULL,
    x_sar_c_change_type                 IN     VARCHAR2    DEFAULT NULL,
    x_father_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_mother_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_g_flag            IN     VARCHAR2    DEFAULT NULL,
    x_dhs_verification_num_txt          IN     VARCHAR2    DEFAULT NULL,
    x_data_file_name_txt                IN     VARCHAR2    DEFAULT NULL,
    x_message_class_txt                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_3_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_12_flag           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_j_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_k_flag            IN     VARCHAR2    DEFAULT NULL,
    x_rejected_status_change_flag       IN     VARCHAR2    DEFAULT NULL,
    x_verification_selection_flag       IN     VARCHAR2    DEFAULT NULL
  );

  PROCEDURE update_row (
    x_rowid                             IN     VARCHAR2,
    x_isir_id                           IN     NUMBER,
    x_base_id                           IN     NUMBER,
    x_batch_year                        IN     NUMBER,
    x_transaction_num                   IN     VARCHAR2,
    x_current_ssn                       IN     VARCHAR2,
    x_ssn_name_change                   IN     VARCHAR2,
    x_original_ssn                      IN     VARCHAR2,
    x_orig_name_id                      IN     VARCHAR2,
    x_last_name                         IN     VARCHAR2,
    x_first_name                        IN     VARCHAR2,
    x_middle_initial                    IN     VARCHAR2,
    x_perm_mail_add                     IN     VARCHAR2,
    x_perm_city                         IN     VARCHAR2,
    x_perm_state                        IN     VARCHAR2,
    x_perm_zip_code                     IN     VARCHAR2,
    x_date_of_birth                     IN     DATE,
    x_phone_number                      IN     VARCHAR2,
    x_driver_license_number             IN     VARCHAR2,
    x_driver_license_state              IN     VARCHAR2,
    x_citizenship_status                IN     VARCHAR2,
    x_alien_reg_number                  IN     VARCHAR2,
    x_s_marital_status                  IN     VARCHAR2,
    x_s_marital_status_date             IN     DATE,
    x_summ_enrl_status                  IN     VARCHAR2,
    x_fall_enrl_status                  IN     VARCHAR2,
    x_winter_enrl_status                IN     VARCHAR2,
    x_spring_enrl_status                IN     VARCHAR2,
    x_summ2_enrl_status                 IN     VARCHAR2,
    x_fathers_highest_edu_level         IN     VARCHAR2,
    x_mothers_highest_edu_level         IN     VARCHAR2,
    x_s_state_legal_residence           IN     VARCHAR2,
    x_legal_residence_before_date       IN     VARCHAR2,
    x_s_legal_resd_date                 IN     DATE,
    x_ss_r_u_male                       IN     VARCHAR2,
    x_selective_service_reg             IN     VARCHAR2,
    x_degree_certification              IN     VARCHAR2,
    x_grade_level_in_college            IN     VARCHAR2,
    x_high_school_diploma_ged           IN     VARCHAR2,
    x_first_bachelor_deg_by_date        IN     VARCHAR2,
    x_interest_in_loan                  IN     VARCHAR2,
    x_interest_in_stud_employment       IN     VARCHAR2,
    x_drug_offence_conviction           IN     VARCHAR2,
    x_s_tax_return_status               IN     VARCHAR2,
    x_s_type_tax_return                 IN     VARCHAR2,
    x_s_elig_1040ez                     IN     VARCHAR2,
    x_s_adjusted_gross_income           IN     NUMBER,
    x_s_fed_taxes_paid                  IN     NUMBER,
    x_s_exemptions                      IN     NUMBER,
    x_s_income_from_work                IN     NUMBER,
    x_spouse_income_from_work           IN     NUMBER,
    x_s_toa_amt_from_wsa                IN     NUMBER,
    x_s_toa_amt_from_wsb                IN     NUMBER,
    x_s_toa_amt_from_wsc                IN     NUMBER,
    x_s_investment_networth             IN     NUMBER,
    x_s_busi_farm_networth              IN     NUMBER,
    x_s_cash_savings                    IN     NUMBER,
    x_va_months                         IN     NUMBER,
    x_va_amount                         IN     NUMBER,
    x_stud_dob_before_date              IN     VARCHAR2,
    x_deg_beyond_bachelor               IN     VARCHAR2,
    x_s_married                         IN     VARCHAR2,
    x_s_have_children                   IN     VARCHAR2,
    x_legal_dependents                  IN     VARCHAR2,
    x_orphan_ward_of_court              IN     VARCHAR2,
    x_s_veteran                         IN     VARCHAR2,
    x_p_marital_status                  IN     VARCHAR2,
    x_father_ssn                        IN     VARCHAR2,
    x_f_last_name                       IN     VARCHAR2,
    x_mother_ssn                        IN     VARCHAR2,
    x_m_last_name                       IN     VARCHAR2,
    x_p_num_family_member               IN     NUMBER,
    x_p_num_in_college                  IN     NUMBER,
    x_p_state_legal_residence           IN     VARCHAR2,
    x_p_state_legal_res_before_dt       IN     VARCHAR2,
    x_p_legal_res_date                  IN     DATE,
    x_age_older_parent                  IN     NUMBER,
    x_p_tax_return_status               IN     VARCHAR2,
    x_p_type_tax_return                 IN     VARCHAR2,
    x_p_elig_1040aez                    IN     VARCHAR2,
    x_p_adjusted_gross_income           IN     NUMBER,
    x_p_taxes_paid                      IN     NUMBER,
    x_p_exemptions                      IN     NUMBER,
    x_f_income_work                     IN     NUMBER,
    x_m_income_work                     IN     NUMBER,
    x_p_income_wsa                      IN     NUMBER,
    x_p_income_wsb                      IN     NUMBER,
    x_p_income_wsc                      IN     NUMBER,
    x_p_investment_networth             IN     NUMBER,
    x_p_business_networth               IN     NUMBER,
    x_p_cash_saving                     IN     NUMBER,
    x_s_num_family_members              IN     NUMBER,
    x_s_num_in_college                  IN     NUMBER,
    x_first_college                     IN     VARCHAR2,
    x_first_house_plan                  IN     VARCHAR2,
    x_second_college                    IN     VARCHAR2,
    x_second_house_plan                 IN     VARCHAR2,
    x_third_college                     IN     VARCHAR2,
    x_third_house_plan                  IN     VARCHAR2,
    x_fourth_college                    IN     VARCHAR2,
    x_fourth_house_plan                 IN     VARCHAR2,
    x_fifth_college                     IN     VARCHAR2,
    x_fifth_house_plan                  IN     VARCHAR2,
    x_sixth_college                     IN     VARCHAR2,
    x_sixth_house_plan                  IN     VARCHAR2,
    x_date_app_completed                IN     DATE,
    x_signed_by                         IN     VARCHAR2,
    x_preparer_ssn                      IN     VARCHAR2,
    x_preparer_emp_id_number            IN     VARCHAR2,
    x_preparer_sign                     IN     VARCHAR2,
    x_transaction_receipt_date          IN     DATE,
    x_dependency_override_ind           IN     VARCHAR2,
    x_faa_fedral_schl_code              IN     VARCHAR2,
    x_faa_adjustment                    IN     VARCHAR2,
    x_input_record_type                 IN     VARCHAR2,
    x_serial_number                     IN     NUMBER,
    x_batch_number                      IN     VARCHAR2,
    x_early_analysis_flag               IN     VARCHAR2,
    x_app_entry_source_code             IN     VARCHAR2,
    x_eti_destination_code              IN     VARCHAR2,
    x_reject_override_b                 IN     VARCHAR2,
    x_reject_override_n                 IN     VARCHAR2,
    x_reject_override_w                 IN     VARCHAR2,
    x_assum_override_1                  IN     VARCHAR2,
    x_assum_override_2                  IN     VARCHAR2,
    x_assum_override_3                  IN     VARCHAR2,
    x_assum_override_4                  IN     VARCHAR2,
    x_assum_override_5                  IN     VARCHAR2,
    x_assum_override_6                  IN     VARCHAR2,
    x_dependency_status                 IN     VARCHAR2,
    x_s_email_address                   IN     VARCHAR2,
    x_nslds_reason_code                 IN     VARCHAR2,
    x_app_receipt_date                  IN     DATE,
    x_processed_rec_type                IN     VARCHAR2,
    x_hist_correction_for_tran_id       IN     NUMBER,
    x_system_generated_indicator        IN     VARCHAR2,
    x_dup_request_indicator             IN     VARCHAR2,
    x_source_of_correction              IN     VARCHAR2,
    x_p_cal_tax_status                  IN     VARCHAR2,
    x_s_cal_tax_status                  IN     VARCHAR2,
    x_graduate_flag                     IN     VARCHAR2,
    x_auto_zero_efc                     IN     VARCHAR2,
    x_efc_change_flag                   IN     VARCHAR2,
    x_sarc_flag                         IN     VARCHAR2,
    x_simplified_need_test              IN     VARCHAR2,
    x_reject_reason_codes               IN     VARCHAR2,
    x_select_service_match_flag         IN     VARCHAR2,
    x_select_service_reg_flag           IN     VARCHAR2,
    x_ins_match_flag                    IN     VARCHAR2,
    x_ins_verification_number           IN     NUMBER   DEFAULT NULL,
    x_sec_ins_match_flag                IN     VARCHAR2,
    x_sec_ins_ver_number                IN     NUMBER,
    x_ssn_match_flag                    IN     VARCHAR2,
    x_ssa_citizenship_flag              IN     VARCHAR2,
    x_ssn_date_of_death                 IN     DATE,
    x_nslds_match_flag                  IN     VARCHAR2,
    x_va_match_flag                     IN     VARCHAR2,
    x_prisoner_match                    IN     VARCHAR2,
    x_verification_flag                 IN     VARCHAR2,
    x_subsequent_app_flag               IN     VARCHAR2,
    x_app_source_site_code              IN     VARCHAR2,
    x_tran_source_site_code             IN     VARCHAR2,
    x_drn                               IN     NUMBER,
    x_tran_process_date                 IN     DATE,
    x_computer_batch_number             IN     NUMBER,
    x_correction_flags                  IN     VARCHAR2,
    x_highlight_flags                   IN     VARCHAR2,
    x_paid_efc                          IN     NUMBER,
    x_primary_efc                       IN     NUMBER,
    x_secondary_efc                     IN     NUMBER,
    x_fed_pell_grant_efc_type           IN     VARCHAR2,
    x_primary_efc_type                  IN     VARCHAR2,
    x_sec_efc_type                      IN     VARCHAR2,
    x_primary_alternate_month_1         IN     NUMBER,
    x_primary_alternate_month_2         IN     NUMBER,
    x_primary_alternate_month_3         IN     NUMBER,
    x_primary_alternate_month_4         IN     NUMBER,
    x_primary_alternate_month_5         IN     NUMBER,
    x_primary_alternate_month_6         IN     NUMBER,
    x_primary_alternate_month_7         IN     NUMBER,
    x_primary_alternate_month_8         IN     NUMBER,
    x_primary_alternate_month_10        IN     NUMBER,
    x_primary_alternate_month_11        IN     NUMBER,
    x_primary_alternate_month_12        IN     NUMBER,
    x_sec_alternate_month_1             IN     NUMBER,
    x_sec_alternate_month_2             IN     NUMBER,
    x_sec_alternate_month_3             IN     NUMBER,
    x_sec_alternate_month_4             IN     NUMBER,
    x_sec_alternate_month_5             IN     NUMBER,
    x_sec_alternate_month_6             IN     NUMBER,
    x_sec_alternate_month_7             IN     NUMBER,
    x_sec_alternate_month_8             IN     NUMBER,
    x_sec_alternate_month_10            IN     NUMBER,
    x_sec_alternate_month_11            IN     NUMBER,
    x_sec_alternate_month_12            IN     NUMBER,
    x_total_income                      IN     NUMBER,
    x_allow_total_income                IN     NUMBER,
    x_state_tax_allow                   IN     NUMBER,
    x_employment_allow                  IN     NUMBER,
    x_income_protection_allow           IN     NUMBER,
    x_available_income                  IN     NUMBER,
    x_contribution_from_ai              IN     NUMBER,
    x_discretionary_networth            IN     NUMBER,
    x_efc_networth                      IN     NUMBER,
    x_asset_protect_allow               IN     NUMBER,
    x_parents_cont_from_assets          IN     NUMBER,
    x_adjusted_available_income         IN     NUMBER,
    x_total_student_contribution        IN     NUMBER,
    x_total_parent_contribution         IN     NUMBER,
    x_parents_contribution              IN     NUMBER,
    x_student_total_income              IN     NUMBER,
    x_sati                              IN     NUMBER,
    x_sic                               IN     NUMBER,
    x_sdnw                              IN     NUMBER,
    x_sca                               IN     NUMBER,
    x_fti                               IN     NUMBER,
    x_secti                             IN     NUMBER,
    x_secati                            IN     NUMBER,
    x_secstx                            IN     NUMBER,
    x_secea                             IN     NUMBER,
    x_secipa                            IN     NUMBER,
    x_secai                             IN     NUMBER,
    x_seccai                            IN     NUMBER,
    x_secdnw                            IN     NUMBER,
    x_secnw                             IN     NUMBER,
    x_secapa                            IN     NUMBER,
    x_secpca                            IN     NUMBER,
    x_secaai                            IN     NUMBER,
    x_sectsc                            IN     NUMBER,
    x_sectpc                            IN     NUMBER,
    x_secpc                             IN     NUMBER,
    x_secsti                            IN     NUMBER,
    x_secsic                            IN     NUMBER,
    x_secsati                           IN     NUMBER,
    x_secsdnw                           IN     NUMBER,
    x_secsca                            IN     NUMBER,
    x_secfti                            IN     NUMBER,
    x_a_citizenship                     IN     VARCHAR2,
    x_a_student_marital_status          IN     VARCHAR2,
    x_a_student_agi                     IN     NUMBER,
    x_a_s_us_tax_paid                   IN     NUMBER,
    x_a_s_income_work                   IN     NUMBER,
    x_a_spouse_income_work              IN     NUMBER,
    x_a_s_total_wsc                     IN     NUMBER,
    x_a_date_of_birth                   IN     VARCHAR2,
    x_a_student_married                 IN     VARCHAR2,
    x_a_have_children                   IN     VARCHAR2,
    x_a_s_have_dependents               IN     VARCHAR2,
    x_a_va_status                       IN     VARCHAR2,
    x_a_s_num_in_family                 IN     NUMBER,
    x_a_s_num_in_college                IN     NUMBER,
    x_a_p_marital_status                IN     VARCHAR2,
    x_a_father_ssn                      IN     VARCHAR2,
    x_a_mother_ssn                      IN     VARCHAR2,
    x_a_parents_num_family              IN     NUMBER,
    x_a_parents_num_college             IN     NUMBER,
    x_a_parents_agi                     IN     NUMBER,
    x_a_p_us_tax_paid                   IN     NUMBER,
    x_a_f_work_income                   IN     NUMBER,
    x_a_m_work_income                   IN     NUMBER,
    x_a_p_total_wsc                     IN     NUMBER,
    x_comment_codes                     IN     VARCHAR2,
    x_sar_ack_comm_code                 IN     VARCHAR2,
    x_pell_grant_elig_flag              IN     VARCHAR2,
    x_reprocess_reason_code             IN     VARCHAR2,
    x_duplicate_date                    IN     DATE,
    x_isir_transaction_type             IN     VARCHAR2,
    x_fedral_schl_code_indicator        IN     VARCHAR2,
    x_multi_school_code_flags           IN     VARCHAR2,
    x_dup_ssn_indicator                 IN     VARCHAR2,
    x_payment_isir                      IN     VARCHAR2,
    x_receipt_status                    IN     VARCHAR2,
    x_isir_receipt_completed            IN     VARCHAR2,
    x_mode                              IN     VARCHAR2    DEFAULT 'R' ,
    x_system_record_type                IN     VARCHAR2    DEFAULT NULL,
    x_verif_track_flag                  IN     VARCHAR2    DEFAULT NULL,
    x_active_isir                       IN     VARCHAR2    DEFAULT NULL,
    x_fafsa_data_verify_flags           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_a                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_c                 IN     VARCHAR2    DEFAULT NULL,
    x_parent_marital_status_date        IN     DATE        DEFAULT NULL,
    x_legacy_record_flag                IN     VARCHAR2    DEFAULT NULL,
    x_father_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_father_step_father_birth_dt       IN     DATE        DEFAULT NULL,
    x_mother_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_mother_step_mother_birth_dt       IN     DATE        DEFAULT NULL,
    x_parents_email_address_txt         IN     VARCHAR2    DEFAULT NULL,
    x_address_change_type               IN     VARCHAR2    DEFAULT NULL,
    x_cps_pushed_isir_flag              IN     VARCHAR2    DEFAULT NULL,
    x_electronic_transaction_type       IN     VARCHAR2    DEFAULT NULL,
    x_sar_c_change_type                 IN     VARCHAR2    DEFAULT NULL,
    x_father_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_mother_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_g_flag            IN     VARCHAR2    DEFAULT NULL,
    x_dhs_verification_num_txt          IN     VARCHAR2    DEFAULT NULL,
    x_data_file_name_txt                IN     VARCHAR2    DEFAULT NULL,
    x_message_class_txt                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_3_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_12_flag           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_j_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_k_flag            IN     VARCHAR2    DEFAULT NULL,
    x_rejected_status_change_flag       IN     VARCHAR2    DEFAULT NULL,
    x_verification_selection_flag       IN     VARCHAR2    DEFAULT NULL
  );

  PROCEDURE add_row (
    x_rowid                             IN OUT  NOCOPY VARCHAR2,
    x_isir_id                           IN OUT  NOCOPY NUMBER,
    x_base_id                           IN     NUMBER,
    x_batch_year                        IN     NUMBER,
    x_transaction_num                   IN     VARCHAR2,
    x_current_ssn                       IN     VARCHAR2,
    x_ssn_name_change                   IN     VARCHAR2,
    x_original_ssn                      IN     VARCHAR2,
    x_orig_name_id                      IN     VARCHAR2,
    x_last_name                         IN     VARCHAR2,
    x_first_name                        IN     VARCHAR2,
    x_middle_initial                    IN     VARCHAR2,
    x_perm_mail_add                     IN     VARCHAR2,
    x_perm_city                         IN     VARCHAR2,
    x_perm_state                        IN     VARCHAR2,
    x_perm_zip_code                     IN     VARCHAR2,
    x_date_of_birth                     IN     DATE,
    x_phone_number                      IN     VARCHAR2,
    x_driver_license_number             IN     VARCHAR2,
    x_driver_license_state              IN     VARCHAR2,
    x_citizenship_status                IN     VARCHAR2,
    x_alien_reg_number                  IN     VARCHAR2,
    x_s_marital_status                  IN     VARCHAR2,
    x_s_marital_status_date             IN     DATE,
    x_summ_enrl_status                  IN     VARCHAR2,
    x_fall_enrl_status                  IN     VARCHAR2,
    x_winter_enrl_status                IN     VARCHAR2,
    x_spring_enrl_status                IN     VARCHAR2,
    x_summ2_enrl_status                 IN     VARCHAR2,
    x_fathers_highest_edu_level         IN     VARCHAR2,
    x_mothers_highest_edu_level         IN     VARCHAR2,
    x_s_state_legal_residence           IN     VARCHAR2,
    x_legal_residence_before_date       IN     VARCHAR2,
    x_s_legal_resd_date                 IN     DATE,
    x_ss_r_u_male                       IN     VARCHAR2,
    x_selective_service_reg             IN     VARCHAR2,
    x_degree_certification              IN     VARCHAR2,
    x_grade_level_in_college            IN     VARCHAR2,
    x_high_school_diploma_ged           IN     VARCHAR2,
    x_first_bachelor_deg_by_date        IN     VARCHAR2,
    x_interest_in_loan                  IN     VARCHAR2,
    x_interest_in_stud_employment       IN     VARCHAR2,
    x_drug_offence_conviction           IN     VARCHAR2,
    x_s_tax_return_status               IN     VARCHAR2,
    x_s_type_tax_return                 IN     VARCHAR2,
    x_s_elig_1040ez                     IN     VARCHAR2,
    x_s_adjusted_gross_income           IN     NUMBER,
    x_s_fed_taxes_paid                  IN     NUMBER,
    x_s_exemptions                      IN     NUMBER,
    x_s_income_from_work                IN     NUMBER,
    x_spouse_income_from_work           IN     NUMBER,
    x_s_toa_amt_from_wsa                IN     NUMBER,
    x_s_toa_amt_from_wsb                IN     NUMBER,
    x_s_toa_amt_from_wsc                IN     NUMBER,
    x_s_investment_networth             IN     NUMBER,
    x_s_busi_farm_networth              IN     NUMBER,
    x_s_cash_savings                    IN     NUMBER,
    x_va_months                         IN     NUMBER,
    x_va_amount                         IN     NUMBER,
    x_stud_dob_before_date              IN     VARCHAR2,
    x_deg_beyond_bachelor               IN     VARCHAR2,
    x_s_married                         IN     VARCHAR2,
    x_s_have_children                   IN     VARCHAR2,
    x_legal_dependents                  IN     VARCHAR2,
    x_orphan_ward_of_court              IN     VARCHAR2,
    x_s_veteran                         IN     VARCHAR2,
    x_p_marital_status                  IN     VARCHAR2,
    x_father_ssn                        IN     VARCHAR2,
    x_f_last_name                       IN     VARCHAR2,
    x_mother_ssn                        IN     VARCHAR2,
    x_m_last_name                       IN     VARCHAR2,
    x_p_num_family_member               IN     NUMBER,
    x_p_num_in_college                  IN     NUMBER,
    x_p_state_legal_residence           IN     VARCHAR2,
    x_p_state_legal_res_before_dt       IN     VARCHAR2,
    x_p_legal_res_date                  IN     DATE,
    x_age_older_parent                  IN     NUMBER,
    x_p_tax_return_status               IN     VARCHAR2,
    x_p_type_tax_return                 IN     VARCHAR2,
    x_p_elig_1040aez                    IN     VARCHAR2,
    x_p_adjusted_gross_income           IN     NUMBER,
    x_p_taxes_paid                      IN     NUMBER,
    x_p_exemptions                      IN     NUMBER,
    x_f_income_work                     IN     NUMBER,
    x_m_income_work                     IN     NUMBER,
    x_p_income_wsa                      IN     NUMBER,
    x_p_income_wsb                      IN     NUMBER,
    x_p_income_wsc                      IN     NUMBER,
    x_p_investment_networth             IN     NUMBER,
    x_p_business_networth               IN     NUMBER,
    x_p_cash_saving                     IN     NUMBER,
    x_s_num_family_members              IN     NUMBER,
    x_s_num_in_college                  IN     NUMBER,
    x_first_college                     IN     VARCHAR2,
    x_first_house_plan                  IN     VARCHAR2,
    x_second_college                    IN     VARCHAR2,
    x_second_house_plan                 IN     VARCHAR2,
    x_third_college                     IN     VARCHAR2,
    x_third_house_plan                  IN     VARCHAR2,
    x_fourth_college                    IN     VARCHAR2,
    x_fourth_house_plan                 IN     VARCHAR2,
    x_fifth_college                     IN     VARCHAR2,
    x_fifth_house_plan                  IN     VARCHAR2,
    x_sixth_college                     IN     VARCHAR2,
    x_sixth_house_plan                  IN     VARCHAR2,
    x_date_app_completed                IN     DATE,
    x_signed_by                         IN     VARCHAR2,
    x_preparer_ssn                      IN     VARCHAR2,
    x_preparer_emp_id_number            IN     VARCHAR2,
    x_preparer_sign                     IN     VARCHAR2,
    x_transaction_receipt_date          IN     DATE,
    x_dependency_override_ind           IN     VARCHAR2,
    x_faa_fedral_schl_code              IN     VARCHAR2,
    x_faa_adjustment                    IN     VARCHAR2,
    x_input_record_type                 IN     VARCHAR2,
    x_serial_number                     IN     NUMBER,
    x_batch_number                      IN     VARCHAR2,
    x_early_analysis_flag               IN     VARCHAR2,
    x_app_entry_source_code             IN     VARCHAR2,
    x_eti_destination_code              IN     VARCHAR2,
    x_reject_override_b                 IN     VARCHAR2,
    x_reject_override_n                 IN     VARCHAR2,
    x_reject_override_w                 IN     VARCHAR2,
    x_assum_override_1                  IN     VARCHAR2,
    x_assum_override_2                  IN     VARCHAR2,
    x_assum_override_3                  IN     VARCHAR2,
    x_assum_override_4                  IN     VARCHAR2,
    x_assum_override_5                  IN     VARCHAR2,
    x_assum_override_6                  IN     VARCHAR2,
    x_dependency_status                 IN     VARCHAR2,
    x_s_email_address                   IN     VARCHAR2,
    x_nslds_reason_code                 IN     VARCHAR2,
    x_app_receipt_date                  IN     DATE,
    x_processed_rec_type                IN     VARCHAR2,
    x_hist_correction_for_tran_id       IN     NUMBER,
    x_system_generated_indicator        IN     VARCHAR2,
    x_dup_request_indicator             IN     VARCHAR2,
    x_source_of_correction              IN     VARCHAR2,
    x_p_cal_tax_status                  IN     VARCHAR2,
    x_s_cal_tax_status                  IN     VARCHAR2,
    x_graduate_flag                     IN     VARCHAR2,
    x_auto_zero_efc                     IN     VARCHAR2,
    x_efc_change_flag                   IN     VARCHAR2,
    x_sarc_flag                         IN     VARCHAR2,
    x_simplified_need_test              IN     VARCHAR2,
    x_reject_reason_codes               IN     VARCHAR2,
    x_select_service_match_flag         IN     VARCHAR2,
    x_select_service_reg_flag           IN     VARCHAR2,
    x_ins_match_flag                    IN     VARCHAR2,
    x_ins_verification_number           IN     NUMBER   DEFAULT NULL,
    x_sec_ins_match_flag                IN     VARCHAR2,
    x_sec_ins_ver_number                IN     NUMBER,
    x_ssn_match_flag                    IN     VARCHAR2,
    x_ssa_citizenship_flag              IN     VARCHAR2,
    x_ssn_date_of_death                 IN     DATE,
    x_nslds_match_flag                  IN     VARCHAR2,
    x_va_match_flag                     IN     VARCHAR2,
    x_prisoner_match                    IN     VARCHAR2,
    x_verification_flag                 IN     VARCHAR2,
    x_subsequent_app_flag               IN     VARCHAR2,
    x_app_source_site_code              IN     VARCHAR2,
    x_tran_source_site_code             IN     VARCHAR2,
    x_drn                               IN     NUMBER,
    x_tran_process_date                 IN     DATE,
    x_computer_batch_number             IN     NUMBER,
    x_correction_flags                  IN     VARCHAR2,
    x_highlight_flags                   IN     VARCHAR2,
    x_paid_efc                          IN     NUMBER,
    x_primary_efc                       IN     NUMBER,
    x_secondary_efc                     IN     NUMBER,
    x_fed_pell_grant_efc_type           IN     VARCHAR2,
    x_primary_efc_type                  IN     VARCHAR2,
    x_sec_efc_type                      IN     VARCHAR2,
    x_primary_alternate_month_1         IN     NUMBER,
    x_primary_alternate_month_2         IN     NUMBER,
    x_primary_alternate_month_3         IN     NUMBER,
    x_primary_alternate_month_4         IN     NUMBER,
    x_primary_alternate_month_5         IN     NUMBER,
    x_primary_alternate_month_6         IN     NUMBER,
    x_primary_alternate_month_7         IN     NUMBER,
    x_primary_alternate_month_8         IN     NUMBER,
    x_primary_alternate_month_10        IN     NUMBER,
    x_primary_alternate_month_11        IN     NUMBER,
    x_primary_alternate_month_12        IN     NUMBER,
    x_sec_alternate_month_1             IN     NUMBER,
    x_sec_alternate_month_2             IN     NUMBER,
    x_sec_alternate_month_3             IN     NUMBER,
    x_sec_alternate_month_4             IN     NUMBER,
    x_sec_alternate_month_5             IN     NUMBER,
    x_sec_alternate_month_6             IN     NUMBER,
    x_sec_alternate_month_7             IN     NUMBER,
    x_sec_alternate_month_8             IN     NUMBER,
    x_sec_alternate_month_10            IN     NUMBER,
    x_sec_alternate_month_11            IN     NUMBER,
    x_sec_alternate_month_12            IN     NUMBER,
    x_total_income                      IN     NUMBER,
    x_allow_total_income                IN     NUMBER,
    x_state_tax_allow                   IN     NUMBER,
    x_employment_allow                  IN     NUMBER,
    x_income_protection_allow           IN     NUMBER,
    x_available_income                  IN     NUMBER,
    x_contribution_from_ai              IN     NUMBER,
    x_discretionary_networth            IN     NUMBER,
    x_efc_networth                      IN     NUMBER,
    x_asset_protect_allow               IN     NUMBER,
    x_parents_cont_from_assets          IN     NUMBER,
    x_adjusted_available_income         IN     NUMBER,
    x_total_student_contribution        IN     NUMBER,
    x_total_parent_contribution         IN     NUMBER,
    x_parents_contribution              IN     NUMBER,
    x_student_total_income              IN     NUMBER,
    x_sati                              IN     NUMBER,
    x_sic                               IN     NUMBER,
    x_sdnw                              IN     NUMBER,
    x_sca                               IN     NUMBER,
    x_fti                               IN     NUMBER,
    x_secti                             IN     NUMBER,
    x_secati                            IN     NUMBER,
    x_secstx                            IN     NUMBER,
    x_secea                             IN     NUMBER,
    x_secipa                            IN     NUMBER,
    x_secai                             IN     NUMBER,
    x_seccai                            IN     NUMBER,
    x_secdnw                            IN     NUMBER,
    x_secnw                             IN     NUMBER,
    x_secapa                            IN     NUMBER,
    x_secpca                            IN     NUMBER,
    x_secaai                            IN     NUMBER,
    x_sectsc                            IN     NUMBER,
    x_sectpc                            IN     NUMBER,
    x_secpc                             IN     NUMBER,
    x_secsti                            IN     NUMBER,
    x_secsic                            IN     NUMBER,
    x_secsati                           IN     NUMBER,
    x_secsdnw                           IN     NUMBER,
    x_secsca                            IN     NUMBER,
    x_secfti                            IN     NUMBER,
    x_a_citizenship                     IN     VARCHAR2,
    x_a_student_marital_status          IN     VARCHAR2,
    x_a_student_agi                     IN     NUMBER,
    x_a_s_us_tax_paid                   IN     NUMBER,
    x_a_s_income_work                   IN     NUMBER,
    x_a_spouse_income_work              IN     NUMBER,
    x_a_s_total_wsc                     IN     NUMBER,
    x_a_date_of_birth                   IN     VARCHAR2,
    x_a_student_married                 IN     VARCHAR2,
    x_a_have_children                   IN     VARCHAR2,
    x_a_s_have_dependents               IN     VARCHAR2,
    x_a_va_status                       IN     VARCHAR2,
    x_a_s_num_in_family                 IN     NUMBER,
    x_a_s_num_in_college                IN     NUMBER,
    x_a_p_marital_status                IN     VARCHAR2,
    x_a_father_ssn                      IN     VARCHAR2,
    x_a_mother_ssn                      IN     VARCHAR2,
    x_a_parents_num_family              IN     NUMBER,
    x_a_parents_num_college             IN     NUMBER,
    x_a_parents_agi                     IN     NUMBER,
    x_a_p_us_tax_paid                   IN     NUMBER,
    x_a_f_work_income                   IN     NUMBER,
    x_a_m_work_income                   IN     NUMBER,
    x_a_p_total_wsc                     IN     NUMBER,
    x_comment_codes                     IN     VARCHAR2,
    x_sar_ack_comm_code                 IN     VARCHAR2,
    x_pell_grant_elig_flag              IN     VARCHAR2,
    x_reprocess_reason_code             IN     VARCHAR2,
    x_duplicate_date                    IN     DATE,
    x_isir_transaction_type             IN     VARCHAR2,
    x_fedral_schl_code_indicator        IN     VARCHAR2,
    x_multi_school_code_flags           IN     VARCHAR2,
    x_dup_ssn_indicator                 IN     VARCHAR2,
    x_payment_isir                      IN     VARCHAR2,
    x_receipt_status                    IN     VARCHAR2,
    x_isir_receipt_completed            IN     VARCHAR2,
    x_mode                              IN     VARCHAR2    DEFAULT 'R',
    x_system_record_type                IN     VARCHAR2    DEFAULT NULL,
    x_verif_track_flag                  IN     VARCHAR2    DEFAULT NULL,
    x_active_isir                       IN     VARCHAR2    DEFAULT NULL,
    x_fafsa_data_verify_flags           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_a                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_c                 IN     VARCHAR2    DEFAULT NULL,
    x_parent_marital_status_date        IN     DATE        DEFAULT NULL,
    x_legacy_record_flag                IN     VARCHAR2    DEFAULT NULL,
    x_father_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_father_step_father_birth_dt       IN     DATE        DEFAULT NULL,
    x_mother_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_mother_step_mother_birth_dt       IN     DATE        DEFAULT NULL,
    x_parents_email_address_txt         IN     VARCHAR2    DEFAULT NULL,
    x_address_change_type               IN     VARCHAR2    DEFAULT NULL,
    x_cps_pushed_isir_flag              IN     VARCHAR2    DEFAULT NULL,
    x_electronic_transaction_type       IN     VARCHAR2    DEFAULT NULL,
    x_sar_c_change_type                 IN     VARCHAR2    DEFAULT NULL,
    x_father_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_mother_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_g_flag            IN     VARCHAR2    DEFAULT NULL,
    x_dhs_verification_num_txt          IN     VARCHAR2    DEFAULT NULL,
    x_data_file_name_txt                IN     VARCHAR2    DEFAULT NULL,
    x_message_class_txt                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_3_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_12_flag           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_j_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_k_flag            IN     VARCHAR2    DEFAULT NULL,
    x_rejected_status_change_flag       IN     VARCHAR2    DEFAULT NULL,
    x_verification_selection_flag       IN     VARCHAR2    DEFAULT NULL
  );

  PROCEDURE delete_row (
    x_rowid                             IN     VARCHAR2
  );

  FUNCTION get_pk_for_validation (
    x_isir_id                           IN     NUMBER
  ) RETURN BOOLEAN;

  PROCEDURE before_dml (
    p_action                            IN     VARCHAR2,
    x_rowid                             IN     VARCHAR2    DEFAULT NULL,
    x_isir_id                           IN     NUMBER      DEFAULT NULL,
    x_base_id                           IN     NUMBER      DEFAULT NULL,
    x_batch_year                        IN     NUMBER      DEFAULT NULL,
    x_transaction_num                   IN     VARCHAR2    DEFAULT NULL,
    x_current_ssn                       IN     VARCHAR2    DEFAULT NULL,
    x_ssn_name_change                   IN     VARCHAR2    DEFAULT NULL,
    x_original_ssn                      IN     VARCHAR2    DEFAULT NULL,
    x_orig_name_id                      IN     VARCHAR2    DEFAULT NULL,
    x_last_name                         IN     VARCHAR2    DEFAULT NULL,
    x_first_name                        IN     VARCHAR2    DEFAULT NULL,
    x_middle_initial                    IN     VARCHAR2    DEFAULT NULL,
    x_perm_mail_add                     IN     VARCHAR2    DEFAULT NULL,
    x_perm_city                         IN     VARCHAR2    DEFAULT NULL,
    x_perm_state                        IN     VARCHAR2    DEFAULT NULL,
    x_perm_zip_code                     IN     VARCHAR2    DEFAULT NULL,
    x_date_of_birth                     IN     DATE        DEFAULT NULL,
    x_phone_number                      IN     VARCHAR2    DEFAULT NULL,
    x_driver_license_number             IN     VARCHAR2    DEFAULT NULL,
    x_driver_license_state              IN     VARCHAR2    DEFAULT NULL,
    x_citizenship_status                IN     VARCHAR2    DEFAULT NULL,
    x_alien_reg_number                  IN     VARCHAR2    DEFAULT NULL,
    x_s_marital_status                  IN     VARCHAR2    DEFAULT NULL,
    x_s_marital_status_date             IN     DATE        DEFAULT NULL,
    x_summ_enrl_status                  IN     VARCHAR2    DEFAULT NULL,
    x_fall_enrl_status                  IN     VARCHAR2    DEFAULT NULL,
    x_winter_enrl_status                IN     VARCHAR2    DEFAULT NULL,
    x_spring_enrl_status                IN     VARCHAR2    DEFAULT NULL,
    x_summ2_enrl_status                 IN     VARCHAR2    DEFAULT NULL,
    x_fathers_highest_edu_level         IN     VARCHAR2    DEFAULT NULL,
    x_mothers_highest_edu_level         IN     VARCHAR2    DEFAULT NULL,
    x_s_state_legal_residence           IN     VARCHAR2    DEFAULT NULL,
    x_legal_residence_before_date       IN     VARCHAR2    DEFAULT NULL,
    x_s_legal_resd_date                 IN     DATE        DEFAULT NULL,
    x_ss_r_u_male                       IN     VARCHAR2    DEFAULT NULL,
    x_selective_service_reg             IN     VARCHAR2    DEFAULT NULL,
    x_degree_certification              IN     VARCHAR2    DEFAULT NULL,
    x_grade_level_in_college            IN     VARCHAR2    DEFAULT NULL,
    x_high_school_diploma_ged           IN     VARCHAR2    DEFAULT NULL,
    x_first_bachelor_deg_by_date        IN     VARCHAR2    DEFAULT NULL,
    x_interest_in_loan                  IN     VARCHAR2    DEFAULT NULL,
    x_interest_in_stud_employment       IN     VARCHAR2    DEFAULT NULL,
    x_drug_offence_conviction           IN     VARCHAR2    DEFAULT NULL,
    x_s_tax_return_status               IN     VARCHAR2    DEFAULT NULL,
    x_s_type_tax_return                 IN     VARCHAR2    DEFAULT NULL,
    x_s_elig_1040ez                     IN     VARCHAR2    DEFAULT NULL,
    x_s_adjusted_gross_income           IN     NUMBER      DEFAULT NULL,
    x_s_fed_taxes_paid                  IN     NUMBER      DEFAULT NULL,
    x_s_exemptions                      IN     NUMBER      DEFAULT NULL,
    x_s_income_from_work                IN     NUMBER      DEFAULT NULL,
    x_spouse_income_from_work           IN     NUMBER      DEFAULT NULL,
    x_s_toa_amt_from_wsa                IN     NUMBER      DEFAULT NULL,
    x_s_toa_amt_from_wsb                IN     NUMBER      DEFAULT NULL,
    x_s_toa_amt_from_wsc                IN     NUMBER      DEFAULT NULL,
    x_s_investment_networth             IN     NUMBER      DEFAULT NULL,
    x_s_busi_farm_networth              IN     NUMBER      DEFAULT NULL,
    x_s_cash_savings                    IN     NUMBER      DEFAULT NULL,
    x_va_months                         IN     NUMBER      DEFAULT NULL,
    x_va_amount                         IN     NUMBER      DEFAULT NULL,
    x_stud_dob_before_date              IN     VARCHAR2    DEFAULT NULL,
    x_deg_beyond_bachelor               IN     VARCHAR2    DEFAULT NULL,
    x_s_married                         IN     VARCHAR2    DEFAULT NULL,
    x_s_have_children                   IN     VARCHAR2    DEFAULT NULL,
    x_legal_dependents                  IN     VARCHAR2    DEFAULT NULL,
    x_orphan_ward_of_court              IN     VARCHAR2    DEFAULT NULL,
    x_s_veteran                         IN     VARCHAR2    DEFAULT NULL,
    x_p_marital_status                  IN     VARCHAR2    DEFAULT NULL,
    x_father_ssn                        IN     VARCHAR2    DEFAULT NULL,
    x_f_last_name                       IN     VARCHAR2    DEFAULT NULL,
    x_mother_ssn                        IN     VARCHAR2    DEFAULT NULL,
    x_m_last_name                       IN     VARCHAR2    DEFAULT NULL,
    x_p_num_family_member               IN     NUMBER      DEFAULT NULL,
    x_p_num_in_college                  IN     NUMBER      DEFAULT NULL,
    x_p_state_legal_residence           IN     VARCHAR2    DEFAULT NULL,
    x_p_state_legal_res_before_dt       IN     VARCHAR2    DEFAULT NULL,
    x_p_legal_res_date                  IN     DATE        DEFAULT NULL,
    x_age_older_parent                  IN     NUMBER      DEFAULT NULL,
    x_p_tax_return_status               IN     VARCHAR2    DEFAULT NULL,
    x_p_type_tax_return                 IN     VARCHAR2    DEFAULT NULL,
    x_p_elig_1040aez                    IN     VARCHAR2    DEFAULT NULL,
    x_p_adjusted_gross_income           IN     NUMBER      DEFAULT NULL,
    x_p_taxes_paid                      IN     NUMBER      DEFAULT NULL,
    x_p_exemptions                      IN     NUMBER      DEFAULT NULL,
    x_f_income_work                     IN     NUMBER      DEFAULT NULL,
    x_m_income_work                     IN     NUMBER      DEFAULT NULL,
    x_p_income_wsa                      IN     NUMBER      DEFAULT NULL,
    x_p_income_wsb                      IN     NUMBER      DEFAULT NULL,
    x_p_income_wsc                      IN     NUMBER      DEFAULT NULL,
    x_p_investment_networth             IN     NUMBER      DEFAULT NULL,
    x_p_business_networth               IN     NUMBER      DEFAULT NULL,
    x_p_cash_saving                     IN     NUMBER      DEFAULT NULL,
    x_s_num_family_members              IN     NUMBER      DEFAULT NULL,
    x_s_num_in_college                  IN     NUMBER      DEFAULT NULL,
    x_first_college                     IN     VARCHAR2    DEFAULT NULL,
    x_first_house_plan                  IN     VARCHAR2    DEFAULT NULL,
    x_second_college                    IN     VARCHAR2    DEFAULT NULL,
    x_second_house_plan                 IN     VARCHAR2    DEFAULT NULL,
    x_third_college                     IN     VARCHAR2    DEFAULT NULL,
    x_third_house_plan                  IN     VARCHAR2    DEFAULT NULL,
    x_fourth_college                    IN     VARCHAR2    DEFAULT NULL,
    x_fourth_house_plan                 IN     VARCHAR2    DEFAULT NULL,
    x_fifth_college                     IN     VARCHAR2    DEFAULT NULL,
    x_fifth_house_plan                  IN     VARCHAR2    DEFAULT NULL,
    x_sixth_college                     IN     VARCHAR2    DEFAULT NULL,
    x_sixth_house_plan                  IN     VARCHAR2    DEFAULT NULL,
    x_date_app_completed                IN     DATE        DEFAULT NULL,
    x_signed_by                         IN     VARCHAR2    DEFAULT NULL,
    x_preparer_ssn                      IN     VARCHAR2    DEFAULT NULL,
    x_preparer_emp_id_number            IN     VARCHAR2    DEFAULT NULL,
    x_preparer_sign                     IN     VARCHAR2    DEFAULT NULL,
    x_transaction_receipt_date          IN     DATE        DEFAULT NULL,
    x_dependency_override_ind           IN     VARCHAR2    DEFAULT NULL,
    x_faa_fedral_schl_code              IN     VARCHAR2    DEFAULT NULL,
    x_faa_adjustment                    IN     VARCHAR2    DEFAULT NULL,
    x_input_record_type                 IN     VARCHAR2    DEFAULT NULL,
    x_serial_number                     IN     NUMBER      DEFAULT NULL,
    x_batch_number                      IN     VARCHAR2    DEFAULT NULL,
    x_early_analysis_flag               IN     VARCHAR2    DEFAULT NULL,
    x_app_entry_source_code             IN     VARCHAR2    DEFAULT NULL,
    x_eti_destination_code              IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_b                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_n                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_w                 IN     VARCHAR2    DEFAULT NULL,
    x_assum_override_1                  IN     VARCHAR2    DEFAULT NULL,
    x_assum_override_2                  IN     VARCHAR2    DEFAULT NULL,
    x_assum_override_3                  IN     VARCHAR2    DEFAULT NULL,
    x_assum_override_4                  IN     VARCHAR2    DEFAULT NULL,
    x_assum_override_5                  IN     VARCHAR2    DEFAULT NULL,
    x_assum_override_6                  IN     VARCHAR2    DEFAULT NULL,
    x_dependency_status                 IN     VARCHAR2    DEFAULT NULL,
    x_s_email_address                   IN     VARCHAR2    DEFAULT NULL,
    x_nslds_reason_code                 IN     VARCHAR2    DEFAULT NULL,
    x_app_receipt_date                  IN     DATE        DEFAULT NULL,
    x_processed_rec_type                IN     VARCHAR2    DEFAULT NULL,
    x_hist_correction_for_tran_id       IN     NUMBER      DEFAULT NULL,
    x_system_generated_indicator        IN     VARCHAR2    DEFAULT NULL,
    x_dup_request_indicator             IN     VARCHAR2    DEFAULT NULL,
    x_source_of_correction              IN     VARCHAR2    DEFAULT NULL,
    x_p_cal_tax_status                  IN     VARCHAR2    DEFAULT NULL,
    x_s_cal_tax_status                  IN     VARCHAR2    DEFAULT NULL,
    x_graduate_flag                     IN     VARCHAR2    DEFAULT NULL,
    x_auto_zero_efc                     IN     VARCHAR2    DEFAULT NULL,
    x_efc_change_flag                   IN     VARCHAR2    DEFAULT NULL,
    x_sarc_flag                         IN     VARCHAR2    DEFAULT NULL,
    x_simplified_need_test              IN     VARCHAR2    DEFAULT NULL,
    x_reject_reason_codes               IN     VARCHAR2    DEFAULT NULL,
    x_select_service_match_flag         IN     VARCHAR2    DEFAULT NULL,
    x_select_service_reg_flag           IN     VARCHAR2    DEFAULT NULL,
    x_ins_match_flag                    IN     VARCHAR2    DEFAULT NULL,
    x_ins_verification_number           IN     NUMBER      DEFAULT NULL,
    x_sec_ins_match_flag                IN     VARCHAR2    DEFAULT NULL,
    x_sec_ins_ver_number                IN     NUMBER      DEFAULT NULL,
    x_ssn_match_flag                    IN     VARCHAR2    DEFAULT NULL,
    x_ssa_citizenship_flag              IN     VARCHAR2    DEFAULT NULL,
    x_ssn_date_of_death                 IN     DATE        DEFAULT NULL,
    x_nslds_match_flag                  IN     VARCHAR2    DEFAULT NULL,
    x_va_match_flag                     IN     VARCHAR2    DEFAULT NULL,
    x_prisoner_match                    IN     VARCHAR2    DEFAULT NULL,
    x_verification_flag                 IN     VARCHAR2    DEFAULT NULL,
    x_subsequent_app_flag               IN     VARCHAR2    DEFAULT NULL,
    x_app_source_site_code              IN     VARCHAR2    DEFAULT NULL,
    x_tran_source_site_code             IN     VARCHAR2    DEFAULT NULL,
    x_drn                               IN     NUMBER      DEFAULT NULL,
    x_tran_process_date                 IN     DATE        DEFAULT NULL,
    x_computer_batch_number             IN     NUMBER      DEFAULT NULL,
    x_correction_flags                  IN     VARCHAR2    DEFAULT NULL,
    x_highlight_flags                   IN     VARCHAR2    DEFAULT NULL,
    x_paid_efc                          IN     NUMBER      DEFAULT NULL,
    x_primary_efc                       IN     NUMBER      DEFAULT NULL,
    x_secondary_efc                     IN     NUMBER      DEFAULT NULL,
    x_fed_pell_grant_efc_type           IN     VARCHAR2    DEFAULT NULL,
    x_primary_efc_type                  IN     VARCHAR2    DEFAULT NULL,
    x_sec_efc_type                      IN     VARCHAR2    DEFAULT NULL,
    x_primary_alternate_month_1         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_2         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_3         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_4         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_5         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_6         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_7         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_8         IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_10        IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_11        IN     NUMBER      DEFAULT NULL,
    x_primary_alternate_month_12        IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_1             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_2             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_3             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_4             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_5             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_6             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_7             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_8             IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_10            IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_11            IN     NUMBER      DEFAULT NULL,
    x_sec_alternate_month_12            IN     NUMBER      DEFAULT NULL,
    x_total_income                      IN     NUMBER      DEFAULT NULL,
    x_allow_total_income                IN     NUMBER      DEFAULT NULL,
    x_state_tax_allow                   IN     NUMBER      DEFAULT NULL,
    x_employment_allow                  IN     NUMBER      DEFAULT NULL,
    x_income_protection_allow           IN     NUMBER      DEFAULT NULL,
    x_available_income                  IN     NUMBER      DEFAULT NULL,
    x_contribution_from_ai              IN     NUMBER      DEFAULT NULL,
    x_discretionary_networth            IN     NUMBER      DEFAULT NULL,
    x_efc_networth                      IN     NUMBER      DEFAULT NULL,
    x_asset_protect_allow               IN     NUMBER      DEFAULT NULL,
    x_parents_cont_from_assets          IN     NUMBER      DEFAULT NULL,
    x_adjusted_available_income         IN     NUMBER      DEFAULT NULL,
    x_total_student_contribution        IN     NUMBER      DEFAULT NULL,
    x_total_parent_contribution         IN     NUMBER      DEFAULT NULL,
    x_parents_contribution              IN     NUMBER      DEFAULT NULL,
    x_student_total_income              IN     NUMBER      DEFAULT NULL,
    x_sati                              IN     NUMBER      DEFAULT NULL,
    x_sic                               IN     NUMBER      DEFAULT NULL,
    x_sdnw                              IN     NUMBER      DEFAULT NULL,
    x_sca                               IN     NUMBER      DEFAULT NULL,
    x_fti                               IN     NUMBER      DEFAULT NULL,
    x_secti                             IN     NUMBER      DEFAULT NULL,
    x_secati                            IN     NUMBER      DEFAULT NULL,
    x_secstx                            IN     NUMBER      DEFAULT NULL,
    x_secea                             IN     NUMBER      DEFAULT NULL,
    x_secipa                            IN     NUMBER      DEFAULT NULL,
    x_secai                             IN     NUMBER      DEFAULT NULL,
    x_seccai                            IN     NUMBER      DEFAULT NULL,
    x_secdnw                            IN     NUMBER      DEFAULT NULL,
    x_secnw                             IN     NUMBER      DEFAULT NULL,
    x_secapa                            IN     NUMBER      DEFAULT NULL,
    x_secpca                            IN     NUMBER      DEFAULT NULL,
    x_secaai                            IN     NUMBER      DEFAULT NULL,
    x_sectsc                            IN     NUMBER      DEFAULT NULL,
    x_sectpc                            IN     NUMBER      DEFAULT NULL,
    x_secpc                             IN     NUMBER      DEFAULT NULL,
    x_secsti                            IN     NUMBER      DEFAULT NULL,
    x_secsic                            IN     NUMBER      DEFAULT NULL,
    x_secsati                           IN     NUMBER      DEFAULT NULL,
    x_secsdnw                           IN     NUMBER      DEFAULT NULL,
    x_secsca                            IN     NUMBER      DEFAULT NULL,
    x_secfti                            IN     NUMBER      DEFAULT NULL,
    x_a_citizenship                     IN     VARCHAR2    DEFAULT NULL,
    x_a_student_marital_status          IN     VARCHAR2    DEFAULT NULL,
    x_a_student_agi                     IN     NUMBER      DEFAULT NULL,
    x_a_s_us_tax_paid                   IN     NUMBER      DEFAULT NULL,
    x_a_s_income_work                   IN     NUMBER      DEFAULT NULL,
    x_a_spouse_income_work              IN     NUMBER      DEFAULT NULL,
    x_a_s_total_wsc                     IN     NUMBER      DEFAULT NULL,
    x_a_date_of_birth                   IN     VARCHAR2    DEFAULT NULL,
    x_a_student_married                 IN     VARCHAR2    DEFAULT NULL,
    x_a_have_children                   IN     VARCHAR2    DEFAULT NULL,
    x_a_s_have_dependents               IN     VARCHAR2    DEFAULT NULL,
    x_a_va_status                       IN     VARCHAR2    DEFAULT NULL,
    x_a_s_num_in_family                 IN     NUMBER      DEFAULT NULL,
    x_a_s_num_in_college                IN     NUMBER      DEFAULT NULL,
    x_a_p_marital_status                IN     VARCHAR2    DEFAULT NULL,
    x_a_father_ssn                      IN     VARCHAR2    DEFAULT NULL,
    x_a_mother_ssn                      IN     VARCHAR2    DEFAULT NULL,
    x_a_parents_num_family              IN     NUMBER      DEFAULT NULL,
    x_a_parents_num_college             IN     NUMBER      DEFAULT NULL,
    x_a_parents_agi                     IN     NUMBER      DEFAULT NULL,
    x_a_p_us_tax_paid                   IN     NUMBER      DEFAULT NULL,
    x_a_f_work_income                   IN     NUMBER      DEFAULT NULL,
    x_a_m_work_income                   IN     NUMBER      DEFAULT NULL,
    x_a_p_total_wsc                     IN     NUMBER      DEFAULT NULL,
    x_comment_codes                     IN     VARCHAR2    DEFAULT NULL,
    x_sar_ack_comm_code                 IN     VARCHAR2    DEFAULT NULL,
    x_pell_grant_elig_flag              IN     VARCHAR2    DEFAULT NULL,
    x_reprocess_reason_code             IN     VARCHAR2    DEFAULT NULL,
    x_duplicate_date                    IN     DATE        DEFAULT NULL,
    x_isir_transaction_type             IN     VARCHAR2    DEFAULT NULL,
    x_fedral_schl_code_indicator        IN     VARCHAR2    DEFAULT NULL,
    x_multi_school_code_flags           IN     VARCHAR2    DEFAULT NULL,
    x_dup_ssn_indicator                 IN     VARCHAR2    DEFAULT NULL,
    x_payment_isir                      IN     VARCHAR2    DEFAULT NULL,
    x_receipt_status                    IN     VARCHAR2    DEFAULT NULL,
    x_isir_receipt_completed            IN     VARCHAR2    DEFAULT NULL,
    x_creation_date                     IN     DATE        DEFAULT NULL,
    x_created_by                        IN     NUMBER      DEFAULT NULL,
    x_last_update_date                  IN     DATE        DEFAULT NULL,
    x_last_updated_by                   IN     NUMBER      DEFAULT NULL,
    x_last_update_login                 IN     NUMBER      DEFAULT NULL,
    x_system_record_type                IN     VARCHAR2    DEFAULT NULL,
    x_verif_track_flag                  IN     VARCHAR2    DEFAULT NULL,
    x_active_isir                       IN     VARCHAR2    DEFAULT NULL,
    x_fafsa_data_verify_flags           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_a                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_c                 IN     VARCHAR2    DEFAULT NULL,
    x_parent_marital_status_date        IN     DATE        DEFAULT NULL,
    x_legacy_record_flag                IN     VARCHAR2    DEFAULT NULL,
    x_father_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_father_step_father_birth_dt       IN     DATE        DEFAULT NULL,
    x_mother_first_name_initial         IN     VARCHAR2    DEFAULT NULL,
    x_mother_step_mother_birth_dt       IN     DATE        DEFAULT NULL,
    x_parents_email_address_txt         IN     VARCHAR2    DEFAULT NULL,
    x_address_change_type               IN     VARCHAR2    DEFAULT NULL,
    x_cps_pushed_isir_flag              IN     VARCHAR2    DEFAULT NULL,
    x_electronic_transaction_type       IN     VARCHAR2    DEFAULT NULL,
    x_sar_c_change_type                 IN     VARCHAR2    DEFAULT NULL,
    x_father_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_mother_ssn_match_type             IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_g_flag            IN     VARCHAR2    DEFAULT NULL,
    x_dhs_verification_num_txt          IN     VARCHAR2    DEFAULT NULL,
    x_data_file_name_txt                IN     VARCHAR2    DEFAULT NULL,
    x_message_class_txt                 IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_3_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_12_flag           IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_j_flag            IN     VARCHAR2    DEFAULT NULL,
    x_reject_override_k_flag            IN     VARCHAR2    DEFAULT NULL,
    x_rejected_status_change_flag       IN     VARCHAR2    DEFAULT NULL,
    x_verification_selection_flag       IN     VARCHAR2    DEFAULT NULL
  );

  PROCEDURE update_row_rectype (
           p_isir_matched_rectype  IN igf_ap_isir_matched%ROWTYPE
  );

END igf_ap_isir_matched_pkg;

 

/
