--------------------------------------------------------
--  DDL for Package IGF_SL_ALT_BORW_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGF_SL_ALT_BORW_PKG" AUTHID CURRENT_USER AS
/* $Header: IGFLI32S.pls 120.1 2005/06/08 00:47:43 appldev  $ */

  PROCEDURE insert_row (
    x_rowid                             IN OUT NOCOPY VARCHAR2,
    x_albw_id                           IN OUT NOCOPY NUMBER,
    x_loan_id                           IN     NUMBER,
    x_fed_stafford_loan_debt            IN     NUMBER,
    x_fed_sls_debt                      IN     NUMBER,
    x_heal_debt                         IN     NUMBER,
    x_perkins_debt                      IN     NUMBER,
    x_other_debt                        IN     NUMBER,
    x_crdt_undr_difft_name              IN     VARCHAR2,
    x_borw_gross_annual_sal             IN     NUMBER,
    x_borw_other_income                 IN     NUMBER,
    x_student_major                     IN     VARCHAR2,
    x_int_rate_opt                      IN     VARCHAR2,
    x_repayment_opt_code                IN     VARCHAR2,
    x_stud_mth_housing_pymt             IN     NUMBER,
    x_stud_mth_crdtcard_pymt            IN     NUMBER,
    x_stud_mth_auto_pymt                IN     NUMBER,
    x_stud_mth_ed_loan_pymt             IN     NUMBER,
    x_stud_mth_other_pymt               IN     NUMBER,
    x_mode                              IN     VARCHAR2    DEFAULT 'R' ,
    x_other_loan_amt                    IN     NUMBER DEFAULT NULL,
    x_cs1_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs1_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs1_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs1_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_years_at_address_txt          IN     NUMBER   DEFAULT   NULL,
    x_cs2_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs2_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs2_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs2_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_years_at_address_txt          IN     NUMBER   DEFAULT   NULL
  );

  PROCEDURE lock_row (
    x_rowid                             IN     VARCHAR2,
    x_albw_id                           IN     NUMBER,
    x_loan_id                           IN     NUMBER,
    x_fed_stafford_loan_debt            IN     NUMBER,
    x_fed_sls_debt                      IN     NUMBER,
    x_heal_debt                         IN     NUMBER,
    x_perkins_debt                      IN     NUMBER,
    x_other_debt                        IN     NUMBER,
    x_crdt_undr_difft_name              IN     VARCHAR2,
    x_borw_gross_annual_sal             IN     NUMBER,
    x_borw_other_income                 IN     NUMBER,
    x_student_major                     IN     VARCHAR2,
    x_int_rate_opt                      IN     VARCHAR2,
    x_repayment_opt_code                IN     VARCHAR2,
    x_stud_mth_housing_pymt             IN     NUMBER,
    x_stud_mth_crdtcard_pymt            IN     NUMBER,
    x_stud_mth_auto_pymt                IN     NUMBER,
    x_stud_mth_ed_loan_pymt             IN     NUMBER,
    x_stud_mth_other_pymt               IN     NUMBER,
    x_other_loan_amt                    IN     NUMBER DEFAULT NULL,
    x_cs1_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs1_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs1_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs1_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_years_at_address_txt          IN     NUMBER   DEFAULT   NULL,
    x_cs2_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs2_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs2_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs2_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_years_at_address_txt          IN     NUMBER   DEFAULT   NULL
  );

  PROCEDURE update_row (
    x_rowid                             IN     VARCHAR2,
    x_albw_id                           IN     NUMBER,
    x_loan_id                           IN     NUMBER,
    x_fed_stafford_loan_debt            IN     NUMBER,
    x_fed_sls_debt                      IN     NUMBER,
    x_heal_debt                         IN     NUMBER,
    x_perkins_debt                      IN     NUMBER,
    x_other_debt                        IN     NUMBER,
    x_crdt_undr_difft_name              IN     VARCHAR2,
    x_borw_gross_annual_sal             IN     NUMBER,
    x_borw_other_income                 IN     NUMBER,
    x_student_major                     IN     VARCHAR2,
    x_int_rate_opt                      IN     VARCHAR2,
    x_repayment_opt_code                IN     VARCHAR2,
    x_stud_mth_housing_pymt             IN     NUMBER,
    x_stud_mth_crdtcard_pymt            IN     NUMBER,
    x_stud_mth_auto_pymt                IN     NUMBER,
    x_stud_mth_ed_loan_pymt             IN     NUMBER,
    x_stud_mth_other_pymt               IN     NUMBER,
    x_mode                              IN     VARCHAR2    DEFAULT 'R',
    x_other_loan_amt                    IN     NUMBER DEFAULT NULL,
    x_cs1_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs1_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs1_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs1_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_years_at_address_txt          IN     NUMBER   DEFAULT   NULL,
    x_cs2_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs2_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs2_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs2_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_years_at_address_txt          IN     NUMBER   DEFAULT   NULL
  );

  PROCEDURE add_row (
    x_rowid                             IN OUT NOCOPY VARCHAR2,
    x_albw_id                           IN OUT NOCOPY NUMBER,
    x_loan_id                           IN     NUMBER,
    x_fed_stafford_loan_debt            IN     NUMBER,
    x_fed_sls_debt                      IN     NUMBER,
    x_heal_debt                         IN     NUMBER,
    x_perkins_debt                      IN     NUMBER,
    x_other_debt                        IN     NUMBER,
    x_crdt_undr_difft_name              IN     VARCHAR2,
    x_borw_gross_annual_sal             IN     NUMBER,
    x_borw_other_income                 IN     NUMBER,
    x_student_major                     IN     VARCHAR2,
    x_int_rate_opt                      IN     VARCHAR2,
    x_repayment_opt_code                IN     VARCHAR2,
    x_stud_mth_housing_pymt             IN     NUMBER,
    x_stud_mth_crdtcard_pymt            IN     NUMBER,
    x_stud_mth_auto_pymt                IN     NUMBER,
    x_stud_mth_ed_loan_pymt             IN     NUMBER,
    x_stud_mth_other_pymt               IN     NUMBER,
    x_mode                              IN     VARCHAR2    DEFAULT 'R',
    x_other_loan_amt                    IN     NUMBER DEFAULT NULL,
    x_cs1_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs1_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs1_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs1_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_years_at_address_txt          IN     NUMBER   DEFAULT   NULL,
    x_cs2_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs2_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs2_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs2_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_years_at_address_txt          IN     NUMBER   DEFAULT   NULL
  );

  PROCEDURE delete_row (
    x_rowid                             IN     VARCHAR2
  );

  FUNCTION get_pk_for_validation (
    x_albw_id                           IN     NUMBER
  ) RETURN BOOLEAN;

  PROCEDURE get_fk_igf_sl_loans (
    x_loan_id                           IN     NUMBER
  );

  PROCEDURE before_dml (
    p_action                            IN     VARCHAR2,
    x_rowid                             IN     VARCHAR2    DEFAULT NULL,
    x_albw_id                           IN     NUMBER      DEFAULT NULL,
    x_loan_id                           IN     NUMBER      DEFAULT NULL,
    x_fed_stafford_loan_debt            IN     NUMBER      DEFAULT NULL,
    x_fed_sls_debt                      IN     NUMBER      DEFAULT NULL,
    x_heal_debt                         IN     NUMBER      DEFAULT NULL,
    x_perkins_debt                      IN     NUMBER      DEFAULT NULL,
    x_other_debt                        IN     NUMBER      DEFAULT NULL,
    x_crdt_undr_difft_name              IN     VARCHAR2    DEFAULT NULL,
    x_borw_gross_annual_sal             IN     NUMBER      DEFAULT NULL,
    x_borw_other_income                 IN     NUMBER      DEFAULT NULL,
    x_student_major                     IN     VARCHAR2    DEFAULT NULL,
    x_int_rate_opt                      IN     VARCHAR2    DEFAULT NULL,
    x_repayment_opt_code                IN     VARCHAR2    DEFAULT NULL,
    x_stud_mth_housing_pymt             IN     NUMBER      DEFAULT NULL,
    x_stud_mth_crdtcard_pymt            IN     NUMBER      DEFAULT NULL,
    x_stud_mth_auto_pymt                IN     NUMBER      DEFAULT NULL,
    x_stud_mth_ed_loan_pymt             IN     NUMBER      DEFAULT NULL,
    x_stud_mth_other_pymt               IN     NUMBER      DEFAULT NULL,
    x_creation_date                     IN     DATE        DEFAULT NULL,
    x_created_by                        IN     NUMBER      DEFAULT NULL,
    x_last_update_date                  IN     DATE        DEFAULT NULL,
    x_last_updated_by                   IN     NUMBER      DEFAULT NULL,
    x_last_update_login                 IN     NUMBER      DEFAULT NULL,
    x_other_loan_amt                    IN     NUMBER      DEFAULT NULL,
    x_cs1_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_lname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_fname                         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mi_txt                        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_ssn_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_citizenship_status            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_1_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_address_line_2_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_city_txt                      IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_state_txt                     IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_txt                       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_zip_suffix_txt                IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_telephone_number_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_signature_code_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs1_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs1_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs1_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs1_years_at_address_txt          IN     NUMBER   DEFAULT   NULL,
    x_cs2_credit_auth_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_birth_date                    IN     Date     DEFAULT   NULL,
    x_cs2_drv_license_num_txt           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_drv_license_state_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_elect_sig_ind_code_txt        IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_postal_code_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_frgn_tel_num_prefix_txt       IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_gross_annual_sal_num          IN     NUMBER   DEFAULT   NULL,
    x_cs2_mthl_auto_pay_txt             IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_cc_pay_txt               IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_edu_loan_pay_txt         IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_housing_pay_txt          IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_mthl_other_pay_txt            IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_other_income_amt              IN     NUMBER   DEFAULT   NULL,
    x_cs2_rel_to_student_flag           IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_suffix_txt                    IN     VARCHAR2 DEFAULT   NULL,
    x_cs2_years_at_address_txt          IN     NUMBER   DEFAULT   NULL
  );

END igf_sl_alt_borw_pkg;

 

/
