--------------------------------------------------------
--  DDL for Package IGI_IGISLSUA_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGI_IGISLSUA_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: IGISLSUAS.pls 120.0.12010000.1 2008/07/29 08:59:52 appldev ship $ */
  P_CONC_REQUEST_ID NUMBER;

  P_GROUP_NAME VARCHAR2(40);
P_GROUP_NAME_T VARCHAR2(40);
  P_USER_NAME VARCHAR2(40);
P_USER_NAME_T VARCHAR2(40);
  CP_GROUP VARCHAR2(30);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_1FORMULA(SLS_GROUP IN VARCHAR2) RETURN NUMBER;

  FUNCTION CP_GROUP_P RETURN VARCHAR2;

END IGI_IGISLSUA_XMLP_PKG;

/
