--------------------------------------------------------
--  DDL for Package IGI_IGISLSOS_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGI_IGISLSOS_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: IGISLSOSS.pls 120.0.12010000.1 2008/07/29 08:59:39 appldev ship $ */
  P_TABLE_NAME VARCHAR2(30);
  P_TABLE_NAME_T VARCHAR2(30);

  P_CONC_REQUEST_ID NUMBER;

  P_OWNER VARCHAR2(32767);
  P_OWNER_T VARCHAR2(32767);

  CP_TABLE_NAME VARCHAR2(30);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_1FORMULA(TABLE_NAME2 IN VARCHAR2) RETURN NUMBER;

  FUNCTION CP_TABLE_NAME_P RETURN VARCHAR2;

END IGI_IGISLSOS_XMLP_PKG;

/
