--------------------------------------------------------
--  DDL for Package IGI_IGIGBJRB_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGI_IGIGBJRB_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: IGIGBJRBS.pls 120.0.12010000.1 2008/07/29 08:57:58 appldev ship $ */

  P_SOB VARCHAR2(40);

  P_BE_BATCH VARCHAR2(40);

  P_FLEXDATA VARCHAR2(600);

  P_COA VARCHAR2(40);

  P_CONC_REQUEST_ID NUMBER;

  P_DEBUG_SWITCH VARCHAR2(1);

  FUNCTION AFTERREPORT RETURN BOOLEAN;

    FUNCTION BEFOREREPORT RETURN BOOLEAN;

END IGI_IGIGBJRB_XMLP_PKG;

/
