--------------------------------------------------------
--  DDL for Package IGI_IGISLSSG_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGI_IGISLSSG_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: IGISLSSGS.pls 120.0.12010000.1 2008/07/29 08:59:44 appldev ship $ */
  P_CONC_REQUEST_ID NUMBER;

  P_GROUP_TYPE VARCHAR2(40);
  P_GROUP_TYPE_T VARCHAR2(40);

  P_GROUP_NAME VARCHAR2(40);
  P_GROUP_NAME_T VARCHAR2(40);

  CP_PRC_NAME VARCHAR2(30);

  CP_SEC_NAME VARCHAR2(30);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_2FORMULA(SEC_NAME IN VARCHAR2) RETURN NUMBER;

  FUNCTION CF_1FORMULA(PROC_NAME IN VARCHAR2) RETURN NUMBER;

  FUNCTION CP_PRC_NAME_P RETURN VARCHAR2;

  FUNCTION CP_SEC_NAME_P RETURN VARCHAR2;

  FUNCTION F_DATE_ENABLED1FORMATTRIGGER(SEC_DT_ENABLED IN DATE,SEC_DT_DISABLED IN DATE,SEC_DT_REMOVED IN DATE,SEC_DT_ENABLED_AU IN DATE,SEC_DT_DISABLED_AU IN DATE,SEC_DT_REMOVED_AU IN DATE) RETURN VARCHAR2;

  FUNCTION F_PRC_DT_ENABLED_AU1FORMATTRIG(PROC_DT_ENABLED IN DATE,PROC_DT_DISABLED IN DATE,PROC_DT_REMOVED IN DATE,PRC_DT_ENABLED_AU IN DATE,PRC_DT_DISABLED_AU IN DATE,PRC_DT_REMOVED_AU IN DATE) RETURN VARCHAR2;

END IGI_IGISLSSG_XMLP_PKG;

/
