--------------------------------------------------------
--  DDL for Package IGS_AS_SU_SETATMPT_H_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_AS_SU_SETATMPT_H_PKG" AUTHID CURRENT_USER AS
/* $Header: IGSDI28S.pls 115.6 2002/11/28 23:18:03 nsidana ship $ */

--

--
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_ORG_ID in NUMBER,
  X_PERSON_ID in NUMBER,
  X_COURSE_CD in VARCHAR2,
  X_UNIT_SET_CD in VARCHAR2,
  X_SEQUENCE_NUMBER in NUMBER,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_US_VERSION_NUMBER in NUMBER,
  X_SELECTION_DT in DATE,
  X_STUDENT_CONFIRMED_IND in VARCHAR2,
  X_END_DT in DATE,
  X_PARENT_UNIT_SET_CD in VARCHAR2,
  X_PARENT_SEQUENCE_NUMBER in NUMBER,
  X_PRIMARY_SET_IND in VARCHAR2,
  X_VOLUNTARY_END_IND in VARCHAR2,
  X_AUTHORISED_PERSON_ID in NUMBER,
  X_AUTHORISED_ON in DATE,
  X_OVERRIDE_TITLE in VARCHAR2,
  X_RQRMNTS_COMPLETE_IND in VARCHAR2,
  X_RQRMNTS_COMPLETE_DT in DATE,
  X_S_COMPLETED_SOURCE_TYPE in VARCHAR2,
  X_CATALOG_CAL_TYPE in VARCHAR2 DEFAULT NULL,
  X_CATALOG_SEQ_NUM  in NUMBER DEFAULT NULL,
  X_MODE in VARCHAR2 default 'R'
  );
procedure LOCK_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_COURSE_CD in VARCHAR2,
  X_UNIT_SET_CD in VARCHAR2,
  X_SEQUENCE_NUMBER in NUMBER,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_US_VERSION_NUMBER in NUMBER,
  X_SELECTION_DT in DATE,
  X_STUDENT_CONFIRMED_IND in VARCHAR2,
  X_END_DT in DATE,
  X_PARENT_UNIT_SET_CD in VARCHAR2,
  X_PARENT_SEQUENCE_NUMBER in NUMBER,
  X_PRIMARY_SET_IND in VARCHAR2,
  X_VOLUNTARY_END_IND in VARCHAR2,
  X_AUTHORISED_PERSON_ID in NUMBER,
  X_AUTHORISED_ON in DATE,
  X_OVERRIDE_TITLE in VARCHAR2,
  X_RQRMNTS_COMPLETE_IND in VARCHAR2,
  X_RQRMNTS_COMPLETE_DT in DATE,
  X_S_COMPLETED_SOURCE_TYPE in VARCHAR2,
  X_CATALOG_CAL_TYPE in VARCHAR2 DEFAULT NULL,
  X_CATALOG_SEQ_NUM  in NUMBER DEFAULT NULL
);
procedure UPDATE_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_COURSE_CD in VARCHAR2,
  X_UNIT_SET_CD in VARCHAR2,
  X_SEQUENCE_NUMBER in NUMBER,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_US_VERSION_NUMBER in NUMBER,
  X_SELECTION_DT in DATE,
  X_STUDENT_CONFIRMED_IND in VARCHAR2,
  X_END_DT in DATE,
  X_PARENT_UNIT_SET_CD in VARCHAR2,
  X_PARENT_SEQUENCE_NUMBER in NUMBER,
  X_PRIMARY_SET_IND in VARCHAR2,
  X_VOLUNTARY_END_IND in VARCHAR2,
  X_AUTHORISED_PERSON_ID in NUMBER,
  X_AUTHORISED_ON in DATE,
  X_OVERRIDE_TITLE in VARCHAR2,
  X_RQRMNTS_COMPLETE_IND in VARCHAR2,
  X_RQRMNTS_COMPLETE_DT in DATE,
  X_S_COMPLETED_SOURCE_TYPE in VARCHAR2,
  X_CATALOG_CAL_TYPE in VARCHAR2 DEFAULT NULL,
  X_CATALOG_SEQ_NUM  in NUMBER DEFAULT NULL,
  X_MODE in VARCHAR2 default 'R'
  );
procedure ADD_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_ORG_ID in NUMBER,
  X_PERSON_ID in NUMBER,
  X_COURSE_CD in VARCHAR2,
  X_UNIT_SET_CD in VARCHAR2,
  X_SEQUENCE_NUMBER in NUMBER,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_US_VERSION_NUMBER in NUMBER,
  X_SELECTION_DT in DATE,
  X_STUDENT_CONFIRMED_IND in VARCHAR2,
  X_END_DT in DATE,
  X_PARENT_UNIT_SET_CD in VARCHAR2,
  X_PARENT_SEQUENCE_NUMBER in NUMBER,
  X_PRIMARY_SET_IND in VARCHAR2,
  X_VOLUNTARY_END_IND in VARCHAR2,
  X_AUTHORISED_PERSON_ID in NUMBER,
  X_AUTHORISED_ON in DATE,
  X_OVERRIDE_TITLE in VARCHAR2,
  X_RQRMNTS_COMPLETE_IND in VARCHAR2,
  X_RQRMNTS_COMPLETE_DT in DATE,
  X_S_COMPLETED_SOURCE_TYPE in VARCHAR2,
  X_CATALOG_CAL_TYPE in VARCHAR2 DEFAULT NULL,
  X_CATALOG_SEQ_NUM  in NUMBER DEFAULT NULL,
  X_MODE in VARCHAR2 default 'R'
  );
procedure DELETE_ROW (
  X_ROWID in VARCHAR2
  );
 FUNCTION Get_PK_For_Validation (
    x_person_id IN NUMBER,
    x_course_cd IN VARCHAR2,
    x_unit_set_cd IN VARCHAR2,
    x_sequence_number IN NUMBER,
    x_hist_start_dt IN DATE
    )RETURN BOOLEAN;

	PROCEDURE Check_Constraints (
	Column_Name	IN	VARCHAR2	DEFAULT NULL,
	Column_Value 	IN	VARCHAR2	DEFAULT NULL
	);

 PROCEDURE Before_DML (
    p_action IN VARCHAR2,
    x_rowid IN VARCHAR2 DEFAULT NULL,
    x_org_id IN NUMBER DEFAULT NULL,
    x_person_id IN NUMBER DEFAULT NULL,
    x_course_cd IN VARCHAR2 DEFAULT NULL,
    x_unit_set_cd IN VARCHAR2 DEFAULT NULL,
    x_sequence_number IN NUMBER DEFAULT NULL,
    x_hist_start_dt IN DATE DEFAULT NULL,
    x_hist_end_dt IN DATE DEFAULT NULL,
    x_hist_who IN NUMBER DEFAULT NULL,
    x_us_version_number IN NUMBER DEFAULT NULL,
    x_selection_dt IN DATE DEFAULT NULL,
    x_student_confirmed_ind IN VARCHAR2 DEFAULT NULL,
    x_end_dt IN DATE DEFAULT NULL,
    x_parent_unit_set_cd IN VARCHAR2 DEFAULT NULL,
    x_parent_sequence_number IN NUMBER DEFAULT NULL,
    x_primary_set_ind IN VARCHAR2 DEFAULT NULL,
    x_voluntary_end_ind IN VARCHAR2 DEFAULT NULL,
    x_authorised_person_id IN NUMBER DEFAULT NULL,
    x_authorised_on IN DATE DEFAULT NULL,
    x_override_title IN VARCHAR2 DEFAULT NULL,
    x_rqrmnts_complete_ind IN VARCHAR2 DEFAULT NULL,
    x_rqrmnts_complete_dt IN DATE DEFAULT NULL,
    x_s_completed_source_type IN VARCHAR2 DEFAULT NULL,
    X_CATALOG_CAL_TYPE in VARCHAR2 DEFAULT NULL,
    X_CATALOG_SEQ_NUM  in NUMBER  DEFAULT NULL,
    x_creation_date IN DATE DEFAULT NULL,
    x_created_by IN NUMBER DEFAULT NULL,
    x_last_update_date IN DATE DEFAULT NULL,
    x_last_updated_by IN NUMBER DEFAULT NULL,
    x_last_update_login IN NUMBER DEFAULT NULL
  ) ;



end IGS_AS_SU_SETATMPT_H_PKG;

 

/
