--------------------------------------------------------
--  DDL for Package IGS_PR_OU_TYPE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_PR_OU_TYPE_PKG" AUTHID CURRENT_USER as
/* $Header: IGSQI06S.pls 115.6 2003/02/24 11:29:03 gjha ship $ */

procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_S_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_ENCUMBRANCE_TYPE in VARCHAR2,
  X_DFLT_RESTRICTED_ENROLMENT_CP in NUMBER,
  X_DFLT_RESTRICTED_ATT_TYPE in VARCHAR2,
  X_CLOSED_IND in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_ORG_ID in NUMBER,
  X_POSITIVE_OUTCOME_IND IN VARCHAR2 DEFAULT 'N'
  );
procedure LOCK_ROW (
  X_ROWID in VARCHAR2,
  X_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_S_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_ENCUMBRANCE_TYPE in VARCHAR2,
  X_DFLT_RESTRICTED_ENROLMENT_CP in NUMBER,
  X_DFLT_RESTRICTED_ATT_TYPE in VARCHAR2,
  X_CLOSED_IND in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_POSITIVE_OUTCOME_IND IN VARCHAR2
);
procedure UPDATE_ROW (
  X_ROWID in VARCHAR2,
  X_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_S_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_ENCUMBRANCE_TYPE in VARCHAR2,
  X_DFLT_RESTRICTED_ENROLMENT_CP in NUMBER,
  X_DFLT_RESTRICTED_ATT_TYPE in VARCHAR2,
  X_CLOSED_IND in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_POSITIVE_OUTCOME_IND IN VARCHAR2 DEFAULT 'N'
  );
procedure ADD_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_S_PROGRESSION_OUTCOME_TYPE in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_ENCUMBRANCE_TYPE in VARCHAR2,
  X_DFLT_RESTRICTED_ENROLMENT_CP in NUMBER,
  X_DFLT_RESTRICTED_ATT_TYPE in VARCHAR2,
  X_CLOSED_IND in VARCHAR2,
  X_COMMENTS in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_ORG_ID in NUMBER ,
  X_POSITIVE_OUTCOME_IND IN VARCHAR2 DEFAULT 'N'
  );

/*Removed procedure Delete_row for Records Locking Bug 2784198 */

 FUNCTION Get_PK_For_Validation (
    x_progression_outcome_type IN VARCHAR2
    )
 RETURN BOOLEAN;

  PROCEDURE GET_FK_IGS_EN_ATD_TYPE (
    x_attendance_type IN VARCHAR2
    );

  PROCEDURE GET_FK_IGS_FI_ENCMB_TYPE (
    x_encumbrance_type IN VARCHAR2
    );

  PROCEDURE GET_FK_IGS_LOOKUPS_VIEW (
    x_s_progression_outcome_type IN VARCHAR2
    );

  PROCEDURE  Check_Constraints (
    Column_Name IN VARCHAR2 DEFAULT NULL,
    Column_Value IN VARCHAR2 DEFAULT NULL
  );

  PROCEDURE Before_DML (
    p_action IN VARCHAR2,
    x_rowid IN VARCHAR2 DEFAULT NULL,
    x_progression_outcome_type IN VARCHAR2 DEFAULT NULL,
    x_s_progression_outcome_type IN VARCHAR2 DEFAULT NULL,
    x_description IN VARCHAR2 DEFAULT NULL,
    x_encumbrance_type IN VARCHAR2 DEFAULT NULL,
    x_dflt_restricted_enrolment_cp IN NUMBER DEFAULT NULL,
    x_dflt_restricted_att_type IN VARCHAR2 DEFAULT NULL,
    x_closed_ind IN VARCHAR2 DEFAULT NULL,
    x_comments IN VARCHAR2 DEFAULT NULL,
    x_creation_date IN DATE DEFAULT NULL,
    x_created_by IN NUMBER DEFAULT NULL,
    x_last_update_date IN DATE DEFAULT NULL,
    x_last_updated_by IN NUMBER DEFAULT NULL,
    x_last_update_login IN NUMBER DEFAULT NULL,
    X_ORG_ID in NUMBER DEFAULT NULL,
    X_POSITIVE_OUTCOME_IND IN VARCHAR2 DEFAULT 'N'
  ) ;

end IGS_PR_OU_TYPE_PKG;

 

/
