--------------------------------------------------------
--  DDL for Package IGS_AS_DOC_DETAILS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_AS_DOC_DETAILS_PKG" AUTHID CURRENT_USER AS
/* $Header: IGSDI71S.pls 115.3 2002/11/28 23:29:29 nsidana noship $ */

  PROCEDURE insert_row (
    x_rowid                             IN OUT NOCOPY VARCHAR2,
    x_order_number                      IN     NUMBER,
    x_document_type                     IN     VARCHAR2,
    x_document_sub_type                 IN     VARCHAR2,
    x_item_number                       IN OUT NOCOPY NUMBER,
    x_item_status                       IN     VARCHAR2,
    x_date_produced                     IN     DATE,
    x_incl_curr_course                  IN     VARCHAR2,
    x_num_of_copies                     IN     NUMBER,
    x_comments                          IN     VARCHAR2,
    x_recip_pers_name                   IN     VARCHAR2,
    x_recip_inst_name                   IN     VARCHAR2,
    x_recip_addr_line_1                 IN     VARCHAR2,
    x_recip_addr_line_2                 IN     VARCHAR2,
    x_recip_addr_line_3                 IN     VARCHAR2,
    x_recip_addr_line_4                 IN     VARCHAR2,
    x_recip_city                        IN     VARCHAR2,
    x_recip_postal_code                 IN     VARCHAR2,
    x_recip_state                       IN     VARCHAR2,
    x_recip_province                    IN     VARCHAR2,
    x_recip_county                      IN     VARCHAR2,
    x_recip_country                     IN     VARCHAR2,
    x_recip_fax_area_code               IN     VARCHAR2,
    x_recip_fax_country_code            IN     VARCHAR2,
    x_recip_fax_number                  IN     VARCHAR2,
    x_delivery_method_type              IN     VARCHAR2,
    x_programs_on_file                  IN     VARCHAR2,
    x_missing_acad_record_data_ind      IN     VARCHAR2,
    x_missing_academic_record_data      IN     VARCHAR2,
    x_send_transcript_immediately       IN     VARCHAR2,
    x_hold_release_of_final_grades      IN     VARCHAR2,
    x_fgrade_cal_type                   IN     VARCHAR2,
    x_fgrade_seq_num                    IN     NUMBER,
    x_hold_degree_expected              IN     VARCHAR2,
    x_deghold_cal_type                  IN     VARCHAR2,
    x_deghold_seq_num                   IN     NUMBER,
    x_hold_for_grade_chg                IN     VARCHAR2,
    x_special_instr                     IN     VARCHAR2,
    x_express_mail_type                 IN     VARCHAR2,
    x_express_mail_track_num            IN     VARCHAR2,
    x_ge_certification                  IN     VARCHAR2,
    x_external_comments                 IN     VARCHAR2,
    x_internal_comments                 IN     VARCHAR2,
    x_dup_requested                     IN     VARCHAR2,
    x_dup_req_date                      IN     DATE,
    x_dup_sent_date                     IN     DATE,
    x_enr_term_cal_type                 IN     VARCHAR2,
    x_enr_ci_sequence_number            IN     NUMBER,
    x_incl_attempted_hours              IN     VARCHAR2,
    x_incl_class_rank                   IN     VARCHAR2,
    x_incl_progresssion_status          IN     VARCHAR2,
    x_incl_class_standing               IN     VARCHAR2,
    x_incl_cum_hours_earned             IN     VARCHAR2,
    x_incl_gpa                          IN     VARCHAR2,
    x_incl_date_of_graduation           IN     VARCHAR2,
    x_incl_degree_dates                 IN     VARCHAR2,
    x_incl_degree_earned                IN     VARCHAR2,
    x_incl_date_of_entry                IN     VARCHAR2,
    x_incl_drop_withdrawal_dates        IN     VARCHAR2,
    x_incl_hrs_for_curr_term            IN     VARCHAR2,
    x_incl_majors                       IN     VARCHAR2,
    x_incl_last_date_of_enrollment      IN     VARCHAR2,
    x_incl_professional_licensure       IN     VARCHAR2,
    x_incl_college_affiliation          IN     VARCHAR2,
    x_incl_instruction_dates            IN     VARCHAR2,
    x_incl_usec_dates                   IN     VARCHAR2,
    x_incl_program_attempt              IN     VARCHAR2,
    x_incl_attendence_type              IN     VARCHAR2,
    x_incl_last_term_enrolled           IN     VARCHAR2,
    x_incl_ssn                          IN     VARCHAR2,
    x_incl_date_of_birth                IN     VARCHAR2,
    x_incl_disciplin_standing           IN     VARCHAR2,
    x_incl_no_future_term               IN     VARCHAR2,
    x_incl_acurat_till_copmp_dt         IN     VARCHAR2,
    x_incl_cant_rel_without_sign        IN     VARCHAR2,
    x_mode                              IN     VARCHAR2    DEFAULT 'R' ,
    X_RETURN_STATUS                     OUT NOCOPY    VARCHAR2,
    X_MSG_DATA                          OUT NOCOPY    VARCHAR2,
    X_MSG_COUNT                         OUT NOCOPY    NUMBER,
    X_DOC_FEE_PER_COPY                  IN     NUMBER,
    X_DELIVERY_FEE                      IN     NUMBER,
    X_RECIP_EMAIL                       IN     VARCHAR2,
    x_overridden_doc_delivery_fee       IN     NUMBER DEFAULT NULL,
    x_overridden_document_fee           IN     NUMBER DEFAULT NULL,
    x_fee_overridden_by                 IN     NUMBER DEFAULT NULL,
    x_fee_overridden_date               IN     DATE DEFAULT NULL,
    x_incl_department                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_field_of_stdy                IN     VARCHAR2 DEFAULT NULL,
    x_incl_attend_mode                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_yop_acad_prd                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_intrmsn_st_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_hnrs_lvl                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_awards                       IN     VARCHAR2 DEFAULT NULL,
    x_incl_award_aim                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_acad_sessions                IN     VARCHAR2 DEFAULT NULL,
    x_incl_st_end_acad_ses              IN     VARCHAR2 DEFAULT NULL,
    x_incl_hesa_num                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_location                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_type                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_name                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_stat              IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_strt              IN     VARCHAR2 DEFAULT NULL,
    x_incl_req_cmplete                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_expected_compl_dt            IN     VARCHAR2 DEFAULT NULL,
    x_incl_conferral_dt                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_thesis_title                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_code                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_ver                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_stud_no                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_surname                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_fore_name                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_prev_names                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_initials                     IN     VARCHAR2 DEFAULT NULL,
    x_doc_purpose_code                  IN     VARCHAR2 DEFAULT NULL,
    x_plan_id				IN     NUMBER DEFAULT NULL,
    x_produced_by                       IN     NUMBER DEFAULT NULL,
    x_person_id                         IN     NUMBER DEFAULT NULL
  );

  PROCEDURE lock_row (
    x_rowid                             IN     VARCHAR2,
    x_order_number                      IN     NUMBER,
    x_document_type                     IN     VARCHAR2,
    x_document_sub_type                 IN     VARCHAR2,
    x_item_number                       IN     NUMBER,
    x_item_status                       IN     VARCHAR2,
    x_date_produced                     IN     DATE,
    x_incl_curr_course                  IN     VARCHAR2,
    x_num_of_copies                     IN     NUMBER,
    x_comments                          IN     VARCHAR2,
    x_recip_pers_name                   IN     VARCHAR2,
    x_recip_inst_name                   IN     VARCHAR2,
    x_recip_addr_line_1                 IN     VARCHAR2,
    x_recip_addr_line_2                 IN     VARCHAR2,
    x_recip_addr_line_3                 IN     VARCHAR2,
    x_recip_addr_line_4                 IN     VARCHAR2,
    x_recip_city                        IN     VARCHAR2,
    x_recip_postal_code                 IN     VARCHAR2,
    x_recip_state                       IN     VARCHAR2,
    x_recip_province                    IN     VARCHAR2,
    x_recip_county                      IN     VARCHAR2,
    x_recip_country                     IN     VARCHAR2,
    x_recip_fax_area_code               IN     VARCHAR2,
    x_recip_fax_country_code            IN     VARCHAR2,
    x_recip_fax_number                  IN     VARCHAR2,
    x_delivery_method_type              IN     VARCHAR2,
    x_programs_on_file                  IN     VARCHAR2,
    x_missing_acad_record_data_ind      IN     VARCHAR2,
    x_missing_academic_record_data      IN     VARCHAR2,
    x_send_transcript_immediately       IN     VARCHAR2,
    x_hold_release_of_final_grades      IN     VARCHAR2,
    x_fgrade_cal_type                   IN     VARCHAR2,
    x_fgrade_seq_num                    IN     NUMBER,
    x_hold_degree_expected              IN     VARCHAR2,
    x_deghold_cal_type                  IN     VARCHAR2,
    x_deghold_seq_num                   IN     NUMBER,
    x_hold_for_grade_chg                IN     VARCHAR2,
    x_special_instr                     IN     VARCHAR2,
    x_express_mail_type                 IN     VARCHAR2,
    x_express_mail_track_num            IN     VARCHAR2,
    x_ge_certification                  IN     VARCHAR2,
    x_external_comments                 IN     VARCHAR2,
    x_internal_comments                 IN     VARCHAR2,
    x_dup_requested                     IN     VARCHAR2,
    x_dup_req_date                      IN     DATE,
    x_dup_sent_date                     IN     DATE,
    x_enr_term_cal_type                 IN     VARCHAR2,
    x_enr_ci_sequence_number            IN     NUMBER,
    x_incl_attempted_hours              IN     VARCHAR2,
    x_incl_class_rank                   IN     VARCHAR2,
    x_incl_progresssion_status          IN     VARCHAR2,
    x_incl_class_standing               IN     VARCHAR2,
    x_incl_cum_hours_earned             IN     VARCHAR2,
    x_incl_gpa                          IN     VARCHAR2,
    x_incl_date_of_graduation           IN     VARCHAR2,
    x_incl_degree_dates                 IN     VARCHAR2,
    x_incl_degree_earned                IN     VARCHAR2,
    x_incl_date_of_entry                IN     VARCHAR2,
    x_incl_drop_withdrawal_dates        IN     VARCHAR2,
    x_incl_hrs_for_curr_term            IN     VARCHAR2,
    x_incl_majors                       IN     VARCHAR2,
    x_incl_last_date_of_enrollment      IN     VARCHAR2,
    x_incl_professional_licensure       IN     VARCHAR2,
    x_incl_college_affiliation          IN     VARCHAR2,
    x_incl_instruction_dates            IN     VARCHAR2,
    x_incl_usec_dates                   IN     VARCHAR2,
    x_incl_program_attempt              IN     VARCHAR2,
    x_incl_attendence_type              IN     VARCHAR2,
    x_incl_last_term_enrolled           IN     VARCHAR2,
    x_incl_ssn                          IN     VARCHAR2,
    x_incl_date_of_birth                IN     VARCHAR2,
    x_incl_disciplin_standing           IN     VARCHAR2,
    x_incl_no_future_term               IN     VARCHAR2,
    x_incl_acurat_till_copmp_dt         IN     VARCHAR2,
    x_incl_cant_rel_without_sign        IN     VARCHAR2,
    X_RETURN_STATUS                     OUT NOCOPY    VARCHAR2,
    X_MSG_DATA                          OUT NOCOPY    VARCHAR2,
    X_MSG_COUNT                         OUT NOCOPY    NUMBER,
    X_DOC_FEE_PER_COPY                  IN     NUMBER,
    X_DELIVERY_FEE                      IN     NUMBER,
    X_RECIP_EMAIL                       IN     VARCHAR2,
    x_overridden_doc_delivery_fee       IN     NUMBER DEFAULT NULL,
    x_overridden_document_fee           IN     NUMBER DEFAULT NULL,
    x_fee_overridden_by                 IN     NUMBER DEFAULT NULL,
    x_fee_overridden_date               IN     DATE DEFAULT NULL,
    x_incl_department                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_field_of_stdy                IN     VARCHAR2 DEFAULT NULL,
    x_incl_attend_mode                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_yop_acad_prd                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_intrmsn_st_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_hnrs_lvl                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_awards                       IN     VARCHAR2 DEFAULT NULL,
    x_incl_award_aim                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_acad_sessions                IN     VARCHAR2 DEFAULT NULL,
    x_incl_st_end_acad_ses              IN     VARCHAR2 DEFAULT NULL,
    x_incl_hesa_num                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_location                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_type                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_name                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_stat              IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_strt              IN     VARCHAR2 DEFAULT NULL,
    x_incl_req_cmplete                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_expected_compl_dt            IN     VARCHAR2 DEFAULT NULL,
    x_incl_conferral_dt                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_thesis_title                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_code                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_ver                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_stud_no                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_surname                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_fore_name                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_prev_names                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_initials                     IN     VARCHAR2 DEFAULT NULL,
    x_doc_purpose_code                  IN     VARCHAR2 DEFAULT NULL,
    x_plan_id				IN     NUMBER DEFAULT NULL,
    x_produced_by                       IN     NUMBER DEFAULT NULL,
    x_person_id                         IN     NUMBER DEFAULT NULL
  );

  PROCEDURE update_row (
    x_rowid                             IN     VARCHAR2,
    x_order_number                      IN     NUMBER,
    x_document_type                     IN     VARCHAR2,
    x_document_sub_type                 IN     VARCHAR2,
    x_item_number                       IN     NUMBER,
    x_item_status                       IN     VARCHAR2,
    x_date_produced                     IN     DATE,
    x_incl_curr_course                  IN     VARCHAR2,
    x_num_of_copies                     IN     NUMBER,
    x_comments                          IN     VARCHAR2,
    x_recip_pers_name                   IN     VARCHAR2,
    x_recip_inst_name                   IN     VARCHAR2,
    x_recip_addr_line_1                 IN     VARCHAR2,
    x_recip_addr_line_2                 IN     VARCHAR2,
    x_recip_addr_line_3                 IN     VARCHAR2,
    x_recip_addr_line_4                 IN     VARCHAR2,
    x_recip_city                        IN     VARCHAR2,
    x_recip_postal_code                 IN     VARCHAR2,
    x_recip_state                       IN     VARCHAR2,
    x_recip_province                    IN     VARCHAR2,
    x_recip_county                      IN     VARCHAR2,
    x_recip_country                     IN     VARCHAR2,
    x_recip_fax_area_code               IN     VARCHAR2,
    x_recip_fax_country_code            IN     VARCHAR2,
    x_recip_fax_number                  IN     VARCHAR2,
    x_delivery_method_type              IN     VARCHAR2,
    x_programs_on_file                  IN     VARCHAR2,
    x_missing_acad_record_data_ind      IN     VARCHAR2,
    x_missing_academic_record_data      IN     VARCHAR2,
    x_send_transcript_immediately       IN     VARCHAR2,
    x_hold_release_of_final_grades      IN     VARCHAR2,
    x_fgrade_cal_type                   IN     VARCHAR2,
    x_fgrade_seq_num                    IN     NUMBER,
    x_hold_degree_expected              IN     VARCHAR2,
    x_deghold_cal_type                  IN     VARCHAR2,
    x_deghold_seq_num                   IN     NUMBER,
    x_hold_for_grade_chg                IN     VARCHAR2,
    x_special_instr                     IN     VARCHAR2,
    x_express_mail_type                 IN     VARCHAR2,
    x_express_mail_track_num            IN     VARCHAR2,
    x_ge_certification                  IN     VARCHAR2,
    x_external_comments                 IN     VARCHAR2,
    x_internal_comments                 IN     VARCHAR2,
    x_dup_requested                     IN     VARCHAR2,
    x_dup_req_date                      IN     DATE,
    x_dup_sent_date                     IN     DATE,
    x_enr_term_cal_type                 IN     VARCHAR2,
    x_enr_ci_sequence_number            IN     NUMBER,
    x_incl_attempted_hours              IN     VARCHAR2,
    x_incl_class_rank                   IN     VARCHAR2,
    x_incl_progresssion_status          IN     VARCHAR2,
    x_incl_class_standing               IN     VARCHAR2,
    x_incl_cum_hours_earned             IN     VARCHAR2,
    x_incl_gpa                          IN     VARCHAR2,
    x_incl_date_of_graduation           IN     VARCHAR2,
    x_incl_degree_dates                 IN     VARCHAR2,
    x_incl_degree_earned                IN     VARCHAR2,
    x_incl_date_of_entry                IN     VARCHAR2,
    x_incl_drop_withdrawal_dates        IN     VARCHAR2,
    x_incl_hrs_for_curr_term            IN     VARCHAR2,
    x_incl_majors                       IN     VARCHAR2,
    x_incl_last_date_of_enrollment      IN     VARCHAR2,
    x_incl_professional_licensure       IN     VARCHAR2,
    x_incl_college_affiliation          IN     VARCHAR2,
    x_incl_instruction_dates            IN     VARCHAR2,
    x_incl_usec_dates                   IN     VARCHAR2,
    x_incl_program_attempt              IN     VARCHAR2,
    x_incl_attendence_type              IN     VARCHAR2,
    x_incl_last_term_enrolled           IN     VARCHAR2,
    x_incl_ssn                          IN     VARCHAR2,
    x_incl_date_of_birth                IN     VARCHAR2,
    x_incl_disciplin_standing           IN     VARCHAR2,
    x_incl_no_future_term               IN     VARCHAR2,
    x_incl_acurat_till_copmp_dt         IN     VARCHAR2,
    x_incl_cant_rel_without_sign        IN     VARCHAR2,
    x_mode                              IN     VARCHAR2    DEFAULT 'R' ,
    X_RETURN_STATUS                     OUT NOCOPY    VARCHAR2,
    X_MSG_DATA                          OUT NOCOPY    VARCHAR2,
    X_MSG_COUNT                         OUT NOCOPY    NUMBER,
    X_DOC_FEE_PER_COPY                  IN     NUMBER,
    X_DELIVERY_FEE                      IN     NUMBER,
    X_RECIP_EMAIL                       IN     VARCHAR2,
    x_overridden_doc_delivery_fee       IN     NUMBER DEFAULT NULL,
    x_overridden_document_fee           IN     NUMBER DEFAULT NULL,
    x_fee_overridden_by                 IN     NUMBER DEFAULT NULL,
    x_fee_overridden_date               IN     DATE DEFAULT NULL,
    x_incl_department                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_field_of_stdy                IN     VARCHAR2 DEFAULT NULL,
    x_incl_attend_mode                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_yop_acad_prd                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_intrmsn_st_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_hnrs_lvl                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_awards                       IN     VARCHAR2 DEFAULT NULL,
    x_incl_award_aim                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_acad_sessions                IN     VARCHAR2 DEFAULT NULL,
    x_incl_st_end_acad_ses              IN     VARCHAR2 DEFAULT NULL,
    x_incl_hesa_num                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_location                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_type                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_name                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_stat              IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_strt              IN     VARCHAR2 DEFAULT NULL,
    x_incl_req_cmplete                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_expected_compl_dt            IN     VARCHAR2 DEFAULT NULL,
    x_incl_conferral_dt                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_thesis_title                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_code                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_ver                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_stud_no                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_surname                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_fore_name                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_prev_names                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_initials                     IN     VARCHAR2 DEFAULT NULL,
    x_doc_purpose_code                  IN     VARCHAR2 DEFAULT NULL,
    x_plan_id				IN     NUMBER DEFAULT NULL,
    x_produced_by                       IN     NUMBER DEFAULT NULL,
    x_person_id                         IN     NUMBER DEFAULT NULL
  );

  PROCEDURE add_row (
    x_rowid                             IN OUT NOCOPY VARCHAR2,
    x_order_number                      IN     NUMBER,
    x_document_type                     IN     VARCHAR2,
    x_document_sub_type                 IN     VARCHAR2,
    x_item_number                       IN OUT NOCOPY NUMBER,
    x_item_status                       IN     VARCHAR2,
    x_date_produced                     IN     DATE,
    x_incl_curr_course                  IN     VARCHAR2,
    x_num_of_copies                     IN     NUMBER,
    x_comments                          IN     VARCHAR2,
    x_recip_pers_name                   IN     VARCHAR2,
    x_recip_inst_name                   IN     VARCHAR2,
    x_recip_addr_line_1                 IN     VARCHAR2,
    x_recip_addr_line_2                 IN     VARCHAR2,
    x_recip_addr_line_3                 IN     VARCHAR2,
    x_recip_addr_line_4                 IN     VARCHAR2,
    x_recip_city                        IN     VARCHAR2,
    x_recip_postal_code                 IN     VARCHAR2,
    x_recip_state                       IN     VARCHAR2,
    x_recip_province                    IN     VARCHAR2,
    x_recip_county                      IN     VARCHAR2,
    x_recip_country                     IN     VARCHAR2,
    x_recip_fax_area_code               IN     VARCHAR2,
    x_recip_fax_country_code            IN     VARCHAR2,
    x_recip_fax_number                  IN     VARCHAR2,
    x_delivery_method_type              IN     VARCHAR2,
    x_programs_on_file                  IN     VARCHAR2,
    x_missing_acad_record_data_ind      IN     VARCHAR2,
    x_missing_academic_record_data      IN     VARCHAR2,
    x_send_transcript_immediately       IN     VARCHAR2,
    x_hold_release_of_final_grades      IN     VARCHAR2,
    x_fgrade_cal_type                   IN     VARCHAR2,
    x_fgrade_seq_num                    IN     NUMBER,
    x_hold_degree_expected              IN     VARCHAR2,
    x_deghold_cal_type                  IN     VARCHAR2,
    x_deghold_seq_num                   IN     NUMBER,
    x_hold_for_grade_chg                IN     VARCHAR2,
    x_special_instr                     IN     VARCHAR2,
    x_express_mail_type                 IN     VARCHAR2,
    x_express_mail_track_num            IN     VARCHAR2,
    x_ge_certification                  IN     VARCHAR2,
    x_external_comments                 IN     VARCHAR2,
    x_internal_comments                 IN     VARCHAR2,
    x_dup_requested                     IN     VARCHAR2,
    x_dup_req_date                      IN     DATE,
    x_dup_sent_date                     IN     DATE,
    x_enr_term_cal_type                 IN     VARCHAR2,
    x_enr_ci_sequence_number            IN     NUMBER,
    x_incl_attempted_hours              IN     VARCHAR2,
    x_incl_class_rank                   IN     VARCHAR2,
    x_incl_progresssion_status          IN     VARCHAR2,
    x_incl_class_standing               IN     VARCHAR2,
    x_incl_cum_hours_earned             IN     VARCHAR2,
    x_incl_gpa                          IN     VARCHAR2,
    x_incl_date_of_graduation           IN     VARCHAR2,
    x_incl_degree_dates                 IN     VARCHAR2,
    x_incl_degree_earned                IN     VARCHAR2,
    x_incl_date_of_entry                IN     VARCHAR2,
    x_incl_drop_withdrawal_dates        IN     VARCHAR2,
    x_incl_hrs_for_curr_term            IN     VARCHAR2,
    x_incl_majors                       IN     VARCHAR2,
    x_incl_last_date_of_enrollment      IN     VARCHAR2,
    x_incl_professional_licensure       IN     VARCHAR2,
    x_incl_college_affiliation          IN     VARCHAR2,
    x_incl_instruction_dates            IN     VARCHAR2,
    x_incl_usec_dates                   IN     VARCHAR2,
    x_incl_program_attempt              IN     VARCHAR2,
    x_incl_attendence_type              IN     VARCHAR2,
    x_incl_last_term_enrolled           IN     VARCHAR2,
    x_incl_ssn                          IN     VARCHAR2,
    x_incl_date_of_birth                IN     VARCHAR2,
    x_incl_disciplin_standing           IN     VARCHAR2,
    x_incl_no_future_term               IN     VARCHAR2,
    x_incl_acurat_till_copmp_dt         IN     VARCHAR2,
    x_incl_cant_rel_without_sign        IN     VARCHAR2,
    x_mode                              IN     VARCHAR2    DEFAULT 'R',
    X_DOC_FEE_PER_COPY                  IN     NUMBER,
    X_DELIVERY_FEE                      IN     NUMBER,
    X_RECIP_EMAIL                       IN     VARCHAR2,
    x_overridden_doc_delivery_fee       IN     NUMBER DEFAULT NULL,
    x_overridden_document_fee           IN     NUMBER DEFAULT NULL,
    x_fee_overridden_by                 IN     NUMBER DEFAULT NULL,
    x_fee_overridden_date               IN     DATE DEFAULT NULL,
    x_incl_department                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_field_of_stdy                IN     VARCHAR2 DEFAULT NULL,
    x_incl_attend_mode                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_yop_acad_prd                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_intrmsn_st_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_hnrs_lvl                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_awards                       IN     VARCHAR2 DEFAULT NULL,
    x_incl_award_aim                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_acad_sessions                IN     VARCHAR2 DEFAULT NULL,
    x_incl_st_end_acad_ses              IN     VARCHAR2 DEFAULT NULL,
    x_incl_hesa_num                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_location                     IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_type                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_name                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_stat              IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_end               IN     VARCHAR2 DEFAULT NULL,
    x_incl_prog_atmpt_strt              IN     VARCHAR2 DEFAULT NULL,
    x_incl_req_cmplete                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_expected_compl_dt            IN     VARCHAR2 DEFAULT NULL,
    x_incl_conferral_dt                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_thesis_title                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_code                 IN     VARCHAR2 DEFAULT NULL,
    x_incl_program_ver                  IN     VARCHAR2 DEFAULT NULL,
    x_incl_stud_no                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_surname                      IN     VARCHAR2 DEFAULT NULL,
    x_incl_fore_name                    IN     VARCHAR2 DEFAULT NULL,
    x_incl_prev_names                   IN     VARCHAR2 DEFAULT NULL,
    x_incl_initials                     IN     VARCHAR2 DEFAULT NULL,
    x_doc_purpose_code                  IN     VARCHAR2 DEFAULT NULL,
    x_plan_id				IN     NUMBER DEFAULT NULL,
    x_produced_by                       IN     NUMBER DEFAULT NULL,
    x_person_id                         IN     NUMBER DEFAULT NULL
  );

  PROCEDURE delete_row (
    x_rowid                             IN     VARCHAR2 ,
    X_RETURN_STATUS                     OUT NOCOPY    VARCHAR2 ,
    X_MSG_DATA                          OUT NOCOPY    VARCHAR2 ,
    X_MSG_COUNT                         OUT NOCOPY    NUMBER
  );

  FUNCTION get_pk_for_validation (
    x_item_number                       IN     NUMBER
  ) RETURN BOOLEAN;

  PROCEDURE get_fk_igs_as_doc_dlvy_typ (
    x_delivery_method_type              IN     VARCHAR2
  );

  PROCEDURE get_fk_igs_ca_inst (
    x_cal_type                          IN     VARCHAR2,
    x_sequence_number                   IN     NUMBER
  );

  PROCEDURE get_fk_igs_as_order_hdr (
    x_order_number                      IN     NUMBER
  );

  PROCEDURE before_dml (
    p_action                            IN     VARCHAR2,
    x_rowid                             IN     VARCHAR2    DEFAULT NULL,
    x_order_number                      IN     NUMBER      DEFAULT NULL,
    x_document_type                     IN     VARCHAR2    DEFAULT NULL,
    x_document_sub_type                 IN     VARCHAR2    DEFAULT NULL,
    x_item_number                       IN     NUMBER      DEFAULT NULL,
    x_item_status                       IN     VARCHAR2    DEFAULT NULL,
    x_date_produced                     IN     DATE        DEFAULT NULL,
    x_incl_curr_course                  IN     VARCHAR2    DEFAULT NULL,
    x_num_of_copies                     IN     NUMBER      DEFAULT NULL,
    x_comments                          IN     VARCHAR2    DEFAULT NULL,
    x_recip_pers_name                   IN     VARCHAR2    DEFAULT NULL,
    x_recip_inst_name                   IN     VARCHAR2    DEFAULT NULL,
    x_recip_addr_line_1                 IN     VARCHAR2    DEFAULT NULL,
    x_recip_addr_line_2                 IN     VARCHAR2    DEFAULT NULL,
    x_recip_addr_line_3                 IN     VARCHAR2    DEFAULT NULL,
    x_recip_addr_line_4                 IN     VARCHAR2    DEFAULT NULL,
    x_recip_city                        IN     VARCHAR2    DEFAULT NULL,
    x_recip_postal_code                 IN     VARCHAR2    DEFAULT NULL,
    x_recip_state                       IN     VARCHAR2    DEFAULT NULL,
    x_recip_province                    IN     VARCHAR2    DEFAULT NULL,
    x_recip_county                      IN     VARCHAR2    DEFAULT NULL,
    x_recip_country                     IN     VARCHAR2    DEFAULT NULL,
    x_recip_fax_area_code               IN     VARCHAR2    DEFAULT NULL,
    x_recip_fax_country_code            IN     VARCHAR2    DEFAULT NULL,
    x_recip_fax_number                  IN     VARCHAR2    DEFAULT NULL,
    x_delivery_method_type              IN     VARCHAR2    DEFAULT NULL,
    x_programs_on_file                  IN     VARCHAR2    DEFAULT NULL,
    x_missing_acad_record_data_ind      IN     VARCHAR2    DEFAULT NULL,
    x_missing_academic_record_data      IN     VARCHAR2    DEFAULT NULL,
    x_send_transcript_immediately       IN     VARCHAR2    DEFAULT NULL,
    x_hold_release_of_final_grades      IN     VARCHAR2    DEFAULT NULL,
    x_fgrade_cal_type                   IN     VARCHAR2    DEFAULT NULL,
    x_fgrade_seq_num                    IN     NUMBER      DEFAULT NULL,
    x_hold_degree_expected              IN     VARCHAR2    DEFAULT NULL,
    x_deghold_cal_type                  IN     VARCHAR2    DEFAULT NULL,
    x_deghold_seq_num                   IN     NUMBER      DEFAULT NULL,
    x_hold_for_grade_chg                IN     VARCHAR2    DEFAULT NULL,
    x_special_instr                     IN     VARCHAR2    DEFAULT NULL,
    x_express_mail_type                 IN     VARCHAR2    DEFAULT NULL,
    x_express_mail_track_num            IN     VARCHAR2    DEFAULT NULL,
    x_ge_certification                  IN     VARCHAR2    DEFAULT NULL,
    x_external_comments                 IN     VARCHAR2    DEFAULT NULL,
    x_internal_comments                 IN     VARCHAR2    DEFAULT NULL,
    x_dup_requested                     IN     VARCHAR2    DEFAULT NULL,
    x_dup_req_date                      IN     DATE        DEFAULT NULL,
    x_dup_sent_date                     IN     DATE        DEFAULT NULL,
    x_enr_term_cal_type                 IN     VARCHAR2    DEFAULT NULL,
    x_enr_ci_sequence_number            IN     NUMBER      DEFAULT NULL,
    x_incl_attempted_hours              IN     VARCHAR2    DEFAULT NULL,
    x_incl_class_rank                   IN     VARCHAR2    DEFAULT NULL,
    x_incl_progresssion_status          IN     VARCHAR2    DEFAULT NULL,
    x_incl_class_standing               IN     VARCHAR2    DEFAULT NULL,
    x_incl_cum_hours_earned             IN     VARCHAR2    DEFAULT NULL,
    x_incl_gpa                          IN     VARCHAR2    DEFAULT NULL,
    x_incl_date_of_graduation           IN     VARCHAR2    DEFAULT NULL,
    x_incl_degree_dates                 IN     VARCHAR2    DEFAULT NULL,
    x_incl_degree_earned                IN     VARCHAR2    DEFAULT NULL,
    x_incl_date_of_entry                IN     VARCHAR2    DEFAULT NULL,
    x_incl_drop_withdrawal_dates        IN     VARCHAR2    DEFAULT NULL,
    x_incl_hrs_for_curr_term            IN     VARCHAR2    DEFAULT NULL,
    x_incl_majors                       IN     VARCHAR2    DEFAULT NULL,
    x_incl_last_date_of_enrollment      IN     VARCHAR2    DEFAULT NULL,
    x_incl_professional_licensure       IN     VARCHAR2    DEFAULT NULL,
    x_incl_college_affiliation          IN     VARCHAR2    DEFAULT NULL,
    x_incl_instruction_dates            IN     VARCHAR2    DEFAULT NULL,
    x_incl_usec_dates                   IN     VARCHAR2    DEFAULT NULL,
    x_incl_program_attempt              IN     VARCHAR2    DEFAULT NULL,
    x_incl_attendence_type              IN     VARCHAR2    DEFAULT NULL,
    x_incl_last_term_enrolled           IN     VARCHAR2    DEFAULT NULL,
    x_incl_ssn                          IN     VARCHAR2    DEFAULT NULL,
    x_incl_date_of_birth                IN     VARCHAR2    DEFAULT NULL,
    x_incl_disciplin_standing           IN     VARCHAR2    DEFAULT NULL,
    x_incl_no_future_term               IN     VARCHAR2    DEFAULT NULL,
    x_incl_acurat_till_copmp_dt         IN     VARCHAR2    DEFAULT NULL,
    x_incl_cant_rel_without_sign        IN     VARCHAR2    DEFAULT NULL,
    x_creation_date                     IN     DATE        DEFAULT NULL,
    x_created_by                        IN     NUMBER      DEFAULT NULL,
    x_last_update_date                  IN     DATE        DEFAULT NULL,
    x_last_updated_by                   IN     NUMBER      DEFAULT NULL,
    x_last_update_login                 IN     NUMBER      DEFAULT NULL,
    X_DOC_FEE_PER_COPY                  IN     NUMBER      DEFAULT NULL,
    X_DELIVERY_FEE                      IN     NUMBER      DEFAULT NULL,
    X_RECIP_EMAIL                       IN     VARCHAR2    DEFAULT NULL,
    x_overridden_doc_delivery_fee       IN     NUMBER      DEFAULT NULL,
    x_overridden_document_fee           IN     NUMBER      DEFAULT NULL,
    x_fee_overridden_by                 IN     NUMBER      DEFAULT NULL,
    x_fee_overridden_date               IN     DATE        DEFAULT NULL,
    x_incl_department                   IN     VARCHAR2    DEFAULT NULL,
    x_incl_field_of_stdy                IN     VARCHAR2    DEFAULT NULL,
    x_incl_attend_mode                  IN     VARCHAR2    DEFAULT NULL,
    x_incl_yop_acad_prd                 IN     VARCHAR2    DEFAULT NULL,
    x_incl_intrmsn_st_end               IN     VARCHAR2    DEFAULT NULL,
    x_incl_hnrs_lvl                     IN     VARCHAR2    DEFAULT NULL,
    x_incl_awards                       IN     VARCHAR2    DEFAULT NULL,
    x_incl_award_aim                    IN     VARCHAR2    DEFAULT NULL,
    x_incl_acad_sessions                IN     VARCHAR2    DEFAULT NULL,
    x_incl_st_end_acad_ses              IN     VARCHAR2    DEFAULT NULL,
    x_incl_hesa_num                     IN     VARCHAR2    DEFAULT NULL,
    x_incl_location                     IN     VARCHAR2    DEFAULT NULL,
    x_incl_program_type                 IN     VARCHAR2    DEFAULT NULL,
    x_incl_program_name                 IN     VARCHAR2    DEFAULT NULL,
    x_incl_prog_atmpt_stat              IN     VARCHAR2    DEFAULT NULL,
    x_incl_prog_atmpt_end               IN     VARCHAR2    DEFAULT NULL,
    x_incl_prog_atmpt_strt              IN     VARCHAR2    DEFAULT NULL,
    x_incl_req_cmplete                  IN     VARCHAR2    DEFAULT NULL,
    x_incl_expected_compl_dt            IN     VARCHAR2    DEFAULT NULL,
    x_incl_conferral_dt                 IN     VARCHAR2    DEFAULT NULL,
    x_incl_thesis_title                 IN     VARCHAR2    DEFAULT NULL,
    x_incl_program_code                 IN     VARCHAR2    DEFAULT NULL,
    x_incl_program_ver                  IN     VARCHAR2    DEFAULT NULL,
    x_incl_stud_no                      IN     VARCHAR2    DEFAULT NULL,
    x_incl_surname                      IN     VARCHAR2    DEFAULT NULL,
    x_incl_fore_name                    IN     VARCHAR2    DEFAULT NULL,
    x_incl_prev_names                   IN     VARCHAR2    DEFAULT NULL,
    x_incl_initials                     IN     VARCHAR2    DEFAULT NULL,
    x_doc_purpose_code                  IN     VARCHAR2    DEFAULT NULL,
    x_plan_id				IN     NUMBER      DEFAULT NULL,
    x_produced_by                       IN     NUMBER      DEFAULT NULL,
    x_person_id                         IN     NUMBER      DEFAULT NULL
  );

END Igs_As_Doc_Details_Pkg;

 

/
