--------------------------------------------------------
--  DDL for Package IGS_PR_RULE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_PR_RULE_PKG" AUTHID CURRENT_USER AS
/* $Header: IGSQI09S.pls 115.5 2002/11/29 03:16:08 nsidana ship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PROGRESSION_RULE_CAT in VARCHAR2,
  X_PROGRESSION_RULE_CD in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_RUL_SEQUENCE_NUMBER in NUMBER,
  X_CLOSED_IND in VARCHAR2,
  X_MESSAGE in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_ORG_ID in NUMBER
  );
procedure LOCK_ROW (
  X_ROWID in VARCHAR2,
  X_PROGRESSION_RULE_CAT in VARCHAR2,
  X_PROGRESSION_RULE_CD in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_RUL_SEQUENCE_NUMBER in NUMBER,
  X_CLOSED_IND in VARCHAR2,
  X_MESSAGE in VARCHAR2
);
procedure UPDATE_ROW (
  X_ROWID in VARCHAR2,
  X_PROGRESSION_RULE_CAT in VARCHAR2,
  X_PROGRESSION_RULE_CD in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_RUL_SEQUENCE_NUMBER in NUMBER,
  X_CLOSED_IND in VARCHAR2,
  X_MESSAGE in VARCHAR2,
  X_MODE in VARCHAR2 default 'R'
  );
procedure ADD_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PROGRESSION_RULE_CAT in VARCHAR2,
  X_PROGRESSION_RULE_CD in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_RUL_SEQUENCE_NUMBER in NUMBER,
  X_CLOSED_IND in VARCHAR2,
  X_MESSAGE in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_ORG_ID in NUMBER
  );
procedure DELETE_ROW (
  X_ROWID in VARCHAR2
);
FUNCTION Get_PK_For_Validation (
    x_progression_rule_cat IN VARCHAR2,
    x_progression_rule_cd IN VARCHAR2
    ) RETURN BOOLEAN;

  PROCEDURE GET_FK_IGS_PR_RU_CAT (
    x_progression_rule_cat IN VARCHAR2
    );

  PROCEDURE GET_FK_IGS_RU_RULE (
    x_sequence_number IN NUMBER
    );
PROCEDURE Before_DML (
    p_action IN VARCHAR2,
    x_rowid IN VARCHAR2 DEFAULT NULL,
    x_progression_rule_cat IN VARCHAR2 DEFAULT NULL,
    x_progression_rule_cd IN VARCHAR2 DEFAULT NULL,
    x_description IN VARCHAR2 DEFAULT NULL,
    x_rul_sequence_number IN NUMBER DEFAULT NULL,
    x_closed_ind IN VARCHAR2 DEFAULT NULL,
    x_message IN VARCHAR2 DEFAULT NULL,
    x_creation_date IN DATE DEFAULT NULL,
    x_created_by IN NUMBER DEFAULT NULL,
    x_last_update_date IN DATE DEFAULT NULL,
    x_last_updated_by IN NUMBER DEFAULT NULL,
    x_last_update_login IN NUMBER DEFAULT NULL,
    x_org_id IN NUMBER DEFAULT NULL
  );
PROCEDURE Check_Constraints(
	Column_Name IN VARCHAR2 DEFAULT NULL,
	Column_Value IN VARCHAR2 DEFAULT NULL
	);

end IGS_PR_RULE_PKG;

 

/
