--------------------------------------------------------
--  DDL for Package IGS_AD_PS_APINTUNTHS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_AD_PS_APINTUNTHS_PKG" AUTHID CURRENT_USER as
/* $Header: IGSAI22S.pls 115.6 2003/12/03 20:49:02 knag ship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
	X_ORG_ID in NUMBER,
  X_PERSON_ID in NUMBER,
  X_ADMISSION_APPL_NUMBER in NUMBER,
  X_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_UNIT_CD in VARCHAR2,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_UV_VERSION_NUMBER in NUMBER,
  X_CAL_TYPE in VARCHAR2,
  X_CI_SEQUENCE_NUMBER in NUMBER,
  X_LOCATION_CD in VARCHAR2,
  X_UNIT_CLASS in VARCHAR2,
  X_UNIT_MODE in VARCHAR2,
  X_ADM_UNIT_OUTCOME_STATUS in VARCHAR2,
  X_ASS_TRACKING_ID in NUMBER,
  X_RULE_WAIVED_DT in DATE,
  X_RULE_WAIVED_PERSON_ID in NUMBER,
  X_SUP_UNIT_CD in VARCHAR2,
  X_SUP_UV_VERSION_NUMBER in NUMBER,
  X_MODE in VARCHAR2 default 'R',
  x_adm_ps_appl_inst_unit_id IN NUMBER DEFAULT NULL,
  x_adm_ps_appl_inst_unithist_id IN OUT NOCOPY NUMBER
  );
procedure LOCK_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_ADMISSION_APPL_NUMBER in NUMBER,
  X_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_UNIT_CD in VARCHAR2,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_UV_VERSION_NUMBER in NUMBER,
  X_CAL_TYPE in VARCHAR2,
  X_CI_SEQUENCE_NUMBER in NUMBER,
  X_LOCATION_CD in VARCHAR2,
  X_UNIT_CLASS in VARCHAR2,
  X_UNIT_MODE in VARCHAR2,
  X_ADM_UNIT_OUTCOME_STATUS in VARCHAR2,
  X_ASS_TRACKING_ID in NUMBER,
  X_RULE_WAIVED_DT in DATE,
  X_RULE_WAIVED_PERSON_ID in NUMBER,
  X_SUP_UNIT_CD in VARCHAR2,
  X_SUP_UV_VERSION_NUMBER in NUMBER,
  x_adm_ps_appl_inst_unit_id IN NUMBER DEFAULT NULL,
  x_adm_ps_appl_inst_unithist_id IN NUMBER DEFAULT NULL
);
procedure UPDATE_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_ADMISSION_APPL_NUMBER in NUMBER,
  X_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_UNIT_CD in VARCHAR2,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_UV_VERSION_NUMBER in NUMBER,
  X_CAL_TYPE in VARCHAR2,
  X_CI_SEQUENCE_NUMBER in NUMBER,
  X_LOCATION_CD in VARCHAR2,
  X_UNIT_CLASS in VARCHAR2,
  X_UNIT_MODE in VARCHAR2,
  X_ADM_UNIT_OUTCOME_STATUS in VARCHAR2,
  X_ASS_TRACKING_ID in NUMBER,
  X_RULE_WAIVED_DT in DATE,
  X_RULE_WAIVED_PERSON_ID in NUMBER,
  X_SUP_UNIT_CD in VARCHAR2,
  X_SUP_UV_VERSION_NUMBER in NUMBER,
  X_MODE in VARCHAR2 default 'R',
  x_adm_ps_appl_inst_unit_id IN NUMBER DEFAULT NULL,
  x_adm_ps_appl_inst_unithist_id IN NUMBER DEFAULT NULL
  );
procedure ADD_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
	X_ORG_ID in NUMBER,
  X_PERSON_ID in NUMBER,
  X_ADMISSION_APPL_NUMBER in NUMBER,
  X_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_UNIT_CD in VARCHAR2,
  X_HIST_START_DT in DATE,
  X_HIST_END_DT in DATE,
  X_HIST_WHO in NUMBER,
  X_UV_VERSION_NUMBER in NUMBER,
  X_CAL_TYPE in VARCHAR2,
  X_CI_SEQUENCE_NUMBER in NUMBER,
  X_LOCATION_CD in VARCHAR2,
  X_UNIT_CLASS in VARCHAR2,
  X_UNIT_MODE in VARCHAR2,
  X_ADM_UNIT_OUTCOME_STATUS in VARCHAR2,
  X_ASS_TRACKING_ID in NUMBER,
  X_RULE_WAIVED_DT in DATE,
  X_RULE_WAIVED_PERSON_ID in NUMBER,
  X_SUP_UNIT_CD in VARCHAR2,
  X_SUP_UV_VERSION_NUMBER in NUMBER,
  X_MODE in VARCHAR2 default 'R',
  x_adm_ps_appl_inst_unit_id IN NUMBER DEFAULT NULL,
  x_adm_ps_appl_inst_unithist_id IN OUT NOCOPY NUMBER
  );
procedure DELETE_ROW (
  X_ROWID in VARCHAR2
);

FUNCTION Get_PK_For_Validation (
    x_adm_ps_appl_inst_unithist_id IN NUMBER
    )
RETURN BOOLEAN;

FUNCTION Get_UK_For_Validation (
    x_adm_ps_appl_inst_unit_id IN NUMBER,
    x_hist_start_dt IN DATE
    )
RETURN BOOLEAN;

PROCEDURE Check_constraints(
  	Column_Name 	IN	VARCHAR2 DEFAULT NULL,
	Column_Value 	IN	VARCHAR2 DEFAULT NULL
	);

PROCEDURE Before_DML (
    p_action IN VARCHAR2,
    x_rowid IN VARCHAR2 DEFAULT NULL,
		x_org_id in NUMBER DEFAULT NULL,
    x_person_id IN NUMBER DEFAULT NULL,
    x_admission_appl_number IN NUMBER DEFAULT NULL,
    x_nominated_course_cd IN VARCHAR2 DEFAULT NULL,
    x_acai_sequence_number IN NUMBER DEFAULT NULL,
    x_unit_cd IN VARCHAR2 DEFAULT NULL,
    x_hist_start_dt IN DATE DEFAULT NULL,
    x_hist_end_dt IN DATE DEFAULT NULL,
    x_hist_who IN NUMBER DEFAULT NULL,
    x_uv_version_number IN NUMBER DEFAULT NULL,
    x_cal_type IN VARCHAR2 DEFAULT NULL,
    x_ci_sequence_number IN NUMBER DEFAULT NULL,
    x_location_cd IN VARCHAR2 DEFAULT NULL,
    x_unit_class IN VARCHAR2 DEFAULT NULL,
    x_unit_mode IN VARCHAR2 DEFAULT NULL,
    x_adm_unit_outcome_status IN VARCHAR2 DEFAULT NULL,
    x_ass_tracking_id IN NUMBER DEFAULT NULL,
    x_rule_waived_dt IN DATE DEFAULT NULL,
    x_rule_waived_person_id IN NUMBER DEFAULT NULL,
    x_sup_unit_cd IN VARCHAR2 DEFAULT NULL,
    x_sup_uv_version_number IN NUMBER DEFAULT NULL,
    x_creation_date IN DATE DEFAULT NULL,
    x_created_by IN NUMBER DEFAULT NULL,
    x_last_update_date IN DATE DEFAULT NULL,
    x_last_updated_by IN NUMBER DEFAULT NULL,
    x_last_update_login IN NUMBER DEFAULT NULL,
    x_adm_ps_appl_inst_unit_id IN NUMBER DEFAULT NULL,
    x_adm_ps_appl_inst_unithist_id IN NUMBER DEFAULT NULL
  ) ;

end IGS_AD_PS_APINTUNTHS_PKG;

 

/
