--------------------------------------------------------
--  DDL for Package IGS_PE_PERS_DISABLTY_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_PE_PERS_DISABLTY_PKG" AUTHID CURRENT_USER AS
/* $Header: IGSNI15S.pls 120.0 2005/06/01 18:59:40 appldev noship $ */

------------------------------------------------------------------
-- Change History
--
-- Bug ID : 2000408
-- who      when          what
-- CDCRUZ   Sep 24,2002   New Col's added for
--                        Person DLD / Pk changed to Seq Gen Pk
------------------------------------------------------------------
 procedure INSERT_ROW (
       X_ROWID in out NOCOPY VARCHAR2,
       X_IGS_PE_PERS_DISABLTY_ID   IN  OUT NOCOPY NUMBER,
       x_PERSON_ID IN NUMBER,
       x_DISABILITY_TYPE IN VARCHAR2,
       x_CONTACT_IND IN VARCHAR2 DEFAULT NULL,
       x_SPECIAL_ALLOW_CD IN VARCHAR2 DEFAULT NULL,
       x_SUPPORT_LEVEL_CD IN VARCHAR2 DEFAULT NULL,
       x_DOCUMENTED IN VARCHAR2 DEFAULT NULL,
       x_SPECIAL_SERVICE_ID IN NUMBER DEFAULT NULL,
       x_ATTRIBUTE_CATEGORY IN VARCHAR2,
       x_ATTRIBUTE1 IN VARCHAR2,
       x_ATTRIBUTE2 IN VARCHAR2,
       x_ATTRIBUTE3 IN VARCHAR2,
       x_ATTRIBUTE4 IN VARCHAR2,
       x_ATTRIBUTE5 IN VARCHAR2,
       x_ATTRIBUTE6 IN VARCHAR2,
       x_ATTRIBUTE7 IN VARCHAR2,
       x_ATTRIBUTE8 IN VARCHAR2,
       x_ATTRIBUTE9 IN VARCHAR2,
       x_ATTRIBUTE10 IN VARCHAR2,
       x_ATTRIBUTE11 IN VARCHAR2,
       x_ATTRIBUTE12 IN VARCHAR2,
       x_ATTRIBUTE13 IN VARCHAR2,
       x_ATTRIBUTE14 IN VARCHAR2,
       x_ATTRIBUTE15 IN VARCHAR2,
       x_ATTRIBUTE16 IN VARCHAR2,
       x_ATTRIBUTE17 IN VARCHAR2,
       x_ATTRIBUTE18 IN VARCHAR2,
       x_ATTRIBUTE19 IN VARCHAR2,
       x_ATTRIBUTE20 IN VARCHAR2,
       X_ELIG_EARLY_REG_IND        IN   VARCHAR2 DEFAULT NULL,
       X_START_DATE                IN   DATE DEFAULT NULL,
       X_END_DATE                  IN   DATE DEFAULT NULL,
       X_INFO_SOURCE               IN   VARCHAR2 DEFAULT NULL,
       X_INTERVIEWER_ID            IN   NUMBER DEFAULT NULL,
       X_INTERVIEWER_DATE          IN   DATE DEFAULT NULL,
      X_MODE in VARCHAR2 default 'R'
  );

 procedure LOCK_ROW (
      X_ROWID in  VARCHAR2,
       X_IGS_PE_PERS_DISABLTY_ID   IN   NUMBER,
       x_PERSON_ID IN NUMBER,
       x_DISABILITY_TYPE IN VARCHAR2,
       x_CONTACT_IND IN VARCHAR2  DEFAULT NULL,
       x_SPECIAL_ALLOW_CD IN VARCHAR2 DEFAULT NULL,
       x_SUPPORT_LEVEL_CD IN VARCHAR2 DEFAULT NULL,
       x_DOCUMENTED IN VARCHAR2 DEFAULT NULL,
       x_SPECIAL_SERVICE_ID IN NUMBER  DEFAULT NULL,
       x_ATTRIBUTE_CATEGORY IN VARCHAR2,
       x_ATTRIBUTE1 IN VARCHAR2,
       x_ATTRIBUTE2 IN VARCHAR2,
       x_ATTRIBUTE3 IN VARCHAR2,
       x_ATTRIBUTE4 IN VARCHAR2,
       x_ATTRIBUTE5 IN VARCHAR2,
       x_ATTRIBUTE6 IN VARCHAR2,
       x_ATTRIBUTE7 IN VARCHAR2,
       x_ATTRIBUTE8 IN VARCHAR2,
       x_ATTRIBUTE9 IN VARCHAR2,
       x_ATTRIBUTE10 IN VARCHAR2,
       x_ATTRIBUTE11 IN VARCHAR2,
       x_ATTRIBUTE12 IN VARCHAR2,
       x_ATTRIBUTE13 IN VARCHAR2,
       x_ATTRIBUTE14 IN VARCHAR2,
       x_ATTRIBUTE15 IN VARCHAR2,
       x_ATTRIBUTE16 IN VARCHAR2,
       x_ATTRIBUTE17 IN VARCHAR2,
       x_ATTRIBUTE18 IN VARCHAR2,
       x_ATTRIBUTE19 IN VARCHAR2,
       x_ATTRIBUTE20 IN VARCHAR2 ,
       X_ELIG_EARLY_REG_IND        IN   VARCHAR2 DEFAULT NULL,
       X_START_DATE                IN   DATE DEFAULT NULL,
       X_END_DATE                  IN   DATE DEFAULT NULL,
       X_INFO_SOURCE               IN   VARCHAR2 DEFAULT NULL,
       X_INTERVIEWER_ID            IN   NUMBER DEFAULT NULL,
       X_INTERVIEWER_DATE          IN   DATE DEFAULT NULL
              );

 procedure UPDATE_ROW (
      X_ROWID in  VARCHAR2,
      X_IGS_PE_PERS_DISABLTY_ID   IN   NUMBER,
       x_PERSON_ID IN NUMBER,
       x_DISABILITY_TYPE IN VARCHAR2,
       x_CONTACT_IND IN VARCHAR2  DEFAULT NULL,
       x_SPECIAL_ALLOW_CD IN VARCHAR2 DEFAULT NULL,
       x_SUPPORT_LEVEL_CD IN VARCHAR2 DEFAULT NULL,
       x_DOCUMENTED IN VARCHAR2  DEFAULT NULL,
       x_SPECIAL_SERVICE_ID IN NUMBER  DEFAULT NULL,
       x_ATTRIBUTE_CATEGORY IN VARCHAR2,
       x_ATTRIBUTE1 IN VARCHAR2,
       x_ATTRIBUTE2 IN VARCHAR2,
       x_ATTRIBUTE3 IN VARCHAR2,
       x_ATTRIBUTE4 IN VARCHAR2,
       x_ATTRIBUTE5 IN VARCHAR2,
       x_ATTRIBUTE6 IN VARCHAR2,
       x_ATTRIBUTE7 IN VARCHAR2,
       x_ATTRIBUTE8 IN VARCHAR2,
       x_ATTRIBUTE9 IN VARCHAR2,
       x_ATTRIBUTE10 IN VARCHAR2,
       x_ATTRIBUTE11 IN VARCHAR2,
       x_ATTRIBUTE12 IN VARCHAR2,
       x_ATTRIBUTE13 IN VARCHAR2,
       x_ATTRIBUTE14 IN VARCHAR2,
       x_ATTRIBUTE15 IN VARCHAR2,
       x_ATTRIBUTE16 IN VARCHAR2,
       x_ATTRIBUTE17 IN VARCHAR2,
       x_ATTRIBUTE18 IN VARCHAR2,
       x_ATTRIBUTE19 IN VARCHAR2,
       x_ATTRIBUTE20 IN VARCHAR2,
       X_ELIG_EARLY_REG_IND        IN   VARCHAR2 DEFAULT NULL,
       X_START_DATE                IN   DATE DEFAULT NULL,
       X_END_DATE                  IN   DATE DEFAULT NULL,
       X_INFO_SOURCE               IN   VARCHAR2 DEFAULT NULL,
       X_INTERVIEWER_ID            IN   NUMBER DEFAULT NULL,
       X_INTERVIEWER_DATE          IN   DATE DEFAULT NULL,
      X_MODE in VARCHAR2 default 'R'
  );

 procedure ADD_ROW (
      X_ROWID in out NOCOPY VARCHAR2,
      X_IGS_PE_PERS_DISABLTY_ID   IN  OUT NOCOPY NUMBER,
       x_PERSON_ID IN NUMBER,
       x_DISABILITY_TYPE IN VARCHAR2,
       x_CONTACT_IND IN VARCHAR2  DEFAULT NULL,
       x_SPECIAL_ALLOW_CD IN VARCHAR2 DEFAULT NULL,
       x_SUPPORT_LEVEL_CD IN VARCHAR2 DEFAULT NULL,
       x_DOCUMENTED IN VARCHAR2 DEFAULT NULL,
       x_SPECIAL_SERVICE_ID IN NUMBER DEFAULT NULL,
       x_ATTRIBUTE_CATEGORY IN VARCHAR2,
       x_ATTRIBUTE1 IN VARCHAR2,
       x_ATTRIBUTE2 IN VARCHAR2,
       x_ATTRIBUTE3 IN VARCHAR2,
       x_ATTRIBUTE4 IN VARCHAR2,
       x_ATTRIBUTE5 IN VARCHAR2,
       x_ATTRIBUTE6 IN VARCHAR2,
       x_ATTRIBUTE7 IN VARCHAR2,
       x_ATTRIBUTE8 IN VARCHAR2,
       x_ATTRIBUTE9 IN VARCHAR2,
       x_ATTRIBUTE10 IN VARCHAR2,
       x_ATTRIBUTE11 IN VARCHAR2,
       x_ATTRIBUTE12 IN VARCHAR2,
       x_ATTRIBUTE13 IN VARCHAR2,
       x_ATTRIBUTE14 IN VARCHAR2,
       x_ATTRIBUTE15 IN VARCHAR2,
       x_ATTRIBUTE16 IN VARCHAR2,
       x_ATTRIBUTE17 IN VARCHAR2,
       x_ATTRIBUTE18 IN VARCHAR2,
       x_ATTRIBUTE19 IN VARCHAR2,
       x_ATTRIBUTE20 IN VARCHAR2,
       X_ELIG_EARLY_REG_IND        IN   VARCHAR2 DEFAULT NULL,
       X_START_DATE                IN   DATE DEFAULT NULL,
       X_END_DATE                  IN   DATE DEFAULT NULL,
       X_INFO_SOURCE               IN   VARCHAR2 DEFAULT NULL,
       X_INTERVIEWER_ID            IN   NUMBER DEFAULT NULL,
       X_INTERVIEWER_DATE          IN   DATE DEFAULT NULL,
      X_MODE in VARCHAR2 default 'R'
  ) ;

procedure DELETE_ROW (
  X_ROWID in VARCHAR2,
  x_mode IN VARCHAR2 DEFAULT 'R'
) ;

  FUNCTION get_uk_for_validation (
    x_person_id                         IN     NUMBER,
    x_disability_type                   IN     VARCHAR2,
    x_start_date                        IN     DATE
  ) RETURN BOOLEAN;

  FUNCTION Get_PK_For_Validation (
       X_IGS_PE_PERS_DISABLTY_ID IN NUMBER
    ) RETURN BOOLEAN ;

  PROCEDURE Get_FK_Igs_Pe_Person (
    x_person_id IN NUMBER
    );

  PROCEDURE Get_FK_Igs_Ad_Disbl_Type (
    x_disability_type IN VARCHAR2
    );


  PROCEDURE Check_Constraints (
		 Column_Name IN VARCHAR2  DEFAULT NULL,
		 Column_Value IN VARCHAR2  DEFAULT NULL ) ;
  PROCEDURE Before_DML (
    p_action IN VARCHAR2,
    x_rowid IN VARCHAR2 DEFAULT NULL,
    X_IGS_PE_PERS_DISABLTY_ID   IN   NUMBER DEFAULT NULL,
    x_person_id IN NUMBER DEFAULT NULL,
    x_disability_type IN VARCHAR2 DEFAULT NULL,
    x_contact_ind IN VARCHAR2 DEFAULT NULL,
    x_special_allow_cd IN VARCHAR2 DEFAULT NULL,
    x_SUPPORT_LEVEL_CD IN VARCHAR2 DEFAULT NULL,
    x_documented IN VARCHAR2 DEFAULT NULL,
    x_special_service_id IN NUMBER DEFAULT NULL,
    x_attribute_category IN VARCHAR2 DEFAULT NULL,
    x_attribute1 IN VARCHAR2 DEFAULT NULL,
    x_attribute2 IN VARCHAR2 DEFAULT NULL,
    x_attribute3 IN VARCHAR2 DEFAULT NULL,
    x_attribute4 IN VARCHAR2 DEFAULT NULL,
    x_attribute5 IN VARCHAR2 DEFAULT NULL,
    x_attribute6 IN VARCHAR2 DEFAULT NULL,
    x_attribute7 IN VARCHAR2 DEFAULT NULL,
    x_attribute8 IN VARCHAR2 DEFAULT NULL,
    x_attribute9 IN VARCHAR2 DEFAULT NULL,
    x_attribute10 IN VARCHAR2 DEFAULT NULL,
    x_attribute11 IN VARCHAR2 DEFAULT NULL,
    x_attribute12 IN VARCHAR2 DEFAULT NULL,
    x_attribute13 IN VARCHAR2 DEFAULT NULL,
    x_attribute14 IN VARCHAR2 DEFAULT NULL,
    x_attribute15 IN VARCHAR2 DEFAULT NULL,
    x_attribute16 IN VARCHAR2 DEFAULT NULL,
    x_attribute17 IN VARCHAR2 DEFAULT NULL,
    x_attribute18 IN VARCHAR2 DEFAULT NULL,
    x_attribute19 IN VARCHAR2 DEFAULT NULL,
    x_attribute20 IN VARCHAR2 DEFAULT NULL,
    X_ELIG_EARLY_REG_IND        IN   VARCHAR2 DEFAULT NULL,
    X_START_DATE                IN   DATE DEFAULT NULL,
    X_END_DATE                  IN   DATE DEFAULT NULL,
    X_INFO_SOURCE               IN   VARCHAR2 DEFAULT NULL,
    X_INTERVIEWER_ID            IN   NUMBER DEFAULT NULL,
    X_INTERVIEWER_DATE          IN   DATE DEFAULT NULL,
    x_creation_date IN DATE DEFAULT NULL,
    x_created_by IN NUMBER DEFAULT NULL,
    x_last_update_date IN DATE DEFAULT NULL,
    x_last_updated_by IN NUMBER DEFAULT NULL,
    x_last_update_login IN NUMBER DEFAULT NULL
 );
END igs_pe_pers_disablty_pkg;

 

/
