--------------------------------------------------------
--  DDL for Package IGS_AD_AUS_SEC_EDU_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_AD_AUS_SEC_EDU_PKG" AUTHID CURRENT_USER as
/* $Header: IGSAI39S.pls 115.4 2002/11/28 22:04:43 nsidana ship $ */

procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_STATE_CD in VARCHAR2,
  X_RESULT_OBTAINED_YR in NUMBER,
  X_SCORE in NUMBER,
  X_AUS_SCNDRY_EDU_ASS_TYPE in VARCHAR2,
  X_CANDIDATE_NUMBER in NUMBER,
  X_SECONDARY_SCHOOL_CD in VARCHAR2,
  X_MODE in VARCHAR2 default 'R'
  );
procedure LOCK_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_STATE_CD in VARCHAR2,
  X_RESULT_OBTAINED_YR in NUMBER,
  X_SCORE in NUMBER,
  X_AUS_SCNDRY_EDU_ASS_TYPE in VARCHAR2,
  X_CANDIDATE_NUMBER in NUMBER,
  X_SECONDARY_SCHOOL_CD in VARCHAR2
);
procedure UPDATE_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_STATE_CD in VARCHAR2,
  X_RESULT_OBTAINED_YR in NUMBER,
  X_SCORE in NUMBER,
  X_AUS_SCNDRY_EDU_ASS_TYPE in VARCHAR2,
  X_CANDIDATE_NUMBER in NUMBER,
  X_SECONDARY_SCHOOL_CD in VARCHAR2,
  X_MODE in VARCHAR2 default 'R'
  );
procedure ADD_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_STATE_CD in VARCHAR2,
  X_RESULT_OBTAINED_YR in NUMBER,
  X_SCORE in NUMBER,
  X_AUS_SCNDRY_EDU_ASS_TYPE in VARCHAR2,
  X_CANDIDATE_NUMBER in NUMBER,
  X_SECONDARY_SCHOOL_CD in VARCHAR2,
  X_MODE in VARCHAR2 default 'R'
  );
procedure DELETE_ROW (
  X_ROWID in VARCHAR2
);

Function Get_PK_For_Validation (
    x_person_id IN NUMBER,
    x_sequence_number IN NUMBER)
RETURN BOOLEAN;

  PROCEDURE Before_DML (
    p_action IN VARCHAR2,
    x_rowid IN VARCHAR2 DEFAULT NULL,
    x_person_id IN NUMBER DEFAULT NULL,
    x_sequence_number IN NUMBER DEFAULT NULL,
    x_state_cd IN VARCHAR2 DEFAULT NULL,
    x_result_obtained_yr IN NUMBER DEFAULT NULL,
    x_score IN NUMBER DEFAULT NULL,
    x_aus_scndry_edu_ass_type IN VARCHAR2 DEFAULT NULL,
    x_candidate_number IN NUMBER DEFAULT NULL,
    x_secondary_school_cd IN VARCHAR2 DEFAULT NULL,
    x_creation_date IN DATE DEFAULT NULL,
    x_created_by IN NUMBER DEFAULT NULL,
    x_last_update_date IN DATE DEFAULT NULL,
    x_last_updated_by IN NUMBER DEFAULT NULL,
    x_last_update_login IN NUMBER DEFAULT NULL
  );

PROCEDURE Check_Constraints (
   Column_Name	IN	VARCHAR2	DEFAULT NULL,
   Column_Value 	IN	VARCHAR2	DEFAULT NULL
);


PROCEDURE GET_FK_IGS_AD_AUSE_ED_AS_TY (
    x_aus_scndry_edu_ass_type IN VARCHAR2
    );

PROCEDURE GET_FK_IGS_AD_AUS_SEC_ED_SC (
    x_secondary_school_cd IN VARCHAR2
    );

PROCEDURE GET_FK_IGS_PE_PERSON (
    x_person_id IN NUMBER
    );

end IGS_AD_AUS_SEC_EDU_PKG;

 

/
