--------------------------------------------------------
--  DDL for Package IGS_RE_CANDIDATURE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IGS_RE_CANDIDATURE_PKG" AUTHID CURRENT_USER as
/* $Header: IGSRI01S.pls 120.0 2005/06/01 15:59:37 appldev noship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_SCA_COURSE_CD in VARCHAR2,
  X_ACAI_ADMISSION_APPL_NUMBER in NUMBER,
  X_ACAI_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_ATTENDANCE_PERCENTAGE in NUMBER,
  X_GOVT_TYPE_OF_ACTIVITY_CD in VARCHAR2,
  X_MAX_SUBMISSION_DT in DATE,
  X_MIN_SUBMISSION_DT in DATE,
  X_RESEARCH_TOPIC in VARCHAR2,
  X_INDUSTRY_LINKS in VARCHAR2,
  X_MODE in VARCHAR2 default 'R' ,
  X_ORG_ID in NUMBER
  );
procedure LOCK_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_SCA_COURSE_CD in VARCHAR2,
  X_ACAI_ADMISSION_APPL_NUMBER in NUMBER,
  X_ACAI_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_ATTENDANCE_PERCENTAGE in NUMBER,
  X_GOVT_TYPE_OF_ACTIVITY_CD in VARCHAR2,
  X_MAX_SUBMISSION_DT in DATE,
  X_MIN_SUBMISSION_DT in DATE,
  X_RESEARCH_TOPIC in VARCHAR2,
  X_INDUSTRY_LINKS in VARCHAR2
);
procedure UPDATE_ROW (
  X_ROWID in VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_SCA_COURSE_CD in VARCHAR2,
  X_ACAI_ADMISSION_APPL_NUMBER in NUMBER,
  X_ACAI_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_ATTENDANCE_PERCENTAGE in NUMBER,
  X_GOVT_TYPE_OF_ACTIVITY_CD in VARCHAR2,
  X_MAX_SUBMISSION_DT in DATE,
  X_MIN_SUBMISSION_DT in DATE,
  X_RESEARCH_TOPIC in VARCHAR2,
  X_INDUSTRY_LINKS in VARCHAR2,
  X_MODE in VARCHAR2 default 'R'
  );
procedure ADD_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_PERSON_ID in NUMBER,
  X_SEQUENCE_NUMBER in NUMBER,
  X_SCA_COURSE_CD in VARCHAR2,
  X_ACAI_ADMISSION_APPL_NUMBER in NUMBER,
  X_ACAI_NOMINATED_COURSE_CD in VARCHAR2,
  X_ACAI_SEQUENCE_NUMBER in NUMBER,
  X_ATTENDANCE_PERCENTAGE in NUMBER,
  X_GOVT_TYPE_OF_ACTIVITY_CD in VARCHAR2,
  X_MAX_SUBMISSION_DT in DATE,
  X_MIN_SUBMISSION_DT in DATE,
  X_RESEARCH_TOPIC in VARCHAR2,
  X_INDUSTRY_LINKS in VARCHAR2,
  X_MODE in VARCHAR2 default 'R',
  X_ORG_ID in NUMBER
  );
procedure DELETE_ROW (
  X_ROWID in VARCHAR2,
  x_mode IN VARCHAR2 DEFAULT 'R'
  );

  FUNCTION Get_PK_For_Validation (
    x_person_id IN NUMBER,
    x_sequence_number IN NUMBER
    )
  RETURN BOOLEAN ;

  PROCEDURE GET_FK_IGS_AD_PS_APPL_INST (
    x_person_id IN NUMBER,
    x_admission_appl_number IN NUMBER,
    x_nominated_course_cd IN VARCHAR2,
    x_sequence_number IN NUMBER
    );

  PROCEDURE GET_FK_IGS_RE_GV_TOA_CLS_CD (
    x_govt_toa_class_cd IN VARCHAR2
    );

  PROCEDURE GET_FK_IGS_PE_PERSON (
    x_person_id IN NUMBER
    );

  PROCEDURE GET_FK_IGS_EN_STDNT_PS_ATT (
    x_person_id IN NUMBER,
    x_course_cd IN VARCHAR2
    );

 PROCEDURE Check_Constraints (
  Column_Name in VARCHAR2 DEFAULT NULL ,
  Column_Value in VARCHAR2 DEFAULT NULL
  );

  PROCEDURE Before_DML (
    p_action IN VARCHAR2,
    x_rowid IN VARCHAR2 DEFAULT NULL,
    x_industry_links IN VARCHAR2 DEFAULT NULL,
    x_person_id IN NUMBER DEFAULT NULL,
    x_sequence_number IN NUMBER DEFAULT NULL,
    x_sca_course_cd IN VARCHAR2 DEFAULT NULL,
    x_acai_admission_appl_number IN NUMBER DEFAULT NULL,
    x_acai_nominated_course_cd IN VARCHAR2 DEFAULT NULL,
    x_acai_sequence_number IN NUMBER DEFAULT NULL,
    x_attendance_percentage IN NUMBER DEFAULT NULL,
    x_govt_type_of_activity_cd IN VARCHAR2 DEFAULT NULL,
    x_max_submission_dt IN DATE DEFAULT NULL,
    x_min_submission_dt IN DATE DEFAULT NULL,
    x_research_topic IN VARCHAR2 DEFAULT NULL,
    x_creation_date IN DATE DEFAULT NULL,
    x_created_by IN NUMBER DEFAULT NULL,
    x_last_update_date IN DATE DEFAULT NULL,
    x_last_updated_by IN NUMBER DEFAULT NULL,
    x_last_update_login IN NUMBER DEFAULT NULL,
    X_ORG_ID in NUMBER DEFAULT NULL
  );


end IGS_RE_CANDIDATURE_PKG;

 

/
