--------------------------------------------------------
--  DDL for Package INV_INVIRSLO_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."INV_INVIRSLO_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: INVIRSLOS.pls 120.2 2008/01/08 06:18:32 dwkrishn noship $ */
  P_ORG_ID NUMBER;

  P_CONC_REQUEST_ID NUMBER := 0;

  P_STRUCT_NUM NUMBER;

  P_CONDITION VARCHAR2(40);

  P_ITEM_FLEX VARCHAR2(900);

  P_CAT_FLEX VARCHAR2(900);

  P_CAT_STRUCT_NUM NUMBER;

  P_BREAK_ID NUMBER;

  P_CAT_SET_ID NUMBER;

  P_CUTOFF_DATE DATE;

  CP_CUTOFF_DATE varchar2(20);

  P_QTY_PRECISION NUMBER;

  P_SUBINV_LO VARCHAR2(10);

  P_SUBINV_HI VARCHAR2(10);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION C_CAT_SET_NAMEFORMULA RETURN VARCHAR2;

  FUNCTION C_SUBINV_WHEREFORMULA RETURN VARCHAR2;

  FUNCTION C_ITEM_PADFORMULA(C_ITEM_PAD IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION BEFOREPFORM RETURN BOOLEAN;

END INV_INVIRSLO_XMLP_PKG;


/
