--------------------------------------------------------
--  DDL for Package INV_INVIRDST_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."INV_INVIRDST_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: INVIRDSTS.pls 120.2 2008/01/08 06:38:44 dwkrishn noship $ */
  P_STATUS_HI VARCHAR2(30);

  P_STATUS_LO VARCHAR2(30);

  P_CONC_REQUEST_ID NUMBER := 0;

  FUNCTION C_WHEREFORMULA RETURN VARCHAR2;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

END INV_INVIRDST_XMLP_PKG;


/
