--------------------------------------------------------
--  DDL for Package INV_INVARPTP_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."INV_INVARPTP_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: INVARPTPS.pls 120.1 2007/12/25 10:10:51 dwkrishn noship $ */
  P_PHYSICAL NUMBER;
  P_SUBINVENTORY VARCHAR2(40);
  P_SORT_ID NUMBER;
  P_ITEM_FLEXDATA VARCHAR2(480);
  P_LOC_FLEXDATA VARCHAR2(480);
  P_ITEM_STRUCT NUMBER;
  P_LOC_STRUCT VARCHAR2(32767);
  P_CONC_REQUEST_ID NUMBER := 0;
  P_ORG_ID NUMBER;
  P_RANGE NUMBER;
  P_TAG_LO VARCHAR2(40);
  P_TAG_HI VARCHAR2(40);
  P_ORDER_BY VARCHAR2(480);
  P_RANGE_SQL VARCHAR2(4800) := '1=1';
  P_ITEM_ORDERBY VARCHAR2(480);
  P_LOC_ORDERBY VARCHAR2(480);
  P_RANGE_FLEX VARCHAR2(4800);
  P_LOC_LO VARCHAR2(40);
  P_LOC_HI VARCHAR2(40);
  P_ITEM_LO VARCHAR2(40);
  P_ITEM_HI VARCHAR2(40);
  P_WMS_INSTALLED VARCHAR2(5) := 'FALSE';
  FUNCTION AFTERREPORT RETURN BOOLEAN;
  FUNCTION BEFOREREPORT RETURN BOOLEAN;
  PROCEDURE WMS_INSTALLED;
  FUNCTION CF_PARENT_LPNFORMULA(PARENT_LPN IN NUMBER) RETURN CHAR;
  FUNCTION GET_LPN(P_LPN_ID IN NUMBER) RETURN VARCHAR2;
  FUNCTION CF_OUTERMOST_LPNFORMULA(OUTERMOST_LPN IN NUMBER
                                  ,PARENT_LPN IN NUMBER) RETURN CHAR;
  FUNCTION CF_COST_GROUPFORMULA(COST_GROUP_ID_1 IN NUMBER) RETURN CHAR;
END INV_INVARPTP_XMLP_PKG;


/
