--------------------------------------------------------
--  DDL for Package INV_INVIRSIQ_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."INV_INVIRSIQ_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: INVIRSIQS.pls 120.1 2007/12/25 10:32:34 dwkrishn noship $ */
  P_CONC_REQUEST_ID NUMBER := 0;
  qty_precision VARCHAR2(15000);
  P_STRUCT_NUM VARCHAR2(1500);

  P_ITEM_FLEXDATA VARCHAR2(300);

  P_ITEM_WHERE VARCHAR2(600);

  P_ITEM_ORDER_BY VARCHAR2(800);

  P_ITEM_LO VARCHAR2(820);

  P_ITEM_HI VARCHAR2(820);

  P_QTY_PRECISION NUMBER;

  P_TRACE_FLAG NUMBER;

  P_OPTIMIZER_CODE NUMBER;

  P_ORGANIZATION_ID VARCHAR2(40);

  P_SUBINV_LO VARCHAR2(10);

  P_SUBINV_HI VARCHAR2(10);

  P_LOC_FLEXDATA VARCHAR2(2600);

  FUNCTION P_STRUCT_NUMVALIDTRIGGER RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION WHERE_SUBINV RETURN VARCHAR2;

  FUNCTION CF_ROUNDEDQTYFORMULA(C_SUM_ITEM_QTY IN NUMBER) RETURN NUMBER;

END INV_INVIRSIQ_XMLP_PKG;


/
