--------------------------------------------------------
--  DDL for Package IRC_POSTING_CONTENT_BE2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."IRC_POSTING_CONTENT_BE2" AUTHID CURRENT_USER as 
--Code generated on 29/08/2013 09:58:20
/* $Header: hrapiwfe.pkb 120.4.12010000.2 2008/09/29 12:54:07 srgnanas ship $*/
procedure update_posting_content_a (
p_posting_content_id           number,
p_display_manager_info         varchar2,
p_display_recruiter_info       varchar2,
p_language_code                varchar2,
p_name                         varchar2,
p_org_name                     varchar2,
p_org_description              varchar2,
p_job_title                    varchar2,
p_brief_description            varchar2,
p_detailed_description         varchar2,
p_job_requirements             varchar2,
p_additional_details           varchar2,
p_how_to_apply                 varchar2,
p_benefit_info                 varchar2,
p_image_url                    varchar2,
p_alt_image_url                varchar2,
p_attribute_category           varchar2,
p_attribute1                   varchar2,
p_attribute2                   varchar2,
p_attribute3                   varchar2,
p_attribute4                   varchar2,
p_attribute5                   varchar2,
p_attribute6                   varchar2,
p_attribute7                   varchar2,
p_attribute8                   varchar2,
p_attribute9                   varchar2,
p_attribute10                  varchar2,
p_attribute11                  varchar2,
p_attribute12                  varchar2,
p_attribute13                  varchar2,
p_attribute14                  varchar2,
p_attribute15                  varchar2,
p_attribute16                  varchar2,
p_attribute17                  varchar2,
p_attribute18                  varchar2,
p_attribute19                  varchar2,
p_attribute20                  varchar2,
p_attribute21                  varchar2,
p_attribute22                  varchar2,
p_attribute23                  varchar2,
p_attribute24                  varchar2,
p_attribute25                  varchar2,
p_attribute26                  varchar2,
p_attribute27                  varchar2,
p_attribute28                  varchar2,
p_attribute29                  varchar2,
p_attribute30                  varchar2,
p_ipc_information_category     varchar2,
p_ipc_information1             varchar2,
p_ipc_information2             varchar2,
p_ipc_information3             varchar2,
p_ipc_information4             varchar2,
p_ipc_information5             varchar2,
p_ipc_information6             varchar2,
p_ipc_information7             varchar2,
p_ipc_information8             varchar2,
p_ipc_information9             varchar2,
p_ipc_information10            varchar2,
p_ipc_information11            varchar2,
p_ipc_information12            varchar2,
p_ipc_information13            varchar2,
p_ipc_information14            varchar2,
p_ipc_information15            varchar2,
p_ipc_information16            varchar2,
p_ipc_information17            varchar2,
p_ipc_information18            varchar2,
p_ipc_information19            varchar2,
p_ipc_information20            varchar2,
p_ipc_information21            varchar2,
p_ipc_information22            varchar2,
p_ipc_information23            varchar2,
p_ipc_information24            varchar2,
p_ipc_information25            varchar2,
p_ipc_information26            varchar2,
p_ipc_information27            varchar2,
p_ipc_information28            varchar2,
p_ipc_information29            varchar2,
p_ipc_information30            varchar2,
p_object_version_number        number,
p_date_approved                date);
end irc_posting_content_be2;

/
