--------------------------------------------------------
--  DDL for Package ITA_SETUP_GROUPS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ITA_SETUP_GROUPS_PKG" AUTHID CURRENT_USER as
/* $Header: itastgrs.pls 120.2 2006/01/17 00:22:20 adixit noship $ */
procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_SETUP_GROUP_CODE in VARCHAR2,
  X_TABLE_ID in NUMBER,
  X_TABLE_APP_ID in NUMBER,
  X_CONTEXT_PARAMETER_CODE in VARCHAR2,
  X_CONTEXT_PARAMETER_CODE2 in VARCHAR2,
  X_HIERARCHY_LEVEL in VARCHAR2,
  X_AUDIT_START_DATE in DATE,
  X_AUDIT_END_DATE in DATE,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SETUP_GROUP_NAME in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
  );
procedure LOCK_ROW (
  X_SETUP_GROUP_CODE in VARCHAR2,
  X_TABLE_ID in NUMBER,
  X_TABLE_APP_ID in NUMBER,
  X_CONTEXT_PARAMETER_CODE in VARCHAR2,
  X_CONTEXT_PARAMETER_CODE2 in VARCHAR2,
  X_HIERARCHY_LEVEL in VARCHAR2,
  X_AUDIT_START_DATE in DATE,
  X_AUDIT_END_DATE in DATE,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SETUP_GROUP_NAME in VARCHAR2
);
procedure UPDATE_ROW (
  X_SETUP_GROUP_CODE in VARCHAR2,
  X_TABLE_ID in NUMBER,
  X_TABLE_APP_ID in NUMBER,
  X_CONTEXT_PARAMETER_CODE in VARCHAR2,
  X_CONTEXT_PARAMETER_CODE2 in VARCHAR2,
  X_HIERARCHY_LEVEL in VARCHAR2,
  X_AUDIT_START_DATE in DATE,
  X_AUDIT_END_DATE in DATE,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SETUP_GROUP_NAME in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_SETUP_GROUP_CODE in VARCHAR2
);
procedure ADD_LANGUAGE;

procedure LOAD_ROW (
  X_SETUP_GROUP_CODE in VARCHAR2,
  X_TABLE_NAME in VARCHAR2,
  X_TABLE_APP_SHORT_NAME in VARCHAR2,
  X_CONTEXT_PARAMETER_CODE in VARCHAR2,
  X_CONTEXT_PARAMETER_CODE2 in VARCHAR2,
  X_AUDIT_END_DATE in DATE,
  X_HIERARCHY_LEVEL in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SETUP_GROUP_NAME in VARCHAR2,
  X_LAST_UPDATE_DATE in VARCHAR2,
  X_OWNER in VARCHAR2,
  X_CUSTOM_MODE IN VARCHAR2);

procedure TRANSLATE_ROW (
  X_SETUP_GROUP_CODE in VARCHAR2,
  X_TABLE_NAME in VARCHAR2,
  X_TABLE_APP_SHORT_NAME in VARCHAR2,
  X_CONTEXT_PARAMETER_CODE in VARCHAR2,
  X_CONTEXT_PARAMETER_CODE2 in VARCHAR2,
  X_AUDIT_END_DATE in DATE,
  X_HIERARCHY_LEVEL in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SETUP_GROUP_NAME in VARCHAR2,
  X_LAST_UPDATE_DATE in VARCHAR2,
  X_OWNER in VARCHAR2,
  X_CUSTOM_MODE IN VARCHAR2);

end ITA_SETUP_GROUPS_PKG;

 

/
