--------------------------------------------------------
--  DDL for Package JA_JAINMCENCG_EXC_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JA_JAINMCENCG_EXC_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: JAINMCENCG_EXCS.pls 120.1 2007/12/25 16:23:07 dwkrishn noship $ */
  /* $Header: JAINMCENCG_EXCS.pls 120.1 2007/12/25 16:23:07 dwkrishn noship $ */
  P_ORGANIZATION_ID NUMBER;

  P_LOCATION_ID NUMBER;

  P_TRN_FROM_DATE DATE;

  P_TRN_TO_DATE DATE;

  P_ADDRESS_LINE_1 VARCHAR2(240);

  P_ADDRESS_LINE_2 VARCHAR2(240);

  P_ADDRESS_LINE_3 VARCHAR2(240);

  P_CIRCLE VARCHAR2(50);

  P_COLLECT VARCHAR2(50);

  P_DESCRIPTION VARCHAR2(240);

  P_EC_CODE VARCHAR2(50);

  P_ORGANIZATION_NAME VARCHAR2(240);

  P_RANGE VARCHAR2(50);

  P_DIVISION VARCHAR2(50);

  P_CONC_REQUEST_ID NUMBER;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION CF_ASSESABLEVALUEFORMULA(RECEIPT_ID IN VARCHAR2) RETURN NUMBER;

  FUNCTION CF_QTYFORMULAFORMULA(RECEIPT_ID IN VARCHAR2
                               ,REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

END JA_JAINMCENCG_EXC_XMLP_PKG;



/
