--------------------------------------------------------
--  DDL for Package JA_JAINJVR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JA_JAINJVR_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: JAINJVRS.pls 120.1 2007/12/25 16:22:22 dwkrishn noship $ */
  P_FROM_DATE DATE;

  LP_FROM_DATE varchar2(30);

  P_TO_DATE DATE;

  LP_TO_DATE varchar2(30);

  P_JV_NO NUMBER;

  P_SOB_ID NUMBER;

  P_SOURCE VARCHAR2(25);

  P_CHART_OF_ACCTS_ID NUMBER;

  P_COLUMN_VALUE VARCHAR2(30);

  LP_COLUMN_VALUE VARCHAR2(30);

  P_CONC_REQUEST_ID NUMBER;

  P_SELECTED_JV_NO VARCHAR2(1000):=' ';

  FUNCTION CF_ACCOUNTFORMULA(CODE_COMBINATION_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_SOB_NAMEFORMULA RETURN VARCHAR2;

  FUNCTION CF_ACCTS_DESCFORMULA(CODE_COMBINATION_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION M_2_GRPFRFORMATTRIGGER RETURN Number;

END JA_JAINJVR_XMLP_PKG;



/
