--------------------------------------------------------
--  DDL for Package JA_JAINPLA_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JA_JAINPLA_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: JAINPLAS.pls 120.1 2007/12/25 16:24:25 dwkrishn noship $ */
  P_AED_OPEN_BAL NUMBER;

  P_BED_OPEN_BAL NUMBER;

  P_FIRST_REC VARCHAR2(1) := 'T';

  P_LOCATION_ID NUMBER;

  P_ORGANIZATION_ID NUMBER;

  P_SED_OPEN_BAL NUMBER;

  P_TRN_FROM_DATE DATE;

  LP_TRN_FROM_DATE varchar2(30);

  P_TRN_TO_DATE DATE;

  LP_TRN_TO_DATE varchar2(30);

  P_TOTAL_BASIC NUMBER;

  P_TOTAL_ADDITIONAL NUMBER;

  P_TOTAL_OTHER NUMBER;

  P_DOC_NO VARCHAR2(32767);

  P_DOC_DATE VARCHAR2(32767);

  P_TR6NO VARCHAR2(50);

  P_FISCAL_YEAR DATE;

  P_MONTH VARCHAR2(3);

  P_CONC_REQUEST_ID NUMBER;

  P_EXCISE_CESS_OPEN_BAL NUMBER;

  P_CVD_CESS_OPEN_BAL NUMBER;

  P_FIRST_REC1 VARCHAR2(1) := 'T';

  P_FIRST_REC2 VARCHAR2(1) := 'T';

  CP_RND_BASIC_ED NUMBER:=0;

  CP_RND_ADDL_ED NUMBER:=0;

  CP_RND_OTHER_ED NUMBER:=0;

  CP_RND_EDU_CESS NUMBER:=0;

  CP_RND_CVD_CESS NUMBER:=0;

  CP_RND_SHE_EDU_CESS NUMBER:=0;

  CP_RND_SHE_CVD_CESS NUMBER:=0;

  CP_BED_OPEN_BAL NUMBER;

  CP_AED_OPEN_BAL NUMBER;

  CP_SED_OPEN_BAL NUMBER;

  CP_PAGE_NO NUMBER;

  CP_EXCISE_CESS_OPEN_BAL NUMBER;

  CP_CVD_CESS_OPEN_BAL NUMBER;

  CP_CR_OPEN_BAL NUMBER;

  CP_ADDITIONAL_OPEN_BAL NUMBER;

  CP_OTHER_OPEN_BAL NUMBER;

  CP_CESS_OPEN_BAL NUMBER;

  CP_CESS_OPEN_BAL_CVD NUMBER;

  FUNCTION CF_BED_CLOSE_BALFORMULA(CR_BASIC_ED IN NUMBER
                                  ,DR_BASIC_ED IN NUMBER) RETURN NUMBER;

  FUNCTION CF_AED_CLOSE_BALFORMULA(CR_ADDITIONAL_ED IN NUMBER
                                  ,DR_ADDITIONAL_ED IN NUMBER) RETURN NUMBER;

  FUNCTION CF_SED_CLOSE_BALFORMULA(CR_OTHER_ED IN NUMBER
                                  ,DR_OTHER_ED IN NUMBER) RETURN NUMBER;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION CF_2FORMULA(ROUNDING_ID IN NUMBER
                      ,INVENTORY_ITEM_ID IN NUMBER
                      ,DR_INVOICE_NO IN VARCHAR2
                      ,CR_BASIC_ED IN NUMBER
                      ,CR_ADDITIONAL_ED IN NUMBER
                      ,CR_OTHER_ED IN NUMBER
                      ,TR6_CHALLAN_NO IN VARCHAR2
                      ,DR_BASIC_ED IN NUMBER
                      ,DR_ADDITIONAL_ED IN NUMBER
                      ,DR_OTHER_ED IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_1FORMULA(ROUNDING_ID IN NUMBER
                      ,INVENTORY_ITEM_ID IN NUMBER
                      ,DR_INVOICE_DATE IN VARCHAR2
                      ,CR_BASIC_ED IN NUMBER
                      ,CR_ADDITIONAL_ED IN NUMBER
                      ,CR_OTHER_ED IN NUMBER
                      ,TR6_CHALLAN_DATE IN VARCHAR2
                      ,DR_BASIC_ED IN NUMBER
                      ,DR_ADDITIONAL_ED IN NUMBER
                      ,DR_OTHER_ED IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_1FORMULA0031(TRANSACTION_ID IN NUMBER
                          ,ROUNDING_ID IN NUMBER
                          ,INVENTORY_ITEM_ID IN NUMBER
                          ,TR6_CHALLAN_DATE IN VARCHAR2
                          ,REMARKS IN VARCHAR2
                          ,DOC_DATE IN DATE
                          ,CR_BASIC_ED IN NUMBER
                          ,CR_ADDITIONAL_ED IN NUMBER
                          ,CR_OTHER_ED IN NUMBER
                          ,DR_BASIC_ED IN NUMBER
                          ,DR_ADDITIONAL_ED IN NUMBER
                          ,DR_OTHER_ED IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_CETFORMULA(INVENTORY_ITEM_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_1FORMULA0032(VENDOR_ID IN NUMBER
                          ,VENDOR_SITE_ID IN NUMBER
                          ,VFLAG IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_FOLIOFORMULA(INVENTORY_ITEM_ID IN NUMBER
                          ,SLNO IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_OPENING_BALFORMULA RETURN NUMBER;

  FUNCTION CF_CR_OPEN_BALFORMULA RETURN NUMBER;

  FUNCTION CF_ADDITIONAL_OPEN_BALFORMULA RETURN NUMBER;

  FUNCTION CF_OTHER_OPEN_BALFORMULA RETURN NUMBER;

  FUNCTION CF_ACK_RECD_DATEFORMULA(TRANSACTION_ID IN NUMBER
                                  ,REGISTER_ID IN NUMBER
                                  ,SLNO IN NUMBER
                                  ,CREATION_DATE IN DATE) RETURN DATE;

  FUNCTION CF_HDR_EC_CODEFORMULA RETURN CHAR;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION CF_CESS_OPEN_BALFORMULA RETURN NUMBER;

  FUNCTION CF_CESS_CLOSE_BALFORMULA1(REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_CESS_CLOSE_BALFORMULA2(REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_CR_CESSFORMULA(REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_DB_CESSFORMULA(REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_CR_CVD_CESSFORMULA(REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_DB_CVD_CESSFORMULA(REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_CVD_CESS_CLOS_BALFORMULA(REGISTER_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_CVD_CESS_OPEN_BALFORMULA RETURN NUMBER;

  FUNCTION CF_ROUNDING_AMTSFORMULA(TRANSACTION_ID IN NUMBER
                                  ,ROUNDING_ID IN NUMBER
                                  ,DR_INVOICE_NO IN VARCHAR2) RETURN NUMBER;

  FUNCTION CF_DR_BASIC_EDFORMULA(DR_BASIC_ED IN NUMBER) RETURN NUMBER;

  FUNCTION CF_DR_ADDL_EDFORMULA(DR_ADDITIONAL_ED IN NUMBER) RETURN NUMBER;

  FUNCTION CF_DR_OTHER_EDFORMULA(DR_OTHER_ED IN NUMBER) RETURN NUMBER;

  PROCEDURE OPENING_BALANCE;

  FUNCTION CP_RND_BASIC_ED_P RETURN NUMBER;

  FUNCTION CP_RND_ADDL_ED_P RETURN NUMBER;

  FUNCTION CP_RND_OTHER_ED_P RETURN NUMBER;

  FUNCTION CP_RND_EDU_CESS_P RETURN NUMBER;

  FUNCTION CP_RND_CVD_CESS_P RETURN NUMBER;

  FUNCTION CP_RND_SHE_EDU_CESS_P RETURN NUMBER;

  FUNCTION CP_RND_SHE_CVD_CESS_P RETURN NUMBER;

  FUNCTION CP_BED_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_AED_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_SED_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_PAGE_NO_P RETURN NUMBER;

  FUNCTION CP_EXCISE_CESS_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_CVD_CESS_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_CR_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_ADDITIONAL_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_OTHER_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_CESS_OPEN_BAL_P RETURN NUMBER;

  FUNCTION CP_CESS_OPEN_BAL_CVD_P RETURN NUMBER;

  LAST_PAGE_G VARCHAR2(1) := 'F';

  LAST_PAGE NUMBER := 0;

  VALIDATION_FLAG VARCHAR2(1) := 'N';

  PREV_PAGE NUMBER := 0;

END JA_JAINPLA_XMLP_PKG;



/
