--------------------------------------------------------
--  DDL for Package JE_JENOGEIS_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JE_JENOGEIS_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: JENOGEISS.pls 120.1 2007/12/25 16:57:53 dwkrishn noship $ */
  P_CONC_REQUEST_ID NUMBER := 0;

  P_LEDGER_ID NUMBER;

  P_FILENAME VARCHAR2(240);

  P_EXPENSE VARCHAR2(32767);

  P_INCOME VARCHAR2(32767);

  P_PERIOD_NAME VARCHAR2(32767);

  P_FINAL VARCHAR2(32767);

  STRUCT_NUM VARCHAR2(15) := '101';

  SET_OF_BOOKS_NAME VARCHAR2(30);

  SELECT_ALL VARCHAR2(1000) := '(CC.SEGMENT1 || ''\n'' || SEGMENT2 || ''\n'' || SEGMENT3 || ''\n'' || SEGMENT4 || ''\n'' || SEGMENT5 || ''\n'' ||
  SEGMENT6 || ''\n'' || SEGMENT7 || ''\n'' || SEGMENT8 || ''\n'' || SEGMENT9 || ''\n'' || SEGMENT10 || ''\n'' || SEGMENT11 || ''\n'' || SEGMENT12 ||
  ''\n'' || SEGMENT13 || ''\n'' || SEGMENT14 || ''\n'' || SEGMENT15 || ''\n'' || SEGMENT16 || ''\n'' || SEGMENT17 || ''\n'' || SEGMENT18 || ''\n'' ||
  SEGMENT19 || ''\n'' || SEGMENT20 || ''\n'' || SEGMENT21 || ''\n'' || SEGMENT22 || ''\n'' || SEGMENT23 || ''\n'' || SEGMENT24 || ''\n'' || SEGMENT25
  || ''\n'' || SEGMENT26 || ''\n'' || SEGMENT27 || ''\n'' || SEGMENT28 || ''\n'' || SEGMENT29 || ''\n'' || SEGMENT30)';

  WHERE_FLEX VARCHAR2(4000) := 'CC.SEGMENT11 BETWEEN  ''00'' and ''11''';

  ORDERBY_ACCT VARCHAR2(30) := 'CC.SEGMENT10';

  PRECISION NUMBER := 0;

  FUNC_CURRENCY VARCHAR2(25);

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  PROCEDURE P_GEI_VIEW;

  PROCEDURE P_INS_ASCII(P_LINE_NUMBER IN JE_NO_GEI_ASCIIS_T.LINE_NUMBER%TYPE
                       ,P_TEXT IN JE_NO_GEI_ASCIIS_T.TEXT%TYPE);

  PROCEDURE P_INSERT_PERIOD_NAME(P_PERIOD_NAME IN GL_BALANCES.PERIOD_NAME%TYPE
                                ,P_ACCOUNT_INCOME IN GL_BALANCES.PERIOD_NET_DR%TYPE
                                ,P_ACCOUNT_EXPENSE IN GL_BALANCES.PERIOD_NET_DR%TYPE);

  FUNCTION CF_DATEFORMULA RETURN CHAR;

  FUNCTION CF_REPORT_TITLEFORMULA RETURN CHAR;

  FUNCTION STRUCT_NUM_P RETURN VARCHAR2;

  FUNCTION SET_OF_BOOKS_NAME_P RETURN VARCHAR2;

  FUNCTION SELECT_ALL_P RETURN VARCHAR2;

  FUNCTION WHERE_FLEX_P RETURN VARCHAR2;

  FUNCTION ORDERBY_ACCT_P RETURN VARCHAR2;

  FUNCTION PRECISION_P RETURN NUMBER;

  FUNCTION FUNC_CURRENCY_P RETURN VARCHAR2;

END JE_JENOGEIS_XMLP_PKG;




/
