--------------------------------------------------------
--  DDL for Package JG_JGZZGLJRB_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JG_JGZZGLJRB_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: JGZZGLJRBS.pls 120.2 2007/12/25 16:07:00 npannamp noship $ */
  P_LEDGER_ID NUMBER;

  P_ACCESS_SET_ID NUMBER;

  P_PERIOD_FROM VARCHAR2(16);

  P_ACCT_FROM VARCHAR2(800);

  P_ACCT_TO VARCHAR2(800);

  P_CURRENCY_TYPE VARCHAR2(1);

  P_ENTERED_CURRENCY VARCHAR2(15);

  P_CONC_REQUEST_ID NUMBER := 0;

  P_COA_ID NUMBER;

  P_PERIOD_TO VARCHAR2(16);

  P_BALANCE_TYPE VARCHAR2(2);

  P_BUD_ENC_TYPE NUMBER;

  P_ACCT_LEVEL NUMBER;

  P_PAGE_NUM_FORMAT VARCHAR2(32767);

  P_START_DATE DATE;

  P_END_DATE DATE;

  CP_END_DATE DATE;

  CP_START_DATE DATE;

  P_LEDGER_CURRENCY VARCHAR2(40);

  P_FIRST_PAGE_NUM NUMBER;

  P_USER_PARAM_1 VARCHAR2(32767);

  P_USER_PARAM_2 VARCHAR2(32767);

  P_USER_PARAM_3 VARCHAR2(32767);

  P_USER_PARAM_4 VARCHAR2(32767);

  P_USER_PARAM_5 VARCHAR2(32767);

  P_TOP_LEVEL_PARENT_ACCT VARCHAR2(800);

  P_ACCT_DELIMITER VARCHAR2(1);

  DATA_ACCESS_SET_NAME VARCHAR2(30);

  CHART_OF_ACCOUNTS_ID NUMBER;

  DAS_WHERE VARCHAR2(600);

  CURR_WHERE_JRNL VARCHAR2(2000);

  PERIOD_WHERE VARCHAR2(2000);

  ACCT_WHERE VARCHAR2(1000);

  SELECT_ACCOUNT VARCHAR2(1000) := '(CC.SEGMENT1 || ''\n'' || SEGMENT2 || ''\n'' || SEGMENT3 || ''\n'' || SEGMENT4 || ''\n'' || SEGMENT5 || ''\n'' || SEGMENT6 || ''\n'' || SEGMENT7 || ''\n'' || SEGMENT8 || ''\n'' || SEGMENT9 || ''\n''
  || SEGMENT10 || ''\n'' || SEGMENT11 || ''\n'' || SEGMENT12 || ''\n'' || SEGMENT13 || ''\n'' || SEGMENT14 || ''\n'' || SEGMENT15 || ''\n'' || SEGMENT16 || ''\n'' || SEGMENT17 || ''\n'' || SEGMENT18 || ''\n'' || SEGMENT19 || ''\n''
  || SEGMENT20 || ''\n'' || SEGMENT21 || ''\n'' || SEGMENT22 || ''\n'' || SEGMENT23 || ''\n'' || SEGMENT24 || ''\n'' || SEGMENT25 || ''\n'' || SEGMENT26 || ''\n'' || SEGMENT27 || ''\n'' || SEGMENT28 || ''\n'' || SEGMENT29 || ''\n'' || SEGMENT30)';

  SELECT_ACCT_SEG VARCHAR2(30) := 'cc.segment1';

  SELECT_BAL_SEG VARCHAR2(30) := 'cc.segment1';

  TEMP_ACCT_WHERE VARCHAR2(1000);

  TEMP_LE_NAME VARCHAR2(240);

  TEMP_TAX_PAYER_ID VARCHAR2(30);

  TEMP_SERVICE_TYPE VARCHAR2(150);

  TEMP_ADDR1 VARCHAR2(240);

  TEMP_ADDR2 VARCHAR2(240);

  FP_START_DATE DATE;

  TP_END_DATE DATE;

  LE_WHERE VARCHAR2(300);

  SELECT_IC_SEG VARCHAR2(30) := 'cc.segment1';

  SELECT_MGT_SEG VARCHAR2(30) := 'cc.segment1';

  SELECT_ST_SEG VARCHAR2(30) := 'cc.segment1';

  SELECT_LE VARCHAR2(50) := '''               ''';

  FROM_LNSV VARCHAR2(50);

  REP_EXECUTION_DATE VARCHAR2(25);

  TEMP_ADDR3 VARCHAR2(240);

  TEMP_TOWN_CITY VARCHAR2(30);

  TEMP_POSTAL_CODE VARCHAR2(30);

  TEMP_LE_ID NUMBER := 0;

  START_DATE_PARAM VARCHAR2(20);

  END_DATE_PARAM VARCHAR2(20);

  SELECT_CC_SEG VARCHAR2(30) := 'cc.segment1';

  PAGE_NUM_FORMAT_PARAM VARCHAR2(20) := 'M of N';

  CURRENCY_TYPE_PARAM VARCHAR2(20);

  CURRENCY_PARAM VARCHAR2(20);

  ACCT_LEVEL_PARAM NUMBER;

  PERIOD_TO_PARAM VARCHAR2(20);

  PERIOD_FROM_PARAM VARCHAR2(20);

  ACCT_TO_PARAM VARCHAR2(800);

  ACCT_FROM_PARAM VARCHAR2(800);

  LEDGER_CURRENCY VARCHAR2(15);

  LEDGER_NAME_PARAM VARCHAR2(30);

  F_PERIOD_NUM NUMBER := -1;

  T_PERIOD_NUM NUMBER := -1;

  BALANCE_TYPE_PARAM VARCHAR2(20);

  BUDGETNAME_ENCUMBRANCETYPE VARCHAR2(80);

  PAGE_NUM_START_PARAM NUMBER := 1;

  USER_PARAM_1 VARCHAR2(20);

  USER_PARAM_2 VARCHAR2(20);

  USER_PARAM_3 VARCHAR2(20);

  USER_PARAM_4 VARCHAR2(20);

  USER_PARAM_5 VARCHAR2(20);

  CURR_WHERE_BAL VARCHAR2(2000);

  BUDENC_WHERE_JRNL VARCHAR2(200);

  BUDENC_WHERE_BAL VARCHAR2(200);

  BAL_CURRENCY VARCHAR2(15);

  SELECT_DR VARCHAR2(1000) := '''1,234,567,890,123,456,789,012,345,678.90''';

  SELECT_CR VARCHAR2(1000) := '''1,234,567,890,123,456,789,012,345,678.90''';

  SELECT_BEGIN_BAL VARCHAR2(1000) := '''1,234,567,890,123,456,789,012,345,678.90''';

  ACCT_SEG_VALUE_SET_ID NUMBER;

  SEG_SECURITY_WHERE VARCHAR2(200);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION LEGAL_ENTITY_NAMEFORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                                   ,LEGAL_ENTITY_NAME IN VARCHAR2) RETURN CHAR;

  PROCEDURE GET_LE_INFO(V_LE_ID IN NUMBER);

  FUNCTION LE_ADDRESS_LINE_1FORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                                   ,LE_ADDRESS_LINE_1 IN VARCHAR2) RETURN CHAR;

  FUNCTION LE_ADDRESS_LINE_2FORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                                   ,LE_ADDRESS_LINE_2 IN VARCHAR2) RETURN CHAR;

  FUNCTION LE_ADDRESS_LINE_3FORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                                   ,LE_ADDRESS_LINE_3 IN VARCHAR2) RETURN CHAR;

  FUNCTION LE_CITYFORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                         ,LE_CITY IN VARCHAR2) RETURN CHAR;

  FUNCTION LE_POSTAL_CODEFORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                                ,LE_POSTAL_CODE IN VARCHAR2) RETURN CHAR;

  FUNCTION LE_REGISTRATION_NUMBERFORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                                        ,LE_REGISTRATION_NUMBER IN VARCHAR2) RETURN CHAR;

  FUNCTION LE_ACTIVITY_CODEFORMULA(LEGAL_ENTITY_ID IN VARCHAR2
                                  ,LE_ACTIVITY_CODE IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL1_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL1_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL2_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL2_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL3_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL3_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL4_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL4_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL5_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL5_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL6_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL6_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL7_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL7_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL8_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL8_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL9_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                   ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL9_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                        ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL10_VALUEFORMULA(ACCT_VALUE IN VARCHAR2
                                    ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION ACCT_LEVEL10_VALUE_DESCFORMULA(ACCT_VALUE IN VARCHAR2
                                         ,ACCT_VALUE_DESC IN VARCHAR2) RETURN CHAR;

  FUNCTION DATA_ACCESS_SET_NAME_P RETURN VARCHAR2;

  FUNCTION CHART_OF_ACCOUNTS_ID_P RETURN NUMBER;

  FUNCTION DAS_WHERE_P RETURN VARCHAR2;

  FUNCTION CURR_WHERE_JRNL_P RETURN VARCHAR2;

  FUNCTION PERIOD_WHERE_P RETURN VARCHAR2;

  FUNCTION ACCT_WHERE_P RETURN VARCHAR2;

  FUNCTION SELECT_ACCOUNT_P RETURN VARCHAR2;

  FUNCTION SELECT_ACCT_SEG_P RETURN VARCHAR2;

  FUNCTION SELECT_BAL_SEG_P RETURN VARCHAR2;

  FUNCTION TEMP_ACCT_WHERE_P RETURN VARCHAR2;

  FUNCTION TEMP_LE_NAME_P RETURN VARCHAR2;

  FUNCTION TEMP_TAX_PAYER_ID_P RETURN VARCHAR2;

  FUNCTION TEMP_SERVICE_TYPE_P RETURN VARCHAR2;

  FUNCTION TEMP_ADDR1_P RETURN VARCHAR2;

  FUNCTION TEMP_ADDR2_P RETURN VARCHAR2;

  FUNCTION FP_START_DATE_P RETURN DATE;

  FUNCTION TP_END_DATE_P RETURN DATE;

  FUNCTION LE_WHERE_P RETURN VARCHAR2;

  FUNCTION SELECT_IC_SEG_P RETURN VARCHAR2;

  FUNCTION SELECT_MGT_SEG_P RETURN VARCHAR2;

  FUNCTION SELECT_ST_SEG_P RETURN VARCHAR2;

  FUNCTION SELECT_LE_P RETURN VARCHAR2;

  FUNCTION FROM_LNSV_P RETURN VARCHAR2;

  FUNCTION REP_EXECUTION_DATE_P RETURN VARCHAR2;

  FUNCTION TEMP_ADDR3_P RETURN VARCHAR2;

  FUNCTION TEMP_TOWN_CITY_P RETURN VARCHAR2;

  FUNCTION TEMP_POSTAL_CODE_P RETURN VARCHAR2;

  FUNCTION TEMP_LE_ID_P RETURN NUMBER;

  FUNCTION START_DATE_PARAM_P RETURN VARCHAR2;

  FUNCTION END_DATE_PARAM_P RETURN VARCHAR2;

  FUNCTION SELECT_CC_SEG_P RETURN VARCHAR2;

  FUNCTION PAGE_NUM_FORMAT_PARAM_P RETURN VARCHAR2;

  FUNCTION CURRENCY_TYPE_PARAM_P RETURN VARCHAR2;

  FUNCTION CURRENCY_PARAM_P RETURN VARCHAR2;

  FUNCTION ACCT_LEVEL_PARAM_P RETURN NUMBER;

  FUNCTION PERIOD_TO_PARAM_P RETURN VARCHAR2;

  FUNCTION PERIOD_FROM_PARAM_P RETURN VARCHAR2;

  FUNCTION ACCT_TO_PARAM_P RETURN VARCHAR2;

  FUNCTION ACCT_FROM_PARAM_P RETURN VARCHAR2;

  FUNCTION LEDGER_CURRENCY_P RETURN VARCHAR2;

  FUNCTION LEDGER_NAME_PARAM_P RETURN VARCHAR2;

  FUNCTION F_PERIOD_NUM_P RETURN NUMBER;

  FUNCTION T_PERIOD_NUM_P RETURN NUMBER;

  FUNCTION BALANCE_TYPE_PARAM_P RETURN VARCHAR2;

  FUNCTION BUDGETNAME_ENCUMBRANCETYPE_P RETURN VARCHAR2;

  FUNCTION PAGE_NUM_START_PARAM_P RETURN NUMBER;

  FUNCTION USER_PARAM_1_P RETURN VARCHAR2;

  FUNCTION USER_PARAM_2_P RETURN VARCHAR2;

  FUNCTION USER_PARAM_3_P RETURN VARCHAR2;

  FUNCTION USER_PARAM_4_P RETURN VARCHAR2;

  FUNCTION USER_PARAM_5_P RETURN VARCHAR2;

  FUNCTION CURR_WHERE_BAL_P RETURN VARCHAR2;

  FUNCTION BUDENC_WHERE_JRNL_P RETURN VARCHAR2;

  FUNCTION BUDENC_WHERE_BAL_P RETURN VARCHAR2;

  FUNCTION BAL_CURRENCY_P RETURN VARCHAR2;

  FUNCTION SELECT_DR_P RETURN VARCHAR2;

  FUNCTION SELECT_CR_P RETURN VARCHAR2;

  FUNCTION SELECT_BEGIN_BAL_P RETURN VARCHAR2;

  FUNCTION ACCT_SEG_VALUE_SET_ID_P RETURN NUMBER;

  FUNCTION SEG_SECURITY_WHERE_P RETURN VARCHAR2;

END JG_JGZZGLJRB_XMLP_PKG;




/
