--------------------------------------------------------
--  DDL for Package JTF_OBJECT_DTLS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JTF_OBJECT_DTLS_PKG" AUTHID CURRENT_USER as
/* $Header: jtfobdts.pls 120.1 2005/07/02 00:52:16 appldev noship $ */
procedure INSERT_ROW  ( X_ROWID  IN OUT NOCOPY   VARCHAR2,
      X_OBJECT_CODE IN VARCHAR2,
      X_APPLICATION_ID IN NUMBER,
      X_PAGE_TYPE IN VARCHAR2,
      X_PG_REGION_PATH  IN VARCHAR2,
      X_CREATION_DATE IN DATE,
      X_CREATED_BY IN  NUMBER,
      X_LAST_UPDATED_BY IN NUMBER,
      X_LAST_UPDATE_DATE IN DATE,
      X_LAST_UPDATE_LOGIN IN NUMBER
   );

procedure LOCK_ROW (
  X_OBJECT_DTLS_ID IN NUMBER,
  X_OBJECT_VERSION_NUMBER IN NUMBER
);

procedure UPDATE_ROW  ( X_OBJECT_DTLS_ID  IN NUMBER,
      X_OBJECT_CODE IN VARCHAR2,
      X_APPLICATION_ID IN NUMBER,
      X_PAGE_TYPE IN VARCHAR2,
      X_PG_REGION_PATH  IN VARCHAR2,
      X_LAST_UPDATED_BY IN NUMBER,
      X_LAST_UPDATE_DATE IN DATE,
      X_LAST_UPDATE_LOGIN IN NUMBER,
      X_OBJECT_VERSION_NUMBER IN OUT NOCOPY NUMBER
   );

procedure DELETE_ROW (
  X_OBJECT_DTLS_ID  IN NUMBER,
  X_OBJECT_VERSION_NUMBER IN NUMBER
) ;
end JTF_OBJECT_DTLS_PKG;

 

/
