--------------------------------------------------------
--  DDL for Package JTF_RS_ROLES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JTF_RS_ROLES_PKG" AUTHID CURRENT_USER as
/* $Header: jtfrstrs.pls 120.0 2005/05/11 08:22:33 appldev ship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_ROLE_ID in NUMBER,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ROLE_CODE in VARCHAR2,
  X_ROLE_TYPE_CODE in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_MEMBER_FLAG in VARCHAR2,
  X_ADMIN_FLAG in VARCHAR2,
  X_LEAD_FLAG in VARCHAR2,
  X_MANAGER_FLAG in VARCHAR2,
  X_ACTIVE_FLAG in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ROLE_NAME in VARCHAR2,
  X_ROLE_DESC in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_ROLE_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER
);

procedure UPDATE_ROW (
  X_ROLE_ID in NUMBER,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ROLE_CODE in VARCHAR2,
  X_ROLE_TYPE_CODE in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_MEMBER_FLAG in VARCHAR2,
  X_ADMIN_FLAG in VARCHAR2,
  X_LEAD_FLAG in VARCHAR2,
  X_MANAGER_FLAG in VARCHAR2,
  X_ACTIVE_FLAG in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ROLE_NAME in VARCHAR2,
  X_ROLE_DESC in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);

procedure LOAD_ROW (
  X_ROLE_ID in NUMBER,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_ROLE_CODE in VARCHAR2,
  X_ROLE_TYPE_CODE in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_MEMBER_FLAG in VARCHAR2,
  X_ADMIN_FLAG in VARCHAR2,
  X_LEAD_FLAG in VARCHAR2,
  X_MANAGER_FLAG in VARCHAR2,
  X_ACTIVE_FLAG in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ROLE_NAME in VARCHAR2,
  X_ROLE_DESC in VARCHAR2,
  X_OWNER in VARCHAR2
);

Procedure TRANSLATE_ROW
(X_role_id  in number,
 X_role_name in varchar2,
 x_role_desc in varchar2,
 x_Last_update_date in date,
 x_last_updated_by in number,
 x_last_update_login in number);

procedure DELETE_ROW (
  X_ROLE_ID in NUMBER
);
procedure ADD_LANGUAGE;
end JTF_RS_ROLES_PKG;

 

/
