--------------------------------------------------------
--  DDL for Package JTF_OBJECTS_MAPPING_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JTF_OBJECTS_MAPPING_PKG" AUTHID CURRENT_USER as
/* $Header: jtfobmas.pls 120.3 2008/01/07 12:37:32 ipananil ship $ */
 procedure INSERT_ROW(
  X_ROWID in out NOCOPY VARCHAR2,
  X_MAPPING_ID in NUMBER,
  X_APPLICATION_ID  in NUMBER,
  X_SOURCE_OBJECT_CODE  in VARCHAR2,
  X_OBJECT_CODE in VARCHAR2,
  X_OBJECT_ID in VARCHAR2,
  X_END_DATE  in DATE 	,
  X_SEEDED_FLAG in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER );

 procedure LOCK_ROW (
  X_MAPPING_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER
) ;

procedure UPDATE_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_MAPPING_ID in NUMBER,
  X_APPLICATION_ID  in NUMBER,
  X_SOURCE_OBJECT_CODE  in VARCHAR2,
  X_OBJECT_CODE in VARCHAR2,
  X_OBJECT_ID in VARCHAR2,
  X_END_DATE  in DATE 	,
  X_SEEDED_FLAG in VARCHAR2,
  X_ATTRIBUTE1 in VARCHAR2,
  X_ATTRIBUTE2 in VARCHAR2,
  X_ATTRIBUTE3 in VARCHAR2,
  X_ATTRIBUTE4 in VARCHAR2,
  X_ATTRIBUTE5 in VARCHAR2,
  X_ATTRIBUTE6 in VARCHAR2,
  X_ATTRIBUTE7 in VARCHAR2,
  X_ATTRIBUTE8 in VARCHAR2,
  X_ATTRIBUTE9 in VARCHAR2,
  X_ATTRIBUTE10 in VARCHAR2,
  X_ATTRIBUTE11 in VARCHAR2,
  X_ATTRIBUTE12 in VARCHAR2,
  X_ATTRIBUTE13 in VARCHAR2,
  X_ATTRIBUTE14 in VARCHAR2,
  X_ATTRIBUTE15 in VARCHAR2,
  X_ATTRIBUTE_CATEGORY in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER);


procedure DELETE_ROW (
  X_MAPPING_ID in NUMBER );

end JTF_OBJECTS_MAPPING_PKG;

/
