--------------------------------------------------------
--  DDL for Package JTF_EVT_HANDLERS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JTF_EVT_HANDLERS_PKG" AUTHID CURRENT_USER as
/* $Header: JTFEVTHS.pls 115.1 2002/02/14 05:44:06 appldev ship $ */
procedure INSERT_ROW (
  X_JTF_EVT_HANDLERS_ID in NUMBER,
  X_JTF_EVT_TYPES_ID in NUMBER,
  X_JTF_EVT_HANDLERS_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_MTD_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_SYNC_FLAG in VARCHAR2,
  X_SECURITY_GROUP_ID in NUMBER,
  X_JTF_EVT_HANDLERS_DESC in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_JTF_EVT_HANDLERS_ID in NUMBER,
  X_JTF_EVT_TYPES_ID in NUMBER,
  X_JTF_EVT_HANDLERS_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_MTD_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_SYNC_FLAG in VARCHAR2,
  X_SECURITY_GROUP_ID in NUMBER,
  X_JTF_EVT_HANDLERS_DESC in VARCHAR2
);
procedure UPDATE_ROW (
  X_JTF_EVT_HANDLERS_ID in NUMBER,
  X_JTF_EVT_TYPES_ID in NUMBER,
  X_JTF_EVT_HANDLERS_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_MTD_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_SYNC_FLAG in VARCHAR2,
  X_SECURITY_GROUP_ID in NUMBER,
  X_JTF_EVT_HANDLERS_DESC in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_JTF_EVT_HANDLERS_ID in NUMBER
);
procedure ADD_LANGUAGE;

procedure LOAD_ROW (
  X_JTF_EVT_HANDLERS_ID in NUMBER, -- key fields
  X_SECURITY_GROUP_ID in NUMBER,
  X_JTF_EVT_TYPES_ID  in NUMBER, -- data fields
  X_JTF_EVT_HANDLERS_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_MTD_NAME in VARCHAR2,
  X_JTF_EVT_HANDLERS_SYNC_FLAG in VARCHAR2,
  X_JTF_EVT_HANDLERS_DESC in VARCHAR2,
  X_OWNER in VARCHAR2 -- owner fields
);


procedure TRANSLATE_ROW (
  X_JTF_EVT_HANDLERS_ID in NUMBER, -- key field
  X_JTF_EVT_HANDLERS_DESC in VARCHAR2, -- translated field
  X_OWNER in VARCHAR2 -- owner fields
);

end JTF_EVT_HANDLERS_PKG;

 

/
