--------------------------------------------------------
--  DDL for Package JTF_IH_ACTIONS_SEED_PVT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JTF_IH_ACTIONS_SEED_PVT" AUTHID CURRENT_USER as
/* $Header: JTFIHACS.pls 115.1 2000/02/15 12:25:08 pkm ship     $ */
procedure INSERT_ROW (
  X_ROWID in out VARCHAR2,
  X_ACTION_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_ACTION in VARCHAR2,
  X_SHORT_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_ACTION_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_ACTION in VARCHAR2,
  X_SHORT_DESCRIPTION in VARCHAR2
);
procedure UPDATE_ROW (
  X_ACTION_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_ACTION in VARCHAR2,
  X_SHORT_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_ACTION_ID in NUMBER
);
procedure ADD_LANGUAGE;
procedure LOAD_ROW (
  X_ACTION_ID in NUMBER,
  X_ACTION in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SHORT_DESCRIPTION in VARCHAR2,
  X_OWNER IN VARCHAR2
);
procedure TRANSLATE_ROW (
  X_ACTION_ID in NUMBER,
  X_ACTION in VARCHAR2,
  X_SHORT_DESCRIPTION in VARCHAR2,
  X_OWNER IN VARCHAR2
);
end JTF_IH_ACTIONS_SEED_PVT;

 

/
