--------------------------------------------------------
--  DDL for Package JTF_PREFAB_CA_COMPS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JTF_PREFAB_CA_COMPS_PKG" AUTHID CURRENT_USER as
/* $Header: jtfprecacompts.pls 120.4 2006/09/15 12:24:14 amaddula noship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_CA_COMP_ID in NUMBER,
  X_SECURITY_GROUP_ID in NUMBER,
  X_APPLICATION_ID in NUMBER,
  X_COMP_NAME in VARCHAR2,
  X_COMPONENT_KEY in VARCHAR2,
  X_LOADER_CLASS_NAME in VARCHAR2,
  X_TIMEOUT_TYPE in VARCHAR2,
  X_TIMEOUT in NUMBER,
  X_TIMEOUT_UNIT in VARCHAR2,
  X_SGID_ENABLED_FLAG in VARCHAR2,
  X_STAT_ENABLED_FLAG in VARCHAR2,
  X_DISTRIBUTED_FLAG in VARCHAR2,
  X_CACHE_GENERIC_FLAG in VARCHAR2,
  X_BUSINESS_EVENT_NAME in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_CA_COMP_ID in NUMBER,
  X_SECURITY_GROUP_ID in NUMBER,
  X_APPLICATION_ID in NUMBER,
  X_COMP_NAME in VARCHAR2,
  X_COMPONENT_KEY in VARCHAR2,
  X_LOADER_CLASS_NAME in VARCHAR2,
  X_TIMEOUT_TYPE in VARCHAR2,
  X_TIMEOUT in NUMBER,
  X_TIMEOUT_UNIT in VARCHAR2,
  X_SGID_ENABLED_FLAG in VARCHAR2,
  X_STAT_ENABLED_FLAG in VARCHAR2,
  X_DISTRIBUTED_FLAG in VARCHAR2,
  X_CACHE_GENERIC_FLAG in VARCHAR2,
  X_BUSINESS_EVENT_NAME in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DESCRIPTION in VARCHAR2
);
procedure UPDATE_ROW (
  X_CA_COMP_ID in NUMBER,
  X_SECURITY_GROUP_ID in NUMBER,
  X_APPLICATION_ID in NUMBER,
  X_COMP_NAME in VARCHAR2,
  X_COMPONENT_KEY in VARCHAR2,
  X_LOADER_CLASS_NAME in VARCHAR2,
  X_TIMEOUT_TYPE in VARCHAR2,
  X_TIMEOUT in NUMBER,
  X_TIMEOUT_UNIT in VARCHAR2,
  X_SGID_ENABLED_FLAG in VARCHAR2,
  X_STAT_ENABLED_FLAG in VARCHAR2,
  X_DISTRIBUTED_FLAG in VARCHAR2,
  X_CACHE_GENERIC_FLAG in VARCHAR2,
  X_BUSINESS_EVENT_NAME in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure UPDATE_ROW_1 (
  X_CA_COMP_ID in NUMBER,
  X_LAST_UPDATED_BY in NUMBER
);
procedure DELETE_ROW (
  X_CA_COMP_ID in NUMBER
);
procedure ADD_LANGUAGE;
procedure LOAD_ROW (
  X_SECURITY_GROUP_ID in NUMBER,
  X_APPLICATION_ID in NUMBER,
  X_COMP_NAME in VARCHAR2,
  X_COMPONENT_KEY in VARCHAR2,
  X_LOADER_CLASS_NAME in VARCHAR2,
  X_TIMEOUT_TYPE in VARCHAR2,
  X_TIMEOUT in NUMBER,
  X_TIMEOUT_UNIT in VARCHAR2,
  X_SGID_ENABLED_FLAG in VARCHAR2,
  X_STAT_ENABLED_FLAG in VARCHAR2,
  X_DISTRIBUTED_FLAG in VARCHAR2,
  X_CACHE_GENERIC_FLAG in VARCHAR2,
  X_BUSINESS_EVENT_NAME in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_OWNER in VARCHAR2,
  X_CUSTOM_MODE in VARCHAR2
);
procedure TRANSLATE_ROW (
  X_APPLICATION_ID in NUMBER,
  X_COMPONENT_KEY in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_OWNER in VARCHAR2,
  X_CUSTOM_MODE in VARCHAR2
);
end JTF_PREFAB_CA_COMPS_PKG;

 

/
