--------------------------------------------------------
--  DDL for Package JTF_AE_PROFPROPS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."JTF_AE_PROFPROPS" AUTHID CURRENT_USER as
/* $Header: JTFAEPPS.pls 120.1 2005/07/02 02:00:05 appldev ship $ */
procedure INSERT_ROW (
  X_PROFILEPROPERTIES_ID in NUMBER,
  X_PROFILE_MAPPINGS_ID in NUMBER,
  X_ATTRNAME in VARCHAR2,
  X_OWNER_APPLICATION_ID in NUMBER,
  X_ISPRIMARYKEY_FLAG_CODE in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SECURITY_GROUP_ID in NUMBER,
  X_PROPERTYNAME in VARCHAR2,
  X_PROP_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_PROFILEPROPERTIES_ID in NUMBER,
  X_PROFILE_MAPPINGS_ID in NUMBER,
  X_ATTRNAME in VARCHAR2,
  X_OWNER_APPLICATION_ID in NUMBER,
  X_ISPRIMARYKEY_FLAG_CODE in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SECURITY_GROUP_ID in NUMBER,
  X_PROPERTYNAME in VARCHAR2,
  X_PROP_DESCRIPTION in VARCHAR2
);
procedure UPDATE_ROW (
  X_PROFILEPROPERTIES_ID in NUMBER,
  X_PROFILE_MAPPINGS_ID in NUMBER,
  X_ATTRNAME in VARCHAR2,
  X_OWNER_APPLICATION_ID in NUMBER,
  X_ISPRIMARYKEY_FLAG_CODE in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_SECURITY_GROUP_ID in NUMBER,
  X_PROPERTYNAME in VARCHAR2,
  X_PROP_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_PROFILEPROPERTIES_ID in NUMBER
);
procedure ADD_LANGUAGE;

procedure TRANSLATE_ROW(
  X_PROFILEPROPERTIES_ID in NUMBER,
  X_PROPERTYNAME in VARCHAR2,
  X_PROP_DESCRIPTION in VARCHAR2,
  X_OWNER in VARCHAR2
);

procedure LOAD_ROW(
  X_PROFILEPROPERTIES_ID in NUMBER,
  X_SECURITY_GROUP_ID in NUMBER,
  X_PROFILE_MAPPINGS_ID in NUMBER,
  X_ATTRNAME in VARCHAR2,
  X_OWNER_APPLICATION_ID in NUMBER,
  X_ISPRIMARYKEY_FLAG_CODE in VARCHAR2,
  X_PROPERTYNAME in VARCHAR2,
  X_PROP_DESCRIPTION in VARCHAR2,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_OWNER in VARCHAR2
);

end JTF_AE_PROFPROPS;

 

/
