--------------------------------------------------------
--  DDL for Package LNS_COND_ASSIGNMENTS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."LNS_COND_ASSIGNMENTS_PKG" AUTHID CURRENT_USER AS
/* $Header: LNS_CASGM_TBLH_S.pls 120.2.12010000.3 2010/03/17 13:34:58 scherkas ship $ */

/* Insert_Row procedure */
PROCEDURE Insert_Row(
	X_COND_ASSIGNMENT_ID		IN OUT NOCOPY NUMBER
	,P_LOAN_ID		IN NUMBER
	,P_CONDITION_ID		IN NUMBER
	,P_CONDITION_DESCRIPTION		IN VARCHAR2
	,P_CONDITION_MET_FLAG		IN VARCHAR2
	,P_MANDATORY_FLAG		IN VARCHAR2
	,P_CREATED_BY		IN NUMBER
	,P_CREATION_DATE		IN DATE
	,P_LAST_UPDATED_BY		IN NUMBER
	,P_LAST_UPDATE_DATE		IN DATE
	,P_LAST_UPDATE_LOGIN		IN NUMBER
	,P_OBJECT_VERSION_NUMBER		IN NUMBER
	,P_FULFILLMENT_DATE		IN DATE
	,P_FULFILLMENT_UPDATED_BY		IN NUMBER
	,P_START_DATE_ACTIVE		IN DATE
	,P_END_DATE_ACTIVE		IN DATE
    ,P_DISB_HEADER_ID		IN NUMBER
	,P_DELETE_DISABLED_FLAG 	IN VARCHAR2
    ,P_OWNER_OBJECT_ID        IN NUMBER
    ,P_OWNER_TABLE        IN VARCHAR2
);

/* Update_Row procedure */
PROCEDURE Update_Row(
	P_COND_ASSIGNMENT_ID		IN NUMBER
	,P_LOAN_ID		IN NUMBER
	,P_CONDITION_ID		IN NUMBER
	,P_CONDITION_DESCRIPTION		IN VARCHAR2
	,P_CONDITION_MET_FLAG		IN VARCHAR2
	,P_MANDATORY_FLAG		IN VARCHAR2
	,P_LAST_UPDATED_BY		IN NUMBER
	,P_LAST_UPDATE_DATE		IN DATE
	,P_LAST_UPDATE_LOGIN		IN NUMBER
	,P_OBJECT_VERSION_NUMBER		IN NUMBER
	,P_FULFILLMENT_DATE		IN DATE
	,P_FULFILLMENT_UPDATED_BY		IN NUMBER
	,P_START_DATE_ACTIVE		IN DATE
	,P_END_DATE_ACTIVE		IN DATE
 	,P_DISB_HEADER_ID		IN NUMBER
	,P_DELETE_DISABLED_FLAG		IN VARCHAR2
    ,P_OWNER_OBJECT_ID        IN NUMBER
    ,P_OWNER_TABLE        IN VARCHAR2
);

/* Delete_Row procedure */
PROCEDURE Delete_Row(P_COND_ASSIGNMENT_ID IN NUMBER);

procedure ADD_LANGUAGE;

/* Lock_Row procedure */
PROCEDURE Lock_Row(
	P_COND_ASSIGNMENT_ID		IN NUMBER
	,P_LOAN_ID		IN NUMBER
	,P_CONDITION_ID		IN NUMBER
	,P_CONDITION_DESCRIPTION		IN VARCHAR2
	,P_CONDITION_MET_FLAG		IN VARCHAR2
	,P_MANDATORY_FLAG		IN VARCHAR2
	,P_CREATED_BY		IN NUMBER
	,P_CREATION_DATE		IN DATE
	,P_LAST_UPDATED_BY		IN NUMBER
	,P_LAST_UPDATE_DATE		IN DATE
	,P_LAST_UPDATE_LOGIN		IN NUMBER
	,P_OBJECT_VERSION_NUMBER		IN NUMBER
	,P_FULFILLMENT_DATE		IN DATE
	,P_FULFILLMENT_UPDATED_BY		IN NUMBER
	,P_START_DATE_ACTIVE		IN DATE
	,P_END_DATE_ACTIVE		IN DATE
	,P_DISB_HEADER_ID		IN NUMBER
	,P_DELETE_DISABLED_FLAG		IN VARCHAR2
    ,P_OWNER_OBJECT_ID        IN NUMBER
    ,P_OWNER_TABLE        IN VARCHAR2
);
END;


/
