--------------------------------------------------------
--  DDL for Package MRP_SCHEDULE_DATES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."MRP_SCHEDULE_DATES_PKG" AUTHID CURRENT_USER AS
/* $Header: MRSDATES.pls 115.0 99/07/16 12:44:37 porting ship $ */

PROCEDURE Insert_Row(
                  X_Rowid                         IN OUT VARCHAR2,
                  X_MPS_Transaction_Id                   NUMBER,
                  X_Schedule_Level                       NUMBER,
                  X_Supply_Demand_Type                   NUMBER,
                  X_Last_Update_Date                     DATE,
                  X_Last_Updated_By                      NUMBER,
                  X_Creation_Date                        DATE,
                  X_Created_By                           NUMBER,
                  X_Last_Update_Login                    NUMBER DEFAULT NULL,
                  X_Inventory_Item_Id                    NUMBER,
                  X_Organization_Id                      NUMBER,
                  X_Schedule_Designator                  VARCHAR2,
                  X_Schedule_Date                        DATE,
                  X_Schedule_Workdate                    DATE,
                  X_Rate_End_Date	                 DATE DEFAULT NULL,
                  X_Schedule_Quantity                    NUMBER DEFAULT NULL,
                  X_Original_Schedule_Quantity           NUMBER DEFAULT NULL,
                  X_Repetitive_Daily_Rate                NUMBER DEFAULT NULL,
                  X_Schedule_Origination_Type            NUMBER,
                  X_Source_Forecast_Designator           VARCHAR2 DEFAULT NULL,
                  X_Reference_Schedule_Id                NUMBER DEFAULT NULL,
                  X_Schedule_Comments                    VARCHAR2 DEFAULT NULL,
                  X_Source_Organization_Id               NUMBER DEFAULT NULL,
                  X_Source_Schedule_Designator           VARCHAR2 DEFAULT NULL,
                  X_Source_Sales_Order_Id                NUMBER DEFAULT NULL,
                  X_Source_Code			         VARCHAR2 DEFAULT NULL,
                  X_Source_Line_Id       	         NUMBER DEFAULT NULL,
                  X_Reservation_Id	                 NUMBER DEFAULT NULL,
                  X_Forecast_Id		                 NUMBER DEFAULT NULL,
                  X_Request_Id                  	 NUMBER DEFAULT NULL,
                  X_Program_Application_Id               NUMBER DEFAULT NULL,
                  X_Program_Id                           NUMBER DEFAULT NULL,
                  X_Program_Update_Date                  DATE DEFAULT NULL,
                  X_DDF_Context                   	 VARCHAR2 DEFAULT NULL,
                  X_Attribute_Category                   VARCHAR2 DEFAULT NULL,
                  X_Attribute1                           VARCHAR2 DEFAULT NULL,
                  X_Attribute2                           VARCHAR2 DEFAULT NULL,
                  X_Attribute3                           VARCHAR2 DEFAULT NULL,
                  X_Attribute4                           VARCHAR2 DEFAULT NULL,
                  X_Attribute5                           VARCHAR2 DEFAULT NULL,
                  X_Attribute6                           VARCHAR2 DEFAULT NULL,
                  X_Attribute7                           VARCHAR2 DEFAULT NULL,
                  X_Attribute8                           VARCHAR2 DEFAULT NULL,
                  X_Attribute9                           VARCHAR2 DEFAULT NULL,
                  X_Attribute10                          VARCHAR2 DEFAULT NULL,
                  X_Attribute11                          VARCHAR2 DEFAULT NULL,
                  X_Attribute12                          VARCHAR2 DEFAULT NULL,
                  X_Attribute13                          VARCHAR2 DEFAULT NULL,
                  X_Attribute14                          VARCHAR2 DEFAULT NULL,
                  X_Attribute15                          VARCHAR2 DEFAULT NULL);

PROCEDURE Lock_Row(
                  X_Rowid                                VARCHAR2,
                  X_MPS_Transaction_Id                   NUMBER,
                  X_Schedule_Level                       NUMBER,
                  X_Supply_Demand_Type                   NUMBER,
                  X_Last_Update_Date                     DATE,
                  X_Last_Updated_By                      NUMBER,
                  X_Creation_Date                        DATE,
                  X_Created_By                           NUMBER,
                  X_Last_Update_Login                    NUMBER DEFAULT NULL,
                  X_Inventory_Item_Id                    NUMBER,
                  X_Organization_Id                      NUMBER,
                  X_Schedule_Designator                  VARCHAR2,
                  X_Schedule_Date                        DATE,
                  X_Schedule_Workdate                    DATE,
                  X_Rate_End_Date	                 DATE DEFAULT NULL,
                  X_Schedule_Quantity                    NUMBER DEFAULT NULL,
                  X_Original_Schedule_Quantity           NUMBER DEFAULT NULL,
                  X_Repetitive_Daily_Rate                NUMBER DEFAULT NULL,
                  X_Schedule_Origination_Type            NUMBER,
                  X_Source_Forecast_Designator           VARCHAR2 DEFAULT NULL,
                  X_Reference_Schedule_Id                NUMBER DEFAULT NULL,
                  X_Schedule_Comments                    VARCHAR2 DEFAULT NULL,
                  X_Source_Organization_Id               NUMBER DEFAULT NULL,
                  X_Source_Schedule_Designator           VARCHAR2 DEFAULT NULL,
                  X_Source_Sales_Order_Id                NUMBER DEFAULT NULL,
                  X_Source_Code			         VARCHAR2 DEFAULT NULL,
                  X_Source_Line_Id       	         NUMBER DEFAULT NULL,
                  X_Reservation_Id	                 NUMBER DEFAULT NULL,
                  X_Forecast_Id		                 NUMBER DEFAULT NULL,
                  X_Request_Id                  	 NUMBER DEFAULT NULL,
                  X_Program_Application_Id               NUMBER DEFAULT NULL,
                  X_Program_Id                           NUMBER DEFAULT NULL,
                  X_Program_Update_Date                  DATE DEFAULT NULL,
                  X_DDF_Context                   	 VARCHAR2 DEFAULT NULL,
                  X_Attribute_Category                   VARCHAR2 DEFAULT NULL,
                  X_Attribute1                           VARCHAR2 DEFAULT NULL,
                  X_Attribute2                           VARCHAR2 DEFAULT NULL,
                  X_Attribute3                           VARCHAR2 DEFAULT NULL,
                  X_Attribute4                           VARCHAR2 DEFAULT NULL,
                  X_Attribute5                           VARCHAR2 DEFAULT NULL,
                  X_Attribute6                           VARCHAR2 DEFAULT NULL,
                  X_Attribute7                           VARCHAR2 DEFAULT NULL,
                  X_Attribute8                           VARCHAR2 DEFAULT NULL,
                  X_Attribute9                           VARCHAR2 DEFAULT NULL,
                  X_Attribute10                          VARCHAR2 DEFAULT NULL,
                  X_Attribute11                          VARCHAR2 DEFAULT NULL,
                  X_Attribute12                          VARCHAR2 DEFAULT NULL,
                  X_Attribute13                          VARCHAR2 DEFAULT NULL,
                  X_Attribute14                          VARCHAR2 DEFAULT NULL,
                  X_Attribute15                          VARCHAR2 DEFAULT NULL);

PROCEDURE Update_Row(
                  X_Rowid                                VARCHAR2,
                  X_MPS_Transaction_Id                   NUMBER,
                  X_Schedule_Level                       NUMBER,
                  X_Supply_Demand_Type                   NUMBER,
                  X_Last_Update_Date                     DATE,
                  X_Last_Updated_By                      NUMBER,
                  X_Creation_Date                        DATE,
                  X_Created_By                           NUMBER,
                  X_Last_Update_Login                    NUMBER DEFAULT NULL,
                  X_Inventory_Item_Id                    NUMBER,
                  X_Organization_Id                      NUMBER,
                  X_Schedule_Designator                  VARCHAR2,
                  X_Schedule_Date                        DATE,
                  X_Schedule_Workdate                    DATE,
                  X_Rate_End_Date	                 DATE DEFAULT NULL,
                  X_Schedule_Quantity                    NUMBER DEFAULT NULL,
                  X_Original_Schedule_Quantity           NUMBER DEFAULT NULL,
                  X_Repetitive_Daily_Rate                NUMBER DEFAULT NULL,
                  X_Schedule_Origination_Type            NUMBER,
                  X_Source_Forecast_Designator           VARCHAR2 DEFAULT NULL,
                  X_Reference_Schedule_Id                NUMBER DEFAULT NULL,
                  X_Schedule_Comments                    VARCHAR2 DEFAULT NULL,
                  X_Source_Organization_Id               NUMBER DEFAULT NULL,
                  X_Source_Schedule_Designator           VARCHAR2 DEFAULT NULL,
                  X_Source_Sales_Order_Id                NUMBER DEFAULT NULL,
                  X_Source_Code			         VARCHAR2 DEFAULT NULL,
                  X_Source_Line_Id       	         NUMBER DEFAULT NULL,
                  X_Reservation_Id	                 NUMBER DEFAULT NULL,
                  X_Forecast_Id		                 NUMBER DEFAULT NULL,
                  X_Request_Id                  	 NUMBER DEFAULT NULL,
                  X_Program_Application_Id               NUMBER DEFAULT NULL,
                  X_Program_Id                           NUMBER DEFAULT NULL,
                  X_Program_Update_Date                  DATE DEFAULT NULL,
                  X_DDF_Context                   	 VARCHAR2 DEFAULT NULL,
                  X_Attribute_Category                   VARCHAR2 DEFAULT NULL,
                  X_Attribute1                           VARCHAR2 DEFAULT NULL,
                  X_Attribute2                           VARCHAR2 DEFAULT NULL,
                  X_Attribute3                           VARCHAR2 DEFAULT NULL,
                  X_Attribute4                           VARCHAR2 DEFAULT NULL,
                  X_Attribute5                           VARCHAR2 DEFAULT NULL,
                  X_Attribute6                           VARCHAR2 DEFAULT NULL,
                  X_Attribute7                           VARCHAR2 DEFAULT NULL,
                  X_Attribute8                           VARCHAR2 DEFAULT NULL,
                  X_Attribute9                           VARCHAR2 DEFAULT NULL,
                  X_Attribute10                          VARCHAR2 DEFAULT NULL,
                  X_Attribute11                          VARCHAR2 DEFAULT NULL,
                  X_Attribute12                          VARCHAR2 DEFAULT NULL,
                  X_Attribute13                          VARCHAR2 DEFAULT NULL,
                  X_Attribute14                          VARCHAR2 DEFAULT NULL,
                  X_Attribute15                          VARCHAR2 DEFAULT NULL);

PROCEDURE Delete_Row(X_Rowid VARCHAR2);

PROCEDURE Get_Unique_Id(X_Unique_Id      IN OUT  NUMBER);

END MRP_SCHEDULE_DATES_PKG;

 

/
