--------------------------------------------------------
--  DDL for Package OKC_XPRT_RULE_PVT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."OKC_XPRT_RULE_PVT" 
/* $Header: OKCVXIRS.pls 120.0.12010000.2 2011/02/07 13:35:53 serukull noship $ */
AUTHID CURRENT_USER AS


 -- g_Success     CONSTANT	VARCHAR2(30) := 'SUCCESS';
 -- g_Error       CONSTANT	VARCHAR2(30) := 'ERROR';
  -- Exceptions
  G_VAL_EXCEPTION EXCEPTION;

  ---------------------------------------------------------------------------
  -- GLOBAL VARIABLES
  ---------------------------------------------------------------------------
  G_PKG_NAME                   CONSTANT   VARCHAR2(200) := 'OKC_XPRT_RULE_PVT';
  G_APP_NAME                   CONSTANT   VARCHAR2(3)   :=  OKC_API.G_APP_NAME;

  ------------------------------------------------------------------------------
  -- GLOBAL CONSTANTS
  ------------------------------------------------------------------------------
  G_FALSE                      CONSTANT   VARCHAR2(1) := FND_API.G_FALSE;
  G_TRUE                       CONSTANT   VARCHAR2(1) := FND_API.G_TRUE;
  G_RET_STS_SUCCESS            CONSTANT   varchar2(1) := FND_API.G_RET_STS_SUCCESS;
  G_RET_STS_ERROR              CONSTANT   varchar2(1) := FND_API.G_RET_STS_ERROR;
  G_RET_STS_UNEXP_ERROR        CONSTANT   varchar2(1) := FND_API.G_RET_STS_UNEXP_ERROR;




TYPE template_rules_rec_type
IS RECORD
( template_rule_id  OKC_XPRT_TEMPLATE_RULES.template_rule_id%TYPE := OKC_API.G_MISS_NUM
, template_id       OKC_XPRT_TEMPLATE_RULES.template_id%TYPE := OKC_API.G_MISS_NUM
, rule_id           OKC_XPRT_TEMPLATE_RULES.rule_id%TYPE     := OKC_API.G_MISS_NUM
, deleted_flag      OKC_XPRT_TEMPLATE_RULES.deleted_flag%TYPE    := OKC_API.G_MISS_CHAR
, published_flag    OKC_XPRT_TEMPLATE_RULES.published_flag%TYPE   := OKC_API.G_MISS_CHAR
, object_version_number OKC_XPRT_TEMPLATE_RULES.object_version_number%TYPE := OKC_API.G_MISS_NUM
, created_by            NUMBER            := OKC_API.G_MISS_NUM
, creation_date         OKC_XPRT_TEMPLATE_RULES.creation_date%TYPE := OKC_API.G_MISS_DATE
, last_updated_by       NUMBER            := OKC_API.G_MISS_NUM
, last_update_date      OKC_XPRT_TEMPLATE_RULES.last_update_date%TYPE := OKC_API.G_MISS_DATE
, last_update_login     NUMBER            := OKC_API.G_MISS_NUM
);
TYPE template_rules_tbl_type IS TABLE OF template_rules_rec_type INDEX BY PLS_INTEGER;


TYPE rule_outcome_rec_type IS RECORD
(      RULE_OUTCOME_ID         OKC_XPRT_RULE_OUTCOMES.RULE_OUTCOME_ID%TYPE       := OKC_API.G_MISS_NUM
,      RULE_ID                 OKC_XPRT_RULE_OUTCOMES.RULE_ID%TYPE               := OKC_API.G_MISS_NUM
,      OBJECT_TYPE             OKC_XPRT_RULE_OUTCOMES.OBJECT_TYPE%TYPE           := OKC_API.G_MISS_CHAR
,      OBJECT_VALUE_ID         OKC_XPRT_RULE_OUTCOMES.OBJECT_VALUE_ID%TYPE       := OKC_API.G_MISS_NUM
,      OBJECT_VERSION_NUMBER   OKC_XPRT_RULE_OUTCOMES.OBJECT_VERSION_NUMBER%TYPE := OKC_API.G_MISS_NUM
,      CREATED_BY              NUMBER            := OKC_API.G_MISS_NUM
,      CREATION_DATE           OKC_XPRT_RULE_OUTCOMES.CREATION_DATE%TYPE         := OKC_API.G_MISS_DATE
,      LAST_UPDATED_BY         NUMBER       := OKC_API.G_MISS_NUM
,      LAST_UPDATE_DATE        OKC_XPRT_RULE_OUTCOMES.LAST_UPDATE_DATE%TYPE      := OKC_API.G_MISS_DATE
,      LAST_UPDATE_LOGIN       NUMBER     := OKC_API.G_MISS_NUM
,      MANDATORY_YN            OKC_XPRT_RULE_OUTCOMES.MANDATORY_YN%TYPE          := OKC_API.G_MISS_CHAR
,      MANDATORY_RWA           OKC_XPRT_RULE_OUTCOMES.MANDATORY_RWA%TYPE         := OKC_API.G_MISS_CHAR
);
TYPE rule_outcome_tbl_type IS TABLE OF rule_outcome_rec_type INDEX BY PLS_INTEGER;

TYPE rule_cond_vals_rec_type IS RECORD
(
       RULE_CONDITION_VALUE_ID   OKC_XPRT_RULE_COND_VALS.RULE_CONDITION_VALUE_ID%TYPE := OKC_API.G_MISS_NUM
,      RULE_CONDITION_ID         OKC_XPRT_RULE_COND_VALS.RULE_CONDITION_ID%TYPE       := OKC_API.G_MISS_NUM
,      OBJECT_VALUE_CODE         OKC_XPRT_RULE_COND_VALS.OBJECT_VALUE_CODE%TYPE       := OKC_API.G_MISS_CHAR
,      OBJECT_VERSION_NUMBER     OKC_XPRT_RULE_COND_VALS.OBJECT_VERSION_NUMBER%TYPE   := OKC_API.G_MISS_NUM
,      CREATED_BY                NUMBER              := OKC_API.G_MISS_NUM
,      CREATION_DATE             OKC_XPRT_RULE_COND_VALS.CREATION_DATE%TYPE           := OKC_API.G_MISS_DATE
,      LAST_UPDATED_BY           NUMBER         := OKC_API.G_MISS_NUM
,      LAST_UPDATE_DATE          OKC_XPRT_RULE_COND_VALS.LAST_UPDATE_DATE%TYPE        := OKC_API.G_MISS_DATE
,      LAST_UPDATE_LOGIN         NUMBER       := OKC_API.G_MISS_NUM
);
TYPE  rule_cond_vals_tbl_type IS TABLE OF rule_cond_vals_rec_type INDEX BY PLS_INTEGER;

TYPE  rule_condition_rec_type IS RECORD
(
       RULE_CONDITION_ID   OKC_XPRT_RULE_CONDITIONS.RULE_CONDITION_ID%TYPE :=  OKC_API.G_MISS_NUM
,      RULE_ID             OKC_XPRT_RULE_CONDITIONS.RULE_ID%TYPE :=            OKC_API.G_MISS_NUM
,      OBJECT_TYPE         OKC_XPRT_RULE_CONDITIONS.OBJECT_TYPE%TYPE :=        OKC_API.G_MISS_CHAR
,      OBJECT_CODE         OKC_XPRT_RULE_CONDITIONS.OBJECT_CODE%TYPE :=        OKC_API.G_MISS_CHAR
,      OBJECT_CODE_DATATYPE OKC_XPRT_RULE_CONDITIONS.OBJECT_CODE_DATATYPE%TYPE := OKC_API.G_MISS_CHAR
,      OPERATOR             OKC_XPRT_RULE_CONDITIONS.OPERATOR%TYPE :=       OKC_API.G_MISS_CHAR
,      OBJECT_VALUE_SET_NAME OKC_XPRT_RULE_CONDITIONS.OBJECT_VALUE_SET_NAME%TYPE :=  OKC_API.G_MISS_CHAR
,      OBJECT_VALUE_TYPE     OKC_XPRT_RULE_CONDITIONS.OBJECT_VALUE_TYPE%TYPE :=   OKC_API.G_MISS_CHAR
,      OBJECT_VALUE_CODE     OKC_XPRT_RULE_CONDITIONS.OBJECT_VALUE_CODE%TYPE :=   OKC_API.G_MISS_CHAR
,      OBJECT_VERSION_NUMBER OKC_XPRT_RULE_CONDITIONS.OBJECT_VERSION_NUMBER%TYPE := OKC_API.G_MISS_NUM
,      CREATED_BY            NUMBER :=  OKC_API.G_MISS_NUM
,      CREATION_DATE         OKC_XPRT_RULE_CONDITIONS.CREATION_DATE%TYPE :=   OKC_API.G_MISS_DATE
,      LAST_UPDATED_BY       NUMBER := OKC_API.G_MISS_NUM
,      LAST_UPDATE_DATE      OKC_XPRT_RULE_CONDITIONS.LAST_UPDATE_DATE%TYPE :=  OKC_API.G_MISS_DATE
,      LAST_UPDATE_LOGIN     NUMBER := OKC_API.G_MISS_NUM
,      rule_cond_vals_tbl    rule_cond_vals_tbl_type
);
TYPE rule_condition_tbl_type IS TABLE OF rule_condition_rec_type INDEX BY PLS_INTEGER;

TYPE rule_header_rec_type IS RECORD
(
 RULE_ID                OKC_XPRT_RULE_HDRS_ALL.RULE_ID%TYPE   :=	OKC_API.G_MISS_NUM
,ORG_ID                 OKC_XPRT_RULE_HDRS_ALL.ORG_ID%TYPE   :=	  OKC_API.G_MISS_NUM
,INTENT                 OKC_XPRT_RULE_HDRS_ALL.INTENT%TYPE   :=	 OKC_API.G_MISS_CHAR
,STATUS_CODE            OKC_XPRT_RULE_HDRS_ALL.STATUS_CODE%TYPE   := OKC_API.G_MISS_CHAR
,RULE_NAME              OKC_XPRT_RULE_HDRS_ALL.RULE_NAME%TYPE   := OKC_API.G_MISS_CHAR
,RULE_DESCRIPTION       OKC_XPRT_RULE_HDRS_ALL.RULE_DESCRIPTION%TYPE   :=	OKC_API.G_MISS_CHAR
,ORG_WIDE_FLAG          OKC_XPRT_RULE_HDRS_ALL.ORG_WIDE_FLAG%TYPE   :=	  OKC_API.G_MISS_CHAR
,PUBLISHED_FLAG         OKC_XPRT_RULE_HDRS_ALL.PUBLISHED_FLAG%TYPE   :=	  OKC_API.G_MISS_CHAR
,CONDITION_EXPR_CODE    OKC_XPRT_RULE_HDRS_ALL.CONDITION_EXPR_CODE%TYPE   :=	OKC_API.G_MISS_CHAR
,REQUEST_ID             NUMBER :=   OKC_API.G_MISS_NUM
,RULE_TYPE              OKC_XPRT_RULE_HDRS_ALL.RULE_TYPE%TYPE   :=	 OKC_API.G_MISS_CHAR
,LINE_LEVEL_FLAG        OKC_XPRT_RULE_HDRS_ALL.LINE_LEVEL_FLAG%TYPE   :=	  OKC_API.G_MISS_CHAR
,OBJECT_VERSION_NUMBER  OKC_XPRT_RULE_HDRS_ALL.OBJECT_VERSION_NUMBER%TYPE   := OKC_API.G_MISS_NUM
,CREATED_BY             NUMBER :=   OKC_API.G_MISS_NUM
,CREATION_DATE          OKC_XPRT_RULE_HDRS_ALL.CREATION_DATE%TYPE   :=	OKC_API.G_MISS_DATE
,LAST_UPDATED_BY        NUMBER :=   OKC_API.G_MISS_NUM
,LAST_UPDATE_DATE       OKC_XPRT_RULE_HDRS_ALL.LAST_UPDATE_DATE%TYPE   :=	 OKC_API.G_MISS_DATE
,LAST_UPDATE_LOGIN      NUMBER :=    OKC_API.G_MISS_NUM
,PROGRAM_ID             NUMBER :=  OKC_API.G_MISS_NUM
,PROGRAM_APPLICATION_ID NUMBER :=  OKC_API.G_MISS_NUM
,PROGRAM_UPDATE_DATE    OKC_XPRT_RULE_HDRS_ALL.PROGRAM_UPDATE_DATE%TYPE   := OKC_API.G_MISS_DATE
);
TYPE rule_header_tbl_type IS TABLE OF rule_header_rec_type INDEX BY PLS_INTEGER;

TYPE rule_rec_type IS RECORD
(
 RULE_HEADER_REC      RULE_HEADER_REC_TYPE
,RULE_CONDITION_TBL   RULE_CONDITION_TBL_TYPE
,RULE_OUTCOME_TBL     RULE_OUTCOME_TBL_TYPE
,TEMPLATE_RULES_TBL       TEMPLATE_RULES_TBL_TYPE
,STATUS VARCHAR2(1)
,ERRMSG VARCHAR2(2500)
);
TYPE RULE_TBL_TYPE IS TABLE OF  RULE_REC_TYPE INDEX BY PLS_INTEGER;

TYPE RULE_CHILD_ENTITY_TBL_TYPE IS TABLE OF NUMBER INDEX BY PLS_INTEGER;

TYPE rule_child_entities_rec_type  IS RECORD
( RULE_ID                   NUMBER
 ,RULE_CONDITION_ID_TBL     RULE_CHILD_ENTITY_TBL_TYPE
 ,RULE_OUTCOME_ID_TBL       RULE_CHILD_ENTITY_TBL_TYPE
 ,TEMPLATE_RULE_ID_TBL      RULE_CHILD_ENTITY_TBL_TYPE
 ,STATUS VARCHAR2(1)
 ,ERRMSG VARCHAR2(2500)
);

TYPE rule_child_entities_tbl_type  IS TABLE OF rule_child_entities_rec_type INDEX BY PLS_INTEGER;


PROCEDURE create_rule(P_RULE_TBL IN OUT NOCOPY RULE_TBL_TYPE
                     ,p_commit   IN VARCHAR2 := FND_API.G_FALSE );

PROCEDURE update_rule(P_RULE_TBL IN OUT NOCOPY RULE_TBL_TYPE
                     ,p_commit   IN VARCHAR2 := FND_API.G_FALSE );

PROCEDURE delete_rule_child_entities(P_RULE_CHILD_ENTITIES_TBL IN OUT NOCOPY rule_child_entities_tbl_type
                                     ,p_commit   IN VARCHAR2 := FND_API.G_FALSE);

END okc_xprt_rule_pvt;

/
