--------------------------------------------------------
--  DDL for Package OKE_API
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."OKE_API" AUTHID CURRENT_USER AS
/* $Header: OKEPAPIS.pls 115.9 2003/03/25 22:43:30 who ship $ */

-- GLOBAL STRUCTURES

 TYPE msg_rec_type IS RECORD (
  	error_status		NUMBER,
	data			VARCHAR2(2000));
 TYPE msg_tbl_type IS TABLE OF msg_rec_type
  	INDEX BY BINARY_INTEGER;

-- GLOBAL CONSTANTS

G_FALSE		CONSTANT VARCHAR2(1) := FND_API.G_FALSE;
G_TRUE		CONSTANT VARCHAR2(1) := FND_API.G_TRUE;
G_MISS_NUM	CONSTANT NUMBER := FND_API.G_MISS_NUM;
G_MISS_CHAR	CONSTANT VARCHAR2(1) := FND_API.G_MISS_CHAR;
G_MISS_DATE	CONSTANT DATE := FND_API.G_MISS_DATE;

-- GLOBAL MESSAGE CONSTANTS

G_FND_APP			CONSTANT VARCHAR2(200) := 'FND';
G_APP_NAME			CONSTANT VARCHAR2(200) := 'OKE';
-- remove line due to bug 2865218 G_FORM_UNABLE_TO_RESERVE_REC	CONSTANT VARCHAR2(200) := 'FORM_UNABLE_TO_RESERVE_RECORD';
G_FORM_UNABLE_TO_RESERVE_REC    CONSTANT VARCHAR2(200) := 'FORM_COULD_NOT_RESERVE_RECORD';


G_FORM_RECORD_DELETED		CONSTANT VARCHAR2(200) := 'FORM_RECORD_DELETED';
G_FORM_RECORD_CHANGED		CONSTANT VARCHAR2(200) := 'FORM_RECORD_CHANGED';
G_RECORD_LOGICALLY_DELETED	CONSTANT VARCHAR2(200) := 'OKE_CONTRACTS_RECORD_LDELETED';
G_REQUIRED_VALUE		CONSTANT VARCHAR2(200) := 'OKE_CONTRACTS_REQUIRED_VALUE';
G_INVALID_VALUE			CONSTANT VARCHAR2(200) := 'OKE_CONTRACTS_INVALID_VALUE';
G_CHILD_RECORD_FOUND		CONSTANT VARCHAR2(200) := 'OKE_CONTRACTS_CHILD_RECORD';
G_NO_PARENT_RECORD		CONSTANT VARCHAR2(200) := 'OKE_CONTRACTS_NO_PARENT_RECORD';
G_UNEXPECTED_ERROR 		CONSTANT VARCHAR2(200) := 'OKE_CONTRACTS_UNEXPECTED_ERROR';

G_COL_NAME_TOKEN		CONSTANT VARCHAR2(200) := 'COL_NAME';
G_PARENT_TABLE_TOKEN		CONSTANT VARCHAR2(200) := 'PARENT_TABLE';
G_CHILD_TABLE_TOKEN		CONSTANT VARCHAR2(200) := 'CHILD_TABLE';
G_SQLERRM_TOKEN 		CONSTANT VARCHAR2(200) := 'ERROR_MESSAGE';
G_SQLCODE_TOKEN 		CONSTANT VARCHAR2(200) := 'ERROR_CODE';




-- ERRORS AND EXCEPTIONS

G_RET_STS_SUCCESS		CONSTANT VARCHAR2(1) := FND_API.G_RET_STS_SUCCESS;
G_RET_STS_WARNING		CONSTANT VARCHAR2(1) := 'W';
G_RET_STS_ERROR			CONSTANT VARCHAR2(1) := FND_API.G_RET_STS_ERROR;
G_RET_STS_UNEXP_ERROR		CONSTANT VARCHAR2(1) := FND_API.G_RET_STS_UNEXP_ERROR;
G_EXCEPTION_ERROR		EXCEPTION;
G_EXCEPTION_UNEXPECTED_ERROR	EXCEPTION;
G_EXC_WARNING			EXCEPTION;

-- GLOBAL VARIABLES

-- Functions and Procedures

PROCEDURE init_msg_list(
	p_init_msg_list			IN VARCHAR2);

FUNCTION start_activity(
	p_api_name			IN VARCHAR2,
	p_pkg_name			IN VARCHAR2,
	p_init_msg_list			IN VARCHAR2,
	l_api_version			IN NUMBER,
	p_api_version			IN NUMBER,
	p_api_type			IN VARCHAR2,
	x_return_status			OUT NOCOPY VARCHAR2
) RETURN VARCHAR2;

FUNCTION start_activity(
	p_api_name			IN VARCHAR2,
	p_init_msg_list			IN VARCHAR2,
	p_api_type			IN VARCHAR2,
	x_return_status			OUT NOCOPY VARCHAR2
) RETURN VARCHAR2;

FUNCTION handle_exceptions (
	p_api_name		IN VARCHAR2,
	p_pkg_name		IN VARCHAR2,
	p_exc_name		IN VARCHAR2,
	x_msg_count		OUT NOCOPY NUMBER,
	x_msg_data		OUT NOCOPY VARCHAR2,
	p_api_type		IN VARCHAR2
) RETURN VARCHAR2;

PROCEDURE end_activity
(
	x_msg_count		OUT NOCOPY NUMBER,
	x_msg_data		OUT NOCOPY VARCHAR2
);

-- Added translation flag by syho on 11-may-01
PROCEDURE set_message (
	p_app_name		IN VARCHAR2 DEFAULT OKE_API.G_APP_NAME,
	p_msg_name		IN VARCHAR2,
	p_token1		IN VARCHAR2 DEFAULT NULL,
	p_token1_value		IN VARCHAR2 DEFAULT NULL,
	p_token1_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token2		IN VARCHAR2 DEFAULT NULL,
	p_token2_value		IN VARCHAR2 DEFAULT NULL,
	p_token2_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token3		IN VARCHAR2 DEFAULT NULL,
	p_token3_value		IN VARCHAR2 DEFAULT NULL,
	p_token3_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token4		IN VARCHAR2 DEFAULT NULL,
	p_token4_value		IN VARCHAR2 DEFAULT NULL,
	p_token4_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token5		IN VARCHAR2 DEFAULT NULL,
	p_token5_value		IN VARCHAR2 DEFAULT NULL,
	p_token5_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token6		IN VARCHAR2 DEFAULT NULL,
	p_token6_value		IN VARCHAR2 DEFAULT NULL,
	p_token6_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token7		IN VARCHAR2 DEFAULT NULL,
	p_token7_value		IN VARCHAR2 DEFAULT NULL,
	p_token7_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token8		IN VARCHAR2 DEFAULT NULL,
	p_token8_value		IN VARCHAR2 DEFAULT NULL,
	p_token8_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token9		IN VARCHAR2 DEFAULT NULL,
	p_token9_value		IN VARCHAR2 DEFAULT NULL,
	p_token9_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE ,
	p_token10		IN VARCHAR2 DEFAULT NULL,
	p_token10_value		IN VARCHAR2 DEFAULT NULL,
	p_token10_translate	IN VARCHAR2 DEFAULT OKE_API.G_FALSE
);
END OKE_API;


 

/
