--------------------------------------------------------
--  DDL for Package OKS_OKSFOSUM_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."OKS_OKSFOSUM_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: OKSFOSUMS.pls 120.2 2007/12/25 07:57:52 nchinnam noship $ */
  P_START_DATE DATE;
  P_START_DATE1 varchar2(15);
  P_END_DATE DATE;
  P_END_DATE1 varchar2(15);
  P_MIN_VAL NUMBER;
  P_MAX_VAL NUMBER;
  P_OPERATING_UNIT NUMBER;
  LP_OPERATING_UNIT NUMBER;
  P_REV_REC_DATE DATE;
  P_REVENUE_RECOGNIZED NUMBER;
  P_CURRENCY_CODE VARCHAR2(32767);
  P_CONTRACT_GROUP NUMBER;
  P_CONTRACT_GROUP_NAME VARCHAR2(300);
  P_ORG_NAME VARCHAR2(300);
  P_CONC_REQUEST_ID NUMBER;
  P_WHERE_CLAUSE VARCHAR2(5000);
  CP_ORG_NAME VARCHAR2(400);
  FUNCTION BEFOREREPORT RETURN BOOLEAN;
  FUNCTION AFTERPFORM RETURN BOOLEAN;
  FUNCTION AFTERREPORT RETURN BOOLEAN;
  FUNCTION P_WHERE_CLAUSE_P RETURN VARCHAR2;
  FUNCTION CP_ORG_NAME_P RETURN VARCHAR2;
END OKS_OKSFOSUM_XMLP_PKG;


/
