--------------------------------------------------------
--  DDL for Package ONT_OEXOEOCR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ONT_OEXOEOCR_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: OEXOEOCRS.pls 120.3 2008/05/05 09:06:37 dwkrishn noship $ */
  P_CONC_REQUEST_ID NUMBER := 0;

  P_SOB_ID NUMBER;

  P_CANCELLED_BY_HIGH VARCHAR2(50);

  P_CANCEL_REASON VARCHAR2(50);

  P_ORDER_BY VARCHAR2(30);

  LP_ORDER_BY varchar2(30);

  P_ORDER_NUM_LOW VARCHAR2(32767);

  P_ORDER_NUM_HIGH VARCHAR2(32767);

  P_CUSTOMER_NAME_LOW VARCHAR2(360);

  P_CUSTOMER_NAME_HIGH VARCHAR2(360);

  P_ITEM_FLEX_CODE VARCHAR2(32767);

  P_ORGANIZATION_ID NUMBER;

  P_CANCEL_DATE_LOW DATE;

  LP_CANCEL_DATE_LOW VARCHAR2(20);

  P_CANCEL_DATE_HIGH DATE;

  LP_CANCEL_DATE_HIGH VARCHAR2(20);

  P_SALESREP_LOW VARCHAR2(240);

  P_SALESREP_HIGH VARCHAR2(240);

  P_USE_FUNCTIONAL_CURRENCY VARCHAR2(5);

  LP_ITEM_FLEX_CODE_HIGH VARCHAR2(600);

  LP_ITEM_FLEX_CODE_LOW VARCHAR2(600);

  LP_ORDER_NUM VARCHAR2(200);

  LP_SALESREP VARCHAR2(240);

  LP_CANCEL_DATE VARCHAR2(500);

  LP_CUSTOMER_NAME VARCHAR2(200);

  P_PRINT_DESCRIPTION VARCHAR2(32767);

  LP_CANCELLED_BY VARCHAR2(1000);

  LP_CANCEL_REASON VARCHAR2(500);

  P_MIXED_PRECISION NUMBER;

  LP_ITEM_FLEX_ALL_SEG VARCHAR2(1000);

  P_ITEM NUMBER;

  P_ITEM_STRUCTURE_NUM NUMBER;

  LP_ORDER_CATEGORY VARCHAR2(500);

  P_ORDER_TYPE VARCHAR2(30);

  LP_ORDER_DATE VARCHAR2(500);

  P_CANCELLED_BY_LOW VARCHAR2(50);

  P_ORDER_DATE_HIGH DATE;

  LP_ORDER_DATE_HIGH  VARCHAR2(20);

  P_ORDER_DATE_LOW DATE;

  LP_ORDER_DATE_LOW VARCHAR2(20);

  P_ORDER_CATEGORY VARCHAR2(32767);

  LP_LINE_CATEGORY VARCHAR2(500);

  P_LINE_CATEGORY VARCHAR2(30);

  P_ITEM_NAME VARCHAR2(200);

  RP_REPORT_NAME VARCHAR2(240);

  RP_SUB_TITLE VARCHAR2(80);

  RP_COMPANY_NAME VARCHAR2(100);

  RP_FUNCTIONAL_CURRENCY VARCHAR2(20);

  RP_DATA_FOUND VARCHAR2(300);

  RP_ITEM_FLEX_LPROMPT VARCHAR2(100);

  RP_ITEM_FLEX_ALL_SEG VARCHAR2(2000) := 'SI.SEGMENT1';

  RP_ITEM_FLEX_APROMPT VARCHAR2(100);

  RP_SALES_REASON_LBL VARCHAR2(15);

  RP_CUSTOMER_RANGE VARCHAR2(42);

  RP_SALESPERSON_RANGE VARCHAR2(42);

  RP_ORDER_RANGE VARCHAR2(82);

  RP_CANCEL_DATE_RANGE VARCHAR2(47);

  RP_SALES_REASON_LBL_2 VARCHAR2(16);

  RP_ORDER_BY VARCHAR2(80);

  RP_CANCEL_REASON VARCHAR2(80);

  RP_USE_FUNCTIONAL_CURRENCY VARCHAR2(80);

  RP_FLEX_OR_DESC VARCHAR2(80);

  RP_ITEM_FLEX_ALL_SEG_WHERE VARCHAR2(1000);

  RP_ORDER_DATE_RANGE VARCHAR2(47);

  RP_CANCELLED_BY_RANGE VARCHAR2(42);

  RP_DATE_LBL VARCHAR2(20);

  CP_UNIT1 VARCHAR2(20);

  CP_UNIT2 VARCHAR2(20);

  RP_DUMMY_ITEM NUMBER;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION P_ITEM_FLEX_CODEVALIDTRIGGER RETURN BOOLEAN;

  FUNCTION P_USE_FUNCTIONAL_CURRENCYVALID RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION C_SET_LBLFORMULA RETURN VARCHAR2;

  FUNCTION C_GL_CONV_RATEFORMULA(CURRENCY_CODE IN VARCHAR2
                                ,ORD_DATE IN DATE
                                ,CONVERSION_TYPE_CODE IN VARCHAR2
                                ,CONVERSION_RATE IN NUMBER) RETURN NUMBER;

  FUNCTION C_AMOUNTFORMULA(CALC_AMOUNT IN NUMBER
                          ,C_GL_CONV_RATE IN NUMBER
                          ,C_PRECISION IN NUMBER) RETURN NUMBER;

  FUNCTION C_CURRENCY_CODEFORMULA(CURRENCY_CODE IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION PR_ORDER_CATEGORYFORMULA RETURN CHAR;

  FUNCTION RP_LINE_CATEGORYFORMULA RETURN VARCHAR2;

  FUNCTION CF_UNIT1FORMULA(UNIT1 IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_UNIT2FORMULA(UNIT2 IN VARCHAR2) RETURN CHAR;

  FUNCTION C_CANCELLED_QTYFORMULA(LINEID IN NUMBER
                                 ,CANCELLED_QTY IN NUMBER) RETURN NUMBER;

  FUNCTION CALC_AMOUNTFORMULA(LINEID IN NUMBER
                             ,CANCELLED_QTY IN NUMBER) RETURN NUMBER;

  FUNCTION C_PRECISIONFORMULA(CURRENCY_CODE IN VARCHAR2) RETURN NUMBER;

  FUNCTION RP_REPORT_NAME_P RETURN VARCHAR2;

  FUNCTION RP_SUB_TITLE_P RETURN VARCHAR2;

  FUNCTION RP_COMPANY_NAME_P RETURN VARCHAR2;

  FUNCTION RP_FUNCTIONAL_CURRENCY_P RETURN VARCHAR2;

  FUNCTION RP_DATA_FOUND_P RETURN VARCHAR2;

  FUNCTION RP_ITEM_FLEX_LPROMPT_P RETURN VARCHAR2;

  FUNCTION RP_ITEM_FLEX_ALL_SEG_P RETURN VARCHAR2;

  FUNCTION RP_ITEM_FLEX_APROMPT_P RETURN VARCHAR2;

  FUNCTION RP_SALES_REASON_LBL_P RETURN VARCHAR2;

  FUNCTION RP_CUSTOMER_RANGE_P RETURN VARCHAR2;

  FUNCTION RP_SALESPERSON_RANGE_P RETURN VARCHAR2;

  FUNCTION RP_ORDER_RANGE_P RETURN VARCHAR2;

  FUNCTION RP_CANCEL_DATE_RANGE_P RETURN VARCHAR2;

  FUNCTION RP_SALES_REASON_LBL_2_P RETURN VARCHAR2;

  FUNCTION RP_ORDER_BY_P RETURN VARCHAR2;

  FUNCTION RP_CANCEL_REASON_P RETURN VARCHAR2;

  FUNCTION RP_USE_FUNCTIONAL_CURRENCY_P RETURN VARCHAR2;

  FUNCTION RP_FLEX_OR_DESC_P RETURN VARCHAR2;

  FUNCTION RP_ITEM_FLEX_ALL_SEG_WHERE_P RETURN VARCHAR2;

  FUNCTION RP_ORDER_DATE_RANGE_P RETURN VARCHAR2;

  FUNCTION RP_CANCELLED_BY_RANGE_P RETURN VARCHAR2;

  FUNCTION RP_DATE_LBL_P RETURN VARCHAR2;

  FUNCTION CP_UNIT1_P RETURN VARCHAR2;

  FUNCTION CP_UNIT2_P RETURN VARCHAR2;

  FUNCTION RP_DUMMY_ITEM_P RETURN NUMBER;

  FUNCTION IS_FIXED_RATE(X_FROM_CURRENCY IN VARCHAR2
                        ,X_TO_CURRENCY IN VARCHAR2
                        ,X_EFFECTIVE_DATE IN DATE) RETURN VARCHAR2;

  PROCEDURE GET_RELATION(X_FROM_CURRENCY IN VARCHAR2
                        ,X_TO_CURRENCY IN VARCHAR2
                        ,X_EFFECTIVE_DATE IN DATE
                        ,X_FIXED_RATE IN OUT NOCOPY BOOLEAN
                        ,X_RELATIONSHIP IN OUT NOCOPY VARCHAR2);

  FUNCTION GET_EURO_CODE RETURN VARCHAR2;

  FUNCTION GET_RATE(X_FROM_CURRENCY IN VARCHAR2
                   ,X_TO_CURRENCY IN VARCHAR2
                   ,X_CONVERSION_DATE IN DATE
                   ,X_CONVERSION_TYPE IN VARCHAR2) RETURN NUMBER;

  FUNCTION GET_RATE(X_SET_OF_BOOKS_ID IN NUMBER
                   ,X_FROM_CURRENCY IN VARCHAR2
                   ,X_CONVERSION_DATE IN DATE
                   ,X_CONVERSION_TYPE IN VARCHAR2) RETURN NUMBER;

  FUNCTION CONVERT_AMOUNT(X_FROM_CURRENCY IN VARCHAR2
                         ,X_TO_CURRENCY IN VARCHAR2
                         ,X_CONVERSION_DATE IN DATE
                         ,X_CONVERSION_TYPE IN VARCHAR2
                         ,X_AMOUNT IN NUMBER) RETURN NUMBER;

  FUNCTION CONVERT_AMOUNT(X_SET_OF_BOOKS_ID IN NUMBER
                         ,X_FROM_CURRENCY IN VARCHAR2
                         ,X_CONVERSION_DATE IN DATE
                         ,X_CONVERSION_TYPE IN VARCHAR2
                         ,X_AMOUNT IN NUMBER) RETURN NUMBER;

  FUNCTION GET_DERIVE_TYPE(SOB_ID IN NUMBER
                          ,PERIOD IN VARCHAR2
                          ,CURR_CODE IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION C_AMOUNT_DSPFORMULA RETURN VARCHAR2;

FUNCTION ITEM_DSPFORMULA
(
ITEM_IDENTIFIER_TYPE_T IN VARCHAR2,
IID IN NUMBER,
SI_ORGANIZATION_ID IN NUMBER,
SI_INVENTORY_ITEM_ID IN NUMBER,
ORDERED_ITEM_ID IN NUMBER,
ORDERED_ITEM IN VARCHAR
)
RETURN CHAR;

END ONT_OEXOEOCR_XMLP_PKG;


/
