--------------------------------------------------------
--  DDL for Package ONT_OEXPRPRS_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ONT_OEXPRPRS_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: OEXPRPRSS.pls 120.1 2007/12/25 07:33:21 npannamp noship $ */
  P_CONC_REQUEST_ID NUMBER := 0;
 F1 VARCHAR2(100);
  P_SOB_ID NUMBER;
  P_ORDER_AMOUNT_LOW NUMBER;
  P_ORDER_AMOUNT_HIGH NUMBER;
  P_ORDER_TYPE_HI VARCHAR2(100);
  P_ORDER_BY VARCHAR2(30);
  P_ORDER_NUM_LOW VARCHAR2(32767);
  P_ORDER_NUM_HIGH VARCHAR2(32767);
  P_CUSTOMER_NAME_HI VARCHAR2(360);
  P_CUSTOMER_NUMBER_HI VARCHAR2(50);
  P_ORGANIZATION_ID VARCHAR2(32767);
  P_AGREEMENT NUMBER;
  P_SALESREP_HI VARCHAR2(50);
  P_OPEN_ORDERS_ONLY VARCHAR2(50);
  P_ORDER_LIST_HIGH NUMBER;
  P_ORDER_LIST_LOW NUMBER;
  P_ORDER_DATE_LOW DATE;
  P_ORDER_DATE_HIGH DATE;
  LP_OPEN_ORDERS_ONLY VARCHAR2(500):='and 1=1';
  LP_ORDER_LIST VARCHAR2(500):='and 1=1';
  LP_ORDER_AMOUNT VARCHAR2(500):='and 1=1';
  LP_ORDER_DATE VARCHAR2(500):='and 1=1';
  LP_AGREEMENT VARCHAR2(5000):='and 1=1';
  LP_ORDER_NUM VARCHAR2(500):='and 1=1';
  LP_ORDER_TYPE VARCHAR2(500):='and 1=1';
  LP_SALESREP VARCHAR2(500):='and 1=1';
  LP_CUSTOMER_NUMBER VARCHAR2(500):='and 1=1';
  LP_CUSTOMER_NAME VARCHAR2(500):='and 1=1';
  LP_HAVING VARCHAR2(1200):=' ';
  P_CUSTOMER_NAME_LO VARCHAR2(360);
  P_CUSTOMER_NUMBER_LO VARCHAR2(50);
  P_SALESREP_LO VARCHAR2(50);
  P_ORDER_TYPE_LO VARCHAR2(100);
  P_ORDER_CATEGORY VARCHAR2(30);
  LP_ORDER_CATEGORY VARCHAR2(500):='and 1=1';
  LP_SORT_BY VARCHAR2(100):=' ';
  LP_LINE_CATEGORY VARCHAR2(500):='and 1=1';
  P_LINE_CATEGORY VARCHAR2(30);
  P_ONE_TIME VARCHAR2(32767);
  L_ORDER_TYPE_LOW VARCHAR2(30);
  L_ORDER_TYPE_HIGH VARCHAR2(30);
  RP_REPORT_NAME VARCHAR2(240);
  RP_SUB_TITLE VARCHAR2(80);
  RP_COMPANY_NAME VARCHAR2(50);
  RP_FUNCTIONAL_CURRENCY VARCHAR2(20);
  RP_DATA_FOUND VARCHAR2(300);
  RP_ORDER_NUMBER_RANGE VARCHAR2(100);
  RP_ORDER_LIST_RANGE VARCHAR2(100);
  RP_ORDER_DATE_RANGE VARCHAR2(100);
  RP_OPEN_ORDERS_ONLY VARCHAR2(80);
  RP_ORDER_AMOUNT_RANGE VARCHAR2(100);
  RP_AGREEMENT_NAME VARCHAR2(240);
  RP_ORDER_TYPE_RANGE VARCHAR2(100);
  RP_CUSTOMER_NUMBER_RANGE VARCHAR2(100);
  RP_CUSTOMER_NAME_RANGE VARCHAR2(100);
  RP_SALESREP_RANGE VARCHAR2(100);
  RP_ORDER_CATEGORY VARCHAR2(100);
  RP_LINE_CATEGORY VARCHAR2(100);
  FUNCTION BEFOREREPORT RETURN BOOLEAN;
  FUNCTION AFTERREPORT RETURN BOOLEAN;
  FUNCTION AFTERPFORM RETURN BOOLEAN;
  FUNCTION RP_ORDER_BYFORMULA RETURN VARCHAR2;
  FUNCTION C_DISCOUNT_PRICEFORMULA(ORDER_AMOUNT IN NUMBER
                                  ,ORDER_LIST IN NUMBER) RETURN NUMBER;
  FUNCTION C_DATA_NOT_FOUNDFORMULA(CURRENCY2 IN VARCHAR2) RETURN NUMBER;
  FUNCTION C_ORDER_AMOUNTFORMULA(ORDER_AMOUNT IN NUMBER
                                ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_LISTFORMULA(ORDER_LIST IN NUMBER
                              ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_DISCOUNT_PRICE_CUFORMULA(S_DISCOUNT_PRICE_CU IN NUMBER
                                     ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_LIST_CUFORMULA(S_ORDER_LIST_CU IN NUMBER
                                 ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_AMOUNT_CUFORMULA(S_ORDER_AMOUNT_CU IN NUMBER
                                   ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_DISCOUNT_PRICE_OTFORMULA(S_DISCOUNT_PRICE_OT IN NUMBER
                                     ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_LIST_OTFORMULA(S_ORDER_LIST_OT IN NUMBER
                                 ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_AMOUNT_OTFORMULA(S_ORDER_AMOUNT_OT IN NUMBER
                                   ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_DISCOUNT_PRCE_CFORMULA(S_DISCOUNT_PRICE_C IN NUMBER
                                   ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_LIST_CFORMULA(S_ORDER_LIST_C IN NUMBER
                                ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_AMOUNT_CFORMULA(S_ORDER_AMOUNT_C IN NUMBER
                                  ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION CF_1FORMULA(CHARGE_PERIODICITY_CODE IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION CF_2FORMULA(S_ORDER_AMOUNT_P IN NUMBER
                      ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_DISCOUNT_PRICE_PFORMULA(S_DISCOUNT_PRICE_P IN NUMBER
                                    ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION C_ORDER_LIST_PFORMULA(S_ORDER_LIST_P IN NUMBER
                                ,C_PRE IN NUMBER) RETURN NUMBER;
  FUNCTION RP_REPORT_NAME_P RETURN VARCHAR2;
  FUNCTION RP_SUB_TITLE_P RETURN VARCHAR2;
  FUNCTION RP_COMPANY_NAME_P RETURN VARCHAR2;
  FUNCTION RP_FUNCTIONAL_CURRENCY_P RETURN VARCHAR2;
  FUNCTION RP_DATA_FOUND_P RETURN VARCHAR2;
  FUNCTION RP_ORDER_NUMBER_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_ORDER_LIST_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_ORDER_DATE_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_OPEN_ORDERS_ONLY_P RETURN VARCHAR2;
  FUNCTION RP_ORDER_AMOUNT_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_AGREEMENT_NAME_P RETURN VARCHAR2;
  FUNCTION RP_ORDER_TYPE_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_CUSTOMER_NUMBER_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_CUSTOMER_NAME_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_SALESREP_RANGE_P RETURN VARCHAR2;
  FUNCTION RP_ORDER_CATEGORY_P RETURN VARCHAR2;
  FUNCTION RP_LINE_CATEGORY_P RETURN VARCHAR2;
END ONT_OEXPRPRS_XMLP_PKG;


/
