--------------------------------------------------------
--  DDL for Package ONT_OEXOECCH_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ONT_OEXOECCH_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: OEXOECCHS.pls 120.1 2007/12/25 07:14:14 npannamp noship $ */
  P_CONC_REQUEST_ID NUMBER := 0;

  P_SOB_ID NUMBER;

  P_ORDER_NUMBER VARCHAR2(32767);

  P_CUSTOMER_NAME VARCHAR2(360);

  P_DATE_HOLD_APPLIED_LOW DATE;

  P_DATE_HOLD_APPLIED_HIGH DATE;

  P_CURRENCY_CODE VARCHAR2(60);

  P_CUSTOMER_NUMBER VARCHAR2(30);

  LP_ORDER_NUMBER VARCHAR2(500):=' ' ;

  LP_DATE_HOLD_APPLIED VARCHAR2(500):=' ';

  LP_CURRENCY_CODE VARCHAR2(500):='  ';

  LP_CUSTOMER_NUMBER VARCHAR2(500):=' ';

  LP_CUSTOMER_NAME VARCHAR2(500):=' ';

  P_ORDER_TYPE VARCHAR2(30);

  LP_ORDER_TYPE VARCHAR2(500):=' ';

  P_VAT_PROFILE VARCHAR2(30);

  L_ORDER_TYPE VARCHAR2(30);

  C_UNINV_ORD_SHIP NUMBER;

  C_UNINV_ORD_CREDIT NUMBER;

  C_REC_BAL_SHIP NUMBER;

  C_REC_BAL_CREDIT NUMBER;

  C_TOT_ORDER_LIMIT NUMBER;

  C_ORDER_LIMIT NUMBER;

  C_REC_BAL_PICK NUMBER;

  C_REC_BAL_PACK NUMBER;

  C_UNINV_ORD_PICK NUMBER;

  C_UNINV_ORD_PACK NUMBER;

  RP_REPORT_NAME VARCHAR2(240);

  RP_SUB_TITLE VARCHAR2(240);

  RP_COMPANY_NAME VARCHAR2(100);

  RP_FUNCTIONAL_CURRENCY VARCHAR2(20);

  RP_DATA_FOUND VARCHAR2(300);

  RP_DATE_HOLD_APPLIED_RANGE VARCHAR2(100);

  RP_SHIP VARCHAR2(100);

  RP_ORDER VARCHAR2(100);

  RP_VAT_PROFILE VARCHAR2(100);

  RP_CURR_PROFILE VARCHAR2(20);

  RP_ORDER_AMOUNT NUMBER;

  RP_TOTAL_AMOUNT NUMBER;

  RP_PICK VARCHAR2(100);

  RP_PACK VARCHAR2(100);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION C_COMPUTE_AMOUNTSFORMULA(SITE_USE_ID IN NUMBER
                                   ,CURRENCY1 IN VARCHAR2
                                   ,CUSTOMER_ID IN NUMBER
                                   ,ENTRY_OPEN_AR_DAYS IN NUMBER
                                   ,ENTRY_OPEN_AR_FLAG IN VARCHAR2
                                   ,SHIP_OPEN_AR_DAYS IN NUMBER
                                   ,SHIP_OPEN_AR_FLAG IN VARCHAR2
                                   ,ENTRY_UNINVOICED_FLAG IN VARCHAR2
                                   ,ENTRY_ON_HOLD_FLAG IN VARCHAR2
                                   ,SHIP_UNINVOICED_FLAG IN VARCHAR2
                                   ,SHIP_ON_HOLD_FLAG IN VARCHAR2
                                   ,ENTRY_SHIPPING_INTERVAL IN NUMBER
                                   ,SHIP_SHIPPING_INTERVAL IN NUMBER
                                   ,ENTRY_RULE_ID IN NUMBER
                                   ,SHIP_RULE_ID IN NUMBER
                                   ,PICK_OPEN_AR_DAYS IN NUMBER
                                   ,PICK_OPEN_AR_FLAG IN VARCHAR2
                                   ,PICK_UNINVOICED_FLAG IN VARCHAR2
                                   ,PICK_ON_HOLD_FLAG IN VARCHAR2
                                   ,PICK_SHIPPING_INTERVAL IN NUMBER
                                   ,PICK_RULE_ID IN NUMBER
                                   ,PACK_OPEN_AR_DAYS IN NUMBER
                                   ,PACK_OPEN_AR_FLAG IN VARCHAR2
                                   ,PACK_UNINVOICED_FLAG IN VARCHAR2
                                   ,PACK_ON_HOLD_FLAG IN VARCHAR2
                                   ,PACK_SHIPPING_INTERVAL IN NUMBER
                                   ,PACK_RULE_ID IN NUMBER) RETURN NUMBER;

  FUNCTION C_DATA_NOT_FOUNDFORMULA(CUSTOMER_NAME IN VARCHAR2) RETURN NUMBER;

  FUNCTION C_ADDRESSFORMULA(ADDRESS1 IN VARCHAR2
                           ,CITY IN VARCHAR2
                           ,STATE IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION C_DAYS_ON_HOLD_CRFORMULA(S_DAYS_ON_HOLD_CR IN NUMBER) RETURN NUMBER;

  FUNCTION C_DAYS_ON_HOLD_CUFORMULA(S_DAYS_ON_HOLD_CU IN NUMBER) RETURN NUMBER;

  FUNCTION C_UNINV_ORD_SHIP_P RETURN NUMBER;

  FUNCTION C_UNINV_ORD_CREDIT_P RETURN NUMBER;

  FUNCTION C_REC_BAL_SHIP_P RETURN NUMBER;

  FUNCTION C_REC_BAL_CREDIT_P RETURN NUMBER;

  FUNCTION C_TOT_ORDER_LIMIT_P RETURN NUMBER;

  FUNCTION C_ORDER_LIMIT_P RETURN NUMBER;

  FUNCTION C_REC_BAL_PICK_P RETURN NUMBER;

  FUNCTION C_REC_BAL_PACK_P RETURN NUMBER;

  FUNCTION C_UNINV_ORD_PICK_P RETURN NUMBER;

  FUNCTION C_UNINV_ORD_PACK_P RETURN NUMBER;

  FUNCTION RP_REPORT_NAME_P RETURN VARCHAR2;

  FUNCTION RP_SUB_TITLE_P RETURN VARCHAR2;

  FUNCTION RP_COMPANY_NAME_P RETURN VARCHAR2;

  FUNCTION RP_FUNCTIONAL_CURRENCY_P RETURN VARCHAR2;

  FUNCTION RP_DATA_FOUND_P RETURN VARCHAR2;

  FUNCTION RP_DATE_HOLD_APPLIED_RANGE_P RETURN VARCHAR2;

  FUNCTION RP_SHIP_P RETURN VARCHAR2;

  FUNCTION RP_ORDER_P RETURN VARCHAR2;

  FUNCTION RP_VAT_PROFILE_P RETURN VARCHAR2;

  FUNCTION RP_CURR_PROFILE_P RETURN VARCHAR2;

  FUNCTION RP_ORDER_AMOUNT_P RETURN NUMBER;

  FUNCTION RP_TOTAL_AMOUNT_P RETURN NUMBER;

  FUNCTION RP_PICK_P RETURN VARCHAR2;

  FUNCTION RP_PACK_P RETURN VARCHAR2;

  FUNCTION ORDER_AMOUNT_DSPFORMULA( currency1 in varchar2,order_amount in number) RETURN VARCHAR2;

  FUNCTION S_ORDER_AMOUNT_CR_DSPFORMULA( currency1 in varchar2,s_order_amount_cr in number) RETURN VARCHAR2;
END ONT_OEXOECCH_XMLP_PKG;


/
