--------------------------------------------------------
--  DDL for Package OTA_DELEGATE_BOOKING_BK1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."OTA_DELEGATE_BOOKING_BK1" AUTHID CURRENT_USER as
/* $Header: otenrapi.pkh 120.13.12010000.6 2009/08/13 07:22:59 smahanka ship $ */
--
-- ----------------------------------------------------------------------------
-- |-------------------------< <CREATE_DELEGATE_BOOKING_b >-------------------|
-- ----------------------------------------------------------------------------
--
procedure create_delegate_booking_b
(
  p_effective_date               in date,
  p_booking_status_type_id       in number,
  p_delegate_person_id           in number,
  p_contact_id                   in number,
  p_business_group_id            in number,
  p_event_id                     in number,
  p_customer_id                  in number,
  p_authorizer_person_id         in number,
  p_date_booking_placed          in date,
  p_corespondent                 in varchar2,
  p_internal_booking_flag        in varchar2,
  p_number_of_places             in number,
  p_administrator                in number,
  p_booking_priority             in varchar2,
  p_comments                     in varchar2,
  p_contact_address_id           in number,
  p_delegate_contact_phone       in varchar2,
  p_delegate_contact_fax         in varchar2,
  p_third_party_customer_id      in number,
  p_third_party_contact_id       in number,
  p_third_party_address_id       in number,
  p_third_party_contact_phone    in varchar2,
  p_third_party_contact_fax      in varchar2,
  p_date_status_changed          in date,
  p_failure_reason               in varchar2,
  p_attendance_result            in varchar2,
  p_language_id                  in number,
  p_source_of_booking            in varchar2,
  p_special_booking_instructions in varchar2,
  p_successful_attendance_flag   in varchar2,
  p_tdb_information_category     in varchar2,
  p_tdb_information1             in varchar2,
  p_tdb_information2             in varchar2,
  p_tdb_information3             in varchar2,
  p_tdb_information4             in varchar2,
  p_tdb_information5             in varchar2,
  p_tdb_information6             in varchar2,
  p_tdb_information7             in varchar2,
  p_tdb_information8             in varchar2,
  p_tdb_information9             in varchar2,
  p_tdb_information10            in varchar2,
  p_tdb_information11            in varchar2,
  p_tdb_information12            in varchar2,
  p_tdb_information13            in varchar2,
  p_tdb_information14            in varchar2,
  p_tdb_information15            in varchar2,
  p_tdb_information16            in varchar2,
  p_tdb_information17            in varchar2,
  p_tdb_information18            in varchar2,
  p_tdb_information19            in varchar2,
  p_tdb_information20            in varchar2,
  p_create_finance_line          in varchar2,
  p_finance_header_id            in number,
  p_currency_code                in varchar2,
  p_standard_amount              in number,
  p_unitary_amount               in number,
  p_money_amount                 in number,
  p_booking_deal_id              in number,
  p_booking_deal_type            in varchar2,
  p_finance_line_id              in number,
  p_enrollment_type              in varchar2,
  p_organization_id              in number,
  p_sponsor_person_id            in number,
  p_sponsor_assignment_id        in number,
  p_person_address_id            in number,
  p_delegate_assignment_id       in number,
  p_delegate_contact_id          in number,
  p_delegate_contact_email       in varchar2,
  p_third_party_email            in varchar2,
  p_person_address_type          in varchar2,
  p_line_id                      in number,
  p_org_id                       in number,
  p_daemon_flag                  in varchar2,
  p_daemon_type                  in varchar2,
  p_old_event_id                 in number,
  p_quote_line_id                in number,
  p_interface_source             in varchar2,
  p_total_training_time          in varchar2,
  p_content_player_status        in varchar2,
  p_score                        in number,
  p_completed_content            in number,
  p_total_content                in number ,
  p_booking_justification_id     in number,
  p_is_history_flag		 in varchar2,
  p_is_mandatory_enrollment      in varchar2
);
  --
-- ----------------------------------------------------------------------------
-- |-------------------------< <CREATE_DELEGATE_BOOKING_a >-------------------|
-- ----------------------------------------------------------------------------
--
procedure create_delegate_booking_a
(
  p_effective_date               in date,
  p_booking_status_type_id       in number,
  p_delegate_person_id           in number,
  p_contact_id                   in number,
  p_business_group_id            in number,
  p_event_id                     in number,
  p_customer_id                  in number,
  p_authorizer_person_id         in number,
  p_date_booking_placed          in date,
  p_corespondent                 in varchar2,
  p_internal_booking_flag        in varchar2,
  p_number_of_places             in number,
  p_administrator                in number,
  p_booking_priority             in varchar2,
  p_comments                     in varchar2,
  p_contact_address_id           in number,
  p_delegate_contact_phone       in varchar2,
  p_delegate_contact_fax         in varchar2,
  p_third_party_customer_id      in number,
  p_third_party_contact_id       in number,
  p_third_party_address_id       in number,
  p_third_party_contact_phone    in varchar2,
  p_third_party_contact_fax      in varchar2,
  p_date_status_changed          in date,
  p_failure_reason               in varchar2,
  p_attendance_result            in varchar2,
  p_language_id                  in number,
  p_source_of_booking            in varchar2,
  p_special_booking_instructions in varchar2,
  p_successful_attendance_flag   in varchar2,
  p_tdb_information_category     in varchar2,
  p_tdb_information1             in varchar2,
  p_tdb_information2             in varchar2,
  p_tdb_information3             in varchar2,
  p_tdb_information4             in varchar2,
  p_tdb_information5             in varchar2,
  p_tdb_information6             in varchar2,
  p_tdb_information7             in varchar2,
  p_tdb_information8             in varchar2,
  p_tdb_information9             in varchar2,
  p_tdb_information10            in varchar2,
  p_tdb_information11            in varchar2,
  p_tdb_information12            in varchar2,
  p_tdb_information13            in varchar2,
  p_tdb_information14            in varchar2,
  p_tdb_information15            in varchar2,
  p_tdb_information16            in varchar2,
  p_tdb_information17            in varchar2,
  p_tdb_information18            in varchar2,
  p_tdb_information19            in varchar2,
  p_tdb_information20            in varchar2,
  p_create_finance_line          in varchar2,
  p_finance_header_id            in number,
  p_currency_code                in varchar2,
  p_standard_amount              in number,
  p_unitary_amount               in number,
  p_money_amount                 in number,
  p_booking_deal_id              in number,
  p_booking_deal_type            in varchar2,
  p_finance_line_id              in number,
  p_enrollment_type              in varchar2,
  p_organization_id              in number,
  p_sponsor_person_id            in number,
  p_sponsor_assignment_id        in number,
  p_person_address_id            in number,
  p_delegate_assignment_id       in number,
  p_delegate_contact_id          in number,
  p_delegate_contact_email       in varchar2,
  p_third_party_email            in varchar2,
  p_person_address_type          in varchar2,
  p_line_id                      in number,
  p_org_id                       in number,
  p_daemon_flag                  in varchar2,
  p_daemon_type                  in varchar2,
  p_old_event_id                 in number,
  p_quote_line_id                in number,
  p_interface_source             in varchar2,
  p_total_training_time          in varchar2,
  p_content_player_status        in varchar2,
  p_score                        in number,
  p_completed_content            in number,
  p_total_content                in number,
  p_booking_justification_id     in number,
  p_is_history_flag		 in varchar2,
  p_is_mandatory_enrollment      in varchar2,
  p_booking_id                   in number
);
--
end OTA_DELEGATE_BOOKING_BK1 ;

/
