--------------------------------------------------------
--  DDL for Package PA_PERF_TRANSACTIONS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PA_PERF_TRANSACTIONS_PKG" AUTHID CURRENT_USER as
/* $Header: PAPEEXTS.pls 120.1 2005/08/19 16:38:49 mwasowic noship $ */

procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2, --File.Sql.39 bug 4440895
  X_PERF_TXN_ID in NUMBER,
  X_PERF_TXN_OBJ_TYPE in VARCHAR2,
  X_PERF_TXN_OBJ_ID in NUMBER,
  X_OBJECT_RULE_ID in NUMBER,
  X_RELATED_OBJ_TYPE in VARCHAR2,
  X_RELATED_OBJ_ID in NUMBER,
  X_RULE_ID in NUMBER,
  X_PROJECT_ID in NUMBER,
  X_KPA_CODE in VARCHAR2,
  X_MEASURE_ID in NUMBER,
  X_MEASURE_VALUE in NUMBER,
  X_PERIOD_NAME in VARCHAR2,
  X_INDICATOR_CODE in VARCHAR2,
  X_THRESHOLD_FROM in NUMBER,
  X_THRESHOLD_TO in NUMBER,
  X_WEIGHTING in NUMBER,
  X_PRECISION in NUMBER,
  X_PERIOD_TYPE in VARCHAR2,
  X_CURRENCY_TYPE in VARCHAR2,
  X_MEASURE_FORMAT in VARCHAR2,
  X_PROGRAM_ID in NUMBER,
  X_DATE_CHECKED in DATE,
  X_EXCEPTION_FLAG in VARCHAR2,
  X_CURRENT_FLAG in VARCHAR2,
  X_INCLUDED_IN_SCORING in VARCHAR2,
  X_RECORD_VERSION_NUMBER in NUMBER DEFAULT 1,
  X_CREATION_DATE in DATE DEFAULT sysdate ,
  X_CREATED_BY in NUMBER DEFAULT fnd_global.user_id,
  X_LAST_UPDATE_DATE in DATE DEFAULT sysdate,
  X_LAST_UPDATED_BY in NUMBER DEFAULT fnd_global.user_id,
  X_LAST_UPDATE_LOGIN in NUMBER DEFAULT fnd_global.login_id
);

procedure LOCK_ROW (
  X_PERF_TXN_ID in NUMBER,
  X_RECORD_VERSION_NUMBER in NUMBER
);

procedure UPDATE_ROW (
  X_PERF_TXN_ID in NUMBER,
  X_PERF_TXN_OBJ_TYPE in VARCHAR2,
  X_PERF_TXN_OBJ_ID in NUMBER,
  X_OBJECT_RULE_ID in NUMBER,
  X_RELATED_OBJ_TYPE in VARCHAR2,
  X_RELATED_OBJ_ID in NUMBER,
  X_RULE_ID in NUMBER,
  X_PROJECT_ID in NUMBER,
  X_KPA_CODE in VARCHAR2,
  X_MEASURE_ID in NUMBER,
  X_MEASURE_VALUE in NUMBER,
  X_PERIOD_NAME in VARCHAR2,
  X_INDICATOR_CODE in VARCHAR2,
  X_THRESHOLD_FROM in NUMBER,
  X_THRESHOLD_TO in NUMBER,
  X_WEIGHTING in NUMBER,
  X_PRECISION in NUMBER,
  X_PERIOD_TYPE in VARCHAR2,
  X_CURRENCY_TYPE in VARCHAR2,
  X_MEASURE_FORMAT in VARCHAR2,
  X_PROGRAM_ID in NUMBER,
  X_DATE_CHECKED in DATE,
  X_EXCEPTION_FLAG in VARCHAR2,
  X_CURRENT_FLAG in VARCHAR2,
  X_INCLUDED_IN_SCORING in VARCHAR2,
  X_RECORD_VERSION_NUMBER in NUMBER,
  X_LAST_UPDATE_DATE in DATE  DEFAULT sysdate,
  X_LAST_UPDATED_BY in NUMBER DEFAULT fnd_global.user_id,
  X_LAST_UPDATE_LOGIN in NUMBER  DEFAULT fnd_global.login_id
);

procedure DELETE_ROW (
  X_PERF_TXN_ID in NUMBER
);

end PA_PERF_TRANSACTIONS_PKG;

 

/
