--------------------------------------------------------
--  DDL for Package PA_PAUBRUER_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PA_PAUBRUER_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PAUBRUERS.pls 120.0 2008/01/02 11:04:57 krreddy noship $ */
  P_GL_PERIOD_NAME VARCHAR2(30);

  P_DEBUG_MODE VARCHAR2(3);

  P_CONC_REQUEST_ID NUMBER;

  P_FROM_PROJECT_NUMBER VARCHAR2(30);

  P_TO_PROJECT_NUMBER VARCHAR2(30);

  C_COMPANY_NAME_HEADER VARCHAR2(50);

  C_NO_DATA_FOUND VARCHAR2(80);

  C_DUMMY_DATA NUMBER;

  C_RETCODE VARCHAR2(32767);

  CURR_CODE VARCHAR2(15);

  C_ERROR_BUF VARCHAR2(80);

  FUNCTION GET_COVER_PAGE_VALUES RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION GET_ALL_NAMES RETURN BOOLEAN;

  FUNCTION BEFOREPFORM RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION C_COMPANY_NAME_HEADER_P RETURN VARCHAR2;

  FUNCTION C_NO_DATA_FOUND_P RETURN VARCHAR2;

  FUNCTION C_DUMMY_DATA_P RETURN NUMBER;

  FUNCTION C_RETCODE_P RETURN VARCHAR2;

  FUNCTION CURR_CODE_P RETURN VARCHAR2;

  FUNCTION C_ERROR_BUF_P RETURN VARCHAR2;

END PA_PAUBRUER_XMLP_PKG;

/
