--------------------------------------------------------
--  DDL for Package PA_PAXSIADJ_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PA_PAXSIADJ_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PAXSIADJS.pls 120.0 2008/01/02 12:18:16 krreddy noship $ */
  P_FROM_AWARD_NUMBER VARCHAR2(15);
  P_TO_AWARD_NUMBER VARCHAR2(15);
  P_TO_PROJECT_NUMBER VARCHAR2(25);
  P_FROM_PROJECT_NUMBER VARCHAR2(25);
  P_EXPENDITURE_ORG_ID NUMBER;
  P_VENDOR_ID NUMBER;
  P_INVOICE_ID NUMBER;
  P_PO_HEADER_ID NUMBER;
  P_TRANSACTION_TYPE VARCHAR2(10);
  P_ADJUSTMENT_TYPE VARCHAR2(10);
  P_FROM_GL_ACCOUNT VARCHAR2(1000);
  P_TO_GL_ACCOUNT VARCHAR2(1000);
  P_SORT_ORDER VARCHAR2(2);
  P_GMS_WHERE VARCHAR2(2000);
  P_ACC_WHERE VARCHAR2(2000);
  P_INV_REV_ADJ_WHERE VARCHAR2(2000);
  P_RCV_REV_ADJ_WHERE VARCHAR2(2000);
  P_PAY_REV_ADJ_WHERE VARCHAR2(2000);
  P_ORDER_BY VARCHAR2(2000);
  P_DEBUG_MODE VARCHAR2(1);
  P_TASK_ID NUMBER;
  P_IS_GRANTS_INSTALLED VARCHAR2(1):='N';
  P_FROM_GL_DATE DATE;
  P_TO_GL_DATE DATE;
  P_CONC_REQUEST_ID NUMBER;
  P_FROM_GL_PERIOD VARCHAR2(15);
  P_TO_GL_PERIOD VARCHAR2(15);
  P_LEDGER_ID NUMBER;
  P_CURRENCY_CODE VARCHAR2(15);
  P_PERIOD_SET_NAME VARCHAR2(15);
  P_COA_ID NUMBER;
  P_INV_PA_ADJ_WHERE VARCHAR2(2000);
  P_RCV_PA_ADJ_WHERE VARCHAR2(2000);
  P_PAY_PA_ADJ_WHERE VARCHAR2(2000);
  FUNCTION BEFOREREPORT RETURN BOOLEAN;
  FUNCTION AFTERREPORT RETURN BOOLEAN;
  FUNCTION CF_COMPANY_NAMEFORMULA RETURN CHAR;
  FUNCTION CF_NO_DATA_FOUNDFORMULA(CS_COUNT IN NUMBER) RETURN CHAR;
  FUNCTION CF_AWARD_NUMBERFORMULA(TRANSACTION_ID IN NUMBER) RETURN CHAR;
END PA_PAXSIADJ_XMLP_PKG;

/
