--------------------------------------------------------
--  DDL for Package PA_PAPERACR_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PA_PAPERACR_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PAPERACRS.pls 120.0 2008/01/02 11:01:35 krreddy noship $ */
  P_PROJECT_NUMBER_FROM VARCHAR2(25);

  P_PROJECT_NUMBER_TO VARCHAR2(25);

  P_DEBUG_MODE VARCHAR2(1);

  P_ACTION_SET_TYPE_CODE VARCHAR2(30);

  P_CONC_REQUEST_ID NUMBER := 0;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION BEFOREPFORM RETURN BOOLEAN;

END PA_PAPERACR_XMLP_PKG;

/
