--------------------------------------------------------
--  DDL for Package PA_PAUPGRRL_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PA_PAUPGRRL_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PAUPGRRLS.pls 120.1 2008/04/18 06:11:58 krreddy noship $ */
  P_RULE_OPTIMIZER VARCHAR2(3);

  P_DEBUG_MODE VARCHAR2(3);

  lp_debug_mode VARCHAR2(3);

  P_CONC_REQUEST_ID NUMBER;

  P_RESOURCE_LIST NUMBER;

 -- C_COMPANY_NAME_HEADER VARCHAR2(50);

  C_NO_DATA_FOUND VARCHAR2(80);

  C_DUMMY_DATA NUMBER;

  C_RESOURCE_LIST VARCHAR2(60);

  C_RETCODE NUMBER;

  FUNCTION GET_COVER_PAGE_VALUES RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

 -- FUNCTION GET_COMPANY_NAME RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION GET_RESOURCE_LIST_NAME RETURN BOOLEAN;

 -- FUNCTION C_COMPANY_NAME_HEADER_P RETURN VARCHAR2;

  FUNCTION C_NO_DATA_FOUND_P RETURN VARCHAR2;

  FUNCTION C_DUMMY_DATA_P RETURN NUMBER;

  FUNCTION C_RESOURCE_LIST_P RETURN VARCHAR2;

  FUNCTION C_RETCODE_P RETURN NUMBER;

END PA_PAUPGRRL_XMLP_PKG;

/
