--------------------------------------------------------
--  DDL for Package PA_PAXTRTRX_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PA_PAXTRTRX_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PAXTRTRXS.pls 120.0 2008/01/02 12:19:43 krreddy noship $ */
  P_RULE_OPTIMIZER VARCHAR2(3);
  P_DEBUG_MODE VARCHAR2(3);
  P_CONC_REQUEST_ID NUMBER;
  P_TRX_SOURCE VARCHAR2(30);
  P_BATCH_NAME VARCHAR2(240);
  P_XFACE_ID NUMBER;
  P_USER_ID NUMBER;
  LP_user_id  number;
  P_PURGEABLE VARCHAR2(1);
  P_STATUS NUMBER;
  C_COMPANY_NAME_HEADER VARCHAR2(50);
  C_NO_DATA_FOUND VARCHAR2(80);
  C_DUMMY_DATA NUMBER;
  C_ERROR_CODE NUMBER;
  C_ERROR_MSG VARCHAR2(512);
  FUNCTION GET_COVER_PAGE_VALUES RETURN BOOLEAN;
  FUNCTION BEFOREREPORT RETURN BOOLEAN;
  FUNCTION GET_COMPANY_NAME RETURN BOOLEAN;
  FUNCTION AFTERREPORT RETURN BOOLEAN;
  FUNCTION C_COMPANY_NAME_HEADER_P RETURN VARCHAR2;
  FUNCTION C_NO_DATA_FOUND_P RETURN VARCHAR2;
  FUNCTION C_DUMMY_DATA_P RETURN NUMBER;
  FUNCTION C_ERROR_CODE_P RETURN NUMBER;
  FUNCTION C_ERROR_MSG_P RETURN VARCHAR2;
  PROCEDURE SET_ERROR_STATUS;
  FUNCTION GET_ERROR_STATUS RETURN BOOLEAN;
END PA_PAXTRTRX_XMLP_PKG;

/
