--------------------------------------------------------
--  DDL for Package PAY_PAYMENT_METHODS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PAY_PAYMENT_METHODS_PKG" AUTHID CURRENT_USER AS
/* $Header: pyppm01t.pkh 120.0 2005/05/29 07:41:08 appldev noship $ */

   PROCEDURE INSERT_ROW(P_ROWID                         IN OUT NOCOPY VARCHAR2,
                        P_PERSONAL_PAYMENT_METHOD_ID    IN OUT NOCOPY NUMBER,
                        P_EFFECTIVE_START_DATE          DATE,
                        P_EFFECTIVE_END_DATE            DATE,
                        P_BUSINESS_GROUP_ID             NUMBER,
                        P_EXTERNAL_ACCOUNT_ID           NUMBER,
                        P_ASSIGNMENT_ID                 NUMBER,
                        P_PERSON_ID                     NUMBER,
                        P_RUN_TYPE_ID                   NUMBER,
                        P_ORG_PAYMENT_METHOD_ID         NUMBER,
                        P_AMOUNT                        NUMBER,
                        P_COMMENT_ID                    NUMBER,
                        P_PERCENTAGE                    NUMBER,
                        P_PRIORITY                      NUMBER,
                        P_PAYEE_TYPE                    VARCHAR2,
                        P_PAYEE_ID                      NUMBER,
                        P_ATTRIBUTE_CATEGORY            VARCHAR2,
                        P_ATTRIBUTE1                    VARCHAR2,
                        P_ATTRIBUTE2                    VARCHAR2,
                        P_ATTRIBUTE3                    VARCHAR2,
                        P_ATTRIBUTE4                    VARCHAR2,
                        P_ATTRIBUTE5                    VARCHAR2,
                        P_ATTRIBUTE6                    VARCHAR2,
                        P_ATTRIBUTE7                    VARCHAR2,
                        P_ATTRIBUTE8                    VARCHAR2,
                        P_ATTRIBUTE9                    VARCHAR2,
                        P_ATTRIBUTE10                   VARCHAR2,
                        P_ATTRIBUTE11                   VARCHAR2,
                        P_ATTRIBUTE12                   VARCHAR2,
                        P_ATTRIBUTE13                   VARCHAR2,
                        P_ATTRIBUTE14                   VARCHAR2,
                        P_ATTRIBUTE15                   VARCHAR2,
                        P_ATTRIBUTE16                   VARCHAR2,
                        P_ATTRIBUTE17                   VARCHAR2,
                        P_ATTRIBUTE18                   VARCHAR2,
                        P_ATTRIBUTE19                   VARCHAR2,
                        P_ATTRIBUTE20                   VARCHAR2,
                        P_PRENOTE_DATE                  DATE,
/** sbilling **/
                        P_TERRITORY_CODE                VARCHAR2,
                        P_PPM_INFORMATION_CATEGORY      VARCHAR2,
                        P_PPM_INFORMATION1              VARCHAR2,
                        P_PPM_INFORMATION2              VARCHAR2,
                        P_PPM_INFORMATION3              VARCHAR2,
                        P_PPM_INFORMATION4              VARCHAR2,
                        P_PPM_INFORMATION5              VARCHAR2,
                        P_PPM_INFORMATION6              VARCHAR2,
                        P_PPM_INFORMATION7              VARCHAR2,
                        P_PPM_INFORMATION8              VARCHAR2,
                        P_PPM_INFORMATION9              VARCHAR2,
                        P_PPM_INFORMATION10             VARCHAR2,
                        P_PPM_INFORMATION11             VARCHAR2,
                        P_PPM_INFORMATION12             VARCHAR2,
                        P_PPM_INFORMATION13             VARCHAR2,
                        P_PPM_INFORMATION14             VARCHAR2,
                        P_PPM_INFORMATION15             VARCHAR2,
                        P_PPM_INFORMATION16             VARCHAR2,
                        P_PPM_INFORMATION17             VARCHAR2,
                        P_PPM_INFORMATION18             VARCHAR2,
                        P_PPM_INFORMATION19             VARCHAR2,
                        P_PPM_INFORMATION20             VARCHAR2,
                        P_PPM_INFORMATION21             VARCHAR2,
                        P_PPM_INFORMATION22             VARCHAR2,
                        P_PPM_INFORMATION23             VARCHAR2,
                        P_PPM_INFORMATION24             VARCHAR2,
                        P_PPM_INFORMATION25             VARCHAR2,
                        P_PPM_INFORMATION26             VARCHAR2,
                        P_PPM_INFORMATION27             VARCHAR2,
                        P_PPM_INFORMATION28             VARCHAR2,
                        P_PPM_INFORMATION29             VARCHAR2,
                        P_PPM_INFORMATION30             VARCHAR2
);
--
   PROCEDURE UPDATE_ROW(P_ROWID                         VARCHAR2,
                        P_PERSONAL_PAYMENT_METHOD_ID    NUMBER,
                        P_EFFECTIVE_START_DATE          DATE,
                        P_EFFECTIVE_END_DATE            DATE,
                        P_BUSINESS_GROUP_ID             NUMBER,
                        P_EXTERNAL_ACCOUNT_ID           NUMBER,
                        P_ASSIGNMENT_ID                 NUMBER,
                        P_PERSON_ID                     NUMBER,
                        P_RUN_TYPE_ID                   NUMBER,
                        P_ORG_PAYMENT_METHOD_ID         NUMBER,
                        P_AMOUNT                        NUMBER,
                        P_COMMENT_ID                    NUMBER,
                        P_PERCENTAGE                    NUMBER,
                        P_PRIORITY                      NUMBER,
                        P_PAYEE_TYPE                    VARCHAR2,
                        P_PAYEE_ID                      NUMBER,
                        P_ATTRIBUTE_CATEGORY            VARCHAR2,
                        P_ATTRIBUTE1                    VARCHAR2,
                        P_ATTRIBUTE2                    VARCHAR2,
                        P_ATTRIBUTE3                    VARCHAR2,
                        P_ATTRIBUTE4                    VARCHAR2,
                        P_ATTRIBUTE5                    VARCHAR2,
                        P_ATTRIBUTE6                    VARCHAR2,
                        P_ATTRIBUTE7                    VARCHAR2,
                        P_ATTRIBUTE8                    VARCHAR2,
                        P_ATTRIBUTE9                    VARCHAR2,
                        P_ATTRIBUTE10                   VARCHAR2,
                        P_ATTRIBUTE11                   VARCHAR2,
                        P_ATTRIBUTE12                   VARCHAR2,
                        P_ATTRIBUTE13                   VARCHAR2,
                        P_ATTRIBUTE14                   VARCHAR2,
                        P_ATTRIBUTE15                   VARCHAR2,
                        P_ATTRIBUTE16                   VARCHAR2,
                        P_ATTRIBUTE17                   VARCHAR2,
                        P_ATTRIBUTE18                   VARCHAR2,
                        P_ATTRIBUTE19                   VARCHAR2,
                        P_ATTRIBUTE20                   VARCHAR2,
                        P_PRENOTE_DATE                  DATE,
/** sbilling **/
                        P_TERRITORY_CODE                VARCHAR2,
                        P_PPM_INFORMATION_CATEGORY      VARCHAR2,
                        P_PPM_INFORMATION1              VARCHAR2,
                        P_PPM_INFORMATION2              VARCHAR2,
                        P_PPM_INFORMATION3              VARCHAR2,
                        P_PPM_INFORMATION4              VARCHAR2,
                        P_PPM_INFORMATION5              VARCHAR2,
                        P_PPM_INFORMATION6              VARCHAR2,
                        P_PPM_INFORMATION7              VARCHAR2,
                        P_PPM_INFORMATION8              VARCHAR2,
                        P_PPM_INFORMATION9              VARCHAR2,
                        P_PPM_INFORMATION10             VARCHAR2,
                        P_PPM_INFORMATION11             VARCHAR2,
                        P_PPM_INFORMATION12             VARCHAR2,
                        P_PPM_INFORMATION13             VARCHAR2,
                        P_PPM_INFORMATION14             VARCHAR2,
                        P_PPM_INFORMATION15             VARCHAR2,
                        P_PPM_INFORMATION16             VARCHAR2,
                        P_PPM_INFORMATION17             VARCHAR2,
                        P_PPM_INFORMATION18             VARCHAR2,
                        P_PPM_INFORMATION19             VARCHAR2,
                        P_PPM_INFORMATION20             VARCHAR2,
                        P_PPM_INFORMATION21             VARCHAR2,
                        P_PPM_INFORMATION22             VARCHAR2,
                        P_PPM_INFORMATION23             VARCHAR2,
                        P_PPM_INFORMATION24             VARCHAR2,
                        P_PPM_INFORMATION25             VARCHAR2,
                        P_PPM_INFORMATION26             VARCHAR2,
                        P_PPM_INFORMATION27             VARCHAR2,
                        P_PPM_INFORMATION28             VARCHAR2,
                        P_PPM_INFORMATION29             VARCHAR2,
                        P_PPM_INFORMATION30             VARCHAR2
);
--
   PROCEDURE DELETE_ROW(P_ROWID                 VARCHAR2,
                        P_PPM_ID                NUMBER,
                        P_AFTER_THIS_DATE       DATE,
                        P_PAYEE_TYPE            VARCHAR2);
--
   PROCEDURE LOCK_ROW(P_ROWID                           VARCHAR2,
                        P_PERSONAL_PAYMENT_METHOD_ID    NUMBER,
                        P_EFFECTIVE_START_DATE          DATE,
                        P_EFFECTIVE_END_DATE            DATE,
                        P_BUSINESS_GROUP_ID             NUMBER,
                        P_EXTERNAL_ACCOUNT_ID           NUMBER,
                        P_ASSIGNMENT_ID                 NUMBER,
                        P_PERSON_ID                     NUMBER,
                        P_RUN_TYPE_ID                   NUMBER,
                        P_ORG_PAYMENT_METHOD_ID         NUMBER,
                        P_AMOUNT                        NUMBER,
                        P_COMMENT_ID                    NUMBER,
                        P_PERCENTAGE                    NUMBER,
                        P_PRIORITY                      NUMBER,
                        P_PAYEE_TYPE                    VARCHAR2,
                        P_PAYEE_ID                      NUMBER,
                        P_ATTRIBUTE_CATEGORY            VARCHAR2,
                        P_ATTRIBUTE1                    VARCHAR2,
                        P_ATTRIBUTE2                    VARCHAR2,
                        P_ATTRIBUTE3                    VARCHAR2,
                        P_ATTRIBUTE4                    VARCHAR2,
                        P_ATTRIBUTE5                    VARCHAR2,
                        P_ATTRIBUTE6                    VARCHAR2,
                        P_ATTRIBUTE7                    VARCHAR2,
                        P_ATTRIBUTE8                    VARCHAR2,
                        P_ATTRIBUTE9                    VARCHAR2,
                        P_ATTRIBUTE10                   VARCHAR2,
                        P_ATTRIBUTE11                   VARCHAR2,
                        P_ATTRIBUTE12                   VARCHAR2,
                        P_ATTRIBUTE13                   VARCHAR2,
                        P_ATTRIBUTE14                   VARCHAR2,
                        P_ATTRIBUTE15                   VARCHAR2,
                        P_ATTRIBUTE16                   VARCHAR2,
                        P_ATTRIBUTE17                   VARCHAR2,
                        P_ATTRIBUTE18                   VARCHAR2,
                        P_ATTRIBUTE19                   VARCHAR2,
                        P_ATTRIBUTE20                   VARCHAR2,
                        P_PRENOTE_DATE                  DATE,
                        P_PPM_INFORMATION_CATEGORY      VARCHAR2,
                        P_PPM_INFORMATION1              VARCHAR2,
                        P_PPM_INFORMATION2              VARCHAR2,
                        P_PPM_INFORMATION3              VARCHAR2,
                        P_PPM_INFORMATION4              VARCHAR2,
                        P_PPM_INFORMATION5              VARCHAR2,
                        P_PPM_INFORMATION6              VARCHAR2,
                        P_PPM_INFORMATION7              VARCHAR2,
                        P_PPM_INFORMATION8              VARCHAR2,
                        P_PPM_INFORMATION9              VARCHAR2,
                        P_PPM_INFORMATION10             VARCHAR2,
                        P_PPM_INFORMATION11             VARCHAR2,
                        P_PPM_INFORMATION12             VARCHAR2,
                        P_PPM_INFORMATION13             VARCHAR2,
                        P_PPM_INFORMATION14             VARCHAR2,
                        P_PPM_INFORMATION15             VARCHAR2,
                        P_PPM_INFORMATION16             VARCHAR2,
                        P_PPM_INFORMATION17             VARCHAR2,
                        P_PPM_INFORMATION18             VARCHAR2,
                        P_PPM_INFORMATION19             VARCHAR2,
                        P_PPM_INFORMATION20             VARCHAR2,
                        P_PPM_INFORMATION21             VARCHAR2,
                        P_PPM_INFORMATION22             VARCHAR2,
                        P_PPM_INFORMATION23             VARCHAR2,
                        P_PPM_INFORMATION24             VARCHAR2,
                        P_PPM_INFORMATION25             VARCHAR2,
                        P_PPM_INFORMATION26             VARCHAR2,
                        P_PPM_INFORMATION27             VARCHAR2,
                        P_PPM_INFORMATION28             VARCHAR2,
                        P_PPM_INFORMATION29             VARCHAR2,
                        P_PPM_INFORMATION30             VARCHAR2);
--
   procedure check_asg_on_payroll (p_asg_id     varchar2,
                                   p_new_date   varchar2);
--
   END PAY_PAYMENT_METHODS_PKG;

 

/
