--------------------------------------------------------
--  DDL for Package PAY_PAYIEP30_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PAY_PAYIEP30_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PAYIEP30S.pls 120.3 2008/03/26 12:53:31 amakrish noship $ */
  P_BUSINESS_GROUP_ID NUMBER;

  P_CONC_REQUEST_ID NUMBER;

  P_P30_ACTION_ID VARCHAR2(40);

  P_SUPPLEMENTARY_RUN VARCHAR2(32767);
  LP_SUPPLEMENTARY_RUN VARCHAR2(32767);

  P_REPORT_MODE VARCHAR2(32767);
  LP_REPORT_MODE VARCHAR2(32767);

  P_START_DATE DATE;

  P_END_DATE DATE;
  P_START_DATE1 varchar2(40);

  P_END_DATE1 varchar2(40);

format_mask varchar2(25) := 'DD-MON-YYYY';
  P_REPORT_DATE VARCHAR2(30);
  LP_REPORT_DATE VARCHAR2(30);

  P_SORT_BY VARCHAR2(32767);

  CP_PAYE_YTD NUMBER;

  CP_EE_PRSI_YTD NUMBER;

  CP_ER_PRSI_YTD NUMBER;

  CP_TOTAL_PRSI_REPORT NUMBER;

  CP_TOTAL_PRSI_YTD NUMBER;

  CP_PAYE_PTD NUMBER;

  CP_EE_PRSI_PTD NUMBER;

  CP_ER_PRSI_PTD NUMBER;

  CP_PAYROLL_ID VARCHAR2(60) := 'pact_er.ACTION_INFORMATION2';

  CP_SUPPLEMENTARY_RUN VARCHAR2(80);

  CP_REPORT_DATE DATE;

  CP_ORDER_BY VARCHAR2(100);

  CP_TAX_START_DATE DATE;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_BUSINESS_GROUPFORMULA RETURN VARCHAR2;

  FUNCTION CF_LEGISLATION_CODEFORMULA RETURN VARCHAR2;

  FUNCTION CF_CURRENCY_FORMAT_MASKFORMULA(CF_LEGISLATION_CODE IN VARCHAR2) RETURN VARCHAR2;

  PROCEDURE SET_CURRENCY_FORMAT_MASK;

  FUNCTION P_BUSINESS_GROUP_IDVALIDTRIGGE RETURN BOOLEAN;

  FUNCTION CF_CALCULATE_TOTAL_PRSIFORMULA(REPORT_ID IN NUMBER
                                         ,ASSIGNMENT_ID IN NUMBER) RETURN NUMBER;

  FUNCTION CF_PAYROLL_NAMEFORMULA(PAYROLL_ID IN VARCHAR2) RETURN CHAR;

  FUNCTION CP_PAYE_YTD_P RETURN NUMBER;

  FUNCTION CP_EE_PRSI_YTD_P RETURN NUMBER;

  FUNCTION CP_ER_PRSI_YTD_P RETURN NUMBER;

  FUNCTION CP_TOTAL_PRSI_REPORT_P RETURN NUMBER;

  FUNCTION CP_TOTAL_PRSI_YTD_P RETURN NUMBER;

  FUNCTION CP_PAYE_PTD_P RETURN NUMBER;

  FUNCTION CP_EE_PRSI_PTD_P RETURN NUMBER;

  FUNCTION CP_ER_PRSI_PTD_P RETURN NUMBER;

  FUNCTION CP_PAYROLL_ID_P RETURN VARCHAR2;

  FUNCTION CP_SUPPLEMENTARY_RUN_P RETURN VARCHAR2;

  FUNCTION CP_REPORT_DATE_P RETURN DATE;

  FUNCTION CP_ORDER_BY_P RETURN VARCHAR2;

  FUNCTION CP_TAX_START_DATE_P RETURN DATE;

END PAY_PAYIEP30_XMLP_PKG;

/
