--------------------------------------------------------
--  DDL for Package PFT_VAL_INDEX_FORMULA_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PFT_VAL_INDEX_FORMULA_PKG" AUTHID CURRENT_USER as
/* $Header: PFTVALINDFS.pls 120.0 2005/10/19 19:17:58 appldev noship $ */
procedure INSERT_ROW (
  X_ROWID in out NOCOPY VARCHAR2,
  X_VALUE_INDEX_FORMULA_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DISPLAY_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_VALUE_INDEX_FORMULA_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DISPLAY_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2
);

procedure UPDATE_ROW (
  X_VALUE_INDEX_FORMULA_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER,
  X_DISPLAY_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);

procedure DELETE_ROW (
  X_VALUE_INDEX_FORMULA_ID in NUMBER
);

procedure ADD_LANGUAGE;

end PFT_VAL_INDEX_FORMULA_PKG;
 

/
