--------------------------------------------------------
--  DDL for Package PNT_COMP_SITE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PNT_COMP_SITE_PKG" AUTHID CURRENT_USER AS
  -- $Header: PNTCSITS.pls 120.3 2005/09/09 01:12:07 appldev ship $

PROCEDURE check_unique_company_role ( p_lease_role_type   IN VARCHAR2,
                                      p_company_id        IN NUMBER,
                                      p_company_site_id   IN NUMBER,
                                      p_org_id            IN NUMBER default NULL
                                    );


FUNCTION defined_address_format(p_addr_code IN VARCHAR2) RETURN BOOLEAN;

PROCEDURE insert_row ( x_rowid                   IN OUT NOCOPY VARCHAR2,
                       x_company_site_id         IN OUT NOCOPY NUMBER,
                       x_last_update_date               DATE,
                       x_last_updated_by                NUMBER,
                       x_creation_date                  DATE,
                       x_created_by                     NUMBER,
                       x_last_update_login              NUMBER,
                       x_name                           VARCHAR2,
                       x_company_id                     NUMBER,
                       x_enabled_flag                   VARCHAR2,
                       x_company_site_code              VARCHAR2,
                       x_address_id              IN OUT NOCOPY NUMBER,
                       x_lease_role_type                VARCHAR2,
                       x_attribute_category             VARCHAR2,
                       x_attribute1                     VARCHAR2,
                       x_attribute2                     VARCHAR2,
                       x_attribute3                     VARCHAR2,
                       x_attribute4                     VARCHAR2,
                       x_attribute5                     VARCHAR2,
                       x_attribute6                     VARCHAR2,
                       x_attribute7                     VARCHAR2,
                       x_attribute8                     VARCHAR2,
                       x_attribute9                     VARCHAR2,
                       x_attribute10                    VARCHAR2,
                       x_attribute11                    VARCHAR2,
                       x_attribute12                    VARCHAR2,
                       x_attribute13                    VARCHAR2,
                       x_attribute14                    VARCHAR2,
                       x_attribute15                    VARCHAR2,
                       x_address_line1                  VARCHAR2,
                       x_address_line2                  VARCHAR2,
                       x_address_line3                  VARCHAR2,
                       x_address_line4                  VARCHAR2,
                       x_county                         VARCHAR2,
                       x_city                           VARCHAR2,
                       x_state                          VARCHAR2,
                       x_province                       VARCHAR2,
                       x_zip_code                       VARCHAR2,
                       x_country                        VARCHAR2,
                       x_territory_id                   NUMBER,
                       x_addr_last_update_date          DATE,
                       x_addr_last_updated_by           NUMBER,
                       x_addr_creation_date             DATE,
                       x_addr_created_by                NUMBER,
                       x_addr_last_update_login         NUMBER,
                       x_addr_attribute_category        VARCHAR2,
                       x_addr_attribute1                VARCHAR2,
                       x_addr_attribute2                VARCHAR2,
                       x_addr_attribute3                VARCHAR2,
                       x_addr_attribute4                VARCHAR2,
                       x_addr_attribute5                VARCHAR2,
                       x_addr_attribute6                VARCHAR2,
                       x_addr_attribute7                VARCHAR2,
                       x_addr_attribute8                VARCHAR2,
                       x_addr_attribute9                VARCHAR2,
                       x_addr_attribute10               VARCHAR2,
                       x_addr_attribute11               VARCHAR2,
                       x_addr_attribute12               VARCHAR2,
                       x_addr_attribute13               VARCHAR2,
                       x_addr_attribute14               VARCHAR2,
                       x_addr_attribute15               VARCHAR2,
                       x_org_id                         NUMBER
                     );

PROCEDURE update_row ( x_rowid                          VARCHAR2,
                       x_company_id                     NUMBER,
                       x_company_site_id                NUMBER,
                       x_last_update_date               DATE,
                       x_last_updated_by                NUMBER,
                       x_last_update_login              NUMBER,
                       x_name                           VARCHAR2,
                       x_enabled_flag                   VARCHAR2,
                       x_company_site_code              VARCHAR2,
                       x_lease_role_type                VARCHAR2,
                       x_attribute_category             VARCHAR2,
                       x_attribute1                     VARCHAR2,
                       x_attribute2                     VARCHAR2,
                       x_attribute3                     VARCHAR2,
                       x_attribute4                     VARCHAR2,
                       x_attribute5                     VARCHAR2,
                       x_attribute6                     VARCHAR2,
                       x_attribute7                     VARCHAR2,
                       x_attribute8                     VARCHAR2,
                       x_attribute9                     VARCHAR2,
                       x_attribute10                    VARCHAR2,
                       x_attribute11                    VARCHAR2,
                       x_attribute12                    VARCHAR2,
                       x_attribute13                    VARCHAR2,
                       x_attribute14                    VARCHAR2,
                       x_attribute15                    VARCHAR2,
                       x_address_id                     NUMBER,
                       x_address_line1                  VARCHAR2,
                       x_address_line2                  VARCHAR2,
                       x_address_line3                  VARCHAR2,
                       x_address_line4                  VARCHAR2,
                       x_county                         VARCHAR2,
                       x_city                           VARCHAR2,
                       x_state                          VARCHAR2,
                       x_province                       VARCHAR2,
                       x_zip_code                       VARCHAR2,
                       x_country                        VARCHAR2,
                       x_territory_id                   NUMBER,
                       x_addr_last_update_date          DATE,
                       x_addr_last_updated_by           NUMBER,
                       x_addr_last_update_login         NUMBER,
                       x_addr_attribute_category        VARCHAR2,
                       x_addr_attribute1                VARCHAR2,
                       x_addr_attribute2                VARCHAR2,
                       x_addr_attribute3                VARCHAR2,
                       x_addr_attribute4                VARCHAR2,
                       x_addr_attribute5                VARCHAR2,
                       x_addr_attribute6                VARCHAR2,
                       x_addr_attribute7                VARCHAR2,
                       x_addr_attribute8                VARCHAR2,
                       x_addr_attribute9                VARCHAR2,
                       x_addr_attribute10               VARCHAR2,
                       x_addr_attribute11               VARCHAR2,
                       x_addr_attribute12               VARCHAR2,
                       x_addr_attribute13               VARCHAR2,
                       x_addr_attribute14               VARCHAR2,
                       x_addr_attribute15               VARCHAR2
                     );

PROCEDURE lock_row   ( x_rowid                          VARCHAR2,
                       x_company_site_id                NUMBER,
                       x_name                           VARCHAR2,
                       x_company_id                     NUMBER,
                       x_enabled_flag                   VARCHAR2,
                       x_company_site_code              VARCHAR2,
                       x_address_id                     NUMBER,
                       x_lease_role_type                VARCHAR2,
                       x_attribute_category             VARCHAR2,
                       x_attribute1                     VARCHAR2,
                       x_attribute2                     VARCHAR2,
                       x_attribute3                     VARCHAR2,
                       x_attribute4                     VARCHAR2,
                       x_attribute5                     VARCHAR2,
                       x_attribute6                     VARCHAR2,
                       x_attribute7                     VARCHAR2,
                       x_attribute8                     VARCHAR2,
                       x_attribute9                     VARCHAR2,
                       x_attribute10                    VARCHAR2,
                       x_attribute11                    VARCHAR2,
                       x_attribute12                    VARCHAR2,
                       x_attribute13                    VARCHAR2,
                       x_attribute14                    VARCHAR2,
                       x_attribute15                    VARCHAR2,
                       x_address_line1                  VARCHAR2,
                       x_address_line2                  VARCHAR2,
                       x_address_line3                  VARCHAR2,
                       x_address_line4                  VARCHAR2,
                       x_county                         VARCHAR2,
                       x_city                           VARCHAR2,
                       x_state                          VARCHAR2,
                       x_province                       VARCHAR2,
                       x_zip_code                       VARCHAR2,
                       x_country                        VARCHAR2,
                       x_territory_id                   NUMBER,
                       x_addr_attribute_category        VARCHAR2,
                       x_addr_attribute1                VARCHAR2,
                       x_addr_attribute2                VARCHAR2,
                       x_addr_attribute3                VARCHAR2,
                       x_addr_attribute4                VARCHAR2,
                       x_addr_attribute5                VARCHAR2,
                       x_addr_attribute6                VARCHAR2,
                       x_addr_attribute7                VARCHAR2,
                       x_addr_attribute8                VARCHAR2,
                       x_addr_attribute9                VARCHAR2,
                       x_addr_attribute10               VARCHAR2,
                       x_addr_attribute11               VARCHAR2,
                       x_addr_attribute12               VARCHAR2,
                       x_addr_attribute13               VARCHAR2,
                       x_addr_attribute14               VARCHAR2,
                       x_addr_attribute15               VARCHAR2
                     );
END PNT_COMP_SITE_PKG;

 

/
