--------------------------------------------------------
--  DDL for Package PO_RCOTOLERANCE_PVT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PO_RCOTOLERANCE_PVT" AUTHID CURRENT_USER AS
/* $Header: POXVRTWS.pls 120.2.12010000.6 2008/11/25 08:21:47 rojain ship $*/
-- Indexes for tolerance values

  TOL_REQTOTAL_IND  CONSTANT NUMBER := 1;

  TOL_REQTOTAL_AMT_IND  CONSTANT NUMBER := 2;

  TOL_UNITPRICE_IND  CONSTANT NUMBER := 3;

  TOL_LINEQTY_IND  CONSTANT NUMBER := 4;

  TOL_LINEAMT_IND  CONSTANT NUMBER := 5;

  TOL_LINEAMT_AMT_IND  CONSTANT NUMBER := 6;

  TOL_STARTDATE_IND  CONSTANT NUMBER := 7;

  TOL_ENDDATE_IND  CONSTANT NUMBER := 8;

  TOL_NEEDBY_IND  CONSTANT NUMBER := 9;

  FUNCTION GET_NEW_DISTRIBUTION_QTY(P_REQ_ID  IN NUMBER,P_GRP_ID  IN NUMBER,P_REQ_LINE_ID  IN NUMBER,P_REQ_DIST_ID  IN NUMBER) RETURN NUMBER;

  FUNCTION GET_NEW_LINE_QUANTITY(P_REQ_ID  IN NUMBER,P_REQ_LINE_ID  IN NUMBER,P_GRP_ID  IN NUMBER) RETURN NUMBER;

  FUNCTION CHANGE_WITHIN_TOL_DATE(P_OLDVALUE  IN DATE,P_NEWVALUE  IN DATE,P_MAXINCREMENT  IN NUMBER,P_MAXDECREMENT  IN NUMBER) RETURN VARCHAR2;

  FUNCTION CHANGE_WITHIN_TOL_PERCENT(P_OLDVALUE  IN NUMBER,P_NEWVALUE  IN NUMBER,P_MAXINCREMENT  IN NUMBER,P_MAXDECREMENT  IN NUMBER) RETURN VARCHAR2;

  FUNCTION CHANGE_WITHIN_TOL_AMOUNT(P_OLDVALUE  IN NUMBER,P_NEWVALUE  IN NUMBER,P_MAXINCREMENT  IN NUMBER,P_MAXDECREMENT  IN NUMBER) RETURN VARCHAR2;

  FUNCTION CHANGES_WITHIN_TOL(P_OLDVALUE  IN NUMBER,P_NEWVALUE  IN NUMBER,P_MAXINCREMENT  IN NUMBER,P_MAXDECREMENT  IN NUMBER,P_MAXINCREMENTAMOUNT  IN NUMBER,P_MAXDECREMENTAMOUNT  IN NUMBER) RETURN VARCHAR2;

  PROCEDURE SET_APPROVAL_REQUIRED_FLAG(P_CHREQGRP_ID  IN NUMBER,X_APPR_STATUS  OUT NOCOPY VARCHAR2,P_SOURCE_TYPE_CODE  IN VARCHAR2 DEFAULT NULL);
END PO_RCOTOLERANCE_PVT;

/
