--------------------------------------------------------
--  DDL for Package PSB_PSBRPCAL_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PSB_PSBRPCAL_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PSBRPCALS.pls 120.0 2008/01/07 10:36:39 vijranga noship $ */
  P_BUDGET_CALENDAR_ID VARCHAR2(40);

  C_NLS_NO_DATA_EXISTS VARCHAR2(80);

  C_NLS_END_OF_REPORT VARCHAR2(80);

  P_CONC_REQUEST_ID VARCHAR2(15);

  CP_CALENDAR VARCHAR2(30);

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION BEFOREPFORM RETURN BOOLEAN;

  FUNCTION BETWEENPAGE RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION C_NLS_NO_DATA_EXISTS_P RETURN VARCHAR2;

  FUNCTION C_NLS_END_OF_REPORT_P RETURN VARCHAR2;

  FUNCTION P_CONC_REQUEST_ID_P RETURN VARCHAR2;

  FUNCTION CP_CALENDAR_P RETURN VARCHAR2;

END PSB_PSBRPCAL_XMLP_PKG;






/
