--------------------------------------------------------
--  DDL for Package PSB_PSBRPBRS_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PSB_PSBRPBRS_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PSBRPBRSS.pls 120.0.12010000.3 2010/06/07 12:06:48 hyaman ship $ */
  P_BUDGET_REVISION_ID NUMBER;

  P_CONC_REQUEST_ID NUMBER := 0;

  CP_ORIGINAL_BUDGET NUMBER := 0;

  CP_END_OF_REPORT VARCHAR2(50);

  CP_NO_DATA_FOUND VARCHAR2(50);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION CP_ORIGINAL_BUDGETFORMULA(CF_ORIGINAL_BUDGET IN NUMBER) RETURN NUMBER;

  FUNCTION CF_ORIGINAL_BUDGETFORMULA(CODE_COMBINATION_ID IN NUMBER
                                    ,BUDGET_GROUP_ID IN NUMBER
                                    ,START_PERIOD IN VARCHAR2
                                    ,GL_BUDGET_VERSION_ID IN NUMBER
                                    ,SET_OF_BOOKS_ID IN NUMBER
                                    ,END_PERIOD IN VARCHAR2
                                    ,CURRENCY_CODE IN VARCHAR2) RETURN NUMBER;

  FUNCTION CF_PERCENT_CHANGEFORMULA(BUDGET_BALANCE IN NUMBER
                                   ,REVISION_AMOUNT IN NUMBER) RETURN NUMBER;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_ACCT_FLEX_DESCFORMULA(CHART_OF_ACCOUNTS_ID IN NUMBER
                                   ,CODE_COMBINATION_ID IN NUMBER) RETURN CHAR;

  FUNCTION CF_CURRENCY_CODEFORMULA RETURN CHAR;

  FUNCTION CF_DOCUMENT_POSTING_STATUSFORM(CURRENCY_CODE IN VARCHAR2) RETURN NUMBER;

  FUNCTION CP_ORIGINAL_BUDGET_P RETURN NUMBER;

  FUNCTION CP_END_OF_REPORT_P RETURN VARCHAR2;

  FUNCTION CP_NO_DATA_FOUND_P RETURN VARCHAR2;

END PSB_PSBRPBRS_XMLP_PKG;


/
