--------------------------------------------------------
--  DDL for Package PSP_PSPLDAWD_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."PSP_PSPLDAWD_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: PSPLDAWDS.pls 120.5 2007/10/29 07:23:35 amakrish noship $ */
  P_AWARD_ID VARCHAR2(2550);

  P_CONC_REQUEST_ID NUMBER;

  P_BUSINESS_GROUP_ID NUMBER;

  P_SET_OF_BOOKS_ID NUMBER;

  P_START_DATE DATE;

  P_END_DATE DATE;

  P_AWD_TEMPLATE_ID NUMBER;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION BEFOREPFORM(ORIENTATION IN VARCHAR2) RETURN BOOLEAN;

  FUNCTION CF_EMPLOYEE_NUMBERFORMULA RETURN VARCHAR2;

  FUNCTION CF_INSTITUTION_NAMEFORMULA RETURN VARCHAR2;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION CF_CURRENCY_FORMATFORMULA(CURRENCY_CODE IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_SUM_CURRENCY_CODEFORMULA(CURRENCY_CODE IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_CURR_AWD_AMT_TOTALFORMULA(CF_CURRENCY_FORMAT IN VARCHAR2
                                       ,CS_CURR_AWD_AMT_TOTAL IN NUMBER) RETURN CHAR;

  FUNCTION CF_EARNINGS_AMOUNTFORMULA(CF_CURRENCY_FORMAT IN VARCHAR2
                                    ,EARNINGS_AMOUNT IN NUMBER) RETURN CHAR;

  FUNCTION CF_AWARD_NAMEFORMULA(AWARD_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_EMPLOYEE_NAMEFORMULA(PERSON_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_ASSIGNMENT_NUMBERFORMULA(ASSIGNMENT_ID IN NUMBER
                                      ,PERSON_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_ELEMENT_NAMEFORMULA(ELEMENT_TYPE_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION CF_TIME_PERIOD_NAMEFORMULA(TIME_PERIOD_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CF_DATE_FORMATFORMULA RETURN CHAR;

  FUNCTION CF_START_DATE_DISPLAYFORMULA(CF_DATE_FORMAT IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_END_DATE_DISPFORMULA(CF_DATE_FORMAT IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_CHARGING_INSTRUCTIONSFORMUL(EXPENDITURE_ORGANIZATION_ID IN NUMBER
                                         ,TASK_ID IN NUMBER
                                         ,PROJECT_ID IN NUMBER
                                         --,CF_AWARD_NAME IN VARCHAR2
					  ,AWARD_ID IN VARCHAR2
                                         ,EXPENDITURE_TYPE IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_DATE_RUNFORMULA(CF_DATE_FORMAT IN VARCHAR2) RETURN CHAR;

  PROCEDURE PUT(NAME IN VARCHAR2
               ,VAL IN VARCHAR2);

  FUNCTION DEFINED(NAME IN VARCHAR2) RETURN BOOLEAN;

  PROCEDURE GET(NAME IN VARCHAR2
               ,VAL OUT NOCOPY VARCHAR2);

  FUNCTION VALUE(NAME IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION SAVE_USER(X_NAME IN VARCHAR2
                    ,X_VALUE IN VARCHAR2) RETURN BOOLEAN;

  FUNCTION SAVE(X_NAME IN VARCHAR2
               ,X_VALUE IN VARCHAR2
               ,X_LEVEL_NAME IN VARCHAR2
               ,X_LEVEL_VALUE IN VARCHAR2
               ,X_LEVEL_VALUE_APP_ID IN VARCHAR2) RETURN BOOLEAN;

  PROCEDURE GET_SPECIFIC(NAME_Z IN VARCHAR2
                        ,USER_ID_Z IN NUMBER
                        ,RESPONSIBILITY_ID_Z IN NUMBER
                        ,APPLICATION_ID_Z IN NUMBER
                        ,VAL_Z OUT NOCOPY VARCHAR2
                        ,DEFINED_Z OUT NOCOPY BOOLEAN);

  FUNCTION VALUE_SPECIFIC(NAME IN VARCHAR2
                         ,USER_ID IN NUMBER
                         ,RESPONSIBILITY_ID IN NUMBER
                         ,APPLICATION_ID IN NUMBER) RETURN VARCHAR2;

  PROCEDURE INITIALIZE(USER_ID_Z IN NUMBER
                      ,RESPONSIBILITY_ID_Z IN NUMBER
                      ,APPLICATION_ID_Z IN NUMBER
                      ,SITE_ID_Z IN NUMBER);

  PROCEDURE PUTMULTIPLE(NAMES IN VARCHAR2
                       ,VALS IN VARCHAR2
                       ,NUM IN NUMBER);

END PSP_PSPLDAWD_XMLP_PKG;

/
