--------------------------------------------------------
--  DDL for Package QPR_PRICE_PLANS_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."QPR_PRICE_PLANS_PKG" AUTHID CURRENT_USER as
/* $Header: QPRUPPLS.pls 120.0 2007/12/24 20:04:21 vinnaray noship $ */
procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_PRICE_PLAN_ID in NUMBER,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_LOGIN_ID in NUMBER,
  X_INSTANCE_ID in NUMBER,
  X_AW_TYPE_CODE in VARCHAR2,
  X_AW_STATUS_CODE in VARCHAR2,
  X_TEMPLATE_FLAG in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_AW_CODE in VARCHAR2,
  X_AW_CREATED_FLAG in VARCHAR2,
  X_START_DATE in DATE,
  X_END_DATE in DATE,
  X_BASE_UOM_CODE in VARCHAR2,
  X_USE_FOR_DEAL_FLAG in VARCHAR2,
  X_CURRENCY_CODE in VARCHAR2,
  X_AW_XML in CLOB,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER);
procedure LOCK_ROW (
  X_PRICE_PLAN_ID in NUMBER,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_LOGIN_ID in NUMBER,
  X_INSTANCE_ID in NUMBER,
  X_AW_TYPE_CODE in VARCHAR2,
  X_AW_STATUS_CODE in VARCHAR2,
  X_TEMPLATE_FLAG in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_AW_CODE in VARCHAR2,
  X_AW_CREATED_FLAG in VARCHAR2,
  X_START_DATE in DATE,
  X_END_DATE in DATE,
  X_BASE_UOM_CODE in VARCHAR2,
  X_USE_FOR_DEAL_FLAG in VARCHAR2,
  X_CURRENCY_CODE in VARCHAR2,
  X_AW_XML in CLOB,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2
);
procedure UPDATE_ROW (
  X_PRICE_PLAN_ID in NUMBER,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_LOGIN_ID in NUMBER,
  X_INSTANCE_ID in NUMBER,
  X_AW_TYPE_CODE in VARCHAR2,
  X_AW_STATUS_CODE in VARCHAR2,
  X_TEMPLATE_FLAG in VARCHAR2,
  X_SEEDED_FLAG in VARCHAR2,
  X_AW_CODE in VARCHAR2,
  X_AW_CREATED_FLAG in VARCHAR2,
  X_START_DATE in DATE,
  X_END_DATE in DATE,
  X_BASE_UOM_CODE in VARCHAR2,
  X_USE_FOR_DEAL_FLAG in VARCHAR2,
  X_CURRENCY_CODE in VARCHAR2,
  X_AW_XML in CLOB,
  X_NAME in VARCHAR2,
  X_DESCRIPTION in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER
);
procedure DELETE_ROW (
  X_PRICE_PLAN_ID in NUMBER
);
procedure ADD_LANGUAGE;
end QPR_PRICE_PLANS_PKG;

/
