--------------------------------------------------------
--  DDL for Package WIP_WIPMTLCT_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."WIP_WIPMTLCT_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: WIPMTLCTS.pls 120.1 2008/01/31 12:29:46 npannamp noship $ */
  P_SORT NUMBER;

  P_FROM_JOB_ID VARCHAR2(80);

  P_TO_JOB_ID VARCHAR2(80);

  P_FROM_ASSEMBLY_ID VARCHAR2(800);

  P_TO_ASSEMBLY_ID VARCHAR2(800);
  p_flex_num number := 101;

  P_FROM_DEPARTMENT_ID VARCHAR2(15);

  P_TO_DEPARTMENT_ID VARCHAR2(15);

  P_STRUCT_NUM VARCHAR2(15);

  P_CONC_REQUEST_ID NUMBER := 0;

  P_ORGANIZATION_ID NUMBER;

  P_FLEXWHERE VARCHAR2(2500);

  P_ASSY_FLEX VARCHAR2(850);

  P_ASSY_ORDER VARCHAR2(850);

  P_QTY_PRECISION NUMBER;

  P_FROM_LINE VARCHAR2(10);

  P_TO_LINE VARCHAR2(10);

  P_DEBUG NUMBER;

  FUNCTION LIMIT_JOBS RETURN CHARACTER;

  FUNCTION LIMIT_LINES RETURN CHARACTER;

  FUNCTION LIMIT_ASSEMBLYFORMULA RETURN VARCHAR2;

  FUNCTION LIMIT_DEPARTMENTS RETURN CHARACTER;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION C_ORDER1 RETURN CHARACTER;

  FUNCTION C_ORDER2 RETURN CHARACTER;

  FUNCTION C_ASSY_ORDER RETURN CHARACTER;

  FUNCTION C_SORT_LIST RETURN CHARACTER;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

END WIP_WIPMTLCT_XMLP_PKG;


/
