--------------------------------------------------------
--  DDL for Package WIP_MOVE_ALLOC_CLEANUP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."WIP_MOVE_ALLOC_CLEANUP" AUTHID CURRENT_USER AS
/* $Header: wipmacls.pls 115.6 2002/11/28 13:23:39 rmahidha ship $ */

  TYPE TRANSACTION_ID_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.TRANSACTION_ID%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE REPETITIVE_SCHEDULE_ID_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.REPETITIVE_SCHEDULE_ID%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE ORGANIZATION_ID_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.ORGANIZATION_ID%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE LAST_UPDATE_DATE_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.LAST_UPDATE_DATE%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE LAST_UPDATED_BY_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.LAST_UPDATED_BY%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE CREATION_DATE_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.CREATION_DATE%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE CREATED_BY_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.CREATED_BY%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE LAST_UPDATE_LOGIN_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.LAST_UPDATE_LOGIN%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE REQUEST_ID_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.REQUEST_ID%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE PROGRAM_APPLICATION_ID_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.PROGRAM_APPLICATION_ID%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE PROGRAM_ID_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.PROGRAM_ID%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE PROGRAM_UPDATE_DATE_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.PROGRAM_UPDATE_DATE%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE TRANSACTION_QUANTITY_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.TRANSACTION_QUANTITY%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE PRIMARY_QUANTITY_T IS TABLE OF
  WIP_MOVE_TXN_ALLOCATIONS.PRIMARY_QUANTITY%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE WIP_MOVE_TXN_ALLOCATIONS_REC IS RECORD (
    NUMRECS NUMBER,
    TRANSACTION_ID TRANSACTION_ID_T,
    REPETITIVE_SCHEDULE_ID REPETITIVE_SCHEDULE_ID_T,
    ORGANIZATION_ID ORGANIZATION_ID_T,
    LAST_UPDATE_DATE LAST_UPDATE_DATE_T,
    LAST_UPDATED_BY LAST_UPDATED_BY_T,
    CREATION_DATE CREATION_DATE_T,
    CREATED_BY CREATED_BY_T,
    LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN_T,
    REQUEST_ID REQUEST_ID_T,
    PROGRAM_APPLICATION_ID PROGRAM_APPLICATION_ID_T,
    PROGRAM_ID PROGRAM_ID_T,
    PROGRAM_UPDATE_DATE PROGRAM_UPDATE_DATE_T,
    TRANSACTION_QUANTITY TRANSACTION_QUANTITY_T,
    PRIMARY_QUANTITY PRIMARY_QUANTITY_T
  );

  procedure fetch_and_delete(
    p_mov_grp_id in     number,
    p_mov_allocs in out nocopy wip_move_txn_allocations_rec);

  procedure insert_rows(
    p_mov_allocs in wip_move_txn_allocations_rec);

END WIP_MOVE_ALLOC_CLEANUP;

 

/
