--------------------------------------------------------
--  DDL for Package WMS_WMSSTCON_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."WMS_WMSSTCON_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: WMSSTCONS.pls 120.3 2007/12/25 08:02:23 nchinnam noship $ */
  P_CONC_REQUEST_ID NUMBER := 0;

  P_WHERE_CLAUSE VARCHAR2(1000) := '1 = 1';

  P_ORG_ID NUMBER;

  P_TRIP_ID NUMBER;

  P_DELIVERY_ID NUMBER;

  P_SALES_ORDER_HEADER_ID NUMBER;

  P_ITEM_FLEX_DATA VARCHAR2(1000);

  P_LOC_FLEX_DATA VARCHAR2(1000);

  RP_REPORT_NAME VARCHAR2(200) := 'Consolidation Report ';

  P_MULTIPLE_YES VARCHAR2(5);

  P_MULTIPLE_NO VARCHAR2(5);

  P_MULTIPLE_ASSOCIATION_CHECK NUMBER;

  P_CUSTOMER_ID NUMBER;

  P_ORDER_TYPE_ID NUMBER;

  P_ORDER_ITEM VARCHAR2(500);

  P_ORDER_LOC VARCHAR2(500);

  P_TRIP_NAME VARCHAR2(30);

  P_DELIVERY_NAME VARCHAR2(30);

  P_SALES_ORDER NUMBER;

  P_CUSTOMER_NAME VARCHAR2(50);

  P_ORG_CODE VARCHAR2(5);

  P_ORG_NAME VARCHAR2(240);

  P_CUSTOMER_NUMBER VARCHAR2(30);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION INMULTIPLESOFORMULA(LPN_ID IN NUMBER) RETURN CHAR;

  FUNCTION INMULTIPLEDELIVERYFORMULA(LPN_ID IN NUMBER) RETURN CHAR;

  FUNCTION INMULTIPLETRIPFORMULA(LPN_ID IN NUMBER) RETURN CHAR;

  FUNCTION P_TRIP_NAME_P RETURN VARCHAR2;

  FUNCTION P_DELIVERY_NAME_P RETURN VARCHAR2;

  FUNCTION P_SALES_ORDER_P RETURN NUMBER;

  FUNCTION P_CUSTOMER_NAME_P RETURN VARCHAR2;

  FUNCTION P_ORG_CODE_P RETURN VARCHAR2;

  FUNCTION P_ORG_NAME_P RETURN VARCHAR2;

  FUNCTION P_CUSTOMER_NUMBER_P RETURN VARCHAR2;

END WMS_WMSSTCON_XMLP_PKG;


/
