--------------------------------------------------------
--  DDL for Package WMS_WMSASNI_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."WMS_WMSASNI_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: WMSASNIBIS.pls 120.1 2008/03/18 05:44:09 dwkrishn noship $ */

  P_CHECK_REVISION VARCHAR2(1);

  ORG_ID VARCHAR2(40);

  P_SHIPMENT_NUMBER VARCHAR2(32767);

  P_CBO_FLAG NUMBER;

  P_TRACE_FLAG NUMBER;

  P_CHECK_LOT_NUMBER VARCHAR2(1);

  P_CHECK_LOT_ATTRIBUTES VARCHAR2(1);

  P_CONC_REQUEST_ID NUMBER := 0;

  P_ITEM_ID VARCHAR2(32767);

  P_CHECK_LPN VARCHAR2(1);

  P_CHECK_SER_NUMBER VARCHAR2(32767);

  P_CHECK_SER_ATTRIBUTES VARCHAR2(32767);

  P_VENDOR_ID VARCHAR2(40);

  P_VENDOR_SITE_ID VARCHAR2(40);

  P_FROM_DATE VARCHAR2(30);

  P_END_DATE VARCHAR2(30);

  P_SHOW_ONLY_DISC VARCHAR2(40);

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION BETWEENPAGE RETURN BOOLEAN;

  FUNCTION CF_1FORMULA RETURN CHAR;

  FUNCTION CF_3FORMULA RETURN CHAR;

  FUNCTION CF_2FORMULA(ITEM_ID IN NUMBER) RETURN CHAR;

  FUNCTION CF_4FORMULA RETURN NUMBER;

  FUNCTION CF_5FORMULA RETURN NUMBER;

  FUNCTION CF_6FORMULA RETURN CHAR;

  FUNCTION CF_7FORMULA RETURN NUMBER;

  FUNCTION CF_8FORMULA RETURN NUMBER;

  FUNCTION CF_9FORMULA(VENDOR_ID1 IN NUMBER) RETURN CHAR;

END WMS_WMSASNI_XMLP_PKG;


/
