--------------------------------------------------------
--  DDL for Package WSH_WSHRDLAB_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."WSH_WSHRDLAB_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: WSHRDLABS.pls 120.3.12010000.2 2009/03/20 09:42:19 gbhargav ship $ */
  P_NO_DATA_FOUND VARCHAR2(1);

  P_TRIP_STOP_ID NUMBER;

  CP_DEPARTURE_DATE_HIGH date;

  P_DEPARTURE_DATE_LOW DATE;

  P_DEPARTURE_DATE_HIGH DATE;

  P_FREIGHT_CODE VARCHAR2(60);

  P_DELIVERY_ID NUMBER;

  P_CONTAINER_ID VARCHAR2(60);

  P_ORGANIZATION_ID NUMBER;

  LP_CONTAINER_ID VARCHAR2(128);

  LP_MASTER_FLAG VARCHAR2(128);

  LP_DELIVERY_ID VARCHAR2(60);

  LP_FREIGHT_CODE VARCHAR2(60);

  LP_ORGANIZATION_ID VARCHAR2(60);

  LP_TRIP_STOP_ID VARCHAR2(250);

  LP_DATE_RANGE VARCHAR2(256);

  LP_TRIP_ID VARCHAR2(350);

  P_TRIP_ID NUMBER;

  P_CONC_REQUEST_ID NUMBER := 0;

  CP_CONTACT_PHONE VARCHAR2(50);

  CP_ADDRESSEE VARCHAR2(1000);

  CP_DELIVER_TO_LOCATION_ID NUMBER;

  CP_SHIP_TO_ADDRESS1 VARCHAR2(240);

  CP_SHIP_TO_ADDRESS2 VARCHAR2(240);

  CP_SHIP_TO_ADDRESS3 VARCHAR2(240);

  CP_SHIP_TO_CSZ VARCHAR2(245);

  CP_SHIP_TO_COUNTRY VARCHAR2(60);

  CP_DEL_TO_ADDRESS1 VARCHAR2(240);

  CP_DEL_TO_ADDRESS2 VARCHAR2(240);

  CP_DEL_TO_ADDRESS3 VARCHAR2(240);

  CP_DEL_TO_CSZ VARCHAR2(245);

  CP_DEL_TO_COUNTRY VARCHAR2(60);

  P_STANDALONE VARCHAR2(1); --STANDALONE CHANGES

  FUNCTION CF_ORDER_NUMBERFORMULA(DELIVERY_DETAIL_ID IN NUMBER) RETURN VARCHAR2;

  FUNCTION CP_SHIP_TO_ADDRESS1FORMULA RETURN CHAR;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION CF_SHIP_TO_CUST_NAMEFORMULA(C_SHIP_TO_SITE_USE_ID IN NUMBER) RETURN CHAR;

  FUNCTION CF_FREIGHT_CARRIERFORMULA(CARRIER_NAME IN VARCHAR2
                                    ,DEL_ORGANIZATION_ID IN NUMBER
                                    ,DELIVERY_ID1 IN NUMBER) RETURN CHAR;

  FUNCTION CF_SHIP_TO_COUNTRY_NAMEFORMULA(SHIP_TO_COUNTRY IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_DEL_TO_COUNTRY_NAMEFORMULA(DEL_TO_COUNTRY IN VARCHAR2) RETURN CHAR;

  FUNCTION CF_CONTACT_NAMEFORMULA(CONTACT_NAME IN VARCHAR2
                                 ,CONTACT_PHONE_NUMBER IN VARCHAR2
                                 ,DELIVERY_DETAIL_ID IN NUMBER) RETURN CHAR;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION CP_CONTACT_PHONE_P RETURN VARCHAR2;

  FUNCTION CP_ADDRESSEE_P RETURN VARCHAR2;

  FUNCTION CP_DELIVER_TO_LOCATION_ID_P RETURN NUMBER;

  FUNCTION CP_SHIP_TO_ADDRESS1_P RETURN VARCHAR2;

  FUNCTION CP_SHIP_TO_ADDRESS2_P RETURN VARCHAR2;

  FUNCTION CP_SHIP_TO_ADDRESS3_P RETURN VARCHAR2;

  FUNCTION CP_SHIP_TO_CSZ_P RETURN VARCHAR2;

  FUNCTION CP_SHIP_TO_COUNTRY_P RETURN VARCHAR2;

  FUNCTION CP_DEL_TO_ADDRESS1_P RETURN VARCHAR2;

  FUNCTION CP_DEL_TO_ADDRESS2_P RETURN VARCHAR2;

  FUNCTION CP_DEL_TO_ADDRESS3_P RETURN VARCHAR2;

  FUNCTION CP_DEL_TO_CSZ_P RETURN VARCHAR2;

  FUNCTION CP_DEL_TO_COUNTRY_P RETURN VARCHAR2;

END WSH_WSHRDLAB_XMLP_PKG;


/
