--------------------------------------------------------
--  DDL for Package WSH_CARRIER_VEHICLE_TYPES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."WSH_CARRIER_VEHICLE_TYPES_PKG" AUTHID CURRENT_USER as
/* $Header: WSHVTTHS.pls 115.0 2003/06/26 10:58:19 msutar noship $ */

TYPE CVTRecType IS RECORD(
CARRIER_ID 		NUMBER,
VEHICLE_TYPE_ID 	NUMBER,
ASSIGNED_FLAG 		VARCHAR2(1),
ATTRIBUTE_CATEGORY 	VARCHAR2(150),
ATTRIBUTE1 		VARCHAR2(150),
ATTRIBUTE2 		VARCHAR2(150),
ATTRIBUTE3 		VARCHAR2(150),
ATTRIBUTE4 		VARCHAR2(150),
ATTRIBUTE5 		VARCHAR2(150),
ATTRIBUTE6 		VARCHAR2(150),
ATTRIBUTE7 		VARCHAR2(150),
ATTRIBUTE8 		VARCHAR2(150),
ATTRIBUTE9 		VARCHAR2(150),
ATTRIBUTE10 		VARCHAR2(150),
ATTRIBUTE11 		VARCHAR2(150),
ATTRIBUTE12 		VARCHAR2(150),
ATTRIBUTE13 		VARCHAR2(150),
ATTRIBUTE14 		VARCHAR2(150),
ATTRIBUTE15 		VARCHAR2(150),
CREATION_DATE 		DATE,
CREATED_BY 		NUMBER,
LAST_UPDATE_DATE 	DATE,
LAST_UPDATED_BY 	NUMBER,
LAST_UPDATE_LOGIN 	NUMBER
);

PROCEDURE Create_Carrier_Vehicle_Type (
   P_Carrier_Vehicle_Info      IN  CVTRecType,
   X_ROWID                     OUT NOCOPY  VARCHAR2,
   X_RETURN_STATUS             OUT NOCOPY  VARCHAR2,
   X_EXCEPTION_MSG             OUT NOCOPY  VARCHAR2,
   X_POSITION                  OUT NOCOPY  NUMBER,
   X_PROCEDURE                 OUT NOCOPY  VARCHAR2,
   X_SQLERR                    OUT NOCOPY  VARCHAR2,
   X_SQL_CODE                  OUT NOCOPY  VARCHAR2 );


PROCEDURE Update_Carrier_Vehicle_Type(
   P_Carrier_Vehicle_Info          IN  CVTRecType,
   P_ROWID                         IN  VARCHAR2,
   X_RETURN_STATUS                 OUT NOCOPY  VARCHAR2,
   X_EXCEPTION_MSG                 OUT NOCOPY  VARCHAR2,
   X_PROCEDURE                     OUT NOCOPY  VARCHAR2,
   X_POSITION                      OUT NOCOPY  NUMBER,
   X_SQLERR                        OUT NOCOPY  VARCHAR2,
   X_SQL_CODE                      OUT NOCOPY  VARCHAR2 );

PROCEDURE Lock_Carrier_Vehicle_Type (
   P_Carrier_Vehicle_Info IN  CVTRecType,
   P_ROWID                IN  VARCHAR2,
   X_RETURN_STATUS        OUT NOCOPY  VARCHAR2 );

END WSH_CARRIER_VEHICLE_TYPES_PKG;

 

/
