--------------------------------------------------------
--  DDL for Package WSH_TPA_CONTAINER_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."WSH_TPA_CONTAINER_PKG" AUTHID CURRENT_USER AS
/* $Header: WSHTPCOS.pls 115.4 2003/08/12 01:28:44 lkuchibh ship $ */
--{
    --
    --
    -- =================================================================
    -- *** PLEASE DO NOT EDIT THIS FILE. ***
    -- *** THIS FILE IS ALWAYS GENERATED BY TPA GENERATE UTILITY. ***
    -- =================================================================
    --
    PROCEDURE Container_Tare_Weight_Self
      (
        p_container_instance_id        IN      NUMBER,
        p_cont_item_id                 IN      NUMBER,
        p_wt_uom                       IN      VARCHAR2,
        p_organization_id              IN      NUMBER,
        x_cont_tare_wt                 OUT     NOCOPY  NUMBER,
        x_return_status                OUT     NOCOPY  VARCHAR2
      );
    --
    --
    PROCEDURE Calc_Cont_Fill_Pc
      (
        p_container_instance_id        IN      NUMBER,
        p_update_flag                  IN      VARCHAR2,
        p_fill_pc_basis                IN      VARCHAR2,
        x_fill_percent                 OUT     NOCOPY  NUMBER,
        x_return_status                OUT     NOCOPY  VARCHAR2
      );
    --
    --
    PROCEDURE Container_Weight_Volume
      (
        p_container_instance_id        IN      NUMBER,
        p_override_flag                IN      VARCHAR2,
        x_gross_weight                 OUT     NOCOPY  NUMBER,
        x_net_weight                   OUT     NOCOPY  NUMBER,
        x_volume                       OUT     NOCOPY  NUMBER,
        p_fill_pc_flag                 IN      VARCHAR2,
        x_cont_fill_pc                 OUT     NOCOPY  NUMBER,
        x_return_status                OUT     NOCOPY  VARCHAR2,
        p_calc_wv_if_frozen            IN      VARCHAR2 DEFAULT 'Y'
      );
    --
    --
    PROCEDURE Validate_Master_Serial_Number
      (
        p_master_serial_number         IN      VARCHAR2,
        p_container_instance_id        IN      NUMBER,
        x_return_status                OUT     NOCOPY  VARCHAR2
      );
    --
    --
    PROCEDURE Estimate_Master_Containers
      (
        p_container_instance_id        IN      NUMBER,
        x_mast_cont_item_id            IN OUT  NOCOPY  NUMBER,
        p_det_cont_item_id             IN      NUMBER,
        p_organization_id              IN      NUMBER,
        x_num_cont                     IN OUT  NOCOPY  NUMBER,
        x_return_status                OUT     NOCOPY  VARCHAR2
      );
    --
    --
    PROCEDURE Estimate_Detail_Containers
      (
        p_container_instance_id        IN      NUMBER DEFAULT NULL,
        x_container_item_id            IN OUT  NOCOPY  NUMBER,
        p_delivery_detail_id           IN      NUMBER,
        p_organization_id              IN      NUMBER,
        x_num_cont                     IN OUT  NOCOPY  NUMBER,
        x_return_status                OUT     NOCOPY  VARCHAR2
      );
    --
    --
    --
--}
END WSH_TPA_CONTAINER_PKG;
--

 

/
