--------------------------------------------------------
--  DDL for Package XTR_XTRAUNCL_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."XTR_XTRAUNCL_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: XTRAUNCLS.pls 120.1 2007/12/28 12:41:48 npannamp noship $ */
  REPORT_DATE2 DATE;

  REPORT_NOS VARCHAR2(30);

  REPORT_SHORT_NAME VARCHAR2(80);

  REPORT_GROUP VARCHAR2(32767);

  VERSION_NUM NUMBER;

  USE_DEFAULTS VARCHAR2(1);

  COMP_CODE VARCHAR2(7);

  CANCEL_BY VARCHAR2(10);

  DEAL_TYPE VARCHAR2(7);

  CANCEL_FROM DATE;

  CANCEL_TO DATE;

  Z2PRODUCT VARCHAR2(100);

  Z2SUBTYPE VARCHAR2(100);

  Z2TYPE VARCHAR2(100);

  Z2CPARTY VARCHAR2(100);

  Z2CCY VARCHAR2(100);

  Z2TRANS_REF VARCHAR2(100);

  Z2DEAL_REF VARCHAR2(100);

  Z2CANCELLED_ON VARCHAR2(100);

  Z1PARAMETERS VARCHAR2(100);

  Z1COMPANY VARCHAR2(100);

  Z1CANCELLED_FROM VARCHAR2(100);

  Z1TO VARCHAR2(100);

  Z1CANCELLED_BY VARCHAR2(100);

  Z1DEAL_TYPE VARCHAR2(100);

  Z2END_OF_REPORT VARCHAR2(100);

  Z2CREATED_ON VARCHAR2(100);

  Z2CREATED_BY VARCHAR2(100);

  Z2PAGE VARCHAR2(100);

  P_COMPANY VARCHAR2(7);

  P_CANCELLED_BY VARCHAR2(10);

  P_DEAL_TYPE VARCHAR2(7);

  P_CANCELLED_FROM VARCHAR2(32767);

  P_CANCELLED_TO VARCHAR2(32767);

  P_SQL_TRACE VARCHAR2(32767);

  P_DISPLAY_DEBUG VARCHAR2(32767);

  COMP_CODE2 VARCHAR2(7);

  CANCELLED_BY2 VARCHAR2(10);

  DEAL_TYPE2 VARCHAR2(7);

  CANCEL_FROM2 DATE;

  CANCEL_TO2 DATE;

  COMPANY_NAME_HEADER VARCHAR2(80);

  REPORT_SHORT_NAME2 VARCHAR2(240);

  P_CONC_REQUEST_ID NUMBER;

  REPORT_DATE VARCHAR2(100);

  P_USER_DEAL_TYPE VARCHAR2(7);

  CP_PARA VARCHAR2(32767);
  /*added as fix*/

  P_CANCELLED_TO_T VARCHAR2(80);
  P_CANCELLED_FROM_T VARCHAR2(80);

  FUNCTION CF_SET_PARAFORMULA RETURN VARCHAR2;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION CP_PARA_P RETURN VARCHAR2;

END XTR_XTRAUNCL_XMLP_PKG;


/
