--------------------------------------------------------
--  DDL for Package XTR_XTRIGSUM_XMLP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."XTR_XTRIGSUM_XMLP_PKG" AUTHID CURRENT_USER AS
/* $Header: XTRIGSUMS.pls 120.1 2007/12/28 12:50:33 npannamp noship $ */
  INPUT_FROM_DATE DATE;

  INPUT_TO_DATE DATE;

  SEL_COMP VARCHAR2(7);

  SEL_PARTY VARCHAR2(7);

  USE_DEFAULTS VARCHAR2(40);

  REPORT_SHORT_NAME VARCHAR2(80);

  REPORT_GROUP VARCHAR2(40);

  REPORT_NOS VARCHAR2(40);

  VERSION_NUM VARCHAR2(40);

  Z1REPORT_NOS VARCHAR2(100);

  Z2DAY VARCHAR2(100);

  Z2PRIN VARCHAR2(100);

  Z2ADJUSTMENT VARCHAR2(100);

  Z2END_OF_REPORT VARCHAR2(100);

  Z2BALANCE VARCHAR2(100);

  Z2INTEREST VARCHAR2(100);

  Z2INT_RATE VARCHAR2(100);

  Z2SETTLED_ON VARCHAR2(100);

  Z1PARAMETERS VARCHAR2(100);

  Z1FOR_PERIOD VARCHAR2(100);

  Z1TO VARCHAR2(100);

  Z1COMPANY VARCHAR2(100);

  Z1INTERGROUP_PARTY VARCHAR2(100);

  Z2CURRENCY VARCHAR2(100);

  Z2INTEREST_FOR_THE_PERIOD VARCHAR2(100);

  Z2INTEREST_SETTLED VARCHAR2(100);

  Z2DATE VARCHAR2(100);

  Z2CCY VARCHAR2(100);

  Z2INTEREST_BFWD VARCHAR2(100);

  Z2INTEREST_CFWD VARCHAR2(100);

  Z2PAGE VARCHAR2(100);

  Z2REPORT VARCHAR2(100);

  Z2REQUESTED_BY VARCHAR2(100);

  Z2NOTE VARCHAR2(100);

  P_PERIOD_FROM VARCHAR2(32767);
  P_PERIOD_FROM_1 VARCHAR2(32767);

  P_PERIOD_TO VARCHAR2(32767);
  P_PERIOD_TO_1 VARCHAR2(32767);

  P_COMPANY VARCHAR2(7);

  P_INTERGROUP_PARTY VARCHAR2(7);

  P_SQL_TRACE VARCHAR2(32767);

  P_DISPLAY_DEBUG VARCHAR2(32767);

  COMPANY_NAME_HEADER VARCHAR2(80);

  PER_FROM DATE;

  PER_TO DATE;

  SEL_COMP2 VARCHAR2(7);

  SEL_PARTY2 VARCHAR2(7);

  P_CONC_REQUEST_ID NUMBER;

  REPORT_SHORT_NAME2 VARCHAR2(240);

  REPORT_DATE VARCHAR2(100);

  P_INTAMT_RUNNING NUMBER;

  P_SETAMT_RUNNING NUMBER;

  P_COMBINATION VARCHAR2(100);

  P_OLDEST_TRANSFER_DATE DATE;

  P_PREV_DAY_COUNT_TYPE VARCHAR2(1);

  P_PREV_PREV_DAY_COUNT_TYPE VARCHAR2(1);

  CP_PARA VARCHAR2(32767);

  FUNCTION CF_SET_PARAFORMULA RETURN VARCHAR2;

  FUNCTION BEFOREREPORT RETURN BOOLEAN;

  FUNCTION AFTERREPORT RETURN BOOLEAN;

  FUNCTION BEFOREPFORM RETURN BOOLEAN;

  FUNCTION AFTERPFORM RETURN BOOLEAN;

  FUNCTION CF_INT_CFFORMULA(COMP_CODE IN VARCHAR2
                           ,PTY_CODE IN VARCHAR2
                           ,CCY IN VARCHAR2
                           ,CF_INTEREST_FOR_DUMMY_REC IN NUMBER
                           ,DAY_COUNT_TYPE IN VARCHAR2
                           ,ACC_INT_BF IN NUMBER) RETURN NUMBER;

  FUNCTION FN_GET_DAYS(ANU_ST_DATE IN DATE) RETURN NUMBER;

  FUNCTION CF_INTEREST_FOR_DUMMY_RECFORMU(CF_NO_OF_DAYS IN NUMBER
                                         ,ROUNDING_FACTOR IN NUMBER
                                         ,IG_YEAR_BASIS IN VARCHAR2
                                         ,DAY_COUNT_TYPE IN VARCHAR2
                                         ,SET_DATE IN DATE
                                         ,PTY_CODE IN VARCHAR2
                                         ,COMP_CODE IN VARCHAR2
                                         ,CCY IN VARCHAR2
                                         ,PRIN_ACTION IN VARCHAR2
                                         ,CF_PRV_DAY IN DATE
                                         ,TRANS_DATE IN DATE
                                         ,BAL_BF IN NUMBER
                                         ,CF_PRV_RATE IN NUMBER
                                         ,ROUNDING_TYPE IN VARCHAR2) RETURN NUMBER;

  FUNCTION CF_NO_OF_DAYSFORMULA(N_DAYS IN NUMBER
                               ,IG_YEAR_BASIS IN VARCHAR2
                               ,DAY_COUNT_TYPE IN VARCHAR2
                               ,SET_DATE IN DATE
                               ,PTY_CODE IN VARCHAR2
                               ,COMP_CODE IN VARCHAR2
                               ,CCY IN VARCHAR2
                               ,PRIN_ACTION IN VARCHAR2
                               ,CF_PRV_DAY IN DATE
                               ,TRANS_DATE IN DATE) RETURN NUMBER;

  FUNCTION CF_PRV_DAYFORMULA(COMP_CODE IN VARCHAR2
                            ,PTY_CODE IN VARCHAR2
                            ,CCY IN VARCHAR2
                            ,TRANS_DATE IN DATE
                            ,TRANSACTION_NUMBER1 IN NUMBER) RETURN DATE;

  FUNCTION CF_PRV_RATEFORMULA(COMP_CODE IN VARCHAR2
                             ,PTY_CODE IN VARCHAR2
                             ,CCY IN VARCHAR2
                             ,TRANS_DATE IN DATE) RETURN NUMBER;

  FUNCTION BAL_BFFORMULA(COMP_CODE IN VARCHAR2
                        ,PTY_CODE IN VARCHAR2
                        ,CCY IN VARCHAR2
                        ,TRANS_DATE IN DATE) RETURN NUMBER;

  FUNCTION CP_PARA_P RETURN VARCHAR2;

END XTR_XTRIGSUM_XMLP_PKG;


/
