--------------------------------------------------------
--  DDL for Package ZX_PARTY_TAX_PROFILE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ZX_PARTY_TAX_PROFILE_PKG" AUTHID CURRENT_USER as
/* $Header: zxcptytaxprfiles.pls 120.3.12010000.2 2009/02/11 13:19:45 srajapar ship $ */

procedure INSERT_ROW (
  p_collecting_authority_flag    IN VARCHAR2,
  p_provider_type_code           IN VARCHAR2,
  p_create_awt_dists_type_code   IN VARCHAR2,
  p_create_awt_invoices_type_cod IN VARCHAR2,
  p_tax_classification_code      IN VARCHAR2,
  p_self_assess_flag             IN VARCHAR2,
  p_allow_offset_tax_flag        IN VARCHAR2,
  p_rep_registration_number      IN VARCHAR2,
  p_effective_from_use_le        IN DATE,
  p_record_type_code             IN VARCHAR2,
  p_request_id                   IN NUMBER,
  p_attribute1                   IN VARCHAR2,
  p_attribute2                   IN VARCHAR2,
  p_attribute3                   IN VARCHAR2,
  p_attribute4                   IN VARCHAR2,
  p_attribute5                   IN VARCHAR2,
  p_attribute6                   IN VARCHAR2,
  p_attribute7                   IN VARCHAR2,
  p_attribute8                   IN VARCHAR2,
  p_attribute9                   IN VARCHAR2,
  p_attribute10                  IN VARCHAR2,
  p_attribute11                  IN VARCHAR2,
  p_attribute12                  IN VARCHAR2,
  p_attribute13                  IN VARCHAR2,
  p_attribute14                  IN VARCHAR2,
  p_attribute15                  IN VARCHAR2,
  p_attribute_category           IN VARCHAR2,
  p_party_id                     IN NUMBER,
  p_program_login_id             IN NUMBER,
  p_party_type_code              IN VARCHAR2,
  p_supplier_flag                IN VARCHAR2,
  p_customer_flag                IN VARCHAR2,
  p_site_flag                    IN VARCHAR2,
  p_process_for_applicability_fl IN VARCHAR2,
  p_rounding_level_code          IN VARCHAR2,
  p_rounding_rule_code           IN VARCHAR2,
  p_withholding_start_date       IN DATE,
  p_inclusive_tax_flag           IN VARCHAR2,
  p_allow_awt_flag               IN VARCHAR2,
  p_use_le_as_subscriber_flag    IN VARCHAR2,
  p_legal_establishment_flag     IN VARCHAR2,
  p_first_party_le_flag          IN VARCHAR2,
  p_reporting_authority_flag     IN VARCHAR2,
  x_return_status               OUT NOCOPY VARCHAR2
  );

procedure INSERT_ROW (
  p_collecting_authority_flag    IN VARCHAR2,
  p_provider_type_code           IN VARCHAR2,
  p_create_awt_dists_type_code   IN VARCHAR2,
  p_create_awt_invoices_type_cod IN VARCHAR2,
  p_tax_classification_code      IN VARCHAR2,
  p_self_assess_flag             IN VARCHAR2,
  p_allow_offset_tax_flag        IN VARCHAR2,
  p_rep_registration_number      IN VARCHAR2,
  p_effective_from_use_le        IN DATE,
  p_record_type_code             IN VARCHAR2,
  p_request_id                   IN NUMBER,
  p_attribute1                   IN VARCHAR2,
  p_attribute2                   IN VARCHAR2,
  p_attribute3                   IN VARCHAR2,
  p_attribute4                   IN VARCHAR2,
  p_attribute5                   IN VARCHAR2,
  p_attribute6                   IN VARCHAR2,
  p_attribute7                   IN VARCHAR2,
  p_attribute8                   IN VARCHAR2,
  p_attribute9                   IN VARCHAR2,
  p_attribute10                  IN VARCHAR2,
  p_attribute11                  IN VARCHAR2,
  p_attribute12                  IN VARCHAR2,
  p_attribute13                  IN VARCHAR2,
  p_attribute14                  IN VARCHAR2,
  p_attribute15                  IN VARCHAR2,
  p_attribute_category           IN VARCHAR2,
  p_party_id                     IN NUMBER,
  p_program_login_id             IN NUMBER,
  p_party_type_code              IN VARCHAR2,
  p_supplier_flag                IN VARCHAR2,
  p_customer_flag                IN VARCHAR2,
  p_site_flag                    IN VARCHAR2,
  p_process_for_applicability_fl IN VARCHAR2,
  p_rounding_level_code          IN VARCHAR2,
  p_rounding_rule_code           IN VARCHAR2,
  p_withholding_start_date       IN DATE,
  p_inclusive_tax_flag           IN VARCHAR2,
  p_allow_awt_flag               IN VARCHAR2,
  p_use_le_as_subscriber_flag    IN VARCHAR2,
  p_legal_establishment_flag     IN VARCHAR2,
  p_first_party_le_flag          IN VARCHAR2,
  p_reporting_authority_flag     IN VARCHAR2,
  x_return_status               OUT NOCOPY VARCHAR2,
  p_registration_type_code       IN VARCHAR2,
  p_country_code                 IN VARCHAR2
  );


procedure UPDATE_ROW (
  p_party_tax_profile_id         IN NUMBER,
  p_collecting_authority_flag    IN VARCHAR2,
  p_provider_type_code           IN VARCHAR2,
  p_create_awt_dists_type_code   IN VARCHAR2,
  p_create_awt_invoices_type_cod IN VARCHAR2,
  p_tax_classification_code      IN VARCHAR2,
  p_self_assess_flag             IN VARCHAR2,
  p_allow_offset_tax_flag        IN VARCHAR2,
  p_rep_registration_number      IN VARCHAR2,
  p_effective_from_use_le        IN DATE,
  p_record_type_code             IN VARCHAR2,
  p_request_id                   IN NUMBER,
  p_attribute1                   IN VARCHAR2,
  p_attribute2                   IN VARCHAR2,
  p_attribute3                   IN VARCHAR2,
  p_attribute4                   IN VARCHAR2,
  p_attribute5                   IN VARCHAR2,
  p_attribute6                   IN VARCHAR2,
  p_attribute7                   IN VARCHAR2,
  p_attribute8                   IN VARCHAR2,
  p_attribute9                   IN VARCHAR2,
  p_attribute10                  IN VARCHAR2,
  p_attribute11                  IN VARCHAR2,
  p_attribute12                  IN VARCHAR2,
  p_attribute13                  IN VARCHAR2,
  p_attribute14                  IN VARCHAR2,
  p_attribute15                  IN VARCHAR2,
  p_attribute_category           IN VARCHAR2,
  p_party_id                     IN NUMBER,
  p_program_login_id             IN NUMBER,
  p_party_type_code              IN VARCHAR2,
  p_supplier_flag                IN VARCHAR2,
  p_customer_flag                IN VARCHAR2,
  p_site_flag                    IN VARCHAR2,
  p_process_for_applicability_fl IN VARCHAR2,
  p_rounding_level_code          IN VARCHAR2,
  p_rounding_rule_code           IN VARCHAR2,
  p_withholding_start_date       IN DATE,
  p_inclusive_tax_flag           IN VARCHAR2,
  p_allow_awt_flag               IN VARCHAR2,
  p_use_le_as_subscriber_flag    IN VARCHAR2,
  p_legal_establishment_flag     IN VARCHAR2,
  p_first_party_le_flag          IN VARCHAR2,
  p_reporting_authority_flag     IN VARCHAR2,
  x_return_status               OUT NOCOPY VARCHAR2
);

procedure UPDATE_ROW (
  p_party_tax_profile_id         IN NUMBER,
  p_collecting_authority_flag    IN VARCHAR2,
  p_provider_type_code           IN VARCHAR2,
  p_create_awt_dists_type_code   IN VARCHAR2,
  p_create_awt_invoices_type_cod IN VARCHAR2,
  p_tax_classification_code      IN VARCHAR2,
  p_self_assess_flag             IN VARCHAR2,
  p_allow_offset_tax_flag        IN VARCHAR2,
  p_rep_registration_number      IN VARCHAR2,
  p_effective_from_use_le        IN DATE,
  p_record_type_code             IN VARCHAR2,
  p_request_id                   IN NUMBER,
  p_attribute1                   IN VARCHAR2,
  p_attribute2                   IN VARCHAR2,
  p_attribute3                   IN VARCHAR2,
  p_attribute4                   IN VARCHAR2,
  p_attribute5                   IN VARCHAR2,
  p_attribute6                   IN VARCHAR2,
  p_attribute7                   IN VARCHAR2,
  p_attribute8                   IN VARCHAR2,
  p_attribute9                   IN VARCHAR2,
  p_attribute10                  IN VARCHAR2,
  p_attribute11                  IN VARCHAR2,
  p_attribute12                  IN VARCHAR2,
  p_attribute13                  IN VARCHAR2,
  p_attribute14                  IN VARCHAR2,
  p_attribute15                  IN VARCHAR2,
  p_attribute_category           IN VARCHAR2,
  p_party_id                     IN NUMBER,
  p_program_login_id             IN NUMBER,
  p_party_type_code              IN VARCHAR2,
  p_supplier_flag                IN VARCHAR2,
  p_customer_flag                IN VARCHAR2,
  p_site_flag                    IN VARCHAR2,
  p_process_for_applicability_fl IN VARCHAR2,
  p_rounding_level_code          IN VARCHAR2,
  p_rounding_rule_code           IN VARCHAR2,
  p_withholding_start_date       IN DATE,
  p_inclusive_tax_flag           IN VARCHAR2,
  p_allow_awt_flag               IN VARCHAR2,
  p_use_le_as_subscriber_flag    IN VARCHAR2,
  p_legal_establishment_flag     IN VARCHAR2,
  p_first_party_le_flag          IN VARCHAR2,
  p_reporting_authority_flag     IN VARCHAR2,
  x_return_status               OUT NOCOPY VARCHAR2,
  p_registration_type_code       IN VARCHAR2,
  p_country_code                 IN VARCHAR2
);

procedure DELETE_ROW (
  p_party_tax_profile_id  IN NUMBER,
  x_return_status        OUT NOCOPY VARCHAR2
  );

procedure sync_tax_reg_num (
   p_party_id       IN NUMBER
  ,p_tax_reg_num    IN VARCHAR2
  ,x_return_status OUT NOCOPY VARCHAR2
  ,x_msg_count     OUT NOCOPY NUMBER
  ,x_msg_data      OUT NOCOPY VARCHAR2
  );

end ZX_PARTY_TAX_PROFILE_PKG;

/
