--------------------------------------------------------
--  DDL for Package ZX_REPORTING_CODES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ZX_REPORTING_CODES_PKG" AUTHID CURRENT_USER as
/* $Header: zxcrepcodess.pls 120.5 2005/03/16 13:55:05 scsharma ship $ */
procedure INSERT_ROW (
  X_ROWID in out nocopy VARCHAR2,
  X_REPORTING_CODE_ID in NUMBER,
  X_REPORTING_CODE_CHAR_VALUE in VARCHAR2,
  X_REPORTING_CODE_NUM_VALUE in NUMBER,
  X_REPORTING_CODE_DATE_VALUE in DATE,
  X_REPORTING_TYPE_ID in NUMBER,
  X_EXCEPTION_CODE in VARCHAR2,
  X_EFFECTIVE_FROM in DATE,
  X_EFFECTIVE_TO in DATE,
  X_RECORD_TYPE_CODE in VARCHAR2,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_LOGIN_ID in NUMBER,
  X_REPORTING_CODE_NAME in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_PROGRAM_APPLICATION_ID in NUMBER,
  X_PROGRAM_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER );
procedure LOCK_ROW (
  X_REPORTING_CODE_ID in NUMBER,
  X_REPORTING_CODE_CHAR_VALUE in VARCHAR2,
  X_REPORTING_CODE_NUM_VALUE in NUMBER,
  X_REPORTING_CODE_DATE_VALUE in DATE,
  X_REPORTING_TYPE_ID in NUMBER,
  X_EXCEPTION_CODE in VARCHAR2,
  X_EFFECTIVE_FROM in DATE,
  X_EFFECTIVE_TO in DATE,
  X_RECORD_TYPE_CODE in VARCHAR2,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_LOGIN_ID in NUMBER,
  X_REPORTING_CODE_NAME in VARCHAR2,
  X_PROGRAM_APPLICATION_ID in NUMBER,
  X_PROGRAM_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER
);
procedure UPDATE_ROW (
  X_REPORTING_CODE_ID in NUMBER,
  X_REPORTING_CODE_CHAR_VALUE in VARCHAR2,
  X_REPORTING_CODE_NUM_VALUE in NUMBER,
  X_REPORTING_CODE_DATE_VALUE in DATE,
  X_REPORTING_TYPE_ID in NUMBER,
  X_EXCEPTION_CODE in VARCHAR2,
  X_EFFECTIVE_FROM in DATE,
  X_EFFECTIVE_TO in DATE,
  X_RECORD_TYPE_CODE in VARCHAR2,
  X_REQUEST_ID in NUMBER,
  X_PROGRAM_LOGIN_ID in NUMBER,
  X_REPORTING_CODE_NAME in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_PROGRAM_APPLICATION_ID in NUMBER,
  X_PROGRAM_ID in NUMBER,
  X_OBJECT_VERSION_NUMBER in NUMBER
  );
procedure DELETE_ROW (
  X_REPORTING_CODE_ID in NUMBER
);
procedure ADD_LANGUAGE;
end ZX_REPORTING_CODES_PKG;

 

/
