--------------------------------------------------------
--  DDL for Package ZX_TRX_DETAIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ZX_TRX_DETAIL" AUTHID CURRENT_USER AS
/* $Header: zxritsimdetails.pls 120.20.12010000.1 2008/07/28 13:37:18 appldev ship $ */


  c_lines_per_commit CONSTANT NUMBER :=
        ZX_TDS_CALC_SERVICES_PUB_PKG.G_LINES_PER_COMMIT;

  TYPE application_id_tbl IS TABLE OF
    ZX_LINES.application_id%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE entity_code_tbl IS TABLE OF
    ZX_LINES.entity_code%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE event_class_code_tbl IS TABLE OF
    ZX_LINES.event_class_code%TYPE
  INDEX BY BINARY_INTEGER;

  TYPE trx_id_tbl IS TABLE OF
    ZX_LINES.trx_id%TYPE
  INDEX BY BINARY_INTEGER;

  PROCEDURE Insert_row
       (p_Rowid                      IN OUT NOCOPY VARCHAR2,
        p_internal_organization_id     NUMBER,
        p_internal_org_location_id     NUMBER,
        p_application_id               NUMBER,
        p_entity_code                  VARCHAR2,
        p_event_class_code             VARCHAR2,
        p_event_type_code              VARCHAR2,
        p_trx_id                       NUMBER,
        p_trx_date                     DATE,
        p_trx_doc_revision             VARCHAR2,
        p_ledger_id                    NUMBER,
        p_trx_currency_code            VARCHAR2,
        p_currency_conversion_date     DATE,
        p_currency_conversion_rate     NUMBER,
        p_currency_conversion_type     VARCHAR2,
        p_minimum_accountable_unit     NUMBER,
        p_precision                    NUMBER,
        p_legal_entity_id              NUMBER,
        p_rounding_ship_to_party_id    NUMBER,
        p_rounding_ship_from_party_id  NUMBER,
        p_rounding_bill_to_party_id    NUMBER,
        p_rounding_bill_from_party_id  NUMBER,
        p_rndg_ship_to_party_site_id   NUMBER,
        p_rndg_ship_from_pty_site_id   NUMBER,  --reduced size p_rndg_ship_from_party_site_id
        p_rndg_bill_to_party_site_id   NUMBER,
        p_rndg_bill_from_pty_site_id   NUMBER,  --reduced size p_rndg_bill_from_party_site_id
        p_establishment_id             NUMBER,
        p_related_doc_application_id   NUMBER,
        p_related_doc_entity_code      VARCHAR2,
        p_related_doc_evt_class_code   VARCHAR2,  --reduced size p_related_doc_event_class_code
        p_related_doc_trx_id           NUMBER,
        p_related_doc_number           VARCHAR2,
        p_related_doc_date             DATE,
        p_default_taxation_country     VARCHAR2,
        p_quote_flag                   VARCHAR2,
        p_trx_number                   VARCHAR2,
        p_trx_description              VARCHAR2,
        p_trx_communicated_date        DATE,
        p_batch_source_id              NUMBER,
        p_batch_source_name            VARCHAR2,
        --p_doc_seq_id                   NUMBER,
        --p_doc_seq_name                 VARCHAR2,
        --p_doc_seq_value                VARCHAR2,
        p_trx_due_date                 DATE,
        p_trx_type_description         VARCHAR2,
        p_billing_trad_partner_name    VARCHAR2,  --reduced size p_billing_trading_partner_name
        p_billing_trad_partner_number  VARCHAR2,  --reduced size p_billing_trading_partner_number
        p_billing_tp_tax_report_flg    VARCHAR2,  --reduced size p_Billing_Tp_Tax_Reporting_Flag
        p_billing_tp_taxpayer_id       VARCHAR2,
        p_document_sub_type            VARCHAR2,
        p_supplier_tax_invoice_number  VARCHAR2,
        p_supplier_tax_invoice_date    DATE,--
        p_supplier_exchange_rate       NUMBER,
        p_tax_invoice_date             DATE,
        p_tax_invoice_number           VARCHAR2,
        p_tax_event_class_code         VARCHAR2,
        p_tax_event_type_code          VARCHAR2,
        p_doc_event_status             VARCHAR2,
        p_rdng_ship_to_pty_tx_prof_id  NUMBER,
        p_rdng_ship_fr_pty_tx_prof_id  NUMBER,  --reduced size p_rdng_ship_from_pty_tx_prof_id
        p_rdng_bill_to_pty_tx_prof_id  NUMBER,
        p_rdng_bill_fr_pty_tx_prof_id  NUMBER,  --reduced size p_rdng_bill_from_pty_tx_prof_id
        p_rdng_ship_to_pty_tx_p_st_id  NUMBER,
        p_rdng_ship_fr_pty_tx_p_st_id  NUMBER,  --reduced size p_rdng_ship_from_pty_tx_p_st_id
        p_rdng_bill_to_pty_tx_p_st_id  NUMBER,
        p_rdng_bill_fr_pty_tx_p_st_id  NUMBER,  --reduced size p_rdng_bill_from_pty_tx_p_st_id
        p_trx_level_type               VARCHAR2,
        p_trx_line_id                  NUMBER,
        p_line_level_action            VARCHAR2,
        p_trx_shipping_date            DATE,
        p_trx_receipt_date             DATE,
        p_trx_line_type                VARCHAR2,
        p_trx_line_date                DATE,
        p_trx_business_category        VARCHAR2,
        p_line_intended_use            VARCHAR2,
        p_user_defined_fisc_class      VARCHAR2,
        p_line_amt                     NUMBER,
        p_trx_line_quantity            NUMBER,
        p_unit_price                   NUMBER,
        p_exempt_certificate_number    VARCHAR2,
        p_exempt_reason                VARCHAR2,
        p_cash_discount                NUMBER,
        p_volume_discount              NUMBER,
        p_trading_discount             NUMBER,
        p_transfer_charge              NUMBER,
        p_transportation_charge        NUMBER,
        p_insurance_charge             NUMBER,
        p_other_charge                 NUMBER,
        p_product_id                   NUMBER,
        p_product_fisc_classification  VARCHAR2,
        p_product_org_id               NUMBER,
        p_uom_code                     VARCHAR2,
        p_product_type                 VARCHAR2,
        p_product_code                 VARCHAR2,
        p_product_category             VARCHAR2,
        p_trx_sic_code                 VARCHAR2,
        p_fob_point                    VARCHAR2,
        p_ship_to_party_id             NUMBER,
        p_ship_from_party_id           NUMBER,
        p_poa_party_id                 NUMBER,
        p_poo_party_id                 NUMBER,
        p_bill_to_party_id             NUMBER,
        p_bill_from_party_id           NUMBER,
        p_merchant_party_id            NUMBER,
        p_ship_to_party_site_id        NUMBER,
        p_ship_from_party_site_id      NUMBER,
        p_poa_party_site_id            NUMBER,
        p_poo_party_site_id            NUMBER,
        p_bill_to_party_site_id        NUMBER,
        p_bill_from_party_site_id      NUMBER,
        p_ship_to_location_id          NUMBER,
        p_ship_from_location_id        NUMBER,
        p_poa_location_id              NUMBER,
        p_poo_location_id              NUMBER,
        p_bill_to_location_id          NUMBER,
        p_bill_from_location_id        NUMBER,
        p_account_ccid                 NUMBER,
        p_account_string               VARCHAR2,
        p_merchant_party_country       VARCHAR2,
        p_ref_doc_application_id       NUMBER,
        p_ref_doc_entity_code          VARCHAR2,
        p_ref_doc_event_class_code     VARCHAR2,
        p_ref_doc_trx_id               NUMBER,
        p_ref_doc_line_id              NUMBER,
        p_ref_doc_line_quantity        NUMBER,
        p_applied_from_application_id  NUMBER,
        p_applied_from_entity_code     VARCHAR2,
        p_applied_from_evt_class_code  VARCHAR2,  --reduced size p_applied_from_event_class_code
        p_applied_from_trx_id          NUMBER,
        p_applied_from_line_id         NUMBER,
        p_adjusted_doc_application_id  NUMBER,
        p_adjusted_doc_entity_code     VARCHAR2,
        p_adj_doc_event_class_code     VARCHAR2,  --reduced size p_adjusted_doc_event_class_code
        p_adjusted_doc_trx_id          NUMBER,
        p_adjusted_doc_line_id         NUMBER,
        p_adjusted_doc_number          VARCHAR2,
        p_adjusted_doc_date            DATE,
        p_applied_to_application_id    NUMBER,
        p_applied_to_entity_code       VARCHAR2,
        p_applied_to_event_class_code  VARCHAR2,
        p_applied_to_trx_id            NUMBER,
        p_applied_to_trx_line_id       NUMBER,
        p_trx_id_level2                NUMBER,
        p_trx_id_level3                NUMBER,
        p_trx_id_level4                NUMBER,
        p_trx_id_level5                NUMBER,
        p_trx_id_level6                NUMBER,
        p_trx_line_number              NUMBER,
        p_trx_line_description         VARCHAR2,
        p_product_description          VARCHAR2,
        p_trx_waybill_number           VARCHAR2,
        p_trx_line_gl_date             DATE,
        p_merchant_party_name          VARCHAR2,
        p_merchant_party_doc_number    VARCHAR2,  --reduced size p_merchant_party_document_number
        p_merchant_party_reference     VARCHAR2,
        p_merchant_party_taxpayer_id   VARCHAR2,
        p_merchant_pty_tax_reg_number  VARCHAR2,  --reduced size p_merchant_party_tax_reg_number
        p_paying_party_id              NUMBER,
        p_own_hq_party_id              NUMBER,
        p_trading_hq_party_id          NUMBER,
        p_poi_party_id                 NUMBER,
        p_pod_party_id                 NUMBER,
        p_title_transfer_party_id      NUMBER,
        p_paying_party_site_id         NUMBER,
        p_own_hq_party_site_id         NUMBER,
        p_trading_hq_party_site_id     NUMBER,
        p_poi_party_site_id            NUMBER,
        p_pod_party_site_id            NUMBER,
        p_title_transfer_pty_site_id   NUMBER,  --reduced size p_title_transfer_party_site_id
        p_paying_location_id           NUMBER,
        p_own_hq_location_id           NUMBER,
        p_trading_hq_location_id       NUMBER,
        p_poc_location_id              NUMBER,
        p_poi_location_id              NUMBER,
        p_pod_location_id              NUMBER,
        p_title_transfer_location_id   NUMBER,
        p_banking_tp_taxpayer_id       VARCHAR2,
        p_assessable_value             NUMBER,
        p_asset_flag                   VARCHAR2,
        p_asset_number                 VARCHAR2,
        p_asset_accum_depreciation     NUMBER,
        p_asset_type                   VARCHAR2,
        p_asset_cost                   NUMBER,
        p_ship_to_party_tax_prof_id    NUMBER,
        p_ship_from_party_tax_prof_id  NUMBER,
        p_poa_party_tax_prof_id        NUMBER,
        p_poo_party_tax_prof_id        NUMBER,
        p_paying_party_tax_prof_id     NUMBER,
        p_own_hq_party_tax_prof_id     NUMBER,
        p_trading_hq_pty_tax_prof_id   NUMBER,  --reduced size p_trading_hq_party_tax_prof_id
        p_poi_party_tax_prof_id        NUMBER,
        p_pod_party_tax_prof_id        NUMBER,
        p_bill_to_party_tax_prof_id    NUMBER,
        p_bill_from_party_tax_prof_id  NUMBER,
        p_title_trans_pty_tax_prof_id  NUMBER,  --reduced size p_title_trans_party_tax_prof_id
        p_ship_to_site_tax_prof_id     NUMBER,
        p_ship_from_site_tax_prof_id   NUMBER,
        p_poa_site_tax_prof_id         NUMBER,
        p_poo_site_tax_prof_id         NUMBER,
        p_paying_site_tax_prof_id      NUMBER,
        p_own_hq_site_tax_prof_id      NUMBER,
        p_trading_hq_site_tax_prof_id  NUMBER,
        p_poi_site_tax_prof_id         NUMBER,
        p_pod_site_tax_prof_id         NUMBER,
        p_bill_to_site_tax_prof_id     NUMBER,
        p_bill_from_site_tax_prof_id   NUMBER,
        p_title_trn_site_tax_prof_id   NUMBER,  --reduced size p_title_trans_site_tax_prof_id
        p_merchant_party_tax_prof_id   NUMBER,
        p_line_amt_includes_tax_flag   VARCHAR2,
        p_historical_flag              VARCHAR2,
        p_tax_classification_code      VARCHAR2,
        p_ctrl_hdr_tx_appl_flag        VARCHAR2,
        p_ctrl_total_line_tx_amt       NUMBER,
        p_tax_regime_id                NUMBER,
        p_tax_regime_code              VARCHAR2,
        p_tax_id                       NUMBER,
        p_tax                          VARCHAR2,
        p_tax_status_id                NUMBER,
        p_tax_status_code              VARCHAR2,
        p_tax_rate_id                  NUMBER,
        p_tax_rate_code                VARCHAR2,
        p_tax_rate                     NUMBER,
        p_tax_line_amt                 NUMBER,
        p_line_class                   VARCHAR2,
        p_input_tax_classif_code      VARCHAR2,
        p_output_tax_classif_code      VARCHAR2,
        p_ref_doc_trx_level_type       VARCHAR2,
        p_applied_to_trx_level_type    VARCHAR2,
        p_applied_from_trx_level_type  VARCHAR2,
        p_adjusted_doc_trx_level_type  VARCHAR2,
        p_exemption_control_flag       VARCHAR2,
        p_exempt_reason_code           VARCHAR2,
        p_receivables_trx_type_id      NUMBER,
        p_object_version_number        NUMBER,
        p_created_by                   NUMBER,
        p_creation_date                DATE,
        p_last_updated_by              NUMBER,
        p_last_update_date             DATE,
        p_last_update_login            NUMBER);

  PROCEDURE Update_row
       (p_Rowid                        VARCHAR2,
        p_internal_organization_id     NUMBER,
        p_internal_org_location_id     NUMBER,
        p_application_id               NUMBER,
        p_entity_code                  VARCHAR2,
        p_event_class_code             VARCHAR2,
        p_event_type_code              VARCHAR2,
        p_trx_id                       NUMBER,
        p_trx_date                     DATE,
        p_trx_doc_revision             VARCHAR2,
        p_ledger_id                    NUMBER,
        p_trx_currency_code            VARCHAR2,
        p_currency_conversion_date     DATE,
        p_currency_conversion_rate     NUMBER,
        p_currency_conversion_type     VARCHAR2,
        p_minimum_accountable_unit     NUMBER,
        p_precision                    NUMBER,
        p_legal_entity_id              NUMBER,
        p_rounding_ship_to_party_id    NUMBER,
        p_rounding_ship_from_party_id  NUMBER,
        p_rounding_bill_to_party_id    NUMBER,
        p_rounding_bill_from_party_id  NUMBER,
        p_rndg_ship_to_party_site_id   NUMBER,
        p_rndg_ship_from_pty_site_id   NUMBER,  --reduced size p_rndg_ship_from_party_site_id
        p_rndg_bill_to_party_site_id   NUMBER,
        p_rndg_bill_from_pty_site_id   NUMBER,  --reduced size p_rndg_bill_from_party_site_id
        p_establishment_id             NUMBER,
        p_related_doc_application_id   NUMBER,
        p_related_doc_entity_code      VARCHAR2,
        p_related_doc_evt_class_code   VARCHAR2,  --reduced size p_related_doc_event_class_code
        p_related_doc_trx_id           NUMBER,
        p_related_doc_number           VARCHAR2,
        p_related_doc_date             DATE,
        p_default_taxation_country     VARCHAR2,
        p_quote_flag                   VARCHAR2,
        p_trx_number                   VARCHAR2,
        p_trx_description              VARCHAR2,
        p_trx_communicated_date        DATE,
        p_batch_source_id              NUMBER,
        p_batch_source_name            VARCHAR2,
        --p_doc_seq_id                   NUMBER,
        --p_doc_seq_name                 VARCHAR2,
        --p_doc_seq_value                VARCHAR2,
        p_trx_due_date                 DATE,
        p_trx_type_description         VARCHAR2,
        p_billing_trad_partner_name    VARCHAR2,  --reduced size p_billing_trading_partner_name
        p_billing_trad_partner_number  VARCHAR2,  --reduced size p_billing_trading_partner_number
        p_billing_tp_tax_report_flg    VARCHAR2,  --reduced size p_Billing_Tp_Tax_Reporting_Flag
        p_billing_tp_taxpayer_id       VARCHAR2,
        p_document_sub_type            VARCHAR2,
        p_supplier_tax_invoice_number  VARCHAR2,
        p_supplier_tax_invoice_date    DATE,
        p_supplier_exchange_rate       NUMBER,
        p_tax_invoice_date             DATE,
        p_tax_invoice_number           VARCHAR2,
        p_tax_event_class_code         VARCHAR2,
        p_tax_event_type_code          VARCHAR2,
        p_doc_event_status             VARCHAR2,
        p_rdng_ship_to_pty_tx_prof_id  NUMBER,
        p_rdng_ship_fr_pty_tx_prof_id  NUMBER,  --reduced size p_rdng_ship_from_pty_tx_prof_id
        p_rdng_bill_to_pty_tx_prof_id  NUMBER,
        p_rdng_bill_fr_pty_tx_prof_id  NUMBER,  --reduced size p_rdng_bill_from_pty_tx_prof_id
        p_rdng_ship_to_pty_tx_p_st_id  NUMBER,
        p_rdng_ship_fr_pty_tx_p_st_id  NUMBER,  --reduced size p_rdng_ship_from_pty_tx_p_st_id
        p_rdng_bill_to_pty_tx_p_st_id  NUMBER,
        p_rdng_bill_fr_pty_tx_p_st_id  NUMBER,  --reduced size p_rdng_bill_from_pty_tx_p_st_id
        p_trx_level_type               VARCHAR2,
        p_trx_line_id                  NUMBER,
        p_line_level_action            VARCHAR2,
        p_trx_shipping_date            DATE,
        p_trx_receipt_date             DATE,
        p_trx_line_type                VARCHAR2,
        p_trx_line_date                DATE,
        p_trx_business_category        VARCHAR2,
        p_line_intended_use            VARCHAR2,
        p_user_defined_fisc_class      VARCHAR2,
        p_line_amt                     NUMBER,
        p_trx_line_quantity            NUMBER,
        p_unit_price                   NUMBER,
        p_exempt_certificate_number    VARCHAR2,
        p_exempt_reason                VARCHAR2,
        p_cash_discount                NUMBER,
        p_volume_discount              NUMBER,
        p_trading_discount             NUMBER,
        p_transfer_charge              NUMBER,
        p_transportation_charge        NUMBER,
        p_insurance_charge             NUMBER,
        p_other_charge                 NUMBER,
        p_product_id                   NUMBER,
        p_product_fisc_classification  VARCHAR2,
        p_product_org_id               NUMBER,
        p_uom_code                     VARCHAR2,
        p_product_type                 VARCHAR2,
        p_product_code                 VARCHAR2,
        p_product_category             VARCHAR2,
        p_trx_sic_code                 VARCHAR2,
        p_fob_point                    VARCHAR2,
        p_ship_to_party_id             NUMBER,
        p_ship_from_party_id           NUMBER,
        p_poa_party_id                 NUMBER,
        p_poo_party_id                 NUMBER,
        p_bill_to_party_id             NUMBER,
        p_bill_from_party_id           NUMBER,
        p_merchant_party_id            NUMBER,
        p_ship_to_party_site_id        NUMBER,
        p_ship_from_party_site_id      NUMBER,
        p_poa_party_site_id            NUMBER,
        p_poo_party_site_id            NUMBER,
        p_bill_to_party_site_id        NUMBER,
        p_bill_from_party_site_id      NUMBER,
        p_ship_to_location_id          NUMBER,
        p_ship_from_location_id        NUMBER,
        p_poa_location_id              NUMBER,
        p_poo_location_id              NUMBER,
        p_bill_to_location_id          NUMBER,
        p_bill_from_location_id        NUMBER,
        p_account_ccid                 NUMBER,
        p_account_string               VARCHAR2,
        p_merchant_party_country       VARCHAR2,
        p_ref_doc_application_id       NUMBER,
        p_ref_doc_entity_code          VARCHAR2,
        p_ref_doc_event_class_code     VARCHAR2,
        p_ref_doc_trx_id               NUMBER,
        p_ref_doc_line_id              NUMBER,
        p_ref_doc_line_quantity        NUMBER,
        p_applied_from_application_id  NUMBER,
        p_applied_from_entity_code     VARCHAR2,
        p_applied_from_evt_class_code  VARCHAR2,  --reduced size p_applied_from_event_class_code
        p_applied_from_trx_id          NUMBER,
        p_applied_from_line_id         NUMBER,
        p_adjusted_doc_application_id  NUMBER,
        p_adjusted_doc_entity_code     VARCHAR2,
        p_adj_doc_event_class_code     VARCHAR2,  --reduced size p_adjusted_doc_event_class_code
        p_adjusted_doc_trx_id          NUMBER,
        p_adjusted_doc_line_id         NUMBER,
        p_adjusted_doc_number          VARCHAR2,
        p_adjusted_doc_date            DATE,
        p_applied_to_application_id    NUMBER,
        p_applied_to_entity_code       VARCHAR2,
        p_applied_to_event_class_code  VARCHAR2,
        p_applied_to_trx_id            NUMBER,
        p_applied_to_trx_line_id       NUMBER,
        p_trx_id_level2                NUMBER,
        p_trx_id_level3                NUMBER,
        p_trx_id_level4                NUMBER,
        p_trx_id_level5                NUMBER,
        p_trx_id_level6                NUMBER,
        p_trx_line_number              NUMBER,
        p_trx_line_description         VARCHAR2,
        p_product_description          VARCHAR2,
        p_trx_waybill_number           VARCHAR2,
        p_trx_line_gl_date             DATE,
        p_merchant_party_name          VARCHAR2,
        p_merchant_party_doc_number    VARCHAR2,  --reduced size p_merchant_party_document_number
        p_merchant_party_reference     VARCHAR2,
        p_merchant_party_taxpayer_id   VARCHAR2,
        p_merchant_pty_tax_reg_number  VARCHAR2,  --reduced size p_merchant_party_tax_reg_number
        p_paying_party_id              NUMBER,
        p_own_hq_party_id              NUMBER,
        p_trading_hq_party_id          NUMBER,
        p_poi_party_id                 NUMBER,
        p_pod_party_id                 NUMBER,
        p_title_transfer_party_id      NUMBER,
        p_paying_party_site_id         NUMBER,
        p_own_hq_party_site_id         NUMBER,
        p_trading_hq_party_site_id     NUMBER,
        p_poi_party_site_id            NUMBER,
        p_pod_party_site_id            NUMBER,
        p_title_transfer_pty_site_id   NUMBER,  --reduced size p_title_transfer_party_site_id
        p_paying_location_id           NUMBER,
        p_own_hq_location_id           NUMBER,
        p_trading_hq_location_id       NUMBER,
        p_poc_location_id              NUMBER,
        p_poi_location_id              NUMBER,
        p_pod_location_id              NUMBER,
        p_title_transfer_location_id   NUMBER,
        p_banking_tp_taxpayer_id       VARCHAR2,
        p_assessable_value             NUMBER,
        p_asset_flag                   VARCHAR2,
        p_asset_number                 VARCHAR2,
        p_asset_accum_depreciation     NUMBER,
        p_asset_type                   VARCHAR2,
        p_asset_cost                   NUMBER,
        p_ship_to_party_tax_prof_id    NUMBER,
        p_ship_from_party_tax_prof_id  NUMBER,
        p_poa_party_tax_prof_id        NUMBER,
        p_poo_party_tax_prof_id        NUMBER,
        p_paying_party_tax_prof_id     NUMBER,
        p_own_hq_party_tax_prof_id     NUMBER,
        p_trading_hq_pty_tax_prof_id   NUMBER,  --reduced size p_trading_hq_party_tax_prof_id
        p_poi_party_tax_prof_id        NUMBER,
        p_pod_party_tax_prof_id        NUMBER,
        p_bill_to_party_tax_prof_id    NUMBER,
        p_bill_from_party_tax_prof_id  NUMBER,
        p_title_trans_pty_tax_prof_id  NUMBER,  --reduced size p_title_trans_party_tax_prof_id
        p_ship_to_site_tax_prof_id     NUMBER,
        p_ship_from_site_tax_prof_id   NUMBER,
        p_poa_site_tax_prof_id         NUMBER,
        p_poo_site_tax_prof_id         NUMBER,
        p_paying_site_tax_prof_id      NUMBER,
        p_own_hq_site_tax_prof_id      NUMBER,
        p_trading_hq_site_tax_prof_id  NUMBER,
        p_poi_site_tax_prof_id         NUMBER,
        p_pod_site_tax_prof_id         NUMBER,
        p_bill_to_site_tax_prof_id     NUMBER,
        p_bill_from_site_tax_prof_id   NUMBER,
        p_title_trn_site_tax_prof_id   NUMBER,  --reduced size p_title_trans_site_tax_prof_id
        p_merchant_party_tax_prof_id   NUMBER,
        p_line_amt_includes_tax_flag   VARCHAR2,
        p_historical_flag              VARCHAR2,
        p_tax_classification_code      VARCHAR2,
        p_ctrl_hdr_tx_appl_flag        VARCHAR2,
        p_ctrl_total_line_tx_amt       NUMBER,
        p_tax_regime_id                NUMBER,
        p_tax_regime_code              VARCHAR2,
        p_tax_id                       NUMBER,
        p_tax                          VARCHAR2,
        p_tax_status_id                NUMBER,
        p_tax_status_code              VARCHAR2,
        p_tax_rate_id                  NUMBER,
        p_tax_rate_code                VARCHAR2,
        p_tax_rate                     NUMBER,
        p_tax_line_amt                 NUMBER,
        p_line_class                   VARCHAR2,
        p_input_tax_classif_code      VARCHAR2,
        p_output_tax_classif_code      VARCHAR2,
        p_ref_doc_trx_level_type       VARCHAR2,
        p_applied_to_trx_level_type    VARCHAR2,
        p_applied_from_trx_level_type  VARCHAR2,
        p_adjusted_doc_trx_level_type  VARCHAR2,
        p_exemption_control_flag       VARCHAR2,
        p_exempt_reason_code           VARCHAR2,
        p_receivables_trx_type_id      NUMBER,
        p_object_version_number        NUMBER,
        p_created_by                   NUMBER,
        p_creation_date                DATE,
        p_last_updated_by              NUMBER,
        p_last_update_date             DATE,
        p_last_update_login            NUMBER);

  PROCEDURE Delete_row
       (p_Rowid                        VARCHAR2,
        p_internal_organization_id     NUMBER,
        p_application_id               NUMBER,
        p_entity_code                  VARCHAR2,
        p_event_class_code             VARCHAR2,
        p_event_type_code              VARCHAR2,
        p_trx_id                       NUMBER,
        p_trx_level_type               VARCHAR2,
        p_trx_line_id                  NUMBER
        );

  PROCEDURE Lock_row
       (p_Rowid                        VARCHAR2,
        p_internal_organization_id     NUMBER,
        p_internal_org_location_id     NUMBER,
        p_application_id               NUMBER,
        p_entity_code                  VARCHAR2,
        p_event_class_code             VARCHAR2,
        p_event_type_code              VARCHAR2,
        p_trx_id                       NUMBER,
        p_trx_date                     DATE,
        p_trx_doc_revision             VARCHAR2,
        p_ledger_id                    NUMBER,
        p_trx_currency_code            VARCHAR2,
        p_currency_conversion_date     DATE,
        p_currency_conversion_rate     NUMBER,
        p_currency_conversion_type     VARCHAR2,
        p_minimum_accountable_unit     NUMBER,
        p_precision                    NUMBER,
        p_legal_entity_id              NUMBER,
        p_rounding_ship_to_party_id    NUMBER,
        p_rounding_ship_from_party_id  NUMBER,
        p_rounding_bill_to_party_id    NUMBER,
        p_rounding_bill_from_party_id  NUMBER,
        p_rndg_ship_to_party_site_id   NUMBER,
        p_rndg_ship_from_pty_site_id   NUMBER,  --reduced size p_rndg_ship_from_party_site_id
        p_rndg_bill_to_party_site_id   NUMBER,
        p_rndg_bill_from_pty_site_id   NUMBER,  --reduced size p_rndg_bill_from_party_site_id
        p_establishment_id             NUMBER,
        p_related_doc_application_id   NUMBER,
        p_related_doc_entity_code      VARCHAR2,
        p_related_doc_evt_class_code   VARCHAR2,  --reduced size p_related_doc_event_class_code
        p_related_doc_trx_id           NUMBER,
        p_related_doc_number           VARCHAR2,
        p_related_doc_date             DATE,
        p_default_taxation_country     VARCHAR2,
        p_quote_flag                   VARCHAR2,
        p_trx_number                   VARCHAR2,
        p_trx_description              VARCHAR2,
        p_trx_communicated_date        DATE,
        p_batch_source_id              NUMBER,
        p_batch_source_name            VARCHAR2,
        --p_doc_seq_id                   NUMBER,
        --p_doc_seq_name                 VARCHAR2,
        --p_doc_seq_value                VARCHAR2,
        p_trx_due_date                 DATE,
        p_trx_type_description         VARCHAR2,
        p_billing_trad_partner_name    VARCHAR2,  --reduced size p_billing_trading_partner_name
        p_billing_trad_partner_number  VARCHAR2,  --reduced size p_billing_trading_partner_number
        p_billing_tp_tax_report_flg    VARCHAR2,  --reduced size p_Billing_Tp_Tax_Reporting_Flag
        p_billing_tp_taxpayer_id       VARCHAR2,
        p_document_sub_type            VARCHAR2,
        p_supplier_tax_invoice_number  VARCHAR2,
        p_supplier_tax_invoice_date    DATE,--
        p_supplier_exchange_rate       NUMBER,
        p_tax_invoice_date             DATE,
        p_tax_invoice_number           VARCHAR2,
        p_tax_event_class_code         VARCHAR2,
        p_tax_event_type_code          VARCHAR2,
        p_doc_event_status             VARCHAR2,
        p_rdng_ship_to_pty_tx_prof_id  NUMBER,
        p_rdng_ship_fr_pty_tx_prof_id  NUMBER,  --reduced size p_rdng_ship_from_pty_tx_prof_id
        p_rdng_bill_to_pty_tx_prof_id  NUMBER,
        p_rdng_bill_fr_pty_tx_prof_id  NUMBER,  --reduced size p_rdng_bill_from_pty_tx_prof_id
        p_rdng_ship_to_pty_tx_p_st_id  NUMBER,
        p_rdng_ship_fr_pty_tx_p_st_id  NUMBER,  --reduced size p_rdng_ship_from_pty_tx_p_st_id
        p_rdng_bill_to_pty_tx_p_st_id  NUMBER,
        p_rdng_bill_fr_pty_tx_p_st_id  NUMBER,  --reduced size p_rdng_bill_from_pty_tx_p_st_id
        p_trx_level_type               VARCHAR2,
        p_trx_line_id                  NUMBER,
        p_line_level_action            VARCHAR2,
        p_trx_shipping_date            DATE,
        p_trx_receipt_date             DATE,
        p_trx_line_type                VARCHAR2,
        p_trx_line_date                DATE,
        p_trx_business_category        VARCHAR2,
        p_line_intended_use            VARCHAR2,
        p_user_defined_fisc_class      VARCHAR2,
        p_line_amt                     NUMBER,
        p_trx_line_quantity            NUMBER,
        p_unit_price                   NUMBER,
        p_exempt_certificate_number    VARCHAR2,
        p_exempt_reason                VARCHAR2,
        p_cash_discount                NUMBER,
        p_volume_discount              NUMBER,
        p_trading_discount             NUMBER,
        p_transfer_charge              NUMBER,
        p_transportation_charge        NUMBER,
        p_insurance_charge             NUMBER,
        p_other_charge                 NUMBER,
        p_product_id                   NUMBER,
        p_product_fisc_classification  VARCHAR2,
        p_product_org_id               NUMBER,
        p_uom_code                     VARCHAR2,
        p_product_type                 VARCHAR2,
        p_product_code                 VARCHAR2,
        p_product_category             VARCHAR2,
        p_trx_sic_code                 VARCHAR2,
        p_fob_point                    VARCHAR2,
        p_ship_to_party_id             NUMBER,
        p_ship_from_party_id           NUMBER,
        p_poa_party_id                 NUMBER,
        p_poo_party_id                 NUMBER,
        p_bill_to_party_id             NUMBER,
        p_bill_from_party_id           NUMBER,
        p_merchant_party_id            NUMBER,
        p_ship_to_party_site_id        NUMBER,
        p_ship_from_party_site_id      NUMBER,
        p_poa_party_site_id            NUMBER,
        p_poo_party_site_id            NUMBER,
        p_bill_to_party_site_id        NUMBER,
        p_bill_from_party_site_id      NUMBER,
        p_ship_to_location_id          NUMBER,
        p_ship_from_location_id        NUMBER,
        p_poa_location_id              NUMBER,
        p_poo_location_id              NUMBER,
        p_bill_to_location_id          NUMBER,
        p_bill_from_location_id        NUMBER,
        p_account_ccid                 NUMBER,
        p_account_string               VARCHAR2,
        p_merchant_party_country       VARCHAR2,
        p_ref_doc_application_id       NUMBER,
        p_ref_doc_entity_code          VARCHAR2,
        p_ref_doc_event_class_code     VARCHAR2,
        p_ref_doc_trx_id               NUMBER,
        p_ref_doc_line_id              NUMBER,
        p_ref_doc_line_quantity        NUMBER,
        p_applied_from_application_id  NUMBER,
        p_applied_from_entity_code     VARCHAR2,
        p_applied_from_evt_class_code  VARCHAR2,  --reduced size p_applied_from_event_class_code
        p_applied_from_trx_id          NUMBER,
        p_applied_from_line_id         NUMBER,
        p_adjusted_doc_application_id  NUMBER,
        p_adjusted_doc_entity_code     VARCHAR2,
        p_adj_doc_event_class_code     VARCHAR2,  --reduced size p_adjusted_doc_event_class_code
        p_adjusted_doc_trx_id          NUMBER,
        p_adjusted_doc_line_id         NUMBER,
        p_adjusted_doc_number          VARCHAR2,
        p_adjusted_doc_date            DATE,
        p_applied_to_application_id    NUMBER,
        p_applied_to_entity_code       VARCHAR2,
        p_applied_to_event_class_code  VARCHAR2,
        p_applied_to_trx_id            NUMBER,
        p_applied_to_trx_line_id       NUMBER,
        p_trx_id_level2                NUMBER,
        p_trx_id_level3                NUMBER,
        p_trx_id_level4                NUMBER,
        p_trx_id_level5                NUMBER,
        p_trx_id_level6                NUMBER,
        p_trx_line_number              NUMBER,
        p_trx_line_description         VARCHAR2,
        p_product_description          VARCHAR2,
        p_trx_waybill_number           VARCHAR2,
        p_trx_line_gl_date             DATE,
        p_merchant_party_name          VARCHAR2,
        p_merchant_party_doc_number    VARCHAR2,  --reduced size p_merchant_party_document_number
        p_merchant_party_reference     VARCHAR2,
        p_merchant_party_taxpayer_id   VARCHAR2,
        p_merchant_pty_tax_reg_number  VARCHAR2,  --reduced size p_merchant_party_tax_reg_number
        p_paying_party_id              NUMBER,
        p_own_hq_party_id              NUMBER,
        p_trading_hq_party_id          NUMBER,
        p_poi_party_id                 NUMBER,
        p_pod_party_id                 NUMBER,
        p_title_transfer_party_id      NUMBER,
        p_paying_party_site_id         NUMBER,
        p_own_hq_party_site_id         NUMBER,
        p_trading_hq_party_site_id     NUMBER,
        p_poi_party_site_id            NUMBER,
        p_pod_party_site_id            NUMBER,
        p_title_transfer_pty_site_id   NUMBER,  --reduced size p_title_transfer_party_site_id
        p_paying_location_id           NUMBER,
        p_own_hq_location_id           NUMBER,
        p_trading_hq_location_id       NUMBER,
        p_poc_location_id              NUMBER,
        p_poi_location_id              NUMBER,
        p_pod_location_id              NUMBER,
        p_title_transfer_location_id   NUMBER,
        p_banking_tp_taxpayer_id       VARCHAR2,
        p_assessable_value             NUMBER,
        p_asset_flag                   VARCHAR2,
        p_asset_number                 VARCHAR2,
        p_asset_accum_depreciation     NUMBER,
        p_asset_type                   VARCHAR2,
        p_asset_cost                   NUMBER,
        p_ship_to_party_tax_prof_id    NUMBER,
        p_ship_from_party_tax_prof_id  NUMBER,
        p_poa_party_tax_prof_id        NUMBER,
        p_poo_party_tax_prof_id        NUMBER,
        p_paying_party_tax_prof_id     NUMBER,
        p_own_hq_party_tax_prof_id     NUMBER,
        p_trading_hq_pty_tax_prof_id   NUMBER,  --reduced size p_trading_hq_party_tax_prof_id
        p_poi_party_tax_prof_id        NUMBER,
        p_pod_party_tax_prof_id        NUMBER,
        p_bill_to_party_tax_prof_id    NUMBER,
        p_bill_from_party_tax_prof_id  NUMBER,
        p_title_trans_pty_tax_prof_id  NUMBER,  --reduced size p_title_trans_party_tax_prof_id
        p_ship_to_site_tax_prof_id     NUMBER,
        p_ship_from_site_tax_prof_id   NUMBER,
        p_poa_site_tax_prof_id         NUMBER,
        p_poo_site_tax_prof_id         NUMBER,
        p_paying_site_tax_prof_id      NUMBER,
        p_own_hq_site_tax_prof_id      NUMBER,
        p_trading_hq_site_tax_prof_id  NUMBER,
        p_poi_site_tax_prof_id         NUMBER,
        p_pod_site_tax_prof_id         NUMBER,
        p_bill_to_site_tax_prof_id     NUMBER,
        p_bill_from_site_tax_prof_id   NUMBER,
        p_title_trn_site_tax_prof_id   NUMBER,  --reduced size p_title_trans_site_tax_prof_id
        p_merchant_party_tax_prof_id   NUMBER,
        p_line_amt_includes_tax_flag   VARCHAR2,
        p_historical_flag              VARCHAR2,
        p_tax_classification_code      VARCHAR2,
        p_ctrl_hdr_tx_appl_flag        VARCHAR2,
        p_ctrl_total_line_tx_amt       NUMBER,
        p_tax_regime_id                NUMBER,
        p_tax_regime_code              VARCHAR2,
        p_tax_id                       NUMBER,
        p_tax                          VARCHAR2,
        p_tax_status_id                NUMBER,
        p_tax_status_code              VARCHAR2,
        p_tax_rate_id                  NUMBER,
        p_tax_rate_code                VARCHAR2,
        p_tax_rate                     NUMBER,
        p_tax_line_amt                 NUMBER,
        p_line_class                   VARCHAR2,
        p_input_tax_classif_code      VARCHAR2,
        p_output_tax_classif_code      VARCHAR2,
        p_ref_doc_trx_level_type       VARCHAR2,
        p_applied_to_trx_level_type    VARCHAR2,
        p_applied_from_trx_level_type  VARCHAR2,
        p_adjusted_doc_trx_level_type  VARCHAR2,
        p_exemption_control_flag       VARCHAR2,
        p_exempt_reason_code           VARCHAR2,
        p_receivables_trx_type_id      NUMBER,
        p_object_version_number        NUMBER,
        p_created_by                   NUMBER,
        p_creation_date                DATE,
        p_last_updated_by              NUMBER,
        p_last_update_date             DATE,
        p_last_update_login            NUMBER);

  PROCEDURE Insert_Temporary_Table
       (p_application_id               NUMBER,
        p_entity_code                  VARCHAR2,
        p_event_class_code             VARCHAR2,
        p_trx_id                       NUMBER,
        p_event_type_code              VARCHAR2,
        p_ledger_id                    NUMBER,
        p_reporting_currency_code      VARCHAR2,
        p_currency_conversion_date     DATE,
        p_currency_conversion_type     VARCHAR2,
        p_currency_conversion_rate     NUMBER,
        p_minimum_accountable_unit     NUMBER,
        p_status                       VARCHAR2 DEFAULT NULL,
        p_precision                    NUMBER,
        p_line_level_action            VARCHAR2,
        x_return_status     OUT NOCOPY VARCHAR2,
        x_msg_data          OUT NOCOPY VARCHAR2);

PROCEDURE process_import_doc_with_tax
       (p_application_id              NUMBER,
        p_entity_code                 VARCHAR2,
        p_event_class_code            VARCHAR2,
        p_trx_id                      NUMBER);


/**************************
  PROCEDURE Update_Transaction_Lines
       (p_application_id               NUMBER,
        p_entity_code                  VARCHAR2,
        p_event_class_code             VARCHAR2,
        p_trx_id                       NUMBER);
*************************/

 PROCEDURE process_purge(
        p_trx_id                       NUMBER);

 PROCEDURE process_purge
   (
        errbuf                      OUT NOCOPY varchar2,
        retcode                     OUT NOCOPY number
   );

 PROCEDURE mark_reporting_only_flag(
         p_trx_id                IN    NUMBER,
         p_application_id        IN    NUMBER,
         p_entity_code           IN    VARCHAR2,
         p_event_class_code      IN    VARCHAR2,
         p_return_status         OUT NOCOPY VARCHAR2,
         p_error_buffer          OUT NOCOPY VARCHAR2,
         p_reporting_flag        IN  VARCHAR2);


END ZX_TRX_DETAIL;

/
