--------------------------------------------------------
--  DDL for Package ZX_TRX_LINE_APP_REGIMES_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS"."ZX_TRX_LINE_APP_REGIMES_PKG" AUTHID CURRENT_USER AS
/* $Header: zxiflineappregs.pls 120.1 2005/04/27 23:48:09 vsidhart ship $ */
procedure INSERT_ROW (
  X_APPLICATION_ID in NUMBER,
  X_ENTITY_CODE in VARCHAR2,
  X_EVENT_CLASS_CODE in VARCHAR2,
  X_TRX_ID in NUMBER,
  X_TRX_LINE_ID in NUMBER,
  X_TRX_LEVEL_TYPE in VARCHAR2,
  X_TAX_REGIME_ID in NUMBER,
  X_TAX_REGIME_CODE in VARCHAR2,
  X_TAX_PROVIDER_ID in NUMBER,
  X_ALLOW_TAX_CALCULATION_FLAG in VARCHAR2,
  X_PSEUDO_TAX_ONLY_LINE_FLAG in VARCHAR2,
  X_CREATION_DATE in DATE,
  X_CREATED_BY in NUMBER,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_RETURN_STATUS out nocopy VARCHAR2);


procedure UPDATE_ROW (
  X_APPLICATION_ID in NUMBER,
  X_ENTITY_CODE in VARCHAR2,
  X_EVENT_CLASS_CODE in VARCHAR2,
  X_TRX_ID in NUMBER,
  X_TRX_LINE_ID in NUMBER,
  X_TRX_LEVEL_TYPE in VARCHAR2,
  X_TAX_REGIME_ID in NUMBER,
  X_TAX_REGIME_CODE in VARCHAR2,
  X_TAX_PROVIDER_ID in NUMBER,
  X_ALLOW_TAX_CALCULATION_FLAG in VARCHAR2,
  X_PSEUDO_TAX_ONLY_LINE_FLAG in VARCHAR2,
  X_UPDATE_FLAG in VARCHAR2,
  X_LAST_UPDATE_DATE in DATE,
  X_LAST_UPDATED_BY in NUMBER,
  X_LAST_UPDATE_LOGIN in NUMBER,
  X_RETURN_STATUS out nocopy VARCHAR2
);

end ZX_TRX_LINE_APP_REGIMES_PKG;

 

/
